### PR TITLE
Fix Fibers errors

### PR DESCRIPTION
**Pull request by d-gubert**
Fixes some Fibers errors introduced by the latest Meteor update.

### CODE REVIEW

**Comment by sampaiodiego** [comment]
Does this still applies? :eyes:

**Comment by d-gubert** [comment]
well.... the changes in the code _do_ make sense 👀

**Comment by sampaiodiego** [comment]
I'm not sure what issues/errors it fixes 🙈

**Comment by sampaiodiego** [comment]
do you mind fixing the conflicts pls?

**Pull request closed without merging**
