### PR TITLE
Keep the sidenav open after clicking any channel or room

### PR DESCRIPTION
**Pull request by sumedh123**
@RocketChat/core 

Fixes https://github.com/RocketChat/Rocket.Chat/issues/9812

### CODE REVIEW

**Comment by sumedh123** [comment]
@geekgonecrazy Please review.

**Comment by geekgonecrazy** [comment]
@sumedh123 this actually isn't the desired behaviour.  The desired behavior is when you click the channel actions it stays open.  If you clicked a channel it should change and collapse like it already does.

**Comment by karlprieb** [comment]
Hey @sumedh123 thank you for your contribution, however @geekgonecrazy is right.

**Comment by geekgonecrazy** [comment]
If you could adjust to fix the actual issue showed in the gif on the original issue please feel free to.

**Comment by sumedh123** [comment]
Yes will do that.

**Pull request closed without merging**
