### PR TITLE
[IMPROVE] Support markdown on App's Description

### PR DESCRIPTION
**Pull request by murtaza98**
## Proposed changes (including videos or screenshots)

Supporting markdown on 2 places:
1. App Details page
2. App List page

## Issue(s)

Before:
image
image

After: 
image
image

### CODE REVIEW

**Comment by graywolf336** [comment]
We actually do not support Markdown in App descriptions, so in theory this is not a bug but an enhancement. Let's not merge this yet as there's more we need to consider with supporting Markdown than just links. 😬

**Comment by vmarinogg** [comment]
We are now working to allow Markdown in the Description and Release Updates fields. But we will not support Links and Images through the Markdown. This will open a lot of risks such as publishers providing scam links and images that could break the UI we are designing. 

We will have the Sliders to properly input images and a specific Documentation link will be provided later as well in the New UI we are developing.

FYI: @murtaza98 @renatobecker

**Comment by murtaza98** [comment]
Alright, @vmarinogg @graywolf336. Looking forward to the new UI :smile:

**Comment by graywolf336** [comment]
I'm going to go ahead and close this PR since the feature set it adds will be coming in the near future.

**Pull request closed without merging**
