### PR TITLE
[FIX] Enabling `Collapse Embedded Media by Default` was hiding replies and quotes

### LINKED ISSUE #10424: "Collapse Embedded Media by Default" Preference Breaks Relplies
### Description:

When the user preference `Collapse Embedded Media by Default` it makes text attachments closed, with no way to open it.

screen shot 2018-04-11 at 11 30 16 am

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Tested on open server

### PR DESCRIPTION
**Pull request by c0dzilla**
Closes #10424 

Enabling the setting "Collapse Embedded Media by Default" was hiding replies and quotes as well. This pr fixes this.

image

### CODE REVIEW

**Comment by c0dzilla** [comment]
@theorenck please review. Thanks :)

**Comment by c0dzilla** [comment]
@karlprieb I've made the change. Please have a look :)

**Comment by c0dzilla** [comment]
@karlprieb I'd be grateful if this is reviewed :relaxed:

**Comment by karlprieb** [comment]
@c0dzilla Your solution is still hiding the attachments and not collapsing them

**Pull request merged**
