### PR TITLE
[FIX] No pattern for user's status text capitalization

### PR DESCRIPTION
**Pull request by sumedh123**
@RocketChat/core 

Closes https://github.com/RocketChat/Rocket.Chat/issues/9547

screen shot 2018-02-20 at 5 12 18 pm

### CODE REVIEW

**Comment by sumedh123** [comment]
@rafaelks @JSzaszvari Please review.

**Comment by karlprieb** [comment]
@sumedh123 can't we do that using only CSS?

@engelgabriel do we want that? I really don't see the problem with lowercase on that case.

**Comment by engelgabriel** [comment]
@karlprieb yes, IF we do it, should be ONLY css, but I don't think we should force this here, we should just fix the translation files and make sure we are using the same string in all places.

**Comment by sumedh123** [comment]
@karlprieb @engelgabriel Should I try this with CSS only or do we follow any other approach?

**Comment by graywolf336** [comment]
@sumedh123 As Gabriel said, change the i18n setup so that it's all the same and using the same string in every place.

**Comment by karlprieb** [comment]
But we really want that? I think it's better to be lowercase. What you guys think? @RocketChat/core

**Comment by rafaelks** [comment]
@karlprieb I prefer all status in lowercase (in all places).

**Comment by geekgonecrazy** [comment]
Yeah I think visually it looks good

**Comment by sumedh123** [comment]
@karlprieb @geekgonecrazy Please review.

**Comment by sumedh123** [comment]
@karlprieb Done 👍 Please review again. Thanks.

**Pull request merged**
