### PR TITLE
[NEW] Unify unread and mentions badge

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

image

### CODE REVIEW

**Comment by ggazzo** [comment]
don't do that =/

 is the number `1` relative to quantity of mentions? or just `mentions|unread`? ugly and confuse =/

**Comment by marceloschmidt** [comment]
Why not use what we had before: filled box or transparent backgound?


--
Marcelo Schmidt

**Comment by engelgabriel** [comment]
The current way takes far too much space. 

image

We can move to old way (filled box or transparent background) but this PR is already an improvement.

@rodrigok please merge this and we can make another PR with the final version.

**Comment by ggazzo** [comment]
This situation is just on the hover. I dont think this "small/confuse" is
better. But...

**Comment by engelgabriel** [comment]
@ggazzo you can do the PR for the old "filled box or transparent background" if your are so disappointed 😉

**Pull request merged**
