### PR TITLE
Allow SMTP server with no login - closes #1883

### LINKED ISSUE #1883: Accept SMTP server with no logins
I have postfix running on localhost port 25. 

In Rocket.Chat /admin/SMTP I have localhost, port 25, no user or password and rocketchat@MYDOMAIN.example.com. 
In /admin/users in the top right, if I click on the + symbol to add a user, it says "In order to send invitation emails you first must configure SMTP settings".

When I choose to send a test email, I get a popup saying, "Success! An email was sent to me@MYDOMAIN.example.com" but an email never arrives. How do I debug this? Nothing seems to hit my postfix mail.log. 

Also, what is the purpose of /mailer, there doesn't seem to be an option to save settings there.

### PR DESCRIPTION
**Pull request by fduraibi**
Only require smtp host to be present. And include username and password if they are provided.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
That was quick :+1: 

LGTM

**Comment by pescobar** [comment]
maybe this PR also fixes this issue?  https://github.com/RocketChat/Rocket.Chat/issues/1901

**Comment by sampaiodiego** [comment]
lgtm

**Comment by sampaiodiego** [comment]
seems that it will fix your issue @pescobar :wink:

**Pull request merged**
