### PR TITLE
[NEW] Announcement bar color wasn't using color from theming variables

### PR DESCRIPTION
**Pull request by cyclops24**
This PR read `color` and `background-color` for `announcement-bar` from color setting.

### CODE REVIEW

**Comment by rodrigok** [comment]
@cyclops24 could you post screen shots of what it looks before and now?

Thanks

**Comment by cyclops24** [comment]
@rodrigok Before we can't change `announcement-bar` style from admin and color's setting but now we can do in by change `Admin > Layout > Old Colors > Primary Background Color` (for background-color) and `Admin > Layout > Colors > Content` (for color).

For example before:

And now:

**Comment by rodrigok** [comment]
So, the idea is to keep the primary base color to the announcement bar? @karlprieb @ggazzo what do you think?

**Comment by cyclops24** [comment]
Yes @rodrigok I think it's better.

**Pull request merged**
