### PR TITLE
fix: mentions and emojis inside bold, italic and strikethrough

### LINKED ISSUE #27838: Unicode emojis look different when inside bold text
### Description:

When putting a unicode emoji somewhere into bold text, it looks differently. This does not affect emojis created using their code (they are not rendered inside bold text at all).

### Steps to reproduce:

1. Write the message `🌈*🌈*`.

### Expected behavior:

image

### Actual behavior:

image

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Deployment Method: Docker
- MongoDB Version: 5.0.14

### Client Setup Information

Issue is browser and operating system agnostic.

### Additional context

This at least happens with italics as well.

Using the browser's development tools, it can be seen that a unicode emoji outside bold text gets replaced by an image from https://github.com/RocketChat/Rocket.Chat/tree/develop/apps/meteor/public/packages/emojione, while the emoji inside bold text doesn't.

### LINKED ISSUE #27839: Emojis not rendered inside bold text
### Description:

When writing bold text, emojis created by their name cannot be used.

### Steps to reproduce:

1. Write the message `:family_mmbb: *:family_mmbb:*`.

### Expected behavior:

image

### Actual behavior:

image

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Deployment Method: Docker
- MongoDB Version: 5.0.14

### Client Setup Information

Issue is browser and operating system agnostic.

### Additional context

This at least happens for italics as well.

### LINKED ISSUE #28843: Unable to highlight users in bold text and italics
### Description:

When formatting text in bold face or italics, users will not be highlighted.

### Steps to reproduce:

1. Compose a message highlighting some user.
2. Before submitting the message, format the message in bold face or italics.
3. Submit the message.

### Expected behavior:

The user will be highlighted.

### Actual behavior:

The user is not highlighted.

image

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.5

### Client Setup Information

Issue is client-agnostic.

### Additional context

This also affects messages composed using `/me` as these messages are automatically formatted in italics.

### PR DESCRIPTION
**Pull request by jayesh-jain252**
## Proposed changes (including videos or screenshots)

Mentions and emojis are not displayed when they are inside bold, italic or strikethrough.

Also modified message-parser package in RocketChat/fuselage. PR: https://github.com/RocketChat/fuselage/pull/1035

Before:

[mention_emoji_inside_markup_before.webm](https://github.com/RocketChat/Rocket.Chat/assets/79307894/730a34d1-7262-497e-8c01-f44f35d6e612)

After:

[mention_emoji_inside_markup_after.webm](https://github.com/RocketChat/Rocket.Chat/assets/79307894/c2fedf6c-7267-496e-be71-e0079bc48fca)

## Issue(s)

Closes #27838
Closes #27839
Closes #28843

### CODE REVIEW

**Comment by jayesh-jain252** [comment]
> can you check the CI errors? Thanks

Sure, Checking errors

**Comment by jayesh-jain252** [comment]
Now supports Emojis when wrapped in markup in ChatTranscript pdf
Before emojis were not shown when wrapped in markup

E.g. For Conversation

image

Before

image

After

image

**Comment by jayesh-jain252** [comment]
@hugocostadev Thanks for pointing out the CI errors! Tried resolving them. Let me know if you have any further feedback.

**Comment by hugocostadev** [comment]
Thank you @jayesh-jain252 , you did an amazing and meaningful contribution 🚀 🥳  

 Let's see if the CI will pass

**Review by hugocostadev — APPROVED** [review]

**Comment by jayesh-jain252** [comment]
> Thank you @jayesh-jain252 , you did an amazing and meaningful contribution 🚀 🥳
> 
I'm glad I could make a meaningful contribution! Thanks for the recognition @hugocostadev! 🚀🎉

**Review by hugocostadev — APPROVED** [review]
All good code wise... Sending to the QA team,
Thanks a lot ! 🚀

**Review by tassoevan — CHANGES_REQUESTED** [review]
I'm not sure if it's OK to break wrapping inline elements (e.g. `<x><y>lorem</y></x> <x><z>ipsum</z></x>` instead of `<x><y>lorem</y> <z>ipsum</z></x>`). My gut feeling is that it damages a11y a little bit.

**Comment by jayesh-jain252** [comment]
Hey @tassoevan, thanks for raising the accessibility concern! We decided to display `<x><y>lorem</y></x> <z>ipsum</z>` to prevent mixing emphasis and mentions together.

With the current solution, the HTML structure for a message like `*hello @jayesh.jain*` looks like this:
```
<div>
  <strong>hello</strong> 
  <span class="......" title="....." data-uid=".....">jayesh.jain</span>
</div>
```
This structure is the same as that of a message like `*hello* @jayesh.jain`, following the existing inline standards.

I believe that our solution follows HTML and a11y standards. If I've misunderstood your concerns or if you have any further suggestions, do let me know.😄

**Review by hugocostadev — APPROVED** [review]

**Review by tassoevan — APPROVED** [review]

**Pull request merged**
