### PR TITLE
[NEW] Adds settings to limit chain of quotes

### LINKED ISSUE #7192: Endless chain of replies to messages should be disabled or limited.  Causes server crash.
Rocket.Chat Version: 0.56
Running Instances: 
DB Replicaset OpLog:
Node Version:

 Endless chains of replies  causes crashing.  When a user replies to a reply to a reply such as the image shown below, the entire server begins to lag and slow very badly.    There should be a limit to the number of replies a message can be replied to.  This will be a way RC chat rooms can be abused. 

screen shot 2017-06-08 at 12 04 09 am

### PR DESCRIPTION
**Pull request by gdelavald**
@RocketChat/core 

Closes #7192

Adds a setting to limit the number of chained quoted messages
captura de tela 2017-06-16 as 15 48 42

The default limit is set to 2 but can be configured under Settings > Messages
captura de tela 2017-06-16 as 16 16 00

Also created a migration step to update past messages with excessive number of quotes, will update the PR to add it after @sampaiodiego's tests.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Should we actually add a migration?  It will require looking through every message right?  won't this be pretty time consuming to look through every message and walk through its attachments?

**Comment by gdelavald** [comment]
@geekgonecrazy we search for every message with N levels of attachments, so yes, it should be quite time consuming for instances with lots of messages. The objective of the migration would be to fix older messages that are already breaking the server, but this could be accomplished simply by providing a script which could be run to fix those messages by those who need it.

**Comment by gdelavald** [comment]
I did some refactoring and now the solutions uses a recursive function to go through all attachments in the message (previously it was fixing only the first one).
Also created a gist with a solution to fix previous messages https://gist.github.com/gdelavald/de47a82021fcfd5f340fa7d0f1c3ae7c

**Comment by pokapow** [comment]
Escuse me but how to active it definitivly on my rocket instance ? Could you explain step by step how to upgrade this in code @gdelavald  ? I'm using docker install

**Pull request merged**
