### PR TITLE
[FIX] Non admin cannot add custom avatar to group

### PR DESCRIPTION
**Pull request by FelipeParreira**
## Proposed changes

Allow non-admins to change room avatar.

## Issue(s)

[#18894](https://github.com/RocketChat/Rocket.Chat/issues/18894)

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] I have added necessary documentation (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules

## Changelog

Allow non-admins to change room avatar.

### CODE REVIEW

**Review by pierre-lehnen-rc — CHANGES_REQUESTED** [review]
This change is causing avatars to not be resized even when the setting is on.

**Comment by sandrotanner** [comment]
@pierre-lehnen-rc well only if it is a room avatar. Since the option for resizing avatars is under "Accounts" it makes sense that it only applies to Accounts.

But yes, the whole avatar system should probably be cleaned  out a bit. This PR would work, but it would make this part of the codebase even more messy.
I think the logic for weather it is a room avatar or a user avatar should happen further up.

Sadly I don't know Meteor...

**Comment by sandrotanner** [comment]
I am confused.This is in the Project https://github.com/RocketChat/Rocket.Chat/projects/54#card-45883577 but 3.7.0 has been released now and this is apparently not in it...

**Comment by klepptor** [comment]
Yes, unfornunatly still not fixed in 3.7.0:

I20200929-10:57:49.543(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setRoomAvatar.js:34:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

Wouldn't it make sense to fix already released features rather then releasing another bunch of new features every 4 weeks with new bugs??

**Comment by juzser** [comment]
Still happened on 3.7.1.

**Comment by sandrotanner** [comment]
Thank you @pierre-lehnen-rc!


Does anybody know when this might be in a stable release?

**Review by sampaiodiego — APPROVED** [review]

**Comment by sandrotanner** [comment]
Thx @sampaiodiego

**Pull request merged**
