### PR TITLE
i18n: Update Hungarian translation

### PR DESCRIPTION
**Pull request by urbalazs**
**100% completed Hungarian translation** translated by [Kinga Kiss](https://kisskinga.hu/) and reviewed by [me](https://github.com/urbalazs/).

The existing Hungarian translation has been machine-translated and most of the messages are absolutely useless. This new translation is made and reviewed by native Hungarian-speaking humans and it was donated by the Hungarian [Free Software Foundation](https://fsf.hu/) with €850. Thanks to this donation, Rocket.Chat is now fully translated into Hungarian.

I created this pull request because LingoHub does not support file uploading and I would not like to copy-paste 5.5k messages.

### CODE REVIEW

**Comment by urbalazs** [comment]
Any news about this PR? Please merge it to avoid overwriting the human translations with machine translating. Thanks!

**Comment by jeanfbrito** [comment]
@dudanogueira

**Comment by dudanogueira** [comment]
hi @urbalazs Thanks for this contribution! We really appreciate it! 

I asked our team to check it out.  This PR will probably get merged and released with our next version.

Considering you also provided translations for the Electron App (thanks there too!!!) We also have some more projects that could benefit from your expertise :grimacing: 
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/i18n/locales/hu.json
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/livechat/src/i18n/hu.json

let me know if you need any assistance for further contributions!

Thanks!!

**Comment by urbalazs** [comment]
@dudanogueira any news about this PR?

**Comment by dudanogueira** [comment]
Hi! Not yet. My friend and colleague that will handle this is in PTO, and should get back next week.

I asked her to handle this ASAP!

**Pull request merged**
