### PR TITLE
Bot autocomplete

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Referring to #1086

Dependent on: https://github.com/RocketChat/hubot-rocketchat/pull/71

This will add the ability to auto complete bot commands.

This is very much in progress.

DON'T MERGE

### CODE REVIEW

**Comment by marceloschmidt** [comment]
Hey @geekgonecrazy can you tell us where this stopped at? Can I do anything to make this real? Thanks!

**Comment by geekgonecrazy** [comment]
@marceloschmidt I left off at the point where I need to drop the commands in a collection, and pull from there.  Then when the commands are sent over again by the bot starting up, it needs to update the collection.

**Comment by geekgonecrazy** [comment]
Closing this for now.  I'll re-open after i've had a chance to refactor it.

**Comment by mfilotto** [comment]
Hi @geekgonecrazy any progress on this one ?

**Comment by geekgonecrazy** [comment]
Not working on this currently.  We have some changes coming that are needed for this, might resume after those

**Pull request closed without merging**
