### PR TITLE
Corresponding to Japanese

### PR DESCRIPTION
**Pull request by aokutemaruino**
I translated ja.i18n.json.
If you merge it, I am glad.

Note
* Some sentences paraphrase it. Because the meaning of the original makes a sentence to come, I change some expressions. However, my understanding may be wrong.
* Because a sentence is mixed up when I translate it into Japanese, I do not translate it.
* There are "login_with" two. This thinks that it is a mistake. I translated all two of them.

### CODE REVIEW

**Comment by engelgabriel** [comment]
Can you tells us which ones were harder to understand? Maybe we can explain them better?

**Comment by aokutemaruino** [comment]
Most of the cause is my English skills. Therefore, it is even difficult to write this sentence :l
Therefore I hope that somebody with the English skill transfers it to a good sentence than me.
Description of the top page has been difficult for me.
* "Follow_social_profiles"
* "Have_your_own_chat"
* "Proudly_developed"
* "Loading_suggestion"


Another cause is difference in grammar.
A noun sometimes moves in the front or the next.
For example, I think that the "Welcome_to_the" key is used as follows.
English: `"Welcome to the AAA"`
Japanese: `"AAA へようこそ"`
* "Welcome_to_the"
* "Created_at"


The last reason does not understand a use case.
How do you differentiate? 
* "are_also_typing"
* "are_typing"
* "is_also_typing"
* "is_typing"

Count of message?
* "Msgs"
* "n_messages"


Translation is difficult work. To collect many opinions; of services such as Transifex can use it. The open source project is available free of charge. I think that there is room for the examination. It seems to use a big project.

**Comment by engelgabriel** [comment]
@marceloschmidt can you give some feedback here? Maybe add an explanation directly on Lingohub

**Comment by marceloschmidt** [comment]
Hey @aokutemaruino, let me try to explain the context of each phrase, and maybe you can think of something to replace this with, whatever makes more sense in Japanese:

"Follow_social_profiles": this is a sentence commonly seen in product webpages or personal webpages, when there are multiple accounts for that product or page, such as Facebook, Twitter, Google Plus, etc. This phrase means that we want the person accessing the app to check out our profiles on those services.

"Have_your_own_chat": is an inviting phrase for people to host their own version of rocket.chat.

Please ignore "Proudly_developed as it is not used anymore.

"Loading_suggestion": this is a message displayed briefly while waiting for suggestions to show up. For example, when you try to change your avatar, we search for a picture of you on different services (facebook, twitter, etc.). While we are searching, this message will appear, informing the user that we are waiting for suggestions to show up.

Please ignore "Welcome_to_the" and "Created_at" as it is not used anymore. *If there are other phrases where the noun is moved to the front and the phrase becomes untranslatable, let us know so that we can make them translatable by adding placeholders to it.*

"are_also_typing" will show up when there is more than one person typing in a room, and you are typing too.
"are_typing" will show up when there is more than one person typing in a room, but you are not typing.

"is_also_typing" will show up when you are typing in a room and there is only one other person typing too.

"is_typing" will show up when there's only one person typing in a room (but not you).

"Msgs" is an abbreviation for "Messages". It is *not* the count of messages, but the word message in the plural, abbreviated. If there's no abbreviation for message in Japanese, it's ok to use the full word representing "Messages" (with capital M)

"n_messages" is a count of messages, as in "10 messages" or "15 messages". Here we use a %s as a placeholder for the number. So, if in Japanese the number comes after the message, you'd translate as "messages %s". If the number comes before, it is "%s messages". 

Let me know if you have any other questions regarding this.

**Pull request merged**
