### PR TITLE
/kick command and button for kicking users from room

### PR DESCRIPTION
**Pull request by marceloschmidt**

### CODE REVIEW

**Comment by marceloschmidt** [comment]
Closes #168

**Comment by engelgabriel** [comment]
lgtm

**Comment by graywolf336** [comment]
This spurred a thought in my head, we should probably start including descriptions on the permissions so that people can see what a permission is used for instead of just guessing based on the name.

**Comment by geekgonecrazy** [comment]
lgtm (though might not hurt to notify telling them they've been kicked.  :) )

**Comment by engelgabriel** [comment]
I agree with @geekgonecrazy, lets ask @marceloschmidt to add that later.

**Comment by sampaiodiego** [comment]
yes @graywolf336 .. I already talked to @engelgabriel about that (permissions' description) .. we'll do that someday :wink:

**Pull request merged**
