### PR TITLE
[FIX] Fix #7992

### LINKED ISSUE #7992: [BUG] [Redesign] Side menu close button have small buggy overlap on user info tab
It's a little misalign on user info tab. See this:
close overlap

### PR DESCRIPTION
**Pull request by cyclops24**
@RocketChat/core 

Closes #7992

### CODE REVIEW

**Comment by gdelavald** [comment]
@cyclops24 Thanks for the PR, but we had a different approach in mind. I will close this but please do continue to look into issues.

**Comment by cyclops24** [comment]
@gdelavald It's OK but, what approach you prefer to solve this issue?
Maybe I can help about it.

**Comment by cyclops24** [comment]
@engelgabriel ?

**Comment by engelgabriel** [comment]
@cyclops24 you can see our new design concepts at https://projects.invisionapp.com/d/main#/projects/prototypes/11275326

**Comment by cyclops24** [comment]
@engelgabriel we can't see this without permission. Please put it somewhere public (and add url to readme file) so people like me can see and send PR based on that. :wink:

**Comment by engelgabriel** [comment]
https://invis.io/TKC46XUZB

**Pull request closed without merging**
