### PR TITLE
[FIX] Archived channels reappearing permanently

### LINKED ISSUE #20065: Archived channels reappearing permanently
### Description:

The channels list is not consistent across user experiences, and archived channels appear when they should not.

### Steps to reproduce:

1. Be in a room with 2 people.
2. User A archives the room.
3. On User B's screen, it is now gone. (Though they are still in the room in the main panel, this is not necessary.)
4. User B can either refresh, navigate to another room and press back, or put the full URL for the room in the location bar.
5. User has loaded archived room, and it reappears in sidebar. Refreshing and loading a different room does not remove the room. You have to re-archive it.

### Expected behavior:

Room never appears in sidebar.

### Actual behavior:

Room reappears and stays in sidebar.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: ContainerOS
- Deployment Method: Docker
- Number of Running Instances: Scalable
- DB Replicaset Oplog: -
- NodeJS Version: 14
- MongoDB Version: Atlas

### Client Setup Information

- Desktop App or Browser Version: Any
- Operating System: Any

### Additional context

None

### Relevant logs:

None

### PR DESCRIPTION
**Pull request by im-adithya**
## Proposed changes (including videos or screenshots)
I have included a check for archived in useEffect in the room list generator which was missing earlier.

## Issue(s)

 This PR closes #20065

## Earlier
https://user-images.githubusercontent.com/64399555/106130968-1757ab00-6188-11eb-8d05-93f647b06457.mp4

## Now
https://user-images.githubusercontent.com/64399555/106130977-19ba0500-6188-11eb-967c-3e5a67cb00bf.mp4

### CODE REVIEW

**Comment by im-adithya** [comment]
@gabriellsh @ggazzo @dougfabris Can anyone please review this? :D

**Comment by im-adithya** [comment]
Can anyone please review this...?

**Review by gabriellsh — CHANGES_REQUESTED** [review]
Build and test failed. I think it's some TS stuff. Can you check? thanks.

**Comment by im-adithya** [comment]
Done! Please review it :)

**Comment by dougfabris** [comment]
> Done! Please review it :)

Still failing, please make sure to check if there are any ts or lint errors

**Comment by im-adithya** [comment]
> > Done! Please review it :)
> 
> Still failing, please make sure to check if there are any ts or lint errors

The code which I have changed isn't causing the fail, it is some regex error (please see files changed section)
How do I correct this?

**Review by ggazzo — APPROVED** [review]

**Pull request merged**
