### PR TITLE
fix null ptr in loadhistory #787

### PR DESCRIPTION
**Pull request by Sing-Li**
at least fixes the exception

### CODE REVIEW

**Comment by graywolf336** [comment]
Heh, you beat me to it as I was just committing the code. :+1:

**Comment by Sing-Li** [comment]
Sorry. That exception was bugging me for a while.  When you pointed out the exact event that caused it to happen (so it is possible to test the fix) ... I can't hold back any longer :grin:

**Comment by graywolf336** [comment]
No worries at all! This does fix the "Start of conversation" not being shown, so it will really fix #787 when this is merged.

**Comment by Sing-Li** [comment]
Great!   Btw - are you getting that npm.shrinkwrap...  file modified and messing up your commits?    I think it has something to do with our quick SAML impl, but couldn't quite finger it yet.

**Comment by graywolf336** [comment]
Not sure what you mean by that...

**Comment by geekgonecrazy** [comment]
@sing-li I get that all the time when switching branches.  It's super annoying.  Not sure why the permissions get screwed up on it.  @rodrigok mentioned yanking it if possible

**Comment by Sing-Li** [comment]
@graywolf336  it is an extra file, that cannot be `.gitignored` but is generated everytime you have RC running (for example, to test the fix you just made) , and ends up being a placebo part of your commit (and PR sometimes ;-) )

**Pull request merged**
