### PR TITLE
[NEW] Rest API endpoints to list, get, and run commands

### PR DESCRIPTION
**Pull request by graywolf336**
Also, includes a nice client utility to use the rest api.

`RocketChat.API.v1.get('info').then((result) => console.log(result));`

### CODE REVIEW

**Comment by graywolf336** [comment]
@rodrigok status update on this? We talked about this pull request two Fridays ago but I've yet to hear anything regarding this.

**Comment by rafaelks** [comment]
We need to merge this one guys.

**Comment by geekgonecrazy** [comment]
Looks solid to me. Not going to break anything and works as intended will help out mobile guys. 

Merging :+1:

**Comment by cardoso** [comment]
@RocketChat/core do we also have a Real-Time method to get the changes?

**Comment by sampaiodiego** [comment]
@cardoso by changes you mean like new commands? since there is no way to add new commands at run time (at least before rocket.chat apps go live), there is no need for such real-time updates.

**Comment by graywolf336** [comment]
@cardoso now that rocket.chat apps is merged there is a real time listener to listen for updates of commands, although that only is enabled if the rocket.chat apps system is enabled.

**Pull request merged**
