### PR TITLE
[FIX] Remove deprecated permissions api endpoint

### PR DESCRIPTION
**Pull request by kaiiiiiiiii**
> The endpoint "permissions" is deprecated and will be removed after version v0.69

Cheers,
Kai

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@RocketChat/android @RocketChat/ios I don't think you guys are using this.  But as typical heads up.  Since we did schedule to be deprecated

**Comment by rafaelks** [comment]
@geekgonecrazy @kaiiiiiiiii Wow, thanks for the heads up! Yes, we **are** using it! What API should we use?

**Comment by MarcosSpessatto** [comment]
@rafaelks you should use `permissions.list`, it was renamed.

**Comment by sampaiodiego** [comment]
I'll add this to `0.72` milestone so we don't forgot to merge.

@rafaelks can you update apps before that? it's a very small change, the response is now within `permissions` field, [see docs](https://rocket.chat/docs/developer-guides/rest-api/permissions/list/)

**Comment by rafaelks** [comment]
@sampaiodiego If `0.72` is the next version, I would say let's wait until `0.73` because we still need to ship new versions of the mobile apps with this changes. Is there any rush to merge this before that?

**Comment by rafaelks** [comment]
Guys, can we hold on this change to `0.74`? iOS and Android still haven't released this change to the store (iOS is done already but not released and Android is on the schedule to do it).

**Comment by MarcosSpessatto** [comment]
@rafaelks I needed to change the endpoint again, so I ended up deprecating `permissions.list`. When you are switching to the new endpoint, please switch to `permissions.listAll`. The reason for this new change is described [in this issue](https://github.com/RocketChat/Rocket.Chat/issues/12730). I already added the new endpoint in  the docs along with the new deprecation notice.([Docs](https://github.com/RocketChat/docs/pull/1005)). Thanks.

**Pull request closed without merging**
