### PR TITLE
[NEW] Add admin and user setting for notifications

### LINKED ISSUE #3862: Set default setting for notifications
Your Rocket.Chat version: 0.35

Allow user or admin to set a default setting for notifications. Currently it says 

> Mentions (default)

 but it doesn't seem possible to change this.
image

For our team, most channels don't get too many messages in, so it is fine to receive notifications for all channels, otherwise we end up missing them. It's annoying having to change the setting for every channel.

### LINKED ISSUE #5867: [Q] How to change the default settings for channel notifications?
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: 4.5

Each channel has a mobile & desktop notification settings.
The default value is "mentions".

However, I would like to our server's default to "All messages".
How can I do this?
I do not want to change every new channel I create.

Thanks for your help!
G'day mate

### PR DESCRIPTION
**Pull request by alexbrazier**
@RocketChat/core 

Closes #3862 
Closes #5867

Add admin and user setting to control the default room preference for when to receive notifications.

image

image

image

### CODE REVIEW

**Comment by rodrigok** [comment]
@alexbrazier Your ideia is great, but we need to evaluate this carefully cuz these changes can add a huge impact on performance for large rooms. I'll try to do some tests ASAP.

**Comment by alexbrazier** [comment]
@rodrigok I made an update to add a setting where notifications for all messages is disabled for large channels. Default currently set to 100 members or more. I have added a screenshot.

**Comment by geekgonecrazy** [comment]
@alexbrazier any thoughts on from a UI/UX perspective disabling the radio buttons to choose all messages if over user limit?

**Comment by alexbrazier** [comment]
@geekgonecrazy Do you mean in the per channel notification settings for the user (3rd screenshot)? A user is still allowed to individually set `All messages` as a preference if they want on a per channel basis, even if the number of users is over the limit. The limit only disables all message notifications on the admin and user global settings for ALL channels (the first 2 screenshots).

**Comment by alexbrazier** [comment]
@geekgonecrazy Any news on whether this PR is going to be merged? Do you want me to change anything?

**Comment by rodrigok** [comment]
IMHO, this PR will add a huge load to large rooms, but we can use it after the merge of branch `experimental` that includes cache for some records and relations, then we can update this PR to just iterate over subscriptions to get user data rather than a new find.

**Comment by alexbrazier** [comment]
@rodrigok I added a setting to set the number of users in a room to disable this feature for. Currently the default is 100, so if a room has 100 users or more the notifications will go back to the original, so hopefully shouldn't have much of an impact.

**Comment by rasos** [comment]
Does this include semantically the patch at https://github.com/RocketChat/Rocket.Chat/issues/1602#issuecomment-226559485? Users want to get notifications in parallel on the desktop AND on the mobile device.

**Comment by megamaced** [comment]
+1 for getting this merged.

**Comment by Flipez** [comment]
+1 would be very helpful

**Comment by engelgabriel** [comment]
We have merged the branch experimental, can we resolve the conflicts now and test it again?

**Comment by alexbrazier** [comment]
Conflicts have now been resolved

**Comment by Mte90** [comment]
any news for it?

**Comment by marceloschmidt** [comment]
@rodrigok can you take a look at this again? does the max limit solve the load problem?

**Comment by alexbrazier** [comment]
@engelgabriel Is this ready to merge if I fix conflicts?

**Comment by RichardFoxworthy** [comment]
how is this one going? we need to set per-channel notification defaults. For some channels it is appropriate that default setting is notification on all messages

**Comment by KirschbaumP** [comment]
any news?

**Comment by marceloschmidt** [comment]
Oh god :( I tried fixing conflicts and pushing to the feature/default-notifications branch on alexbrazier/Rocket.Chat. Let me try to revert that... sorry for any inconvenience.

**Comment by marceloschmidt** [comment]
Just fixed the conflicts! @RocketChat/core can we merge it please?

**Comment by rodrigok** [comment]
@alexbrazier can you fix the conflicts? I'll review it after that

**Comment by fuzunspm** [comment]
any news?

**Comment by zipper2110** [comment]
This feature is to selebrate a 1 year birthday soon :)

**Comment by megamaced** [comment]
Commiserate 1 year birthday :-(. Should be merged

**Comment by geekgonecrazy** [comment]
Not exactly a year.  ;-) Still have 2 months.  

@alexbrazier do you have a chance to merge conflicts?

**Pull request closed without merging**
