### PR TITLE
Added docker-compose file for local development

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
I was just getting a Rocket.Chat environment setup for development (hope to be contributing soon!).

I noticed a Dockerfile, so I added a docker compose file, and now all it takes to get started with development is `docker-compose up`, which I find super convenient.

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
If you're using boot2docker, you'll have to run `VBoxManage controlvm boot2docker-vm natpf1 "rocket,tcp,127.0.0.1,3000,,3000"` to port forward from boot2docker to localhost

**Comment by engelgabriel** [comment]
thanks @Joshua-Anderson 

@Sing-Li is it ok to merge this pr?

**Comment by Sing-Li** [comment]
s, @Joshua-Anderson!

Actually, the Dockerfile is used on a commit trigger that builds [our image at the docker hub](https://registry.hub.docker.com/u/rocketchat/rocket.chat/).

This way, Rocket.Chat Docker deployers, cloud or otherwise, always get the bleeding-edge version as soon it is ready; and allows us to t.i.p. prior to one dot oh.

For hosted VPS and container deployments, @pierreozoux has authored [a set of docker-compose scripts](https://github.com/RocketChat/Deploy.to.Cloud/blob/master/GenericLinux/docker-compose.yml) that can start or stop Rocket.Chat and backup instance data.

For development convenience, I'd imagine that most of our contributors are coding on a Mac, Linux, or Windows machine.  Rocket.Chat runs native on *all* of these platforms.  The edit, test, re-edit cycle is lightning fast thanks to Meteor hot code pushes.  Introducing a docker container in-between, except for special cases, will likely slow things down significantly -- especially since our image build process is not particularly fast at this time.

Having said this, we are extremely interested in creating 'no-brainer one-click deploys' for VPS and container deployment, specific ones for specific providers. See our [Nitrous.io](https://github.com/RocketChat/Deploy.to.Cloud/tree/master/Nitrous), [Heroku](https://github.com/RocketChat/Deploy.to.Cloud/tree/master/Heroku) and [IBM Bluemix](https://github.com/RocketChat/Deploy.to.Cloud/tree/master/Bluemix)  efforts.  It would be awesome if you can help us with it, this PR can be readily repurposed.

**Comment by Joshua-Anderson** [comment]
This is useful for me, since I work with a bunch of different languages and databases and don't want to clutter my machine with all the different runtimes. I understand this could be less useful for the community as a whole. I'll move this to another directory and get started developing :smiley:.

**Pull request closed without merging**
