### PR TITLE
[IMPROVE] Don't send emails to online users and remove delay when away/idle

### PR DESCRIPTION
**Pull request by sampaiodiego**
## Proposed changes

This reverts some undesired changes introduced by #17357, so with this changes:
- it will not send emails to connected users
- send notifications to away users right away

## Issue(s)

Closes https://github.com/RocketChat/Rocket.Chat/issues/17492

## How to test or reproduce

- While online, receive a message and wait 2 minutes without looking anything, you will receive an email
- Open mobile app and send it to background (the connection will be set to away), receive a message, a notification will be sent only after 2 minutes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by densik** [comment]
This was not fixed, I'm still getting emails. Looks like connection status isn't being used as a parameter? sendNotificationsOnMessage.js ([148](https://github.com/RocketChat/Rocket.Chat/blob/11570758a81c7f1d742da63df33273fde0c1ae7b/app/lib/server/lib/sendNotificationsOnMessage.js#L148))

**Comment by sampaiodiego** [comment]
this improvement was released today on 3.4.0 release.. did you update already?

**Comment by densik** [comment]
Yes I'm on 3.4.0

**Comment by FredNass** [comment]
Hello, we're running 3.13.2 and emails are still sent to 'away' users. We dig this further and here's what we found:
- emails are sent to 'away' users when the got set 'away' automatically (after 300s)
- emails are not sent to users that set them 'away' manually.
Can someone please check the code and fix this for good? :-)

**Pull request merged**
