### PR TITLE
[FIX] Custom scripts descriptions were not clear enough 

### PR DESCRIPTION
**Pull request by MarcosSpessatto**
Closes https://github.com/RocketChat/Rocket.Chat/issues/14436

### CODE REVIEW

**Comment by rodrigok** [comment]
@MarcosSpessatto this is not the intent for this script, it should run always for logged out clients, for example, for people in login screen.

**Comment by MarcosSpessatto** [comment]
Oh okay, the bug related is not a bug then. It's an error on script. I think we can close this then, What do you think?

**Comment by geekgonecrazy** [comment]
Yeah this may be a case we need to tweak the description to make more clear some how what that script field can be used for

**Comment by rodrigok** [comment]
@MarcosSpessatto what if you change this PR to improve the field description?

**Pull request merged**
