### PR TITLE
[FIX] fix emoji package path so they show up correctly in browser

### LINKED ISSUE #8465: Emojis not visible
### Description:

Emojis are not visible in Emoji and Reaction menu
2017-10-11 23_23_18-rocket chat

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-develop
* Operating System: CoreOS alpha
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 4.8.4 - x64

### Steps to Reproduce:

1. Join any public / private channel as admin or user
2. Open Emojis / Reactions menu - emojis are not showing up

### Expected behavior:

should be obvious

### Actual behavior:

emojis are not showing up

### Relevant logs:

only some ldap errors, nothing related
no errors in Browser Console

Edit: custom emojis are displayed properly

### PR DESCRIPTION
**Pull request by ryoshimizu**
@RocketChat/core 

Closes #8465

### CODE REVIEW

**Comment by ryoshimizu** [comment]
@rodrigok @geekgonecrazy  - kindly review

**Comment by geekgonecrazy** [comment]
@karlprieb this looks safe to me, can you confirm?

**Comment by ryoshimizu** [comment]
@karlprieb - kindly review wyam

**Comment by geekgonecrazy** [comment]
@ggazzo this might fix the emoji issue identified on designpreview?

**Comment by karlprieb** [comment]
@ryoshimizu thank you! 👍 

@geekgonecrazy it will fix the designpreview :D

**Comment by geekgonecrazy** [comment]
Yay!  😄  i'll go ahead and merge down.

**Pull request merged**
