### PR TITLE
[IMPROVE] Slack "corporate-export"-import (groups, direct messages and multi-user-messages)

### LINKED ISSUE #13905: Slack Import: corporate-export data (direct messages, private channels, etc.) is not imported
### Description:

Right now Rocket.Chat´s Slack Import only imports public channels, users and messages.
The coporate-export of Slack gives the opportunity to also export:

- private channels  ("groups")(`groups.json`)
- direct messages (`dms.json`)
- multi-user-conversations (`mpims.json`)

The [importer.js](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/importer-slack/server/importer.js) is processing all the message-subfolders but only takes care about the public channels, described in `channels.json`.

(To me) it looks like the routines are already there to process the other json-files mentioned above, especially because the importer already handles all the message-subfolders. So it would be great if this could be implemented.

### Steps to reproduce:

1. Go to AdminPanel->Import->Slack
2. Select Sack-Coporate-Export-Zip-file
3. Wait for Rocket-Chat Importer to process the file
4. See that all users, all messages but only public channels are importable

### Expected behavior:

Also private channels, direct messages and multi-user-conversations should be importable

### Server Setup Information:

- Version of Rocket.Chat Server: latest (0.74.3)
- Operating System: Synology DSM 
- Deployment Method: Docker Container
- Number of Running Instances: 1
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.5

I would be happy to provide more information or a testfile if nessecary.

### PR DESCRIPTION
**Pull request by niklasdahlheimer**
Closes #13905

**An attempt to include abilities to import all of the data from slack-corporate-exports.**
Slack corporate-exports are including private chats, direct messages and multi-user-direct-messages.

### The structure of the corporate-export zip-file

```
├── channels.json
├── subfolder_channel_1 (i.e. "General", "public Information")
│   ├── 2019-12-20.json            
│   ├── 2019-12-21.json
│   └── ... 
├── ... (more subfolders)
├── groups.json
├── subfolder_group_1 (i.e. "secret Group", "Management")
│   ├── 2019-12-20.json            
│   ├── 2019-12-21.json
│   └── ... 
├── ... (more subfolders)
├── mpims.json
├── subfolder_multi_person_chat_1 (i.e. "mpdm-joe-lisa-anna-john", "mpdm-lisa-john-peter")
│   ├── 2019-12-20.json            
│   ├── 2019-12-21.json
│   └── ... 
├── ... (more subfolders)
├── dms.json
├── subfolder_direct_messages_1 (i.e. "D38RUJBCP", "D39AJJG7L")
│   ├── 2019-12-20.json            
│   ├── 2019-12-21.json
│   └── ... 
├── ... (more subfolders)
```

groups.json and mpims.json looks just like the channels.json.

### The structure of the dms.json

```
[
    {
        "id": "D38RUJBCP",
        "created": 1529308826,
        "members": [
            "U63MAB7U5",
            "U1D4CHJLV"
        ]
    },
    {
        "id": "D39AJJG7L",
        "created": 1527578772,
        "members": [
            "U63MAB7U5",
            "U1GKUUV7H"
        ]
    },...
]
```

I added parsing of groups.json, which is the equivalent to private channels in Rocket-Chat.

### Next steps

- [ ] process mpims.json, which contains the multi-user-direct-messages. 
multi-user-direct-messages are like private channels without a name. Because Rocket-Chat has no feature like this, it needs to be handled as private channels. But the channel name "user1-user2-user3-.." would look silly. **Any suggestions on this?**

- [x] direct messages should be parsed also. Two cases:
  - rocketchat_room-document for the private-chat already exists -> add messages to this room id
  - rocketchat_room-document for the private-chat does not exist -> the importer needs to create the rocketchat_room-document for this private chat. How does Rocket-Chat add the rocketchat_room-document for private chats? I only found `lib/server/methods/createPrivateGroup.js` and `lib/server/methods/createChannel.js`. **Is there an equivalent for private chats?**

### CODE REVIEW

**Comment by niklasdahlheimer** [comment]
I added support for direct messages by creating the rooms via a new server-method createDirectRoom.
So two more thoughts about this

1. should there be a possibility in the frontend to choose if direct messages should be imported?
2. Whats about the multi-user-chats in slack? Should the be imported and, if yes, which name should they have? Just the usernames?

**Comment by niklasdahlheimer** [comment]
I managed to import the data including direct chats and private channels from the slack-corporate-import-zip-file, backuped and restored the mongo-data and use it in the docker production environment of our company right now.
There is still a bug which leads to a fail of the first import, the second import works flawlessly, it can be traced back to a undefined room object in [line 381](https://github.com/niklasdahlheimer/Rocket.Chat/blob/c1083d4c2a3f5fdf7a77e6038f5938e36f61bb1b/app/importer-slack/server/importer.js#L381), where I'm not really sure why this happens.

However, some comments of the project maintainers would be appreciated because I still need to know:

- how we should handle multi-user-chats
- is there any objection against appending the private channel data to the channel collection (see [line 98](https://github.com/niklasdahlheimer/Rocket.Chat/blob/c1083d4c2a3f5fdf7a77e6038f5938e36f61bb1b/app/importer-slack/server/importer.js#L98))
- what should be the way of improving the feedback for the user? Right now uploading and parsing of the zip file, even if everything is running on localhost, takes really long (~5min for a 10mb-file) and the only feedback the user gets is a connection timeout and a page reload after uploading and preparing has finished. But that not leads back to the import selection, the user has manually navigate to the slack importer again to see the import selection.

**Comment by Hudell** [comment]
Multi user messages can be skipped for now. We are going to implement a similar feature on Rocket.Chat soon, but until then it's ok to skip those conversations.

**Comment by geekgonecrazy** [comment]
Are we planning to get this in a version near?  I know there are several people wanting these changes to begin using rocket.chat

**Comment by sampaiodiego** [comment]
can someone please fix the conflicts? :hugs:

**Comment by niklasdahlheimer** [comment]
I think, beside fixing the conflicts, additional testing is needed. I managed to use this version to import the corporate data into Rocket.Chat but had to delete a few files from the import-data-zip-file.
It worked for our company so I didn't spent more time on that.
Unfortunately I can not provide any test-data, because we deleted the uncrypted corporate-import-data due to privacy reasons.

If someone could provide test-data I could bring this feature to a more stable state, so it could be merged into a release.

**Comment by pigmonkey** [comment]
I have corporate exports and am waiting on this feature before migrating to rocket chat. I cannot share the data, but I can try to spin up a development environment to test this branch on my exports and report the results.

On the subject of multi-party direct messages, I would be happy for them to be imported as `user1-user2-user3...` private channels -- unless rocket chat's version of that feature is imminent. I would rather not skip that data.

**Comment by AitorCM** [comment]
So, any news on when this feature is going to be added to RocketChat?

Thanks!

**Comment by geekgonecrazy** [comment]
#16279 - this major refactor might be related

**Pull request closed without merging**
