### PR TITLE
[FIX] Email notifications were still being sent for online users

### PR DESCRIPTION
**Pull request by densik**
Add the missing the statusConnection parameter, which should prevent emails being sent if user is online. Fixes PR [#17907](https://github.com/RocketChat/Rocket.Chat/pull/17907)

## Proposed changes

Add missing parameter `receiver.statusConnection` to shouldNotifyEmail function.

## Issue(s)

[#17492](https://github.com/RocketChat/Rocket.Chat/issues/17492)

## How to test or reproduce

- While online, receive a message and wait 2 minutes without looking anything, you will receive an email

- Open mobile app and send it to background (the connection will be set to away), receive a message, a notification will be sent only after 2 minutes

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

The previous PR had added a new parameter, but this is not being used when called. I have not done any tests locally, hoping some one else can do this and accept this PR to finally fix these spam of notification emails.

### CODE REVIEW

**Comment by rodrigok** [comment]
@densik thanks for your contribution, we gonna release a patch ASAP.

**Comment by rikatz** [comment]
After this patch the email stopped working at all for us ;(

The SMTP test works fine, but offline users doesn't get email even if they configure in their preferences

**Comment by rodrigok** [comment]
@rikatz I'll double check this, we are facing some other issues that may be related and we are going to release a patch 3.4.2 ASAP

**Comment by pierre-lehnen-rc** [comment]
@rikatz is none of your users receiving the emails? can you confirm that their connection status is really offline? this change shouldn't have broken anything unless the status is somehow stuck as online.

**Comment by densik** [comment]
@pierre-lehnen-rc Thanks for chiming in, that's what I thought too. Maybe there's something else causing incorrect connection statuses. Do they use any other/multiple clients at once like the mobile app maybe? Maybe the issue lies there, I'm not sure.

**Comment by rikatz** [comment]
I've asked for a user to logoff from his mobile and also from the chat but no message received. Will ping them tomorrow :)

**Pull request merged**
