### PR TITLE
[FIX] Fix 'GO TO MESSAGE' link in notification e-mails

### PR DESCRIPTION
**Pull request by JSzaszvari**
Closes https://github.com/RocketChat/Rocket.Chat/issues/

I'm honestly not sure if this is the right way to fix this, I tried a few ways and this seemed to be the simplest and works reliably.

Please close if this is not suitable, otherwise would appreciate some feedback on the correct way to do this.

Currently, the 'Go to Message' link in the E-mail notifications is missing the actual room/user part, so they are coming through http://rocket.chat/direct/ without the username (same for room/group messages)

### CODE REVIEW

**Comment by antgel** [comment]
@JSzaszvari Looks like you need to rebase on latest `develop`, there are conflicts. :)

**Comment by JSzaszvari** [comment]
@antgel - Done :)

**Comment by sampaiodiego** [comment]
image

is this a demonstration to what is happening to our email links? 😂 just kidding..

I've create https://github.com/RocketChat/Rocket.Chat/pull/10928 which fixes it properly.. thanks y'all..

**Comment by sampaiodiego** [comment]
sure.. the problem is we have a architecture to support multiple room types, not only the default ones (public channel, private channel and direct messages). so anything that is hard coded regarding room types _tends_ to be wrong.

so that's why the result of `RocketChat.roomTypes.getRouteLink` should be the correct one.. because it has all room types configured and know how to handle each one..

the problem was the `sub` parameter being sent to it hasn't enough data to generate the correct link.. this could be solved by using typescript (enforcing what properties the object should have) or having a documentation on the function itself, saying for example the `sub` parameter should have at least `name`, `_id` properties..

**Comment by JSzaszvari** [comment]
@sampaiodiego Thank you so much, that's perfect!

I genuinely see now why my change would not have been suitable and now have a much better understanding why you method is the correct one. 

I really appreciate the explanation. 

Thanks dude 👍

**Pull request closed without merging**
