### PR TITLE
fix for #838

### LINKED ISSUE #838: Create Channel button hidden
The create new channel button in the listChannelsFlex footer is hidden. If you view the html, it's present, but hidden by the RocketChat logo 

To replicate:
1. login as user
2. click on "More channels"
3. scroll to bottom.  There should be a button that allows you to create a new channel.

### PR DESCRIPTION
**Pull request by rabbihossain**
This patch fixes #838 . Here is a screen-shot of the current fix of this issue.

rocket-chat

### CODE REVIEW

**Comment by sampaiodiego** [comment]
hey @rabbihossain 

looking at your PR I got noticed that we lose some animations on sideNav.
One of them replaces the footer with that button.

what you think? PR #1134

**Comment by rabbihossain** [comment]
I just tested my modified version and compared with current demo on the main site. I haven't found any issue regarding your point on missing any animation on  sideNav. 
I haven't touched any animation nor added or modified any animation. So actually it shouldn't mess with any animations. 

Can you give me any clue on reproducing the issue you mentioned?

**Comment by rabbihossain** [comment]
Oh the PR #1134 has been merged an hour ago. So it might not be visible on current demo on website. Let me check the issue on my current local installation with latest commits.

**Comment by sampaiodiego** [comment]
I'm sorry @rabbihossain .. I was not so clear.
I put back the animations, but was not you (or your PR) who removed them.

but, when I put the animations back, the "create channel" button appeared again.. so, I just asked your thoughts on the animations.. =)

**Comment by rabbihossain** [comment]
Hi @sampaiodiego 
I have tested your PR. Yes your commits makes the "Create New" button appear again. But it contains an issue. The "Create New" button overlaps with the footer logo and makes it ugly. Here is a screenshot.

rocket

My PR positions it as it should be and doesn't mess with your animations. I think this PR is good to merge. Please have a check.

**Comment by sampaiodiego** [comment]
actually, code on master and live on the demo server looks good to me:

image

**Comment by rabbihossain** [comment]
Now it's clear to me. You tested on chrome. Check the current live demo on Firefox. It's broken.

**Comment by sampaiodiego** [comment]
you are right =)

damn firefox.. it doesn't respect the `min-height` property =( fixing right now!

**Comment by rabbihossain** [comment]
Yup that needs to be fixed and I think this PR needs to be closed. Should I close it or wait?

**Comment by sampaiodiego** [comment]
I'll close it. thank you btw :+1:

**Pull request closed without merging**
