### PR TITLE
Revert: [IMPROVE] Update system messages' behavior in rooms

### PR DESCRIPTION
**Pull request by KevLehman**
Reverts RocketChat/Rocket.Chat#22018

### CODE REVIEW

**Comment by KevLehman** [comment]
@matheusbsilva137 can you confirm this rolls back all your changes? 😬 I verified the same amount/content on files, but, a second pair of eyes is great

**Comment by matheusbsilva137** [comment]
> @matheusbsilva137 can you confirm this rolls back all your changes? 😬 I verified the same amount/content on files, but, a second pair of eyes is great

Yes, it does! LGTM 🙂 
Thanks for creating this PR to revert the changes, btw 😄

**Review by matheusbsilva137 — APPROVED** [review]

**Comment by ankar84** [comment]
What's wrong with #22018?

**Comment by milton-rucks** [comment]
> What's wrong with #22018?

Hi @ankar84 after analyzing the behavior on open and receiving user feedback we decided together with our UX team to revert the PR.

Users getting notifications and marking system messages as unread can be annoying in channels with many people (e.g people getting notified when someone leaves the channel).

We will conduce a deeper discovery and we implement it again when we have the final solution

**Pull request merged**
