### PR TITLE
[FIX] Add <html> and </html> to header and footer

### LINKED ISSUE #7001: Include <html> and </html> in header and footer
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

In file `Rocket.Chat/packages/rocketchat-lib/server/startup/settings.js` the default `Email_Header` and `Email_Footer` values should include a preceding \<html> and a trailing \</html> respectively, or the emails sent by Rocket.chat will [get spam points from SpamAssassin](https://wiki.apache.org/spamassassin/Rules/HTML_MIME_NO_HTML_TAG) due to technically malformed html (typical of spam messages).

### PR DESCRIPTION
**Pull request by ExTechOp**
Adding the html tags makes the emails sent out by rocket.chat better compliant with standards, and lowers the chance they'll be marked as spam.

@RocketChat/core 

Closes #7001

### CODE REVIEW

**Comment by sampaiodiego** [comment]
thanks @ExTechOp .. I think we also need `<body/>` tags to have a valid HTML, right?

**Comment by ExTechOp** [comment]
Email messages aren't usually formatted like complete web pages, with \<head>\</head> and \<body>\</body> sections. Adding the \<html>\</html> tags should be sufficient at least for the purpose of heuristic-based spam detection – I do not know of any such system that does more extensive html syntax/semantics analysis.

**Comment by engelgabriel** [comment]
@sampaiodiego and @rodrigok should we add a migration here?

**Comment by sampaiodiego** [comment]
good catch @engelgabriel .. yes we do need.

**Pull request merged**
