### PR TITLE
[NEW] Add REST API endpoints `channels.counters`, `groups.counters and `im.counters`

### PR DESCRIPTION
**Pull request by xbolshe**
@RocketChat/core 

This PR allows to get counters for channels, groups, im. 
If calling user has no `view-room-administration` right, only user's counts will be provided.
If calling user has `view-room-administration` right, it is possible to specify userId to get counters for any pair { user, room }.

Examples:

```
GET http://192.168.2.71:3000/api/v1/channels.counters?roomId=GENERAL HTTP/1.1
X-Auth-Token: xPdcjO2pMLEl-pRTIXwXbnnY4OrMpcfcNz00t7SgNVk
X-User-Id: JLtMZRq55PdypTkcr
Host: 192.168.2.71:3000
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
X-Instance-ID: 2RfALZjsq2zaJYJkW
Cache-Control: no-store
Pragma: no-cache
content-type: application/json
Vary: Accept-Encoding
Date: Sun, 11 Feb 2018 13:47:01 GMT
Connection: keep-alive
Transfer-Encoding: chunked

{"members":3,"joined":true,"unreads":4,"unreadsFrom":"2018-02-11T02:10:05.294Z","msgs":25,"latest":"2018-02-11T11:52:16.836Z","userMentions":1,"success":true}
```

where
           `joined` - boolean flag that shows that user is joined the room or not
           `members` - count of current room members
           `unreads` - count of unread messages for specified user (calling user or provided userId)
           `unreadsFrom` - start date-time of unread interval for specified user 
           `msgs` - count of messages in the room
           `latest` - end date-time of unread interval for specified user (or date-time of last posted message)
           `userMentions` - count of user mentions in messages

If calling user has no `view-room-administration` right and has not joined a channel:
```
GET http://192.168.2.71:3000/api/v1/channels.counters?roomId=GENERAL&userId=3WpJQkDHhrWPBvXuW HTTP/1.1
X-Auth-Token: xPdcjO2pMLEl-pRTIXwXbnnY4OrMpcfcNz00t7SgNVk
X-User-Id: JLtMZRq55PdypTkcr
Host: 192.168.2.71:3000
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)

HTTP/1.1 403 Forbidden
Access-Control-Allow-Origin: *
X-Instance-ID: 2RfALZjsq2zaJYJkW
Cache-Control: no-store
Pragma: no-cache
content-type: application/json
Vary: Accept-Encoding
Date: Sun, 11 Feb 2018 13:45:25 GMT
Connection: keep-alive
Transfer-Encoding: chunked

{"success":false,"error":"unauthorized"}
```

If calling user has `view-room-administration` right to check counters of another user:
```
GET http://192.168.2.71:3000/api/v1/channels.counters?roomId=GENERAL&userId=JLtMZRq55PdypTkcr HTTP/1.1
X-Auth-Token: 907HhASs1Ob1TCYFgEOC1ClxjlYzgdNvcxA_Oyy4f9C
X-User-Id: 3WpJQkDHhrWPBvXuW
Host: 192.168.2.71:3000
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
X-Instance-ID: 2RfALZjsq2zaJYJkW
Cache-Control: no-store
Pragma: no-cache
content-type: application/json
Vary: Accept-Encoding
Date: Sun, 11 Feb 2018 13:43:49 GMT
Connection: keep-alive
Transfer-Encoding: chunked

{"members":3,"joined":true,"unreads":4,"unreadsFrom":"2018-02-11T02:10:05.294Z","msgs":25,"latest":"2018-02-11T11:52:16.836Z","userMentions":1,"success":true}
```

### CODE REVIEW

**Comment by xbolshe** [comment]
@RocketChat/core Any comments?

**Comment by engelgabriel** [comment]
Documentation: https://github.com/RocketChat/docs/pull/596

**Comment by MarcosSpessatto** [comment]
@xbolshe already did! RocketChat/docs#596 ^^

**Comment by rodrigok** [comment]
@MarcosSpessatto haha, sorry

**Pull request merged**
