### PR TITLE
fix: Application crashes when clicking on Analytics option in Omnichannel view page

### LINKED ISSUE #29272: Application crashes when clicking on Analytics option in Omnichannel view page
### Description:

When clicking on the "Analytics" option in the Omnichannel view page (omnichannel/analytics) the application crashes with the following error in the console

image

### Steps to reproduce:

1. Click on omnichannel
image

2. Then Click on Analytics
image

### Expected behavior:

Analytics pages should be displayed

### Actual behavior:

Application is crashing

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0-develop
- Operating System: Windows 10
- Deployment Method: Gitpod
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.3 - x64
- MongoDB Version: 6.0.3

### Relevant logs:

image

location of AgentOverview.tsx: apps/meteor/client/views/omnichannel/analytics/AgentOverview.tsx

### PR DESCRIPTION
**Pull request by anikdhabal**
## Issue(s)

fix #29272 
OC-953

### CODE REVIEW

**Review by yash-rajpal — DISMISSED** [review]

**Comment by KevLehman** [comment]
Hey! Thanks for the contribution. The PR indeed solves the crash problem, but it also removes the translations for the server-returned strings:
image

In this case, `%_of_conversations` should translate to `% of conversations` (and other languages too) but the string is left as it is. Would you mind checking? 🙌🏽 thanks!

**Comment by jayesh-jain252** [comment]
The presence of the '%' symbol in the "% of Conversations" at "apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json" file is probably causing the problem.

image

Escaping the "%" like this solves the issue

image

Reference: https://github.com/martinandert/counterpart/issues/37

image

@KevLehman is this solution accurate and valid?

**Comment by anikdhabal** [comment]
> Hey! Thanks for the contribution. The PR indeed solves the crash problem, but it also removes the translations for the server-returned strings: image
> 
> In this case, `%_of_conversations` should translate to `% of conversations` (and other languages too) but the string is left as it is. Would you mind checking? 🙌🏽 thanks!

sure sir!

**Comment by anikdhabal** [comment]
Yes sir, percentage signs need to be escaped with another percentage sign in the json file.

**Comment by murtaza98** [comment]
> Yes, percentage signs need to be escaped with another percentage sign in the json file. Sorry for my mistake.

Hey @anikdhabal  No need to apologize, we're all learning here. Thanks for letting us know about the percentage sign issue in the json file. Could you please inform us when you're done with the suggestion? We appreciate your help! 😊

**Review by murtaza98 — APPROVED** [review]

**Review by KevLehman — APPROVED** [review]

**Pull request merged**
