### PR TITLE
Add Pinning Functionality

### PR DESCRIPTION
**Pull request by graywolf336**
As part of preparing Rocket.Chat for the Slack import, this piece is critical for teams who use the pinned messages to keep important information related to the channel the discussion happened in. The functionality this pull request provides allows configuring who can do the pinning and whether pinning is enabled. You can change between everyone being able to pin, like slack, or only channel owner and admins being able to pin messages. If pinning is disabled, the pin tab won't show up on the right.

### CODE REVIEW

**Comment by rwakida** [comment]
This is a great feature to have :smile: 

I know we don't have a roles and permissions UI yet, but I think *who* can pin should be a permission assigned to a role.  i.e. Message_AllowPinningByAnyone should be a permission instead of a setting.

**Comment by graywolf336** [comment]
@rwakida So, should I add that now or what until roles and permissions gets a ui?

**Comment by rwakida** [comment]
I was hoping you'd say you'd build the UI.  :wink: 

I guess keep it as a setting and we'll port it over when the roles and permissions UI is built.

**Comment by graywolf336** [comment]
Haha I haven't looked into the requirements for that feature enough yet to
even think about it. ;)

Let me know if there's anything else needed to do so this gets pulled.

**Comment by geekgonecrazy** [comment]
@graywolf336 this looks good!  Some reason meteor failed to download in travis.  I'd like to go ahead and get this merged so we can get on with slack

**Comment by Telemakhos** [comment]
+1

**Comment by graywolf336** [comment]
@Telemakhos it's implemented already :wink:

**Pull request merged**
