### PR TITLE
[FIX] Clear UI when user mentioned in threads and removed additional jump to message option.

### LINKED ISSUE #20786: Jump to message option shown twice in mentions
### Description:
The jump to message option is shown twice in the mentions option of the contextual bar.

### Steps to reproduce:

1. Contexual bar
2. Three dots
3. Mentions

### Expected behavior:
The option should be shown once only.

### Actual behavior:
The option is shown twice.

https://user-images.githubusercontent.com/55157259/108108166-45a91600-70b6-11eb-9a46-404414223ab1.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu

### Additional context
Working on it!

### LINKED ISSUE #20787: When user is mentioned in threads, the mentions option of contexual bar has unusual UI.
### Description:
When a user is mentioned in thread messages, UI of the mentions option is weird.

### Steps to reproduce:

1. Any thread and tag yourself
2. Mentions from contextual bar

### Expected behavior:

UI should be clear.
### Actual behavior:
UI seems unusual.

https://user-images.githubusercontent.com/55157259/108108654-e697d100-70b6-11eb-9aad-6d8008eda51c.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context
Working!

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)

UI is fixed when a user is mentioned in threads and an extra jump to message button is removed.

https://user-images.githubusercontent.com/55157259/108108927-4a21fe80-70b7-11eb-8410-a5b076c02f40.mp4

## Issue(s)

Closes #20787 
Closes #20786

### CODE REVIEW

**Comment by im-adithya** [comment]
The 'Jump To Message' isn't the only button that is additional, even the Quote, Add Reaction, Reply in Thread are also present twice for every message. This I think is intentional so that users can select actions easily rather than options > action

**Comment by Darshilp326** [comment]
@im-adithya Hello. Actually, in Mentions there is only one option, so it seems irrelevant in having an additional jump button.

**Comment by im-adithya** [comment]
Hmmm, then you can consider adding the 'Get Link' button as well to options and bring the 'Jump To Message' button back again. This will maintain uniformity with Starred and Pinned Messages tab (refer to them once).

**Comment by Darshilp326** [comment]
@im-adithya Okay!

**Comment by Darshilp326** [comment]
@dougfabris @ggazzo Please review :smile:

**Pull request closed without merging**
