### PR TITLE
Modified 'info' end point to require authentication

### LINKED ISSUE #3651: RestAPI: info end point is public
Your Rocket.Chat version: 0.35.0

Whilst I was looking at the API I noticed that the 'info' endpoint is available without authenticating, it should probably require authentication as it returns various information about the build that system administrators would rather keep private.

Easy to remedy, PR incoming.

### PR DESCRIPTION
**Pull request by jamie-owen**
@RocketChat/core 

Closes #3651

### CODE REVIEW

**Comment by sampaiodiego** [comment]
@rodrigok I know we use this [for the mobile app to validate the server](https://github.com/RocketChat/Rocket.Chat.Cordova/blob/develop/www/coffee/servers.coffee#L103) so it could not require authentication.. do you think we can (fix and) use the [/version endpoint](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/restapi/restapi.coffee#L11) for that? do you remember any other place we use the `/api/info` endpoint?

**Comment by rodrigok** [comment]
@Jamie-Owen Maybe we can keep showing the property `version` when user is not logged and show everything if user is logged and is admin. What do you think?

**Comment by rodrigok** [comment]
@Jamie-Owen do you need some help here?

**Comment by Jamie-Owen** [comment]
Wouldn't it be better to fix the `/version` endpoint and switch the way that the mobile app validates the server?

**Comment by rodrigok** [comment]
@Jamie-Owen That will break new old versions of the app to work with new versions of the server and vice versa.

**Comment by Jamie-Owen** [comment]
@rodrigok Understood, I'll review and take the suggested approach.

**Comment by marceloschmidt** [comment]
@rodrigok @Jamie-Owen any progress on this one?

**Comment by graywolf336** [comment]
Closing as this has be resolved by: https://github.com/RocketChat/Rocket.Chat/pull/5942

**Pull request closed without merging**
