### PR TITLE
fix: Dropping a file from another browser window creates two upload dialogs

### PR DESCRIPTION
**Pull request by Sayan4444**
Proposed changes (including videos or screenshots)
BEFORE THE FIX
https://github.com/RocketChat/Rocket.Chat/assets/112304873/a6f0faf1-cd9a-480d-bbe1-c60044d10205

AFTER THE FIX
https://github.com/RocketChat/Rocket.Chat/assets/112304873/d59fb5c2-9fcd-40fc-9630-8386a0712520

REASON BEHIND CHANGES
We are comparing the files by their size in bytes and checking for any duplicate files as it is very hard to find files of same size.We can also use nodejs to check but it takes a bit longer for long files.If you want the nodejs version please do tell me.

Issue(s)
This should close issues :-
closes https://github.com/RocketChat/Rocket.Chat/issues/30793

Steps to test or reproduce
Open a Rocket.Chat channel in one Chromium window.
Open the image to be drag-and-dropped in another Chromium window.
Drag the image and drop it into the Rocket.Chat channel.

### CODE REVIEW

**Comment by hugocostadev** [comment]
Did you understand why it's creating two files?  I think that we need to fix this problem instead of resolving this issue in our application

**Comment by Sayan4444** [comment]
Yes I have @hugocostadev.
image
The primary cause of multiple files being created for (some type of files) is this commented-out code(commented by me for now for demonstration purpose). The program attempts to send a get request to each src of img contained in the dropped file as soon as the if condition is satisfied. A duplicate file is not produced if the URL returns an error stating that a direct request is blocked.
Example

Screenshot 2024-01-04 235343

However, if the request is made, a new file containing the identical picture is created and added to the files array that previously included the image, resulting in the creation of a duplicate file.

The problematic code has been commented out, and practically all cases for drag and drop runs normally. Would you kindly let me know if I missed any cases and how do you want me to approach the situation with the duplicate files?

**Comment by Sayan4444** [comment]
@hugocostadev can you check from this website,
https://tenor.com/ 
and revert me back?

**Comment by hugocostadev** [comment]
For me does not work but a windows user tested and it was able to reproduce, I'll accept your solution! Thanks

**Review by hugocostadev — APPROVED** [review]

**Review by hugocostadev — APPROVED** [review]

**Pull request merged**
