### PR TITLE
adding in user icon in the desktop notifications

### PR DESCRIPTION
**Pull request by soonahn**
Address https://github.com/RocketChat/Rocket.Chat/issues/729

### CODE REVIEW

**Comment by rodrigok** [comment]
@soonahn awesome, this works synchronously?

**Comment by rodrigok** [comment]
Seems that it isn't, if avatar (initials) not was loaded before the notification the notification has no image.

**Comment by soonahn** [comment]
Synconous on the client side. Feature of html5 and canvas to transform image to png. Does require building a canvas element, but doesn't attach to the DOM

**Comment by soonahn** [comment]
Well yes, it's using the same method to get the avatar as everything else is. Is this an issue?

**Comment by rodrigok** [comment]
No, you didn't understand, if the image isn't in browser cache you are rendering an empty image because render is sync but the code doesn't stop while the image is loaded from server.

**Comment by rodrigok** [comment]
Steps to reproduce:

* Login with user A and user B
* With user A got to some room where you can't see user B, like a private room with another user and do a refresh clearing the browser cache
* With user B send a direct message to user A
* User A will receive a notification from user B without the avatar of user B (if it is initials)

**Comment by soonahn** [comment]
Ahh, now I understand. What is the right solution? Grab the user's initials avatar, load it into the browser cache, then send the notification?   Seems weird to delay the notification, I would rather have a notification without an image, than a notification that came at the wrong time.

**Comment by geekgonecrazy** [comment]
What about something like:

```
img.onload = ->
  //proceed cause image should have now loaded
```

Not much of a delay.. also I haven't tested this.  But i'd think that'd insure the image was there before running through the canvas.

Especially since avatarUrlFromUsername just returns a url:
```
return "#{Meteor.absoluteUrl()}avatar/#{username}.jpg?_dc=#{random}"
```

**Comment by rodrigok** [comment]
@geekgonecrazy good ideia :smile:

**Comment by soonahn** [comment]
@geekgonecrazy good idea, I'll look at it again tonight.  Thanks guys!

**Comment by geekgonecrazy** [comment]
@soonahn let me know if you need help with this.

**Comment by soonahn** [comment]
Am just busy with work.  Weekdays are hard for me, I'll get it done this weekend, unless someone wants to take this branch over.

**Comment by engelgabriel** [comment]
It's fine @soonahn 

we appreciate all the help we can get. :)

**Pull request closed without merging**
