### PR TITLE
[WIP] Livechat manager

### PR DESCRIPTION
**Pull request by sampaiodiego**
I'm finishing the livechat manager page.
This pages will be used livechat managers to configure livechat behaviors.

This is what I have for now:

## User management
image

## Department management
image

image

## Triggers (only one atm)
image

## Installation code
image

## Appearance settings
image

### CODE REVIEW

**Comment by diogobernini** [comment]
Looking neat.

**Comment by skyred** [comment]
I guess this is not included in 0.9 release. I am wondering what steps that I need to do in order to test this?

**Comment by sampaiodiego** [comment]
hey @skyred you can test it enabling the `rocketchat:livechat` meteor package in your dev environment.
if you want to test it in production, you'll have to build rocket.chat yourself.. we'll add it to our builds in the next weeks..

**Comment by skyred** [comment]
I see v0.11.0 is tagged. On the other hand, the docker image is still at v0.9. Using Docker for creating sandboxes for testing is great, but it seems that this project has skipped a few releases on docker?

**Comment by Sing-Li** [comment]
@skyred   --  please make sure you are using this Docker image ...

https://hub.docker.com/r/rocketchat/rocket.chat/builds/

... if you want to play with the latest code - as you can see, it is updated *instantly*  (2 hours ago)

**Comment by skyred** [comment]
Interestingly, this gets more confusing. Why does your organization keep two Docker repos? 

https://hub.docker.com/_/rocket.chat/
https://hub.docker.com/r/rocketchat/rocket.chat/ (including Dockerfile in the project itself doesn't seem to be a common practice)

**Comment by Sing-Li** [comment]
It is _very_ common practice for rapidly-moving FOSS projects.  Please just browse around at the repositories available at hub.docker.com to see many examples.

We keep *THREE* images, for the diverse needs of our global users community:

1.  Official  - stable, reviewed by Docker committee `rocket.chat`
2.  Latest - stable, tested, latest available off our `master` branch `rocketchat/rocket.chat:latest`
3.  Develop - absolute latest, for those who need to work with the latest code  `rocketchat/rocket.chat:develop`

See this (and other info available at our wiki) for our branching strategy details:

https://github.com/RocketChat/Rocket.Chat/wiki/Branches-and-Releases

**Comment by skyred** [comment]
I see your point now. Thanks for the information. I will report it back once I have the chance to test the feature related to this issue.

**Comment by sampaiodiego** [comment]
so, docker images doesn't have livechat package installed.
I was discussing about this with @engelgabriel .. maybe we should release new images with livechat installed.

**Comment by Sing-Li** [comment]
:disappointed:   True.   Perhaps we need the LiveChat edition #1741 even sooner :grin:

**Comment by skyred** [comment]
rocketchat/rocket.chat:latest still uses the built package https://github.com/RocketChat/Rocket.Chat/blob/develop/Dockerfile#L19

I can't find the documentation on this project wiki about building from source. If someone can point me to the documentation, I might be able to build my own docker image for testing.

**Comment by sampaiodiego** [comment]
@skyred you can follow this steps to build Rocket.Chat from source:  [here](https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker/f0b2a36e19bd66b62033225d36170497db03e0d0#3-download-rocketchat)

**but**, in #1799 I'm adding livechat as default to develop branch. we'll merge it today and test it  during the week to release it on master branch in the next week.

**Comment by skyred** [comment]
I tested the latest develop built. It works well. Three quick comments: 

1. showing visitor's name is better than show their username, like guest-1, guest-2,.. 
2. Images posted on the main window cannot be seen in the live chat.
3. I guess there is no Android Notification yet.

**Pull request merged**
