### PR TITLE
[WIP][FEAT] Added right-click actions on message

### LINKED ISSUE #10955: [NEW] Right-click actions
### Description:
Right now, right-clicking messages, channels, and other things does nothing. It would be a lot nicer UX to allow all elements that have tripledots to also allow rightclick.

Quick mockup:
 

I believe this would be a very welcoming addition in place of hunting for the tripledot :-)
I'd be willing to implement this myself if someone can give me a few pointers on how to invoke the overflow menu in a correct way. (Unless we just want to make rightclick send a click event to the tripledots :smirk:)
For touch screens, we could use a tap-and-hold in place of rightclick.

### PR DESCRIPTION
**Pull request by ashwaniYDV**
Closes #10955

- [x] Only overwrite when clicking on the plain text of a message body, but not over images, links, etc.
- [x] When there is any selected text, show the original contextual menu.
- [ ] Display the original contextual menu when right-clicking the second time, like YouTube.
- [ ] Add hint on the menu footer to click again to access the original contextual menu.
- [ ]  Create a global setting for admins to control the feature (default disabled, for now).
- [x] Create a user setting to overwrite the admin setting.
- [ ] Have the app contextual bar on the rooms list, like Slack.

### Gif for changes:
qwerty

### CODE REVIEW

**Comment by ashwaniYDV** [comment]
@tassoevan @gabriellsh  I think we need a setting for developers to enable/disable this feature so that they can open developer console. What are your views. Please suggest.

**Comment by rodrigok** [comment]
@ashwaniYDV I like the approach to open the native menu on the double right-click or have a special key like (option/ctrl + right-click) opens the native menu, or even both :)

**Comment by ashwaniYDV** [comment]
> @ashwaniYDV I like the approach to open the native menu on the double right-click or have a special key like (option/ctrl + right-click) opens the native menu, or even both :)

@rodrigok I have added ctrl+rightclick event and details are updated in description of PR.
Please review

**Comment by reetp** [comment]
Please make this admin or even user switchable, and default to off.

Please don't force this sort of change. You are breaking accepted practice. Implemented as is this   isn't just a feature request, but a breaking change because you are forcing change.

Leave the system as is, and add the option to turn this on if required.

Not everyone is going to like it or want it (personally I think it goes against expected normal browser practice), and the option to override with your ctrl-click will be lost here and probably non existent in any documentation as normal.

Once you suddenly implement it you will probably have a mob of people asking how to disable it again because few people bother reading change-logs.

All that glisters is not gold.

**Comment by ashwaniYDV** [comment]
> Please make this admin or even user switchable, and default to off.
> 
> Please don't force this sort of change. You are breaking accepted practice. Implemented as is this isn't just a feature request, but a breaking change because you are forcing change.
> 
> Leave the system as is, and add the option to turn this on if required.
> 
> Not everyone is going to like it or want it (personally I think it goes against expected normal browser practice), and the option to override with your ctrl-click will be lost here and probably non existent in any documentation as normal.
> 
> Once you suddenly implement it you will probably have a mob of people asking how to disable it again because few people bother reading change-logs.
> 
> All that glisters is not gold.

Sorry @reept . I did not intended to break accepted practise. I saw that issue #10955 and tried to solve it. I like your suggestion to add it in user preferences and add their as an option to anable/disable this feature. Initially it will be off.

**Comment by rodrigok** [comment]
I agree with the option to disable this behavior but I'd like to see this enabled by default.

**Comment by reetp** [comment]
> Sorry @reetp . I did not intended to break accepted practise. I saw that issue #10955 and tried to solve it. I like your suggestion to add it in user preferences and add their as an option to enable/disable this feature. Initially it will be off.

Don't need to apologise....  :-)

By default web browsers do not use right clicks for application functionality in a page. People are used to the way it works. Don't just change it in a whim unless you have a *really* good reason.

eg it is pretty ubiquitous across browsers to use standard items like left click highlight, with right click then to copy, or say right click Select All, Save As, and other options like View Source or Inspect Element. They work the same pretty well everywhere, unless someone has tried to load a bit of JS to prevent copying.

That is just accepted practice over the majority of sites, like it or not.

So making a change like this may confuse and annoy a lot of people if you just implement it with no choice.

> So should I carry on with this setting in preference?

Yup, add it. But I a setting with default to off would be the best route. Let the user decide. They are the ones who will actually use it day to day.

You could add an admin setting to set all users to default on, with a user option to switch off, I guess. (I'd never use it, and my users will have a meltdown if they saw such a thing, but I don't care if others want to turn it on)

Again, when changing things unless there is a *REALLY* good reason otherwise, let the user choose. If it isn't broken, don't try fixing it. You might think it is a great idea, but they may not, and there are a lot more of them than there are of you!

**Comment by engelgabriel** [comment]
@reetp I understand your concerns and I think we should implement the feature and a way that addresses them. I'll add more requirements to the Pull Request in order to get this merged on the 4.0.0 release.

**Comment by engelgabriel** [comment]
> By default web browsers do not use right clicks for application functionality in a page. People are used to the way it works. Don't just change it in a whim unless you have a _really_ good reason.

I agree, and we can find a few examples, like Youtube, Telegram, and Slack that have done so.

> eg it is pretty ubiquitous across browsers to use standard items like left click highlight, with right click then to copy, or say right click Select All, Save As, and other options like View Source or Inspect Element. They work the same pretty well everywhere, unless someone has tried to load a bit of JS to prevent copying.

We can think in a few ways to allow the default context menu to appear, like when you have something selected, or click on a link or image, or ANYWHERE else that is not a plain text in the message body.
 
> Let the user decide. They are the ones who will actually use it day-to-day.

I am a bit in the fence here because we don't want to keep adding 100s os settings for everything, but this one looks like something that can be very annoying to some people.

> You could add an admin setting to set all users to default on, with a user option to switch off, I guess. (I'd never use it, and my users will have a meltdown if they saw such a thing, but I don't care if others want to turn it on)

Sounds good.

> Again, when changing things unless there is a _REALLY_ good reason otherwise, let the user choose. If it isn't broken, don't try fixing it. You might think it is a great idea, but they may not, and there are a lot more of them than there are of you!

Agreed. Let's make it DISABLE by default first, and use it ourselves a lot and tell the community to test it. If the feedback is largely positive, we will make it on by default on the subsequent release.

**Comment by ashwaniYDV** [comment]
@engelgabriel I have added it to user settings and made it false by default
Great to hear from you. Would like work upon all the todos :)

**Comment by reetp** [comment]
>     * Display the original contextual menu when right-clicking the second time, like YouTube.

Didn't even realise that you could - learn something new every day........

Totally non obvious with the second right click, and the reason not to change the expected behaviour UNLESS you really carefully explain it. Otherwise support admins are just going to get bombarded with users who suddenly can't find things.

One thought is the 3 dot menu to the right is not really 'obvious' for new users and I always felt a bit buried out of the way over on the right when you are on a wide screen.

It is also the symbol for 'Options' or 'Settings'. People are really looking for 'message actions' rather than 'message options' or 'message settings'. A different symbol may help.

Also unlike the thread icon and reaction icon it has no help on hover which is really a bug...... it should have a hover help like 'Message Actions'.

And what about say Mac users? Right clicking for them isn't normal behaviour?

**Comment by korobita** [comment]
i copy code to layout-> custom CSS but not work

**Comment by gabriellsh** [comment]
Hi @ashwaniYDV! Right now we're already rewriting this part of the code, and I think some of the files you edited don't even exist anymore.

I'll be closing this PR for now, but thanks a lot for the time commitment that went into making this. We really appreciate it.

**Comment by Cronus1007** [comment]
@gabriellsh Shall I implement this feature with several modification in this PR

**Pull request closed without merging**
