### PR TITLE
add/remove user to/from room api

### PR DESCRIPTION
**Pull request by yehuditgefen**
@RocketChat/core 

Closes #ISSUE_NUMBER

### CODE REVIEW

**Comment by graywolf336** [comment]
@yehuditgefen Thanks for the pull request, however I see comments in there that it isn't completed. Please comment back and let us know when you are finished.

**Comment by yehuditgefen** [comment]
@graywolf336 removed unnecessary comments.

**Comment by yehuditgefen** [comment]
@graywolf336 can it be merged?

**Comment by graywolf336** [comment]
Closing this in favor of #5140.

**Pull request closed without merging**
