### PR TITLE
Chore: Fix grammatical typo when only one message is pruned

### PR DESCRIPTION
**Pull request by shrinish123**
## Proposed changes (including videos or screenshots)

Whenever only 1 message is pruned it says '1 messages pruned' instead of '1 message pruned' in the toast message

## Steps to test or reproduce

Try to prune only 1 message check the toast message

## Further comments
 
This is done to implement the requested changes on  #21341

### CODE REVIEW

**Comment by shrinish123** [comment]
@KevLehman Please review 😄. I made another pull request to implement the requested changes as the repo linked with that pull request was deleted.

**Comment by sumukhah** [comment]
Hey @shrinish123, 
You can pull the same branch to your local repo (If that is what you were looking for).

**Comment by shrinish123** [comment]
> Hey @shrinish123,
> You can pull the same branch to your local repo (If that is what you were looking for).

No the online forked repo was deleted

**Review by KevLehman — DISMISSED** [review]

**Comment by shrinish123** [comment]
@ggazzo  Please check this PR

**Comment by shrinish123** [comment]
@ggazzo I have made changes as per the current code. Please check.

**Review by ggazzo — CHANGES_REQUESTED** [review]
hey @shrinish123 can I ask you to solve this issue in a "proper" way?
3 points:

1- we don't have `message_pruned` key for english or any "default" language

2- help us stop concatenating strings: (look at the __count__ part)
create the key: `"message_pruned": "__count__ message pruned"`

3- `tap-i18n` has "plural" feature, so change the `"messages_pruned": "messages pruned"` to `"message_pruned_plural": "__count__ messages pruned"`

and use
```
t("message_pruned", { count }) 
```

no need to use if/else

**Review by dougfabris — DISMISSED** [review]

**Pull request merged**
