### PR TITLE
(slash commands) invite all users to another room, create a private channel and send a direct message

### LINKED ISSUE #5240: create a new private group or direct message from the message input window
Your Rocket.Chat version: 0.48.1
command to create a new private group or direct message from the message input window? 
Similar to /create for channels?

i.e.,
`/create #channel|@username public|private`

### LINKED ISSUE #5301: Allow inviting all users from another channel
would be nice to get something like
`/invite #fun`
i.e.
`/invite #fun@all`
i.e.
`/invite_all_users_from_channel #fun`

should be simple to implement but might be really helpful to "move over" some discussions to a seperate channel without "leaving" the other readers but not force them to activly joining the new channel

labels:
* `type: new feature`
* `contrib: easy`

related:
* Allow giving channel permissions to a bulk of users #5302

### PR DESCRIPTION
**Pull request by ggazzo**
@RocketChat/core 
Closes #5240
Closes #5301
## 5301 use
```
/invite-all #room
```
Obs: if the channel does not exist, the command create a new one
image

image

## 5240 use
**part one**
```
/msg @username  <message>
```
Here I found the command "msg" I don't know why it was hidden, but your behavior is exactly the asked.
image
**part two**
```
/create #room --private
```
The second part is about create a private channel, I'm not sure if this way would be the chosen by the team. But I created the a '--private' param. I don't if a new command would be better or not.

### CODE REVIEW

**Comment by marceloschmidt** [comment]
Hi @ggazzo 
Thanks for submitting your code. Could you please rewrite your coffeescript files as js?

**Comment by rodrigok** [comment]
I guess we should have a new setting to limit invite all users from rooms with more than X users, where X could be 100 by default.

Example: prevent users to create channels and invite 100k users from our general.

**Comment by graywolf336** [comment]
@rodrigok It should call the `addAllUserToRoom` meteor method, as that checks this: `RocketChat.settings.get('API_User_Limit')`

**Comment by ggazzo** [comment]
@graywolf336 actually I'm using the `addUserToRoom` method. The `addAllUserToRoom ` adds all users, but I'm adding just the users from active channel, maybe the method could support the user list. 

I added this if
```javascript
if (users.length > RocketChat.settings.get('API_User_Limit')) {
    return RocketChat.Notifications.notifyUser(Meteor.userId(), 'message', {
      _id: Random.id(),
      rid: item.rid,
      ts: new Date(),
      msg: TAPi18n.__('error-user-limit-exceeded', null, currentUser.language)
    });		
}

...
"error-user-limit-exceeded" : "Users limit to add exceeded",
...
```

What do you think? Is good enough?

**Comment by engelgabriel** [comment]
Hi @ggazzo, Great work! The only thing that got me confused, was that I didn't know if I should call invite all people FROM a channel to my current one, or from the current one TO a channel.

Maybe we should rename the current command to `/invite-all-to` and we can create `/invite-all-from`.

What do you think?

**Comment by ggazzo** [comment]
@engelgabriel after you wrote, even having an explanation, could seem confusing.

**Comment by ggazzo** [comment]
I'm not sure, is the same code. Shoud I create another folder... client and server files. or just add 2 methods? like

_packages\rocketchat-slashcommands-inviteall\server.js_
```javascript
RocketChat.slashCommands.add('invite-all-to', InviteAll('to'));
RocketChat.slashCommands.add('invite-all-from', InviteAll('from'));
```

**Comment by marceloschmidt** [comment]
@ggazzo Just use the same package, like you said above :)

**Comment by ggazzo** [comment]
that seems better?
image

**Comment by engelgabriel** [comment]
You just have to change the help text, as the word `actual` is a false cognates in Portuguese, you meant to say `current` rather than `actual`.

Also replace the word indicated by [#room] so it is more clear.

**Comment by engelgabriel** [comment]
- invite all users from [#channel] to join this channel
- invite all users from this channel to join [#channel]

**Comment by engelgabriel** [comment]
We need to make sure the user is a member of the FROM channel, or that is public, and we may want to create a limit on the amount of users, as our GENERAL channel has over 100k members, for instance.

**Comment by ggazzo** [comment]
@engelgabriel sorry, but I didn't understand this part

> ...and we may want to create a limit on the amount of users, as our GENERAL channel has over 100k members...

Ì'm using this value :
`RocketChat.settings.get('API_User_Limit')`

**Comment by engelgabriel** [comment]
API_User_Limit is fine

**Comment by ggazzo** [comment]
Sorry about the delay, I changed the descriptions and created a method `addUsersToRoom `like `addUserToRoom`, there are some test to prevent the concerns about permissions and etc,

I think in the future `addUserToRoom `can use `addUsersToRoom`.

I'm not sure what is the problem about visibility (if I the user is able to invite, I see no problem), so I just created a test:

```javascript
Meteor.call(baseChannel.t == 'c' ? 'createChannel' : 'createPrivateGroup', channel, users)
```
to get the same visibility when a new channel are created.

**Comment by marceloschmidt** [comment]
Instead of `Users limit to add exceeded` please use `The number of users you are trying to invite to #channel_name exceeds the limit set by the administrator`

**Comment by marceloschmidt** [comment]
`/invite-all-to` should probably check if it's possible to invite everyone and if it is, then open that channel before inviting people... as it is now, you have no confirmation that the command is running. If you open that channel, you'll see that people are joining the channel.

**Comment by ggazzo** [comment]
@marceloschmidt sorry, but I don't know why somebody couldn't be invited to a new channel (ignoring the `API_User_Limit)`.

Should not the method `createRoom` do this "notification" like the method `addUserToRoom`? 

I'm asking because I think slash commands shoud have a minimal code and verifications, and the methods should do the rest.

I thought, maybe, some error should happen on channel creation. is that enough?
```javascript
try {
  Meteor.call(baseChannel.t === 'c' ? 'createChannel' : 'createPrivateGroup', channel, users);
} catch(e) {
  RocketChat.Notifications.notifyUser(...)
}
```

**Comment by marceloschmidt** [comment]
@ggazzo I meant the API_User_Limit.

As for you last comment, I don't understand what you meant. But I'll explain what I meant.

When I go to `#some_channel` and type `/invite-all-to #some_other_channel`, it looks like nothing is going on. There's not even a message saying users are being invited... I think the best solution would be to open the `#some_other_channel` so you can see that users are being invited to that channel...

**Comment by ggazzo** [comment]
I'm can't open a created channel after slash command (problably I'm doing something wrong), I have tried a lot of ways (server, client, `Meteor.call(openRoom)`, `FlowRouter.go(..)`) unsuccessfully.

Actually, not even the command `create` open the new channel.

**Comment by marceloschmidt** [comment]
How about `/open #channel_name`?

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (107/100 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:60789 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWnwD-003j8p-4n
	for greg@biomassiv.es; Thu, 26 Jan 2017 11:34:21 -0600
Date: Thu, 26 Jan 2017 04:44:08 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485434648;
	bh=Z1fa4+KMnx0PoWvL9t48CJikuQvK43pm0ywUqt1ijB0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=XBSJh8aPKVeiT4T9fjxY4wkT80+xVdPdh97cQHWuIxFCloVRjF/ml+Hfv6ZodpXxl
	 L2SQAShYvyLTL+oW2HyY9ZhIH+KvH1iig0J/OrksA0jGquM7hBmt54AmOGzw1M7LyJ
	 ZrWL1jSVCFd1G4MaOhD0VY1r6CHc2+qvGLoXZwYc=

**Comment by ggazzo** [comment]
I'm sending a notification now:
```/invite-all-from #general```
image
```/invite-all-from #unknown```
image

```/invite-all-to #newchannel```
image

**Comment by ledainam** [comment]
When i type any command below : 
- invite-all-to
- invite-all-from
it alway show : 
image
i used version 0.51

**Comment by graywolf336** [comment]
@ledainam How are you using the command? Show us a screenshot of the command you have sent.

**Comment by ggazzo** [comment]
I did a simple test here and works..

```javascript 
/invite-all-from #nonexistent
```
image
```javascript 
/invite-all-to #nonexistent
```
image

**Comment by ledainam** [comment]
@graywolf336 i stay at channel #general : this channel have all users. 
I use command below to add all users to channel smchat-hoidap
image
I have admin role also.

**Comment by ledainam** [comment]
@graywolf336 i think that channel general store some user missing  or maybe deleled. 
I use with other channel it successfully.

**Comment by hitochan777** [comment]
Is there anyway to suppress the system message when an user is added to a room?
When inviting a lot of members (e.g., 300 ), it is a bit annoying :(

**Comment by hitochan777** [comment]
I noticed I can suppress system messages in room setting.

**Comment by ruKurz** [comment]
Are there any plans to release this feature?

**Pull request merged**
