### PR TITLE
Livechat Widget Attachments

### LINKED ISSUE #4124: Livechat Attachments
Your Rocket.Chat version: 0.37 

Just saw the PR on integrating videochat into livechat, seems natural to have attachments within the chat client as well.

### PR DESCRIPTION
**Pull request by AlecTroemel**
@RocketChat/core 
Closes #4124 #3686

screen shot 2016-08-29 at 4 00 04 pm  screen shot 2016-08-29 at 4 08 37 pm

screen shot 2016-08-29 at 4 10 32 pm

TODO: 
- [X] Amazon s3 
- [ ] GridFS
- [ ] Local Storage 
- [X] enable/disable through setting in FileUpload page 

Not ready for review, just looking to get some feedback and make sure I'm on the right track. 

I have been using the rocketchat-file-upload package as a base. Works correctly (as far as I can tell) with Amazon s3 but runs into trouble with gridFS and local filesystem.

the gridFS implementation of FileUpload requires `Meteor.fileStore`, which is defined [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/lib/fileUpload.coffee#L18). Feels wrong to just copy-paste the needed code, since that may open a can of worms with dependencies. GridFS and local will both most likely require a subscription to `RocketChat.models.Uploads.model`, though I'm unsure of where that publication is

### CODE REVIEW

**Comment by sampaiodiego** [comment]
oh.. that's nice @AlecTroemel :smile: 

we already have [some](https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/rocketchat-livechat/app/client/lib/fromApp) ["copy & pasted"](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-livechat/app/client/lib/chatMessages.coffee) files from the main repo :disappointed: I don't know what we can do about this.

I was recently looking into [Meteor-Files package](https://github.com/VeliovGroup/Meteor-Files), which should provide even more storage options..

**Comment by AlecTroemel** [comment]
Oooh nice, the Meteor-Files package looks promising :open_mouth:. Just from skimming it looks like it  abstracts out the actual storage used to Client, which would be perfect for the widget where we could just subscribe to that model and not worry about which storage we're using(hope I'm reading the example right). I want to see how far I can get in integrating the package today from a fresh branch

**Comment by AlecTroemel** [comment]
Update on the Meteor-Files: The package causes errors because it is unable to find Mongo.
```
ReferenceError: Mongo is not defined
    at new FilesCollection (packages/ostrio_files/files.coffee:200:24)
```

 I talked with a developer of the package and it's an issue that was resolved in more recent version of the package, but those require a more recent version of Meteor than 1.2.1

**Comment by AlecTroemel** [comment]
with Meteor 1.4 in develop I was able to successfully upload and attach a file in a message using the Meteor-files package! Its supper dirty right now but it seems like things will be a good bit simpler than the current implementation for uploading files (it does more of the work for us). It would also make attachments in the livechat widget easier I believe. I will most likely create a new PR once things are more complete (hopefully towards the end of the week), delete this one, then create a another PR for attachments in livechat further down the road if Meteor-files is where Rocket.Chat wants to go.

**Comment by sampaiodiego** [comment]
cool @AlecTroemel .. please, let me know if you need anything.
thanks again

**Comment by deep0892** [comment]
Does this work for GridFS, i am getting error while using GridFS, i have uncommented the code in of 
GridFs, but getting error 
screenshot from 2016-11-28 16 41 03

**Comment by AlecTroemel** [comment]
@deep0892 Currently not, still pretty experimental and unfortunately only works with amazon s3

**Comment by engelgabriel** [comment]
@AlecTroemel and @sampaiodiego what is pending on this PR? Can help to finish this?

**Comment by AlecTroemel** [comment]
@engelgabriel I got pulled away from this, but have time now. Logistically, I reorganized my workflow after this PR was made, and would need to create a new branch/PR for additional work, thats no problem though. Attachments with s3 through slingshot are currently working, but I'll take a look at the other 2 options again (filesystem, gridFS) to see what problems I was encountering

**Comment by AlecTroemel** [comment]
@engelgabriel @sampaiodiego Alright, my plan of attack was to simply copy the fileupload objects used in the main app for gridFS and filesystem type storage, however both have some issues. 
- With filesystem, the widget does not have any notion of Rocketchat models so this line wont work https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-file-upload/client/lib/FileUploadFileSystem.js#L4
- With gridFS, I get an odd `Uncaught TypeError: data is not an Blob or File(…)` which I'm having problems tracing

If we did switch to using [Meteor-Files package](https://github.com/VeliovGroup/Meteor-Files) I believe this would alleviate the issue of having to reimplement all the storage options in the widget, as you simply subscribe to a publication, though I know we've been trying to avoid subscriptions in the widget. 

I'd want your guys opinion on this before I spend too much time switching to meteor-files or solving those errors listed above with the current implementation.

**Comment by sampaiodiego** [comment]
cool @AlecTroemel .. @rodrigok and @engelgabriel any thoughts on moving to Meteor-Files instead of using "jalik:ufs" + slingshot ?

**Comment by AlecTroemel** [comment]
@here any update on the opinion of Meteor-files. I've done a little testing with reimplementing filesystem with that package. There are some hiccups with protecting files (https://github.com/VeliovGroup/Meteor-Files/issues/159) but seems like everything else is very feasible. I could create a PR with the current progress..

**Comment by sampaiodiego** [comment]
hey @AlecTroemel .. we discussed internally and our intention is to keep with both slingshot and ufs..
so if you need help to make ufs working, please let me know and I will be glad to help you.

**Comment by AlecTroemel** [comment]
@sampaiodiego sounds good! I'll continue looking into ufs and will most likely reach out to you at the demo app.

**Comment by dr-dimitru** [comment]
Hi @AlecTroemel ,

Just saw this thread, about Meteor-Files package and this comment:

> If we did switch to using Meteor-Files package I believe this would alleviate the issue of having to reimplement all the storage options in the widget, as you simply subscribe to a publication, though I know we've been trying to avoid subscriptions in the widget.

It is possible to void subscriptions and show uploaded files via copying necessary fields from "file object" to a message, or any other document.

Let me know if you need a help with integration, I'm ready to contribute.

**Comment by dr-dimitru** [comment]
@AlecTroemel have you ever considered server-less file transferring and messaging, using WebRTC?

**Comment by sampaiodiego** [comment]
@AlecTroemel we're looking to unify file uploads codebase.

it will be easier to add support to any file storage and integrate to livechat.

so I'll close this PR because this code will be deprecated soon and the work to fix the conflicts will not worth it. thx again

**Comment by ccfiel** [comment]
@AlecTroemel @engelgabriel  Any reason why this not merge? :+1:

**Pull request closed without merging**
