### PR TITLE
Regression: Misplaced language dropdown in user preferences panel

### LINKED ISSUE #9882: Misplaced language dropdown in user preferences panel
screen shot 2018-02-24 at 09 38 29

Misplaced language dropdown in user preferences panel (My Account -> Preferences).

Error only occurs in 0.62.0-rc releases.

I'll take this one over.

### PR DESCRIPTION
**Pull request by kaiiiiiiiii**
@RocketChat/core 

Closes #9882

Looks like all the other dropdowns in Rocket.Chat again :)

**Before:**
screen shot 2018-02-24 at 09 38 29

**After:**
screen shot 2018-02-24 at 10 59 49

### CODE REVIEW

**Comment by karlprieb** [comment]
You can set `width: 100%` to `.rc-select__element` and the select will look like this:

image

**Comment by kaiiiiiiiii** [comment]
@karlprieb but is it supposed to look different from all the other dropdowns in the user preferences ui?

**Comment by karlprieb** [comment]
@kaiiiiiiiii no, the other ones are wrong. We didn't updated this page. You can fix that if you want changing all selects to be equal to the language selector.

**Comment by kaiiiiiiiii** [comment]
@karlprieb As far as I can see there's only one other dropdown which is tagged with the `rc-input__element` class. 

Anyway, can you may approve this PR to get a working solution for release 0.62.0 (same look as in 0.61.2) and I'll open another PR which changes all dropdowns in RC?

screen shot 2018-02-26 at 22 45 25

**Comment by karlprieb** [comment]
@kaiiiiiiiii Sure!

**Pull request merged**
