### PR TITLE
Release 6.2.2

### PR DESCRIPTION
**Pull request by sampaiodiego**
`2023-05-19  ·  1 🐛  ·  2 👩‍💻👨‍💻`

### Engine versions
- Node: `14.21.3`
- NPM: `6.14.17`
- MongoDB: `4.4, 5.0, 6.0`
- Apps-Engine: `1.39.1`

### 🐛 Bug fixes

- Livechat `CSP` whitelist validation ([#29278](https://github.com/RocketChat/Rocket.Chat/pull/29278))

  This PR fixes the Livechat CSP validation, which was incorrectly blocking access to the widget for all non whitelisted domains.

### 👩‍💻👨‍💻 Core Team 🤓

- [@aleksandernsilva](https://github.com/aleksandernsilva)
- [@ggazzo](https://github.com/ggazzo)

### CODE REVIEW

**Review by ggazzo — APPROVED** [review]

**Review by KevLehman — APPROVED** [review]

**Comment by asarubbo** [comment]
> ### Engine versions
> * Node: `14.21.3`

@sampaiodiego 

nodejs-14 reached its EOL on 30 Apr 2023 (see https://endoflife.date/nodejs )

Is there a plan to move to 16.x or even better 18.x ?

On Gentoo we have removed 14.x and it causes a bit trouble for new installation.

Thanks

**Comment by sampaiodiego** [comment]
@hey asarubbo , yes. we've been working closely to Meteor folks to update their code to support Node 18.. during last months we've upgraded all our codebase in preparation for this upgrade, we're just waiting for them now.

cc @rodrigok

**Comment by asarubbo** [comment]
> @Hey asarubbo , yes. we've been working closely to Meteor folks to update their code to support Node 18.. during last months we've upgraded all our codebase in preparation for this upgrade, we're just waiting for them now.
> 
> cc @rodrigok

Hello @sampaiodiego , do we have news about this topic?

Just to say more, nodejs-14 needs openssl-1.1.1 that was marked EOL and will be removed [soon](https://github.com/gentoo/gentoo/blob/d2f7750cf28ee82baf5a199720120dbc13880a1a/profiles/package.mask#L202) from the package distribution.
Thanks.

**Comment by sampaiodiego** [comment]
hey @asarubbo .. Meteor has recently started testing out the first builds using NodeJS 18.. we've helped them in a bunch of issues so far.. but looks like it will still take some time.

**Pull request merged**
