### PR TITLE
Added dropdown for message options

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Behavior could probably use some tweaking.  Thoughts @RocketChat/owners? 

image

image

Related to: #828 and #310

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Hold on this.  May close it out.  @rodrigok has something he was trying out that looked much cooler.  :)

**Comment by rodrigok** [comment]
@geekgonecrazy done :)

set 18 2015 12 12

**Comment by geekgonecrazy** [comment]
nice! :+1:

**Comment by graywolf336** [comment]
Is that on hover or on click? Looks like on click, wonder how it would work with on hover..

**Comment by sampaiodiego** [comment]
I think you should not be able to open two dropdowns.. I mean, if you click outside the opened dropdown, it should close.

what you guys mean?

**Comment by rockneverdies55** [comment]
> I think you should not be able to open two dropdowns.. I mean, if you click outside the opened dropdown, it should close.

:+1:

**Comment by geekgonecrazy** [comment]
> Is that on hover or on click? Looks like on click, wonder how it would work with on hover..

Would that get tricky to actually click on one of them?  We can try it

> I think you should not be able to open two dropdowns.. I mean, if you click outside the opened dropdown, it should close.

I agree.  Clicking outside should close it, and it can get messy with multiple up.

**Comment by graywolf336** [comment]
Yes I agree, there should be a max of only one opened up at a time.

I'm wondering if it should show up on hovering instead of clicking on the cog? That way it's one less click?

**Comment by rodrigok** [comment]
@graywolf336, can be on hover, but hover don't work for mobile.

**Comment by graywolf336** [comment]
@rodrigok I would think mobile you would tap and hold the message to bring up a list of actions on the message, like the report abuse way is.

**Comment by geekgonecrazy** [comment]
See f60eadc34

**Comment by rodrigok** [comment]
@graywolf336 I'm thinking something more like this on tap:

image

**Comment by rockneverdies55** [comment]
@rodrigok - This really looks cool.

:+1:

**Comment by graywolf336** [comment]
@rodrigok Oh yeah that'll work too :+1:

**Pull request closed without merging**
