### PR TITLE
[FIX] Channel mentions showing user subscribed channels twice

### LINKED ISSUE #20483: [BUG]While mentioning channel,user subscribed rooms are shown twice.
### Description:
While mentioning the channel in the message, user subscribed rooms are shown twice.

### Steps to reproduce:

1. Select any channel
2. Message box
3.  Type #

### Expected behavior:
All channels should be shown only once.

### Actual behavior:
User subscribed channels are shown twice.

https://user-images.githubusercontent.com/55157259/106182396-c0bc9200-61c4-11eb-8d32-5353c6de4295.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu

### Additional context
Working!

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)

Channel mention shows user subscribed channels twice.

https://user-images.githubusercontent.com/55157259/106183033-b353d780-61c5-11eb-8aab-1dbb62b02ff8.mp4

## Issue(s)

Closes #20483

### CODE REVIEW

**Comment by C1ean** [comment]
Important PR, please approve ^)

**Comment by KevLehman** [comment]
Tested code fix presented in this PR:
Current status [develop]
image

Status after applying changes [develop + this branch]
image

**Comment by KevLehman** [comment]
@Darshilp326, would you mind updating your base branch with the tip of develop? Thanks!

**Comment by Darshilp326** [comment]
@KevLehman Do you meant to update my base branch?

**Review by KevLehman — APPROVED** [review]
Working as expected

**Pull request merged**
