### PR TITLE
Feature option /ignore option, text input,etc

### PR DESCRIPTION
**Pull request by Nemra1**
@RocketChat/Rocket.Chat

Rocket.Chat Need User privacy option to make control about others for example
User1 >ignored User2
User1 > Report Admin About User2
Users Can Enable / Disable Private Chat..
User Can Choose Font option. .like color,bold,italic, Kind Font like important, arial,etc..to add to user text input. .
User Can linked All social account without change default account..

### CODE REVIEW

**Comment by rodrigok** [comment]
This PR looks weird.

Are you just merging 2 of our branchs?

**Comment by Nemra1** [comment]
No its just pull request

**Comment by rodrigok** [comment]
@Nemra1 Ok, you are creating a new PR, but why are you creating a PR with changes I did some time ago in another branch and not related with the description of your PR?

Can you explain if I am wrong?

**Comment by Nemra1** [comment]
im sorry but this frist time to make pull request and im not mean to make that u can delet it

**Comment by rodrigok** [comment]
@Nemra1 Ok, no prob 😄

**Pull request closed without merging**
