### PR TITLE
[NEW] Add "real name change" setting

### LINKED ISSUE #8576: Update Avatar while Profile Change is prohibited
### Description:

After upgrading to 0.59.1 the Avatar settings were merged into Profile settings. To allow avatar updates I have to allow profile changes now which I am not intend to do. I want users to be able to update their avatars while maintaining the display name given by CAS or LDAP.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Debian 8.9
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 12
* DB Replicaset Oplog: Enabled
* Node Version: v4.8.4

### Steps to Reproduce:

1. Set **Allow User Profile Change** to **false**
2. Set **Allow User Avatar Change** to **true**
3. Try to update avatar

### Expected behavior:

**My Account** should list **Avatar**.

**OR**

**Administration** -> **Accounts** should give me the option to set **Allow User (Display) Name Change** to **false**.

### Actual behavior:

Avatar settings are in **My Account** -> **Profile** now, which cannot be accessed with above settings anymore. Thus, you cannot forbid changing the display name while allowing avarar updates.

### Relevant logs:
None.

### PR DESCRIPTION
**Pull request by AmShaegar13**
@RocketChat/core 

Closes #8576 

Added a setting to allow real name updates. This was necessary after avatar updating was merged into profile page. One could not allow avatar updates while forbidding name changes (implicitly with fobidding profile updates at all). I used the exact same logic as the username setting does.

Just one question: How about the languages I do not speak? Do I just omit them or fill i18n JSONs with placeholders?

admin_setting
user_profile
bypass_ui

### CODE REVIEW

**Comment by cyclops24** [comment]
@AmShaegar13 Thanks for this PR. Usually guys fill English and omit other languages for translators.

**Comment by AmShaegar13** [comment]
I added some tests to ensure it's working as intended. Should be ready to merge after checks are green.

**Comment by gdelavald** [comment]
Thanks for your PR, we'll review it and provide feedback when possible.

**Comment by AmShaegar13** [comment]
My new tests are failing. I am still searching for a clever way to make them pass reliably.

**Comment by AmShaegar13** [comment]
Okay, tests are green. I am done. :)

**Comment by ggazzo** [comment]
@AmShaegar13 approved ;)

**Comment by dajoker** [comment]
I see this is still open; has it been merged at all, or could it be?  If working, it s something our users would like.  In our case we have disabled Profile changes, but would like Avatar changes still, so that may not be part of what was originally scoped here.

**Pull request merged**
