### PR TITLE
[FIX] Hightlights validation on Account Preferences page

### PR DESCRIPTION
**Pull request by aKn1ghtOut**
## Checklist

- [x] I have read the Contributing Guide
- [x]  I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes

This PR fixes two issues in the account settings "preferences" panel.
Once set, the "Highlighted Words" setting cannot be reset to an empty string. This was fixed by changing the string validation from checking the length to checking the type of variable.
Secondly, it tracks the changes to correctly identify if changes after the last "save changes" action have been made, using an "updates" state variable, instead of just comparing against the initialValue that does not change on clicking "save changes".

## Issue(s)

Fixes issue #19896

## Steps to test or reproduce

**Reproduce in order.**
- Reload Webpage.
- In Highlights, start editing the "Highlighted words" TextArea. [ Default value should now be "klt" ]
- Delete all contents of the textarea. [ "Save Changes" correctly activates ]
- Click "Save Changes" [ Shows error "[Undefined]" ]

## Further comments

The first issue will affect other settings pages too. There are two solutions I considered to this: The one implemented here or simply reloading the webpage on clicking "Save Changes". The project should pick one approach and that should be implemented for all the settings pages.

### CODE REVIEW

**Comment by aKn1ghtOut** [comment]
@dougfabris should I open a separate issue for the other issue that occurs because of no page refresh?

**Comment by dougfabris** [comment]
@aKn1ghtOut the fix should properly solve both now. Thanks for the help =)

**Comment by aKn1ghtOut** [comment]
Just checked. The "first issue" described above is still there. I do however doubt that it may be out of scope for the Issue being referenced here since it would warrant a uniform approach to solve it on all settings pages.
Can you have a look please?
Hope to be more useful in the future :)

**Comment by aKn1ghtOut** [comment]
I just opened #19927 to allow more space for that bug specifically. If a different issue seems unnecessary, it can be closed and maybe, the discussion could be done on this PR itself.

**Comment by dougfabris** [comment]
@aKn1ghtOut Ok thanks. I'll fix the description and check the other issue separately!

**Review by ggazzo — APPROVED** [review]

**Pull request merged**
