### PR TITLE
Loginform a11y and UX - labels instead of placeholders

### PR DESCRIPTION
**Pull request by pajasevi**
@RocketChat/core 

Hey guys, I made improvements to login form (as well as registration and password reset). I replaced placeholders with labels, because placeholders are bad for UX and a11y and they do not serve the same purpose as labels.

Here is the current state:
original

And here the improvement:
update

I also changed the button text from "Submit" to "Register a new account" so the action is more obvious to user.

Let me know if there is something I should fix in this PR.

### CODE REVIEW

**Comment by rodrigok** [comment]
Hi @pajasevi, this looks awesome.

I did some changes in registration form [here](https://github.com/RocketChat/Rocket.Chat/pull/4073?ts=2), can you fix the conflicts? I added a new setting to add custom fields in registration form, can you test with some new fields too?

Thanks

**Comment by pajasevi** [comment]
Hi @rodrigok , nice changes, I will take a look at that and fix the conflicts. Hopefully tomorrow.

Thank you

**Comment by rodrigok** [comment]
Awesome, thanks

**Comment by geekgonecrazy** [comment]
👍  nice!  I like that style of placeholder -> label.  Good UX IMHO :smile:

**Comment by pajasevi** [comment]
So I merged your changes @rodrigok , I checked it and it should be fine.

merged

Take a look and let me know if I missed something.

**Comment by engelgabriel** [comment]
Thanks @pajasevi 

@rodrigok please review and merge :)

**Comment by geekgonecrazy** [comment]
lgtm 👍

**Comment by pajasevi** [comment]
merge

**Comment by rodrigok** [comment]
lgtm, I'll fix the label for select input

**Pull request merged**
