### PR TITLE
This is for livechat's new feature.

### PR DESCRIPTION
**Pull request by alexdorn87**
Administrator can see the customer's message before he send it.
And it has several fixings of livechat.

### CODE REVIEW

**Comment by rodrigok** [comment]
@alexdorn87 Can you fix the conflicts and ESLint errors?

@sampaiodiego Can you review this?

**Comment by sampaiodiego** [comment]
@alexdorn87 thanks for the contribution =)

can you please describe the fixes you have done?

**Comment by alexdorn87** [comment]
hi @sampaiodiego 

Could you explain more how I can resolve this conflict, please?
When I worked on my localhost, it was working successfully.
I don't understand what is conflict.

**Comment by alexdorn87** [comment]
This feature is for allowing live chat manager can see the customer's inputbox's text before user send it.

**Comment by sampaiodiego** [comment]
@alexdorn87 they are git conflicts.. you have to update your fork with the latest changes and fix the conflicts keeping your changes. [See how to sync your fork](https://help.github.com/articles/syncing-a-fork/)

**Comment by alexdorn87** [comment]
Igor's code is unnecessary for Rocket chat

**Comment by alexdorn87** [comment]
it is for ubegin.com.

**Comment by sampaiodiego** [comment]
@alexdorn87 this is feature is very cool and we would love to have it.

I'll close this PR since it is too old and have too many conflicts. Feel free to submit a new PR. Thanks

**Comment by alexdorn87** [comment]
@sampaiodiego Thank you!
I hope to participate more in Rocket chat project.
I hope to make more contribution on this project!

**Pull request closed without merging**
