### PR TITLE
[FIX] Line breaks with Marked Markdown

### PR DESCRIPTION
**Pull request by Karting06**
## Proposed changes (including videos or screenshots)

Fix missing line breaks when using Marked Markdown. This also fixes ASCII emojis that weren't converted to an emoji.

## Issue(s)

Fixes: #11675 (line break issue)
Fixes: #11214 (emoji)

## Steps to test or reproduce

See details for the line break issue : #11675
## Further comments

The implementation of the _Original_ Markdown in Rocket.Chat doesn't add a paragraph HTML tag to each message (`<p>message</p>`) while Marked.js did. I changed the paragraph renderer to fix that. This also fixed the problem with ASCII emojis (`:)`) not being parsed by the emoji parser.

Marked Markdown also parsed multiple line breaks as a new paragraph while Original Markdown doesn't. I slightly changed the paragraph rule of Marked Markdown (GFM & normal) in order to keep 1 paragraph. The line breaks are now consistent with Original Markdown.

I created one pull request for both fixes in order to avoid to break the line break workaround.

### CODE REVIEW

**Comment by Karting06** [comment]
I noticed that it broke tables when they were sent after some text. I fixed it for tables that are made like this with latest commit:
```
some text

|header1|header2|
|---|---|
|cell1|cell2|
```
but I can't fix it for 

```
some text

header1|header2
---|---
cell1|cell2
```

**Comment by pke** [comment]
Can someone please give this PR a little kick to complete the tests? ;)

**Comment by Karting06** [comment]
@pke I have just updated the branch. I suppose that it will help?

**Comment by mrsimpson** [comment]
@MartinSchoeler can you please re-review? Markdown parsing is still a PITA

**Comment by pke** [comment]
> @pke I have just updated the branch. I suppose that it will help?

Already out of sync with Base branch already 😩

**Comment by Karting06** [comment]
> 
> 
> > @pke I have just updated the branch. I suppose that it will help?
> 
> Already out of sync with Base branch already 😩

Fixed (for now at least ^^)

**Comment by thekief** [comment]
Is there any progress on this? The style sheet changes [1] are a neat workaround for now but a permanent fix would be even better.

[1] https://github.com/RocketChat/Rocket.Chat/issues/11675#issuecomment-853059988

**Comment by pke** [comment]
Maintainers seem to merge all kind of other PRs which brings this one out of sync all the time.
I wonder why this PR is not considered, especially since it fixes a bug that went into the main branch a couple of months ago only. It was working just fine in the beginning of the year.

**Comment by pke** [comment]
I hope @dougfabris is looking into this now ;)

**Comment by Karting06** [comment]
@dougfabris, I looked at it. 
The `InlineLexer` doesn't exist anymore and is in the "normal" `Lexer`. 
`InlineLexer` became `Lexer.rules.inline` and the block `Lexer` became `Lexer.rules.block`. 

The rules for `em` & `strong` were merged into 1 (`emStrong`).
Due to the new marked verison, I created a new PR for this (#23596).

**Comment by dougfabris** [comment]
@Karting06 Can you add the fix for the `MarkdownText` as well?

**Comment by Karting06** [comment]
@dougfabris, do you mean this [line](https://github.com/RocketChat/Rocket.Chat/pull/23596/files#diff-50a814106d086acf6ae0b1f998a6058fc0cf29b2c2032e83d0dcff1715d6303aR18) of the other PR?

In the newer PR, I put it only in `MarkdownText.tsx`. Here, it is in `marked.js` [(see here)](https://github.com/RocketChat/Rocket.Chat/pull/20234/files#diff-aae3ef0d39fdb501488f94f2e645168f16fd8fe83298e7132e24ee00616150d5R13). I didn't see a difference while testing it.

Do you want me to remove it from `marked.js` and put it in `MarkdownText.tsx` or put it in both?

**Comment by dougfabris** [comment]
@Karting06 as I can see we already fixed the main issue: #11675 
Can you provide more details about the real propose of this fix?

**Comment by Karting06** [comment]
Yeah of course @dougfabris.
Without the fix, every message has a `<p>` tag. So, you ASCII emojis aren't parsed if they are at the end of the line. This doesn't happen with Original markdown.
image

Also, if you write the following text (in the compose box as a normal text):
```
test

test
```

It would be rendered as
```
test test
```

**Comment by pke** [comment]
This should really be merged by now. Can't be this problem exists for over a year now. Is nobody using markdown in rocketchat?

**Comment by dougfabris** [comment]
@Karting06 We decided to focus our work on our own parser. Because of that I'm going to close this one. Please if you find any issue or improve please help us on the [package](https://github.com/RocketChat/fuselage/tree/develop/packages/message-parser)
Thank you so much for you help!

**Comment by Karting06** [comment]
Hi @dougfabris,
OK, thank you for the update
If the option `original parser` is not enabled, does that mean that we are using your parser (even if marked is selected)?

**Comment by pke** [comment]
Uhmm why a own parser? Whats wrong with existing ones? The work on markdown parsers has been done years ago.
And it already worked in RocketChat before!

**Comment by ggazzo** [comment]
> Uhmm why a own parser? Whats wrong with existing ones? The work on markdown parsers has been done years ago. And it already worked in RocketChat before!

actually it's not like that, we always had parser problems, inconsistencies and unexpected behaviors, not to mention extra features were almost impossible to add.

to not mention  the fact of having two implementations, that was the first sign that something was not ok.

so we decided that if we were going to have to customize and handle ever single update or change because some library, it made more sense to implement ours. now we can share cross server/desktop/mobile the same parser

this is not something new, our parser is quite mature right now btw

**Comment by pke** [comment]
Understood. Why is RC rendering no line breaks then?
Which version does support basic markdown features?

**Pull request closed without merging**
