### PR TITLE
Fixed crash if a webhook payload had a field named "payload"

### PR DESCRIPTION
**Pull request by bruno-rocha-movile**
@RocketChat/core 

Closes [#5113](https://github.com/RocketChat/Rocket.Chat/issues/5113)

It appears that the Incoming Webhooks script accounted the fact that some JSONs might be packed inside a "payload" field, like the following:

```
{
  "payload": { actual JSON here }
}
```
and started parsing from inside that field, if it was the case.

However, this solution conflicts with the possibility that this field is not a container for the whole thing, but simply another field, like Crashlytics's payloads:

```
{
  "event": "issue_impact_change",
  "payload_type": "issue",
  "payload": {
    "display_id": 123 ,
    "title": "Issue Title" ,
    "method": "methodName of issue",
    "impact_level": 2,
    "crashes_count": 54,
    "impacted_devices_count": 16,
    "url": "http://crashlytics.com/full/url/to/issue"
  }
}
```

This resulted in crashes, so I removed this special treatment.

### CODE REVIEW

**Comment by rodrigok** [comment]
@bruno-rocha-movile Ok, I understand your point, but that is not the best solution cuz you drop support for url-encoded using json payload (slack compatibility)

You can replace the if by
```
if @bodyParams?.payload? and @request.headers['content-type'] is 'application/x-www-form-urlencoded'
```

**Comment by bruno-rocha-movile** [comment]
@rodrigok This does not solves the problem, only shifts it. Services that send url-encoded payloads will have the same problem unless they wrap the payload.

I think the only way of doing this is checking if "payload" is the only field on the payload. What do you think?

**Comment by rodrigok** [comment]
@bruno-rocha-movile I liked your solution :)

**Comment by engelgabriel** [comment]
Thanks @bruno-rocha-movile I am looking forward for the updated PR 👍

**Comment by bruno-rocha-movile** [comment]
Awesome! 😄 There you go.

**Pull request merged**
