### PR TITLE
[NEW] useUserData Hook

### PR DESCRIPTION
**Pull request by ggazzo**

### CODE REVIEW

**Comment by aditya-mitra** [comment]
Just a question, can we use this hook to get the **custom user status text**?

I had made **Pull Request #20257 (Open)** a while back where I had to make a few changes to get the **live user status text**.

**Comment by ggazzo** [comment]
hey @aditya-mitra 
sure! I have created this hook thinking about how to solve the issue you mentioned!

**Comment by aditya-mitra** [comment]
Can I commit and pull request on this branch - `chore/userPresence` so that we can resolve issue #20197 with lesser changes required? 
( I will make a fresh pull request for that and do it today. )
( I will also close PR #20257 as it is outdated now. )

Or should I wait until this pull request is merged?

Thank you.

**Comment by ggazzo** [comment]
> Can I commit and pull request on this branch - `chore/userPresence` so that we can resolve issue #20197 with lesser changes required?
> ( I will make a fresh pull request for that and do it today. )
> ( I will also close PR #20257 as it is outdated now. )
> 
> Or should I wait until this pull request is merged?
> 
> Thank you.

hm... wait a minute I will merge this one today/tomorrow no more, I like the idea to keep it in different prs, AND I think I would make change few things in your pr if I could

**Comment by aditya-mitra** [comment]
Sure.
No problem.

**Review by gabriellsh — APPROVED** [review]

**Pull request merged**
