### PR TITLE
fix: room avatar UnHandledPromiseRejection

### PR DESCRIPTION
**Pull request by hugocostadev**
## Proposed changes (including videos or screenshots)

fixed UnHandledPromiseRejection in a Promise

## Issue(s)

fix https://github.com/RocketChat/Rocket.Chat/issues/31378

## Steps to test or reproduce

1.  Go to Rocket.Chat workspace
2. go to any room
3. Room Information
4. Upload a .ico file in the avatar
5. The dev server will break due to a UnHandledPromiseRejection

### CODE REVIEW

**Review by KevLehman — COMMENTED** [review]
no changeset?

**Comment by hugocostadev** [comment]
> no changeset?

> Since changesets are not for devs, refactors and chore tasks should generally not include one. 

https://developer.rocket.chat/contribute-to-rocket.chat/modes-of-contribution/participate-in-rocket.chat-development/development-workflow#id-4.-adding-changeset-to-your-pull-request

Since this a a chore that does not impact end users I don't think that it's necessary

**Comment by KevLehman** [comment]
Hmmm, if this is causing the server to "die" (on dev), why it's not a `fix`? 🤔 I know on prod it won't die, but there will be the nasty log of "unhandled promise rejection" that scares people out.

**Comment by hugocostadev** [comment]
> Hmmm, if this is causing the server to "die" (on dev), why it's not a `fix`? 🤔 I know on prod it won't die, but there will be the nasty log of "unhandled promise rejection" that scares people out.

@KevLehman Not sure if is best to be a fix or a chore, but either way, does not impact end users... But I'll change back to `fix` thanks for your feedback

**Pull request merged**
