### PR TITLE
Add translation of Edit Status in all languages

### PR DESCRIPTION
**Pull request by sushant52**
## Proposed changes (including videos or screenshots)

Closes [#19915](https://github.com/RocketChat/Rocket.Chat/issues/19915)
The profile options menu is well translated in many languages. However, Edit Status is the only button which is not well translated. With this change, the whole profile options will be properly translated in a lot of languages.

## Initially
Screenshot from 2020-12-20 21-53-21

## Finally
Screenshot from 2020-12-20 21-49-43

## Issue(s)
[#19915](https://github.com/RocketChat/Rocket.Chat/issues/19915)

### CODE REVIEW

**Comment by sushant52** [comment]
@ggazzo Please review the changes

**Comment by sampaiodiego** [comment]
thanks @sushant52 for you contribution..

just one question, have you used an automated tool to get those translation? like Google Translate? we've had bad feedbacks about those translations in the past, that's why we stopped using them, now we wait for our native speakers contributors to help translating all sentences.

**Comment by sushant52** [comment]
@sampaiodiego I have used a mix of Automated Translators(including but not only Google Translate), Online Dictionaries in various languages and also used pre-existing translations of similar words such as "Edit Trigger" to come at these translations. I am a native Hindi Speaker so I can definitely confirm that the translation is correct for Hindi, and if not all the languages, I can definitely help build up the translation dictionary for the Hindi Language :D

**Comment by sushant52** [comment]
@sampaiodiego Any updates on this? :)

**Review by sampaiodiego — APPROVED** [review]

**Comment by sampaiodiego** [comment]
thx again @sushant52 .. really appreciated

**Pull request merged**
