### PR TITLE
[IMPROVE] Added timer in video message recorder

### LINKED ISSUE #16220: [Feature Request] Add timer in video message to keep track of recording
### Description:
While sending video message, it would be awesome if user can also keep track of the amount of recording they have made. So this issue is about adding a timer while recording a video message.

### Additional context
I am working on it.

### PR DESCRIPTION
**Pull request by ashwaniYDV**
Closes #16220 
It has been moved to feature request
https://github.com/RocketChat/feature-requests/issues/262

### After changes:
wer

### Before changes:
viddss

### CODE REVIEW

**Comment by ashwaniYDV** [comment]
@tassoevan @ggazzo Would you please review

**Comment by wreiske** [comment]
I like this! IMO it may be nice to not show the timer until the record button is pressed, but that's just my opinion. 

+1

**Comment by ashwaniYDV** [comment]
> I like this! IMO it may be nice to not show the timer until the record button is pressed, but that's just my opinion.
> 
> +1

@wreiske I too agree with you.
@ggazzo @tassoevan what do you think about this? Please give your reviews too :)

**Comment by ashwaniYDV** [comment]
@wreiske I have done the changes so that "00:00" is not displayed initially :)

**Comment by ashwaniYDV** [comment]
@sampaiodiego Kindly please review :)

**Pull request merged**
