### PR TITLE
docs: update documentation

### PR DESCRIPTION
**Pull request by SANTHOSH-MAMIDISETTI**
## Proposed changes (including videos or screenshots)
fixed the broken [minimum requirements](https://docs.rocket.chat/deploy/installing-client-apps/minimum-requirements-for-using-rocket.chat) and [how can I help](https://docs.rocket.chat/contribute-to-rocket.chat/how-can-i-help) links in [README.md](https://github.com/RocketChat/Rocket.Chat#readme) .

## Issue(s)

fix https://github.com/RocketChat/Rocket.Chat/issues/28746
fix https://github.com/RocketChat/Rocket.Chat/issues/28494

### CODE REVIEW

**Comment by hugocostadev** [comment]
Hi there, thanks for your contribution! 🚀 💯

**Comment by SANTHOSH-MAMIDISETTI** [comment]
> Hi there, thanks for your contribution! rocket 100

This is the first time I ever actually contributed to open-source @hugocostadev  . Thanks sir . I would actually like to contribute to opensource , but don't know where to start hence did that .

**Comment by hugocostadev** [comment]
> > Hi there, thanks for your contribution! rocket 100
> 
> This is the first time I ever actually contributed to open-source @hugocostadev . Thanks sir . I would actually like to contribute to opensource , but don't know where to start hence did that .

This is a great start! Find a project that you are interested in, check the issues, and get one that you think you can fix it!

**Review by hugocostadev — APPROVED** [review]

**Comment by SANTHOSH-MAMIDISETTI** [comment]
@hugocostadev  sir , I didn't understand why the pull request you approved now has not yet reflected in the repositories' main README.md . I mean will it take time to reflect over there (or) it hasn't be merged/ pulled yet ? or any other thing

**Comment by hugocostadev** [comment]
> 

Approve does not mean that the PR it's merged, to be merged the CI (robot) needs to run checks and if everything is correct it'll be merged

**Comment by hugocostadev** [comment]
We are fixing a CI error , after that your PR will be merged

**Comment by SANTHOSH-MAMIDISETTI** [comment]
> We are fixing a CI error , after that your PR will be merged

waiting for it to be done sir , Thanks for the reply 😄

**Review by hugocostadev — APPROVED** [review]

**Pull request merged**
