### PR TITLE
[FIX] Corrected bad words filtering issue

### LINKED ISSUE #16670: Badwords are not filtered correctly in UI
#### These are the issues:-
(1) Bad words are not filtered properly on UI.
(2) If bad words filtering is turned on, then filtering should not be done on previously sent messages.
Currently, if filtering is turned off, then previously sent bad words messages are replaced with  `****`. The expected behaviour is to see actual message with bad words not filtered.

### Steps to reproduce:

1. Go to administration->Message
2. Turn on bad words filtering
3. Type bad words in chats

### Expected behavior:
Correct UI rendering and messages to be displayed in accordance to admin settings for bad words filtering.

### Actual behavior:
Actual behavior is as mentioned in the description.

### PR DESCRIPTION
**Pull request by ashwaniYDV**
Closes #16670

### CODE REVIEW

**Comment by gabriellsh** [comment]
Your changes made it possible to write bad-words inside code blocks:

image

Could you check that? thanks!

**Comment by ashwaniYDV** [comment]
@gabriellsh I have done the requested changes. I have created a seperate function for bad word filter and used it wherever required. 
Please review :)

**Comment by gabriellsh** [comment]
Hey @ashwaniYDV, thanks for the response. Unfortunately, although this really is a problem and we ought to solve it, I'll have to close this.

Firstly, your implementation doesn't cover some cases: 
image

And it probably wont. The renderMessage callbacks won't provide you with a way to fix this entirely. And it's been causing some problems alike. For example, imagine we add a few more renderers, how can we ensure the bad words would still be filtered? What about usernames/full names? Imagine for some reason a URL token has `knob` in it. Will the link become broken?

We're planing on rewriting entirely how the message rendering works so we can prevent lots of problems like these. But right now, whatever way you choose, there will be another little kink to work around. Anyway, thanks for your help!

**Comment by ashwaniYDV** [comment]
@gabriellsh I totally understand. Thanks for the feedback :)

**Pull request closed without merging**
