### PR TITLE
Merge channels and private groups

### LINKED ISSUE #3126: Merge channel and private group lists
I would love an option (or even the default behaviour, I believe it would make more sense) to merge channels and private groups in the sidebar.

Rationale for this:

 - there is already visual feedback to tell channels and private groups apart (the lock icon vs. the # icon)
 - owners can change a channel into a private group at any moment and conversely, which will move the room around in the users’s sidebar and cause confusion
 - when one has many direct messages open, *massive* amounts of scrolling are required to reach the bottom of the sidebar to see private groups

### PR DESCRIPTION
**Pull request by alexbrazier**
@RocketChat/core 

Closes #3126

Merge channels and private groups

image

image

image

image

image

Tasks
- [x] Merge channels and groups
- [x] Allow users to add groups and search for groups from the new merged channel section
- [x] Allow users to select if new "channel" should be a private group or a channel
- [x] Add an admin setting to turn on/off merged groups and channels by default?
- [x] Add a user setting to allow users to individually choose to merge channels and groups?
- [x] Add/change some strings to relate more to the merge e.g. "list of public channels"
- [x] Add public/private dropdown to filter channel search

### CODE REVIEW

**Comment by sampaiodiego** [comment]
cool.. @RocketChat/core any thoughts on this? is this something we want?

**Comment by geekgonecrazy** [comment]
@alexbrazier @sampaiodiego maybe we can have this as an option to combine the lists?

I think a combined channel creation is something that we wanted though.  Listing like I said I think should remain optional.

**Comment by alexbrazier** [comment]
@RocketChat/core I think this is ready for review/merging

**Comment by rodrigok** [comment]
LGTM But I think we should have no option, only the combined mode :)

**Comment by engelgabriel** [comment]
I agree with @rodrigok ... should we do only have the combined mode or merge this now and do that later?

**Comment by geekgonecrazy** [comment]
Maybe we default to combined?  Cause I *think* I and others would like it.  But people might not like it.  So we should give them an option to separate it maybe?

**Comment by graywolf336** [comment]
I think those who like the legacy look and organization, I hated when Slack moved to combined, the option to keep the current organization is best.

**Pull request merged**
