### PR TITLE
[FIX] Fixed a bug where avatars weren't reactive after update

### PR DESCRIPTION
**Pull request by wreiske**
I noticed avatars weren't changing/updating correctly to other users. When you change your profile picture, you'd expect other users to see the change. 

Currently, avatars are cached at a 1-hour cache. Even if you reloaded when someone changed their avatar, it would pull from the cache because _dc always was 0.

### Before
avatar-fix-before

### After
avatar-fix-after

### CODE REVIEW

**Comment by sampaiodiego** [comment]
I noticed that as well when I was testing https://github.com/RocketChat/Rocket.Chat/pull/14053

I have fixed it there and have rewritten many files related to avatar..

**Comment by wreiske** [comment]
> I noticed that as well when I was testing #14053
> 
> I have fixed it there and have rewritten many files related to avatar..

There's still some things in your pull-request that could be merged with this one:

Specifically:
https://github.com/RocketChat/Rocket.Chat/pull/14053/files#diff-d2332873e39c73cb3fecfc555cdda382R30
Instead of doing a math.random for caching, you can just use Date.now() and ensure there will never be a conflict.

**Comment by sampaiodiego** [comment]
agreed.. do you want to target the PR to my branch instead of `develop`? or is it enough if I implement those changes there?

**Comment by wreiske** [comment]
> agreed.. do you want to target the PR to my branch instead of `develop`? or is it enough if I implement those changes there?

I'll close this and you're welcome to just make the change on yours. I'm not too worried about the credit for one line of code change ;)

Thanks!

**Pull request closed without merging**
