### PR TITLE
[FIX][NEEDS INFO] fix android push notification and logic

### LINKED ISSUE #9885: [BUG] Android Push notification is not working
### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: 
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 6.4
* mongoDB Version: 3.2 

### Steps to Reproduce:

1. Sign in by using android phone.
2. close rocket chat app
3. send message from desktop

### Expected behavior:

It shows new message by using notification.
[NEW]
In additional, I hope to change this push notification logic.
I want to receive push notification when I am online, too.
If I am talking in Channel A and User A sends message to me in Direct ChatRoom, I want to receive push notification of it.
So I made some changes on server side, too.
I need to receive current room id from mobile app.

### Actual behavior:
I can't find any push notification on my android phone.

### PR DESCRIPTION
**Pull request by ggrish**
@RocketChat/core 

Closes #9885

### CODE REVIEW

**Comment by rodrigok** [comment]
@ggrish is this PR in progress?

**Comment by ggrish** [comment]
@rodrigok It is completed code.

**Comment by geekgonecrazy** [comment]
Thanks for contributions.  We need to stop though and make sure to fully communicate here.

I believe this is related to this: https://github.com/RocketChat/Rocket.Chat.Android/pull/814

From my understanding the idea would be to set room, and then display notifications for messages sent in rooms not "in"

I think this needs to involve mobile team @rocketchat/Android @rocketchat/iOS because I think for one this might not be necessary to do this.  Two... Might not be how they planned to handle this.

**Comment by rafaelks** [comment]
@ggrish @rodrigok @geekgonecrazy I can see the why of the change now. It makes sense in a way, because we don't subscribe to all the rooms when the WebSocket is opened on the mobile clients, so we cannot know what message was received.

I think this change needs a lot more thought to be made and we need to have a better description on how you want to accomplish that @ggrish. Can you explain better in your pull request description please?

**Comment by ggrish** [comment]
https://github.com/RocketChat/Rocket.Chat.Android/pull/814
https://github.com/RocketChat/Rocket.Chat.iOS/pull/1340

These pull requests are for mobile apps

**Comment by ggrish** [comment]
@rafaelks 
it is for send push notification when user doesn't see room's message.
it doesn't need sockets for every channel.
when new message is arrived, we need to determine whether the user is current open that room.

**Comment by atc07** [comment]
@rafaelks This fix is to receive notifications for all rooms, except for the room a user is currently chatting in when the app is open. If the app is open and the user is chatting with someone in a room, they do not need a push notification also while they are chatting. 

Currently the rocket chat iOS app sends push notifications for a room that a user is chatting in. So as a user is in the room, they will see the message in the room and get a push notification with the same message on the same device. It's redundant and the major chat apps do not handle like this. 

This fix updates the server and should solve the issue for the apps.

**Comment by rafaelks** [comment]
I was thinking about your guys PRs... and let me try to think here if that could be resolved in a simpler way: today, each client have a subscription to each room to listen to changes (new messages, topic changed, description changed, new user, etc). We **could** make a verification in our back-end code that would see if the client is already subscribing to that room via WebSocket and don't send the notification? 🤔

**Comment by atc07** [comment]
@rafaelks That could work. If there is a verification that would see if the client is already subscribing to that room, would that verification be true for all rooms the client is a part of? or just the one the that client currently has open and chatting?

**Comment by reetp** [comment]
Is there anything being done on this ?
Lack of notifications is an absolute killer.

**Comment by sampaiodiego** [comment]
@ggrish I'm sorry for the lack of response. this has become obsolete now as I have rewritten whole notifications logic. 

I'm closing it then. If the current logic is still behaving oddly please let me know.

**Pull request closed without merging**
