### PR TITLE
[IMPROVE] Attachment download caching

### PR DESCRIPTION
**Pull request by wreiske**
This pull request adds a cache to the file-uploads handler to help improve subsequent load times.

Currently Rocket.Chat re-downloads images every time they are viewed / reacted / starred / etc. This commit helps keep images that will never change from being re-requested, and re-downloaded. There's no reason why a file-upload should change. It has a unique ID and will forever contain the same content.

### Before
Screen Shot 2019-04-14 at 1 13 00 AM

### After
Screen Shot 2019-04-14 at 1 11 22 AM

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
I can’t see a reason not to do this.. seems silly not to include this.

@rocketchat/core any reason not to?

**Comment by sampaiodiego** [comment]
@wreiske have you tested in which storage providers? I'm a bit concerned about S3 and GCP storage providers, as they sent a redirect to clients and I'm not sure how clients deal redirects and cache.. If they cache the redirect URL or the content itself..

**Comment by wreiske** [comment]
> @wreiske have you tested in which storage providers? I'm a bit concerned about S3 and GCP storage providers, as they sent a redirect to clients and I'm not sure how clients deal redirects and cache.. If they cache the redirect URL or the content itself..

I have not tested with any other storage providers. If anything, we could add an if statement to check if the storage is local filesystem / GridFS and only set expires that way.

**Comment by d-gubert** [comment]
I've tested this with the Amazon S3 storage. 

It looks like the browser simply ignores the `Cache-Control` header when the also specifies a `Location` header, effectively redirecting that request to even another origin. Since it's being redirected, I figure the browser would respect the `Cache-Control` directive of the external resource instead.

It looks to me that there's no harm in merging this. @sampaiodiego do you think it needs more testing?

**Comment by d-gubert** [comment]
So, further testing indicated that this does introduce a problem after all. I've opened my dev tools in the first attempt, inadvertently disabling Chrome's cache 🤦‍♂️ 

The added header caches the redirect URL sent by Rocket.Chat, but when using S3 and a timeout setting smaller than the specified `Cache-Control`, the browser will eventually end up with a stale URL for the redirecting.

**Comment by d-gubert** [comment]
I'm gonna update it then :)

**Comment by wreiske** [comment]
🎉

**Pull request merged**
