### PR TITLE
fix: Quotes chain off by one error in quote chain limit settings

### PR DESCRIPTION
**Pull request by jayesh-jain252**
## Proposed changes (including videos or screenshots)

Fixed off by one error in Quote Chain Limit. Now if a user sets Message_QuoteChainLimit (default is 2) the number of quotes chained matches the setting.
Changes are made in apps/meteor/app/oembed/server/jumpToMessage.ts file

With Message_QuoteChainLimit=2
Before:
quote_limit2_before

After:
quote_limit2_after

## Issue(s)

#27206

## Further comments

Remaining Changes:
- [x] Message_QuoteChainLimit 1 and 0 results in quote chain of default value 2

TC-256

### CODE REVIEW

**Comment by hugocostadev** [comment]
Hi @jayesh-jain252 thanks for your contribution, I'll review it soon

**Comment by jayesh-jain252** [comment]
If a user sets the value of "Maximum Number of Chained Quotes" setting (at  /admin/settings/Message) 1 or 0, the setting does not apply and quotes chain length remains 2 (default value).

As per my view:
If a user sets "Maximum Number of Chained Quotes" = 0 then there should be no message in quote chain or user should be prompted "not allowed to quote message"
If a user sets "Maximum Number of Chained Quotes" = 1 then there should be only one message in quote chain 
Mock (should work like this):
quote_val1_1  quote_val1_2

But in Both cases (0 and 1) Its get a default chain of 2 messages
quote_val2_2

**Comment by jayesh-jain252** [comment]
Do let me know if my understanding is wrong here

**Comment by hugocostadev** [comment]
You are partially right @jayesh-jain252, in case of 0 as the value of the setting we should consider the same as 1...

I made a commit to complement the task

**Comment by jayesh-jain252** [comment]
I tried logging the data received from data.ts file(/apps/meteor/client/lib/chats/data.ts)
1. When there is no quote data returned is just plain text

No quote

2. When we quote a message data returned is in form of `[ ] (URL) /n message`

one_quote

3. Chaining Quotes for second time. There is no URL present in Quote Preview

no_url

4. If we chain quotes for more than 2 times. There is URL in Quote Preview

url_present

I am guessing that this value of msg is given to QuoteAttachment as text prop
(at apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxReplies.tsx)
But I am not able to understand why URL is shown after chaining for more than 2 times

@hugocostadev would you please guide me on how should I approach this problem.

**Review by guijun13 — APPROVED** [review]

**Comment by hugocostadev** [comment]
> composer/messageBox/MessageBoxReplies.tsx) But I am not able to understand why URL is shown after chaining for more than 2 times

Hi @jayesh-jain252 you can create a separate issue/pull request for that issue, I need to investigate here to check what is happening...

**Comment by jayesh-jain252** [comment]
> 
> Hi @jayesh-jain252 you can create a separate issue/pull request for that issue, I need to investigate here to check what is happening...

Sure, I will do that..

**Comment by jayesh-jain252** [comment]
> > composer/messageBox/MessageBoxReplies.tsx) But I am not able to understand why URL is shown after chaining for more than 2 times
> 
> Hi @jayesh-jain252 you can create a separate issue/pull request for that issue, I need to investigate here to check what is happening...

Hi @hugocostadev, I opened a new PR for the link appearing in quotes preview #28443, so I am removing the second checklist from Remaining Changes.

**Review by guijun13 — APPROVED** [review]

**Pull request merged**
