### PR TITLE
Allow administrators to send e-mail invitations;

### PR DESCRIPTION
**Pull request by marceloschmidt**

### CODE REVIEW

**Comment by marceloschmidt** [comment]
Closes #194

**Comment by geekgonecrazy** [comment]
:+1:

**Comment by rodrigok** [comment]
Where are the prints? :smile:

**Comment by marceloschmidt** [comment]
I don't know how to grab those fancy animated screenshots you like so much @rodrigok but here are my prints ;) 

image

image

**Comment by rodrigok** [comment]
@marceloschmidt http://www.gifgrabber.com/

**Pull request merged**
