### PR TITLE
New eslint rules

### PR DESCRIPTION
**Pull request by sampaiodiego**
New rules are not yet in this PR, I'll release it before merging.

The rules are being implemented by https://github.com/RocketChat/eslint-config-rocketchat/pull/8

I recommend reviewing by commit.

### CODE REVIEW

**Comment by d-gubert** [comment]
Tests passing are a good sign! :D

**Comment by sampaiodiego** [comment]
yep! :D 

what is scary is that the new code (following the new rules) is still valid for current rules :stuck_out_tongue_closed_eyes:

**Comment by tassoevan** [comment]
```js
Im.kinda()
? annoyed
: by(this)
```

**Comment by d-gubert** [comment]
> ```js
> Im.kinda()
> ? annoyed
> : by(this)
> ```

No indentation? 👀

```js
I.would()
    ? beOk()
    : with(this).though()
```

What about you @tassoevan

**Pull request merged**
