### PR TITLE
[IMPROVE] Message rendering time

### PR DESCRIPTION
**Pull request by ggazzo**
the objective here is reduce the computations and finds

### CODE REVIEW

**Comment by wreiske** [comment]
Curious if there are any before/after benchmarks for this?

**Comment by ggazzo** [comment]
@wreiske, actually I dont have graphs yet (I'm working on it now)...
I made that changes because I want to remove the nrr package and in the past, it was almost impossible render messages using blaze, now you can run `localStorage.set('useNrr', 'false')` and test, the speed should be almost the same...

**Comment by wreiske** [comment]
It would be interesting to do benchmarks in the unit tests and save them somewhere. That way, if a test that normally takes 300ms to complete now takes 1s to complete, a red flag will be thrown.

**Comment by ggazzo** [comment]
> It would be interesting to do benchmarks in the unit tests and save them somewhere. That way, if a test that normally takes 300ms to complete now takes 1s to complete, a red flag will be thrown.

yep, actually, for now, we have too many side effects so its quite hard to make a unit test, but part of the rewrite was, in fact, remove some side effects

**Pull request merged**
