### PR TITLE
[NEW] Federation event for when users left rooms

### LINKED ISSUE #16879: When a user left a federated room. The federated server doesn't know it.
### Description:
We don't have the event for this action 
https://github.com/RocketChat/Rocket.Chat/blob/ee85516ecb2ff0c4997518c274c28095b407b24f/app/federation/server/endpoints/dispatch.js#L25

### Steps to reproduce:

Create a room. and a user from the federated server.
if the federated user left the room. I don't know about it 

### Expected behavior:

System message "User left the room"

### Actual behavior:

Nothing happened

### Server Setup Information:

- The version of Rocket.Chat Server: 3.0.3
- Operating System: centos 8 or ubuntu 18
- Deployment Method: Manual
- Number of Running Instances: 1

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: Windows 10

P.S. This action you can reproduce only after applying this pull request 
https://github.com/RocketChat/Rocket.Chat/pull/16878

### PR DESCRIPTION
**Pull request by alansikora**
Closes #16878 
Closes #16861
Closes #16879

### CODE REVIEW

**Comment by 1rV1N-git** [comment]
Hello 
I already write about it
https://github.com/RocketChat/Rocket.Chat/pull/16878
https://github.com/RocketChat/Rocket.Chat/pull/16861
https://github.com/RocketChat/Rocket.Chat/issues/16879

**Comment by alansikora** [comment]
hey @1rV1N-git! Thanks for your contributions!

I will check #16879 and add a fix on this PR as well.

**Comment by ndroo** [comment]
This is likely unrelated but I've found that when I use the mobile client the user being invited into a room bas a weird experience. The room doesnt appear in their list of channels until they click the notification, which unfortunately means if they dont action the notification they never actually make it into the room.

I'm going to verify this today, i was looking at it around midnight after a long day and want to document the actual issue clearly.

**Comment by ndroo** [comment]
I merged all these changes into our test build, they all work really well. Thanks for contributing them. I'll let someone from RC review this, but just wanted to drop a thanks :)

I'm going to look at contributing some other features i.e. having /invite work even when the user has not yet been included from a federation perspective

**Pull request merged**
