### PR TITLE
Add editable channel descriptions

### PR DESCRIPTION
**Pull request by thomasspiesser**
@RocketChat/core 

If applied, this PR will introduce channel descriptions.
bildschirmfoto 2016-07-06 um 12 42 59

### CODE REVIEW

**Comment by rodrigok** [comment]
Do you show this description somewhere?

**Comment by thomasspiesser** [comment]
Yes, on the Room Info Panel. But this is the only place.

**Comment by rodrigok** [comment]
Ok, do you have plans to add that to the beginning of the message's list? Like Slack does?

**Comment by thomasspiesser** [comment]
Atm I didn't, but if you think that could be a good place to show it, we can also add it there.

**Comment by rodrigok** [comment]
No problem, we can add this config now and add the description somewhere later.

**Pull request merged**
