### PR TITLE
Load and clear some cache on login

### LINKED ISSUE #3761: BUG: Cannot Login - Unless I Reload the Browser or App
Your Rocket.Chat version: (make sure you are running the latest)

I don't know if anyone is experiencing this issue, but for some reason when I try to login to Rocket.Chat, my browser or phone gets stuck on the login loading screen. 

When I refresh the browser or reload (force close and run) the app I can log into my account account again. 

I have tried different accounts which doesn't seem to make a difference. 

cannot_login

Syirrus

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

Closes #3761

### CODE REVIEW

**Comment by Syirrus** [comment]
I don't believe this bug has been fixed. Is anyone else still experiencing #3761 that was closed via #4009?  I've updated to the latest and when I logout and try to log back in, I still experience this issue #3761

**Comment by geekgonecrazy** [comment]
@Syirrus just out of curiousity can you replicate it on: https://demo.rocket.chat ?

**Comment by Syirrus** [comment]
@geekgonecrazy I can confirm that it is still occurring. However this time when I logged out and logged back in (I logged in, clicked on something and then logged out) more data appears to be being loaded. I could see that I had some unread messages, but I still received  a loading screen.
This happens on the latest version of Chrome and Safari and within the cordova app.

screen shot 2016-08-18 at 8 05 57 am

**Comment by geekgonecrazy** [comment]
@Syirrus ok perfect.  Yes output will appear slightly different on our Demo server right now.  We're running some code that will be released in the near future.  I just wanted to confirm it was happening even there.

**Pull request merged**
