### PR TITLE
[FIX] room messages direction and 'user is typing' location

### LINKED ISSUE #9214: Reduce white space above messagebox
### Description:

image

Its really only noticeable when you scroll.

I know this area is needed to display the typing indicators.  Not sure how one could accomplish if at all.

@karlprieb is such magic possible? :)

### PR DESCRIPTION
**Pull request by karlprieb**
Closes #9214

Remove top padding of messages box textarea
Changed the rom messages direction from top to bottom to bottom to top
Changed "user is typing" message location

### CODE REVIEW

**Comment by graywolf336** [comment]
I personally do **not** like the change where the user is typing is at the bottom of the scrolling content. If I am scrolling trying to find an old message, I 99.9% of the time want to see when someone else is typing.

**Comment by ggazzo** [comment]
@engelgabriel

**Comment by ggazzo** [comment]
@graywolf336 do you have any suggestion? we had a discussion here #9214 and the PR seems very close.

**Comment by graywolf336** [comment]
Make it like Gabriel Engel said:

> ...we will make it only appear when someone is typing, and we will add a padding so it won't cover the last message when you are scrolled to the bottom.

To me this means it will stay where it has been and then the area will only show whenever someone is typing and not moved inside the dom elements that scroll.

**Comment by ggazzo** [comment]
react native is a little different from this statement...
>@karlprieb let's to this like it is done on the ReactNative app.

**Comment by sampaiodiego** [comment]
I personally think I'll miss the typing indication when scrolling up as well.. so I would like to have it always showing as well (different from what is being currently proposed)

**Comment by ggazzo** [comment]
=/

**Comment by engelgabriel** [comment]
let's merge this like it is, and use it during the release to see if we will really miss the typing info when scrolling.

**Comment by geekgonecrazy** [comment]
I think a lot will miss this.  Every other platform has it visible at all times.

Just earlier I was digging through message history for how I helped someone in the past.  Then I saw someone replying that I knew was involved and would be able to help.  I was then able to just hop back to current messages and they answered and gave the answer.

If you only live in present and never look at chat history this is fine.  But most everyone uses chat history.

**Comment by ggazzo** [comment]
@geekgonecrazy I agree about miss the typing... But there are a lot of clients that scroll the typing (like facebook, hangouts) ok  they are a little different chats but... I think we should discuss more about, or try on 0.66 until the release and admit if got worse

**Comment by geekgonecrazy** [comment]
Sounds like the decision is already made.  Lets make sure this shows up soon on a build on open.rocket.chat so community can give feedback and not leave it until right before 0.66.0 to merge.

**Comment by ggazzo** [comment]
I dont have "powers" to decide, but I can make a huge effort to undo this decision if the community disagree... @rodrigok what do you think about?

**Comment by geekgonecrazy** [comment]
clipboard - june 1

This is how discord does it.  Also how slack does it to my knowledge.  

I think if its no longer visible at all times.. we might as well remove the typing event.  Because its no longer useful.

Kind of like the status indicator by a person.  If we were to put it some obscure place.  If i'm in a DM and their status isn't visible to me at all times... Its really not that useful to even know their status.

If we want to go and change or remove for mobile... That's fine to be like facebook messenger ***shudder*** I suppose we can. Desktop should still be the power user / business user interface.  If I were to gamble... I'd say most "real time' conversations happen on desktop

**Comment by JSzaszvari** [comment]
Sorry, but how is this a 'fix'? 

If anything, at absolute worst this, needs to be an option that can be toggled on or off. **Having these UI changes that nobody has asked for forced on the community is getting awfully tiresome.**

If I am scrolling up to, let's say reference or find a message in the context of a conversation I still need to be able to see if a user is typing as that may affect the flow of the conversation. 

It's becoming increasingly common now that a change that was never put to the community for a vote, Or there is no feature request for, or that nobody has ever mentioned before just all of a sudden is pushed into the project and 'that's the way it's going to be'

I mean no disrespect but one that comes to mind is the UI changes that forced the buttons up the top of the sidebar. I spoke to so many community members that were really upset around this change. I raised a Issue/Feature request asking if this can be a option we can toggle on or off. And it was the quickest issue resolution id ever seen on this project with @engelgabriel closing the issue 5 mins later essentially with (paraphrasing) "No. This is the way it's going to be" 

I f**king love this project, I genuinely believe in it and the purpose/mission behind Rocket.Chat - But if you keep going down this path of making changes that were not asked for instead of fixing existing issues that have been outstanding for god knows how long, Ignoring the community and what they feel should be done, acting like feature requests which clearly have a majority community interest don't exist - This is how Open Source Projects die. 

The last thing I want to see is a Hard Fork of this project because the community feels ignored and like their input means nothing. Throughout history projects have gone down this road and not survived because they adopt the attitude that the maintainers know better than the community. 

Most people in the Open Source world are aware of the OwnCloud vs NextCloud saga. The community and developrs felt like they were being ignored for whatever reason, the project was hard forked and now NextCloud is the platform that everyone uses. 

https://owncloud.org/news/owncloud-statement-concerning-the-formation-of-nextcloud-by-frank-karlitschek/

https://www.cio.com/article/3078173/cloud-computing/owncloud-forked-to-create-nextcloud.html

```His resignation appears to have been sparked by disagreement over the direction ownCloud was taking, with claims that the community's needs were being placed second and the direction sought by investors taking precedence```

Whilst other chat platforms have rapidly been moving forward, each release here sees more and more bugs, regressions that are happening multiple times over different releases and a code base thats really difficult to maintain if you have a custom fork. 

My life is that much harder personally because of all these forced changes, I have a Rocket.Chat deployment with over 8000 users and 500k messages per day, and it's using a lot of custom work we have done in house to achieve this. The fact that I can no longer merge branches because so many changes were forced that nobody asked for, or we were not given the option for means I have to spend 24+ hours cherry picking commit by commit and testing if stuff breaks. 

It's changes like this PR that will result in the downfall of the project, Something will be the straw that breaks the camels back, and us enterprise users will band togethr on a hard fork that is actually maintainable and has a feedback loop of asking wether something is wanted, or at least giving the options. 

Please please please please for the love of this project please asses the path you are going down and ask your-selves if this is really what is in the best interests of the community. 

I'm so passionate about this product, and really beleive in it and the Rocket.Chats team abilities, but Its becoming increasingly harder as time goes on because we are the people at the bottom of the barrel, and treated like we dont exist.

**Comment by Antairez** [comment]
Agree with @geekgonecrazy, this should be a more elegant solution.

**Comment by vynmera** [comment]
**Oppose**: This just seems like a regression - if I didn't know about this whole GitHub, and I just saw the change, I think I'd see it as a bug.

After all:

At bottom -> always visible -> can tell if activity is taking place while not being scrolled down In messages -> only visible when scrolled down -> can't tell if activity is happening without looking

Generally, if I'm already scrolled down all the way, I can already tell how active what people are, the typing indicator would just be an extra.

**Comment by JSzaszvari** [comment]
@vynmera @Antairez Don't hold your breath. 

Unfortunately the trend I have observed over the past 2 years of being involved with this project from the community side is that once @engelgabriel has decided something is going to be a certain way , then that's it. Doesn't matter if 5000 people come out in opposition of the change, it will still be pushed through because @engelgabriel wants it so. 

There won't be any engagement with the community or discussions on how it could be better. It's "I have said it will be this way and thats the end of it" 

It's disappointing and has repeatedly done damage to this project and is essentially the opposite of how a open source project should be run.

**Comment by rodrigok** [comment]
@JSzaszvari for sure this is not a "fix" the title should be fixed :)

AFAIK this is not a decision, it's more a test of UX, and as I could see people is not liking it.

One question, would you miss the information of who is typing if you are looking for information in past messages? Even if we add a ballon popping up from the bottom when there is a new message (I don't know why we removed this).

My point of view is, if you just sent a message you want to know if someone is replying you, so that would make you wait, but if you are focusing your attention to another thing, like scrolling up, the typing information is not important, but a new message indicator is.

**Comment by Sameesunkaria** [comment]
Just my personal opinion, there is absolutely no reason to make it scrollable. It takes up very little space, and it's always nice to know who's typing, even if I'm 1000 messages deep into the history. 🤷🏻‍♂️

**Comment by vynmera** [comment]
@rodrigok First of all, such a bubble doesn't show who the message is by. Aside from how it's simply nice information to have (to unconsciously keep tabs on the discussion), what's the point to hiding it anyway?

**Comment by rodrigok** [comment]
@vynmera Yes, the bubble would not say who sent the message, but the typing does not do that too, you know who typed but you can't be sure who sent a message.

**Comment by engelgabriel** [comment]
@JSzaszvari 

First, let me thank you for the feedback. All feedback is very valuable to us, and in this particular case, I do appreciate it took you time and it was given with passion. Thats why it took me a few days to reply, I needed to take the time digest it and give you an appropriated reply. I strongly disagree with many of your points here, but the fact that you see things this way, is a problem in itself, so I wanted to reflect about before just dismissing it as mere miscommunications. I'll try to go one by one and add some overall consideration on the end.

I am not sure why you say:
> UI changes that nobody has asked for forced on the community

**Comment by engelgabriel** [comment]
@JSzaszvari I am not sure why you think that the following is true:

> UI changes that nobody has asked for forced on the community

All UI changes ever done were either base on community request via issues/PRs or were created to deal with recurring usability issues.

You've mention 2 examples, so I'll comment on them.

# Typing Notification

This very PR is a response to #9214 witch specifically asks "Reduce white space above message box" based on users feedback on the issue and on the forum. So *clearly some people did ask for a fix* to that. 

Now, you may like the proposed solution (with was based on how *Facebook*, *Google* and *Skype* do it), but the fact is that this UX challenge has been meet with 3 different approach by the main chat platform, each with pros and cons.

## Show typing in the message flow

### Skype

screen shot 2018-06-04 at 10 55 49

### Facebook

screen shot 2018-06-04 at 13 42 24

### Google Hangouts

screen shot 2018-06-04 at 13 44 28

- **Pros**: The context area is VERY clear, it is almost like a pre-message. Works well on Mobile

- **Cons**: When you scroll, you cannot see it, but you are notified of new messages.

## Show typing fixed above message box

### Rocket.Chat

screen shot 2018-06-04 at 13 52 44

### Flock

screen shot 2018-06-04 at 11 03 47

- **Pros**: The context area is still clear and you can still see it when you scroll

- **Cons**: Looks odd, and when you scroll, the white space gives you the impression that the UI is broke. 

## Show typing in the header

### Telegram

screen shot 2018-06-04 at 10 56 54

### WhatsApp

screen shot 2018-06-04 at 10 58 10

- **Pros**: You can still see it when you scroll, works well on mobile

- **Cons**: Looks out of place on desktop, its placed on a area of the screen that you are not looking when having a conversation.

## Show typing fixed under message box

### Slack

screen shot 2018-06-04 at 14 20 15

### Discord

image

- **Pros**: You can still see it when you scroll

- **Cons**: Slightly wrong context area to be placed, does not work on mobile.

## Conclusion

The prosed solution has the less cons and more pros, and if combined with better "new message notification bubble" that includes the sender of the message, we may have the ideal scenario.

But we want to test, collect feedback and maybe make the behaviour optional. So this is not being *forced on the community*, but rather we want to run an experiment, I thought I was clear about it.

# Buttons up the top of the sidebar

On this instante you've also mentioned, we did a long research and hired 2 UX design agencies to work on fixing the experience of finding/creating channels and users. The result was not novelty as per example below:

### Skype

screen shot 2018-06-04 at 15 05 43

### WhatsApp

screen shot 2018-06-04 at 15 06 21

### Flock

screen shot 2018-06-04 at 15 06 50

### Telegram

screen shot 2018-06-04 at 15 07 36

### iMessegner

screen shot 2018-06-04 at 15 08 43

### Stride

screen shot 2018-06-04 at 15 13 52

### MS Teams

screen shot 2018-06-04 at 15 21 45

## Conclusion

Our designers usually share links to the mockups on the issues and we collect feedback about it. This is not always the case, and I think we can work on that, but in this case, there was a clear trend in the industry and based on research and feedback we decided to follow. Again, not everyone was happy as many people are averse to change, but after the change we have not received complains about it. Usually when something is very wrong, we received many duplicated issues complaining about it, again and again, until we change it. This has not been the case, and the feedback was overwhelming positive about the new design.

# OwnCloud vs NextCloud saga

I've met Frank personally in USA last year, so I've heard directly from him about the events. It was a complex different scenario: the ownCloud project was forked by its own creator, the CTO of the company for having disagreements with investors.

# Contributing Back

> My life is that much harder personally because of all these forced changes, I have a Rocket.Chat deployment with over 8000 users and 500k messages per day, and it's using a lot of custom work we have done in house to achieve this. The fact that I can no longer merge branches because so many changes were forced that nobody asked for, or we were not given the option for means I have to spend 24+ hours cherry picking commit by commit and testing if stuff breaks.

It's great to hear about your customisations for scalability improvements. Are you going to open a PR with those changes? 

This way **you'd not need to keep merging them back** on each release.

*PS. I'll continue in another comment.*

**Comment by geekgonecrazy** [comment]
In the cases of messages being in context of conversation those are 1:1 conversation and platforms in those cases makes a lot of sense.

Thought came to mind... 

If we want to try to see how people like this.  Can we maybe make it look a little nicer?  Hangouts specifically I always liked because of how it showed the avatar.

Maybe in addition... when scrolling back in history we could show below the message box?

The UI across mobile and desktop would look same + that information we crave would be visible on desktop.

Just a thought.

**Comment by rodrigok** [comment]
@geekgonecrazy we could even create a bubble to show the typing information when scrolling, that could be optional if some people thinks it is annoying, it would be easier to have as an option.

**Comment by mrsimpson** [comment]
Hi guys,

I am reading this discussion (particularly the non-feature-related aspects) with great interest and concern.
All people involved here are highly regarded by myself and it hurts to read this kind of disagreement. Though it’s tricky to convey the core of what’s in my head in a foreign language, let me try to add something on the meta-layer. 

The facts I extracted:

- There’s a change to be introduced which is very visible to end-users and which implementation is subject to different opinions
- A part of the people contributing time and effort to the software proposed this change – communicated with this PR. I don’t even see a “company boundary” here since parts of the RC-company also got diverse opinions.
- Since there is objection that this implementation resolves more issues than it creates, it raised the question of how the *larger* community is currently valued when deciding for how the product changes. Some already expressed their unhappiness with the as-is.

I believe that both discussions are well justified. And that they take place is a sign for a (still) intact community. Thus, I pledge

- Continue both discussions. Try to avoid sarcasm as it is hard to be conveyed properly in a written form. Express your opinion and perception as your perception.
- Discuss the PR here (whether it should be configurable, done, tried, changed at all). This is why all these changes happen in public – so that they can be discussed by everybody.
- Open another thread (maybe in the forum, maybe in another issue) about how RC and its community interact. The RC-core team shall decide upon the format and set it up.

I’ll join both the discussions separately.

Oliver

**Comment by mrsimpson** [comment]
@engelgabriel you once said about a contribution: "If it's configurable so that it doesn't affect the current users, you can contribute it".
Is this still the paradigm which the maintainer of the project follows?

**Comment by Sameesunkaria** [comment]
Here are a couple of possible solution:
- Place the typing indicator under the text field, just like slack does.
- Make the typing indicator animate in to its current position when someone is typing, and hide under the textfield when its not required. (something similar to how the iOS native app handles it)

**Comment by vynmera** [comment]
How's something like this mockup? The gradient could even get smaller if there's nobody typing.

Mockup

**Comment by ggazzo** [comment]
w

**Pull request closed without merging**
