### PR TITLE
[IMPROVE] Replace Site_Name and Site_Url config name

### PR DESCRIPTION
**Pull request by dougfabris**
## Proposed changes (including videos or screenshots)

image
image

## Steps to test or reproduce

- Go to Admin > General 
- Check the new labels Workspace URL and Workspace Name instead of Site URL and Site Name

### CODE REVIEW

**Review by sampaiodiego — CHANGES_REQUESTED** [review]
@geekgonecrazy how this affects Cloud? I'm wondering if we can keep the setting name but change only the label.

**Comment by geekgonecrazy** [comment]
Yeah I think us and a few deployment methods.  Alternatively could just take and if those are set via environment variable drop them into new setting?  At least in interm?

**Comment by murtaza98** [comment]
FYI: Some of the omnichannel apps are also accessing the `Site_Url` setting value. Any suggestions on how to handle this without publishing a new version of the app?

**Comment by dougfabris** [comment]
@murtaza98 we are checking a way to change just the label as @sampaiodiego suggested

**Comment by sampaiodiego** [comment]
thanks @dougfabris .. thinking more about this, I realized that we should consider changing a setting as a breaking change.

I think having this definition will help us making the decision whether we should change it or not.

**Pull request closed without merging**
