### PR TITLE
[NEW] Hide inactive rooms

### PR DESCRIPTION
**Pull request by mrsimpson**
## What this adds

As time does by, users are being subscribed to many rooms. The left-hand side navigation gets messy. This PR adds an action for the user to hide inactive rooms.

Note the read conversations vanishing ;)
_Remark: the icon is `eye-off` - it's just not shown on my local dev-env_

## How this is implemented

- It adds an option to the sort-list. There is no better place for cross-room-actions, imho - the user preferences would be too far off.
- With a modal, a user can define how old the minimum age is for rooms to be hidden.
- Favorites and unread rooms are exempted
- The implementation is similar to the normal hide-leave-actions with respect to package and model assignment.

## What could be improved

- Default value for the modal. This needs a modification of the modal (`modal.html, line 36ff ({{#if input}})`). I didn't do this since it's a reuse component and wanted to get your feedback first.
- Create a regular ob and have the age defined by each user in its preferences (might be a second PR)

### CODE REVIEW

**Comment by kaiiiiiiiii** [comment]
IMO the user preferences are the perfect place for such settings. It’s something you may change once in a while, but nothing that needs to be super accessible :)

**Comment by mrsimpson** [comment]
@kaiiiiiiiii if it was "only" a setting ("every day, hide rooms which have not been active for n days"), I'd add it to the user preferences. 
Adding an action ("a button") in the preferences feels a bit awkward.

**Comment by graywolf336** [comment]
I like the way this one is set up, as the user preferences feels hidden.

**Comment by mrsimpson** [comment]
@ggazzo Nobody cared about this change so far - and I think it should be implemented properly. Can you or someone from @RocketChat/core please give some feedback on whether this feature is desired?

**Comment by mrsimpson** [comment]
Closing this MR since I'll not be adapting it for a merge. However, I consider the feature elementary, but with another implementation

**Pull request closed without merging**
