### PR TITLE
[WIP] RTL Support

### PR DESCRIPTION
**Pull request by shahar3012**
This is a work in progress of Rocket.Chat RTL Support. The work is not finished. I didn't know where to put the .rtl class in the html file, so I use the addClass method in layout.coffee. Please write down suggestions to cover all the missing elements that need to be supported and **don't** accept this pull request yet, until final version.

### CODE REVIEW

**Comment by shahar3012** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/165

**Comment by engelgabriel** [comment]
Looking good! The place where you added the .rlt support seem right, it just need a logic test to check if the user is using a rtl locale?

**Comment by shahar3012** [comment]
I think so. I suggested earlier that the layout change should be based on the language, and that the language can be changed from the settings section.

**Comment by shahar3012** [comment]
I've commited a several changes mostly to the side-nav elements.

**Comment by engelgabriel** [comment]
Seem all good. Should I merge it now and create the language selection option?

**Comment by shahar3012** [comment]
You can. I think it's  good enough. The language selection option is mandatory!  :)

**Pull request merged**
