### PR TITLE
This allows to use user session specific custom css

### LINKED ISSUE #5469: Add user session specific class or attribute to manipulate with custom css
Your Rocket.Chat version: 48.1

This is a feature request. It is already possible to alter the style of messages from specific users with the attribute selector for the data-username attribute. It would be really awesome, if it would additionally be possible to alter the css just for specific users, by adding a session specific class or attribute to be used with selectors. I don't know if this is something which is desired by the dev team and how this could be made possible in the best way, but I could eventually invest some time into trying to implement it, if I get some feedback.

### PR DESCRIPTION
**Pull request by saram-kon**
sessions_specific_css

@RocketChat/core 

Closes #5469

This allows to have user session specific custom css. The gif shows, that the css sets the color of al div elements red for the admin user, but the test user is not effected.

### CODE REVIEW

**Comment by graywolf336** [comment]
Thanks for this pull request, it is an interesting idea. However, at the moment we aren't interested in doing a per user item and instead we should go for roles.

**Comment by payafterwork** [comment]
session-username no longer works. 

How to achieve this now? Please help.

@strangerintheq  @graywolf336

**Comment by payafterwork** [comment]
> Thanks for this pull request, it is an interesting idea. However, at the moment we aren't interested in doing a per user item and instead we should go for roles.

session-username no longer works.

[session-username="admin"] doesn't work.

How to achieve this now? Please help.

**Comment by payafterwork** [comment]
> sessions_specific_css
> 
> @RocketChat/core
> 
> Closes #5469
> 
> This allows to have user session specific custom css. The gif shows, that the css sets the color of al div elements red for the admin user, but the test user is not effected.

session-username no longer works.

[session-username="admin"] doesn't work.

How to achieve this now? Please help.

**Comment by payafterwork** [comment]
@rocketchat-github-ci  @graywolf336  Can you please help with this?

**Pull request closed without merging**
