### PR TITLE
Custom emoji

### LINKED ISSUE #1723: Custom emoji
It would be nice to be able to add custom emoji, just like how it's done on slack: 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29311916-custom-emoji?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nokobon**
@RocketChat/core 

Closes #1723

Changes:
Switched to a common package for handling emoji (rocketchat-emoji-base); new sets of emoji can be added by creating new packages
Changed rocketchat-emojione to work with rocketchat-emoji-base
Created a package to support custom emoji (rocketchat-custom-emoji)
Emoji-only messages now enlarge multiple emoji instead of only working when one emoji is used

Notes:
Uses the permission manage-emoji for adding/editing/removing custom emoji
Picker/autocomplete works as normal for default/custom emoji
Reactions and webhook avatars also work as normal

Screenshots:
image

image

image

image

### CODE REVIEW

**Comment by xandershelley** [comment]
Looking forward to it, thanks!

**Comment by sampaiodiego** [comment]
This is looking awesome @nokobon ... many thanks!!! :smiley: 
@RocketChat/core please take a look on this

**Comment by graywolf336** [comment]
Is this finished and ready to be looked at? As this is awesome and one of the more requested features :+1:

**Comment by nokobon** [comment]
Yes, I'm finished with it. As far as I'm aware, there are no issues and custom emoji should work everywhere the default emoji worked.

**Comment by graywolf336** [comment]
What happens when a user disables in their preferences displaying emojis?

**Comment by nokobon** [comment]
If a user disables displaying emojis, they aren't displayed.
image

**Comment by graywolf336** [comment]
Awesome thanks! I will try this out later on today :+1:

**Comment by Molle500** [comment]
Is it optional if the server owners wants the users to be able to upload custom emojis?
Should be a allow/disallow setting in admin panel :) Perhaps in the permissions so we can even set which rank should be allowed to do it

**Comment by rodrigok** [comment]
Maybe should we use a new permission for that rather than `manage-assets`?

**Comment by nokobon** [comment]
Would it really be better to add a whole new permission just for emoji? Currently, all I see `manage-assets` used for is changing the logo and favicon.
I have no problem with it requiring a different permission, but it seems slightly unnecessary to create a new one because I think `manage-assets` fits.

**Comment by xandershelley** [comment]
Maybe a permission for uploading a custom emoji, and then use the manage-assets permission to change what emoji-packs are used? That way users can upload custom emojis without being able to edit server assets.

**Comment by rodrigok** [comment]
@nokobon IMHO we have 2 problems

1. It's not clear that you need to have `manage-assets` to manage emojis
2. As @xandershelley we could have an permission where users can upload and manage they own emojis (but we can implement this in the future)

**Comment by dbushong** [comment]
Does giving, e.g., Moderators `manage-emoji` permission do anything useful at the moment (if they aren't an Admin)?  I only see the Custom Emoji panel in the Admin section - is this just prep for future enhancement?

**Comment by sampaiodiego** [comment]
@dbushong you can assign any permission to any role at the moment.
so the answer is no, you can't do anything useful doing this. :wink:

**Pull request merged**
