### PR TITLE
[FIX] Create direct message from search

### PR DESCRIPTION
**Pull request by debdutdeb**
## Further comments

Probably not the best solution but it works :/

### CODE REVIEW

**Comment by ankar84** [comment]
Hey Deb!
What that PR should fix?
Creating DM was fixed in https://github.com/RocketChat/Rocket.Chat/pull/24623
Is your case still not fixed?

**Comment by debdutdeb** [comment]
Screenshot_2022-03-11-11-49-36-157_com android chrome
No looks like it hasn't.

**Comment by debdutdeb** [comment]
Closes #23041

**Comment by ankar84** [comment]
> No looks like it hasn't.

Try develop branch.
I tested - all works perfect. 
Fix not in 4.5.1

**Comment by debdutdeb** [comment]
Ah crap. Thanks for confirming :P

**Comment by debdutdeb** [comment]
@ankar84 can you double check please? I just heard that this is not working in 4.5.2 :/

**Comment by ankar84** [comment]
> @ankar84 can you double check please? I just heard that this is not working in 4.5.2 :/

I will do it today, because it was all perfect in develop branch...

**Comment by debdutdeb** [comment]
Hm thanks. I'm outside so can't test it rn.

**Comment by pierre-lehnen-rc** [comment]
The search result was generating a link with the user id instead of the username, but that was fixed on #24955, so this change will no longer be necessary.

**Pull request closed without merging**
