### PR TITLE
[WIP | NEW] Dark theme!

### LINKED ISSUE #1887: Theme as a per-user configuration
Themes should be configurable by each user for himself, and not only as a global, administrative theme.

### LINKED ISSUE #6405: Feature Request : "night / dark mode" switch available to users
I'm from the "blue light" fighters team and work (i guess like many of you) on screens a big part of the time, and my users too. One of the first thing that was asked to me when introducing Rocket : "does it have night mode ?"

I know we can redesign through the admin but i though it would be awesome (and not that complicated ?) to **add a Dark/light theme separation and let the user choose one or another in his parameters**.

### PR DESCRIPTION
**Pull request by vynmera**
Closes #6405
Closes #1887 (partially)

This PR adds an option in user preferences to enable a dark UI theme. It syncs across clients and looks nice. It's also good at night, and for people who wish or need to protect their eyes from bright pages.
I could type here for ages, but I feel the images will speak for themselves.

_Main screen_
Main

_Sidebars_
Sidebars

_Popouts_
Popouts

_Dialogs_
Dialogs

_User preferences_
User preferences

_Admin tables_
Admin tables

_Admin settings_
Admin settings

It adds user preference field `usedTheme`.

Although I believe I have checked every nook and cranny, there may be issues. So please look through it all, and report on any unstyled/badly styled components, or things you'd like to see improved.

:heart:

### CODE REVIEW

**Comment by engelgabriel** [comment]
@vynmera this is an awesome work! Do you think that rather than supporting only light/dark themes, we could make it in a way to support multiples themes? So we could allow the admin to create as many themes as they want, and allow the users to choose from them?

**Comment by vynmera** [comment]
@engelgabriel That's a good idea! What kind of storage format would we want for this, though? It should be possible to store an entire theme in just one JSON file. I'd take it we add a menu in administration, called Themes, and allow the admins to create or import themes there.

**Comment by HammyHavoc** [comment]
Perfect! This is some brilliant work!

**Comment by vynmera** [comment]
@engelgabriel Sure, that should be possible. Can you give me a few hints to get started though? I'm mucking about with models right now, but I can't seem to get anything to work yet :relaxed:

**Comment by engelgabriel** [comment]
@ggazzo @karlprieb can you help here?

**Comment by rafaelks** [comment]
We've iOS themes already implemented too (adding @Sameesunkaria here)... what do you guys think about doing them on the same "structure"?

Heres the PR: https://github.com/RocketChat/Rocket.Chat.iOS/pull/1602

**Comment by Sameesunkaria** [comment]
@rafaelks Right now, i'm in talks with @thiagosanchz . We'll be probably end up finalizing the colors.

But I can implement a translation, when @vynmera gets around to saving it as a JSON. If this is implemented as a server preference, we can send the theming info to the devices as well.

**Comment by vynmera** [comment]
Perhaps a JSON schema like this could work? (I'm not too good with this, so I just adapted the way I added the dark theme into JSON)

https://gist.github.com/vynmera/e129d2794c8f4ef406753b90339e6a6d

`schema.txt` shows the way the JSON is built up, so does `generic_theme.json`, whereas `rc_dark.json` would be the current version of the dark theme implemented into the JSON format.

**Comment by geekgonecrazy** [comment]
Not sure how I missed seeing this sooner.  Super cool!

One thing I would say is would love to see dark theme look the same as iOS's :)  This looks like iOS's black theme.

To me this schema looks like a great start

**Comment by Sameesunkaria** [comment]
@vynmera I could share the colors for the dark and the black themes on iOS, if you'd like that.

**Comment by Max-Github** [comment]
Any updates regarding when this planned on being added?

**Comment by Sameesunkaria** [comment]
@vynmera do we have any updates on this PR?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by senpl** [comment]
@engelgabriel Could someone with write acess make code review??? There nothing fancy in this changes. Thanks in advance.

**Comment by HammyHavoc** [comment]
@piotrkochan But that sets it for every user, correct? If so, that's terrible for accessibility. We have a legally blind employee, he would benefit massively from this, but some users don't want a dark theme because they find a brighter UX easier on their eyes for all-day use.

Having a dark and light option in apps is considered good accessibility practice now. Even YouTube and Twitter have it.

**Comment by rafaelks** [comment]
Any way we can get this theme applied by default (or some "Automatic" setting) based on the OS theme? Now that macOS Mojave supports Dark Theme that would be very interesting I think.

More info about that here: https://blog.iconfactory.com/2018/10/dark-mode-and-css/

**Comment by tassoevan** [comment]
Some styling is outdated, but just a few adjustments would be enough.
However, I wonder if we should support two sets of colors and provide a switch for users or go to a more general approach enabling more themes and some logic to activate them. A bad decision here will leave a lot of issues regarding backward compatibility. Thoughts?

**Comment by piotrkochan** [comment]
I hope this code will not break https://github.com/0x0049/Rocket.Chat.Dark theme compatibility.

**Comment by HammyHavoc** [comment]
@tassoevan How does this sound?

Rocket.Chat _should_ ship with both a light and a dark mode in terms of OOBE, that's just modern accessibility, and what's expected, even Facebook Messenger has a dark mode now. The light and dark modes _should_ be treated as a switch for two theme files. This would allow the default themes to be treated as a starting point for other themes that users can then install.

Ideally, these themes would sync between user devices just like messages do, or, if the user desires, they can set a theme per-device, or have it change based on time of day as I know some people like to do that since iOS started doing it.

In terms of user-configurable themes, it should work similarly to Windows 10; there's a standard dark and light mode, users can choose an accent colour if desired from some preset colours, however, they can also roll their own themes. I personally feel like Microsoft really nails making this easily understandable and accessible on Windows 10.

**Comment by keegandent** [comment]
The importance of having a dark theme option in a chat application dwarfs the importance of having many theme options. Right now the only desert you're serving is vanilla, so I'd say get chocolate in there before thinking about potential other flavors which nobody has really asked for yet. Many seem to be interested in just a dark theme, but that's just my $0.02

**Comment by rafaelks** [comment]
> The importance of having a dark theme option in a chat application dwarfs the importance of having many theme options.

Agreed. I think we can have the initial merge just by having Light and Dark themes, just like [we did with the iOS application](https://rocket.chat/2018/07/17/ios_3_0_0_released/) and in the future, if very there's too many requests, we can discuss all the complexities about letting the users (or admins) create their own themes.

**Comment by tassoevan** [comment]
@rafaelks Could you make a new issue about detection of dark mode for macOS Mojave? This need some extra work a little out of the scope of this pull request.

**Comment by tassoevan** [comment]
For now, everything looks fine. I renamed this feature from *dark theme* to *dark mode* because @HammyHavoc made interesting remarks about the dark mode as an accessibility-related feature; this implies that we need to change the *Theme* select box of Account Preferences to something like "Appearance".

**Comment by piotrkochan** [comment]
Finally.....

**Comment by buczo23** [comment]
Almost there ❤️

**Comment by marcinkorzycki** [comment]
1.0.0 released - still lack of dark theme...

**Comment by tripout** [comment]
> 1.0.0 released - still lack of dark theme...

1.1.0-rc2 and still no dark theme.

**Comment by Sparkrdom** [comment]
Bump to this. Definitely a highly requested feature.

**Comment by keegandent** [comment]
^ Agreed, is there something that can be done to make this a greater priority in the process?

**Comment by tassoevan** [comment]
https://github.com/RocketChat/feature-requests/issues/143

**Comment by tripout** [comment]
One day I hope that I will be able to view the dark theme in Rocket Chat without using some sort of hack.

Version 2.2.0 and still no dark theme :(

**Comment by foss-** [comment]
What is missing for this to be merged? Maybe moving some features like automatic system mode detection to a followup PR would help to get this merged?

**Comment by Molle500** [comment]
Is this one never going to be implemented? :( So the users can pick dark mode themselves if they want to in the browser / desktop app.

**Comment by rataman098** [comment]
Any news on this?

**Comment by sevikerr** [comment]
Any news about feature?  😊

**Comment by brittyazel** [comment]
I came across this mod that does something similar, albeit with a switchable night/day mode:
https://github.com/pbaity/rocketchat-dark-mode

Perhaps some of these ideas can be coordinated. I like having the quick access toggle for night/day.

**Comment by ankar84** [comment]
> I came across this mod that does something similar, albeit with a switchable night/day mode:
> https://github.com/pbaity/rocketchat-dark-mode
> 
> Perhaps some of these ideas can be coordinated. I like having the quick access toggle for night/day.

Installed that Dark Theme, works good!
User can switch dark\light by themselves
image
Install is very simple.

**Comment by jeroenpraat** [comment]
What is the reason this is not implemented (besides the conflicts)? This is a accessibility issue and should be a default option in every software project.

**Comment by tassoevan** [comment]
We're not going to merge this implementation of dark theming. It's a bummer, but we'd like to reaffirm that it doesn't mean we aren't interested in bringing the dark theme experience for Rocket.Chat. The main reasons for not accepting it are:

- duplicating the number of color settings adds an unfair overhead to server admins that would have to configure the server theme twice;
- modern UIs are adopting a three-brightness scheme, i.e., light, dark, and black variants (e.g. Twitter's client);
- there are three competing ways to style Rocket.Chat at the moment -- a legacy LESS file, some non-standard components and the newest [Fuselage](https://github.com/RocketChat/Rocket.Chat.Fuselage);
- there is a [work in progress regarding accessibility](https://github.com/RocketChat/Rocket.Chat/pull/16498) which may be impacted by this;
- handling dark mode color schemes while keeping it consistent to our white-labelling policies is hard and currently there is no guidelines to do it (the design team is aware of it at the time).

Apart from all these blockers, the frontend team is engaged to make [group direct messages](https://github.com/RocketChat/Rocket.Chat/pull/9106) happen ASAP. If you think it should have a higher priority in our milestones, please add your remarks to [this feature request](https://github.com/RocketChat/feature-requests/issues/143).

**Comment by keegandent** [comment]
It’s more than a little unfortunate you guys took over a year to finally shoot down a solution that worked well, and with no good alternatives. No offense, but custom color schemes should really take a back seat to “please stop sending so many lumens into my retinas”. I don’t see why it was a priority to give server admins so many color scheme configuration abilities before this simple accessibility setting was available to the client. At the end if the day, if the end user hates what they see, they’re going to hate the application, regardless of whether it’s actually the server admin who made the color decisions.

**Comment by mribeiro** [comment]
One of things I don’t get is why themes are set on server side. It’s just they way it looks, it should be a user decision whether the like the app more in blue, red or black. Or at least let the admins let the users manage it.

Bad bad thing to do when there are tons of people expecting this in a PR that has been  opened for so long.

**Comment by keegandent** [comment]
@mribeiro I definitely get why global customization is a nice feature to have, especially if you’re using this in a corporate setting and would like it to match your company colors. However, giving users the ability to change their own color scheme from a set of at least two standard themes (ahem, light or dark) would seem to be more relevant to everyday use.

Also @tassoevan I looked at that PR for group messaging and, all respect to the people who really want that feature, they already have that capability with private groups and are just upset that it’s not totally convenient. We had a team of a few dozen people using this application and I can’t remember once somebody complaining about that, just saying. Nearly every team member under 35 was upset by the lack of a dark theme.

**Comment by recklessnl** [comment]
Fully agree with the comments above. It's disappointing to see it take this long to add a proper dark theme when they're more or less common now for most major applications.

Please reconsider your stance and take this issue more seriously. As you can see from the comments, this is high on the wishlist of many users.

**Comment by tassoevan** [comment]
I'm sorry that I wasn't clear, but my comments address **this pull request only**. As stated before:

> we'd like to reaffirm that it doesn't mean we aren't interested in bringing the dark theme experience for Rocket.Chat

If there are no particular remarks about **this pull request**, only the dark mode feature: please comment on https://github.com/RocketChat/feature-requests/issues/143 to reiterate how important is this feature for you.

**Comment by gerroon** [comment]
Is this going to be implemented in the new versions?

**Comment by fumin** [comment]
Still no dark theme on 25th December, 2021!?!?!?
Even a monkey knows how to code a dark theme.

**Pull request closed without merging**
