### PR TITLE
[NEW] Allow "Owner" permission in direct channel

### PR DESCRIPTION
**Pull request by vova-zush**
[NEW] Allow "Owner" permission in direct channel

## Proposed changes (including videos or screenshots)

  Allow "Owner" permission in direct channel

### CODE REVIEW

**Comment by ggazzo** [comment]
is there any reason for that? I dont think we should have an owner for direct message, doesnt make sense for me @sampaiodiego what do you think?

**Comment by vova-zush** [comment]
the main reason for this pull request was that users can't prune message in direct message

**Comment by ggazzo** [comment]
> the main reason for this pull request was that users can't prune message in direct message

HMMMM need to check, nowadays its not possible because the information is shared, they belong for both so its not technically fair if you delete someones message 🤔

**Comment by KevLehman** [comment]
Hey! After a conversation with the product team, we decided this was not a bug and as a result, we won't attempt to modify the current behavior :)

Thanks for submitting this as it gave us the opportunity to settle the behavior. For now, I'm closing this PR.

**Pull request closed without merging**
