### PR TITLE
Fix bug when setting readonly room as default room

### LINKED ISSUE #825: Create room permissions for read-only / speak
<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26744641-create-room-permissions-for-read-only-speak?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #4405: Readonly default channels
Your Rocket.Chat version: 0.4.0

Default channels readonly does not work / users can write to default readonly channels.

Not good for a announement channel where all users should be in.

### PR DESCRIPTION
**Pull request by alexbrazier**
@RocketChat/core 

Closes #4405 
Probably also closes #825 as this is now done

- Fix bug to mute users in default read only channels
- Show muted icon in members list to easily spot who is muted (already half implemented)

image

### CODE REVIEW

**Comment by alexbrazier** [comment]
Any ideas why the build keeps on failing when building `rocketchat:cas`?

```
rocketchat:cas: updating npm dependencies -- cas...
                                              
   Building package rocketchat:autolinker    \
                                              
   Building package rocketchat:cas           \
                                              
   Building package rocketchat:cas           \
                                              
   Building package rocketchat:cas           \
                                              
   Building package rocketchat:cas           \
```

Just logs `Building package rocketchat:cas` until it errors.

Seems to be doing it in general (nothing to do with these code changes)

**Comment by graywolf336** [comment]
I haven't tested it out, but what does the chat box to type in look like when you're muted? I think it'd be nice if the chat box became disabled and the placeholder/text in it became "Chatting disabled, you have been muted." and the user couldn't type of click any of the buttons to do any actions.

@engelgabriel any idea why the build is failing in travis?

**Comment by alexbrazier** [comment]
Seems the build is now passing.
@graywolf336 this is what it looks like when you are muted in a read only room:
image

**Comment by Lucky21110** [comment]
Is it already committed into the development or 41?

**Pull request merged**
