### PR TITLE
Less borders

### PR DESCRIPTION
**Pull request by engelgabriel**
@RocketChat/core

### CODE REVIEW

**Comment by rodrigok** [comment]
Can you put print screens of your changes (before/after)? 😄

**Comment by geekgonecrazy** [comment]
:grin: I was trying to figure out what was different too

**Comment by engelgabriel** [comment]
BEFORE

image

AFTER

image

**Comment by geekgonecrazy** [comment]
ah much better!

**Comment by Molle500** [comment]
nice!

**Pull request merged**
