### PR TITLE
[FIX] Quoting Issue

### LINKED ISSUE #27366: Regression: Quoting issue
### Description:

Sometimes when I try to quote the message, the popup that shows the quoted message does not appear, if I send the message the quote is sent properly.
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### PR DESCRIPTION
**Pull request by henit-chobisa**
The following PR is currently is Ready for Review.

## Issue in brief: 
Sometimes when a person tries to quote a message, the quoting dialog doesn't appear above the text, but when the message is sent the quote appears perfectly.

## Steps to Reproduce 
- Open up a room
- Interrupt your connectivity in some way ( maybe switch off your internet for a while )
- Switch some rooms, and come back to the previous room
- You'll notice that now you are not able to you won't be able to quote the issue [anymore](URL)

## Technical Reasoning 
The source of the issue seem to be the lifecycle methods of `MessageBoxTemplateInstance`, which goes like these
   `OnCreated` the `MessageBoxTemplateInstance` subscribes to the `quoteMessages` with the help of `chatMessageInstance` provided by `Composer`.
- ### Issue
     - If the current Room is still opened ( Provided by RoomManager ) then it will have the current node of the room, which       means that if by any chance the room is `looses connectivity` or `closed` by the RoomManager,  the existing quoted messages may not be re-created.
- ### Solution
  - Transfering `quoteSubscription` to the `onRendered` method instead of the `onCreated` method of `MessageBoxTemplate` which will create more frequent subscriptions to the `quotes` whenever a room is rendered.

### Before : 
quotesMessages
### After applying above solution :
quotesMessagesSolution

## Issue(s)
Closes #27366 
TC-290

### CODE REVIEW

**Comment by hugocostadev** [comment]
Hi @henit-chobisa thanks a lot for your contribution! We are taking a look.

Please, remove the gitpod file.

**Comment by henit-chobisa** [comment]
Ohh no, I might have forgotten, 
Sure thing, @hugocostadev 🙌
I will do it ASAP! 💨

**Comment by henit-chobisa** [comment]
Hey there @hugocostadev, I have removed the `.gitpod.yml` file.

**Review by yash-rajpal — APPROVED** [review]

**Comment by henit-chobisa** [comment]
Hey @yash-rajpal, thank you so much for approving the PR, 🙏🏼
Apologies for requesting again, that was just a mistake. 😅

**Comment by yash-rajpal** [comment]
No worries! Thanks for the amazing contribution!

**Review by yash-rajpal — APPROVED** [review]

**Comment by henit-chobisa** [comment]
Hey @murtaza98, @hugocostadev, @yash-rajpal, @dudanogueira & @debdutdeb, 
Thank you so much for your support on this PR and merging it! 🙏🙏
Looking forward to more contributions like these! 🤩🤩🤩

**Comment by jeanfbrito** [comment]
Thanks for your effort @henit-chobisa!

**Pull request merged**
