### PR TITLE
Fonts cleanup

### PR DESCRIPTION
**Pull request by sampaiodiego**
New icons everywhere:
image

### CODE REVIEW

**Comment by sampaiodiego** [comment]
@fduraibi I think this PR will revert all your font fixes:

* c85e1fd74e89a2809a227d3c666d3e3d9aeeb5c7
* 82db55f153ead30fd165bba54c3416b97dfba3f7
* 349d5f70bc9343e30c2f7d3381e271bffa3f3e9c

can you please help us to apply them again?

**Comment by fduraibi** [comment]
😱 oh nooooo.

I think the best solution is to create the font using the private address space and not the regular ascii range, since in this range there are many mirrored characters that doesn't work correctly when used as icons.

I will check it out and see if there is a way to solve it for good.

**Comment by sampaiodiego** [comment]
:grin: thanks
maybe we need to update the file [fontello.json](https://github.com/RocketChat/Rocket.Chat/blob/develop/private/fontello.json`) so we can keep using fontello.con without losing this key map.

**Comment by sampaiodiego** [comment]
@fduraibi I just added a RTL switch to fontello demo page (you access it at http://localhost:3000/fonts/fontello.html)
so it'll be easy to identify which character is being affected =)

**Comment by sampaiodiego** [comment]
@fduraibi nvm.. we just fixed all mirrored characters directly in fontello.com =)

**Comment by fduraibi** [comment]
Thanks @sampaiodiego  شكرا
I loved the RTL switch, smart idea :+1:

**Pull request merged**
