### PR TITLE
fix: Resolve Reset Password feature not sending email for emails containing capital letters

### LINKED ISSUE #28730: Reset Password will not work when email address contains capital letter.
This reference page does not exist ... https://rocket.chat/docs/contributing/reporting-issues

### Description:

If the email address includes a capital letter (upper case letter), the "Reset Password" feature is not triggered. The Reset Password feature is accessed from the Forgot Password link on the login page

### Steps to reproduce:

1. Go to Login.
2. Click "Forgot your password".
3. Enter email address on Reset Password page. Press [Send instructions] button.
4. No email is sent.

### Expected behavior:

1. Go to Login.
2. Click "Forgot your password".
3. Enter email address on Reset Password page. Press [Send instructions] button.
4. Receive an email at registered address.

### How I proved this.

Monitored the logs of my email server. No email arrived at the server.
Using admin account in RC, updated the users email address several times.
Only when the capital letter was dropped would an email actually be sent.

Note:

There is an existing bug in RC where the case of an email address cannot be changed. I presume RC thinks the addresses are equivalent regardless of case. See...

https://github.com/RocketChat/Rocket.Chat/issues/12557

### PR DESCRIPTION
**Pull request by Pranshu1902**
feat: Fixes a bug
  refactor: A code change that doesn't change behavior (it doesn't add anything and doesn't fix anything)
  fix: Reset password feature not sending emails for emails containing capital letters.

## Proposed changes (including videos or screenshots)
Convert the email ID to all lowercase before calling the API to send the forgot password email.

## Issue
fix #28730 

## Steps to test or reproduce
1. Go to Login.
2. Click "Forgot your 
3. Enter email address on Reset Password page. Press [Send instructions] 
4. Email is sent.

### CODE REVIEW

**Review by HanmantPetekar — APPROVED** [review]
this will convert the email to lowercase so this will work as expected.

**Comment by Pranshu1902** [comment]
@HanmantPetekar please update the label on this PR

**Comment by hugocostadev** [comment]
@Pranshu1902 The label it's automatic, you need to update the PR title using the commonmark names (check on the template)

**Comment by Pranshu1902** [comment]
@hugocostadev done! Please review this PR

**Review by hugocostadev — APPROVED** [review]

**Pull request merged**
