### PR TITLE
File uploads

### PR DESCRIPTION
**Pull request by rockhouse**
Hey guys, this is my first approach to the file upload functionality #24. It still needs work but I thought it would be good to have a discussion before more work is done. Do you like the approach? Can you help me with some open issues:
1. There should be some animation like a greyed out screen
2. Permissions need to be adjusted still getting an error (hate allow/deny)

The choice here is CollectionFS (https://github.com/CollectionFS/Meteor-CollectionFS). Issues with that package are: it is not stable and is discouraged by the developer to be used in production, second: it uses allow/deny rules and not methods which I personally don't like. Third: it implements HTTP endpoints which are convenient but also very open I feel. 

Besides that, it does what it should. There is a possibility to extend to S3, at the moment it uses as discussed GridFS/MongoDB as storage. 

What are your comments, thoughts and suggestions?

### CODE REVIEW

**Comment by engelgabriel** [comment]
Thanks!! Can you update the fork so I can try to merge again?

**Comment by sampaiodiego** [comment]
@rockhouse as pointed by @engelgabriel on https://github.com/RocketChat/Rocket.Chat/issues/24#issuecomment-123504995, the uploaded file always point to localhost:3000

do you want some help to do a "stylized drop area"? or is it something you are working on?

**Comment by inderpreetsingh** [comment]
I have had quite an experience in collection FS, would be happy to help.

**Comment by rodrigok** [comment]
Nice @inderpreetsingh.

Can you review our implementation of file upload using Collection FS? Maybe you can see errors and improvements to do :)

Thanks

**Comment by rockhouse** [comment]
Thanks @inderpreetsingh! There is actually still an issue with the allow/deny rules maybe you can have a look at that? 

Thanks so much!

**Comment by inderpreetsingh** [comment]
Aah! somehow I missed the follow up comments. I will surely look into those this weekend.

**Comment by rodrigok** [comment]
Hei @inderpreetsingh and @rockhouse, we are considering to move file uploading to use this package https://github.com/jalik/jalik-ufs, what do you think about?

CollectionFS is so big, have a lot of bugs and we can't use a progress bar.

**Comment by inderpreetsingh** [comment]
@rodrigok I don't have experience with jalik-ufs. I am currently looking into it. In first look it seems a good alternative. 

Also, is dropping on the page deliberate design decision ? I was working on adding a upload attachment icon in the message bar.

**Comment by rodrigok** [comment]
@inderpreetsingh, it is a good alternative, I did the adapter for gridfs some days ago.

We started with D&D and today I did the button in the message bar for upload file. I already did an modal to confirm and preview file before upload.

**Comment by inderpreetsingh** [comment]
That's great. Would you be interested in a trello board, it's really
difficult to see the status of what's being worked upon and what is to be
done from issues. Trello board would make it simpler, what say ?

**Comment by engelgabriel** [comment]
We had a Trello board, and it was even more complicated, and information and status about issues was spread in two systems that do not talk to each other. The best way is to always comment on an issue saying that you want to start working on it and we should mark what we are working on as IN PROGRESS. 

Having said that, this may not be the case here, as I can see there was some discussion already on top here. Maybe @sampaiodiego should add @inderpreetsingh to the file-uploading channel on the demo server?

Looks like a real time chat would be more helpful here.

**Comment by rockhouse** [comment]
@rodrigok jalik's approach to fileupload looks very promising I like the clean implementation compared to CollectionFS. I completely agree with you, it is way to bloated. What is your experience with it until now after your implementation of the adapter? What else needs to be done, maybe I can help at some point?
@engelgabriel / @inderpreetsingh I would also vote for keeping it in github seems the best central point to keep the discussion

**Comment by engelgabriel** [comment]
@rockhouse, I agree, lets keep the conversation here.

**Comment by ai10** [comment]
I would love to see a rocketchat-amazons3 package; but am focused on other priorities.

**Comment by engelgabriel** [comment]
AWS should be a top priority IMHO.. especially with our big 40k users deployment coming next month. I think we will need it to be able to handle that kind of load.

**Comment by rodrigok** [comment]
@rockhouse I have no experience with jalik's packages, but I really can't solve certain problems with CollectionFS because their huge size.

I think jalik-ufs much more accessible to our necessities, and is very easy to create new adapters, I can create an adapter for S3 with no problems in, maybe, 1 day.

If @RocketChat/owners agree, I can start migration today or tomorrow to see how big is this change.

**Comment by engelgabriel** [comment]
OK, lets leave it for next week?

**Comment by rodrigok** [comment]
Is better launch the 1.0 version with the correct file system, do not you think @engelgabriel?

**Comment by engelgabriel** [comment]
True... :(

**Comment by rodrigok** [comment]
@rockhouse and @inderpreetsingh, my WIP for this migration https://github.com/RocketChat/Rocket.Chat/pull/518

**Comment by rockhouse** [comment]
@rodrigok looks awesome! let me check it out in more detail next week. Well done! thanks

**Comment by jhnvz** [comment]
+1 for an s3 adapter!

**Comment by batuhan** [comment]
Is there any development with the S3 adaptor?

**Comment by rodrigok** [comment]
@batuhan not yet.

**Pull request merged**
