### PR TITLE
Minimalistic view

### PR DESCRIPTION
**Pull request by sampaiodiego**
@RocketChat/core 

To see it, just add `?layout=embedded` to URL:
image

### CODE REVIEW

**Comment by rodrigok** [comment]
Screen shoots?

**Comment by geekgonecrazy** [comment]
I second that request! :smile:

**Comment by sampaiodiego** [comment]
Screenshot added =)

**Comment by rodrigok** [comment]
Nice!

**Comment by geekgonecrazy** [comment]
@sampaiodiego is the purpose to be embeded in pages?  If so I propose changing it to `embeded=1`  I think it'd make more sense to users as to what it actually is.

**Comment by rodrigok** [comment]
@geekgonecrazy or maybe `style=embedded` or `style=mini`

**Comment by engelgabriel** [comment]
I like `layout=embedded`

**Comment by sampaiodiego** [comment]
Changed to `?layout=embedded` by popular demand.. also I've created a class to manage better which layout is being used (there is only `embedded` at the moment)

**Comment by geekgonecrazy** [comment]
@sampaiodiego sorry :grin:  Awesome feature though

**Pull request merged**
