### PR TITLE
Regression: User thread join message

### LINKED ISSUE #13644: Discussions - next steps and minor issues
Following #13541, we've addressed some issues and defined how the new feature must improve:

### Bugs

- [x] Data to create discussions on direct messages is incomplete (#13646)
- [x] Cannot select more users to invite on "Create a new discussion" modal (#13646)

### Open for discussion

- [ ] Mentioning discussions?
- [ ] Nested discussions?
- [ ] Slash commands for discussion creation/handling?

### Improvements

- [x] Join without send a message
- [x] Limit size of `name` field
- [ ] Promote/convert discussions to channels/groups
- [x] Rephrase "has joined the channel" as "has joined the conversation"
- [ ] Improve attachment for quoting discussions
- [x] Show discussions as section option on popover

### PR DESCRIPTION
**Pull request by bhardwajaditya**
thread_fix

### CODE REVIEW

**Comment by fliptrail** [comment]
@bhardwajaditya Please remove the tag "Closes 13644" from the description as it does not close down the entire issue

**Comment by bhardwajaditya** [comment]
@fliptrail thanks.

**Comment by bhardwajaditya** [comment]
@ggazzo please review.

**Comment by sampaiodiego** [comment]
Thanks guys :smile:

**Pull request merged**
