### PR TITLE
[FIX] Missing page "not found"

### LINKED ISSUE #6366: No error page when connecting to wrong url https://[server_name]/[wrong_name]
Rocket.Chat Version:  0.49.2
Running Instances: 1
DB Replicaset OpLog: 79
Node Version: 4.7.1

When connecting with a browser (Firefox 45 ESR) to an URL like https://[rocket_chat_server]/[random_name] user get no error report and is not redirected anywhere. He is connected but have no clue what to do.

Same thing happen in the demo server (see gif attached) : go to https://demo.rocket.chat/nothingthere and see by yourself.

bugreport

User should be redirected to an error page, and see his sidebar so he would be able to join another room.

### PR DESCRIPTION
**Pull request by Prakharsvnit**
fixes #6366

@RocketChat/core 

Improvements required: enlarge font-size and change font-color

### CODE REVIEW

**Comment by sampaiodiego** [comment]
hey, thanks for your contribution. can you please fix the lint/codacy errors?

also, you should translate the messages on template like [this](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-authorization/client/views/permissions.html#L33) and adding it source like [this](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-i18n/i18n/en.i18n.json#L1078)

**Comment by sampaiodiego** [comment]
@Prakharsvnit you're still not using the translated text on template. please change this:
`<h1>Error:404</h1>`
by this:
`<h1>{{_ "Error_404"}}</h1>`

and so on.
thx

**Comment by Prakharsvnit** [comment]
@sampaiodiego Tested changes on my local machine, it gives output as 

> Sorry_page_you_requested_does_not_exists_or_was_deleted

which shouldn't be the case.

**Comment by pkgodara** [comment]
@Prakharsvnit I had same problem. The problem seems due to cache. You will have to clear cache & rebuild your app.

There are two ways around.

1. Meteor reset `meteor reset` but it will also **delete your database** (I would not recommend personally).

2. I tried `meteor rebuild` but it would not help since it does not rebuild whole app. So you will have to manually delete all these folders in `.meteor/local` : 
`build
bundler-cache
isopacks
plugin-cache
shell`

Now run it again `meteor npm start`. Works for me.

**Comment by geekgonecrazy** [comment]
@Prakharsvnit sorry for the delay on this one.  I like the suggestion of linking to the home page.  That way the user isn't stuck once they get this page.

Is that something you could add?

**Comment by geekgonecrazy** [comment]
@karlprieb what do you think?  It'd probably be great to have a nice page at some point with designer being involved.  But this would be better than what we have now

**Pull request merged**
