### PR TITLE
[FIX] Performance issues when using new Oplog implementation

### PR DESCRIPTION
**Pull request by rodrigok**
## Issue(s)

Closes https://github.com/RocketChat/Rocket.Chat/issues/19082

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Changelog

A missing configuration was not limiting the new oplog tailing to pool the database frequently even when no data was available, leading to both node and mongodb process been consuming high CPU even with low usage. This case was happening for installations using `mmapv1` database engine or when no admin access was granted to the database user, both preventing the usage of the new [Change Streams](https://docs.mongodb.com/manual/changeStreams/) implementation and fallbacking to our custom oplog implementation in replacement to the Meteor's one what was able to be disabled and use the native implementation via the environmental variable `USE_NATIVE_OPLOG=true`.

### CODE REVIEW

**Review by sampaiodiego — APPROVED** [review]

**Comment by codeneno** [comment]
Does this only fix "mmapv1 database engine or when no admin access was granted to the database user,"?
we use 3.3.3 version,and it will have a high cpu load sometimes,does this work for wiredTiger ?thank you.

**Comment by codeneno** [comment]
when we use rocket.chat 3.9.4 version,without (USE_NATIVE_OPLOG=true),our mongodb will have much getmore operation,
and the mongodb's cpu is 99%......

**Comment by codeneno** [comment]
@sampaiodiego @rodrigok 
All of us suggest there is something wrong with your new method (own oplog implementation) 
https://github.com/RocketChat/Rocket.Chat/issues/20027

**Comment by 564064202** [comment]
this bug is   still  hear

**Pull request merged**
