### PR TITLE
[IMPROVE] Removed close function on selecting emoji.

### LINKED ISSUE #20378: While sending more than one emojis we need to click on emoji picker icon again .
### Description:
When a user wants to send more than one emoji he/she needs to click emoji-picker for every single emoji. 

### Steps to reproduce:

1. Message box
2. Click emoji-picker.
3. 

### Expected behavior:
Users only need to click once.

### Actual behavior:
Users need to click more than once.

https://user-images.githubusercontent.com/55157259/105715393-8d1f0500-5f43-11eb-87da-62994dc3be4a.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu

### Additional context
PR is ready!

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)

Removed closed function on selecting emoji so emoji-picker still remains on screen.

https://user-images.githubusercontent.com/55157259/105715885-24845800-5f44-11eb-99be-b80f0d8b0763.mp4

## Issue(s)

Closes #20378

### CODE REVIEW

**Review by MartinSchoeler — DISMISSED** [review]
This change makes sense to me, LGTM!

**Comment by Darshilp326** [comment]
@ggazzo Please go through this PR.

**Comment by ggazzo** [comment]
I'm not sure if it this a desired behavior but I will mention here and check

**Comment by Darshilp326** [comment]
@ggazzo Okay!

**Pull request closed without merging**
