### PR TITLE
[FIX] Fixed Notification-sound volume number in profile settings.

### LINKED ISSUE #20236: No one can change profile settings.
### BUG 1
No one can change profile settings, this prompt appears even when all correct passwords have been typed in. This issue can be solved for some people by using incognito.

### Steps to reproduce:

1. Go to profile settings.
2. Change a setting.
3. Error is produced.

### Expected behavior:

When changing a setting, we are expecting for the changes to be made without this error.

### Actual behavior:

Changes aren't being made to the user's profile. It keeps producing errors.

### BUG 2
Reloading the website while not being logged in prompts this error.

### Steps to reproduce:

1. Logout
2. Reload the page.
3. Error is produced.

### Expected behavior:

When reloading the page, while logged out, it should not be producing errors.

### Actual behavior:

User should be able to re-load the page, while logged out without seeing these errors.

### BUG 3
The sound volume number for notifications is messed up in profile settings.

### Steps to reproduce:

1. Navigate to Settings > Nofications > Sounds
2. Sound shows as an incorrect value.

### Expected behavior:

When reloading the page, while logged out, it should not be producing errors.

### Actual behavior:

User should be able to re-load the page, while logged out without seeing these errors.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.4

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)
Notification-sound volume number can be viewed properly.

Before
Screenshot from 2021-01-17 14-41-04
After
Screenshot from 2021-01-17 14-35-32

## Issue(s)

Fixes #20236
Bug Number 3

### CODE REVIEW

**Review by ggazzo — CHANGES_REQUESTED** [review]
hey, thanks for your PR but I don't think this currently fixes the problem, as you can see there is an arrow there: 
image
you just positioned the arrow in a different place that we cant see, the fix should be put the arrow in the right place


thanks again

**Comment by Darshilp326** [comment]
@ggazzo Sorry, I am not able to get your point. Can you explain?

**Comment by ggazzo** [comment]
look this pr https://github.com/RocketChat/Rocket.Chat/pull/20310, it is almost right but he put to the wrong side

**Comment by sushant52** [comment]
> almost right but he put to the wrong side

Sorry I thought it was the correct position 😅. I have made the changes, fits perfectly now.

**Comment by Darshilp326** [comment]
> look this pr #20310, it is almost right but he put to the wrong side
Ohh like this.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Closing this PR because it's stale now and it was already fixed in another one.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Pull request closed without merging**
