### PR TITLE
feat: Support for chunked upload in rooms.upload/:rid

### LINKED ISSUE #25732: [BOUNTY] Can Not Upload Files Larger Than CDN or Proxy Single Request Limits without Chunking
Description

Since the change to send files via the REST API https://github.com/RocketChat/Rocket.Chat/pull/16617, RocketChat instances hosted behind a CDN can not upload files larger than the limit for a single request (100MB for Cloudflare)

Problem has been recognized in posts here: https://github.com/RocketChat/Rocket.Chat/pull/16617#issuecomment-591119408, https://forums.rocket.chat/t/file-uploads-are-super-slow-because-theyre-sent-in-many-small-post-requests-wtf/4600/24, and https://forums.rocket.chat/t/file-uploads-are-super-slow-because-theyre-sent-in-many-small-post-requests-wtf/4600/26

While the previous uploading library https://github.com/jalik/meteor-jalik-ufs#uploading-files had issues, it did chunk uploads.  If the upload chunk size was configurable, rather than a single POST request it would fix this issue and allow administrators to tune the setup to their network.

Steps to reproduce

Host RocketChat instance behind Cloudflare, and upload a file over 100MB

Server Setup Information

Version of Rocket.Chat Server: 3.14.3
Operating System: Ubuntu
Deployment Method: Manual install
Number of Running Instances: 4
DB Replicaset Oplog: Enabled
NodeJS Version: v12.18.4
MongoDB Version: 4.0.25

Client Setup Information 

Desktop App or Browser Version: Firefox version 100
Operating System: Any

Additional context

Relevant logs

### PR DESCRIPTION
**Pull request by Ousret**
## Proposed changes (including videos or screenshots)

Simply put, reinstate the chunked upload capability (workaround) since the last major change. This does not revert any commit.
This change does not change the actual behavior, instead, it offers two parameters that will enable admins to tweak it.

This fix applies to both single instances and multiple.

rocket patch-params

rocket patch-upload

rocket patch-upload-range

## Issue(s)

Close #25732
Related #16542 #16617

## Steps to test or reproduce

Since the change to send files via the REST API #16617, RocketChat instances hosted behind a CDN can not upload files larger than the limit for a single request.

## Further comments

The main criticism about this fix is that to provide a minimum changeset, I had to compose.
- Chunks must be sent in order (no parallelism allowed)
- Tmp file is re-read entirely in memory (last post request may be longer)

### CODE REVIEW

**Comment by sampaiodiego** [comment]
thanks @Ousret for your contribution.. the main problem with this approach is that multiple requests can land in different rocket.chat instances, causing the upload to fail. this was on of the main problems with the previous approach, where we'd have to route the chunks to the instance that has received the first chunk in order to complete the upload.

**Comment by Ousret** [comment]
Ok. I understand a bit more. There was no mention of this issue in previous issues.
Why is there no volume shared across containers or hosts? Is this why you used GridFs in the first place?

It would be up to the admin to choose the best-suited configuration.

Maybe, on first-through, add a parameter server-only, _tmp path shared_ across instances. And enforce a lock on the file.

**Comment by Ousret** [comment]
Let's find an ideal compromise on that feature.
I have updated the branch to support chunk upload through GridFs, so that, when selected (in params upload) will work as expected.
Nevertheless, when filesystem is selected, it will be up to the admin to ensure that proper volume (if needed) sharing through whatever (eg. cephfs, glusterfs, swarm volumes, etc..). 

WDYT?

rocket patch-params-2

**Comment by Ousret** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/27105 just caused conflicts.

**Comment by Ousret** [comment]
Fixed and tested locally.
I noted a minor decrease in performance (backend processing).
@sampaiodiego

**Comment by Ousret** [comment]
Can someone approve the CI run?

**Comment by cross-hello** [comment]
Not related with formal developer, just delegates self, תודה אתה.

----------------------------------------

*From: *TAHRI Ahmed R. ***@***.***>
*To: *RocketChat/Rocket.Chat ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Nov 12, 2022 11:41:51
*Subject: *Re: [RocketChat/Rocket.Chat] [FIX] Support for chunked upload 
in rooms.upload/:rid (PR #27168)

**Comment by cross-hello** [comment]
@sampaiodiego Please revisit if the code is suitable.
We want the feature : )

**Comment by Ousret** [comment]
ping @RocketChat/chat-engine

**Comment by Ousret** [comment]
PR #27457 just broke this PR.

```
import { Uploading } from '../../../../../app/ui/client/lib/fileUpload';
import { Upload } from '../../../../lib/chats/Upload';
```

**Comment by sampaiodiego** [comment]
hi @Ousret , I've been discussing about this with @rodrigok and we're considering merging this, but we still have a few concerns about the implementation. We're wondering if the implementation should be simpler and always save the chunks using gridfs, this way it will covers all deployments with no extra config. wdyt?

**Comment by Ousret** [comment]
Hi @sampaiodiego 

> We're wondering if the implementation should be simpler and always save the chunks using gridfs, this way it will covers all deployments with no extra config. wdyt?

I think that is a viable option, nevertheless, could be weird to see GridFS used when explicitly left aside. It works for me.
I'll leave the final say to you.

p.s. fixed the merge conflict.

**Comment by Ousret** [comment]
@sampaiodiego @rodrigok did you reach a decision about excluding (or not) the fs as the chunk receiver?

**Comment by Ousret** [comment]
friendly ping @sampaiodiego

**Comment by rodrigok** [comment]
@Ousret, thanks for your patience, end of the year is always a crazy time.

FileSystem is, for sure, a bad idea for this purpose. It requires access to the same disk for all the instances, which leads to confusion for less experienced users. I suggest you remove this possibility for this PR and keep it on GridFS for the temp files. GridFS is not intended for the final place per scale purposes, but for a temporary location, it should be fine. We can have S3 as an option later.

In other to have this incorporated we will need the implementation on our mobile application https://github.com/RocketChat/Rocket.Chat.ReactNative. Please check and let us know when you can make the implementation.

I'll go over the code and review it ASAP, thanks 😄

**Comment by Ousret** [comment]
Hi,

I understand. No pressure.

As you decided to exclude fs for the chunk temporary storage, it is done.
The PR now reflects that position.

I am checking out the react native application as I speak. 
Meanwhile, this PR is ready for review.

**Comment by rodrigok** [comment]
@Ousret thanks, will review it ASAP

**Comment by Ousret** [comment]
gentle ping

**Comment by Ousret** [comment]
ping @sampaiodiego @rodrigok 
pr is fixed for the latest develop.

**Pull request closed without merging**
