### PR TITLE
[NEW] Section to monitor and manage bot accounts on admin interface

### LINKED ISSUE #10831: [NEW] Section to monitor and manage bot accounts on admin interface
This is part of the GSoC project to improve the integration of Rocket.Chat with bots, the discussion about changes on the User model is found [here](https://forums.rocket.chat/t/change-the-architecture-of-bot-accounts/776).

This issue is about creating a new section on the Administration Panel to visualize all bots of the server and monitor or manage them with a interface that is similar to the User's section.

The list will contain all accounts with the `type: 'bot'` attribute (as discussed in the link above) and display relevant information about it. By clicking on a single bot, a summary with additional info will be displayed in the sidebar along with a link "More details", pointing to a new page where you can see all details of a bot, its editable fields and statistics about it.

And for last, a page where you can convert user accounts to bot and vice versa, this one does not have a preview yet.

The previews do not reflect neither the current or final state of the UI and its details such as icons or fields. Screenshots of the current work will be displayed in the PR and all suggestions to improve them are welcome.

Previews:

image

image

image

### PR DESCRIPTION
**Pull request by mikaelmello**
This is part of the GSoC project to improve the integration of Rocket.Chat with bots, the discussion about changes on the User model is found [here](https://forums.rocket.chat/t/change-the-architecture-of-bot-accounts/776). Also the utility used to communicate with bots using something else than messages (for server-side admin operations) can be found [here](https://forums.rocket.chat/t/introducing-a-new-utility-to-manage-custom-clients-from-the-server/1411/7). This PR consists of the addition of two features (and packages) to Rocket.Chat

# 1. DDP Requests

DDP Requests is the name given to a solution created to allow the Rocket.Chat server to trigger actions in subscriber clients (bots and possibly other websocket clients). This is handled at the adapter and/or SDK level, not by final users (e.g. normal bot developers).

They are better explained [here](https://forums.rocket.chat/t/introducing-a-new-utility-to-manage-custom-clients-from-the-server/1411)

## 1.1. customClientData

Some features depend on which adapter the bot is running on, a bot that does not use the JS SDK might not support a few or all DDP Requests. That's why before showing any of the features, a check is made to see if the account currently supports such feature.

The client sets the `customClientData` field with information about its custom client. A client that can reply to `getStatistics` and `pauseBot` sets `customClientData = { canGetStatistics: true, canBePaused: true }`, for example.

This field can be used to store any information about the client, such as [text commands implemented by the bot](https://github.com/RocketChat/Rocket.Chat/issues/1086#issuecomment-374465944).

# 2. Bot Management Admin Panel

The package `rocketchat-bot-manager` consists of adding a new section on the administration panel to manage bot accounts, that is, accounts with the `type` attribute set as `'bot'`, as discussed [here](https://forums.rocket.chat/t/change-the-architecture-of-bot-accounts/776).

## 2.1. List view

The list view is a list of all the existing bot accounts. It is accessible from the admin sidenav and shows the following information about an account:
  - Status (online/away/busy/offline)
  - Name
  - Username
  - Framework used by the account

[Screenshot](https://user-images.githubusercontent.com/17488630/42197042-4f8c168a-7e57-11e8-9fdb-2cb1c483a4b9.png)

## 2.2. Creation of a bot account

To create a bot account, the admin must first go to the list view and then click on the plus button on the right sidetab, opening a form similar to the one used to create a normal account, except for all e-mail related fields that have been removed.

[Screenshot](https://user-images.githubusercontent.com/17488630/42197061-665419da-7e57-11e8-994d-d40c57db503a.png)

## 2.3. Visualizing general info about an account

In the list view, the admin can click on any listed account and a flextab will be opened on the right side, displaying some information about the clicked account. Currently, it is displayed:
  - Roles of the account
  - Last login
  - Framework used by the account
  - Stack of clients the accounts is running on
  - (Optional) Button to pause or resume the bot

If the admin clicks on the 'More Details' button, it will be taken to the Details page.

[Screenshot 1 - Offline account](https://user-images.githubusercontent.com/17488630/42197056-5efd4f12-7e57-11e8-9e12-0c690cda9d77.png). [Screenshot 2 - Online account](https://user-images.githubusercontent.com/17488630/43169347-0e676d36-8f77-11e8-8342-ff7f700f2b10.png)

## 2.4. Overview of the newly implemented management features

The features listed here were created using DDP Requests.

### 2.4.1. Pausing or resuming a bot

Pausing or resuming a bot is handled at the JS SDK, not handled by the bot developer. Therefore any bot that uses the SDK can be paused.

Paused here means that the SDK will unsubscribe itself from the message stream until it is told to resume or is restarted.

### 2.4.2. Pinging a bot

As it has been [previously requested](https://forums.rocket.chat/t/good-ways-to-check-bots-are-alive-and-well/259), whenever the admin is visiting a bot's details page, the server pings the bot each second to check if it is still alive and to also know the response time of the bot.

### 2.4.3. Getting statistics from a bot

Besides statistics that can be retrieved from the server, the total number of messages sent by the account for example, the bot client can also have meaningful data to be displayed in the management view. Therefore the admin can choose to load statistics provided by the bot client. What data is retrieved is specific to each Framework/Adapter.

## 2.5. Bot Details view

The main management page of a bot is its details page. It displays:
  - Status (offline/online/pauseOrResume) - Pause of Resume is displayed when the bot is online and can be paused
  - Editable field displaying the account name
  - Editable field displaying the account username
  - Editable field to be filled with a new password, if it is to bechanged
  - Framework/Adapter used by the bot
  - Connection status displaying the bot's IP address and its response time (ping)
  - Uptime of how long the bot has been online and another for how long the bot has been active (not paused)
  - Roles and the possibility to add or remove them

[Screenshot 1 - Offline](https://user-images.githubusercontent.com/17488630/42197100-a03c7976-7e57-11e8-8371-0c72e25a6870.png). [Screenshot 2 - Online](https://user-images.githubusercontent.com/17488630/42197119-b3f0f500-7e57-11e8-8437-a12e5951f709.png)

The admin can also delete the account and convert the account to the user type. Converting it to the user type will simply edit the `type` attribute and ask for an e-mail if the account does not have one.

Regarding the statistics view, it is displayed when the admin clicks on 'Load' and currently shows:
  - Total number of messages sent by the bot
  - Total number of messages in which the bot is mentioned
  - Total number of rooms that bot has joined
  - [L] - How many times the bot had to reconnect to the server
  - [L] - How many messages the bot has read
  - [L] - Time when the last message was read
  - [L] - How many users are stored in the Hubot brain (Hubot only).

Items starting with [L] are retrieved live from the bot client. Note that different adapters can display different information.

--- 

Todo:
- When receiving a response of a ClientCommand, the instance that receives it uses the `RocketChat` global variable, an EventEmitter, to emit the response to the original caller of the command that is now waiting for the response. On multi-instance servers this original caller might be in another instance, using streams the ClientCommand is broadcasted and the receiver does receive the ClientCommand, however it responds to a server that might be different than the one that sent the ClientCommand, and since I am using the RocketChat EventEmitter, which does not broadcast, the server might not receive the response. Help to fix this would be highly appreciated.

Related:
- #10459 - Easier to implement with the differentiation between account types.
- #1086 - Possible using the 'customClientData` user attribute, implemented here
- #10688

Closes:
- #7125
- #8483

Changes on SDK: https://github.com/RocketChat/Rocket.Chat.js.SDK/pull/15

Since there are a lot of images, it is better to use a list
- [List of all bot accounts on the server](https://user-images.githubusercontent.com/17488630/42197042-4f8c168a-7e57-11e8-9fdb-2cb1c483a4b9.png)
- [Form to create a new account (no need to use an e-mail)](https://user-images.githubusercontent.com/17488630/42197061-665419da-7e57-11e8-994d-d40c57db503a.png)
- [Info that is shown after clicking on an account](https://user-images.githubusercontent.com/17488630/42197056-5efd4f12-7e57-11e8-9e12-0c690cda9d77.png)
- [Info about a bot that is online](https://user-images.githubusercontent.com/17488630/43169347-0e676d36-8f77-11e8-8342-ff7f700f2b10.png)
- [Details about a bot that is offline](https://user-images.githubusercontent.com/17488630/42197100-a03c7976-7e57-11e8-8371-0c72e25a6870.png)
- [Statistics about a bot, there's a lot to do here](https://user-images.githubusercontent.com/17488630/42297129-6d37ca6c-7fd3-11e8-8b5f-9f63c259648c.png)
- [Details about a bot that is online](https://user-images.githubusercontent.com/17488630/42197119-b3f0f500-7e57-11e8-8437-a12e5951f709.png)
- [After clicking on "Convert Account", to convert an account to `'user'` type](https://user-images.githubusercontent.com/17488630/42197341-b5302d90-7e58-11e8-9b19-c7322682c3ae.png)
- [If the bot account does not have an e-mail set, it asks for a new one since users are required to have](https://user-images.githubusercontent.com/17488630/42197351-c45b63a2-7e58-11e8-9f35-4244113be1f1.png)
- [Showing that an user can be converted to a bot account (useful to upgrade bots that were functioning on older versions of RC)](https://user-images.githubusercontent.com/17488630/42197383-df317b9e-7e58-11e8-98f8-3354d9eff2da.png)
- [Warning after clicking on "Convert to bot"](https://user-images.githubusercontent.com/17488630/42197392-e4955a38-7e58-11e8-928e-6b32e93e0538.png)
- [Warning after clicking on "Delete account" in the Bot Details page](https://user-images.githubusercontent.com/17488630/42197588-e4b1ef3a-7e59-11e8-95a3-5c0d1441ccab.png)

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@mikaelmello can you drop some current screens in your initial post here.  Really helps people understand a bit better whats happening and what the code is coming together to do

**Comment by mikaelmello** [comment]
@geekgonecrazy I should have done that sooner. Here it is https://imgur.com/a/oG9CAU4

**Comment by mikaelmello** [comment]
A new album has been added showing the latest changes.

**Comment by timkinnane** [comment]
@mikaelmello I have a question about the coding patterns you're using, I'm asking about `getBotStatistics` but my question would probably apply across the entire solution.

So I might not understand, but my first impression is that `getBotStatistics` shouldn't be a server method. It seems to just wrap the call to `sendClientCommand` with a `getStatistics` command. In templates like `adminBotDetails`, why not just call `sendClientCommand` directly?

If the reason is something like you need a server method to call, that also gets user permissions and check the bot is online before `sendClientCommand`, shouldn't you either make it a `sendClientCommand` server method instead, so that it includes the permission and online checks, or make a server method counterpart for `sendClientCommand` that can be used as a common helper for all template features that use a client command.

My concern is that I don't want every client command to require it's own server method. That could pollute the namespace as the usage of client commands grows, but it also defeats the purpose of having one consistent utility instead of repeating the logic for different use cases.

I would also like to see some more comments that give some context for your methods, just a basic **why** and **how**, would help people reading the code maybe not jump to the wrong conclusion - as I might have done?

**Comment by mikaelmello** [comment]
@timkinnane 

> So I might not understand, but my first impression is that getBotStatistics shouldn't be a server method. It seems to just wrap the call to sendClientCommand with a getStatistics command. In templates like adminBotDetails, why not just call sendClientCommand directly?

Because it also retrieves statistics from the server, not just the client, for now it only retrieves the total number of messages

https://github.com/mikaelmello/Rocket.Chat/blob/8f921030f79918376a1f048fa1243be619c44633/packages/rocketchat-bot-manager/server/methods/getBotStatistics.js#L14

but I will add more in the future such as 'Messages mentioning the bot' or 'Messages DM'd to the bot', etc. 

> If the reason is something like you need a server method to call, that also gets user permissions and check the bot is online before sendClientCommand, shouldn't you either make sendClientCommand a server method instead, so that it includes the permission and online checks, or make a server method counterpart that can be used as a common helper for all template features that use a client command.

The main reason is because different ClientCommands would require different permissions, an admin with less privileges might be able to view the statistics but not to pause/resume the bot. I see though that using a single method would make the code clearer and besides that, the permissions are not very well defined so I will try to improve them.

> I would also like to see some more code comments that give some context for your methods, just a basic why and how, would help people reading the code maybe not jump to the wrong conclusion (as I might have done) and answer questions before they need asking, to improve the pace of contributions and reviews.

Alright!

**Comment by timkinnane** [comment]
> Because it also retrieves statistics from the server

OK, now I understand. But I don't know if that's as clear and maintainable as it could be. I think stats from the bot and stats from the server are two different concerns - for different methods at least. I don't know what stats will be needed from the server or if this is the best place for them, because it might be stepping on other features that aim to give a statistics view. With the different types of data returned from adapters as well, it might be just too confusing for developers to make use of in that shape.

I think the simplest solution is to just ask the bot to return stats and display those stats. Each adapter can determine what's appropriate for the framework/platform. The stats from the server should be another section in the template, then we can accept contributions for refining those as a seperate issue which doesn't require understanding the client commands methods.

For client commands usage, I'm still concerned about the repetition of logic. Imagine if there's some change to the method interface or permissions, it would require refactoring many different methods that are all repeating the same steps. It doesn't align with the vision of one simple utility.

I can see that it won't always be used the same way, for instance, some commands will need extra permission checks and it won't always be used with a bot, it could be a front-end app consuming the SDK. But what if you had a `sendBotCommand` server method, that always checks `manage-bot-client` permission and if the bot is online before calling `sendClientCommand`. That would work for 90% of the bot management that use client commands.

**Comment by mikaelmello** [comment]
Description updated better explaining the PR.

**Comment by MarcosSpessatto** [comment]
@mikaelmello can you fix the conflicts?

**Comment by mikaelmello** [comment]
@MarcosSpessatto will do it tonight

**Comment by mikaelmello** [comment]
@MarcosSpessatto done

**Comment by mikaelmello** [comment]
Can anyone give me a status on this PR? Just out of curiosity

**Comment by timkinnane** [comment]
@mikaelmello I'm sad to say I think this one missed the window to be implemented during GSOC and now there's a lot of competing priorities and no direct ownership of bot related enhancements.

I would still really like to see this merged, but I think the only way forward is to break it apart into components that can be more easily understood and accepted. e.g. Just splitting the user/bot account type, listing and creation - that would be a very good step forward for the platform.

Then the other enhancements about stats etc would be less complex and easier to demonstrate value.

Are you able to do that?

**Comment by mikaelmello** [comment]
@timkinnane Sure, I'll try to map the dependencies of all changes (which depends on which) and then make some sort of progressive PRs.

**Comment by mikaelmello** [comment]
I am going to split this PR in 2:

1. Change the role of the 'type' attribute, as discussed, and all the management panel for bots. The difference from now is that it won't contain any changes related to DDP Requests, all info that relies on a server-client communication.
2. DDP Requests on top of that.

**Comment by mikaelmello** [comment]
Closing it in favor of #13609

**Pull request closed without merging**
