### PR TITLE
Update to meteor 1.6.1

### PR DESCRIPTION
**Pull request by engelgabriel**
Re-enable:

- [x] rocketchat:graphql
- [x] rocketchat:internal-hubot
- [x] steffo:meteor-accounts-saml

### CODE REVIEW

**Comment by engelgabriel** [comment]
Maybe we need to do https://github.com/RocketChat/Rocket.Chat/issues/9545 first

**Comment by sampaiodiego** [comment]
[awesome release](https://github.com/meteor/meteor/blob/devel/History.md#v161-2018-01-19)

**Comment by rodrigok** [comment]
@engelgabriel why did you delete some i18n files?

**Comment by engelgabriel** [comment]
@rodrigok I finihed deleting the` /app/` directory, since @sampaiodiego moved it to `/.app/`

**Pull request merged**
