### PR TITLE
[WIP] Slash command parameter suggestion

### LINKED ISSUE #7307: Slash Command Parameter Suggestions
The slash commands right now inside of Rocket.Chat only suggest parameters which start with `#` or `@`. Adding the ability to provide suggestions to the user for any configurable parameters along with where the suggestions come from would be superb!

For example, let's say someone creates a GitHub slash command. It provides one main command and several subcommands which those then take other parameters. For example: the command `/github assign <repository> <issue-number> <person>` would bring up suggestions when typing where the repository would go, the issue, and person being assigned. The slash command would be able to pull data from various resources and provide the suggestions asynchronously.

Also need a way to format the data which is being shown along with what is inserted into the message box when the user selects one of the suggestions. Ideally this would be done in a way that it's very generic and several packages can make usage of it.

### PR DESCRIPTION
**Pull request by graywolf336**
This is a WIP pull request from a branch by @gdelavald, this might be closed in favor of a new one in the future but the purpose of creating it now is to open discussion regarding this feature.

Closes #7307

### CODE REVIEW

**Comment by jszaszvari** [comment]
@graywolf336 Out of curiosity why have you put the github commands in the rocketchat-slashcommand-asciiarts package and not a seperate rocketchat-slashcommand-github package?

**Comment by graywolf336** [comment]
It's not me writing this @jszaszvari ;) but it's merely for an example of what is possible and hence the `[WIP]` prefix on this pull request. It will be removed before this gets merged to `develop`.

**Comment by jszaszvari** [comment]
@graywolf336 Ah ok, Awesome stuff. Very useful, helps me in my current endeavour.

Thanks dude

**Comment by graywolf336** [comment]
@jszaszvari This is one piece in a larger puzzle, it's super exciting actually. You will soon be hearing/seeing a term we are calling "Rocketlet", it will allow developers to easily extend/modify the behavior of Rocket.Chat without forking Rocket.Chat and changing any of the core code.

**Comment by jszaszvari** [comment]
@graywolf336 this is very woot. I've been hoping for something like this for quite a while now. Read my comment on the Bot blog post on the RC website. 

It's desperately needed and I'm super excited as it's a step closer to a large ecosystem of integrations.

**Comment by graywolf336** [comment]
@jszaszvari Just read it and that is aligned with the goals of the Rocketlets. If you're interested in more information, contact me on the demo server and I can get you looped into everything along with would love to throw some thoughts and ideas at you and get your opinion since you're extremely opinionated in this realm (don't get me wrong, that's a positive thing!).

**Comment by jszaszvari** [comment]
@graywolf336 be in touch in a few hours. 

Been keen to get involved in any way I can for a few months now. I very much do have lots of thoughts, ideas and opinions on things that I think could be a positive step for the future. 

Also got some stuff I have done around this sort of stuff that I can't show off publicly but can in private. 

Plus a bunch of practical experience as I'm pretty sure I look after the 2 largest RC deployments in Australia, which has been a epic learning experience and helped shape some of my ideas. 

Thanks :)

**Comment by graywolf336** [comment]
@jszaszvari sounds good to me, I'll be up for several more hours. I look forward to chatting with you. :+1:

**Pull request closed without merging**
