### PR TITLE
[NEW] Adds admin option to globally set mobile devices to always be notified regardless of presence status.

### LINKED ISSUE #1602: Change Push Notification logic
Currently, the only way you will ever get a push notification is if your connection is considered "away". (This is different from your status. Basically, it's controlled by how long it's been since you last interacted with anything.)

My suggestion is to make the logic instead work like this:
- If a message that would generate a notification (DM, mention, etc.) has not been read in X minutes, send a push notification.
- Add an option for how many minutes (2 feels like a good default, minimum should be 0, aka "immediately")
- Add an option to disable sending push notification at all.

We may also want an option for the current behavior: "Do not send a notification if I have been active in the last X minutes."
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28961269-change-push-notification-logic?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by stalley**
@RocketChat/core 

Closes #1602

image

Adds an option to always send push to mobile devices regardless of Online or Away presence status. Defaults to false. This is a global option in Admin->General->Notifications.

### CODE REVIEW

**Comment by stalley** [comment]
@rodrigok Can this be reviewed if it's an acceptable addition.

**Comment by stalley** [comment]
@engelgabriel  Can this be reviewed? I've done 10 deployments of Rocket Chat servers so far and every single one has asked for this to be an option.

**Comment by davidrea** [comment]
:+1: Adding my vote to please review and merge this PR!

Suggest maybe adding an extra set of parens around the 1st two conditionals at (new) line 237. But then, I'm an embedded C guy who starts to twitch when order-of-operations is left up to the compiler! :wink:

**Comment by rodrigok** [comment]
Hi @stalley I liked the idea, can you fix the conflict? I'll add this PR to the version 0.60

**Comment by stalley** [comment]
@rodrigok Apologies, I'm getting this cleaned up

**Comment by stalley** [comment]
@rodrigok Everything looks good now.

**Comment by stalley** [comment]
@rodrigok Wanted to be sure this made it in for 0.60  Thanks!

**Comment by stalley** [comment]
@rodrigok @sampaiodiego Sorry to keep spamming this, just don't want this to get left behind.

**Comment by engelgabriel** [comment]
This will be merged into `0.60.0` we are just too busy with the UX issues of the `0.59.0`

**Comment by stalley** [comment]
@engelgabriel Understood.

**Pull request merged**
