### PR TITLE
[NEW] Add route to get user shield/badge

### LINKED ISSUE #9488: Feature: Add a "user" shield
Related to #6565.

 * Add a route like `/api/v1/shield.svg?type=user&username=someuser`
 * Display user's `name` and `status` (status via either the usual colored circle, or else by changing the shield's background)
 * Can then be used to link to direct chat web UI URL, and display the online status in wikis etc.

### PR DESCRIPTION
**Pull request by kb0304**
@RocketChat/core 

Closes #9488 

Add route:
`/api/v1/shield.svg?type=user&username=USERNAME`

Displays user's `name` and `status` as follows:

shield-online
shield-away
shield-busy
shield-offline

Please guide me how can I improve the code further. Thank You.

### CODE REVIEW

**Comment by jhermann** [comment]
Choosing black as the text color would benefit all but the red version. Or dial the background way darker – bad contrast plagues the current RC default theme, no need to extend that to the shields.

**Comment by kb0304** [comment]
I have made the background darker. Please check the following and suggest further changes. I will update the PR accordingly.

shield-online 1
shield-away 1
shield-busy 1
shield-offline 1

Hex values : #1FB31F, #DC9B01, #BC2031, #A5A1A1

**Comment by graywolf336** [comment]
Looking good :+1: once you make the changes, I'll take a look

**Comment by kb0304** [comment]
@graywolf336 
Hi Bradley,
I have updated the color schemes to as in my previous comment. Please have a look now.
Thanks

**Pull request merged**
