### PR TITLE
fix: incorrect Email Validation and Persistent display of error message on message selection in MailExportForm

### PR DESCRIPTION
**Pull request by Shahmaz0**
## Proposed changes (including videos or screenshots)

In the Export Message dialog box
1. Made some changes in validateEmail function to validate the email according to RFC standards.
2. Also did some changes in regex in emailValidator and made it more efficient

## Issue(s)

fixed: #32974

### CODE REVIEW

**Review by Gustrb — CHANGES_REQUESTED** [review]
Could you add some tests showing which emails were rejected that shouldn't??
I don't think the email regex matches exactly the RFC in any of the cases 🤔

**Comment by Shahmaz0** [comment]
## Actual Behaviour: 

* This is the current emailValidation that we are seeing in our codebase.

https://github.com/user-attachments/assets/1bd8ccf6-6913-42d9-a796-288e45fa47ad

## After the changes that i did:

* This is the output after changes i did which more efficient and robust.


https://github.com/user-attachments/assets/12ff6a7e-2221-49d1-a273-5229094b5c26

**Comment by Gustrb** [comment]
> ## After the changes that i did:
> * This is the output after changes i did, more efficient and robust.
> 
>  Fixed.mov

Wouldn't this happen just by virtue of passing the { style: 'rfc' }?
I am skeptical of the Regex change, that is why I asked for some test cases

**Comment by Gustrb** [comment]
As per @rique223 explained in the issue, emails without TLD are not invalid per se, I don't think this PR makes a lot of sense

**Pull request closed without merging**
