### PR TITLE
Develop sync

### PR DESCRIPTION
**Pull request by rodrigok**

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@rodrigok Any way this can go out with next release?

Looks like: https://github.com/RocketChat/Rocket.Chat/pull/7102 targeted master so didn't make it in 0.57.1 or 0.57.2 so the method getRoomNameById doesn't exist

Related to: https://github.com/RocketChat/hubot-rocketchat/issues/225

**Comment by rodrigok** [comment]
@geekgonecrazy Are you sure it was not in the .2 release? Cuz the release was made from master

**Comment by geekgonecrazy** [comment]
:joy: disregard :)

**Comment by rodrigok** [comment]
@geekgonecrazy Can you aprove this PR?

**Comment by sampaiodiego** [comment]
where is `0.57.2` release notes?

**Pull request merged**
