### PR TITLE
[FIX] Push gateway and cloud integration

### PR DESCRIPTION
**Pull request by sampaiodiego**
## Proposed changes

Add more strict relationship between push gateway and cloud registration.

Disable push gateway if server is not registered to our cloud services but also alerts admins via a banner and a message as shown on the screenshot below.

## Screenshots

* alert and message sent to admins during upgrade
image

* new description to settings
image

image

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
This alert is only when disabled indirectly right?

**Comment by sampaiodiego** [comment]
the alert is triggered only during server upgrade if push gateway is enabled and server is not registered and cloud services terms not agreed.

after server upgrade push gateway will be blocked if those conditions are not met, thus no alert needed.

**Comment by sampaiodiego** [comment]
> I think we need to make sure to add a checkbox on the connectivity services screen to agree otherwise once through wizard they have no clear place to find this

we'll add a checkbox in another PR 😉

**Comment by rodrigok** [comment]
@Exordian that's a good question, we didn't realize other push gateways may exist. Will figure out a solution for that.

**Pull request merged**
