### PR TITLE
[FIX] Added missing Nextcloud icon

### LINKED ISSUE #16980: Missing Nextcloud Icon
### Description:

Missing Nextcloud icon on login screen (Oauth).

Server: https://chat.melroy.org/

### Steps to reproduce:

1. Enable Nextcloud Oauth
2. Fill-in the ID/secret and all. Press Save.
3. Log-out and visit the login window.

### Expected behavior:

Instead of "NEXTCLOUD", I expect the icon of Nextcloud. Just like Gitlab, etc.

### Actual behaviour:

nextcloud_icon_not_loaded

### Server Setup Information:

See attachment.
[statistics.json.zip](https://github.com/RocketChat/Rocket.Chat/files/4372165/statistics.json.zip)

### Client Setup Information

- Desktop App or Browser Version: Browser - Firefox v.74
- Operating System: Linux Mint 19.3

 XFCE

### Additional logging (browser)

```
Error loading moment locale: 
Object { stack: "r@https://chat.melroy.org/13eba955117b5c7d57ae08e2221bd9c20f388e68.js?meteor_js_resource=true:1:4173\n_livedata_result@https://chat.melroy.org/13eba955117b5c7d57ae08e2221bd9c20f388e68.js?meteor_js_resource=true:695:17753\nonMessage@https://chat.melroy.org/13eba955117b5c7d57ae08e2221bd9c20f388e68.js?meteor_js_resource=true:695:20094\n_launchConnection/this.socket.onmessage/<@https://chat.melroy.org/13eba955117b5c7d57ae08e2221bd9c20f388e68.js?meteor_js_resource=true:693:2681\nforEachCallback@https://chat.melroy.org/13eba955117b5c7d57ae08e2221bd9c20f388e68.js?meteor_js_resource=true:693:3827\n_launchConnection/this.socket.onmessage@https://chat.melroy.org/13eba955117b5c7d57ae08e2221bd9c20f388e68.js?meteor_js_resource=true:693:2650\nt/a</r.prototype.dispatchEvent@https://chat.melroy.org/13eba955117b5c7d57ae08e2221bd9c20f388e68.js?meteor_js_resource=true:693:6334\nt/a</k.prototype._dispatchMessage@https://chat.melroy.org/13eba955117b5c7d57ae08e2221bd9c20f388e68.js?meteor_js_resource=true:693:19967\nt/a</k.prototype._didMessage@https://chat.melroy.org/13eba955117b5c7d57ae08e2221bd9c20f388e68.js?meteor_js_resource=true:693:20869\nt/a</k.websocket/o.ws.onmessage@https://chat.melroy.org/13eba955117b5c7d57ae08e2221bd9c20f388e68.js?meteor_js_resource=true:693:23022\n", isClientSafe: true, error: "moment-locale-not-found", reason: "Moment locale not found: 39", details: undefined, message: "Moment locale not found: 39 [moment-locale-not-found]", errorType: "Meteor.Error" }
13eba955117b5c7d57ae08e2221bd9c20f388e68.js:973:83158

uncaught exception: undefined
```

### PR DESCRIPTION
**Pull request by melroy89**
Closes #16980

`icon-nextcloud` was missing on fontello for some reason. I imported the original json file added my Nextcloud SVG logo and updated all needed files within Rocket.chat git repo.

Before (notice the missing icon for Nextcloud):

image

Thanks.

Regards,
Melroy

### CODE REVIEW

**Comment by danger89** [comment]
Or try to use the Fork-Awesome project instead. Since this one has the logo:

https://forkaweso.me/Fork-Awesome/icon/nextcloud/

**Comment by danger89** [comment]
Error in CI/CD pipeline of the build image doesn't looks like it's related to this issue:

> denied: Resource not accessible by integration

Can't fix.

**Comment by danger89** [comment]
@Sing-Li What do you think?

**Comment by danger89** [comment]
@ggazzo could this be merged?

**Comment by danger89** [comment]
@engelgabriel I see a commit to this PR, but it's not merged?

**Comment by danger89** [comment]
Released my own build: https://server.melroy.org/Rocket.Chat.tar.gz

**Comment by danger89** [comment]
You do want to remove 'NEXTCLOUD' text from the service.buttonLabelText value of the Nextcloud service. But I don't know where that field is defined in this code.

Otherwise you have both a logo + still the text (you only want to have the logo):

image

**Comment by danger89** [comment]
I signed the SLA, but engelgabriel is from your own team.

**Comment by danger89** [comment]
I removed my fork in the mean time.. Sorry... But it took way to long. It's 1.5 year later. Still no response or anything.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Closing this PR because it's stale now and it was already fixed in another one.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Pull request closed without merging**
