### PR TITLE
Remove registration name requirement

### PR DESCRIPTION
**Pull request by yakirac**
Name is now optional when registering

PR for https://github.com/RocketChat/Rocket.Chat/issues/610

### CODE REVIEW

**Comment by engelgabriel** [comment]
Thanks @yakirac I agree the name requirement should not be mandatory, but instead of just changing the behaviour, we need to make it optional on the admin setting.

@gmsecrieru can you give some help here?

**Comment by gmsecrieru** [comment]
Hey @yakirac , once again thanks for your contribution! :) We usually handle this kind of thing as an Admin option so we can give people option on how to setup their on instances. I have implemented this same behavior following this approach in the branch [improvement-registration-optional-name](https://github.com/RocketChat/Rocket.Chat/tree/improvement-registration-optional-name) so you can review for similar future contributions. Could you please review those changes and sync your PR with them so we can merge it?

**Comment by yakirac** [comment]
@engelgabriel @gmsecrieru My apologies. Thanks for letting me know. I'll sync my PR and get this fixed up.

**Comment by gmsecrieru** [comment]
Not a problem and thanks again!

**Comment by marceloschmidt** [comment]
Is this the final code? Can we test and merge if appropriate? (I'm asking because @gmsecrieru added In Progress, meaning we could not merge yet)

**Comment by gmsecrieru** [comment]
LGTM!

**Pull request merged**
