### PR TITLE
Chore: Change Omnichannel aggregations to run on a secondary

### PR DESCRIPTION
**Pull request by KevLehman**

### CODE REVIEW

**Comment by ankar84** [comment]
Thank you, Kevin!

**Comment by sampaiodiego** [comment]
I think there are a few conflicts to solve 🙈

**Comment by KevLehman** [comment]
> I think there are a few conflicts to solve 🙈

C'mon, just like 1 or 2 lines of conflicts. EZ

**Comment by KevLehman** [comment]
@sampaiodiego , you can do your magic with the review now :trollface:

**Pull request merged**
