### PR TITLE
Reactions support

### LINKED ISSUE #505: Add reaction support
Something like this: https://slack.zendesk.com/hc/en-us/articles/206870317-Emoji-reactions

Would be pretty cool!

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25945335-add-reaction-support?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sampaiodiego**
How it looks:
image

How to react:
image
image

Who reacted:
image

Closes #505

### CODE REVIEW

**Comment by rodrigok** [comment]
LGTM

**Comment by geekgonecrazy** [comment]
some reason the heroku deploy is bootlooping... but code looks good :+1: 

LGTM

**Comment by gcassel** [comment]
Right now, Reactions are working great for me in Firefox on Windows 10!  However, I have a problem on Android:
rc3

@sampaiodiego , can you please tell us if you're aware of this issue, and if there are any plans yet to address it?

I love the work you're doing, and hoping to migrate some groups from Slack to Rocket Chat as soon as the transition seems feasible!

**Comment by sampaiodiego** [comment]
hi @gcassel .. yes, I'm aware of this issue.

we're releasing on the next few days an updated of the android (and iOS) app which removes the cog button and adds a long press menu. =)

for now, you can rotate your phone, so the reaction button will be visible (this is how I do today :smile: )

**Pull request merged**
