### PR TITLE
WIP: Styles architecture cleanup

### PR DESCRIPTION
**Pull request by Igloczek**
Styles part of this chat looks messy, but before more radical code changes will be nice to fix overall architecture. Most of the code sits inside one enormous file (over 5000 LoC), imports are handled manually, by merging files, which are defined manually inside build pipeline configuration... It's hard to maintain or even understand, it took me few hours to get familiar with it and made some (not working) changes.

I know is related to the way you are handling variables values defined by user, but it breaks rules of working with LESS (or any other pre-processed) code. 

Working `@import` is key to keep styles simple and modular. Same about ability to have multiple output files (i.e. one per view or some view group) to reduce unused code ratio and just simplify development. Even now everyone have to download RTL styles, doesn't matter if they need them or not, just b/c there is only `theme.css` file.

Much better option will to create a temp file with user defined variables during build process, then inject `@import` to this file inside root files, save them in temp directory, which contains symlinks to all partials and then compile. This will let us to keep writing styles native or very close to native.

Last part of necessary changes will be to replace LESS with some better processing.
SASS will be okay, it's way more strict (proper compilation order, self-descriptive syntax, well known structure of conditional statements and loops, instead of weird `when` based s**t), have bigger market share and it's faster.
PostCSS is also an option, few plugins and all necessary things will be covered, but it will lead to plugin-depended syntax, which might be a barrier for contributors.

### CODE REVIEW

**Comment by karlprieb** [comment]
@Igloczek Thanks for that :)

I liked the way you organize the CSS files and I agreed with you about our build process, we are already discussed about that and we will improve the process, but I don't get why we should change to SASS.
With `libsass` we will gain speed, but with that we will have to force the users to install C compilers to build Rocket.Chat. Currently Rocket.Chat will only require `meteor` to build.

How faster is PostCSS and which are the advantages over Less?

**Comment by engelgabriel** [comment]
Let's close this in favor of https://github.com/RocketChat/Rocket.Chat/pull/5364

Most of the changes there are aligned with what is proposed here, and we used this PR as the starting point.

We will move back the compilation of all LESS files back to building time, and only keep in the runtime the `colors.less`, that will be converted into a much simpler `CSS`so it can be rendered using a Blaze template.

Also, we will try remove the dependency on lesshat.

**Comment by Igloczek** [comment]
Holly smoke, you are writing code faster than I'm answering your questions, good job! 😜 

---

There is also [node-sass](https://github.com/sass/node-sass) .
> Node-sass is a library that provides binding for Node.js to LibSass, the C version of the popular stylesheet preprocessor, Sass.

First of all let me give you some quick backstory of my relationship with LESS to make clear that's I'm no.1 hater of LESS on earth and probably even in whole universe 🌚 🌝 

On my daily basics I'm working with Magento and last year they released version 2.0. We are waiting for them like 5 years, looking for some step forward into modern web development, but we've got server-side PHP processed LESS files, which require another PHP processor to run before compilation and it takes like 30 second to get any output, ofc there were no place for any post-processing etc., b/c there were only PHP.

Previously my LESS experience was in scale from 0 to 10, like 1. I know just it's a something similar to SASS and it's easy to replace, due to almost same syntax.
Oh my gawd, how [wrong](http://i.giphy.com/3oz8xLd9DJq2l2VFtu.gif) I was :O

After spending some time with it, I realize that's the only option is to change language. LESS let do (evil) developers, pure evil things, which is not obvious just looking on simple code (like this one in rocket.chat). 

That's why I organize whole community movement to get rid of it, then made a few conference talks about this problem, spend hundreds of hours building own tools, themes, educating, speaking with Magento engineers etc.

Explaining drawbacks of LESS here will take me some time, but instead you can watch first 10:30 min of my presentation at #mm16de [here.](https://iglo.tech/my-talk-on-meet-magento-germany-2016/). [Small example of their magic code.](https://github.com/magento/magento2/blob/develop/lib/web/css/source/lib/_forms.less)

---

I'm not an expert of PostCSS things, I'm using only few plugins, only after SASS compilation so it's hard to say. But community voices are "it's the fasters", but no one know which plugin they choose and if it was fun to use 😉 
From my perspective, even it it was like 50% faster, replacing well known syntax with nice market share in favor of saving ~200ms, isn't a good idea.

**Comment by karlprieb** [comment]
Thanks for this explanation @Igloczek 😄 I will watch your talk. The thing with node-sass is the C compiler dependency, node-sass will compile libsass on your machine, it's not an option for us even knowing that the libsass is much faster than LESS.

I'm a PostCSS enthusiastic... I really like it, but I need to do some testing (basically performance) to know if worth change to.

**Comment by engelgabriel** [comment]
dec-29-2016 15-26-57

**Comment by engelgabriel** [comment]
dec-29-2016 15-32-39

**Comment by engelgabriel** [comment]
@Igloczek please not the time between meteor has detected the changes on the files on the terminal on the top right, and the refresh of the style on the top left. :)

**Comment by Igloczek** [comment]
For me compilation speed in this case is a minor thing, b/c Meteor kill any kind of fast processing, so second less or second more when we are talking about 10-15 second of processing on every change, doesn't make any difference.

But at all, you are masters here, I'm just sharing my perspective and I'm so glad that you are here, trying to "Make rocket.chat styles great again", responding quickly and just facing all of this issues. One more time - great job guys!

**Pull request closed without merging**
