### PR TITLE
[FIX] Fix LDAP login by REST API, normal login and 2FA as well.

### LINKED ISSUE #4961: REST API - LDAP login not working
Your Rocket.Chat version: (make sure you are running the latest)

Hi,
I have LDAP set and user can properly login from the UI.
They are synchronized properly but when I try login in (first login) through the API I get 401 "Unauthorized"
Is there any special configuration that I am missing?

After the initial load from login via UI the API login works fine

Tks

### LINKED ISSUE #5499: Login with LDAP via Iframe
Hi,
I have a Rocket.Chat instance on my server with standalone LDAP server. Iframe.contentWindow.PostMessage with login-with-token event works great for logging users, but only for those previously logged in with Meteor.loginWithLDAP method. Is there a way to login users with LDAP via Iframe (or API) ? Or just run Meteor.loginWithLDAP from iframe parent window?

### LINKED ISSUE #7642: API login doesn't work with an LDAP user when "Login Fallback" parameter is False
### Description:
Configure LDAP auth with "Login Fallback" parameter to False.

Log yourself with a valid user normally to validate that the user/pass is valid.

Use the same user/pass to perform an API authentication:
```
curl -H "Content-type:application/json" http://localhost:3000/api/v1/login -d '{ "username": "supervisor", "password": "xxxxxxx" }'
{
  "status": "error",
  "message": "Unauthorized"
}
```
Change the "Login Fallback" parameter to True, then log yourself again on the web interface with the same user to store the password in the local database, you then set the "Login Fallback" parameter to False again, it doesn't mater.

The authentication will now work with the same login/pass:
```
curl -H "Content-type:application/json" http://localhost:3000/api/v1/login -d '{ "username": "supervisor", "password": "xxxxxxx" }'
{
  "status": "success",
  "data": {
    "authToken": "KJQhGtdtBb0ecSn3CUQCpCWNUB6nVhpA226GEMM_72M",
    "userId": "tkBC5AEQvDLZ5SqNc"
  }
}
```
The API should ask LDAP when a user tries to use it and LDAP is active.
### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.2
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: no
* Node Version: 4.5.0

### LINKED ISSUE #11411: Fail to login with  the REST API
I used the REST API to login, but the following error happened. I used wireshark to observe and although 200 is returned, not the json data, one html data is returned. I don't understand where the problem is.

 File "D:/06_PythonProject/Test/RocketChat.py", line 19, in <module>
    main()
  File "D:/06_PythonProject/Test/RocketChat.py", line 12, in main
    rocket = RocketChat('XXXX', 'XXXXX', server_url='https://open.rocket.chat/home')
  File "C:\Python27\lib\site-packages\rocketchat_API\rocketchat.py", line 21, in __init__
    self.login(user, password)
  File "C:\Python27\lib\site-packages\rocketchat_API\rocketchat.py", line 78, in login
    if login_request.json().get('status') == "success":
  File "C:\Python27\lib\site-packages\requests\models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

### PR DESCRIPTION
**Pull request by MarcosSpessatto**
Closes #5499
Closes #4961 
Closes #7642 
Closes #11411

and partially: #11570

### CODE REVIEW

**Comment by suportecri1** [comment]
waiting for it so much!

**Comment by toimtoimtoim** [comment]
It would be really nice to see this resolved, merged and released. We have LDAP in our corporate infrastructure and this problem blocks us creating CI bots using REST API.

**Comment by MarcosSpessatto** [comment]
We must have [this PR](https://github.com/RocketChat/Rocket.Chat/pull/11726) merged before working again on this one.
Depends of: https://github.com/RocketChat/Rocket.Chat/pull/11726
Refs: https://github.com/RocketChat/Rocket.Chat/issues/11570#issuecomment-411867583

**Comment by engelgabriel** [comment]
We may have fixed these issues on our latest refactoring. @rodrigok will check and update the PR and related issues.

**Comment by StarScream902** [comment]
I have the same problem with the login of Jenkins plugin for rocketchat to rocketchat server. But, the plugin connects, when rocketchat is set up without LDAP.
And I found this hidden login payload too
```
curl -s -H "Content-type:application/json" \
      ${ROCKET_URL}/api/v1/login \
      -d "{\"ldap\": true, \"username\": \"${ROCKET_USER}\", \"ldapPass\": \"${ROCKET_PASSWORD}\", \"ldapOptions\":{} }"
```
And this solution Is not suitable for me, because I need the working plugin

**Comment by TBG-FR** [comment]
Any updates on this ?

**Pull request closed without merging**
