### PR TITLE
[FIX] Save button does not stay disabled in Notification Preferences for no change on mute group option

### LINKED ISSUE #27512: [BUG] - Save button does not stay disabled in Notification Preferences for no change
### Description:

https://user-images.githubusercontent.com/91999901/206894234-9f993371-64d9-47f0-9c37-4c034a168104.mp4

### Steps to reproduce:
on a refreshed page
1. On a refreshed page of the channel (or go to another channel on a refreshed page) , click on three-dots menu on right corner.
2. Click on the Notification Preferences, toggle "Mute @all and @here mentions" on and then off again.
3. Disabled "Save" button does not stay disabled. 

### Expected behavior:

"Save" button should stay disabled.

### Actual behavior:

"Save" button is enabled even toggle button is off as before (i.e even after no change)

### Server Setup Information:

- Version of Rocket.Chat Server:  5.5.0-develop
- Operating System: Ubuntu 20.04.5 LTS
- Deployment Method: yarn dsv
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.3
- MongoDB Version: v5.0.12

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 107.0.5304.87 (Official Build) (64-bit)
- Operating System: Ubuntu 20.04.5 LTS

### Relevant logs:

LocalStore: store created at  
LocalStore: store created at  
LocalStore: store created at  
Loaded the Apps Framework and loaded a total of 0 Apps! 
LISTENING 
+-----------------------------------------------+ 
|                 SERVER RUNNING                | 
+-----------------------------------------------+ 
|                                               | 
|  Rocket.Chat Version: 5.5.0-develop           | 
|       NodeJS Version: 14.19.3 - x64           | 
|      MongoDB Version: 5.0.5                   | 
|       MongoDB Engine: wiredTiger              | 
|             Platform: linux                   | 
|         Process Port: 24187                   | 
|             Site URL: http://localhost:3000/  | 
|     ReplicaSet OpLog: Enabled                 | 
|          Commit Hash: e0de8d4eb1              | 
|        Commit Branch: develop                 | 
|                                               | 
+-----------------------------------------------+

### PR DESCRIPTION
**Pull request by xareyli**
## Proposed changes (including videos or screenshots)

Added default value for "Mute @all and @here mentions" option

## Issue(s)

Closes #27512
## Steps to test or reproduce

Follow the instructions in the issue

## Further comments

Lack of default value for `muteGroupMentions` may cause unexpected behavior

### CODE REVIEW

**Comment by xareyli** [comment]
@hugocostadev please review

**Comment by debdutdeb** [comment]
I think in this case we're using *any* falsy value indication. If that's the case not sure whether this patch is necessary or not.

**Comment by hugocostadev** [comment]
@debdutdeb is right, I don't think that this is necessary.

@xareyli did you face some issues with this?

**Comment by xareyli** [comment]
I haven't faced any issues with this. Through logging I have figured out that lack of initial value for `muteGroupMentions` causes the bug (https://github.com/RocketChat/Rocket.Chat/issues/27512). Initially `muteGroupMentions` is undefined. When user toggles it the value turns to `true`. When they toggle it again, the value is `false`, which differs from `undefined`. On my opinion `muteGroupMentions` should have initial value. But if I am not right, please close the PR. Thanks

@hugocostadev @debdutdeb

**Comment by debdutdeb** [comment]
I see.

Ok, for now, we don't have a standard for domain specific falsy values (i.e. for strings, '' instead of undefined, for boolean, false instead of undefined, and so on). I think, for now, a better approach to fixing this would be to figure out what frontend logic is handling the state diff first, and see if it can be fixed there.

**Comment by xareyli** [comment]
I had a little research on this.

Here we define the `muteGroupMentions` as `undefined`, which then will be tried to cast to `boolean`, which leads to `muteGroupMentions` is defined with undefined value. My idea is to cast `muteGroupMentions` to `boolean` when getting defined (in the first line)
https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferencesWithData.tsx#L33
https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferencesWithData.tsx#L42

I understand my bad and I am going to create a commit for this PR, which will fix the issue correctly

**Comment by xareyli** [comment]
@debdutdeb please review. Think this should work

**Comment by debdutdeb** [comment]
Change the pr title to what you're fixing, not what you're doing code-wise, as that doesn't give us context as to why we need the patch.

**Comment by xareyli** [comment]
@debdutdeb @hugocostadev if you have spare time, please review

**Review by hugocostadev — APPROVED** [review]

**Pull request merged**
