### PR TITLE
Add settings for Piwik Analytics, for #233

### LINKED ISSUE #233: Piwik integration
Piwik is the leading open-source analytics platform.
It will be very nice to have an integration with Piwik - only need to specify a siteID (a number), the url for your own piwik tracker and to put the generated code from piwik in some place on the site.
This is for the basic intergration.

It can be a bit challanging to use all of piwik features, but we might not have to - it's your choice.

As I've already said, the basic integration is very simple and easy to implement in any website.

We should have settings for that too. It can be in some config file, I really don't care, beacuse in Rocket.Chat you only config this once, and if the url and the siteID aren't changing than we have no more work to do. So UI settings doesn't have to be a requirement.

See more on: http://piwik.org/ or https://github.com/piwik/piwik

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/23135257-piwik-integration?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by graywolf336**
@RocketChat/core 

Closes #233

Right now this is a very basic implementation and only tracks the first page view. Later implementations might extend this further.

Couldn't exactly test locally for some reason, so I am committing this to test via the requested deployment.

### CODE REVIEW

**Comment by graywolf336** [comment]
@RocketChat/core this is ready to be merged, I verified it. Next integration level will contain event tracking statistics with piwik, including but not limited tracking channel creations, deletions, archiving, and sending them to the piwki.

**Comment by sampaiodiego** [comment]
LGTM

**Comment by marceloschmidt** [comment]
LGTM

**Comment by graywolf336** [comment]
Closing in favor of a new pull request I will be opening in a few days.

**Pull request closed without merging**
