### PR TITLE
Livechat valid domains

### PR DESCRIPTION
**Pull request by AlecTroemel**
@RocketChat/core 

When enabled, restrict the embedding of the livechat widget to a list of domains. Uses the `X-FRAME-OPTIONS` head in addition to actually serving the app. So, if enabled and your domain is valid `X-FRAME-OPTIONS = ALLOW-FROM yourDomain` (for when browsers finally support that)
screen shot 2017-01-06 at 3 32 24 pm
When domain is invalid
screen shot 2017-01-06 at 3 33 48 pm
When domain is valid 
screen shot 2017-01-06 at 3 34 31 pm

Also includes rest api endpoints to list/add/remove valid domains

### CODE REVIEW

**Comment by sampaiodiego** [comment]
@AlecTroemel thanks for this awesome addition. 
you've added the REST APIs also, that's amazing!

the cons:
- I didn't like the sweer alert to include new domains
- the domain validation is not working for me

what you think in just having a setting of "Livechat allowed domains" (pretty much like `Allowed domains list` - under `Admin > Accounts > Registration`)?

I just add config options under `Livechat` menu to the settings I think livechat managers should be able to manage. But I think the _allowed domains_ should be managed by the admins only. what you think?

**Comment by AlecTroemel** [comment]
@sampaiodiego hadn't thought about the visibility between managers and admins.. I agree with the move, `Admin -> Livechat`. Having it simply be a Comma-separated list will make things a lot simpler too (no need for a mongoDB model 😄 ). Would we want to have an "enabled" boolean, or just assume if the list is empty all domains are valid?

For your issue with the validation, is it never serving the livechat widget, or always serving it? It's probably an issue with my regex used to parse the domain. I'll take a look at what you guys are already doing with `Allowed domains list` - under `Admin > Accounts > Registration` (I didn't know that setting existed!)

**Comment by sampaiodiego** [comment]
@AlecTroemel I'm sorry I was not clear enough.. what I meant was that I was able to save domains like `1111` (without `www` and TLD as well)..

having it only on _Admin_ there isn't also the need for custom REST APIs :wink: 

I think there is no need to have a toggle. Maybe we can let that clear on setting's description that having no allowed domains means _any domain is valid_ .. what you think?

**Comment by AlecTroemel** [comment]
@sampaiodiego Ah I see the problem now. I agree thats there's no need for the toggle, also matches the pattern with the other domain list settings.

I personally still have some value with the rest api, specifically being able to add and remove domains programmatically without parsing the string each time, so I'll be updating the routes for my own personal use. But I can definitely see how they don't fit with the current Rest API paradigm since it will just be a single setting. I'll remove them when I update the PR unless people want them

**Comment by AlecTroemel** [comment]
updated based on the comments above. domains are now set in `admin -> Livechat`. Was able to remove a majority of the files/logic needed the old way (thanks @sampaiodiego!)
screen shot 2017-01-10 at 11 21 23 am

**Comment by sampaiodiego** [comment]
@AlecTroemel the REST APIs are still here. they are not working right (they are still using `RocketChat.Livechat.addValidDomain`)?

**Comment by AlecTroemel** [comment]
whoops, just pushed with the removal.

**Pull request merged**
