### PR TITLE
[BREAK] Remove Sandstorm login method

### PR DESCRIPTION
**Pull request by sampaiodiego**
@RocketChat/core 

Looks like the Sandstorm package does not work with Meteor 1.5. It's logging me out on every page refresh and given the error below:
image

Also looks like our latest version available on Sandstorm grain is outdated, so I'm removing the Sandstorm login package until it can get it fixed.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Is there an upstream repo we can post an issue on?

**Comment by sampaiodiego** [comment]
> Is there an upstream repo we can post an issue on?

@geekgonecrazy yes: https://github.com/sandstorm-io/meteor-accounts-sandstorm

**Comment by geekgonecrazy** [comment]
:+1: created issue.

**Comment by rodrigok** [comment]
@sampaiodiego Can you solve the problems with sandstorm usage like:
```
RocketChat.Sandstorm.notify
```
That is generating the error:
```
I20170725-11:05:20.147(-3)? Exception in defer callback: TypeError: Cannot read property 'notify' of undefined
I20170725-11:05:20.147(-3)?   at /Users/rodrigonascimento/Projects/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:2107:24
I20170725-11:05:20.147(-3)?   at /Users/rodrigonascimento/Projects/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:316:25
I20170725-11:05:20.148(-3)?   at Array.reduce (native)
I20170725-11:05:20.148(-3)?   at Object.RocketChat.callbacks.run (/Users/rodrigonascimento/Projects/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:309:6)
I20170725-11:05:20.148(-3)?   at /Users/rodrigonascimento/Projects/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:3205:31
I20170725-11:05:20.149(-3)?   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
I20170725-11:05:20.149(-3)?   at packages/meteor.js:445:51
I20170725-11:05:20.149(-3)?   at runWithEnvironment (packages/meteor.js:1180:24)
```

**Pull request merged**
