### PR TITLE
[FIX] Make the sidebar flextab higher than unread bar 

### LINKED ISSUE #14448: Unread message bar shows above flextab
### Description:

The unread message bar has a z-index that is higher than the contextual-bar flextab.

### Expected behavior:

image

### Actual behavior:

image

### Server Setup Information:

- Version of Rocket.Chat Server: open.rocket.chat

### PR DESCRIPTION
**Pull request by wreiske**
Closes #14448

### Before

image

### After

image

### CODE REVIEW

**Comment by ggazzo** [comment]
could you test again our last version, I'm quite sure I already made a fix for that, btw thanks

**Comment by ggazzo** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/14443

**Comment by wreiske** [comment]
> could you test again our last version, I'm quite sure I already made a fix for that, btw thanks

Looks like this is good now.... it wasn't last night when I tested...

image

looks a bit off though.

**Comment by ggazzo** [comment]
I'm gonna close this, thanks @wreiske and I'm trying to improve this bar too ;)

**Pull request closed without merging**
