### PR TITLE
[NEW] Functionality to hide all direct messages with a button

### LINKED ISSUE #14003: Improvement: Hiding all direct messages with a single button
Description:
- Currently it's only possible to hide direct messages one at a time to prevent the Direct Messages list from getting large

Use case:
- I constantly chat with different people to ask questions/give feedback etc., but those conversations are finished rather quickly, and yet to get them out of the list of Direct Messages I have to manually hide every single chat

Expected result:
- I want a button to be able to hide every chat at the end of the day to start the next day with a "clean slate" as far as Direct Messages are concerned, especially considering a chat will be visible again if something new is happening in it

### PR DESCRIPTION
**Pull request by mohamedar97**
Closes #14003

### CODE REVIEW

**Comment by knrt10** [comment]
@mohamedar97 your git config is not set correctly on your local machine. Fix that to sign the CLA

**Comment by mohamedar97** [comment]
@knrt10 any advice on how to do that, resources would be great

**Comment by mohamedar97** [comment]
i think i'm ruining everything now. should i close this and create a new PR?

**Comment by knrt10** [comment]
@mohamedar97 [Check this](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup)

**Comment by mohamedar97** [comment]
i have done everything in the article now
what should i do next?

**Comment by mohamedar97** [comment]
i opened another PR #14037 i have this issue fixed there. closing this one

**Pull request closed without merging**
