### PR TITLE
Update emojione to 2.2.5

### LINKED ISSUE #3735: Emoji One upgrade to v2.2.5
Emoji One has received an update.
https://github.com/Ranks/emojione/releases

Features new 'Unicode 9' set which might be useful to colorify what one has to say.

Please add support for the new ones.

Your Rocket.Chat version: 0.35.0

### PR DESCRIPTION
**Pull request by xasx**
@RocketChat/core 

Closes #3735 

Is this sufficient or are there any further build steps involved?

### CODE REVIEW

**Comment by xasx** [comment]
Hmm, wondering why `emojione` does not show up in Travis' log as an updated dependency...

**Comment by xasx** [comment]
Codacy issues come from upmerge.

**Comment by marceloschmidt** [comment]
Sorry @xasx I've updated the emojione after a conversation we had without realizing you had a PR open. We'll merge it anyway :D thanks for your time and efforts.

**Comment by purldator** [comment]
@xasx @marceloschmidt A bug exists with this update.

image

That is suppose to be :zzz:.

Emoji are now out of alignment.

image

(I just pulled, rebuilt and deployed the latest dockerfile from the develop branch.)

**Pull request merged**
