### PR TITLE
[NEW] Add markdown parser "marked"

### PR DESCRIPTION
**Pull request by nishimaki10**
@RocketChat/core 

[marked](https://github.com/chjj/marked) is support GFM.
- ruler
- tables
- lists

---

ss

------

You can select parser Original or Marked.

ss2

### CODE REVIEW

**Comment by shtefcs** [comment]
This is really cool @nishimaki10  .

Waiting for approval of this PR.

**Comment by RichardFoxworthy** [comment]
Will markdown messages be rendered properly in email alerts?

**Comment by shtefcs** [comment]
@RichardFoxworthy  Can't confirm, but I guess will not.

**Comment by nishimaki10** [comment]
Why Travis CI is not running?

**Comment by rodrigok** [comment]
@nishimaki10 can you solve the conflicts?

**Comment by nishimaki10** [comment]
@rodrigok yes, solved.

**Comment by rodrigok** [comment]
@nishimaki10 Idk why, but travis think this PR as an abuse, so I'll create a new one

image

**Comment by rodrigok** [comment]
Closed in favor of https://github.com/RocketChat/Rocket.Chat/pull/7852

**Pull request closed without merging**
