### PR TITLE
Better visual for highlighting

### LINKED ISSUE #2486: Highlight words - Visual inconsistency
Your Rocket.Chat version: 0.21.0 (deployed through Docker)

`@mentions` have bolded text and a rounded background. Extra highlight words currently look out of place.

image

### PR DESCRIPTION
**Pull request by fduraibi**
May closes #2486 

A small enhancement to the CSS of word highlighting

Before:

rocket1

After:

rocket2

The background is set to be lighter than the own `@mention` to not confuse them with each other. Also mentions are bold and in white color. The yellow background felt kinda dull and similar to the emoji's color

### CODE REVIEW

**Comment by rodrigok** [comment]
@fduraibi awesome, but, can we use the same padding and radius from mentions?

```CSS
border-radius: 4px;
padding: 0px 4px 2px 4px;
```

**Comment by fduraibi** [comment]
@rodrigok the mention padding doesn't look good when I used it with the highlight (check picture)
rocket3

the radius is not that different so I will change it to 4px to unify them

**Comment by rodrigok** [comment]
LGTM

**Comment by engelgabriel** [comment]
LGTM

**Pull request merged**
