### PR TITLE
[IMPROVE] Added reset and save buttons for the permissions

### LINKED ISSUE #5436: Add a reset button in permissions
its easy to mess up the permissions, a reset button would be very useful there.

### PR DESCRIPTION
**Pull request by ritwizsinha**
Closes #5436 

out

### CODE REVIEW

**Comment by ritwizsinha** [comment]
@MartinSchoeler please review

**Comment by ritwizsinha** [comment]
@MartinSchoeler please review

**Comment by gabriellsh** [comment]
Hey @ritwizsinha, how's it going?

So, most admin settings are on our roadmap to be redesigned as soon as possible, and this one is one of our priorities. There are a few things I'd like for you to fix/change in this PR, but due to these circumstances I won't take your time to do it, as if it even were to be merged, it wouldn't stay here for long.

Please don't let this discourage you!

And to not let you hanging for the review, as an advice, always try to look for other places where something similar to what you're doing has already been implemented, paying attention to what you need to keep/improve on it.

Thanks really much for your help!

**Comment by ritwizsinha** [comment]
@gabriellsh thanks for your feedback and review , I'll keep these points in mind next time, thanks

**Pull request closed without merging**
