### PR TITLE
[FIX] In threads sending a message should scroll to the sent message

### LINKED ISSUE #16280: In threads sending a message should scroll to latest thread message
### Description:
In threads the new messages are not automatically previed if the chat becomes more than the display area. It is lacking auto scroll behaviour

### Steps to reproduce:

1. Create a new thread or reply in an existing thread
2. Just make the chat long

### Expected behavior:
Like the normal message area it should automatically scroll to bottom.

### Actual behavior:
It is not automatically scrolling to bottom

asasasasa

### Additional context:
I am working on it

### PR DESCRIPTION
**Pull request by ashwaniYDV**
Closes #16280

 

### After Changes:
Whether you are in any part of messags in a the thread. When message is sent, it brings the user back to the sent message. This also ensures the user if sent markdown message is correctly rendered.

azazaaz

### CODE REVIEW

**Comment by ashwaniYDV** [comment]
@gazzo I dont know why I'm getting this alert from the bot. It is mentioning your commit https://github.com/RocketChat/Rocket.Chat/commit/f92cff77ee54d8b7ea588e2fe61922d5ebae9452

**Comment by zdumitru** [comment]
@gabriellsh Code review, please.

**Comment by ggazzo** [comment]
@ashwaniYDV could you check how we are using `resize observer` on `room.js` and apply the same behavior? thanks :)

**Comment by rodrigok** [comment]
@ggazzo should we close this one in favor of the new implementation?

**Pull request closed without merging**
