### PR TITLE
Removed site-specific information, see #234

### PR DESCRIPTION
**Pull request by warcode**
Changed default language to en-US.
Changed meta robots to ensure privacy-by-default.

### CODE REVIEW

**Comment by nevson** [comment]
Don't forget the Google Tag Manager and meta tags in the [client/views/main.html](https://github.com/RocketChat/Rocket.Chat/blob/e151b93a53507be503dd0e0c5f7bfa237a3110d7/client/views/main.html) :+1:

**Comment by engelgabriel** [comment]
Depends on #222

**Comment by joepie91** [comment]
This seems like it should be configurable.

Also, `robots` instructions are broken; [robots.txt doesn't actually serve a purpose](http://archiveteam.org/index.php?title=Robots.txt). 'Privacy' isn't obtained by asking a bot not to index a page.

**Comment by engelgabriel** [comment]
@joepie91 We are making everything configurable on the next version .

**Comment by marceloschmidt** [comment]
Part of this pull request has made into production. 
File public/landing/index.html will not be changed.

**Pull request closed without merging**
