### PR TITLE
Spotify enhancements to handle more syntaxes

### PR DESCRIPTION
**Pull request by kakawait**
From https://github.com/RocketChat/Rocket.Chat/pull/904#issuecomment-143839156 current *Spotify* plugin does not handle syntaxes like `spotify:user:spotifydiscover:playlist:2RjlnjirDnFioPelxk0g4M` or `spotify:user:spotify:playlist:1Gmt8tPWrRNyNjwCDsuEtk`

Plugin now support 4 groups syntax `spotify:TYPE:GROUP:GROUP:ID`

Samples

screen shot 2015-09-29 at 12 27 34

screen shot 2015-09-29 at 12 27 50

Even better than *Slack* that currently does not support

screen shot 2015-09-29 at 12 29 11

### CODE REVIEW

**Comment by kakawait** [comment]
There is a *bug* (it depends of point of view) but if you are using spotify syntax/link inside backtick quote  `` ` `` syntax/link will be processed? Do you think it should be fix?

**Comment by geekgonecrazy** [comment]
LGTM :+1: 

You're awesome!  Really cool especially since you don't use spotify :grinning: 

> There is a bug (it depends of point of view) but if you are using spotify syntax/link inside backtick quote ` syntax/link will be processed? Do you think it should be fix?

I think that is probably a bug.  I think anything inside 3 backticks should be ignored.  We should probably open an issue, and have a bit of discussion to make sure that's a consensus

**Comment by kakawait** [comment]
@geekgonecrazy not it only on simple backticks not 3 backticks like

`` `spotify:user:spotify:playlist:1Gmt8tPWrRNyNjwCDsuEtk` ``

**Comment by geekgonecrazy** [comment]
@kakawait ah!  sorry I mis-understood.  So you mean process even when quoted?

I don't think it would.  Usually we quote commands to demonstrate and not have them ran.  So I think you're good there.

**Comment by kakawait** [comment]
Screenshot is better than long discours :)

screen shot 2015-09-29 at 16 53 02

two first is OK, but third one is rendered

**Comment by geekgonecrazy** [comment]
Picture is worth a thousand words!  I see what you mean.  We need to fix that.  I personally think that quoting should escape everything.  Including links.

**Comment by geekgonecrazy** [comment]
@kakawait looks like the other format now doesn't work :)

`spotify:track:1L94M3KIu7QluZe63g64rv`

Any ideas to fix that?

**Comment by kakawait** [comment]
Oups I will check that tomorrow.

**Comment by rodrigok** [comment]
@kakawait don't work in Rocket.Chat electron app

**Comment by geekgonecrazy** [comment]
@rodrigok I think i've got a fix for that.  Its in how electron is setup.  Trying to get a few bugs ironed out of webview-switch branch and i'll get a PR open.

**Comment by kakawait** [comment]
@rodrigok whole integration or just some syntaxes?

**Comment by kakawait** [comment]
@rodrigok tested with https://github.com/RocketChat/Rocket.Chat.Electron/commit/611e1511531ce81995a97dd5bdfb814458c2cf9c works at home :)

screen shot 2015-09-30 at 12 05 42

**Comment by geekgonecrazy** [comment]
@kakawait yeah it seems to be certain cases, like I said pretty positive its on the electron end.

**Comment by rodrigok** [comment]
@kakawait the error happens for me when I try to play the music

**Pull request merged**
