### PR TITLE
[FIX] Displays the quoted or replied message above instead of below

### LINKED ISSUE #9799: Display quoted message above the user message
When quoting a message using the "Quote" or "Reply" action, I think it would be better if the quoted message appeared above the user message, not below as it is done currently:

image

This was already asked [here](https://github.com/RocketChat/Rocket.Chat/issues/164#issuecomment-216991364), I'm creating this issue to trace this more easily.

### PR DESCRIPTION
**Pull request by ubarsaiyan**
@RocketChat/core 

Closes #9799 

When replying to or quoting a message the quoted text appears above and the reply message below it, similar to WhatsApp.
screenshot from 2018-03-05 23-36-15

### CODE REVIEW

**Comment by sampaiodiego** [comment]
based on file changes looks like *ALL* attachments will be above the message, not only replies and quotes, can you confirm that please?

can you also include some screenshots? thx

**Comment by ubarsaiyan** [comment]
@sampaiodiego Yes, all attachments are above messages, though I think it looks better this way.
https://imgur.com/a/oGXIp

**Comment by kaiiiiiiiii** [comment]
@ubarsaiyan I disagree. @sampaiodiego is a 100% right.

And can you please attach the screenshot to your post?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ubarsaiyan** [comment]
@kaiiiiiiiii I'm sorry, it was just my opinion. I'll change it to display only the replies and quotes.

**Comment by ubarsaiyan** [comment]
@sampaiodiego @kaiiiiiiiii I tried uploading images and files and the description comes below the file. This is the expected behaviour right? Check the screenshot.

**Comment by marceloschmidt** [comment]
@ubarsaiyan please review your pull request, it looks like you're trying to merge an outdated fork. You have 160+ commits on this PR. Thanks.

**Comment by ubarsaiyan** [comment]
I'm sorry. I will close this pull request and submit a new one as by mistake I pushed this from the master branch.

**Pull request closed without merging**
