### PR TITLE
Add unicode support for channel name

### PR DESCRIPTION
**Pull request by brylie**

### CODE REVIEW

**Comment by brylie** [comment]
Related issue #640

**Comment by rodrigok** [comment]
@brylie for username or for channel name? And about private groups?

**Comment by geekgonecrazy** [comment]
This for sure looks like for channel name.  We still have the potential issue of the name in the URL.  I know this has been pretty much the only reason we haven't already done this.

**Comment by steedos** [comment]
name in UTF-8 can be encoded for URL:

http://stackoverflow.com/questions/332872/encode-url-in-javascript

发自我的 iPhone

**Comment by brylie** [comment]
Where does the URL component get encoded? We can add the `encodeURIComponent(roomName)` function at that point.

**Comment by brylie** [comment]
I added an encoding step at the top of the createChannel method, so that any subsequent validation would be done against the encoded component:

```
# Encode the name for use in URL
name = encodeURIComponent(name)
```

**Comment by rodrigok** [comment]
I see 2 problems here

1. You are doing this only for channels, if we change the name’s behavior, we need to change for channels and groups (private groups)
2. If you save the name as URL encoded we will need to decode in all places where we show the room name

**Comment by brylie** [comment]
@rodrigok Where should the URL be encoded?

**Comment by rodrigok** [comment]
@brylie where there are links for rooms, like the left sidebar and room mentions.

**Comment by brylie** [comment]
@rodrigok Will you please link me to some of the locations I should edit? I will update the PR ASAP.

**Comment by rodrigok** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/master/client/views/app/sideNav/listChannelsFlex.html#L13
https://github.com/RocketChat/Rocket.Chat/blob/master/client/views/app/sideNav/listPrivateGroupsFlex.html#L13
https://github.com/RocketChat/Rocket.Chat/blob/master/client/views/app/sideNav/chatRoomItem.coffee#L43-L48
https://github.com/RocketChat/Rocket.Chat/blob/master/client/views/admin/rooms/adminRoomInfo.coffee#L14-L19
https://github.com/RocketChat/Rocket.Chat/blob/master/client/views/admin/users/adminUserChannels.coffee#L6-L11
https://github.com/RocketChat/Rocket.Chat/blob/master/client/views/app/privateHistory.coffee#L26-L31

You need to improve the regex of channel mentions
https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-mentions/client.coffee#L34-L45
https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-mentions/server.coffee#L28-L39

And some way to improve the autocomplete for channels
https://github.com/RocketChat/Rocket.Chat/blob/master/client/views/app/messagePopupConfig.coffee#L50-L70
The default regex is here https://github.com/RocketChat/Rocket.Chat/blob/master/client/views/app/messagePopup.coffee#L46-L49

I don't know if i have listed all places here

**Comment by rodrigok** [comment]
As far as i know the `FlowRouter.path` already do the url encode

**Comment by sokolovstas** [comment]
I have tried just remove RegExp checking and all working fine. No need to encode and decode. One problem with renaming room with unicode chars, it doesn't save at all.

**Comment by marceloschmidt** [comment]
Closed by #1145

**Pull request closed without merging**
