### PR TITLE
[WIP] Add sandstorm back to our Circle CI

### PR DESCRIPTION
**Pull request by geekgonecrazy**
We've had some requests to get sandstorm builds back up and going. 

I'm wondering if we should change the build to make use of our bundle instead of building all over again...

If not we should probably try to parallelize the build of sandstorm and regular build

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
I'm just gonna /sub here. I might be able to answer a question or two if a Sandstorm-ish question crops up.

**Comment by urakagi** [comment]
Hi, is the team stuck up here about releasing a new version rocket.chat sandstorm app including #9062?

**Comment by geekgonecrazy** [comment]
@urakagi if you take a look at change log it was removed.  This issue now is making sure it builds properly with the CI and can resume publishing.  It was removed a while ago due to some issues building.  So if you have experience making this work.  We definitely are open to contributions.

The idea behind sandstorm is a really great one.  Unfortunately not had time to really dig deep and get as familiar as I'd like.

**Comment by ocdtrekkie** [comment]
What version of Meteor is Rocket.Chat currently using? That's likely to be one of the blockers here since this is packaged for Sandstorm using vagrant-spk. I can look into figuring out which meteor-spk tool you need and how to get that back into vagrant-spk.

Additionally, the Vagrantfile calls for an old base image that's no longer available. This one's an easy fix, but there's definitely a few changes that will need to happen in your .sandstorm folder before it'll work.

**Comment by geekgonecrazy** [comment]
We're up to latest meteor version I think if not close 

https://github.com/RocketChat/Rocket.Chat/blob/develop/.meteor/release#L1

Meteor 1.6.1.1

**Comment by ocdtrekkie** [comment]
Alright, I'll look into it and get back to this issue on the status of packaging working for Meteor 1.6.1.1.

**Comment by ocdtrekkie** [comment]
Current status: meteor-spk has been updated and confirmed to work with Meteor 1.6.1.1.

Next steps:
- I need to update vagrant-spk's meteor stack to use the new version of meteor-spk.
- I will create a PR to update the /,sandstorm directory of Rocket.Chat to use the updated configurations.
- Then we test whether or not Rocket.Chat builds correctly with it.

**Comment by ocdtrekkie** [comment]
This PR updates vagrant-spk's meteor stack to use the new version of meteor-spk: https://github.com/sandstorm-io/vagrant-spk/pull/231

The next part of this will entail updating Rocket.Chat's /.sandstorm directory with the updated scripts. (Both from this pull request and other changes to the Vagrantfile and global-setup.sh required for it to run correctly.)

**Comment by ocdtrekkie** [comment]
Hmmm, I was hoping to see if any remaining errors cropped up, but that Heroku link does gives an application error at the moment.

**Comment by engelgabriel** [comment]
@peterlee0127 we would love to make our circle ci to update the sandstorm marketplace, can you help?

**Comment by engelgabriel** [comment]
This also helped: https://github.com/RocketChat/Rocket.Chat/pull/11056

**Comment by peterlee0127** [comment]
#11056  will help current develop branch to build Rocket.Chat for Sandstorm normally.
With the vagrant-spk, Vagrant, VirtualBox, you can
$ sudo vagrant-spk vm up
$ sudo vagrant-spk dev
If the build successful, you can open browser to localhost:6080.

What's the current status of CI build ?

**Comment by GustavoMarcante** [comment]
Any news?
Sandstorm site shows "version 0.53.0-develop, last updated 2017 Feb 21".

**Comment by peterlee0127** [comment]
@GustavoMarcante  
Still need time to fix.
If you need newer version. You can try this build.
1: Update 0.61.0-develop.
2: Fix mobile app push notification.
https://github.com/peterlee0127/RocketChat-for-Sandstorm

**Comment by peterlee0127** [comment]
@ocdtrekkie 
Please try it.
https://github.com/peterlee0127/Rocket.Chat/commit/523f983a5325cd8aa0b2689a6e3be3ca660a4948
https://github.com/peterlee0127/Rocket.Chat/commits/sandstorm_0.59.3
You can find patch for it.  Sorry it is so much commits.
About Powerbox in Sandstorm. https://docs.sandstorm.io/en/latest/developing/powerbox/

But I think adding powerbox to Rocket.Chat may let the code become more complex.
Like my patch for fix push notifications. It will need a UI for user 'Ask User is agree to let grain to send to https://gateway.rocket.chat'
screen shot 2018-07-06 at 10 56 07 pm
Then, it generate the token, these token can let the outing network can pass to Rocket.Chat's server.
It means every out going traffic will need user's permission. Like a external bot, services will need a different token to pass Sandstorm.
I think it's still difficult to do it perfectly. If Sandstorm can open a white list for Rocket.Chat, it should be easily and possible solution.

**Comment by raarts** [comment]
Hi. I'm following this issue, and want to implement Rocket.Chat within Sandstorm. It's not clear to me what exactly is remaining for this issue to be resolved, can anybody summarize for me? Am I right in assuming sandstorm needs to be changed for allowing notifications?

**Comment by rjBadger** [comment]
Is there still progress being made on this? Is there specific work that still needs to be done. I really would like to see an up to date rocket.chat on sandstorm.

**Comment by geekgonecrazy** [comment]
I'm going to go ahead and close this.  If someone else wants to pick it up feel free.

**Comment by rjBadger** [comment]
Very disappointing, but i guess expected.

**Comment by ocdtrekkie** [comment]
FWIW, a PR with nobody taking the reins isn’t getting us anywhere. Hopefully with Sandstorm development picking up again someone will be interested in updating the Sandstorm package again someday soon.

**Comment by geekgonecrazy** [comment]
Yeah as much as i'd love to finish this one out my self..  I don't personally run sandstorm, i've only played with it a few times in a VM.  I love the concept, if development takes off again and there is enough demand for I will gladly help invest time in it.

For that matter if anyone else wants to take point on this I will gladly help them out.  [@aaron.ogle](https://open.rocket.chat/direct/aaron.ogle) on open.rocket.chat.   I just can't really drive it forward my self right now

**Comment by peterlee0127** [comment]
Sorry for that. Because my organization already migrate sandstorm version to standalone Rocket.Chat.

**Pull request closed without merging**
