### PR TITLE
[NEW] API for anonymous users. Registering and posting message to channel

### PR DESCRIPTION
**Pull request by knrt10**
To use this API, new method of auth has been  created for anonymous users.

- Enable `Allow Anonymous Registering of accounts` inside `Administration -> Accounts`
- Register new anonymous user  using `curl -X POST http://localhost:3000/api/v1/users.registerAnonymous`
- Copy `username` and `hashedToken` from above response
- Now you can use this to post message anonymously
```bash
curl -H "Content-type:application/json" http://localhost:3000/api/v1/chat.postMessageAnonymous \
-d '{ "channel": "#general", "text": "Huee This is a test!aaaa", "username": "your username", "token": "hashedToken" }'
```

Please test it, once approved, will write tests for it.

### CODE REVIEW

**Comment by Hudell** [comment]
Can you give us an example of a situation where this feature would be needed?

**Comment by acerbisgianluca** [comment]
> Can you give us an example of a situation where this feature would be needed?

Hi, I'm from the Alexa Skill Team and we are planning to add anonymous usage, so we asked @knrt10 to add needed API to RC core.
Every server has its own Skill, so now if you enable its Skill on your Alexa account you will be asked to login with your server credentials otherwise you cannot use it. If you merge this API, we will be able to enable Skill to non-registered user.

**Comment by Hudell** [comment]
Thanks for clarifying!
Would this API be registering multiple anonymous users or would that be done only once and the user reused?

I'm wondering if we can skip the registration and simply send the message as rocket.cat (the default bot) with an alias for the username.

**Comment by knrt10** [comment]
@Hudell This API will only register anonymous account once and then that user can be used again and again.

> I'm wondering if we can skip the registration and simply send the message as rocket.cat (the default bot) with an alias for the username.

I like this solution, can you please give an example how anonymous users will be able to send messsage as rc bot? It would help me to update the PR. Thanks

**Comment by geekgonecrazy** [comment]
So regarding the api specifically.  I have no problem.  I think if we are going to allow anonymous usage on web app we should have an api so that it can be used by other clients as well.

But with regard to needing to turn this on to register a skill... I think this will be a very bad design decision.  

I can tell you if the choice came down to turn on anonymous access to my server or chose another bot framework or platform....... I will choose something else.  99.9% of our regular-non-anonymous using users will be the exact same way.

To me the better solution is a way to be able to easily generate a bot token that will let the rocket.cat user be used for functionality like this.

I think there is a PR open for a bot dashboard where they were trying to do some interesting stuff like this.  Please feel free to hit me up on open server if you want to bounce ideas.  There has surely got to be a better way for the alexa skill.


But to me the Endpoint should be very valid if we want to keep allowing communities to choose anonymous registration.  Which to my knowledge we do.

**Comment by acerbisgianluca** [comment]
Didn't know about that. I thought that admins could choose to enable anonymous usage. We should definitely add that option.

**Comment by acerbisgianluca** [comment]
> But to me the Endpoint should be very valid if we want to keep allowing communities to choose anonymous registration. Which to my knowledge we do.
This has already been implemented [here](https://github.com/RocketChat/Rocket.Chat/pull/14424/files#diff-754e1ad21750596a396930b3c235f364R241).

**Comment by geekgonecrazy** [comment]
> This has already been implemented here.

Exactly.  Thats what i'm saying.  This PR is great.  But the application you intend to use it for I do not agree with.  I think it will end in the alexa skill not being able to be used by 95% of Rocket.Chat users if not more that will refuse to turn on anonymous registration.

**Comment by acerbisgianluca** [comment]
> Exactly. Thats what i'm saying. This PR is great and adds value.

Sorry, I misunderstood your response

**Comment by Sing-Li** [comment]
This capability will DRIVE adoption of Rocket.Chat and not the other way around.

Essentially, the  Alexa (100 million+ users)  skill developers will create and operate a brand new Rocket.Chat server in order to offer these "dynamic flash briefings" to their users. 

There will be no case where the anonymous (or not decision) needs to be made. 

In addition, the only anonymous privilege this needs is Anonymous READ.  And all public channels are by definition public - and should be anonymous readable anyways.

Please review and merge asap.

**Comment by geekgonecrazy** [comment]
I have no problem with what the Pr brings.

I guess I don’t understand how the Alexa skill relates only to developers and not end users.  Just because channels are public doesn’t mean I want someone outside of my server to be able to just read. 

Seems like if the issue is registering.. something like how zapier hooks up would make more sense.  That way not exposing messages directly to the world but instead I as admin still get to maintain control.

But if you guys are sure go for it :)

**Comment by PrajvalRaval** [comment]
Hi @geekgonecrazy, Prajval here from Alexa team. We decided that we also do not want anonymous registration and message post as it can be a major security concern. So we made a decided to make a new endpoint that just gives access to anonymous message read. Please review PR here => https://github.com/RocketChat/Rocket.Chat/pull/14714

**Pull request closed without merging**
