### PR TITLE
[NEW] The messageActions menu now opens on right click

### PR DESCRIPTION
**Pull request by fliptrail**
Partial improvement to #10955

The messageActions__menu would now open when the user right clicks on the message. It would spawn at the cursor location. The default browser behaviour has been removed.
Peek 2019-03-20 22-37

### CODE REVIEW

**Comment by kaiiiiiiiii** [comment]
How does it behave if I only want to copy a small part of a message? “Copy” in the action menu copies the whole message.

**Comment by fliptrail** [comment]
@kaiiiiiiiii It would copy the whole message as before.

**Comment by kaiiiiiiiii** [comment]
That’s bad. There should be an action that only copies the selected text, otherwise our developers can’t copy single lines of code from a multi line message. 

And still, please as an optional feature :)

**Comment by fliptrail** [comment]
They would still be able to select parts of a message using left click and then copy it using Ctrl+c. This menu drops down using the right click. I don't see any changes to user experience.

**Comment by kaiiiiiiiii** [comment]
Not everyone is using shortcuts, I bet most of the users don’t. 

You may need to change your view from a tech guy to a normal office employee, if you don’t see the change in user experience or the issue itself.

Don’t take this as an offense, I really appreciate your work, but there needs more to be done.

**Comment by fliptrail** [comment]
Of course, I won't take offense. Receiving comments are a constructive part of it.
Can you tell how do you guys do it now?

**Comment by fliptrail** [comment]
Maybe you are actually right...It might not be good this way. I would try to look around for a workflow which makes sure that default browser behaviour is used when right clicking on text.

**Comment by engelgabriel** [comment]
I think that if we do the following:

1. Add a "Copy selection" option to the menu
2. Make the right-click-menu  optional for each user, configurable on preferences
3. Create a server config for the default behavior

This could be accepted by the community.

**Comment by engelgabriel** [comment]
Or maybe just try to check if there is any text currently selected, and if there is, use the browser contextual bar, if not, show the message actions menu. This would be even better.

**Comment by engelgabriel** [comment]
> * Make the right-click-menu  optional for each user, configurable on preferences
> * Create a server config for the default behavior

@fliptrail ask @ggazzo about reference code for this, we have done it many times.

**Comment by fliptrail** [comment]
@ggazzo Please help me with this.

> > * Make the right-click-menu  optional for each user, configurable on preferences
> > * Create a server config for the default behavior
> 
> @fliptrail ask @ggazzo about reference code for this, we have done it many times.

**Comment by fliptrail** [comment]
@engelgabriel Which should be implemented?
1. 

> I think that if we do the following:
> 
> 1. Add a "Copy selection" option to the menu
> 2. Make the right-click-menu  optional for each user, configurable on preferences
> 3. Create a server config for the default behavior
> 
> This could be accepted by the community.

**OR**
2.

> Or maybe just try to check if there is any text currently selected, and if there is, use the browser contextual bar, if not, show the message actions menu. This would be even better.

**Comment by fliptrail** [comment]
I found out another error in this approach, that the user would want to open a link in a new tab by using right click.
I am thinking that over complete text, only browser default context menu should spawn.

**Comment by fliptrail** [comment]
@engelgabriel Please review this. 
Copy Selected option has been added. If no text is selected then error message "No text selected" is displayed.
Plus, now, the default browser context menu is used for images, anchors and extra divs, so that options like "Open image in new tab" , "open link in new tab" are still available to user.

**Comment by ashwaniYDV** [comment]
I am working on it

**Comment by ashwaniYDV** [comment]
@

> Or maybe just try to check if there is any text currently selected, and if there is, use the browser contextual bar, if not, show the message actions menu. This would be even better.

@ engelgabriel I have made the pull request. This is the best option I like which you suggested for context menu.
https://github.com/RocketChat/Rocket.Chat/pull/16305

**Comment by rodrigok** [comment]
We apologize for not getting a review on this sooner.

I'll close this in favor of https://github.com/RocketChat/Rocket.Chat/pull/16305

Thanks for your contribution

**Pull request closed without merging**
