### PR TITLE
Add support for Google Analytics

### LINKED ISSUE #5955: Add setting for Google Analytics
Let's have a setting for admins to add Google Analytics ID, as not everyone has Google Tag Manager.

Also, let's move the GTM script to the index.html injection, so it is already available before users finish loading the JS.

### PR DESCRIPTION
**Pull request by alexbrazier**
@RocketChat/core 

Closes #5955 

Add support for Google Analytics

## Todo
- [x] Database migration for Piwik

image

### CODE REVIEW

**Comment by Molle500** [comment]
Will this fix the problem that is today? it only detecs a page view if you reload a page, not if u jump between different channels.

**Comment by alexbrazier** [comment]
@Molle500 Is that an issue you have using the current Piwik analytics?
I have tested page views with Google Analytics, and they are working, but I will check if there is an issue with Piwik.

**Comment by Molle500** [comment]
No i have never used piwik. I use google analytics with google tag manager. 

I found a isse here on github yesterday with other ppl having this problem but cant find it right now

**Comment by alexbrazier** [comment]
@Molle500 Page tracking will work with this implementation, as it manually records it when you select a channel.

**Pull request merged**
