### PR TITLE
Allow rename of room when clicking out of room name edit input box

### PR DESCRIPTION
**Pull request by owenconti**

### CODE REVIEW

**Comment by davidmalcoci** [comment]
Check the "Main room" - later grant ability to modify even the "General" area.

**Comment by owenconti** [comment]
Hi @davidmalcoci - is this something you want me to add to this pull request? Or are you just noting it for later?

**Comment by davidmalcoci** [comment]
Hey I have just entered the testing team :) So just pointing from a perspective the things that should be done for the future. Consider the fact that there is going to be a lot of foreign people adopting it. 

Date: Sun, 31 May 2015 13:39:26 -0700

**Comment by rodrigok** [comment]
@sampaiodiego Can you review this PR?

**Comment by sampaiodiego** [comment]
hey @owenconti, thanks for the PR.

But, I don't think this is a good behavior. The current behavior is the one adopted by Trello, for example.

But we can discuss here what is the most expected behavior for this =)

**Comment by engelgabriel** [comment]
I like the idea of moving the functionality to method, so it can be called elsewhere. Just not sure about the expected behaviour. Maybe we can turn this into an "advanced" configuration at some point. But I do like the code moving to a method.

**Comment by owenconti** [comment]
Okay, no problem. I assumed it was a bug when I went to edit a room name but it didn't save because I had blurred via click instead of the Enter key.

**Comment by owenconti** [comment]
Side question: If I find something that I think may be a bug (like in this case), what is the best way to resolve it?

Open an issue ticket and offer to fix it, if it is confirmed to be a bug?

**Comment by engelgabriel** [comment]
Yes, it would save you the time, as in some cases, even when it is a bug, we may have been working on it already. Nevertheless, I really appreciated you help! And like I said, we will make this behaviour optional.

**Comment by owenconti** [comment]
Sounds good. Thanks!

**Pull request merged**
