### PR TITLE
[fix] Disable eslint import/no-unresolved

### PR DESCRIPTION
**Pull request by im-adithya**
## Proposed changes (including videos or screenshots)
This was causing build failures so I have disabled eslint.

### CODE REVIEW

**Comment by im-adithya** [comment]
@MartinSchoeler Please review this :)

**Comment by yash-rajpal** [comment]
@im-adithya I am not sure, but I think #21831 solves the lint issues on CI checks.

**Comment by im-adithya** [comment]
No @yash-rajpal, this doesn't apply to CI checks but covers it (as it includes linting tests) and this PR disables eslint for the specific file.

**Comment by yash-rajpal** [comment]
Yes, was just confirming it.

Also if you would do npm install in EE folder too, I don't think lint would give import errors on these files.

EE folder also now requires node modules.

**Comment by KevLehman** [comment]
As @yash-rajpal mentioned, in local you should run `npm install` from the ee folder. Disabling eslint is not something we should do 😬 

I'm closing this since it's not needed.

**Pull request closed without merging**
