### PR TITLE
[FIX] Message search breaking URL, usertags and emojis

### PR DESCRIPTION
**Pull request by TBG-FR**
**Clean version of #18913** (still worth mentionning it for the discussions in comments about "missing" search results")

## Proposed changes

It has been reported that when searching for a message, the results were displaying with bugs : URLs where broken, emojis title too, ~~and some results are missing~~. This PR aims to fix these issues.

Elements resolved:
- [X] URLs are broken by search `<mark>`
- [X] Emojis are broken by search `<mark>`
- [X] `mailto:` links  are broken by search `<mark>`
- ~~[ ] Some search results are missing (is it really a bug ? See comment on #18913 )~~

## Issue(s)

#18770 => reports that highlighted links, emojis (and mentions ?) are broken, as well as missing results
#18696 => reports that highlighted links are broken
#18456 => report that highlighted links are broken

## How to test or reproduce

Go into a channel, and post these messages :
> smile
> :smile:
> smile.com
> smile-not.com
> smilenot.com

Then search for the word `smile` in that channel. You'll notice that: 
- you can't click on links anymore (they're broken by `<mark>` tags)
- if you hover on the smile emoji, its title is broken by `<mark>` tags too
- the `smilenot.com` link isn't part of the results

## Screenshots
See issues for screenshots

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [X] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

#### Broken links/emojis
I fixed the `<mark>` tag issue by doing three `replace` steps
1. Using a (bit tricky) REGEX, we find every occurence of `searchedText` which is inside a `title="..."` or `href="..."` and replace `searchedText` in them by an unique UUID
2. Using the previous line of code, we find every occurence of `searchedText` left and we mark it
3. We find every occurence of the UUID and replace them with `searchedText`

I did this because I couldn't make a better REGEX, which would exclude `1` and find only `2`. If you are able to do it, or if you see a better solution, feel free to comment ! Also, you may wonder "Why an UUID ?" : I used it because I thought that any arbitrary set of characters could end up being part of the initial search, and I think we're safe about that with a V4 UUID.

~~Considering the other issue, which we'll call "missing results", I searched in the whole project and found that it uses a **Meteor function `messageSearch`**. So I suspect Meteor for being responsible of that bug, but we need more investigation to be sure.~~

#### Related PR
Results highlighting has been implemented in #16166

### CODE REVIEW

**Comment by TBG-FR** [comment]
For reference : PR #23309 / Issue #19369 / Issue #23285

**Comment by TBG-FR** [comment]
I just updated the PR to rebase on `origin/develop`, and CLA is signed since Dec 2021. 

As stated [here](https://github.com/RocketChat/Rocket.Chat/issues/22877#issuecomment-957752558), this PR will close 6 issues and 3 PRs :

> We are dealing with that issue for such a long time now. There are several issues and PRs over the past year:
> 
> * [Search Messages - links containing the exact search term become corrupted #18456](https://github.com/RocketChat/Rocket.Chat/issues/18456)
> * [Search mark breaks links #18696](https://github.com/RocketChat/Rocket.Chat/issues/18696)
> * [URL link in search broken #18770](https://github.com/RocketChat/Rocket.Chat/issues/18770)
> * [mark-tags affect internet addresses in search #21206](https://github.com/RocketChat/Rocket.Chat/issues/21206)
> * [URL href values in search results are rendered with <mark> tag #22877](https://github.com/RocketChat/Rocket.Chat/issues/22877)
> * [Broken links in search when search term is part of the URL #23285](https://github.com/RocketChat/Rocket.Chat/issues/23285)
> 
> PR:
> 
> * [[FIX] Message search breaking URL and emojis, and missing results [WIP] #18913](https://github.com/RocketChat/Rocket.Chat/pull/18913)
> * [[FIX] Message search breaking URL, usertags and emojis #20878](https://github.com/RocketChat/Rocket.Chat/pull/20878)
> * [[FIX]: Broken links in search #23309](https://github.com/RocketChat/Rocket.Chat/pull/23309)

@debdutdeb would it be possible for you (or someone else) to review that PR ? We discussed it with @sampaiodiego in #18913 (Sep 2020 - Feb 2021), I since cleaned the PR, and everything looks good to go !

Hope we'll finally get rid of this issue, a long await one ! 💪

**Comment by TBG-FR** [comment]
@debdutdeb @dudanogueira @sampaiodiego Could you guys review (and accept if it looks good to you) this PR ? There's a lot of issues (and now, many PRs) aiming to fix that one, showing how disturbing it is for users to have broken links (regular urls and `mailto`), emojis and user tags

**Review by sampaiodiego — CHANGES_REQUESTED** [review]
hey @TBG-FR thx for the deep investigation on this issue..

I was wondering if we could still use a single regex to do the replace.. I give it a try a come up with this:

```js
msg = msg.replace(new RegExp(`(${searchedText})(?![^<]*>)`, 'gi'), (str) => `<mark>${str}</mark>`);
```

a tested very quick and got good results.. can you pls try it on your end to see if it works as expected as well?

**Comment by TBG-FR** [comment]
> hey @TBG-FR thx for the deep investigation on this issue..
> 
> I was wondering if we could still use a single regex to do the replace.. I give it a try a come up with this:
> 
> ```js
> msg = msg.replace(new RegExp(`(${searchedText})(?![^<]*>)`, 'gi'), (str) => `<mark>${str}</mark>`);
> ```
> 
> a tested very quick and got good results.. can you pls try it on your end to see if it works as expected as well?

Thanks for your message, and for that improvement ! I finally tested it, and:
- ✅ URIs aren't broken anymore (`href`)
- ✅ Mails aren't broken anymore (`mailto:`)
- ✅ Emojis titles are fixed too !

Good catch with that solution that stays simple 😄 
Should I update this PR, or do you want to simply push a commit yourself ?

**Comment by sampaiodiego** [comment]
that's great to know 😄 

I'd be happy to accept that as a contribution.. so feel free to update this PR with it :)

**Comment by TBG-FR** [comment]
PR updated ;) I also checked tags (`@smile`) and their titles aren't broken anymore 🥳

**Pull request merged**
