### PR TITLE
[NEW] Option to allow to signup as anonymous

### LINKED ISSUE #604: Allow anonymous use of the chat [$250]
So currently, Rocket.Chat is a very much a Slack clone. But my main issue with Slack is that it is not open enough. So I would like an option to make Rocket.Chat more open. What I mean by that is that is that users can come and start reading what is happening on public channels without registration. So when a not-logged in user would open root address, they would get to the normal main screen, with all channels listed and so on. When they would open a channel, they could see what is happening there, but the message input box would be grayed out and a message to register/login to post would be there.
## <bountysource-plugin>

There is a **[$250 open bounty](https://www.bountysource.com/issues/26280752-allow-anonymous-use-of-the-chat?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

Closes #5647
Closes #604

- Rename setting `Accounts_AllowAnonymousAccess` to `Accounts_AllowAnonymousRead`
- Add setting `Accounts_AllowAnonymousWrite` that depends on `Accounts_AllowAnonymousRead`
- Add a new button to `talk as anonymous` that creates a new account without email and request a username
- Add a setting `Accounts_DefaultUsernamePrefixSuggestion` to be able to change the default prefix for username suggestions
- Add a new role `anonymous` with a few permissions (it's possible to change it at admin area)
- Create the anonymous user with role `anonymous`
- Change the role to `user` when user adds and verifies the email adding more permissions

captura de tela 2017-04-25 as 15 42 57
captura de tela 2017-04-25 as 15 43 02
captura de tela 2017-04-25 as 15 43 09

### CODE REVIEW

**Comment by sampaiodiego** [comment]
I'm getting this when showing real names enabled:
image

**Comment by rodrigok** [comment]
@sampaiodiego Can you review it again? You'll need to rerun the last migration cuz I did change it.

**Comment by sampaiodiego** [comment]
I still have found some issues but I dont think they block merging the PR:

- channels created after anonymous user loads the page are not searchable
- after anonymous user joins a channel it doesn't see topic nor description changes until a refresh:
image

**Comment by engelgabriel** [comment]
Created:
https://github.com/RocketChat/Rocket.Chat/issues/6817
https://github.com/RocketChat/Rocket.Chat/issues/6818

**Comment by sampaiodiego** [comment]
@ruKurz you can already do that disabling pre-registration form:

image

**Comment by ruKurz** [comment]
know your product ;-) Thanks for your quick reply!

**Pull request merged**
