### PR TITLE
Webrtc

### PR DESCRIPTION
**Pull request by rodrigok**
- [x] Direct call
- [x] Group call
- [x] Show all remote videos
- [x] Close connections on remote close
- [x] Fix mute in Firefox
- [x] Allow select the main video
- [x] Join an existent call
- [x] Option active/deative camera
- [x] Option to mute
- [x] Audio call
- [x] Join calls with audio only
- [x] Show more information about the call before accept
- [x] Redirect to correct room on accept
- [x] Auto accept call
- [x] Call as monitor (without local video and audio, only in direct rooms)
- [x] Overlay
- [x] Screen sharing
- [x] Option to disable in general settings

## Start video or audio calls in direct or group rooms
captura de tela 2015-10-03 as 15 12 21

## Join calls in progress
captura de tela 2015-10-03 as 15 14 00

## Accept or reject audio calls
captura de tela 2015-10-03 as 15 13 47

## Accept or reject video calls
captura de tela 2015-10-03 as 15 12 56

## Accept or reject monitoring calls
captura de tela 2015-10-01 as 14 56 27

## See all videos and click to show one bigger
captura de tela 2015-10-03 as 15 15 14

## Share your screen
captura de tela 2015-10-03 as 15 15 47

## Expand the UI
captura de tela 2015-10-03 as 15 16 06
captura de tela 2015-10-03 as 15 16 01

### CODE REVIEW

**Comment by gmsecrieru** [comment]
:+1: :+1: :+1:

**Comment by geekgonecrazy** [comment]
Wow!  Amazing work!!

**Comment by gmsecrieru** [comment]
Should close #418

**Comment by mhurwi** [comment]
Wow.  Very awesome and impressive!  :bow:

**Pull request merged**
