### PR TITLE
CAS 2.0 Support

### LINKED ISSUE #2325: CAS Plugin: Upgrade cas libs to support CAS 2.0 protocol
The current CAS plugin supports only CAS 1.0 which is sufficient to login with a username.

The CAS 2.0 protocol transports user attributes such as Common Name, Email, and even custom attributes. The minimal implementation for CAS 2.0 rocketchat plugin would allow defining a map of attributes, which are parsed from the CAS response and will be mapped towards what RC user attributes:
- cas_response.email -> rc.user.emails
- cas_response.fullname -> rc.user.name/profile

### PR DESCRIPTION
**Pull request by corecache**
@RocketChat/core 

Closes #2325 #2326 #2963 

**CAS 2.0 Support**
The CAS 2.0 protocol allows that the CAS SSO server transmits user attributes towards a CAS client, the RocketChat instance. RocketChat user attributes such as name, email and rooms (to join on default) can be sourced/generated from the external attributes. This is done by defining a JSON attribute map where the values may container external attribute placeholders which will be interpolated and assigned to internal user attributes.

Adds the following Settings to the CAS configuration:

**Always sync User data**
Always synchronize external CAS User data into available attributes upon login. Note: Attributes are always synced upon account creation anyway.)

**Attribute map**
Use this JSON input to build internal attributes (key) from external attributes (value). External attribute names enclosed with '%' will interpolated in value strings.
Example, `{"email":"%email%", "name":"%firstname%, %lastname%"}`

The attribute map is always interpolated. In CAS 1.0 only the `username` attribute is available. Available internal attributes are: username, name, email, rooms; rooms is a comma separated list of rooms to join upon user creation e.g: {"rooms": "%team%,%department%"} would join CAS users on creation to their team and department channel.

### CODE REVIEW

**Comment by madhusudan** [comment]
Custom attributes not working!.
I tried with  `{"mail":"%username%@example.com", "name":"%username%"}`  with both CAS 1 and 2, but only username is coming correct but the email field is **blank**!!
I am using 
> Rocket chat version:0.49.3 (without docker)
Jasig Central Authentication Service 4.0.0

Any guess how to fix..?

**Comment by corecache** [comment]
Hey there,

Only the following internal attributes are beeing sourced from external attributes:
- email
- name
- username
- rooms

You have however tried sourcing "mail" instead of "email" - try the following syntax:
`{"email":"%username%@example.com", "name":"%username%"}`

Keep in mind that CAS attributes do only work with a CAS 2.0 enabled server.

**Comment by madhusudan** [comment]
@corecache 
Thanks, its working now.. :-) :+1:

**Comment by corecache** [comment]
You are welcome, just please be cautios about your conclusions next time, Thanks! :)

> Custom attributes not working!.

**Pull request merged**
