### PR TITLE
[NEW] - Add gitpod config

### PR DESCRIPTION
**Pull request by Rodriq**
this commit adds support for Gitpod.io, a free automated
dev environment that makes contributing and generally working on GitHub
projects much easier. It allows anyone to start a ready-to-code dev
environment for any branch, issue and pull request with a single click.

In relation with #16087

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Thanks! @Rodriq for making a PR for this. Your config does not seem to be working Pease use this instead https://github.com/corneliusludmann/Rocket.Chat/commit/8577c92de8dec1251ece515f7a02d0bcadfcfebf

**Comment by nisarhassan12** [comment]
Once this Pr is merged then for anyone with a single click Gitpod will launch a workspace and automatically:

- clone the Rocket.Chat repo.
- install meteor.
- run `meteor npm install`.
- run `meteor npm start`.

You can give it a try via this link:

https://gitpod.io/#https://github.com/corneliusludmann/Rocket.Chat/tree/corneliusludmann/gitpod-setup

This is how it looks:

image

 A lot of popular OSS projects out there are already using it simplify contributors onboarding some of them are:

- https://github.com/freeCodeCamp/freeCodeCamp
- https://github.com/facebook/docusaurus
- https://github.com/mozilla/pdf.js/

You can find a brief list of them at https://contribute.dev

image

**Comment by nisarhassan12** [comment]
@Rodriq Thanks for making a Pr for this. Your config does not seem to be working please use this instead: https://github.com/corneliusludmann/Rocket.Chat/commit/8577c92de8dec1251ece515f7a02d0bcadfcfebf

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 

Closing this PR because it's duplicated now and it has been fixed in another one. #30921

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Pull request closed without merging**
