### PR TITLE
[FIX] Deactivating user breaks if user is the only room owner

### LINKED ISSUE #24934: Deactivating only owners breaks the app
### Description:
When a user is the only owner of a channel, and admin chooses to deactivate that specific user in the Administration, then the whole app breaks with an error from server i.e,
```
{
  "success": false,
  "error": "[user-last-owner]",
  "errorType": "user-last-owner",
  "details": "[object Object]"
}
```

### Steps to reproduce:

1. If owner is the last person, and tries to leave the channel by `Leave` option in the sidebar options, it shows us to set an owner before leaving.
2. But when an admin for example, goes to `Admin > Users > Edit User > Deactivate` (to that specific user who is the only owner of the channel)
3. it shows error

### Expected behavior:
Should properly handle this scenario

### Actual behavior:
Breaks the app

https://user-images.githubusercontent.com/73601258/160001768-15352249-4d87-414d-a3e9-89c9cd3d90a1.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 4.6.0-develop
- Operating System: Ubuntu 20.04
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 14.18.3-x64
- MongoDB Version:4.4.4

### Client Setup Information

- Desktop App or Browser Version: Brave
- Operating System: Ubuntu 20.04

### Additional context
Thanks @dudanogueira ! :)

### LINKED ISSUE #25155: [Bug] Admin UI web page crashed when deactivating user who is owner of at least one private group
### Description:

Admin UI web page crashed when deactivating user who is owner of at least one chat.
If you deactivations user that not an owner of any chat - it's OK.

### Steps to reproduce:

1. Create a new user, called UserA for example
2. Login as UserA and create private group chat
3. Login as Administrator in Admin UI - Users try to Deactivate UserA
4. App crashes

### Expected behavior:

Admin UI not crashed on deactivating any users

### Actual behavior:

deactivate-owner
image

### Server Setup Information:

- Version of Rocket.Chat Server: 4.6.1
- Operating System: Centos7
- Deployment Method: docker
- Number of Running Instances: 12
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.18.3
- MongoDB Version: 4.4.8

### Client Setup Information

- Desktop App or Browser Version: Chrome 100
- Operating System: Windows 10

### Additional context

If you deactivations user that not an owner of any chat - it's OK.
So the problem is in changing owner in chat to another user

### Relevant logs:

```
POST https://rc.company.com/api/v1/users.setActiveStatus 400
send @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1053
ajax @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1053
d @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1493
_jqueryCall @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1493
a._jqueryCall @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1495
await in a._jqueryCall (async)
post @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1493
post @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1493
callEndpoint @ /client/providers/ServerProvider.tsx:1
(anonymous) @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1495
eval @ /client/views/admin/users/UserInfoActions.js:1
eval @ /client/views/admin/users/UserInfoActions.js:1
oc @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:5
(anonymous) @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:5
onMouseDown @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:5
Ke @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
tr @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
nr @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
Zn @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
Xn @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
(anonymous) @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
He @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
We @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
co @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
pt @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
dt @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
t.unstable_runWithPriority @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1122
_c @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
Le @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
lt @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104 TypeError: Cannot read properties of undefined (reading 'length')
    at r (/client/components/ConfirmOwnerChangeWarningModal.tsx:1:415)
    at Ma (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:59696)
    at Rs (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:111726)
    at nf (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:98840)
    at rf (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:98768)
    at ef (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:98631)
    at Gs (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:95485)
    at 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:45604
    at t.unstable_runWithPriority (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1122:3778)
    at _c (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:45381)
Fi @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
Ni.t.callback @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
Lc @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
$i @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
af @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
t.unstable_runWithPriority @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1122
_c @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
cf @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
Gs @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
(anonymous) @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
t.unstable_runWithPriority @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1122
_c @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
vc @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
Ac @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
Ls @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
ti @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
eval @ /client/views/admin/users/UserInfoActions.js:1
await in eval (async)
oc @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:5
(anonymous) @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:5
onMouseDown @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:5
Ke @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
tr @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
nr @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
Zn @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
Xn @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
(anonymous) @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
He @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
We @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
co @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
pt @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
dt @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
t.unstable_runWithPriority @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1122
_c @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
Le @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
lt @ 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104
/client/components/ConfirmOwnerChangeWarningModal.tsx:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at r (/client/components/ConfirmOwnerChangeWarningModal.tsx:1:415)
    at Ma (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:59696)
    at Rs (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:111726)
    at nf (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:98840)
    at rf (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:98768)
    at ef (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:98631)
    at Gs (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:95485)
    at 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:45604
    at t.unstable_runWithPriority (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1122:3778)
    at _c (1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1104:45381)

```

### PR DESCRIPTION
**Pull request by sidmohanty11**
When we send details as `String(rooms)` it returns us a string =>  "[object Object]" so we cannot destructure out `shouldChangeOwner, shouldBeRemoved` which breaks the whole app.

## Before

https://user-images.githubusercontent.com/73601258/160000871-cfc2f2a5-2a59-4d27-8049-7754d003dd48.mp4

## After
https://user-images.githubusercontent.com/73601258/159998287-681ab475-ff33-4282-82ff-db751c59a392.mp4

## Issue(s)

Fixes #24934
Fixes #25155

### CODE REVIEW

**Review by debdutdeb — APPROVED** [review]

**Comment by debdutdeb** [comment]
@sidmohanty11 please resolve the conflicts ASAP :) Thanks!

**Comment by sidmohanty11** [comment]
yup on it @debdutdeb

**Review by debdutdeb — APPROVED** [review]

**Comment by debdutdeb** [comment]
Btw @sidmohanty11  - very good job 👏

**Review by pierre-lehnen-rc — APPROVED** [review]

**Comment by nishant23122000** [comment]
Any reason why Build and Test falling...?

**Comment by debdutdeb** [comment]
This should fix that https://github.com/RocketChat/Rocket.Chat/pull/25168

**Comment by nishant23122000** [comment]
okay Thanks

**Pull request merged**
