### PR TITLE
Improment/integrations

### PR DESCRIPTION
**Pull request by rodrigok**
* Support Incoming WebHooks
* Support Slack API format (https://api.slack.com/docs/attachments)
* Render Attachments
* Support Slack link format `<http://rocket.chat|Rocket Chat>`

captura de tela 2015-12-09 as 18 00 18
captura de tela 2015-12-09 as 18 00 13
captura de tela 2015-12-09 as 18 00 06
captura de tela 2015-12-09 as 17 59 53

captura de tela 2015-12-09 as 17 57 11
captura de tela 2015-12-09 as 17 56 18
captura de tela 2015-12-09 as 17 55 16

### CODE REVIEW

**Comment by graywolf336** [comment]
I think this pull request broke previews for links...

**Comment by rodrigok** [comment]
@graywolf336 yes, but is fixed now, thanks

**Comment by vetash** [comment]
emoji does not work in attachmens. :disappointed:

**Comment by gustavkarlsson** [comment]
Sorry to ask this, but how complete is the compatibility? I could not find a complete specification of the rocketchat incoming or outgoing webhook formats anywhere. Is it documented anywhere? Are there any inconsistencies? Is there any point at all writing a rocketchat integration if a slack-integration already exists?

**Pull request merged**
