### PR TITLE
[FIX] WebRTC echo while talking

### LINKED ISSUE #15018: WebRTC echo while talking
### Description:
When make audio call via webrtc on desktop client there are some echo on both side

### Steps to reproduce:

1. Login to RC
2. Choose buddy to  make audiocall
3. Hear you-self voice

### Expected behavior:

We do not hear any echo as as-self voice

### Actual behavior:

we hear selfs echo 

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Centos 7
- Deployment Method: docker
- Number of Running Instances:  3
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6

### PR DESCRIPTION
**Pull request by ndroo**
Closes #15018

### CODE REVIEW

**Comment by engelgabriel** [comment]
@ndroo can you please point the PT to our `develop` branch instead of `master`?

**Comment by rodrigok** [comment]
@ndroo can you fix the conflicts? I changed the base branch from master to develop

**Comment by rodrigok** [comment]
@ndroo I reverted the base branch, please rebase your work base on develop branch, otherwise, it will show all the diff we have on master here

**Comment by ndroo** [comment]
Update branch, resolved merges. Let me know if you're happy with this!

**Comment by engelgabriel** [comment]
@ndroo 

I am so sorry for asking this, I don't want to be annoying but the best way for us to merge your PR without having to deal with all these conflicts on unrelated files would be if you can please fork our current develop branch and make the 2 line changes again on a new PR.

I know it is a lot of work for just a small fix, but we need to keep the changelog clean and I really want to merge this PR ASAP to give you the credit.

Can you please do that?

Cheers,

Gab

**Comment by gabriellsh** [comment]
Could you please remove history files from commit and update with develop branch? Thanks!

**Comment by ndroo** [comment]
Sorry for the delayed reply here, life has been crazy, looks like you're in good shape now...so glad this got fixed for everyone else.

**Pull request merged**
