### PR TITLE
Move snap build from travis to launchpad

### LINKED ISSUE #5383: Snap: Add builtin Reverse Proxy with auto ssl
is there an easy way to configure reverse proxy on a snap installation?!

### PR DESCRIPTION
**Pull request by geekgonecrazy**
@RocketChat/core 

Move snapcraft build over to launchpad instead of in travis.

Successful build: https://code.launchpad.net/~rocket.chat.buildmaster/+snap/edge/+build/17179 on edge channel Revision 396

closes #5383

### CODE REVIEW

**Comment by Sing-Li** [comment]
Need to use existing snapcraft.yaml  (instead of mines)

Because all existing amd64 snap users are already deploying Mongo 3.2 - due to the hard coded URL to download the binaries in the old snap builds.

Reverting to the distribution specific Mongo, while is the "correct" way of doing things, will immediately disable those existing users upon upgrade.

**Comment by Sing-Li** [comment]
Awesome.   I'll help test the resulting snap tomorrow (Tues).  

Let's hold off merge until the (initial) resulting snap is thoroughly tested.

**Comment by geekgonecrazy** [comment]
Forgot about needing different yaml file for each  channel.  Have to adjust to be this way again

**Comment by Sing-Li** [comment]
Thanks.  Will test the new snap binaries once ready.

**Comment by Sing-Li** [comment]
both generated snaps (edge and stable) tested ....

* mongo verified to be 3.2.7
* both server and mongo came up in reasonable time
* backup command tested
* caddy tested

**Pull request merged**
