### PR TITLE
Set some queries to prefer the secondary database

### PR DESCRIPTION
**Pull request by rodrigok**
## Proposed changes
Direct the most expensive queries, that are not required to be made on the primary database, to use the secondaries when available, it will distribute the load of those queries on the other database instances and release the primary to the other operations.

This PR changes the following items:
* Some of the analytics queries
* Some of the statistics queries including the sessions' aggregations
* The message search
* The users autocomplete
* The messages search for data export

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
I wonder if we set tags in connection string if they will be honored by this query and only find secondaries matching the tags

**Comment by rodrigok** [comment]
@geekgonecrazy now it does https://github.com/RocketChat/Rocket.Chat/pull/18887/commits/10eb7c95d19f87ec2ba8265e8b70132b2f622855

**Review by sampaiodiego — APPROVED** [review]

**Comment by ankar84** [comment]
Sounds like fantastic improvement to Rocket Chat performance!
We have secondary MongoDB node and it idle almost all the time. And with this PR it will take part of most expensive queries. That's really great!
Thanks for that PR @rodrigok @sampaiodiego @geekgonecrazy 
And for  https://github.com/RocketChat/Rocket.Chat/pull/18892 thanks!  So much trouble was with user presence and so, I hope with that PR it's all in past.
Good job, RC team!
PS. I think WiredTiger engine should be recommended in all docs since now.

**Comment by antkaz** [comment]
Good work!
What are your thoughts on adding a secondary preference for all admin requests? i think this will give a small effect too

**Comment by ankar84** [comment]
I believe, that this PR not working as it should for some reason.
https://github.com/RocketChat/Rocket.Chat/issues/22132#issuecomment-857533050
https://github.com/RocketChat/Rocket.Chat/issues/22193#issuecomment-859396783

**Pull request merged**
