### PR TITLE
[FIX] Show active admin and user account menu item

### PR DESCRIPTION
**Pull request by hullen**
Closes https://github.com/RocketChat/Rocket.Chat/issues/8500

Added support to show active sidebar menu item on the user account and admin panels.

Screen Capture on 2020-03-27 at 10-35-25

Screen Capture on 2020-03-27 at 10-43-23

### CODE REVIEW

**Comment by sampaiodiego** [comment]
Looks like admin routes definition has changed, causing conflicts to this PR.. can you please take a look?

maybe @tassoevan can give a little help

**Comment by hullen** [comment]
Hey @tassoevan, did you change route '/admin/info' param name? Before section param returns 'admin-info', but now just 'admin'. I control the active menu item with this prop param.
File: app/ui-admin/client/adminFlex.js:83

**Comment by tassoevan** [comment]
@hullen I don't think so. At least it seems correctly defined in `app/ui-admin/client/routes.js`.

**Comment by hullen** [comment]
> @hullen I don't think so. At least it seems correctly defined in `app/ui-admin/client/routes.js`.
I see this changes, but i dont understand why route param name changed.

**Comment by rodrigok** [comment]
Would this replace the PR https://github.com/RocketChat/Rocket.Chat/pull/13111?

**Comment by hullen** [comment]
> Would this replace the PR #13111?

Yes, my PR cover itens this PR too. ;) But with another aproach to solve this.

**Pull request merged**
