### PR TITLE
[NEW] Setting option to mark as containing a secret/password

### LINKED ISSUE #9790: Add Setting Option to Mark as Containing a Secret or Password
Add a property to the setting object to mark it as containing a secret or password, this way when other items interact with settings (such as Rocket.Chat Apps) we can exclude these by default instead of maintaining an internal list of them.

### PR DESCRIPTION
**Pull request by kb0304**
@RocketChat/core 

Closes #9790

### CODE REVIEW

**Comment by graywolf336** [comment]
Let's move this to the next release, just because it's not needed at this point in time for the Apps. But will be needed next release. Thanks for making this @kb0304!

**Comment by geekgonecrazy** [comment]
wow git is painful... but its now up to date.  😌  @sampaiodiego

**Comment by sampaiodiego** [comment]
@geekgonecrazy :cry: 
image

**Comment by geekgonecrazy** [comment]
@sampaiodiego fixed!  Some how that got lost during all of the git shuffle 😢

**Comment by rodrigok** [comment]
Can someone fix the conflicts?

**Comment by rodrigok** [comment]
Missing following settings as secret:

- Accounts_OAuth_GitHub_Enterprise_id
- SMS_Voxtelesys_authToken
- SMS_Voxtelesys_URL

**Pull request merged**
