### PR TITLE
Accounts CAS login support

### PR DESCRIPTION
**Pull request by engelgabriel**

### CODE REVIEW

**Comment by rodrigok** [comment]
@engelgabriel what is CAS?

**Comment by engelgabriel** [comment]
LMGIFY

https://en.wikipedia.org/wiki/Central_Authentication_Service

**Comment by rodrigok** [comment]
CAS is like SAML

**Comment by corecache** [comment]
For more information on CAS, check out too: https://rubycas.github.io/

**Comment by Sing-Li** [comment]
Other than large hosting providers, CAS can become Rocket.Chat's entry-token into the world of Higher Education Institutions ->

Yale:

http://www.yale.edu/tp/auth/usingcasatyale.html

MIT:

https://sso-cas.rmit.edu.au/rmitcas/login?service=https%3A%2F%2Fmy.rmit.edu.au%2Fportal%2F

Harvard:

http://iam.harvard.edu/resources/cas-integration 

Columbia:

https://cuit.columbia.edu/cas-authentication

Just three from hundreds of examples worldwide.

**Comment by engelgabriel** [comment]
Hi @corecache can you give some instructions for us newbies on how to test this? Can we merge this PR after testing?

**Comment by corecache** [comment]
@engelgabriel I've tried testing this with a local CAS server running at localhost with a docker setup and came along some SSL shenanigans (self-signed certs) and having to disable checks for self-signed certs at different modules, such as hitting NodeJS with a bat to get this insecure setup working. 

Conclusion: if I need to fiddle that much around to actually test it, the results of the test are actually flawed - the better way is to test this with some live/production setup of a CAS instance with CA signed certs.

**Comment by engelgabriel** [comment]
@corecache lets us know if we can help.

**Comment by engelgabriel** [comment]
Closed in favor of https://github.com/RocketChat/Rocket.Chat/pull/2183

**Pull request closed without merging**
