### PR TITLE
[FIX] Custom sound error toast messages

### LINKED ISSUE #24514: [BUG] Needed error message in custom sound
### Description:
Whenever we only write name of custom sound in and do not upload custom sound it shows error 'undefined'.
### Steps to reproduce:

1.  Go to Admin
2.  Click on Custom Sound
3.  Click on New

### Expected behavior:

https://user-images.githubusercontent.com/76220055/154109264-8b56c44b-0c17-4cc6-9205-0c7e81e97bff.mp4

### Actual behavior:

https://user-images.githubusercontent.com/76220055/154109255-7f161390-ddd5-4b91-931a-74eb0435bf70.mp4

### Server Setup Information:
Version of Rocket.Chat Server: 4.5.0-develop
Operating System: Linux ubuntu 20.04
NodeJS Version: v14.18.2
MongoDB Version: 4.4.4 / wiredTiger (oplog Enabled)

### Client Setup Information
Desktop App or Browser Version: Chrome 97.0.4692.99 (Official Build) (64-bit)
Operating System: Linux Ubuntu 20.04

### PR DESCRIPTION
**Pull request by Himanshu664**
-   [x] I have read the Contributing Guide https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
  -  [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
  -  [x] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  - [ ] I have added necessary documentation (if applicable)
  - [ ] Any dependent changes have been merged and published in downstream modules
## Proposed changes (including videos or screenshots)
Added error message when user only write name and do not upload custom sound.

https://user-images.githubusercontent.com/76220055/154623353-2d333577-ab43-4dc8-a60f-0a2c36f0b625.mp4

## Issue(s)

fixes #24514

## Steps to test or reproduce
As mentioned in issue

### CODE REVIEW

**Comment by Himanshu664** [comment]
@dougfabris please review this PR.

**Review by debdutdeb — CHANGES_REQUESTED** [review]
Hi Himanshu ! Good jod keeping up the work ;)

About this pr, here's the problem I'm seeing here, this isn't effectively handling the actual issue. 

From the toast you could notice that `error` is undefined, but you took that off and added another string error message basically. Don't do that. Instead, figure out WHY `error` is undefined. 

I'll give you a hint, take look at `createSoundData`.

Once you figure out exactly why `saveAction` is failing, figure out what'd be the ideal way to mitigate that. Hint no. 2 - maybe you don't need to mess with errors here at all?

**Comment by Himanshu664** [comment]
@debdutdeb Sir I have made new commit I am not able to resolve issue I want your help. While debugging I got to know that soundFile is giving undefined, because we split the file by extension.So when no file uploaded it gives undefined.Here is video what I have tried.



https://user-images.githubusercontent.com/76220055/154484072-8184f91d-f48f-436a-bf51-ca3546c48f43.mp4

**Review by debdutdeb — APPROVED** [review]
Lgtm :)

**Review by debdutdeb — DISMISSED** [review]

**Review by dougfabris — APPROVED** [review]

**Pull request merged**
