### PR TITLE
[IMPROVE] Show roles on Thread Messages

### LINKED ISSUE #20282: No user roles displayed in the thread replies
### Steps to reproduce:

A user with special role, e.g. `Admin` that is displayed next to his username needs to do the following:
1. Go to any public or private channel or direct message
2. Find a message
3. Write a thread reply
4. Check that there is no role e.g. `Admin` displayed next to the username. --> a bug

In the regular messages, all user roles are displayed correctly.

### Expected behavior:

Display user roles next to the username in the thread replies, the same way it is done in the main messages.

### Actual behavior:

image
_Note the user roles `Admin` and `M` in the main thread for the user `dumitru`. And no roles in the thread reply message for the user `dumitru`._

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: Linux
- Deployment Method:  snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.14
--

### Client Setup Information

- Desktop App or Browser Version: browser version
- Operating System: Ubuntu

### PR DESCRIPTION
**Pull request by yash-rajpal**
## Proposed changes (including videos or screenshots)

Show User's roles in Thread Messages, as done in normal room Messages
image

## Issue(s)

fixes #20282 
## Steps to test or reproduce

Go to issue
## Further comments

Perhaps we can make a in-room setting to enable or disable this.

### CODE REVIEW

**Comment by yash-rajpal** [comment]
@dougfabris @MartinSchoeler @ggazzo Please Review. :)
Is this needed, perhaps we can make a setting which can toggle show roles for thread messages.

**Comment by dougfabris** [comment]
> @dougfabris @MartinSchoeler @ggazzo Please Review. :)
> Is this needed, perhaps we can make a setting which can toggle show roles for thread messages.

@yash-rajpal Unfortunately, we cannot move forward with your PR. We have concerns about UI. For example, users with bigger username lengths and the same for the role's length. For us, it's not a big problem for now since we can just click on the user's profile and see the roles quickly. Btw, thanks for all help!

**Comment by yash-rajpal** [comment]
@dougfabris No problem, I too think the UI looked too cluttered, we can then close the issue to which this pr was linked.

Thanks :)

**Comment by dougfabris** [comment]
> @dougfabris No problem, I too think the UI looked too cluttered, we can then close the issue to which this pr was linked.
> 
> Thanks :)

We're planning to improve this case with a better design solution with our team as soon as possible =)

**Pull request closed without merging**
