### PR TITLE
Feature - Highlights Words

### PR DESCRIPTION
**Pull request by Johann-Snapp**
As asked in #2223, I've closed the old and created a new PR.

I've:

- Rearrange my commits
- Renamed the package from `rocketchat-highlight-words` to `rocketchat:highlight-words`
- Started to optimize the query

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@Johann-Snapp looks like this needs rebased, are you familiar with how to do that?

@RocketChat/core anything else we need before we try and merge this down?

**Comment by Johann-Snapp** [comment]
Rebase done !

I think the query can be improved but as I'm not very at comfortable with querying mongo, I'd need some help.
We can do this before merging or open an issue in order to not forget.

**Comment by geekgonecrazy** [comment]
@RocketChat/core anything else we need?

**Comment by sampaiodiego** [comment]
I have a few considerations:

- highlights are not case insensitive as mentioned [here](https://github.com/RocketChat/Rocket.Chat/pull/2236/files#diff-3bd53577793963a790b0a2c8b10e3fabR213);
- [renderMessage callback](https://github.com/RocketChat/Rocket.Chat/pull/2236/files#diff-0925f8763a039a22e134ac95bbb98349R25) should be client **and** server side;
- highlight words shoud be regex-sanitized [here](https://github.com/RocketChat/Rocket.Chat/pull/2236/files#diff-0925f8763a039a22e134ac95bbb98349R20).

Anyway, LGTM :smile: .. we can merge and fix it later..

Also, we need to put messages with highlighted words on _mentions panel_ :wink:

**Comment by geekgonecrazy** [comment]
LGTM too :)

**Comment by Johann-Snapp** [comment]
- highlights  are not case insensitive as mentioned;
I'm gonna test it

- renderMessage callback should be client and server side;
Can you explain please ? I don't understand.

- highlight words shoud be regex-sanitized here.
I'm gonna do it.

I'll make asked changes tomorrow (9:00 GMT + 1)

**Comment by sampaiodiego** [comment]
@Johann-Snapp if you don't mind, I can do this after I merge it.
I'm just waiting for Travis-CI

**Comment by geekgonecrazy** [comment]
>* renderMessage callback should be client and server side;

>Can you explain please ? I don't understand.

In the file: 
packages/rocketchat-highlight-words/package.js

You have:

```
api.addFiles('client.coffee', 'client');
```

Which makes the code there only execute on the client.  He's saying we want this code to execute on the client and the server.

**Comment by sampaiodiego** [comment]
hmm.. we can't use it on server as ask before (sry, my fault)..
we can't use `Meteor.user()` as used in `client.coffee` file.

the reason why I asked to run it on server side too was because the send email feature. without running it on the server, the message sent by email will not have _ highlight words_

**Comment by sampaiodiego** [comment]
btw, since @engelgabriel merged it, I'm already working to fix that issues.

**Pull request merged**
