### PR TITLE
Audio record

### PR DESCRIPTION
**Pull request by rodrigok**
captura de tela 2015-08-17 as 18 47 58
captura de tela 2015-08-17 as 18 48 03
captura de tela 2015-08-17 as 18 48 08

### CODE REVIEW

**Comment by Sing-Li** [comment]
omg!  can't wait to try this mobile :smile:

**Comment by rodrigok** [comment]
@Sing-Li Doesn't works in iOS with safari, I don't now about cordova and android

**Comment by Sing-Li** [comment]
@rodrigok   Don't know about webview.  But on my note 2, android 4.4.2, with latest chrome it (almost) works :smile:   It asks for permission, shows the dialog box, takes the recording 'square button' click, but always records a short 2 second silence only. It also successfully upload  that 2 seconds of silence.

**Comment by guarilha** [comment]
@rodrigok tested on the android app but it doesn't work. On chrome android app it works like a charm, didn't have the same problems @Sing-Li had. I'm on a Moto G 1st gen with android 5.1.1

**Comment by Sing-Li** [comment]
Just tried the latest HEAD.  Chrome v.latest on android 4.4.2 - records okay, uploads okay. But uploaded file no longer shows up as audio oembed on message page.

**Comment by rodrigok** [comment]
@Sing-Li at demo.rocket.chat?

**Comment by Sing-Li** [comment]
@rodrigok  no.  locally hosted.  Having problem accessing demo.rocket.chat - with both Chrome (page lockup after oauth) and the hybrid client (Method not Found for most ops).  Do I need to 'meteor add' something additional to make local version work?

**Comment by rodrigok** [comment]
@Sing-Li Your settings for Embed is active?

**Comment by Sing-Li** [comment]
@rodrigok - that was it!   I changed it as admin (and had to reboot server) and embed worked. But the embed cannot play - probably related to #497.  @guarilha  - were you able to play back the sound by touching the embed in the message list?

**Pull request merged**
