### PR TITLE
Fix more rtl issues

### LINKED ISSUE #8180: [BUG] [UI] "<username> is typing" (in arabic یکتب...) alignment is incorrect in RTL
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.

### LINKED ISSUE #8181: [BUG] [UI] "Unread message" alignment issue in RTL
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.

### LINKED ISSUE #8186: [BUG] [UI] Some bug in create room modal in RTL
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.

### LINKED ISSUE #8187: [BUG] [UI] Cross alignment is incorrect in search textbox in RTL
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #8180
Closes #8181
Closes #8186 
Closes #8187

* Add cross icon to cancel button on modal and fix that button on RTL
image

* Fix unread message on RTL
image

* User is typing on RTL
image

* Fix message box placeholder direction on RTL
image

### CODE REVIEW

**Comment by cyclops24** [comment]
Thanks @karlprieb 
In modal (create room) when we want add user a little padding required between username and user avatar. See this:

I mentioned this in #8186

**Comment by karlprieb** [comment]
@cyclops24 Sorry, I forgot about that. I will add this fix to this PR :) Thank you!

**Comment by karlprieb** [comment]
Fixed submit button on RTL
image

Fixed username padding on RTL
image

**Comment by cyclops24** [comment]
@karlprieb , @rodrigok Cross icon to cancel button on modal ( #8186 ) still has bug in Firefox 55:

Other parts fixed completely, thanks @karlprieb 😉

**Pull request merged**
