### PR TITLE
[FIX] Changing Room name updates the webhook

### LINKED ISSUE #8477: Changing room name doesn't update incoming webhooks
If I have an incoming webhook set to room #foo, then I change #foo's name to #bar, the webhooks don't get updated, and I only find out when webhooks stop working. No error is raised either, I opened #8476 for that.

### PR DESCRIPTION
**Pull request by knrt10**
Closes #8477 

@MartinSchoeler @ggazzo would you please review.

### CODE REVIEW

**Comment by ggazzo** [comment]
@knrt10 I made a few changes, we usually create a file for each method... and its not a client concern update webhooks... please check if you agree

**Comment by knrt10** [comment]
@ggazzo totally agree with you. It would have been on  server side. Looks good

**Comment by rodrigok** [comment]
@knrt10 can you fix the conflicts please?

**Comment by knrt10** [comment]
Yes let me update it

**Comment by knrt10** [comment]
@rodrigok rebased

**Comment by knrt10** [comment]
@sampaiodiego updated

**Pull request merged**
