### PR TITLE
i18n: more Hindi translation keys added

### LINKED ISSUE #30892: Some of the translation keys are missing in Hindi translation
### Description: 

There are lots of keys missing in `hi-IN.18N.json` as compared to `en.i18n.json` file available in the `apps/meteor/packages/rocketchat-i18n/i18n` folder

### Steps to reproduce:

1. Go to-  `apps/meteor/packages/rocketchat-i18n/i18n`

### Expected behavior:

There should be a translation present for all the keys.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### LINKED ISSUE #32786: Hindi Language Translation Backlog in UI
### Description:

When switching the language to Hindi, some words and phrases remain in the default language. The application should fully support Hindi translation.

### Steps to reproduce:
Go the preferences section while clicking upon the profile
choose Hindi from the dropdown of language
### Expected behavior:

All UI elements should be translated into Hindi.
### Actual behavior:
Certain words and phrases remain in English.

https://github.com/user-attachments/assets/7bc4b92d-3c8f-43ed-82fe-6780c454f3c3

### Server Setup Information:

- Version of Rocket.Chat Server:  6.10.0
- License Type:Community
- Number of Users: 3
- Operating System: MacOs
- Deployment Method: docker
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.4
- MongoDB Version:7.0.5

### Client Setup Information

- Desktop App or Browser Version:Browser
- Operating System:MacOs

### PR DESCRIPTION
**Pull request by its-kunal**
## Proposed changes (including videos or screenshots)

Added translation more translation keys for hindi language.

## Issue(s)

Closes #30892 
Closes #32786

### CODE REVIEW

**Comment by its-kunal** [comment]
Hey @MartinSchoeler Please review my pull request. #30927

**Comment by its-kunal** [comment]
@MartinSchoeler When will this PR get merged?

**Comment by its-kunal** [comment]
Hey @reetp , can you please review my PR.

**Comment by scuciatto** [comment]
Hey, @its-kunal . Thanks for this contribution. Can you please fix the conflicts so we can review it?

Also, you can contribute to translations using Duolingo. It's a faster way to do it, since the merges are automated and the translations added to new releses. If you want an invite to Duolingo, please send me an e-mail (felipe.scuciatto[at]rocket.chat )

**Review by scuciatto — CHANGES_REQUESTED** [review]
Hey, @its-kunal . Thanks for this contribution. Can you please fix the conflicts so we can review it?

Also, you can contribute to translations using Duolingo. It's a faster way to do it, since the merges are automated and the translations added to new releses. If you want an invite to lingohub, please send me an e-mail (felipe.scuciatto[at]rocket.chat )

**Comment by its-kunal** [comment]
Ok, I'll soon resolve the conflicts.

**Review by dougfabris — APPROVED** [review]

**Review by dougfabris — APPROVED** [review]

**Pull request merged**
