### PR TITLE
[FIX] File upload (Avatars, Emoji, Sounds)

### PR DESCRIPTION
**Pull request by ggazzo**
closes https://github.com/RocketChat/Rocket.Chat/issues/18736

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by gabriellsh — APPROVED** [review]

**Comment by klepptor** [comment]
Well, still doesn't work at least in my case. I can upload the room avatar picture and it's shown in room settings. But after saving it's not set as room avatar!

RC 3.6.1 using docker

I20200912-08:14:07.186(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setRoomAvatar.js:34:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by klepptor** [comment]
Well, still doesn't work at least in my case. I can upload the room avatar picture and it's shown in room settings. But after saving it's not set as room avatar!

RC 3.6.1 using docker

I20200912-08:14:07.186(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setRoomAvatar.js:34:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by klepptor** [comment]
Well, still doesn't work at least in my case. I can upload the room avatar picture and it's shown in room settings. But after saving it's not set as room avatar!

RC 3.6.1 using docker

I20200912-08:14:07.186(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setRoomAvatar.js:34:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by klepptor** [comment]
Well, still doesn't work at least in my case. I can upload the room avatar picture and it's shown in room settings. But after saving it's not set as room avatar!

RC 3.6.1 using docker

I20200912-08:14:07.186(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setRoomAvatar.js:34:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by klepptor** [comment]
Well, still doesn't work at least in my case. I can upload the room avatar picture and it's shown in room settings. But after saving it's not set as room avatar!

RC 3.6.1 using docker

I20200912-08:14:07.186(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setRoomAvatar.js:34:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by klepptor** [comment]
Well, still doesn't work at least in my case. I can upload the room avatar picture and it's shown in room settings. But after saving it's not set as room avatar!

RC 3.6.1 using docker

I20200912-08:14:07.186(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setRoomAvatar.js:34:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by klepptor** [comment]
Well, still doesn't work at least in my case. I can upload the room avatar picture and it's shown in room settings. But after saving it's not set as room avatar!

RC 3.6.1 using docker

I20200912-08:14:07.186(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setRoomAvatar.js:34:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by klepptor** [comment]
Well, still doesn't work at least in my case. I can upload the room avatar picture and it's shown in room settings. But after saving it's not set as room avatar!

RC 3.6.1 using docker

I20200912-08:14:07.186(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setRoomAvatar.js:34:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by klepptor** [comment]
Well, still doesn't work at least in my case. I can upload the room avatar picture and it's shown in room settings. But after saving it's not set as room avatar!

RC 3.6.1 using docker

I20200912-08:14:07.186(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setRoomAvatar.js:34:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by klepptor** [comment]
Well, still doesn't work at least in my case. I can upload the room avatar picture and it's shown in room settings. But after saving it's not set as room avatar!

RC 3.6.1 using docker

I20200912-08:14:07.186(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setRoomAvatar.js:34:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by yusolcev** [comment]
> Well, still doesn't work at least in my case. I can upload the room avatar picture and it's shown in room settings. But after saving it's not set as room avatar!
> 
> RC 3.6.1 using docker
> 
> I20200912-08:14:07.186(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined at app/lib/server/functions/setRoomAvatar.js:34:46 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js12) at packages/meteor.js:550:25 at runWithEnvironment (packages/meteor.js:1286:24)

Group avatar saved only from admin account

**Pull request merged**
