### PR TITLE
[FIX] Fixed #8368 by removing first carriage return after triple backticks.

### LINKED ISSUE #8368: multi line code adds extra line
### Description:

Using the multi line code (```) adds an extra line on top of its content.
This was detected on demo.rocket.chat 0.59.0-rc.10

### Steps to Reproduce:

1. Write some multi line code
screen shot 2017-10-01 at 01 52 51

2. Send

3. Extra line added up top
screen shot 2017-10-01 at 01 53 18

### Expected behavior:

screen shot 2017-10-01 at 02 01 44

### Actual behavior:

  
screen shot 2017-10-01 at 01 53 18

### PR DESCRIPTION
**Pull request by TunedMidja**
@RocketChat/core 

Closes #8368

### CODE REVIEW

**Comment by rodrigok** [comment]
Can you confirm if is there 2 \n at the beginning? My opinion is, if you remove the first \n without check if there is an empty line you will break if the empty line was removed by another code

**Comment by TunedMidja** [comment]
@rodrigok, when the \n is removed there is only one \n so only remove one if there are two won't fix the original issue.

**Comment by geekgonecrazy** [comment]
@rodrigok is the answer satisfactory to dismiss review?  Or should there be more changes?

**Comment by gdelavald** [comment]
I think we could have a better implementation here, maybe directly on the blockquote detection? This seem awfully _brute-forcey_.

**Comment by TunedMidja** [comment]
I just tried the latest code on develop and this problem seems to have been solved already. Please verify this and then we can close this pull request.

**Comment by ggazzo** [comment]
hey @TunedMidja you are right thanks for you time, but the problem was fixed by another code... thanks again

**Pull request closed without merging**
