### PR TITLE
fix flex-tab on ie11 and fix all will-change

### LINKED ISSUE #5313: Right sidebar blank on Internet Explorer 11
Your Rocket.Chat version: rocketchat-server  0.48.2   326

Recently installed rocketchat as snap on ubuntu. In Firefox everything I tested works fine, but in Internet Explorer 11, the right sidebar menu is blank only, doesn't matter which tab on the right sidebar. Everything else works as expected in Internet Explorer, too.
IE:
2016-12-23 10-36-54_constant 100 processor load with multiple rocket chat instances issue 5312
FF:
2016-12-23 10-37-45_pwo chat

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #5313

- Fix IE11 flex-tab
- Adjust all `will-change` for better performance (using CPU wisely :) )
- Fix messages-box position on RTL (`message-buttons` was hidden)

### CODE REVIEW

**Comment by engelgabriel** [comment]
@karlprieb the tests are failing :(

**Comment by karlprieb** [comment]
@engelgabriel Can you run the tests again? It's possible that the problem is timing. Thanks :)

**Comment by engelgabriel** [comment]
I have tried 3 times already... are the tests passing locally?

**Comment by karlprieb** [comment]
Sorry, I didn't know that you already tried that. I will check locally and fix this bug.

**Comment by rodrigok** [comment]
@karlprieb Can you solve the conflicts?

**Comment by engelgabriel** [comment]
depends on https://github.com/RocketChat/Rocket.Chat/pull/5394

**Pull request closed without merging**
