### PR TITLE
[NEW] [WIP] Room Avatar

### LINKED ISSUE #3582: Add Avatar for channels
Your Rocket.Chat version: (make sure you are running the latest)
HI
The proposal for channels
Avatar set to channels that have more beauty
Example: See photos
qqqdd

### PR DESCRIPTION
**Pull request by ramrami**
Closes #3582 

Capture d’écran 2019-05-23 à 19 16 04

Capture d’écran 2019-05-23 à 19 51 04

- [x] Create room
- [x] Update room
- [x] Discussions (have the same avatar as the parent room)
- [x] Admin room list
- [x] Admin room update
- [x] Directory list
- [ ] Api
- [ ] Tests

Question :  
what is this for ?  ```Session.set(`avatar_random_${ username }`, Date.now());```

### CODE REVIEW

**Comment by Xerionty** [comment]
Nice!

**Comment by ggazzo** [comment]
to invalidate/rerender the image after some avatar update
> Question :
what is this for ? Session.set(`avatar_random_${ username }`, Date.now());

**Comment by ramrami** [comment]
I see thanks

**Comment by gyde** [comment]
Epic, we would really love this feature :)

**Comment by Giplat** [comment]
This would be great!

**Comment by liangzhifeng12** [comment]
cant wait for this

**Comment by novacrazy** [comment]
What's the status on this?

**Comment by zdumitru** [comment]
@ramrami Can you please sign the CLA?

**Comment by ramrami** [comment]
@zdumitru done

**Comment by lmopi** [comment]
Any date ?

**Comment by knarrff** [comment]
Maybe we could get this reviewed and merged as a Christmas present? Please? :)

**Comment by col-panic** [comment]
what happened?

**Comment by mrbenito** [comment]
Oooh! WANT THIS. Can we get merged please?

**Comment by C1ean** [comment]
Any updates?

**Comment by engelgabriel** [comment]
Sorry for the delay guys, we will give this a high priority and get it done.

**Pull request closed without merging**
