### PR TITLE
 [NEW] Syncloud deploy option

### PR DESCRIPTION
**Pull request by cyberb**
I would like to add Syncloud (https://github.com/syncloud/platform, https://syncloud.org) as a deploy option.
We have Rocket.Chat as an app on our self-hosting project.

Thank you

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@cyberb I would recommend adding to our docs also.  This file is getting kind of massive.  I suspect at some point we might want to clean up a bit.  But listing as a deployment option in docs would probably be more guaranteed to stick around.

Also curious is this using snaps under the hood?

**Comment by cyberb** [comment]
Yes we are usong snap but daemon is a little bit modified to support plain s3 backend for packages.

Sure I can look at the docs, do you have a link?

Thanks

**Comment by geekgonecrazy** [comment]
awesome!  Sounds interesting.  

https://rocket.chat/docs is public facing.  The repo that backs it is at: https://github.com/rocketchat/docs

**Comment by marceloschmidt** [comment]
@geekgonecrazy can you check his [PR](https://github.com/RocketChat/docs/pull/1019)? and also merge or close this one?

**Pull request merged**
