### PR TITLE
Fixes #13909 Directory label height

### LINKED ISSUE #13909: Directory fields wrong size
As seen below when Federation is enabled:

image

### PR DESCRIPTION
**Pull request by sudipt1999**
Just need to set a min height for the directory class!

### CODE REVIEW

**Comment by sampaiodiego** [comment]
I'm not sure this fixes the issue.

**Comment by sudipt1999** [comment]
Ok! can you please tell where I should be looking then

**Comment by sampaiodiego** [comment]
@sudipt1999 sorry I don't know the fix or where it should be done. But I tested your proposal and it didn't fix..

I recommend you to run the project and test the changes before submitting any fix.

**Comment by sudipt1999** [comment]
Actually I tested on my machine then made the pr !Sorry for inconvenience!

**Comment by sampaiodiego** [comment]
tested again but the search field is still wrong:
image

I'll be closing the PR as invalid.. please don't hesitate in opening another one if you happen to find the fix.. thx

**Pull request closed without merging**
