### PR TITLE
Fix: Rooms and users are using different avatar style

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

image

image

### CODE REVIEW

**Comment by graywolf336** [comment]
Sorry, but I prefer the other way. This is now way too confusing. If you're dead set on making it this way, can we please make it a personal preference?

**Comment by sampaiodiego** [comment]
@graywolf336 the idea is to prepare to when channels will have their own avatar.. so they will like pretty much as users.. 

I'm just not sure if we should have the new colored avatars for channels even on the small version. we could maybe have the "old way" (non-colored with just the icon) on the small version and have the colored/image avatar for channels on the big version..

**Comment by geekgonecrazy** [comment]
> I'm just not sure if we should have the new colored avatars for channels even on the small version. we could maybe have the "old way" (non-colored with just the icon) on the small version and have the colored/image avatar for channels on the big version..

I think on the large view its probably ok for avatars and/or showing this default name based image.  But on small version I think we should keep the icons like they are now.

I think by changing the colors like we have we've already changed a lot this version :grin:

**Comment by rodrigok** [comment]
@graywolf336 @geekgonecrazy The current version (with lock/hash inside the colored square) will need to change as soon we have images for channels, that's why I moved the icon out.

That is a design decision and @engelgabriel can explain.

**Comment by rodrigok** [comment]
There is an option to reduce the noise, move the room icon to the right
image

**Comment by engelgabriel** [comment]
We will merge this to keep it coherent with the new mobile design. I agree that avatars should be optional, and we will implement that option later.

image

**Comment by geekgonecrazy** [comment]
In those screens with lock/hash + image.  That to me is a bit better :+1:

**Comment by rodrigok** [comment]
Another option to reduce the noise is reduce the initials to one letter
image

**Comment by geekgonecrazy** [comment]
IMO that helps a lot.

**Comment by graywolf336** [comment]
> Another option to reduce the noise is reduce the initials to one letter

I like this option the best then.

**Comment by rodrigok** [comment]
Another option
image

**Comment by rodrigok** [comment]
image

**Pull request merged**
