### PR TITLE
Better centering for dropzone

### PR DESCRIPTION
**Pull request by mccambridge**
@RocketChat/core 

I noticed an issue with our R.C site where the dropzone message wasn't centered in its div. Also, at certain widths (around 500px or so), the message was being hidden by the left sidebar. This commit fixes both of these issues. Cheers!

### CODE REVIEW

**Comment by rodrigok** [comment]
Awesome @mccambridge, can you post print screens of before and after your changes?
Thanks

**Comment by mccambridge** [comment]
screen shot 2016-08-04 at 10 04 48 am 2
Before: centered on page (whereas dropzone in only the main pane on the right)

screen shot 2016-08-04 at 10 02 52 am 2
After: centered on right pane

screen shot 2016-08-04 at 10 05 37 am 2
Before: really small screens see smooshed text. We actually use Rocket.Chat in an iframe in our app, so a screen this small is common for us.

screen shot 2016-08-04 at 10 05 53 am 2
After: readable text

**Comment by mccambridge** [comment]
@rodrigok whoops, i closed and re-opened. screenshots attached

**Comment by rodrigok** [comment]
@mccambridge so beautiful :D thanks

**Comment by mccambridge** [comment]
@rodrigok it doesn't include the cold start text in the background of the screenshot -- just to be clear. is that something you'd like me to PR?

**Comment by dytec** [comment]
@mccambridge are you able to share how you managed the cold start text in the channel?
It would be very interesting!

**Comment by rodrigok** [comment]
@mccambridge Yes, it's clear :) Will amazing if you can submit a PR for that :D

**Pull request merged**
