### PR TITLE
[FIX] Fix typo when create discussion modal opens

### PR DESCRIPTION
**Pull request by Amit91848**
- [x]  I have read the Contributing Guide 
  https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
-  [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
  - [x] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
   - [ ] I have added necessary documentation (if applicable)

## Proposed changes (including videos or screenshots)

Fixed typo when discussion modal opens. Now it says - Help keep an overview of what's going on!

Screenshot 2022-03-29 at 6 59 45 PM

### CODE REVIEW

**Comment by debdutdeb** [comment]
@Amit91848 please sign the CLA.

**Comment by Amit91848** [comment]
Screenshot 2022-03-29 at 9 17 19 PM

I have already signed the cla. But somehow it keeps on showing pending!?

**Comment by Kunalvrm555** [comment]
Please make sure that you are using the same GitHub account for signing the CLA and for opening a pull request.
@Amit91848

**Comment by Amit91848** [comment]
Yes, I checked multiple times, I am using the same account

**Review by ggazzo — APPROVED** [review]

**Review by dougfabris — APPROVED** [review]

**Pull request merged**
