### PR TITLE
[NEW] Save room's last message

### LINKED ISSUE #8383: API to pull unread messages
We need the Rest API to be able to pull the following:
1. Username/name of person who sent me the message
2. Message text (or at least X chars of the beginning of the message)
3. Message timestamp

Use case: We want to alert our users when they have a new message, but don't want them to have to load the whole chat screen. Instead, we want to enable the user to quickly check who sent them a message and what they said. If they want to read more or reply they can click to open the full RC window.

### PR DESCRIPTION
**Pull request by sampaiodiego**
@RocketChat/core 

It closes #8383 since the `lastMessage` field is also returned from `im.list`, `channels.list` and `groups.list` REST APIs.

The feature is turned off by default and can be activated via admin panel:
image

This is how it looks on web when turned on:
image

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
😍  that screenshot is killer with a John Doe user and his very own avatar. :grin:

**Comment by geekgonecrazy** [comment]
Ok I gotta ask.  What happens if If the last message is massive?

**Comment by sampaiodiego** [comment]
>Ok I gotta ask. What happens if If the last message is massive?

@geekgonecrazy it will be all rendered but hidden via CSS :thinking:

**Comment by graywolf336** [comment]
> it will be all rendered but hidden via CSS :thinking:

Do you think there should be a character limit? For performance reasons? :thinking:

**Pull request merged**
