### PR TITLE
[FIX] File uploads out of threads are not visible in regular message view

### LINKED ISSUE #16276: Image uploads (thumbnails) out of threads are not visible in regular message view
### Description:

If you upload a image into a thread, the image is only visible in the left thread sidebar when certain thread is currently opened. In the main conversation view there is just an empty message without any thumbnail or indicator that there should be an image embedded.

#### Thread view

Bildschirmfoto 2020-01-18 um 09 18 19

#### Main conversation view

Bildschirmfoto 2020-01-18 um 09 18 29

### Steps to reproduce:

1. Go to an channel and find an existing thread
2. Upload an image into the thread
3. Notice how it's missing in the main conversation view

### Expected behavior:

There should be should be some kind of indicator that there was an image uploaded. 

### Actual behavior:

Just an empty message / placeholder

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: Yes
- NodeJS Version: Docker
- MongoDB Version: Docker

### PR DESCRIPTION
**Pull request by ashwaniYDV**
Closes #16276 #16415

### CODE REVIEW

**Comment by ashwaniYDV** [comment]
@ggazzo Would you please review

**Comment by ggazzo** [comment]
just waiting @sampaiodiego fix the CI

**Comment by sampaiodiego** [comment]
CI is fixed.. just need to update to rebase with latest `develop`

**Comment by gabriellsh** [comment]
> CI is fixed.. just need to update to rebase with latest `develop`

Done.

**Pull request merged**
