### PR TITLE
fix: Can't remove channel's password to join

### LINKED ISSUE #31506: [BUG] Unable to remove the channel password once it has been set.
### Description:

Once you set a password for your channel, you can change/reset it, but you can't remove it. Even if you turn off the password access, it doesn't unset, and the toggle will still be on. It has been tested with another user too to confirm that the password isn't actually being unset.

### Steps to reproduce:

1. Open the Rocket Chat application and log in with admin privileges.
2. Choose a channel and click on the info icon.
3. In the opened box, click on Edit.
4. Scroll down and set a password to access the channel.
5. Attempt to unset the password by toggling it off and saving.
6. The password cannot be unset, and it will remain in place.

### Expected behavior:

Once the "password to access" toggle is turned off and saved, the password should be unset.

### Actual behavior:

The password to access remains unchanged and does not unset even after setting it off.

https://github.com/RocketChat/Rocket.Chat/assets/78961432/fdb7a4b9-f970-4a53-8b83-493eff331db7

### Server Setup Information:

- Rocket.Chat Server Version: 6.6.0-develop
- Operating System: Ubuntu 22.04.3 LTS 
- Deployment Method: Local development server deployment
- NodeJS Version: 14.21.4 - x64
- MongoDB Version: 6.0.3

### Client Setup Information

- Desktop App or Browser Version: Microsoft Edge Version 120.0.2210.133 (Official build) (64-bit)
- Operating System: Ubuntu 22.04.3 LTS

### PR DESCRIPTION
**Pull request by Spiral-Memory**
## Proposed changes (including videos or screenshots)

The issue arises from a minor detail: when the password box is empty, the condition `data.joinCode` results in a falsy value. As a result, no key with the name `joinCode` is sent, preventing the password from unsetting. The backend, however, expects an empty string ('') to unset the password. To resolve this, a small fix was implemented. The `getDirtyFields` returns a key of `joinCodeRequired` when the password to access toggle changes. So, i used that property to create a new condition to check for the existence of this key. If it exists, an object named `joinCode` with an empty string value is created and sent to the backend to address the issue.

## Issue(s)

Closes #31506 

https://github.com/RocketChat/Rocket.Chat/assets/78961432/23ee4ed2-96f5-4ce2-a826-50c9201d7ffa

## Steps to test or reproduce

The steps to reproduce is mentioned in the issue I created, which is #31506.

## Further comments

Just a very small but important fix.

### CODE REVIEW

**Review by dougfabris — APPROVED** [review]
@Spiral-Memory Nice catch, thank you so much for helping us!

**Comment by Spiral-Memory** [comment]
@dougfabris , Thank you so much for reviewing my changes and approving them. It's my very first PR in this repository to get merged, and I am really happy that I could be of some use in helping the application. I would like to request you to please review two more of my PRs: [PR #1265](https://github.com/RocketChat/fuselage/pull/1265) and [PR #1262](https://github.com/RocketChat/fuselage/pull/1262) in the Fuselage repository if possible. They were raised a week before, and I believe they might be helpful as well.

Additionally, I would like to report a security issue in the Rocket Chat application related with password protected channel only. However, I am uncertain whether to report it in the bug section or the security vulnerability section. Could you please guide me on this? Also, can I work on that issue?

**Comment by dougfabris** [comment]
@Spiral-Memory Sure, I will take a look as soon as possible. 
For vulnerability and security issues I would recommend you use our [Hackerone page](https://hackerone.com/rocket_chat)

**Comment by Spiral-Memory** [comment]
> @Spiral-Memory Sure, I will take a look as soon as possible. 
> For vulnerability and security issues I would recommend you use our [Hackerone page](https://hackerone.com/rocket_chat)

Thank you for your reply. Sir, I have reported the security issue on GitHub in the security vulnerability section. You can have a look; it's still in the triage section. Also, HackerOne is not accepting submissions, I believe.

**Pull request merged**
