### PR TITLE
[FIX] User status missing on user info

### PR DESCRIPTION
**Pull request by sumedh123**
@RocketChat/core 

Fixes https://github.com/RocketChat/Rocket.Chat/issues/9820
screen shot 2018-02-23 at 7 31 27 pm

### CODE REVIEW

**Comment by sumedh123** [comment]
@geekgonecrazy Please review.

**Comment by sumedh123** [comment]
@geekgonecrazy @rodrigok  Please review.

**Comment by karlprieb** [comment]
I think it's not necessary. We already have the user status on the sidebar, on member list panel and on the header.

What you guys think @RocketChat/core ?

**Comment by sampaiodiego** [comment]
IMO it is good to have this information there as well

**Comment by graywolf336** [comment]
Yes, I think we should have this here, Especially for the administration side of things..

**Comment by geekgonecrazy** [comment]
Yes I miss this when gone 😁

**Pull request merged**
