### PR TITLE
[FIX] Normalize Thread Messages

### LINKED ISSUE #20841: [BUG] Reactions in Threads do not enforce Real Name Setting
### Description:

While reactions in rooms and discussions are served with the real name setting enforced, those in the thread aren't. In the Threads, the usernames are **always** used for display.

### Steps to reproduce:

1. Set Real Names setting on for the server, or use one where it is turned on(Ex: Open.Rocket.Chat).
2. Open any thread with replies where at least one person other than the current user has reacted to a reply.
3. Hover over the reaction to look at the names.

### Expected behavior:
For the real name to be used.

### Actual behavior:

With use real name turned on.
Screenshot from 2021-02-21 00-15-18

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu 20.10
- Deployment Method: develop
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.2.8 

### Client Setup Information

- Desktop App or Browser Version: Firefox Latest
- Operating System: Ubuntu 20.10

### Additional context

Fix PR ready.

### PR DESCRIPTION
**Pull request by aKn1ghtOut**
## Checklist

- [x] I have read the Contributing Guide
- [x]  I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

The `getThreadMessages` function was not using the normalize function, which adds the real names to the reactions in accordance with the `Use Real Name` setting. Added that. Now, the function works as expected.

### Before:
Screenshot from 2021-02-21 00-15-18

### Now:
Screenshot from 2021-02-21 00-11-11

## Issue(s)

Closes #20841 

## Steps to test or reproduce

1. Set Real Names setting on for the server, or use one where it is turned on(Ex: Open.Rocket.Chat).
2. Open any thread with replies where at least one person other than the current user has reacted to a reply.
3. Hover over the reaction to look at the names.

### CODE REVIEW

**Comment by sampaiodiego** [comment]
how this compares to https://github.com/RocketChat/Rocket.Chat/pull/20634 ?

**Comment by rodrigok** [comment]
Missing the normalization on REST APIs and on `getThreadsList`

**Comment by KevLehman** [comment]
I think this is a duplicate of #20634

**Comment by aKn1ghtOut** [comment]
The other PR author was going about it a different way before, and perceived it to be a different issue. I think he's now implementing the changes as prescribed right now.
I'll wait for a couple days. If not, I'll implement the additions @rodrigok mentioned here instead.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Closing this PR because it's stale now and it was already fixed here: #30069

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Pull request closed without merging**
