### PR TITLE
fix: Login services button colors

### PR DESCRIPTION
**Pull request by yash-rajpal**
## Proposed changes (including videos or screenshots)

The login services button was not implementing the button color properties, so fixed it and now the login services button will render the button colors as per the settings.
image
image

## Further comments

[SUP-590](https://rocketchat.atlassian.net/browse/SUP-590)

[SUP-590]: https://rocketchat.atlassian.net/browse/SUP-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MarcosSpessatto — CHANGES_REQUESTED** [review]
Would it be possible to add a UI test to ensure the behavior?

**Review by MarcosSpessatto — CHANGES_REQUESTED** [review]
I didn't see any test assertion related to the fix, am I missing something? 🤔

**Comment by yash-rajpal** [comment]
Tested the change of button text setting in existing tests.

**Comment by MarcosSpessatto** [comment]
> Tested the change of button text setting in existing tests.

But what about the issue? Isn't it about the color? 🤔 Didn't see anything mentioning the label..

**Review by dougfabris — CHANGES_REQUESTED** [review]
During the login refactor it was a design decision to not allow such customization. 

Waiting for their reply to move forward!

**Review by dougfabris — APPROVED** [review]
LGTM!

**Review by MarcosSpessatto — APPROVED** [review]

**Pull request merged**
