### PR TITLE
[FIX] Issue #13285 channel setting topic,description changed to textarea.

### LINKED ISSUE #13285: Make the channel description a textarea
Expressing the purpose of a channel in a single line without any line breaks isn't always possible and quite ugly. So please make it a `textarea` instead of an text `type=input`

If I change my local html via Browserdevtools it works out of the box - so you guys are already saving and displaying newlines correctly - I just can't type them without a little hack.

### PR DESCRIPTION
**Pull request by savish28**
Closes #13285 

It is taken care that header topic does not overflow.

It looks like :- 
rocketchat issue13285 after

### CODE REVIEW

**Comment by savish28** [comment]
@ggazzo

**Comment by savish28** [comment]
@ggazzo Please could you review this. I made the changes as suggested by you in #13434.

**Comment by tassoevan** [comment]
The `textarea`'s font must be the same of other inputs.

**Comment by ggazzo** [comment]
@savish28 duplicated of #13328 but really thanks for your time

**Pull request closed without merging**
