### PR TITLE
[IMPROVE] Improve the add user drop down for add a user in create channel modal for UserAutoCompleteMultiple

### LINKED ISSUE #21474: Create channel - username and alias is not presented on add users dropdown
### Description:

After upgrade to 3.13.0 nickname and username are not presented on `Add Memebers` dropdown during `Create Channel`. It is confuisng in case when two people have same first and last name. Is it possible to add username and nickname back?
It can be similar as during creation multi user direct message.

### Steps to reproduce:

1. Go to create `New Channel`
2. Check `Add Members` drop down
3. Username and nick name are not presented for users

### Expected behavior:

Username and nick name are presented for users

### Actual behavior:

Username and nick name are not presented for users

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0
- Operating System: Centos7
- Deployment Method: docker-compose
- Number of Running Instances: 31
- DB Replicaset Oplog: YES
- NodeJS Version: v12.21.0
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: booth
- Operating System: Windows 10

### Additional context

image

image

### PR DESCRIPTION
**Pull request by Jeanstaquet**
## Proposed changes (including videos or screenshots)

Seeing only the name of the person you are not adding is not practical in my opinion because two people can have the same name. Moreover, you can't see the username of the person you want to add in the dropdown. So I changed that and created another selection of users to show the username as well. I made this change so that it would appear in the key place for creating a room and adding a user.

Before:

https://user-images.githubusercontent.com/45966964/115287805-faac8d00-a150-11eb-871f-147ab011ced0.mp4

After:

https://user-images.githubusercontent.com/45966964/115287664-d2249300-a150-11eb-8cf6-0e04730b425d.mp4

## Issue(s)

Fixes #21474
## Further comments

Let me know if you want other changes

### CODE REVIEW

**Comment by emikolajczak** [comment]
Hi,
Any chance to move this fix https://github.com/RocketChat/Rocket.Chat/pull/21649 into release version?

**Comment by ankar84** [comment]
Nice improvement!

**Review by ostjen — APPROVED** [review]
nice improvement! lgtm

**Comment by ivans-netto** [comment]
Hey @Jeanstaquet I'm designer at Rocket.Chat and I'd like to thank you for you contribution.

**Comment by casalsgh** [comment]
There were some conflicts. This item was edited and added into a new PR: https://github.com/RocketChat/Rocket.Chat/pull/23766

**Pull request closed without merging**
