### PR TITLE
Fix url parse on markdown formatted urls

### PR DESCRIPTION
**Pull request by jf-guillou**
#1857 allowed wider fragment matches, but breaks auto url embed with markdown urls. See #2034

This pr attemps to improve this behaviour.

**Previously :**
```javascript
"[stream](https://www.twitch.tv/stream)".match(/([A-Za-z]{3,9}):\/\/([-;:&=\+\$,\w]+@{1})?([-A-Za-z0-9\.]+)+:?(\d+)?((\/[-\+=!:~%\/\.@\,\w]+)?\??([-\+=&!:;%@\/\.\,\w]+)?#?([^\s]+)?)?/)
```
    https://www.twitch.tv/stream)

**With this pr :**
```javascript
"[stream](https://www.twitch.tv/stream)".match(/([A-Za-z]{3,9}):\/\/([-;:&=\+\$,\w]+@{1})?([-A-Za-z0-9\.]+)+:?(\d+)?((\/[-\+=!:~%\/\.@\,\w]+)?\??([-\+=&!:;%@\/\.\,\w]+)?(?:#([^\s]+))?)?/)
```
    https://www.twitch.tv/stream

**Fragments still works :**
```javascript
"https://www.twitch.tv/stream#with/fragment".match(/([A-Za-z]{3,9}):\/\/([-;:&=\+\$,\w]+@{1})?([-A-Za-z0-9\.]+)+:?(\d+)?((\/[-\+=!:~%\/\.@\,\w]+)?\??([-\+=&!:;%@\/\.\,\w]+)?(?:#([^\s]+))?)?/)
```
    https://www.twitch.tv/stream#with/fragment

**But markdown format with fragments are still failing :**
```javascript
"[stream](https://www.twitch.tv/stream#with/fragment)".match(/([A-Za-z]{3,9}):\/\/([-;:&=\+\$,\w]+@{1})?([-A-Za-z0-9\.]+)+:?(\d+)?((\/[-\+=!:~%\/\.@\,\w]+)?\??([-\+=&!:;%@\/\.\,\w]+)?(?:#([^\s]+))?)?/)
```
    https://www.twitch.tv/stream#with/fragment)

I cannot find a way to correctly handle this case since parenthesis are allowed in fragments

### CODE REVIEW

**Comment by rodrigok** [comment]
I think we can ignore the `)` in fragments, so you can change `(?:#([^\s]+))?` to `(?:#([^\s\)]+))?`

**Comment by jf-guillou** [comment]
Got to admit that `)` in fragments is rare enough to be ignored

**Comment by rodrigok** [comment]
LGTM

**Comment by engelgabriel** [comment]
LGTM

**Pull request merged**
