### PR TITLE
Fix: Custom fields not showing on user info panel

### PR DESCRIPTION
**Pull request by ggazzo**
@RocketChat/core 
@juliagrala 

before:
image

after:
image

### CODE REVIEW

**Comment by kaiiiiiiiii** [comment]
I closed my PR in favor of this one, because your solution looks a bit smoother :)
#9646

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JSzaszvari** [comment]
@ggazzo can you post what exactly you have in your "Accounts -> Custom Fields to Show in User Info" & "LDAP -> User Data Field Map" sections to make this work please?

Even after testing this PR i'm unable to get any custom fields to display

**Comment by kaiiiiiiiii** [comment]
@JSzaszvari I've posted an explanation how the custom fields configuration should work in an issue the other day. You may want to have a look:
https://github.com/RocketChat/Rocket.Chat/issues/9763#issuecomment-366533538

**Comment by JSzaszvari** [comment]
@kaiiiiiiiii Thank you very much, thats amazing. Now I've got them showing up. Just need to work out how to populate the fields from AD/LDAP now. Have you tried this?

**Comment by geekgonecrazy** [comment]
@kaiiiiiiiii Would you mind creating a PR in our documentation for this?  I can imagine it'd help a lot of others out as well. :+1:

**Comment by JSzaszvari** [comment]
I was just about to suggest the same thing. @kaiiiiiiiii Happy to do this if you'd like otherwise i'll leave the honors with you.

**Comment by JSzaszvari** [comment]
@kaiiiiiiiii Actually, looks like i just figred it out. THanks for your help in the message above. Invaluable advice. 

If you want to submit a PR for that side, I can do the Populating from LDAP side?

**Comment by kaiiiiiiiii** [comment]
I can do that, no worries :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ggazzo** [comment]
@kaiiiiiiiii I didnt see or solution before, sorry about that, but the most important its working now ;)

**Comment by ggazzo** [comment]
@JSzaszvari  

`[{ label : key }...]`
image

**Comment by suvarov** [comment]
Hey guys!

I was wondering if this works in 0.61.0. 
Tried to add simple custom field in Accounts -> Custom Fields section:
`{
"department": {
  "type": "text",
  "required": true,
  "minLength": 2,
  "maxLength": 10
 }
}`
and added "department" in Accounts -> Custom Fields to Show in User Info
but nothing happens when I review user profiles including my own.

any advice where in what direction I should look for the answer?

**Comment by kaiiiiiiiii** [comment]
@suvarov Customer user fields do not work in 0.61.x, but it will be fixed in 0.62.0.

**Comment by suvarov** [comment]
@kaiiiiiiiii thnx!

**Comment by piotrkochan** [comment]
@kaiiiiiiiii this does not work for me on 0.69.1. Users does not have these options visible in profile-edit page as in profiles itself.

**Pull request merged**
