### PR TITLE
[NEW] Indicate the Self DM room

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

clipboard - 22 de dezembro de 2017 17-04

### CODE REVIEW

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/9234

**Comment by rodrigok** [comment]
@engelgabriel ??

**Comment by engelgabriel** [comment]
Would this solve https://github.com/RocketChat/Rocket.Chat/issues/3886 ?

**Comment by rodrigok** [comment]
No, that was already solved, I'm just adding a `tag` to the room with yourself

**Pull request merged**
