### PR TITLE
Remove auto-generated directory

### PR DESCRIPTION
**Pull request by paulproteus**
This commit removes a directory that is automatically created
as part of doing `vagrant-spk up`.

### CODE REVIEW

**Comment by paulproteus** [comment]
Hi @Sing-Li,

Humbly requesting your approval of this patch into the `sandstorm-port-001` branch!

**Comment by geekgonecrazy** [comment]
@paulproteus perhaps this needs also added to the gitignore file?

**Comment by paulproteus** [comment]
+1, will add to `.gitignore`

If it's OK, I'll add a separate `.sandstorm/.gitignore` containing this.

**Comment by geekgonecrazy** [comment]
@paulproteus that sounds reasonable to me. :+1:

**Comment by geekgonecrazy** [comment]
@paulproteus thanks for this!

**Comment by Sing-Li** [comment]
@paulproteus   no need to be humble around here :smile:   :+1:

**Comment by paulproteus** [comment]
Y'all are very kind!

**Pull request merged**
