### PR TITLE
adding octicons for the right tab pane

### PR DESCRIPTION
**Pull request by leefaus**
@geekgonecrazy can you confirm this is working?

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
This definitely works.   Also to note:  This adds Github Enterprise support.

**Comment by geekgonecrazy** [comment]
### Octicons
This adds font octicons

#### Normal Icon set

image

#### Chatops buttons

image

#### Expanded / Active State

image


### Github Enterprise

image

**Comment by rodrigok** [comment]
@leefaus this adds the github enterprise package too, right?

**Comment by leefaus** [comment]
@rodrigok that is correct!

**Comment by rodrigok** [comment]
LGTM

**Comment by leefaus** [comment]
@rodrigok @geekgonecrazy 

I don't have write access so I can't do the merge.  Can we :ship: these changes?

**Comment by rodrigok** [comment]
@leefaus sure :smile:

**Pull request merged**
