### PR TITLE
Livechat visitor info tabbar

### PR DESCRIPTION
**Pull request by sampaiodiego**
Adding more visitor information on right tab bar:

image

### CODE REVIEW

**Comment by shtefcs** [comment]
I am using Livechat feature on daily basis. I get contacted by ~10-15 people every day.

What I really missing in that visitor sidebar information, is to see from what country he is coming and what is his referral domain. 

It's mean alot to be able to bring better decisions and conversations with potential customer.

What you think guys ?

**Comment by engelgabriel** [comment]
@sampaiodiego have been working on this features. Your site can nos pass some custom variables to be displayed on the info tab.

**Comment by engelgabriel** [comment]
See https://rocket.chat/docs/master/server-management/livechat

**Comment by shtefcs** [comment]
I noticed you removed OS, IP from live chat users tab.


Checked the link you sent, but to me with, it's not mean a lot cause I am not developer.

Can you help to return that and add fields like Country, , referral ?

**Comment by sampaiodiego** [comment]
this was unintended @shtefcs .. I'm already fixing it.. thx

**Pull request merged**
