### PR TITLE
[FIX] Change wording to start DM from info panel

### PR DESCRIPTION
**Pull request by bryandesrosiers**
Minor word change from "Conversation" to "Direct Message". To keep UI consistency with the left side bar.

@RocketChat/core 

Closes #ISSUE_NUMBER

### CODE REVIEW

**Comment by HammyHavoc** [comment]
Nice catch! This was a little difficult figuring out initially; ended up using group channels to begin with until I discovered this.

**Comment by geekgonecrazy** [comment]
I would tend to agree.  @RocketChat/core  I know this is part of our new redesign also.  

Opening a `Conversation` doesn't hold consistent with us calling them `Direct Messages` in channel list.

Should we change it to `Direct Message` ?  I personally think its clearer

**Comment by sampaiodiego** [comment]
I agree. But the new UI is already touching this area, so I would say to opening a PR against the new branch..

Also, there is no translation for `"Direct Message"`, so that will be needed as well..

**Comment by geekgonecrazy** [comment]
@bryandesrosiers @HammyHavoc what do you guys think in context of new UI?

image

**Comment by HammyHavoc** [comment]
"Conversation" isn't a verb, "Video Call" is; with that in mind, "Direct Message" makes far more sense. :- ) Looking good though lads, really pretty UX! 👍

**Comment by geekgonecrazy** [comment]
Hm.. maybe "Start Conversation" ?  

@karlprieb @arthurgiustina This is a design thing.  :)

**Comment by HammyHavoc** [comment]
I could get behind that idea if we're also going to change 'Direct Messages' elsewhere to 'Conversations'. :- ) Loving the direction things are going; consistency!

**Pull request merged**
