### PR TITLE
[NEW] Message read receipts

### LINKED ISSUE #3411: read receipts?
Your Rocket.Chat version: (make sure you are running the latest) 31

Is there any way to tell if a Rocket.Chat message has actually been read by the recipient?

### PR DESCRIPTION
**Pull request by sampaiodiego**
Closes #3411 

With this PR I'm proposing a new folder structure for features/packages, using new [Meteor proposal](https://guide.meteor.com/structure.html) as well ES2015 imports.
Please let me know what y'll think on this.

About the feature, it starts disabled by default, if enabled it will add a gray `check` on every message. If it was read by everyone on the room it will turn blue.

There is another setting (also disabled by default) that will start storing the read time of everyone. So you'll be able to see the message's read receipts by looking at the `Message info` message action.

Please advice on settings label and description, I'm not sure they are clear enough.

## Settings
image

## Check marks detail
The blue one means read by everyone.
image

## New message action to see message info
image

## Message info modal
image

### CODE REVIEW

**Comment by sampaiodiego** [comment]
the PR is ready for merge, I would like to have @RocketChat/core eyes on it pls :smiley:

**Comment by geekgonecrazy** [comment]
My only dislike is visual.  It seems like putting this there would lead to it being very noisy.  

Could it maybe be next to time stamp?  Maybe on grouped messages could actually show up on hover like the timestamp does? 

That or right justify it to be in a more consistent place?  Imagine every message length is different, the check marks will be all over the page. 

Also perhaps a bit smaller?

**Comment by sampaiodiego** [comment]
> My only dislike is visual. It seems like putting this there would lead to it being very noisy.

this is how @arthurgiustina designed. I kind of agree with you, but not sure where it should be.

> The other thing is next to join messages those don't seem to be getting updated. So maybe need a way to not apply read receipts to messages based on something in message type definition?

I'll have to give this a look, thx

**Comment by sampaiodiego** [comment]
what do you guys think on having a permission to enable seeing read receipts from other persons? the default might be only for admins, owners and moderators but this would allow people to have more control on this.

so the default would be you can see read receipts for your own messages only, but admins/owners/moderators can see every ones.

**Comment by sampaiodiego** [comment]
@geekgonecrazy I've changed a few things, please let me know what you think =)

- check marks are now a bit smaller and on the right, they also turn blue when read by everyone
- detailed read receipts are under a new message action `Message info`

**Comment by geekgonecrazy** [comment]
I'm not sure why that blue is so satisfying.  But I like it.  Not sure about placement. 🤔 

For some reason it not long shows up on my own messages.  I wonder if it should only even actually show on own messages? Or maybe configurable.

**Comment by graywolf336** [comment]
@sampaiodiego glad to see I'm not the only one who has started to use the new es6 features for packages 😉 #nomoreglobals

**Comment by rafaelks** [comment]
@sampaiodiego Since we're going to implement this feature on the mobile apps, is this new property `unread` being returned into the message objects (REST and RealTime) API already when the feature is enabled?

Also, could you please work on a new REST API that returns the return of the new Meteor method `getReadReceipts` @MarcosSpessatto?

**Comment by MarcosSpessatto** [comment]
For sure! @rafaelks

**Comment by MarcosSpessatto** [comment]
@rafaelks, see #9907 please.

**Comment by mrqbmrqb** [comment]
@sampaiodiego @MarcosSpessatto Is there any way to know whether the message is delivered or not?

**Comment by sampaiodiego** [comment]
@mrqbmrqb no there is not.

**Comment by dcook1313** [comment]
I know this thread is older but I was curious if this feature of knowing when people read the message was ever implemented?  If so is it available in the free version or just the paid version?  thank you.

**Comment by sampaiodiego** [comment]
@dcook1313 yes it was. you have to enabled it from Admin panel, `Message` menu and then `Show Read Receipts` option.

**Comment by dcook1313** [comment]
Thank you very much Diego. :)

**Comment by dcook1313** [comment]
thank you Diego. :)

**Comment by GoetheG** [comment]
Shouldn't this issue be merged with all the other same isses? Cause this error still occurs with the latest version.
#4957
#15656
#15484

**Pull request merged**
