### PR TITLE
[Fix]  Check For Undefined Room in Hooks ( #24273 , #24282 , #24283)

### PR DESCRIPTION
**Pull request by samad-yar-khan**
-  [x] I have read the Contributing Guide - https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
  -  [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
  - [x] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  -  [ ] I have added necessary documentation (if applicable)
  - [x] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

 

- I have added a check for undefined room in useAppsContextualBar hook which stops an undefined object from destructuring.

## Issue(s)

Fixes : #24273 ,  #24283 , #24282
## Steps to test or reproduce

Mentioned in the Issues

# 1) Issue #24273 

## Before : 

https://user-images.githubusercontent.com/70485812/150815310-c19c3d6d-7d7b-4fc6-ad11-3d99253f6208.mp4

## After : 

https://user-images.githubusercontent.com/70485812/150815364-1c58c786-5e67-489a-b69c-65654f1affe1.mp4

# 2) Issue #24282 

## Before : 

https://user-images.githubusercontent.com/70485812/150969621-6d54ae08-e6f8-4465-8360-2e33c02cde62.mp4

## After : 

https://user-images.githubusercontent.com/70485812/150971562-475dd3c5-81d7-4e89-9820-1f71a80afcd2.mp4

# 3) Issue #24283 

## Before

https://user-images.githubusercontent.com/70485812/150970534-466c80e5-1283-47df-b1ca-dd0bcf3646dc.mp4

# After 

https://user-images.githubusercontent.com/70485812/150971838-2ef21681-b4c3-45f2-9e4a-eadfc5b9be8a.mp4

### CODE REVIEW

**Comment by samad-yar-khan** [comment]
@d-gubert @debdutdeb  Can you guys please have a look at this once. The issues are present on https://open.rocket.chat/  as well.

**Comment by debdutdeb** [comment]
[this](https://github.com/RocketChat/Rocket.Chat/pull/24272/files) probably fixes the issue. 

Not sure, @gabriellsh can you please take a look?

**Comment by samad-yar-khan** [comment]
> [this](https://github.com/RocketChat/Rocket.Chat/pull/24272/files) probably fixes the issue.
> 
> Not sure, @gabriellsh can you please take a look?

@debdutdeb I will try to run the code written by @gabriellsh  on that PR on my development server and see if it solves the issue. Although the solution which I proposed in my PR works for all of these issues as well.

**Comment by samad-yar-khan** [comment]
> [this](https://github.com/RocketChat/Rocket.Chat/pull/24272/files) probably fixes the issue.
> 
> Not sure, @gabriellsh can you please take a look?

@debdutdeb I just checked, the PR you mentioned above fixes the issues as well and seems like a better solution :)

**Pull request closed without merging**
