### PR TITLE
Change role from user edit flyout

### LINKED ISSUE #3656: Change role from user edit flyout
Feature request / improvement
Admins should be able to change a user's role from the user flyout panel, instead of having to go through permissions. This would address a couple issues:
1. It's not intuitive that the permissions edit screen is where you would change a user's role. Even being pretty familiar with RC now, it took me a long time to track that down.
2. When creating a user, it's easy to accidentally select the wrong role from the drop down. So it should be easy to follow up creating a user with editing those details to correct any mistakes.

On that last point, it might be cause for another bug report, where I've seen a different role selected as default on consecutive user creation (e.g. create first user, gets assigned 'user' by default, next time I make a user, 'livechat-agent' is the default selection). That causes even more confusion when you can't easily change or even check the user's role after creation.

We will work on developing and submitting this solution, but I'm reporting it for the future PR and in case anyone else is interested.

Related to #1629, would be enhanced by #3057.

### PR DESCRIPTION
**Pull request by Ethaan**
@RocketChat/core 

Closes #3656

This issue is related to the issue #3656 and let the admins edit roles on the user panel

### CODE REVIEW

**Comment by rodrigok** [comment]
@marceloschmidt can you review this?

**Comment by marceloschmidt** [comment]
@sampaiodiego you added the role field to user creation. What do you think about having it on edit? One problem I can immediately see is that you may have multiple roles, instead of only one. And also the roles that are subscription based (maybe we should limit to setting user-based roles). Still, the multiple roles problem stand.

**Comment by marceloschmidt** [comment]
I think we should make some changes in this regard. Having a list of user-based roles and allowing to select multiple instead of one is a start.

**Comment by graywolf336** [comment]
I agree with @marceloschmidt :+1:

**Comment by Ethaan** [comment]
Add a new PR to keep a work on this PR that should close #3679, which disabled the roles dropdown when the flexbox if for edit user and the app have just 1 admin with this we avoid letting the system with 0 admins.

Also it checks if the user have access to assign or create user with admin role

and on the other hand it doesn't show roles which are "channels" scope like `Moderator`

**Comment by graywolf336** [comment]
Closing this pull request as it was implemented via #7309. :)

**Pull request closed without merging**
