### PR TITLE
[FIX] Error in permission check for getLivechatDepartmentByNameOrId method in Apps

### PR DESCRIPTION
**Pull request by d-gubert**
## Proposed changes (including videos or screenshots)

Update the Apps-Engine with a fix for the permission check on the `getLivechatDepartmentByNameOrId` method

### CODE REVIEW

**Comment by smcnairn99** [comment]
We like / need this!  Thank you.  Look forward to it being merged. :)

**Comment by murtaza98** [comment]
Hello @d-gubert @sampaiodiego I tested this PR and the new changes looks good. I'm no longer getting the permission denied error. Thanks :smile:

**Comment by d-gubert** [comment]
@murtaza98 we had this comment from the community about an issue https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/429#issuecomment-872217953 - have you noticed any problems similar to that?

**Comment by murtaza98** [comment]
> @murtaza98 we had this comment from the community about an issue [RocketChat/Rocket.Chat.Apps-engine#429 (comment)](https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/429#issuecomment-872217953) - have you noticed any problems similar to that?

Yups I faced this same issue today while testing and I was a le to fix it via this PR PR: https://github.com/RocketChat/Rocket.Chat/pull/22587

**Review by sampaiodiego — APPROVED** [review]

**Pull request merged**
