### PR TITLE
[NEW] Move administration links to an exclusive kebab menu

### PR DESCRIPTION
**Pull request by filipemarins**
## Proposed changes (including videos or screenshots)

Move administration links to an exclusive kebab menu.

Screen Shot 2022-09-14 at 02 59 03

## Further comments

Also removed the gold license from the upgrade tab conditional since we no longer commercialize this license.

The App link was split into `Marketplace` and `Installed`.

The Administration link was split into `Manage Workspace` and  `Workspace settings`.

New button `upgrade` was added.

### CODE REVIEW

**Review by hugocostadev — DISMISSED** [review]

**Review by hugocostadev — APPROVED** [review]

**Review by hugocostadev — DISMISSED** [review]

**Review by MartinSchoeler — DISMISSED** [review]
Tested it and functionality wise, all Omnichannel items are working fine.

**Review by ggazzo — CHANGES_REQUESTED** [review]
image
I'm wondering if this section makes sense , since settings belongs to administration and there is only one item

**Comment by filipemarins** [comment]
> image I'm wondering if this section makes sense , since settings belongs to administration and there is only one item

I believe it was a design decision after I talked with the product team and the idea was to split these admin section.

**Review by ggazzo — APPROVED** [review]

**Comment by chotaire** [comment]
This was a semi-optimal idea. https://github.com/pbaity/rocketchat-dark-mode/issues/199

**Pull request merged**
