### PR TITLE
chore: better instant to call `getCachedSupportedVersionsToken.reset()`

### PR DESCRIPTION
**Pull request by ggazzo**

### CODE REVIEW

**Review by sampaiodiego — APPROVED** [review]

**Comment by ggazzo** [comment]
backport 6.5.6

**Comment by ggazzo** [comment]
/backport. 6.6.7

**Comment by ggazzo** [comment]
/backport. 6.6.7

**Comment by ggazzo** [comment]
/backport. 6.6.7

**Pull request merged**
