### PR TITLE
Search full name

### LINKED ISSUE #1209: Ability to have "Display Name" which is different from username.
This is especially helpful if you are utilizing a corporate LDAP/Active Directory which is setting your username to some obscure alphanumeric combination.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27616256-ability-to-have-display-name-which-is-different-from-username?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #4618: Only possible to use username in CTRL+P dialog to switch to private chat.
In the versions before it was possible to switch to a private chat in CTRL+P dialog by typing first or last name of user. Now it's only possible with username. Can I change this in settings? Is it a bug? Or is it meant to behave like this?

Really missing the possibility to use first or last name.

Your Rocket.Chat version: 0.42

### PR DESCRIPTION
**Pull request by marceloschmidt**
@RocketChat/core 

Closes #1209
Closes #4618

Related to #874
Related to #4210
Related to #3851

This PR standardizes displaying of usernames + name (when enabled in Accounts section of Admin)

**Accounts setting:** 
Accounts setting turned off

**Autocomplete with setting OFF**
Autocomplete `@`

**Spotlight search with setting OFF**
Spotlight search

**Create direct message with setting OFF**
Create direct message with setting OFF

**Autocomplete with setting ON**
Autocomplete with setting ON

**Spotlight search with setting ON**
Spotlight search with setting ON

**Create direct message with setting ON**
Create direct message with setting ON

### CODE REVIEW

**Comment by rodrigok** [comment]
@marceloschmidt What happens when the result of search is based on usernames from messages (user autocomplete) and users are based on room's name (spotlight)?

**Comment by rodrigok** [comment]
This search will return names only when the data came from server.
Some results will have name (results from server) and others will not (results from client)

This will half work, and probably will cause confusion.

**Comment by marceloschmidt** [comment]
I think there are a few reasons why this PR should be approved. For starters, it's a setting that can be enabled/disabled. If disabled, there's no change on current functionality. Second, if someone searches by username, there's no impact, except that they will see some users' names; and if someone searches by name, they get the advantage of finding who they are looking for. The only names they won't see are the names belonging to users that have a message/subscription loaded... And I don't think that's a major drawback that justifies not approving this PR. If it can be improved later on, the better... but while it can't, I'd merge it.

**Comment by aggregat4** [comment]
Any chance this is going to get resolved? Real name search is unbelievable useful in corporate settings.

**Comment by subesokun** [comment]
@marceloschmidt @rodrigok @engelgabriel I'd also like to ask if there is any chance that this feature gets merged soon. As mentioned in #4210 our users are strongly requesting a better LDAP integration. The current LDAP integration might cause that Rocket.Chat fails in enterprise environments as most enterprises have only cryptic user names and hence Rocket.Chat will be very hard to use :( Not sure how long I can keep our users waiting but I really want to avoid switching to another chat platform because I really do like Rocket.Chat.

**Comment by marceloschmidt** [comment]
@rodrigok @engelgabriel are you guys not going to merge this? if not, let's close it... are there change requests?

**Comment by graywolf336** [comment]
I think it should be merged 🤔

**Comment by subesokun** [comment]
@marceloschmidt Can this PR be merged as soon as the merge conflicts has been solved? That would be awesome :)

**Comment by albert-the-creator** [comment]
@marceloschmidt this is great, Good job!! can't wait to use it.

**Comment by Franziskus1988** [comment]
@engelgabriel @rodrigok As the others already stated this is a sensible improvement. Rocket.Chat is currently under testing in my company and this is a feature many would like to see. So why is this issue ignored (for nearly 3 month)

**Comment by danpospisil** [comment]
Please add this soon as this is a must have for us as we use 3 letters abbreviations for users which we have in full name from LDAP (in form of "XYZ | Real Name"} but users are not able to search by them.

**Comment by engelgabriel** [comment]
@marceloschmidt @rodrigok is this worth solving the conflicts?

**Comment by subesokun** [comment]
Due to our cryptic LDAP usernames and the recently improved search bar (which is great) in RC it's now almost impossible to start a new conversation with somebody you didn't chat yet if you don't ask him (e.g via phone) for his username :( So this makes things recently quite complicated. Hence I'd really appreciate this feature.

**Comment by antgel** [comment]
@engelgabriel I'd say it's well worth solving the merge conflicts, we too need this one. :)

**Comment by marceloschmidt** [comment]
@engelgabriel @rodrigok I don't think it's worth solving conflicts. We don't have a spotlight search anymore and the "add users to room" field already displays user names. 

@subesokun @antgel how do you think this PR would benefit you? is there anything else we can do to improve your experience (assuming you have tested our latest version)?

**Comment by subesokun** [comment]
@marceloschmidt my issue with the search has been solved via https://github.com/RocketChat/Rocket.Chat/commit/4f54238c156c99f130132284f82134f668c5082c from @alexbrazier 👍

**Pull request closed without merging**
