### PR TITLE
Add livechat package as default

### PR DESCRIPTION
**Pull request by sampaiodiego**

### CODE REVIEW

**Comment by sampaiodiego** [comment]
- asdf
- asdf
- asdf

**Comment by skyred** [comment]
I ran:
````
docker run --name db -d mongo --smallfiles
docker run --name rocketchat -p 80:3000 --env ROOT_URL=http://localhost --link db -d rocketchat/rocket.chat
````

But, then ran into this error:
````
/app/bundle/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: failed to connect to [mongo:27017]
    at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /app/bundle/programs/server/packages/accounts-base.js:1814:4
    - - - - -
    at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
    at process._tickCallback (node.js:448:13)

````

I am not sure what went wrong.

**Comment by sampaiodiego** [comment]
@skyred the docker image from rocket.chat expects a link to `mongo` not `db`.. so you can run with:
`docker run --name rocketchat -p 80:3000 --env ROOT_URL=http://localhost --link db:mongo -d rocketchat/rocket.chat:develop`
I added the tag `develop` to rocket.chat image so you can use the livechat ;)

**Comment by sampaiodiego** [comment]
oh, I'm sorry @skyred .. seems that our `develop` image docker tag was not built on the last merges.
I'll check with @Sing-Li what happened.

**Pull request merged**
