### PR TITLE
Improved performance of sidebar rendering. Fixed RTL sidebar opening.

### PR DESCRIPTION
**Pull request by Igloczek**
@RocketChat/core 

I moved rendering of sidebar, main content and "burger" blocks to new composite layers using `will-change`, which improve performance of open/close animations and overall rendering performance.

I removed some global classes, b/c applying them forces browser to unnecessary layout calculations on child elements. Now it use same method as in swiping (just operate on the numbers directly on selected elements) to open sidebar. Previously go get state of menu, we have to check if some element has an class, right now it's reactive, based on `Session` object and it's used also to set `menu-opened` class to 🍔 element (synchronizing DOM Ready events of few async modules it's kinda tricky, I'm not sure how to handle it).

I changed also a way of animating 🍔  icon, replacing not so fast `width` based translations, with pure transforms solution.

I fixed also sidebar opening for RLT lang users, b/c was totally broken.

Tested on Chrome with 5x CPU slowdown, previously min fps was like 10-15, now it's almost stable 60fps - there are still some minor (AFAIK) Meteor related performance issues related to event listeners, but currently I have no idea how to fix it 😞

### CODE REVIEW

**Comment by engelgabriel** [comment]
@Igloczek thanks for the amazing contribution! This is the kind of front end expertise that we need :)

I have tried to run your branch on my local machine, but I am getting a layout error as below:

image

Do you have any idea about what can be pushing the flex-tab to the middle?
It is worst on wider screens.

**Comment by engelgabriel** [comment]
image

**Comment by Igloczek** [comment]
Ops 😉 Fixed.

BTW. Are you open for wider changes in front-end area? Working with layout based on nested  `position: fixed` blocks it's painful and might be related to poor performance in some cases.

**Comment by engelgabriel** [comment]
@Igloczek we are you open for wider changes in front-end area :) there is A LOT of room for improvement. I am "recruiting" a team of talented contributors to in a private group to discuss our UX future, and I'd love to have you on board :)

I'll contact you at our demo server, I presume you are using the same username.

**Comment by engelgabriel** [comment]
@timkinnane and @karlprieb do you guys have any comments on this PR?

LGTM, but I am not an expert :)

**Comment by timkinnane** [comment]
LGTM. I haven't looked into the layout transitions much but I can definitely confirm that nested `position: fixed` is always a pain.

**Comment by karlprieb** [comment]
LGTM too.
We need to be careful using ``will-change`` in too many elements in the future, but it's ok for this PR :) 👍 

Using ``will-change`` in many elements will use a lot of machine resources and can slow down the page.

**Pull request merged**
