### PR TITLE
[NEW] Markdown Color Support - Redone for new code structure.

### LINKED ISSUE #7009: Feature: IRC Color Support
It would be nice to have (m)IRC Color support in webhooks. This way I can color code parts of text, instead of the whole thing.

### PR DESCRIPTION
**Pull request by ellisgl**
@RocketChat/core 
Closes #7009

Creates markdown syntax for IRC colors: {color fg:red bg:yellow}text{/color} or full hex: {color fg:#FF0000 bg:#FFFF000}text{/color}. Also can be used with only forground (fg), or background only (bg). You can select between none, IRC 16 color support (named), or full (IRC and hex) in the markdown settings.

Screen shot: 
capture

#

### CODE REVIEW

**Comment by ellisgl** [comment]
@graywolf336 any change requests?

**Comment by ellisgl** [comment]
Ah, the updated main development branch is borked...

**Comment by ellisgl** [comment]
1ytqjq

**Comment by ellisgl** [comment]
OK, I just donated a dollar! Now will someone please review this!

**Comment by graywolf336** [comment]
I'm going to take a look at it this week and try to get you an answer from someone soon.

**Comment by ellisgl** [comment]
It been 3 years, so I'm going to just delete the PR.

**Pull request closed without merging**
