### PR TITLE
[FIX] Overflowing buttons in Preferences section

### LINKED ISSUE #16937: Overflowing buttons in Preferences section
### Description:
The content of the buttons in 'My Data' section are overflowing in the mobile view.

### Steps to reproduce:

1. Start the development server
2. Go to My Account
3. Select Preferences

### Current behavior:
mydata

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0-develop 
- Operating System: linux
- NodeJS Version: 12.16.1 - x64
- MongoDB Version: 4.0.6

### PR DESCRIPTION
**Pull request by Nikhil713**
Closes #16937 

The height of the buttons have been adjusted so that the text fits

mydatacorrected

### CODE REVIEW

**Comment by gabriellsh** [comment]
What if instead of increasing the buttons height, we just put them one below the other? I think it would look better like that. What's your opinion?.

Also, please merge your branch with the most current develop. Thank!

**Comment by Nikhil713** [comment]
It does look better when the buttons are aligned vertically. I've made the necessary changes for the same:
mydatafinal

**Comment by Nikhil713** [comment]
@ggazzo I've removed the ids and used the `white-space:nowrap;` property.

**Comment by danger89** [comment]
LGTM

**Comment by Nikhil713** [comment]
@ggazzo Could you please check if it's fine now?

**Comment by ggazzo** [comment]
sorry for the delay , as you can see we have written the whole page in react, any problem please let me know, and thanks for your time

**Pull request closed without merging**
