### PR TITLE
move create channel icon to toolbar

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Create channel icon was moved to toolbar and `channels` and `listChannelsFlex` was removed since we only use `combined` and `listCombinedFlex`.

### CODE REVIEW

**Comment by graywolf336** [comment]
It's not clear from the gif on how to create a direct message with someone here

**Comment by rodrigok** [comment]
@graywolf336 You need to search for the user using the search field on top and the room will be created when you select the user.

**Comment by TheReal1604** [comment]
@rodrigok wow, this ui change is really hard for our users . (especially for creating a private chat!) Maybe this could improved in such way..? but atm i have no idea :/

**Comment by graywolf336** [comment]
@karlprieb @rodrigok @engelgabriel this pull request broke the UI when you don't have your channels merged. I no longer can see **channels** at all except those I have favorited.

**Comment by karlprieb** [comment]
@graywolf336 Thanks for report!
I fixed this problem here #5856 :)

**Comment by Nosferous** [comment]
Creating Direct Messages is a pain now for my users. While we understand how the function works, it just doesn't work as well. Particularly searching for a user is clumsy and very specific. Before you could search either first, last name or username and accurate suggestions would pop-up immediately. Similar to how it does now when creating a private group channel and selecting Users. That still works OK. But direct messages- not really. It is so bad it has halted the rest of my deployment to the remaining departments at my company.

Current behavior with Direct Messages when you enter a first name I only get suggestions of people I've previously chatted with almost instantly. Otherwise I don't get a proper name of who I'm looking for unless I search for Last Name or Username. 95% of my user bases instinct is to search first name. They've already made a fuss about searching usernames before First/Last name searches were developed to work solidly in the add user fields before the recent server updates.

Our usernames are in the format of FLast (first initial last name). And the left side-bar interface is garbage when I search for a first name and it's trying to find a room, see screen: This is the same result whether I'm using a browser or Electron app.

screen shot 2017-02-13 at 7 54 16 am

Running Server Version 0.51.0
Hosted on an Ubuntu 16.04 LTS

Behavior is the same in Browser and Electron App version  2.4.0 (which I would expect as this is a server code issue not electron app).

**Comment by Nosferous** [comment]
Creating Direct Messages is a pain now for my users. While we understand how the function works, it just doesn't work as well. Particularly searching for a user is clumsy and very specific. Before you could search either first, last name or username and accurate suggestions would pop-up immediately. Similar to how it does now when creating a private group channel and selecting Users. That still works OK. But direct messages- not really. It is so bad it has halted the rest of my deployment to the remaining departments at my company.

Current behavior with Direct Messages when you enter a first name I only get suggestions of people I've previously chatted with almost instantly. Otherwise I don't get a proper name of who I'm looking for unless I search for Last Name or Username. 95% of my user bases instinct is to search first name. They've already made a fuss about searching usernames before First/Last name searches were developed to work solidly in the add user fields before the recent server updates.

Our usernames are in the format of FLast (first initial last name). And the left side-bar interface is garbage when I search for a first name and it's trying to find a room, see screen: This is the same result whether I'm using a browser or Electron app.

Searching First Name Behavior current version (not working):
screen shot 2017-02-13 at 8 01 10 am

Searching Last Name behavior (working - same fine behavior when searching username ):
screen shot 2017-02-13 at 8 02 20 am

Searching First Name in the Private Groups select Users window (this is how direct messages used to prompt quick and painlessly and how we need direct messages to work again):
screen shot 2017-02-13 at 8 03 21 am


Running Server Version 0.51.0
Hosted on an Ubuntu 16.04 LTS

Behavior is the same in Browser and Electron App version 2.4.0 (which I would expect as this is a server code issue not electron app).

**Pull request merged**
