### PR TITLE
[FIX] Dynamic popover

### LINKED ISSUE #8023: Message action popover/dropdown slides offscreen on mobile
The popover that appears when clicking the message overflow menu slides offscreen on mobile. [This video](https://shitty.download/MioQ.mp4) shows the behaviour.

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #8023 

Create popovers dynamically.

image

image

### CODE REVIEW

**Comment by sampaiodiego** [comment]
is this space above the highlight desirable?
image

looks the the search is broken again:
image

the mobile paddings seems odd:
image

**Comment by rodrigok** [comment]
Wrong status indicator alignment in Safari
image

**Comment by karlprieb** [comment]
@sampaiodiego the space above the highlight was decided by @engelgabriel 

@rodrigok Fixed status indicator on Safari

**Comment by rodrigok** [comment]
@karlprieb The animation on mobile is very slow.

image
The plus icon is unaligned and the top margin seems wrong

**Pull request merged**
