### PR TITLE
Allow LDAP user to update local user

### PR DESCRIPTION
**Pull request by colinho**
Previously, if a user successfully logged in with a LDAP username that matched an existing local username, the login would fail. Now the login will succeed (with the rationale that the user provided legit LDAP credentials) and the existing user object is updated with ldap = true.

Signed-off-by: Colin Ho <colin@colinho.com>

### CODE REVIEW

**Comment by colinho** [comment]
I believe this will fix #1912.

**Comment by colinho** [comment]
It may also fix #1823, because I speculate that what happens is the LDAP auth succeeds with the username, which fires the exception that this commit removes.

**Comment by colinho** [comment]
Also, this commit addresses the "troubleshooting" issue mentioned on the wiki here: https://github.com/RocketChat/Rocket.Chat/wiki/LDAP-Authentication#i-cannot-login-even-everything-looks-good.

**Comment by rodrigok** [comment]
@colinho thank you, your solution is great, but I think that this should be optional and can be enabled by default.

Can you add an option to disable this in settings?

**Comment by engelgabriel** [comment]
Thanks for the PR @colinho, we have added it into https://github.com/RocketChat/Rocket.Chat/pull/2167

Can you help test it?

**Pull request closed without merging**
