### PR TITLE
fix: Time format in quoted message according to user preference

### LINKED ISSUE #28863: Quotes do not honor time format settings
### Description:

The timestamp given in a quoted message does not honor time format settings (global and/or user-dependent).

### Steps to reproduce:

1. Login with an admin.
2. In Administration -> Settings -> Message, reset "Time Format" to its default value `LT`.
3. In My Account -> Preferences -> Localization, set the "Language" to "English".
4. In My Account -> Preferences -> Messages, reset the "Time Format" to "Default".
5. Write a message quoting another one.
6. Look at the timestamp of the quoted message.
7. In Administration -> Settings -> Message, set "Time Format" to `LTS`.
8. Look at the timestamp of the quoted message.
9. In Administration -> Settings -> Message, reset "Time Format" to its default value `LT`.
10. In My Account -> Preferences -> Messages, set the "Time Format" to "24-hour clock".
11. Look at the timestamp of the quoted message.

### Expected behavior:

In step 6, I would expect the timestamp to read `11:08 PM`.

In step 8, I would expect the timestamp to read `11:08:28 PM`.

In step 11, I would expect the timestamp to read `23:08`.

### Actual behavior:

The timestamp is always shown as `11:08 PM`.

Step 6:

image

Step 8:

image

Step 11:

image

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.5

### Client Setup Information

The issue seems to occur with any combination of client and operating system.

- Browser Version:
  - Chromium Version 112.0.5615.49 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 111.0.1 (64-bit)
- Operating System: Arch Linux

### Additional context

The issue is further complicated by the user's language setting. I only documented what's happening in English.

In #25034, a similar issue is reported regarding the timestamp in the sidebar.

### PR DESCRIPTION
**Pull request by ayush3160**
## Proposed changes (including videos or screenshots)

This pull request adds the time format in quoted message according to the user preference in settings.

Images for different Format settings -> 

Screenshot 2023-04-14 004135
Screenshot 2023-04-14 004355
Screenshot 2023-04-14 004636

## Issue(s)

fix #28863 
## Steps to test or reproduce

1. Login with an admin.
2. In Administration -> Settings -> Message, reset "Time Format" to its default value LT.
3. In My Account -> Preferences -> Localization, set the "Language" to "English".
4. In My Account -> Preferences -> Messages, reset the "Time Format" to "Default".
5. Write a message quoting another one.
6. Look at the timestamp of the quoted message.
7. In Administration -> Settings -> Message, set "Time Format" to LTS.
8. Look at the timestamp of the quoted message.
9. In Administration -> Settings -> Message, reset "Time Format" to its default value LT.
10. In My Account -> Preferences -> Messages, set the "Time Format" to "24-hour clock".
11. Look at the timestamp of the quoted message.

### CODE REVIEW

**Comment by ayush3160** [comment]
@hugocostadev , Can you please review this PR.

**Review by debdutdeb — DISMISSED** [review]
looking at the code, this will ignore context view of "time range differences" - as in, currently, if the quoted message was sent let's say yesterday, it'll show "yesterday", if within the week but not yesterday, it'll specify the day exactly, and so on. 

instead of this, a more appropriate fix would be to incorporate the format hook into the timeago hook.

**Comment by hugocostadev** [comment]
Hi @ayush3160 ... @debdutdeb it's correct, just a tip: 

edit the `useTimeAgo()` hook and assign the format 

```ts
const format = useSetting('Message_TimeFormat') as string;
```

to `sameDay` key

**Review by hugocostadev — APPROVED** [review]

**Comment by hugocostadev** [comment]
@ayush3160 can you resolve the conflict?

**Comment by hugocostadev** [comment]
I'll review again this PR, some changes were made

**Review by rique223 — APPROVED** [review]

**Pull request merged**
