### PR TITLE
NEW: Apps enable after install

### PR DESCRIPTION
**Pull request by d-gubert**
With this PR, apps will be automatically enabled after install, and a different text will be shown if the app is in the `INVALID_SETTINGS_DISABLED` state.

image

image

### CODE REVIEW

**Comment by reetp** [comment]
Please don't do that.
I don't want apps enabled thank you.

**Comment by d-gubert** [comment]
Hey @reetp ! So, the current behavior is, when you click `Install` in an app, said app is installed but remains disabled - which requires you to manually enable it.

The change this PR introduces is that, when you click `Install` in an app, said app is installed AND is automatically enabled - no further interaction is required.

Do you think this change is actually undesirable? We've found this new behavior to be simpler for the user. Considering you are willingly installing an app, you'd probably think you can start using it right away

**Comment by wreiske** [comment]
I prefer it this way... I can't tell you how many times I've gone in and had an enabled app actual disable itself or after restart have to manually re-enable all my apps. +1

**Comment by geekgonecrazy** [comment]
@reetp to be clear.. this is to enable individual apps after the user has chosen to install them.  

The apps engine has already always been on by default.  That in its self is not a privacy issue.  Users can choose to side load an app.  Or they can opt-in to use the marketplace.  They are never forced to do so.  If they chose to never install an app they are not negatively impacted nor their privacy impacted in anyway.

Thanks

**Pull request merged**
