### PR TITLE
Set user's name to alias in message

### PR DESCRIPTION
**Pull request by nishimaki10**
@RocketChat/core 

Related #1209

I think this solution is not perfect. However, this is easy and low cost.
I focused only to now and future messages. A message's alias not changed if a user has changed the name. But I thought that was okay anyway.

set-realname-to-alias

EDIT:
Add settings for this feature.

ss2

### CODE REVIEW

**Comment by jaredneedell** [comment]
Is this in master yet?

**Comment by hvma** [comment]
status?

**Comment by chey** [comment]
What about using @{user}
I think using @ for name auto-completion should also look at the alias in this case.

**Comment by LFCavalcanti** [comment]
@chey 
Like your idea, but in that case if there is no {name} would {user} be duplicated onto {name}?
This will happen for GitHub integration, where there is a nickname only for posting.

**Comment by chey** [comment]
@LFCavalcanti 
When typing @ to look for a user the auto-complete box that comes up should be in this format.
{user} {name}
{user} {name}
etc.
as the user types, it can match either.
when the user chooses by either clicking or hitting enter key ... the {user} field gets put in the input box
pretty simple really. only minor ui changes i would think.

**Comment by graywolf336** [comment]
@RocketChat/core Hey can we take a look at this? Will this effect performance in any way like was mentioned in #1209

**Comment by rodrigok** [comment]
This will not affect the performance, but I don't know if it's what users expect from.

1. If you change your name the old messages will keep the old name
2. The auto complete will keep showing the username only

@RocketChat/core what do you think?

**Comment by imjustfly** [comment]
I think the alias should be shown in `Members List`,  `DIRECT MESSAGES` and any area that shows users.

**Comment by rodrigok** [comment]
@imjustfly Alias is a message related thing, it's not a user property.

**Comment by bhbarbosa** [comment]
Curious to know if this will work on LDAP too, even if Alias is just used in message, it's a potential gain for environments like mine.

**Comment by richardwlu** [comment]
If we are on LDAP, how do we let users choose their own "name" so they have an alias but avoid it being in sync with LDAP; however, it is still important that email addresses/accounts sta up to date?  We currently have the User Data Field Map as `{"cn":"name", "mail":"email"}`. When I change my name from the Account settings, it gets reset back since the "Sync Data" is on. But I'm assuming we need "Sync Data" on so users can log in? Please correct me if I am wrong.

**Pull request merged**
