### PR TITLE
[NEW] code to get the updated messages

### PR DESCRIPTION
**Pull request by ggazzo**
@RocketChat/core

### CODE REVIEW

**Comment by rafaelks** [comment]
@graywolf336 Yes, please. :-)

**Comment by ggazzo** [comment]
image
@rafaelks @graywolf336 @rodrigok

**Comment by rodrigok** [comment]
@graywolf336 can you review it again?

**Comment by ggazzo** [comment]
as @rafaelks suggested I changed the REST endpoint to `chat.syncMessages` and the param name to `lastUpdate`

**Comment by rafaelks** [comment]
My suggestion was actually don't return two different types of objects on the same API and don't replicate what we have in `channels.history`. About the name, if we want to follow some pattern, could be something like: `channels.history.sync` (one per type of room).

**Comment by graywolf336** [comment]
The api method doesn't conform to the rest of the room and messages apis, there should have been something like @rafaelks said.

**Comment by rafaelks** [comment]
I agree. Will we update the name of the method, or keep the same? @graywolf336 @ggazzo @rodrigok

**Pull request merged**
