### PR TITLE
Fix overlapping windows

### PR DESCRIPTION
**Pull request by marceloschmidt**

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
You guys were able to actually reproduce this?

**Comment by marceloschmidt** [comment]
Yes @geekgonecrazy. The problem seemed to be when clicking too fast (or server to slow) between rooms, there was a problem with removing child nodes. Usually there was the loader, then the code for opening a room would remove the child nodes, but it failed to remove all children, and I'm guessing it's because the loader had already been removed or something like that. I reproduced the error by simulating the click on rooms, like this: `rooms = $(".rooms-list li a.open-room"); for (i=0; i<4; i++) { rooms.get(i).click() };` and then running the same command again, but "clicking" more rooms `rooms = $(".rooms-list li a.open-room"); for (i=0; i<8; i++) { rooms.get(i).click() };`

**Comment by IQ2022** [comment]
this happens to me every single day.. what i noticed (and can be totally wrong) is if am logged in one room for long time and then quickly go to another room or to Administration, the overlap happens.
could it be:
PC related?
Server type related (running Heroku vs others?

i was able to replicate on desktop application and on browser.

**Comment by marceloschmidt** [comment]
If you can reproduce with ease, let us merge this into develop and maybe you could try then? Thanks!

**Comment by Sing-Li** [comment]
Genius!  :+1: 

@marceloschmidt   How does removing the loader before removing the nodes fix this?

My usual way of reproducing this:

1.  upload a few huge PNGs ... as big in width and height as possible into a room 
2.  with the PNGs displaying, reload browser
3.  while those PNG are resize-reloading, keep switching rooms back and forth

Almost 100% hit rate.

**Comment by marceloschmidt** [comment]
Let me just say that I'm not 100% confident on this solution, but it has worked for me.
If you don't remove the loader beforehand, this code in here: 
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages%2Frocketchat-lib%2Fclient%2Flib%2FopenRoom.coffee#L32-L33
will try to remove it when you switch rooms. *I think* the problem is that the loader gets removed at the previous call but after the `for` has started, so a race-condition. Maybe someone else can prove this?

**Comment by IQ2022** [comment]
http://i.imgur.com/wgjSf4g.gifv

**Comment by rodrigok** [comment]
LGTM

**Comment by IQ2022** [comment]
what is LGTM?

**Comment by engelgabriel** [comment]
LGTM = Looks Good To Me

**Comment by IQ2022** [comment]
oh okay, so am guessing we found a solution?

**Comment by geekgonecrazy** [comment]
@IQ2022 we think so.  After if you are running your instance on develop, feel free to pull, and check this out.  If not, this fix will land in our next release

**Pull request merged**
