### PR TITLE
[FIX] Snippetted messages not working

### LINKED ISSUE #8585: Can't add snippet in 0.59.1
### Description:

In 0.59.1 there doesn't appear to be a way to create a Snippet.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Docker image rocketchat/rocket.chat:0.59.1
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:
0. Enable Snippet support in Administration > Message > Allow Message Snippeting
1. Create an IM post
2. Edit by clicking on the "..." button
3. Expect a "snippet" icon to be displayed, but none found

Note: I was previously using a 0.58.3 Rocket.chat database and pulled the 0.59.1 docker image and ran it on the existing data. I expected that it updated the database as needed.

Thanks

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #8585 #8809

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@karlprieb out of curiousity what's the point of adding a name with these changes?  Since looks like it no longer shows the name of the snippet :grin:

I am however glad that you don't click to see the snippet... because that view was broken majorly.

**Comment by rodrigok** [comment]
@karlprieb @geekgonecrazy Lets merge this and add the title as a FIX while in release candidate? What do you think?

**Comment by karlprieb** [comment]
@rodrigok @geekgonecrazy I'm only fixed the snippetted messages and made it work as always (without title). I can implement that, but I agree with @rodrigok  we can make on another PR.

**Comment by geekgonecrazy** [comment]
follow up issue created #9050

**Comment by ged-nn** [comment]
please, you can use the full example of using snippets.
I just can not understand how it works.
:-(

**Pull request merged**
