### PR TITLE
[FIX] Fixes Omnichannel Analytics page error (default export of chart.js was undefined)

### PR DESCRIPTION
**Pull request by belmeopmenieuwesim**
## Issue(s)

#25775

### CODE REVIEW

**Comment by belmeopmenieuwesim** [comment]
The bug is still present on that PR. We need to get rid of using .default to grab the Chart export.

**Comment by KevLehman** [comment]
maybe you need to install the deps again? how are you testing it? 👀 on develop, seems to be working fine, but let me know how you're testing it so we can work on a fix if needed
image
image

**Comment by debdutdeb** [comment]
Technically should work 👀 looking at the docs chats.js/auto exports Chart as default not as named. Therefore this pr should not be working;

**Comment by KevLehman** [comment]
yeah, per docs, you can do the import like ` { Chart } from 'chart.js'` when you're not using `/auto`. That means you have to add extra config to generate the graph, but since we were using already "light" config, auto was the choice.
And `/auto` has a `default` export for creating charts 🤗 

@belmeopmenieuwesim , let us know after you tested, and we can close this one if it works 🥳

**Comment by belmeopmenieuwesim** [comment]
Alright awesome, seems to be fine indeed using `chart.js/auto`. Hopefully a new release is being pushed soon with the current fix in `develop` :D

**Pull request closed without merging**
