### PR TITLE
fix: Fixed no role assign to manual registered users despite of Default Roles for Users settings

### LINKED ISSUE #27736: No role assign to manual registered users despite of Default Roles for Users settings
### Description:

I have defined the `guest role` on **Admin UI - Account - Registration - Default Roles for Users**
image
But when I'm creating a user though the portal doing it manual filling the form, it sends the following json to the api.
```
{"roles":[],"name":"testuser","username":"testuser","statusText":"","bio":"","nickname":"","email":"<ommited>","password":"<ommited>","verified":false,"requirePasswordChange":false,"setRandomPassword":false,"sendWelcomeEmail":true,"joinDefaultChannels":true}
```
I know that I left empty the list_box where you can choose on which roles you want to add the user but that's because I want to use the default one defined on **Admin UI - Account - Registration - Default Roles for Users**
image

### Steps to reproduce:

1. Define your default roles on **Admin UI - Account - Registration - Default Roles for Users**
2. Create a manual user through https://_yourdomain_/admin/users/new
3. Check the role of the user created

### Expected behavior:

I would like to have on my user the default role

### Actual behavior:

It creates the user but doesn't have been assigned to any role.
image

### Server Setup Information:

- Version of Rocket.Chat Server: 5.2.0
- Operating System: Ubuntu 20.04
- Deployment Method: docker-compose
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.13

### Client Setup Information

- Desktop App or Browser Version: Firefox 108.0.2
- Operating System: Ubuntu 22.04

### PR DESCRIPTION
**Pull request by bhardwajdisha**
## Proposed changes (including videos or screenshots)
Fixed no role assign to manual registered users despite of Default Roles for Users settings
changes done in apps/meteor/app/lib/server/functions/saveuser.js file and checked it on my local environment and it works fine. Please review this.

https://user-images.githubusercontent.com/67470541/223122109-95c5b7f2-3920-4376-a72d-23723dc1d31c.mp4

## Issue(s)
closes #27736 

## Steps to test or reproduce
1. Define your default roles on Admin UI - Account - Registration - Default Roles for Users
2. Create a manual user through https://yourdomain/admin/users/new
3. Check the role of the user created

### CODE REVIEW

**Comment by bhardwajdisha** [comment]
@dudanogueira Can you please review this

**Comment by hugocostadev** [comment]
That is great! Thanks for your contribution! 

What do you think to add the prefilled field role with the default role?

**Comment by bhardwajdisha** [comment]
Yes @hugocostadev, I think that will be great. 
I see you have self assigned this task to yourself, so are you working on it or should I do this?

**Comment by hugocostadev** [comment]
No @bhardwajdisha you can work on that, I only assign myself to keep track

**Comment by bhardwajdisha** [comment]
Hi @hugocostadev, I have made the changes.
Can you please review them?

**Comment by bhardwajdisha** [comment]
Hi @hugocostadev , I have made the changes.
Can you please review them?

**Review by ggazzo — APPROVED** [review]

**Pull request merged**
