### PR TITLE
[NEW] Add prometheus port config

### LINKED ISSUE #11114: Allow the Prometheus port to be configuration
**Is your feature request related to a problem? Please describe.**
Currently the Prometheus port is hardcoded to `9100` which has already allocated to the `node_exporter` in https://github.com/prometheus/prometheus/wiki/Default-port-allocations

**Describe the solution you'd like**
The port should be configurable so that if someone also deploys a `node_exporter` on the same host, the server will still work at another port.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by thaiphv**
[NEW] Allow the Prometheus port to be configurable

Closes #11114

This also picks a default port number that doesn't conflict with existing allocations from https://github.com/prometheus/prometheus/wiki/Default-port-allocations. Per the recommendation, I use the `9451` port, which is available after the one allocated to [Habitat Exporter](https://github.com/chef/habitat_exporter)

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
My only problem is this now becomes a breaking change.  Because it was released with 9100 already, so if we change the default then when people upgrade it's broken

**Comment by thaiphv** [comment]
> My only problem is this now becomes a breaking change. Because it was released with 9100 already, so if we change the default then when people upgrade it's broken
I'm OK with not setting a default value of `9100` as we haven't actually reserved any port for the service.

**Comment by thaiphv** [comment]
I've changed the default value of `Prometheus_Port` to `9100` so that it doesn't introduce a backward incompatible change.

**Comment by thaiphv** [comment]
Can someone please take a look at this change?

**Review by geekgonecrazy — APPROVED** [review]

**Pull request merged**
