### PR TITLE
[Fix] Remove quote option from DM message options

### LINKED ISSUE #14063: While DMing a user, quote and reply are the same
### Description:

While DMing a user, quote and reply option both are the same. 
So, one option can be removed.

Screenshot from 2019-04-09 15-56-50

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0 - develop

### PR DESCRIPTION
**Pull request by mohamedar97**
Closes #14063

### CODE REVIEW

**Comment by mohamedar97** [comment]
i understood from the issue that this is a problem with messages in general

**Comment by mohamedar97** [comment]
i'll do some more testing and update this

**Comment by graywolf336** [comment]
The issues states:
> While DMing a user, quote and reply option both are the same.

So, that means it is only when you are direct messaging someone.

**Comment by mohamedar97** [comment]
okay will be checking it

**Comment by mohamedar97** [comment]
i guess that was the implementation you were looking for?

**Comment by geekgonecrazy** [comment]
I'm not too sure about this change.  I think we plan to keep the ability to quote in DMs.  I know I personally use quotes a lot to respond to a message a few above.

Its great for giving context to a message.

**Comment by mohamedar97** [comment]
it's great in discussions but useless in DMs i guess, the reply options will do the same thing

**Comment by geekgonecrazy** [comment]
> the reply options will do the same thing

except that reply now does threading. :) so now it actually doesn't.

@RocketChat/core I appreciate the work here.  But, I think this one is not needed.  Thoughts?

**Comment by mohamedar97** [comment]
I was not aware of that update. I guess this PR wouldn't be the best now

**Comment by Hudell** [comment]
Closing this, since this change is no longer needed.

**Pull request closed without merging**
