### PR TITLE
Only show users of room if no view-d-room permission

### LINKED ISSUE #2588: limit autocompleting names in private channels to those in the channel
When you're in a private channel and start to type @name... it attempts to autocomplete, but it will include names of people NOT in the channel. If you're using private channels for conversations with customers, this leaks info on other customers (or employees)

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

Closes #2588

Will not work for branch `experimental` and it's a client solution only, users still can use console to request a list of other users

### CODE REVIEW

**Comment by rodrigok** [comment]
@RocketChat/core Any ideias here?

**Comment by sampaiodiego** [comment]
I don't agree with #2588

**Comment by graywolf336** [comment]
What if we added another permission, like `can-autocomplete-users-not-in-room` or something like that?

**Comment by rodrigok** [comment]
@sampaiodiego This is not exactly what that issue require, this limit the autocomplete for "guest" users

**Comment by hussamEddinAlhendi** [comment]
@rodrigok I'm thinking to start implement this in server side but I'm new on Rocket.Chat so do have any instructions to do this

**Comment by geekgonecrazy** [comment]
Fixed by #7830

**Pull request closed without merging**
