### PR TITLE
[NEW] Direct Message Quick Button

### PR DESCRIPTION
**Pull request by wreiske**
Currently this button calls `FlowRouter.go('directory');`, however, if possible I would like this to go directly to the "Users" list instead of the "Channels" list. 

My organization has been having trouble figuring out how to create new direct messages, it's not very intuitive to have to hit the directory button, then hit users, then open a direct message. Hopefully this will clear up some confusion. 

new-direct-message-button mov

If anybody knows how to make it go directly to the "Users" list in the directory, please feel free to edit this pull request or tell me how. Otherwise, this works for me for now.

### CODE REVIEW

**Comment by rodrigok** [comment]
@engelgabriel and @thiagosanchz can you evaluate the idea/request in a UI/UX perspective and decide if we want to have it and if it would need changes?

**Comment by ggazzo** [comment]
@wreiske  you can "add" a direct message using "cmd + p" or "ctrl + p" and write the users name... is it not enough?

**Comment by wreiske** [comment]
> @wreiske you can "add" a direct message using "cmd + p" or "ctrl + p" and write the users name... is it not enough?

The CMD + P only works if you have already messaged someone before. You have to go to the directory to start your first messages + search for someone by name that you haven't searched for before. 

Also, new users don't have any idea about keyboard shortcuts. They are looking for a simple way to start a new message. 

Example of how slack does it:
image

**Comment by ggazzo** [comment]
It's not true
> The CMD + P only works if you have already messaged someone before.

image

ok you got a point :)
> Also, new users don't have any idea about keyboard shortcuts. They are looking for a simple way to start a new message.

**Comment by wreiske** [comment]
Odd. Did that functionality change? I could have sworn I tested that... searching for users didn't find any. I had to go to the directory to find them. It seems to be working today, however.

Maybe the direct message button could just trigger the same thing the hotkey does?

**Comment by engelgabriel** [comment]
Thanks for the contribution @wreiske but we believe that out messages list should be cleaner, and we have removed our the BUTTONS like the plus button you are suggesting. We believe it works better when you start to have a long list of rooms that you participate in.

**Pull request closed without merging**
