### PR TITLE
[NEW] Makes shield icon configurable

### LINKED ISSUE #6989: Questions on Shields feature
Rocket.Chat Version: 0.56
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

Hi @alexbrazier I had a look at your new shields feature https://github.com/RocketChat/Rocket.Chat/pull/6565 which looks cool!

How can we change the branding and colours for the shield to use some other icon than Rocket.chat? Would be nice to have a new shield.svg included in the Assets section under Administration

### PR DESCRIPTION
**Pull request by c0dzilla**
@RocketChat/core 

Closes #6989  

This pr makes the shield icon in the shield.svg api route configurable. Desired svg image can be added in the public/images/shield/shield-icon.svg file to replace the default rocket.chat icon.

Example:
github_shield

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Ideally we want to keep it so a user never edits the local files.  It should be possible in the UI.  We have many cases where the filesystem Rocket.Chat is on is read only.

My suggestion would be to change it to actually make use of the svg icon that can be uploaded in assets: 
image

That way will make use of the very same icon used as favicon.

**Comment by c0dzilla** [comment]
@geekgonecrazy should there be a separate icon called shield in the assets ui or the favicon icon itself be used?

**Comment by geekgonecrazy** [comment]
In my opinion making use of the same exact icon would be desirable for the end user.  Less for them to have to upload and maintain.

This way they upload their logo once and its used everywhere its needed.

**Comment by c0dzilla** [comment]
Made requested changes.

**Pull request merged**
