### PR TITLE
fix: remove link appearing in quotes preview

### PR DESCRIPTION
**Pull request by jayesh-jain252**
## Proposed changes (including videos or screenshots)

When a user chained quotes for more than 2 times, there was a link appearing in the quotes preview

Before:

Rocket Chat

After:

Rocket Chat After

## Further comments

The link is appearing for the following reason:
- The link is "message text prepended by quotedMessages link" (apps/meteor/client/lib/chats/data.ts) therefore text property of a message is in the form of `[ ] (URL) message`
- The replies array in MessageBoxReplies.tsx (apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxReplies.tsx) does not provide `md` property to reply.attachment.

RocketChat attachmentNoMd

- Therefore in QuoteAttachment.tsx (apps/meteor/client/components/message/content/attachments/QuoteAttachment.tsx) attachment.text is executed.

Let me know if I need to add something more.

JIRA task: TC-403

### CODE REVIEW

**Review by hugocostadev — APPROVED** [review]
Hi @jayesh-jain252 , thanks again for your contribution! 

I had to add the md prop to the QuoteAttachment because the `md` prop contains the tokens for the messages, with that the messages always follow the desirable structure.

I decided to keep your solution to keep working on old quoteAttachment that not contain the `md` prop, since it comes from backend

**Comment by hugocostadev** [comment]
@jayesh-jain252 no need to update branch... this blocks the CI workflow

**Comment by jayesh-jain252** [comment]
> @jayesh-jain252 no need to update branch... this blocks the CI workflow

Hi @hugocostadev is there a way to revert this... I clicked on update again by mistake.

**Comment by hugocostadev** [comment]
> > @jayesh-jain252 no need to update branch... this blocks the CI workflow
> 
> @hugocostadev is there a way to revert this... I clicked on update again by mistake.

Don't worry, I ran the CI again

**Pull request merged**
