### PR TITLE
fix: userinfo json

### PR DESCRIPTION
**Pull request by 0o001**

### CODE REVIEW

**Comment by dougfabris** [comment]
Hey there! 

Thanks for your interest in contributing to Rocket.Chat

Can you please explain better, what you are aiming to fix?

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Comment by dougfabris** [comment]
@0o001 Did you test the oauth service with your changes? I'm afraid fixing the typo can break the service.

**Comment by 0o001** [comment]
> @0o001 Did you test the oauth service with your changes? I'm afraid fixing the typo can break the service.

Hello, I did not test the code, I just noticed the typo based on the following code

https://github.com/RocketChat/Rocket.Chat/blob/0c3a563b3a3303251420729b75ebb5105bff2317/apps/meteor/app/custom-oauth/server/custom_oauth_server.js#L322

https://github.com/RocketChat/Rocket.Chat/blob/0c3a563b3a3303251420729b75ebb5105bff2317/apps/meteor/app/drupal/client/lib.ts#L18

**Comment by dougfabris** [comment]
@0o001 To move forward with this PR we have to test it, otherwise it potentially can break the service

**Pull request closed without merging**
