### PR TITLE
Combined Hightlight & Markdown packages. Fixed Katex & markdown collision

### PR DESCRIPTION
**Pull request by pitamar**
@RocketChat/core

### CODE REVIEW

**Comment by engelgabriel** [comment]
Maybe it will fix https://github.com/RocketChat/Rocket.Chat/issues/3177

**Comment by marceloschmidt** [comment]
LGTM

**Comment by marceloschmidt** [comment]
Doesn't fix #3177 though

**Comment by marceloschmidt** [comment]
@pitamar what were you trying to **fix** here? How can we test this?

**Comment by pitamar** [comment]
@marceloschmidt
I noticed there is a collision between markdown and katex because markdown had higher priority over katex, so if do something like $5 *5* 5$ it will try to treat *5* as markdown first and bold it.
Before:
image
After:
image
But inline code is also a part of markdown processing an I prefer it to have higher priority so I can show katex syntax just like in the screenshots above.

The PR got old by now, I will try to update it

**Comment by marceloschmidt** [comment]
Thanks @pitamar

**Comment by pitamar** [comment]
@marceloschmidt Updated :)

**Comment by mblo** [comment]
> @marceloschmidt
> I noticed there is a collision between markdown and katex because markdown had higher priority over katex, so if do something like $5 _5_ 5$ it will try to treat _5_ as markdown first and bold it.
> Before:
> image
> After:
> image
> But inline code is also a part of markdown processing and I prefer it to have higher priority so I can show katex syntax just like in the screenshots above.
> 
> The PR got old by now, I will try to update it

I'm on `3.0.9` and face the same issue as written here.
`$1*2*3$` appears as
image

**Pull request merged**
