### PR TITLE
[NEW][API] Add `interation.update` endpoint

### PR DESCRIPTION
**Pull request by tonobo**
Heyho guys, i've added the `integrations.update` restapi endpoint. It's currently missing at https://rocket.chat/docs/developer-guides/rest-api/integration/

### CODE REVIEW

**Comment by Kjarrigan** [comment]
Anyone have a feedback for this? Was there a specific reason the endpoint wasn't added together with the create and delete API?

We would like to manage our Webhooks outside of RocketChat in a git-repo and then only sync them to RocketChat via the API. Obviously this can only work with an update endpoint.

**Comment by zdumitru** [comment]
@tonobo Could you please sign the CLA?

**Comment by tonobo** [comment]
CLA sigend! ;)

**Comment by Kjarrigan** [comment]
Any news on this?

**Pull request merged**
