### PR TITLE
[FIX] Fix the capital letters issue in username on accountProfile page

### PR DESCRIPTION
**Pull request by lunaticmonk**
@RocketChat/core 

Fixes https://github.com/RocketChat/Rocket.Chat/issues/9620

Initially user was only able to type in small cased letters. This pr enables both small and capital letters in username.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Thanks for the contribution.

@RocketChat/core anyone know why we were forcing to lowercase?  Any reason to keep it forced to lowercase?

**Comment by gdelavald** [comment]
@ggazzo can you check this?

**Comment by sumedh123** [comment]
@karlprieb Is this feature meaningful out here? Currenlty, We are forcing the username to lowercase.

**Comment by geekgonecrazy** [comment]
@gazzo or anyone else @RocketChat/core any reason to keep forcing username lowercase?

If its just the way we'd prefer.  Its ok, just need to know to not leave the PR in limbo :)

**Pull request merged**
