### PR TITLE
[FIX] Support DISABLE_PRESENCE_MONITOR env var in new DB watchers

### PR DESCRIPTION
**Pull request by sampaiodiego**
## Proposed changes (including videos or screenshots)

With the introduction of micro services and the new DB watchers in https://github.com/RocketChat/Rocket.Chat/pull/19000 the env var `DISABLE_PRESENCE_MONITOR` used to control whether an instance should be watching for user presence events was not being respected.

### CODE REVIEW

**Review by ggazzo — APPROVED** [review]

**Comment by ankar84** [comment]
Am I get this right that using **native oplog** and `DISABLE_PRESENCE_MONITOR` honored and works fine. But if we use modern **change streams** that `DISABLE_PRESENCE_MONITOR` env not honored and all instances write to db presence changes?

**Comment by sampaiodiego** [comment]
hey @ankar84 this actually affects native oplog too.. I'll be probably releasing this in a patch for 3.15.x as well.

**Comment by ankar84** [comment]
> hey @ankar84 this actually affects native oplog too.. I'll be probably releasing this in a patch for 3.15.x as well.

This is a really good news, Diego!
And thanks for your great work!

**Comment by emikolajczak** [comment]
Sounds fantastic!

**Pull request merged**
