### PR TITLE
[FIX] Make bold, italics and strike work back-to-back with word

### PR DESCRIPTION
**Pull request by Gyaviste**
This PR makes bo**ld** ita*lics* and str~ike~ working in represented situation

### CODE REVIEW

**Comment by gdelavald** [comment]
Hey @Gyaviste, thanks for the Pull Request.
This seems to fix some weird behaviors with markdown formatting, but at the same time causes problems like word_with_underscore which I don't expect to get formatted, but I think that is the use case you were looking for.

**Comment by Gyaviste** [comment]
This is how sanitize on my forum works. I thought that this is the same here and it's a bug.

**Comment by gdelavald** [comment]
Yeah, I'll discuss this implementation with the team. 👍

**Comment by rodrigok** [comment]
@Gyaviste It's not how github works:
test_italic_var    _italic_
test__bold__var    __bold__

**Comment by gdelavald** [comment]
We'll close this PR since the implementation is not what we are looking forward right now. Thanks for your time!

**Pull request closed without merging**
