### PR TITLE
[NEW] login-privacy-permission

### LINKED ISSUE #6515: split up view-full-other-user-info permission
Rocket.Chat Version: 0.52.0

I'd like to give my users the permission to see other users email address. Activation of "view-full-other-user-info" permission can do that, but then they can see information like "Created at" and "Last login" too. Especially "Last login" is an information which could be sensible in some circumstances. To my mind this permission should be split up into something like "view-full-other-user-info" and "view-other-user-email".

Ciao!

### PR DESCRIPTION
**Pull request by localguru**
[NEW] login privacy permission feature

@RocketChat/core

Closes #6515

Under some circumstances presenting a user's last login time to others might be a privacy problem, e.g. laws governing data protection and data security. This feature splits up "last login" and "create at" info from "view-full-other-user-info" permission to a separated "view-login-other-user-info" permission.

### CODE REVIEW

**Comment by localguru** [comment]
I would be pleased about a review. Thanks, Marcus

**Comment by rodrigok** [comment]
Hi, 

I didn't understand the problem. You want to display the email, services, roles, customFields, etc, and not show the createdAt and lastLogin?

For me, makes more sense to add new permissions that you can enable field by field, in your case, `view-other-user-email`

**Comment by jszaszvari** [comment]
I'm curious.. Where in the world would laws governing data protection and data security prevent someone or restrict someone from seeing a user's last log in time?

**Comment by localguru** [comment]
Believe it or not, but that's a critical point in German law especially in public service as you can control people.

**Comment by MayaWolf** [comment]
+1. Would also like to see statusConnection, services, requirePasswordChange and requirePasswordChangeReason excluded here. Would also need to update [userInfo.html](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui-flextab/client/tabs/userInfo.html)
Being able to show custom fields and contact data without exposing other private information is an incredibly important use case for big distributed teams.

**Comment by rodrigok** [comment]
Closing this since it's old, with conflicts and not the best way to solve the problem. As mentioned, we should expand this to decide field by field in the future.

**Pull request closed without merging**
