### PR TITLE
[FIX] Fix badge counter on iOS push notifications

### LINKED ISSUE #6356: ios push notification uses always badge:1
We are developing an QT5 based iOS 10/Android 4.4+/WinMobile10, client for RocketChat(which by the way will be released soon under GPLv3), 
and I am now facing the issue, that the iOS push notifications always contain badge:1, instead of sending the absolute number of unread messages.

### PR DESCRIPTION
**Pull request by sampaiodiego**
@RocketChat/core 

Closes #6356

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
What about multi instance?  If you set the count doesn't iOS take that number regardless?  So if server a said `badge: 5` and server b said `badge: 1` wouldn't the badge count alternate between the two badge counts?

**Comment by sampaiodiego** [comment]
multi-instances will be handled by client.. the app should store a counter by server and display the correct number.. @rafaelks is aware of it https://github.com/RocketChat/Rocket.Chat.iOS/pull/460 :)

**Comment by geekgonecrazy** [comment]
@sampaiodiego ok just checking it was my understanding that if the app set it, and a push notification came in.. it would automatically take what the push notification told it.

So if the iOS app had calculated 10 total and set it to 10.  When a new push came in that said `badge: 5` that it would automatically set it back to 5.

Just want to make sure so it doesn't cause any issues with crazy counts down the road.
@rafaelks

**Comment by sampaiodiego** [comment]
@geekgonecrazy nope.. like if the server `A` send a badge count of `5`, when the app receives it, it will show `5` and store on it's local DB.. if server `B` send a badge count `2`, the app will sum stored badges from all servers and then show it, so in this case it would show `7`..

also if the user clicks on server `B` notification (or opens the app and connects to server `B`), the would clean up only the badges for server `B` and then show `5` again..

this is how I think it should work.. :grimacing:

**Comment by rafaelks** [comment]
@sampaiodiego @geekgonecrazy The value of the `badge` property here will always override whatever I have in the app. If the app has `10` and the push contains `badge: 5`, the app will (automatically) change the badge number to 5 and I cannot do anything about it.

Since we don't support multi-server right now on the client, I don't worry about it now. At some point, we'll need to change it (I think) to support the badge for multiple servers. I don't know yet what's the best solution for it, but we really don't need to worry about it right now.

Note: I **think** I have a way to handle the notification and manipulate the badge, but I haven't tried yet.

**Comment by rodrigok** [comment]
Since the solution looks better than what we have now I'll merge this

**Pull request merged**
