### PR TITLE
[FIX] API users.info returns caller rooms and not requested user ones

### LINKED ISSUE #12726: API users.info returns caller rooms, not requested user ones
### Description:

0.72.0-rc.0 introduced PR https://github.com/RocketChat/Rocket.Chat/pull/12105 but it does not work because it don't use request user id - caller user id is used to fetch Subscriptions instead.

### Steps to reproduce:

Call `/api/v1/users.info?username=username1&fields={"userRooms":1}` and be authenticated as `username2`

### Expected behavior:

Response contains `username1` groups and channels

### Actual behavior:

Response contains `username2` groups and channels

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.0-rc.1

### PR DESCRIPTION
**Pull request by piotrkochan**
Closes #12726

### CODE REVIEW

**Comment by MarcosSpessatto** [comment]
@piotrkochan can you please solve this issue about `Contributor License`? Because it would be interesting to have this fix before we release the final version of `v0.72`.

**Comment by piotrkochan** [comment]
@MarcosSpessatto I've already did it

**Comment by piotrkochan** [comment]
why not merged to 0.72.0?

**Comment by piotrkochan** [comment]
This CLA sign process is a trash.

**Pull request merged**
