### PR TITLE
[FIX] Added check for view admin permission page

### LINKED ISSUE #20400: user can see admin permissions page
### Description:

A typical user can visit permissions page by call admin/permissions url directly although users do not have permission to view Permissions

### Steps to reproduce:

1. user login
2. user type https://XXX/admin/permissions url directly
3. user can see this page!

### Expected behavior:

Users restrict from seeing permission page in admin section when they do not have permission to view Permissions

### Actual behavior:

user can ses permissions page (can not edit)

### Server Setup Information:

I use rocket.chat demo cloud 

- Version of Rocket.Chat Server: 3.9.4
- Operating System: linux
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: firefox and chromium
- Operating System:  fedora 33

### PR DESCRIPTION
**Pull request by yash-rajpal**
- [x] I have read the Contributing Guide 
  - [x] I have signed the CLA
  - [x] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  - [ ] I have added necessary documentation (if applicable)
  - [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

Admin Permission page was visible to all, if you add admin/permissions after the base url. This should not be visible to all user, only people with certain permissions should be able to see this page.
I am also able to see permissions page for open workspace of Rocket chat.
image

## Issue(s)

fixes #20400 
## Steps to test or reproduce

Check issue.
## Further comments

Fixed admin page, by including checks before rendering admin page.
image

### CODE REVIEW

**Comment by sushant52** [comment]
I found the changes required. The permission page access is granted using 'access-setting-permissions' not by 'access-permissions'. The label for both of them are swapped and the correct functionality of the permissions can be seen in the tooltip by hovering over the permissions. I have provided details in #20420 . The labels should be swapped.

**Review by gabriellsh — APPROVED** [review]

**Review by gabriellsh — CHANGES_REQUESTED** [review]
Please read https://github.com/RocketChat/Rocket.Chat/issues/20400#issuecomment-769422985

**Comment by yash-rajpal** [comment]
@gabriellsh done the required changes Please have a look.

On PermissionRouter added checks for 2 permissions and if any one of them is granted, user will be allowed for next page.

On PermissionTable added Permissions checks for permissions and settings tab. Any user having one of them will be only allowed to use only one of the tab, other one will be disabled. Also added default tab, if user doesn't have permission for permission's tab, settings tab will be made default tab and other tab would be disabled. And vice-versa for permissions tab.

### When only Permission tab is allowed
fix-access-permissions only

### When only settings tab is allowed
fix-access-settings only

Please review :)

**Comment by danel1** [comment]
Ping @gabriellsh

**Comment by yash-rajpal** [comment]
@gabriellsh Please review. :)

**Comment by gabriellsh** [comment]
I just have to test it, but looks good ;)

**Review by gabriellsh — APPROVED** [review]

**Pull request merged**
