### PR TITLE
[NEW] Beta support for Big Blue Button video conferencing system

### PR DESCRIPTION
**Pull request by rodrigok**
image
image
image

### CODE REVIEW

**Comment by jsdckr** [comment]
Greetings; the support for BigBlueButton is fantastic; and this is working superbly. Just wondering if there is a way for the current Android app also to connect to the BigBlueButton platform to communicate with a desktop/browser user?

**Comment by sampaiodiego** [comment]
@jsdckr may I ask you to create an issue on Android repo https://github.com/RocketChat/Rocket.Chat.Android ? they can answer better and proper prioritize if it gets attraction. thx

**Comment by kenculate** [comment]
do you have any documentation on how to enable this feature with a self-hosted server, 
I am having this error after start meeting 
`"Error: Internal server error [500]
    at w._livedata_result (https://skychat.online/ba77dee8bac2314ed1cb402c93013d2f89668bba.js?meteor_js_resource=true:59:17834)
    at w.onMessage (https://skychat.online/ba77dee8bac2314ed1cb402c93013d2f89668bba.js?meteor_js_resource=true:59:20175)
    at https://skychat.online/ba77dee8bac2314ed1cb402c93013d2f89668bba.js?meteor_js_resource=true:57:2772
    at Array.forEach (<anonymous>)
    at l.forEachCallback (https://skychat.online/ba77dee8bac2314ed1cb402c93013d2f89668bba.js?meteor_js_resource=true:57:3967)
    at k.socket.onmessage (https://skychat.online/ba77dee8bac2314ed1cb402c93013d2f89668bba.js?meteor_js_resource=true:57:2742)
    at k.r.dispatchEvent (https://skychat.online/ba77dee8bac2314ed1cb402c93013d2f89668bba.js?meteor_js_resource=true:57:6474)
    at k._dispatchMessage (https://skychat.online/ba77dee8bac2314ed1cb402c93013d2f89668bba.js?meteor_js_resource=true:57:20111)
    at k._didMessage (https://skychat.online/ba77dee8bac2314ed1cb402c93013d2f89668bba.js?meteor_js_resource=true:57:21011)
    at WebSocket.o.ws.onmessage (https://skychat.online/ba77dee8bac2314ed1cb402c93013d2f89668bba.js?meteor_js_resource=true:57:23160)"`

**Comment by Cormoran96** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/11837#issuecomment-603610719

I have the same issue

**Comment by kdre** [comment]
I installed BBB on a separate server and integrated it into rocket.chat (installed on another server). So far, it works very well.
However, all users who join the chat have super powers. They can mute others, they can take presenter etc. Is it possible to configure rocket.chat/BBB in such a way that only the mod of a rocket.chat channel (and/or the admin of rocket.chat) is also the user with super power in the BBB chat?

**Comment by pguzmanc** [comment]
would you please share how you make it work? any changed made on BBBserver?

> I installed BBB on a separate server and integrated it into rocket.chat (installed on another server). So far, it works very well.
> However, all users who join the chat have super powers. They can mute others, they can take presenter etc. Is it possible to configure rocket.chat/BBB in such a way that only the mod of a rocket.chat channel (and/or the admin of rocket.chat) is also the user with super power in the BBB chat?

**Comment by kdre** [comment]
> would you please share how you make it work? any changed made on BBBserver?

What do you mean? I installed BBB using the install script on a server. Afterwards, I installed web-hoos using apt. Then I extracted the secret and used the URL + secret to configure Rocket.Chat.  Thats all. No changes made.

Anyway, i already found out that currently everything works as designed. In Rocket.Chat the BBB Join-API call submits the moderator password for every user (see bbb.js). As a matter of fact: Everyone is a moderator in BBB.

i am still deciding what is the best approach:
1. Every user is moderator (current approach)
2. Every user is only viewer (no screensharing,  no presentation, but nobody can make fun of others)
3. Channel mod is BBB mod, all the others only viewers (if moderator isn't present nobody can share screen or give presentation, but nobody can make fun of others.)
4. Let channel moderator configure a link to a BBB room that he created on the BBB server using Greenlight.
5. Implement a per channel configuration (options 1-3) that the owner of a channel can change.

**Comment by pguzmanc** [comment]
Webhooks, that is what i missed, thanks.

**Comment by pguzmanc** [comment]
In my opinión your options 3 and 5 seems fine to me.

**Comment by arpsyapathy** [comment]
> > would you please share how you make it work? any changed made on BBBserver?
> 
> What do you mean? I installed BBB using the install script on a server. Afterwards, I installed web-hoos using apt. Then I extracted the secret and used the URL + secret to configure Rocket.Chat. Thats all. No changes made.
> 
> Anyway, i already found out that currently everything works as designed. In Rocket.Chat the BBB Join-API call submits the moderator password for every user (see bbb.js). As a matter of fact: Everyone is a moderator in BBB.
> 
> i am still deciding what is the best approach:
> 
> 1. Every user is moderator (current approach)
> 2. Every user is only viewer (no screensharing,  no presentation, but nobody can make fun of others)
> 3. Channel mod is BBB mod, all the others only viewers (if moderator isn't present nobody can share screen or give presentation, but nobody can make fun of others.)
> 4. Let channel moderator configure a link to a BBB room that he created on the BBB server using Greenlight.
> 5. Implement a per channel configuration (options 1-3) that the owner of a channel can change.

+1 On all items
I also want the moderator to be only the one who created the conference or the owner of the channel. Otherwise, anyone can end the conference by mistake. And I want to be able to pass the link to the conference to other users who are not added to this channel.

**Comment by falkiy** [comment]
Hi Guys,
we integrated bbb in our rocketchat and works well, thx!
But i/we dont like to run the confernce within the rocketchat-browserwindow, neither running bbb in complete fullscreen. Is there any comfortable way/workaround to open the conference in a new browsertab or just print out the api-url? Only way i found so far, is inspect element / dev console to investigate the complete url. 
thx && greets

**Pull request merged**
