### PR TITLE
[NEW] Omnichannel Contact Center (Directory)

### PR DESCRIPTION
**Pull request by rafaelblink**
## Proposed changes

Omnichannel Contact Center (or Directory) is a way that the agents for example can see more details about chat conversations, they can create new contacts.

As an agent, for example, you can see chat duration of your conversations, you can assign e-mail address and phone to your contacts, if you are an enterprise, you can assign Rocket.Chat users as a contact manager, and so on.

## Screenshots
image

image

image

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by renatobecker** [comment]
@rafaelblink please, improve the PR description, we need to share more details on this important feature.
Feel free to add more screenshots as well, they are very important for other community members to understand what's going to be delivered and how to use it. 

Thanks.

**Review by renatobecker — DISMISSED** [review]

**Review by renatobecker — APPROVED** [review]

**Comment by sampaiodiego** [comment]
Please fix https://github.com/RocketChat/Rocket.Chat/pull/19931#issuecomment-749349330 LGTM bot comments

**Comment by yash-rajpal** [comment]
@renatobecker If documentation is needed, I can try and understand the endpoint and changes and try the docs part, can you please guide me through it?
Thanks.

**Comment by renatobecker** [comment]
> @renatobecker If documentation is needed, I can try and understand the endpoint and changes and try the docs part, can you please guide me through it?
> Thanks.

Hi @yash-rajpal, the team has already started working on it, but thanks for being willing to help us.

**Pull request merged**
