### PR TITLE
[NEW] Sender's name in email notifications.

### PR DESCRIPTION
**Pull request by pkgodara**
In case Channel, Channel name would appear in place of sender's name.

In case DM, If sender's name is **John Doe** then, in email notifications, it would appear as if **John Doe** has sent the email.

Initially emails looked like:
screenshot from 2017-08-30 13-33-13

Now emails would be more specific:
screenshot from 2017-09-06 12-40-50

@RocketChat/core

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
In a DM I think this would make total sense.  But in a channel... I think this should maybe should something to indicate channel name.

I say this because if it says it comes from John if reply by email feature is enabled and they replied... You aren't really replying just to John.  We need to not confuse users

**Comment by sampaiodiego** [comment]
I agree with @geekgonecrazy .. also on Gmail on subsequent replies to that channel it will group as if "John Doe" replies even if they are not..

**Comment by pkgodara** [comment]
@geekgonecrazy @sampaiodiego I've updated accordingly. Can you check it again?

**Comment by sampaiodiego** [comment]
looks good

**Pull request merged**
