### PR TITLE
Fixing attach icon misalignment + Fix unread message shadow + Change unread bar colors entries to correct file

### PR DESCRIPTION
**Pull request by AdrianoCahete**

### CODE REVIEW

**Comment by rodrigok** [comment]
Can you add prints showing the changes?

**Comment by AdrianoCahete** [comment]
For misalignment:
Before
1before

After
1after

For shadow is just to not leak the shadown in the right:
Before
2before

After
2after

**Comment by rodrigok** [comment]
This alignment problem don't happens for me.
captura de tela 2015-09-19 as 18 46 33

Which browser and OS are you using?

**Comment by AdrianoCahete** [comment]
Firefox @ Windows 10

**Comment by rodrigok** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/commit/eb394be0fc613d68d90a5772828373cdc431669a and https://github.com/RocketChat/Rocket.Chat/commit/6334ec7baaa2c7653fae5e73ae1e98a65117beff

**Comment by rodrigok** [comment]
And https://github.com/RocketChat/Rocket.Chat/commit/bc3d7ed6057904ba94911fbe6b113aadeecd0262

**Comment by AdrianoCahete** [comment]
Ok. :D

**Pull request closed without merging**
