### PR TITLE
[FIX] Downloading files when running in sub directory

### LINKED ISSUE #14472: Can't download files when running RocketChat in subdir
### Description:

When running RocketChat in subdir, I can't download all files.

### Steps to reproduce:

1. Start Rocket Chat with using `ROOT_URL=https://(FQDN)/chat`
2. Upload a file. (such as `test.jpg`)
3. Try to download the file.

### Expected behavior:

Downloading the file is success.
The URL should be `https://(FQDN)/chat/file-upload/(hash)/test.jpg`.

### Actual behavior:

Downloading the file is fail. My front proxy server reports that the page is not found.
The broken URL is `https://(FQDN)/file-upload/(hash)/test.jpg`.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.4.20

### PR DESCRIPTION
**Pull request by miolane**
fix URI for uploading file

Closes #14472

### CODE REVIEW

**Comment by miolane** [comment]
Sorry for my previous stupid mistake.

**Comment by ura14h** [comment]
@miolane 
I feel that it is better to create `fileUrl` using `getURL()`.

**Comment by ura14h** [comment]
I feel it is better to create a link using `getURL()` at the time of display like `app/ui-flextab/client/tabs/uploadedFilesList.js`, not at upload time.

@tassoevan what do you think about?

**Comment by miolane** [comment]
@ura14h Thanks for your direction. I'm not familiar with the frameworks and the whole system and do it in a wrong way. I will update it soon

**Comment by miolane** [comment]
@tassoevan I found many wrong urls in this edge case. One of them is the footer of side navigator. I tried to change app/lib/server/startup/settings.js at line 1246 like `<script type="text/javascript">
(function(w, d, s, u) {
	w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
	var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
	j.async = true; j.src = 'http://chat.miolane.moe:3000/livechat/1.0.0/rocketchat-livechat.min.js?_=201903270000';
	h.parentNode.insertBefore(j, h);
})(window, document, 'script', 'http://chat.miolane.moe:3000/livechat?version=1.0.0');
</script>`

**Comment by ura14h** [comment]
@miolane Your insight is great.

However, I think it is difficult to solve as this pull-request because the scope is too large. This pull- request should be focused on only solving the upload and download link issues, for to merge easy.

You can report a new issue about other wrong links you found and create a new pull-request for to fix it.

Thanks.

**Comment by miolane** [comment]
@ura14h I have already solved the upload and download issue by using `getURL()` but it still tells me 
"Changes requested". I don't how to let it be merged. Sorry I'm new in Github.

**Comment by ura14h** [comment]
I think that the reviewer will close "Changes requested" manually. So you need only to mention to tassoevan that "changed to using getURL()" after fixing the point where He and I pointed out.

Then after, reviewers reviews your changes again, and RocketChat development members approve and merge it into develop-branch.

I don't have an authority of reviewer :)

**Comment by ura14h** [comment]
@tassoevan, I feel  that 3455ad1 is good but 22b7848 is not necessary.

**Pull request merged**
