### PR TITLE
fix: Fixes bell icon hover status

### PR DESCRIPTION
**Pull request by AdityaSingh-02**
## Proposed changes (including videos or screenshots)

I just made few changes in styles and it fixes the issue #28115 
image

## Issue(s)

This Pull request closes issue #28115  , the issue was while we were hovering over the notification icon the content was going outside the window
## Steps to test or reproduce
Goto http://localhost:3000/livechat?mode=popout
Then on top right corner look for bell icon and hover over it then you will see the content is inside the window and not going outside the window

### CODE REVIEW

**Review by ggazzo — CHANGES_REQUESTED** [review]
rocket.chat has several languages modifying the percentage will not work

**Comment by KevLehman** [comment]
Gazzo's right on this one. Can you try a more safe approach, that can work with multiple languages?
Your Language setting (workspace) defines which one do you use, try with Arabic or other languages with long text 🤗

**Comment by AdityaSingh-02** [comment]
Sure I'll try to fix it.✌️

**Comment by AdityaSingh-02** [comment]
hey @ggazzo i came across an approach where i added margin and it solves the issue and i have tested it on multiple languages.. if you like it i can make an pull request over it

margin

**Pull request closed without merging**
