### PR TITLE
[NEW] Endpoint to anonymously read channel's messages

### PR DESCRIPTION
**Pull request by PrajvalRaval**
## Overview

This API Endpoint is made for RC Alexa and Google Action to allow Anonymous READ in VUI Devices without linking their accounts first to the Apps. This endpoint will enable access to messages in public channels, which are by definition public - and should be anonymous readable. In addition to that, this endpoint can be accessed by VUI user without any registration required. Also if admin has disabled anonymous read on his server, it won't work. So to summarise, after merging this API endpoint, we will be able to enable Alexa skill and Google Action to non-registered user if anonymous reading options are enabled on that server.

## Testing

* Enable `Allow Anonymous Read` inside **Administration -> Accounts**
* Now you can use this to get message anonymously
```
curl http://localhost:3000/api/v1/channels.anonymousread?roomName=general
```

### CODE REVIEW

**Comment by rodrigok** [comment]
@PrajvalRaval thanks for your contribution, can you add tests for this new endpoint? Either for the situation where Anonymous Read is enabled and disabled?

Refer to https://github.com/RocketChat/Rocket.Chat/blob/develop/tests/end-to-end/api/01-users.js#L24 for example of how to change settings in tests.

**Comment by PrajvalRaval** [comment]
> @PrajvalRaval thanks for your contribution, can you add tests for this new endpoint? Either for the situation where Anonymous Read is enabled and disabled?
> 
> Refer to https://github.com/RocketChat/Rocket.Chat/blob/develop/tests/end-to-end/api/01-users.js#L24 for example of how to change settings in tests.

Hello @rodrigok, this is my first PR for Core API and I am not exactly sure what should I include in tests for endpoints. Can you please tell me what should I include in tests, perhaps with an example or something ? Thanks 👍

**Comment by PrajvalRaval** [comment]
Thank You very much @MarcosSpessatto for adding tests for this endpoint. For a rookie like me, it helps a lot when senior developer like yourself come forward for our help. 👏

**Comment by PrajvalRaval** [comment]
@rodrigok Just A reminder for merge. If it's alright for you. 😓

**Pull request merged**
