### PR TITLE
[Fix]Add custom sound form submits even without adding a file

### PR DESCRIPTION
**Pull request by PriyaBihani**
- [x] I have read the Contributing Guide
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- I have added necessary documentation (if applicable)
- Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)
Earlier the form for uploading a custom sound allowed submission even if a file isn't present. I've added a check for file , so that the submit button remains disabled unless both "name" and "file" is provided.

Previously
Screenshot 2021-04-20 at 4 08 43 PM

Now
Screenshot 2021-04-20 at 4 09 14 PM

## Issue(s)
#21664

### CODE REVIEW

**Comment by KevLehman** [comment]
In the line of the issue, could you please also add a backend validation to prevent this behavior? So, if a user tries to upload it through the API it's also locked.

**Comment by PriyaBihani** [comment]
Sure i'll do it :)

**Comment by PriyaBihani** [comment]
@KevLehman backend validation for this already exists we don't need to make any changes to that :)

**Comment by yash-rajpal** [comment]
@PriyaBihani I have a pr that would fix this issue. Please have a look at #20376 , Thanks.

@KevLehman I checked but I didn't find any API endpoints for updating or adding custom sounds. I found 2 Meteor Methods `uploadCustomSound` and `insertOrUpdateSound`, these methods don't contain checks for missing file, should I add it in these methods? If so please let me know, I will add them in mentioned pr itself. Thanks :)

**Pull request closed without merging**
