### PR TITLE
[NEW] User activity counter

### PR DESCRIPTION
**Pull request by gsunit**
Implemented a feature to sorting `members list` on the basis of user activity. Using this users can sort the members of a channel on the basis of their activity/contribution to the channel.

Currently, activity is only being measured by catching the event of sending a message and incrementing a counter in the model of respective room.

### CODE REVIEW

**Comment by gsunit** [comment]
@kb0304 @bizzbyster Please have a look at my progress. Let me know what changes need to be made.

**Comment by kb0304** [comment]
@gsunit The tests fail on Circle CI, could you please have a look at fix that?

**Comment by gsunit** [comment]
@kb0304 I have figured out what was causing the tests to fail but not why. Apparently, the call to a method to update user message count was causing the problem. I may need to call this method from somewhere else. Can you please look at my [last commit](https://github.com/RocketChat/Rocket.Chat/pull/13780/commits/09191c42dd447850b51d26a82d3479175e516a0d) and let me know what went wrong.

**Comment by engelgabriel** [comment]
I am really worried about the extra load this would add to the DB, looking at the code, it seems to be very "havy"

**Comment by gsunit** [comment]
@engelgabriel Any suggestions how I can improve upon it?

**Comment by engelgabriel** [comment]
Hi, I was looking at the code. For the load to be ok, we would have to increment a messages counter on the user's subscriptions each time they send a message, in similar way we increment the messages counter on room object.

**Comment by rodrigok** [comment]
We apologize for not getting a review on this sooner.

This implementation has huge performance problems for large rooms, it may break the process and/or the DB by getting all the users of a big room in memory to loop everyone and create a huge array of users to save to the Room's and Subscription's model.

Due to the lack of activity here, the performance and implementation design issue I'll close this PR by now. Please open a new one if you find a better way to implement this.

Thanks

**Pull request closed without merging**
