### PR TITLE
Improve image oembed

### PR DESCRIPTION
**Pull request by rodrigok**
Before
captura de tela 2015-10-19 as 21 07 23

After
captura de tela 2015-10-19 as 21 06 46

### CODE REVIEW

**Comment by sampaiodiego** [comment]
I don't think it is a good idea to round the image corners

**Comment by rodrigok** [comment]
Why?

**Comment by sampaiodiego** [comment]
you are losing image data.

**Comment by geekgonecrazy** [comment]
@sampaiodiego are we loosing that much?  Enough to actually be noticed or missed?

**Comment by geekgonecrazy** [comment]
Does this also solve #1138 ?

**Comment by sampaiodiego** [comment]
Well, not so much. Its more like a preference :)

Em seg, 19 de out de 2015 22:27, Aaron Ogle <notifications@github.com>
escreveu:

> Does this also solve #1138
> <https://github.com/RocketChat/Rocket.Chat/issues/1138> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/pull/1170#issuecomment-149336466>
> .
>
-- 
.Diego Sampaio

**Comment by stefanlegg** [comment]
Was there anything particularly wrong with my pr (#1167)?
If so, constructive criticism would be awesome.

**Comment by geekgonecrazy** [comment]
@stefanlegg I didn't see anything wrong with your PR.  I'm trying to see if it solved both problems yours solved if so then the changes are now in master.  If not then we need to find out what we can do to also get your changes in and fix #1138

**Comment by stefanlegg** [comment]
@geekgonecrazy Gotcha, thanks!

**Pull request merged**
