### PR TITLE
[FIX] Usernames are case-sensitive when mentioning someone

### LINKED ISSUE #13374: Usernames are case-sensitive when mentioning someone
### Description:

When creating users in RocketChat they are treated case insensitive, e.g. I can't create two users with the username "foo" and "Foo". But apparently when mentioning someone in a channel, it only gets converted to a highlight if one uses the correct case. This bites a lot of our customers because to to pretty short names some of them just type the message including the highlight instead of using the autocompletion dropdown.

screenshot 2019-02-05 at 17 38 52

### Steps to reproduce:

1. Create a user called "foo"
2. Go to a channel and mention "@Foo"

### Expected behavior:

The user "foo" gets a mention because usernames are case-insensitive in the rest of the system

### Actual behavior:

No mention is created.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.0
- Operating System: Linux
- Deployment Method: Hosted Cloud Version
- NodeJS Version: v8.11.4

### PR DESCRIPTION
**Pull request by ashwaniYDV**
Closes #13374

### Description:
Since username is unique and case-insensitive. That means `ashwaniYDV` and `ashwaniydv` should be treated same while mentioning. There added case-insensitive query.

### After fix:
qwerty

qwertyu

### CODE REVIEW

**Comment by fleaz** [comment]
Exactly the behavior that I would expect. Nice :)

**Comment by ashwaniYDV** [comment]
@ggazzo @gabriellsh Would you please review :)

**Comment by ashwaniYDV** [comment]
@ggazzo Would you please review
Thanks

**Comment by rodrigok** [comment]
@ashwaniYDV since you have the autocomplete why do you need this? The autocomplete already searches as case insensitive.

**Comment by sybrenstuvel** [comment]
> since you have the autocomplete why do you need this? 

There are multiple reasons:

- The autocomplete popup can get confused sometimes when I type, wait, and press Enter to choose the name. Sometimes it correctly picks the top choice, but sometimes it changes to whatever my mouse cursor happens to hover over.
- The autocomplete popup seems to be populated incrementally. This means that I type, I see the name, and press Enter to choose that name, only to get the wrong name because between seeing it and pressing Enter another incremental update came along and changed the selected name.
- The above means I have to triple-check that the selected name is correct, making the process even more slow.
- **I type faster** than the autocomplete does a search, especially when I'm chatting with colleagues whose name I've typed hundreds of times already. I shouldn't have to type `@name` only to wait for all of the above to change it to `@Name` for me.
- On our server there are people with the same name as Full Name and Username, with only a difference in case. If someone has username `name` but full name `Name`, I don't want to remember that I can't type `@Name` to mention them.

**Comment by ashwaniYDV** [comment]
hi @rodrigogs
I have too experienced the same issues as mentioned above by @sybrenstuvel

**Comment by fleaz** [comment]
> @ashwaniYDV since you have the autocomplete why do you need this? The autocomplete already searches as case insensitive.

"Just user the other way" is imho not a good reply to a bug. If mentioning user is just indended to be used via the autocomplete popup, then you have to disable mentioning user by manually typing `@username`.

I'm not quite sure why we have to discuss over one year for such a small bug :/

**Comment by rodrigok** [comment]
We found some performance issues. Using regex, on a database with 600k users, it brings the find from 0.002 seconds to 0.4, what is a huge increase, so we need to figure out if it's possible to improve this.

**Comment by engelgabriel** [comment]
@rodrigok did you find something about using case insensitive indexes?

**Pull request closed without merging**
