### PR TITLE
[FIX] Sidebar and RTL alignments

### LINKED ISSUE #8148: Sidebar Account alignments

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #8148 #8129 #8165 #8179 #8184 #8185 #8182

Sidebar:
* Removed empty space above sidebar header
* Fixed header color on lighten version of the sidebar
* Fixed empty room groups alignment
* Fixed livechat icon alignment
* Fixed Back button alignment

Create Channel:
* Fixed create channel page on mobile
* Now private channels are default

Popover:
* Fixed popover position on RTL

image

image

image

image

image

### CODE REVIEW

**Comment by rodrigok** [comment]
image

**Comment by rodrigok** [comment]
The popover when click on + icon is going out of the screen

**Comment by rodrigok** [comment]
When creating a new room, the initial label of the room type switch is wrong

image

**Comment by rodrigok** [comment]
On create room screen and using RTL the switch layout is broken and the label is very near to the switch

image

**Comment by cyclops24** [comment]
@rodrigok, @karlprieb Please visit #8175

**Comment by karlprieb** [comment]
@rodrigok thank for you report :)
It's fixed!

image

image

**Comment by fifou17** [comment]
@karlprieb did you fixed the height of sidenav in admin ?? and profile height for mobile?? becaus its has even issue on scroll

**Comment by cyclops24** [comment]
@karlprieb #8182 not fixed with this PR.

**Pull request merged**
