### PR TITLE
[Fix] Fix url parsing on markdown

### PR DESCRIPTION
**Pull request by cuonghuunguyen**
Closes [#15438 ](https://github.com/RocketChat/Rocket.Chat/issues/15438)

### CODE REVIEW

**Comment by meomay503** [comment]
Hi @ggazzo, could you please review it for me?

**Comment by meomay503** [comment]
@renatobecker Hi, could you please review this PR for me. It is just a small change but it affects a lot on my project 😄 
This has been here for a long time. Thank you in advance.

**Comment by debdutdeb** [comment]
Hi, this issue seems to have been already fixed since the version it first surfaced. Just checked. 

Response object -

```json
{'channel': 'general',
 'message': {'_id': 'YpFsLnsb2E68pRyfq',
             '_updatedAt': '2021-09-06T10:42:32.037Z',
             'alias': '',
             'attachments': [],
             'channels': [],
             'groupable': False,
             'md': [{'type': 'PARAGRAPH',
                     'value': [{'type': 'LINK',
                                'value': {'label': {'type': 'PLAIN_TEXT',
                                                    'value': 'markdown'},
                                          'src': {'type': 'PLAIN_TEXT',
                                                  'value': 'https://example.com'}}}]}],
             'mentions': [],
             'msg': '[markdown](https://example.com)',
             'parseUrls': True,
             'rid': 'GENERAL',
             'ts': '2021-09-06T10:42:32.025Z',
             'u': {'_id': 'CpM8PcRjZ3E6fRApP',
                   'name': 'Debdut Chakraborty',
                   'username': 'debdut.chakraborty'},
             'urls': [{'url': 'https://example.com'}]},
 'success': True,
 'ts': 1630924952039}
```

**Comment by cuonghuunguyen** [comment]
seems to be fixed

**Pull request closed without merging**
