### PR TITLE
Slackbridge out

### LINKED ISSUE #3457: Slackbridge 2-way
Your Rocket.Chat version: develop 2015-06-03

Great work on slackbridge! It's working so well.

Is it in the plans to have it a two way communication so you could reply in rocket chat and it would also show in slack?

### PR DESCRIPTION
**Pull request by marceloschmidt**
@RocketChat/core 

Closes #3457

### CODE REVIEW

**Comment by marceloschmidt** [comment]
Attachments don't work yet

**Comment by acrogenesis** [comment]
Nice! Was looking exactly for this feature.

**Comment by mrplow** [comment]
Thanks so much! Working great with my 250+ team so far.

**Comment by acrogenesis** [comment]
On my rocket.chat everything I say is repeated by the bot:

screen shot 2016-10-26 at 10 22 37 pm

**Comment by letic** [comment]
Same here messages are duplicated randomly by rocket.cat this is not currently urgent for us, but I'll try to investigate later.

**Comment by mrplow** [comment]
I'm noticing this as well.

It didn't happen after this was initially added and I'm not sure when it started.

**Comment by marceloschmidt** [comment]
I'll investigate this

**Pull request merged**
