### PR TITLE
add velocity jasmine and sample unit test - closes #1027

### LINKED ISSUE #1027: Add unit testing framework and example test
Meteor's official framework is velocity.   And the most frequently used tester is jasmine.

Add velocity jasmine to core, and a sample markdown client side unit test.

### PR DESCRIPTION
**Pull request by Sing-Li**
Add test framework and a sample test.

unitest

### CODE REVIEW

**Comment by kakawait** [comment]
:+1: I will try to implement some tests for Spotify integration

**Comment by gmsecrieru** [comment]
:+1: :+1:

**Comment by geekgonecrazy** [comment]
Awesome!  :)  Lets get the party started!

Is there anyway to do this with the tests contained in the package?  As is, won't this cause issues if we have tests for a package and that package is disabled?  I know per package was mentioned here: #306

I personally couldn't figure it out when I tried it.

**Comment by rodrigok** [comment]
Great, can we merge this?

**Comment by geekgonecrazy** [comment]
@rodrigok the PR looks good to me.  Especially with the testing disabled by default.  As when enabled it shows a green dot in the corner :)

**Comment by kakawait** [comment]
only problem is testing *velocity frame* is load by default. So when using latest code with `docker meteor` you see *velocity*

**Comment by geekgonecrazy** [comment]
@kakawait even with the package commented out?

@Sing-Li mentioned they had a console version, we might have to use that version.

**Comment by kakawait** [comment]
@geekgonecrazy nop my bad I deleted my comment... I tested code without second commit https://github.com/RocketChat/Rocket.Chat/commit/4131338257cba1f3e1fa3d90f4a2f2245711c7a9

**Comment by geekgonecrazy** [comment]
@kakawait :+1: downside to it showing up instantly in RC heh

**Comment by kakawait** [comment]
*Big brother is watching you* :laughing:

**Comment by Sing-Li** [comment]
@rodrigok  Please merge asap.  Thx  :smiley:

**Pull request merged**
