### PR TITLE
[BUG] Icon Fixed for Knowledge base on Livechat 

### LINKED ISSUE #13797: [BUG] Icon Missing for Knowledge base on Livechat
### Description:

Inside `app/livechat/client/ui.js` on line 41, tabBar Icon is set to `lightbulb`. But it is missing from `app/ui-master/public/icons`. So add svg for it

### Steps to reproduce:

1. Open live chat for any user
2. See tabBar

### Expected behavior:

Icon should be there

### Actual behavior:

Screenshot 2019-03-20 at 1 01 43 AM

### Server Setup Information:

- Version of Rocket.Chat Server:  1.0.0-develop
- Operating System: MacOs
- Deployment Method: Meteor
- Number of Running Instances: 1
- DB Replicaset Oplog: Enables
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6

### Additional Text

Will add a PR for the same

### PR DESCRIPTION
**Pull request by knrt10**
Closes #13797 

Icon fixed, along that updated instructions to add and update new icons for RC.

Knowledge Icon

cc @renatobecker @tassoevan would you please review

### CODE REVIEW

**Comment by ashwaniYDV** [comment]
@knrt10 There is a small typo in app/ui-master/public/README.md (line 5):-

typo

**Comment by knrt10** [comment]
Thanks @ashwaniYDV for pointing that out

**Comment by engelgabriel** [comment]
@brunosquadros can you help with the right icon here?

**Comment by engelgabriel** [comment]
Should we use 
image 
or 

image
??

**Comment by renatobecker** [comment]
> Should we use
> image
> or
> 
> image
> ??

IMO, the second one looks better.

**Comment by engelgabriel** [comment]
The light bulb is more about creativity than knowledge, IMHO

**Comment by knrt10** [comment]
@engelgabriel you tell me about the icon, I can convert it into single path

**Comment by tassoevan** [comment]
@engelgabriel The lightbulb looks great, but the book is more adequate in this context.

**Comment by knrt10** [comment]
Converting to one path. 

This is lightbulb

Screenshot 2019-03-20 at 11 10 58 PM

and this is book

Screenshot 2019-03-20 at 11 12 08 PM

cc @engelgabriel @renatobecker @tassoevan

**Comment by brunosquadros** [comment]
The book works better for this context, I've adapted a path that one from FontAwesome.
[Book.svg.zip](https://github.com/RocketChat/Rocket.Chat/files/2989722/Book.svg.zip)

**Comment by knrt10** [comment]
Cool, let me update the PR then

**Comment by knrt10** [comment]
Updated the PR. Logo

Logo

cc @tassoevan would you please review

**Comment by knrt10** [comment]
Done @tassoevan

**Pull request merged**
