### PR TITLE
feat: Implemented InlineCode handling in Bold, Italic and Strike

### LINKED ISSUE #30185: Markdown: strikethrough text does not work with the code span
### Description:

I have my application that works as a notificator. It gets alerts from Zabbix and sends them to Rocket.Chat. After the alert is closed, my notification edits Rocket.Chat message.

For new alert message is:

```
:sos: WARNING `[server.example.net]: less than 10% 4.48 GB on volume /` [12345](https://zabbix.example.net/tr_events.php?triggerid=29634&eventid=247154493)
```

it is ok: 
image

but after the notificator app edit message, formatting breaks. Edited message:

```
:white_check_mark: ~~_WARNING `[server.example.net]: less than 10% 4.48 GB on volume /` Duration: 01:10:01 [12345](https://zabbix.example.net/tr_events.php?triggerid=29634&eventid=247154493)_~~

or

:white_check_mark: ~_WARNING `[server.example.net]: less than 10% 4.48 GB on volume /` Duration: 01:10:01 [12345](https://zabbix.example.net/tr_events.php?triggerid=29634&eventid=247154493)_~
```
and it is broken:

image

if I put exactly the same markdown to the Visual Studio Code, it is ok:

image

### Expected behavior:

Show the message as in VS code editor

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.1
- Operating System: Debian 12 x64
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: desktop app 3.8.16 and Google Chrome 116
- Operating System: Ubuntu 22.04 x64

### PR DESCRIPTION
**Pull request by Subhojit-Dey1234**
## Proposed changes (including videos or screenshots)
The required result for the corresponding codes changes.
Screenshot from 2024-01-01 17-37-53

## Issue(s)
Fixes #30185

## Steps to test or reproduce
Please follow the #30185 

https://rocketchat.atlassian.net/browse/SUP-285

### CODE REVIEW

**Comment by Subhojit-Dey1234** [comment]
@tuxmartin Raised the following PRs for this issue. Hope it will fix it.
https://github.com/RocketChat/fuselage/pull/1256
https://github.com/RocketChat/Rocket.Chat/pull/31349

**Review by hugocostadev — CHANGES_REQUESTED** [review]
LGTM 🚀  thanks for your contribution

We need to wait the https://github.com/RocketChat/fuselage/pull/1256 PR be merged and than update the message-parser package to actually fix the issue 

image

**Comment by hugocostadev** [comment]
Hey man, it was merged! Thanks a lot! 
If possible, update the package version when it gets updated in the npm, pelase.

[@rocket.chat/message-parser - npm](https://www.npmjs.com/package/@rocket.chat/message-parser?activeTab=versions)

**Comment by Subhojit-Dey1234** [comment]
Hi @hugocostadev , thanks a lot for the changes. I have been checking the version might have missed it in the couple of days. Let me know if any changes are required from my side.

**Review by hugocostadev — APPROVED** [review]

**Review by tapiarafael — APPROVED** [review]

**Pull request merged**
