### PR TITLE
Integração com skype

### PR DESCRIPTION
**Pull request by hfsoares**
@RocketChat/core 

Closes no open issue

screen shot 2016-06-07 at 10 19 19 am

This package will allow users to start a skype call with all room users.
Every user must fill its skype login. This info is stored on RocketChat.models.Users.
It shows the list of room users with skype login and without, so you know if someone still didn't filled the info.
And you have a skyppe button that uses the skype uri api to start the call. 
https://msdn.microsoft.com/en-us/library/office/dn745878.aspx#sectionSection0

I'm totally noob on meteor, css, .less and .coffee... I did a lot of copy and paste and probably made some pattern mistakes. 

There are some messages that must improve, but I dont know how to use the in18, etc....

### CODE REVIEW

**Comment by graywolf336** [comment]
Please add a setting which will have this disabled and have it be disabled by default. Also, is this for Skype or Skype for Business?

**Comment by hfsoares** [comment]
It is using The url api. In my machine, The Skype was opened. i dont have Skype for Businnes so I cant check if it Will work with it...
I Will add The settings

**Comment by graywolf336** [comment]
@hehsiao Thanks! Looking forward to the settings change, I'll have to see if there's something different for Skype for Business.

**Comment by rodrigok** [comment]
Hei @hfsoares do you need some help here?

**Comment by hfsoares** [comment]
Well, i cant find the time to do this... It is been a long, long run im my work and home...

**Comment by geekgonecrazy** [comment]
I apologize for the length of time that has passed on this.  In the near future we will be including Rocket.Chat Apps framework in the code base.  This is the type of feature that will be perfect for it.

Please see Apps issue here: #6890

**Pull request closed without merging**
