### PR TITLE
Add extention to filename if not included in download file

### LINKED ISSUE #3183: Pasting images to uploads, files are missing file extension
When I post image to a room from clipboard, it will save it as clipboard.. so when anyone downloads that file it will be with file format, and they can't open it, can we make it default to an image (JPEG)? 

or any other format if its audio or video?

Your Rocket.Chat version: (make sure you are running the latest)

### PR DESCRIPTION
**Pull request by nishimaki10**
@RocketChat/core 

Closes #3183

### CODE REVIEW

**Comment by rodrigok** [comment]
Hi @nishimaki10, this is a great idea.

But, why not use a node library of mime types collection like we are using here https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-assets/server/assets.coffee?ts=2#L2?

**Comment by nishimaki10** [comment]
Oh, I see. Your way is better. I will rewrite the code.

**Comment by nishimaki10** [comment]
I finished the code rewrite.

**Comment by engelgabriel** [comment]
@rodrigok can  you please review this?

**Comment by rodrigok** [comment]
@nishimaki10 Awesome, this looks great.

**Pull request merged**
