### PR TITLE
Migrations

### PR DESCRIPTION
**Pull request by marceloschmidt**

### CODE REVIEW

**Comment by engelgabriel** [comment]
LGTM

**Comment by rodrigok** [comment]
LGTM

**Comment by geekgonecrazy** [comment]
:+1: much needed

**Comment by NinoSkopac** [comment]
Guys, I am trying to migrate a RC installation from AWS t1.micro to t2.micro. I've saved and loaded Docker images, but I'm getting a "nodejs can't connect to mongo service" even though i loaded mongo imade first.

Nevertheless, after a lot of googling, I came across this new package, but I've no idea how to use it, since I'm a PHP dev.

So, how does one use this migrations package?

Thanks

**Pull request merged**
