### PR TITLE
add owner when changing from channel to private group - closes #1252

### LINKED ISSUE #1252: Bug - After converting default channel to a private group can no longer add users
It occurred to me that we've been using an open channel for discussions which would better be served from a private invite only group on our rocket.chat instance. It would be a shame to lose the history of the channel so I was wondering if there was a way to convert a channel to a private group?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27706258-add-a-facility-to-convert-a-channel-to-a-private-group?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Sing-Li**
applies to GENERAL which does not have an owner;  also replaces the existing public channel's owner with the administrator who changes a group from public to private (allowing him/her to add members immediately)

### CODE REVIEW

**Comment by marceloschmidt** [comment]
I don't think this is what one would expect. I think that, instead, we should be using permissions to check who can add users to the room, and give that permission to admins and room moderators by default. 
If we absolutely need a room owner (which I don't believe we do), then I think that when we set the first user to admin, we should add that user as the owner of the channels created by default.

**Comment by Sing-Li** [comment]
The problem is in the UI template code.   If there is no room owner ... it will not show the "add user" field at all.   GENERAL has no room owner.

**Comment by marceloschmidt** [comment]
That's what I meant... I think the "add user" field should check if the user has permission to add users, not if he/she is the room owner...

**Comment by rodrigok** [comment]
I agree with @marceloschmidt

**Comment by Sing-Li** [comment]
:smiley:   I also agree with @marceloschmidt.  Hence the `in progress` label.  Need a bit of time to get the layering right + tested and see if new authorization subscription impact this or not.

**Comment by marceloschmidt** [comment]
I think this PR is no longer required. Our migrations now set owner and moderator to channel and private group creators. When you change from channel to private group or vice versa, roles are kept. @Sing-Li what do you think?

**Comment by Sing-Li** [comment]
I :heart: it.   A  PR _auto fixes_ itself while sitting on the queue  :smile_cat: 

Wohoo!  

Thx  :+1:

**Pull request closed without merging**
