### PR TITLE
Add the join command

### PR DESCRIPTION
**Pull request by graywolf336**
This adds the `/join` command, allowing a user to type `/join #test` to join the test channel if they haven't already joined it.

Couple of notes:
* The channels listed when you start typing `#` are ones you've joined, so it feels pointless at the moment
* There is no error message if you type a channel you're already part of

Those two things should probably be discussed on another issue to determine how they should be handled.

### CODE REVIEW

**Comment by Morgul** [comment]
Out of curiosity, what happens when you try to join a channel that doesn't exist? Does it create that channel? If not, should it? IIRC, that's the default IRC (and Jabber?) use, but I haven't tried it in other systems.

**Comment by graywolf336** [comment]
Right now, it silently does nothing at all. I don't think it should create channels/rooms if they don't exist and you try to join them, as that could lead to a false impression of it already existing?

**Comment by Morgul** [comment]
You're right. What probably would be the best user experience, as I see it, would be to respond with an error message: 

"Channel `#foo` does not exist. Would you like to [create it]()?"

The `create it` link would of course be a link that opens channel creation in side bar, auto-populates the name with the channel the user tried to join, and focuses the correct input element.

**Comment by graywolf336** [comment]
Agreed with everything you said! :+1: We need a way to send messages to just one user which would show up in the channel an action was done and make it visible that the message is just for them to see and no one else could see it. (Hopefully that makes sense.) As that would be useful for what you described and also for handling errors with messages to send back to users.

**Comment by rodrigok** [comment]
Looks good, I will merge, please create new issues for these improvements

**Pull request merged**
