### PR TITLE
Add "mark message as unread" feature

### LINKED ISSUE #2856: Mark as Unread
I think this feature will come really handy.

I find myself multiple times where I read message, but forget to replay. If I don't put it as unread, its gone, and probably missing to replay to person.

What you think ?

### PR DESCRIPTION
**Pull request by reda-alaoui**
@RocketChat/core 

Closes #2856 

## Description
Added an action (icon-flag) on other users messages to be able to mark them as unread.

When the action is triggered:
- the message timestamp is taggued as the last seen in the user's room subscription
- the room unread messages counter is updated
- the room is closed and user redirected to /home to prevent message automatic read marking

## Action location
image

## Action consequence
image

### CODE REVIEW

**Comment by marceloschmidt** [comment]
I'm not sure I like this "User is redirected to /home" thing... I think that's not very user-friendly, but I can't think of something else. @RocketChat/core any ideas?

**Comment by marceloschmidt** [comment]
I've merged this with a few changes, regarding the counter in the unread indicator. We usually use the counter to indicate how many mentions there are, and not the amount of unread messages there.

**Comment by reda-alaoui** [comment]
Thank you :)

**Comment by xenithorb** [comment]
There's still no better way to do this? Whether it's intentional or not it's still a jarring experience and presents ltself like a bug

**Pull request merged**
