### PR TITLE
color change on online status to improve accessibility - issue  #3625

### LINKED ISSUE #3625: Improve accessibility of user status indicator for colorblind users
Your Rocket.Chat version: Windows App: 1.3.1, Server: Still an issue for me on the public demo server

As a colorblind user (red/green), I find it very difficult to determine the status of a user (available, away, etc.) from the small colored dot next to the name. Would it be possible to either customize per user which colors should be used, or, perhaps even easier, display a tooltip with the user's status when the mouse rolls over the status dot?

Thanks,
Josh

### PR DESCRIPTION
**Pull request by gabrielsixel**
@RocketChat/core 

Improves on  #3625 

I just change the color from the original #35AC19 (dark green) to a clear one #4dff4d (adding a 5% darker as border too), as requested in the issue.

### CODE REVIEW

**Comment by engelgabriel** [comment]
Thanks for the PR! Can you please add a BEFORE/AFTER screenshot to help people give feedback?

**Comment by gabrielsixel** [comment]
My bad.. 

Original: 
oie_ivnlvdvswv24

Modified: 
oie_azsxbkpqisur

Original: 
oie_sgombgpjevp7

Modified: 
oie_qixsu5vjmlsq

**Comment by marceloschmidt** [comment]
Should we make this into a user preference? Something like `Use colorblind friendly colors?` ?

**Comment by gabrielsixel** [comment]
I think that the colorblind or other accessibility options could be more than just the color, as pointed out in the issue, like changing the shape of the different status and adding title to the buttons (to enhance for the screen-readers).
This is more just a hot-fix than a preference, in my opinion.

**Comment by geekgonecrazy** [comment]
@gabrielsixel yeah I feel like this should be behind an accessibility preference.  Because I personally wouldn't want to see this new color.  It just doesn't fit.  But for someone that needs accessibility over visual they wouldn't necessarily care.

**Comment by engelgabriel** [comment]
image

**Comment by engelgabriel** [comment]
@karlprieb was this done on the big color update?

**Comment by karlprieb** [comment]
@engelgabriel No... and I agreed with @geekgonecrazy, maybe we can add an option to activate that. We can start with just colors and contrast adjustments and in the future add more changes like forms, font sizes, etc.

**Comment by engelgabriel** [comment]
I think the default colors SHOULD have enough contrast.

**Pull request closed without merging**
