### PR TITLE
 Doc: Corrected links to documentation of rocket.chat README.md 

### LINKED ISSUE #20525: Doc: Links to documentation is not correct in the README.md file
## Description
There are many links in documentation which are referring to https://rocket.chat/docs/
while that link is no longer in the official page and has changed to https://docs.rocket.chat/
As a result many links are giving a 404 error.

## Steps to reproduce
Correct the links

## Expected behavior
Direct to docs.rocket.chat

## Actual behavior
Direct to rocket.chat/docs

## Server Setup Information
None

## Version of Rocket.Chat Server
Current version of doc

### PR DESCRIPTION
**Pull request by joshi008**
Fix Documentation:
 

## Proposed changes

The link for documentation in the readme was previously https://rocket.chat/docs/ while that was not working and according to the website it was https://docs.rocket.chat/
The link for deployment methods in readme was corrected from https://rocket.chat/docs/installation/paas-deployments/ to https://docs.rocket.chat/installation/paas-deployments
Some more links to the documentations were giving 404 error which hence updated.

## Issue(s)
The link was not correct for documentation in the readme.

## Steps to test or reproduce
This requires no test

## Further comments

Closes #20525

### CODE REVIEW

**Comment by joshi008** [comment]
Could anyone please review it and tell if the links are correct or not

**Review by KevLehman — APPROVED** [review]
LGTM, thanks!

**Comment by KevLehman** [comment]
Can you please update your base branch with the tip of develop? Thanks!

**Comment by joshi008** [comment]
> Can you please update your base branch with the tip of develop? Thanks!

Thanks for reviewing @KevLehman . I have updated the branch with develop branch.

**Pull request merged**
