### PR TITLE
[FIX] reset the margin to solve to prevent cutoff usernames in the sid…

### PR DESCRIPTION
**Pull request by DanielRuf**
…ebar

@RocketChat/core 

But the issue seems to be the missing status indicator.

### CODE REVIEW

**Comment by DanielRuf** [comment]
See https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui-sidenav/client/chatRoomItem.js#L37

**Comment by DanielRuf** [comment]
The issue appears when we use a custom script which appends numbers to usernames (the internal phone number). Then we do not get any activity icon.

In general the negative margins seems to be there to "fix" the wrong icon size (which uses 1.25em, should be 1em).

bildschirmfoto 2018-03-06 um 09 10 25

**Comment by rodrigok** [comment]
@DanielRuf can you add screenshots from after and before your change?

**Comment by DanielRuf** [comment]
The issue is that the markup was changed and we use a custom script which adds a text after the username which also removed the new status div by accident (was not the case before) and you try to fix the size of the icons (which have no viewBox attribute or right size) by using negative margins which is not the right way to solve the wrong size of the icons in general and produced cutoff usernames ;-)

bildschirmfoto 2018-03-06 um 16 18 32

**Comment by karlprieb** [comment]
@DanielRuf thank you for you contribution.

The negative margin is fixing the positive margin of the children elements, so when you use RTL language we maintain the same margin without an specific css rule for rtl. We need to find another solution for that.

**Comment by DanielRuf** [comment]
> We need to find another solution for that.

Probably using the right widths for icons and using the dir="rtl" attribute on the html tag.

**Comment by karlprieb** [comment]
We use a generic size for icons, so we won't change that and we already use dir="rtl" when you change your language for a rtl one.

**Comment by DanielRuf** [comment]
> we already use dir="rtl" when you change your language for a rtl one.

Then we can already use that in the CSS for applying different styles instead of general styles for rtl and ltr languages.

**Comment by karlprieb** [comment]
We are using negative margin to NOT create more css for rtl specific margins/paddings.

We are not change the negative margin, as I said before we will need to find another way.

**Comment by DanielRuf** [comment]
Well, I've never solved rtl issues like this (with a negative margin) in any project. And there are node modules like rtlcss to help with the generation.

**Comment by karlprieb** [comment]
The problem is that our CSS bundle is huge already and we don't wanna increase our build, that's why we chose that technique.

**Comment by karlprieb** [comment]
You can put `flex: 0 0 auto` on `.sidebar-item__user-status` to fix that error, but don't change the margin.

**Comment by ggazzo** [comment]
@DanielRuf, are you facing this problem? Because I cant reproduce...

**Comment by DanielRuf** [comment]
I'll check again next week. I think some parts were already fixed.

**Comment by DanielRuf** [comment]
I guess we can close this.

> tassoevan (Tasso Evangelista) added the stat: waiting response  label 16 hours ago

This does not trigger any notifitcation on my side so I oversaw this.

**Pull request closed without merging**
