### PR TITLE
[FIX] Fix the wrong user priviledges for on the UI for MovingToTeam & ConvertToTeam buttons

### LINKED ISSUE #21584: [Teams] Wrong user priviledges and locales
### Description:

A new user can change public rooms to "Teams"

### Steps to reproduce:

1. Create a new user from an invite link
2. Join a public room
3. Click the little "room info" ("i" top left corner)
4. You can see two buttons "Move to Team" & "Convert to team"

image

### Expected behaviour:

Move and Convert should only be enable / visible for admins and room owner. 
Text is displayed in English instead of local language. Here, it should have been fr-FR

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.1

### PR DESCRIPTION
**Pull request by Jeanstaquet**
## Proposed changes (including videos or screenshots)

I added the right privilege to not display AddToTeam and ConvertToTeam for those who can't 

Before the changes

https://user-images.githubusercontent.com/45966964/114909360-5c04f100-9e1d-11eb-9363-f308e5d0be68.mp4

After the changes

https://user-images.githubusercontent.com/45966964/114909388-61fad200-9e1d-11eb-9bbe-114b55954a9f.mp4

## Issue(s)

Fixes #21584

### CODE REVIEW

**Comment by Jeanstaquet** [comment]
@dougfabris can you review please ? :)

**Comment by Jeanstaquet** [comment]
Hi @KevLehman, can you review plsease ? :)

**Review by dougfabris — APPROVED** [review]

**Comment by dougfabris** [comment]
> @dougfabris can you review please ? :)

@Jeanstaquet Thanks for helping us! We really appreciate your contribution and we would love to be quicker on the reviews, but as you can see there's a lot of work here! Please, don't mention each member of the core team, it can confuse us! Thanks =)

**Comment by Jeanstaquet** [comment]
@dougfabris Thanks for reviewing my PR, I will only mention one person from now on, thanks for the notice. 👍

**Comment by dougfabris** [comment]
> @dougfabris Thanks for reviewing my PR, I will only mention one person from now on, thanks for the notice.

will be fixed here: #22350

**Pull request closed without merging**
