### PR TITLE
[FIX] Change registration message when user need to confirm email

### LINKED ISSUE #9063: Misleading Info for New Users that are Manually Approved
When the setting for "Email Verification" and "Manually Approve New Users" are set to "True", upon registering, the new user is shown this information:

>REGISTRATION SUCCEEDED
>Before you can login, your account must be manually activated by an administrator.
>Please wait, this can take some time.
>Back to login

It doesn't mention that the user need to verify its email address first.

How to change the text?

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #9063

image

### CODE REVIEW

**Comment by graywolf336** [comment]
@karlprieb ping pong!

**Comment by ggazzo** [comment]
@karlprieb

**Comment by tassoevan** [comment]
This is shown instead of a toast message now:

image

**Comment by tassoevan** [comment]
With the correct logo:

screenshot from 2018-07-23 16-46-21

**Pull request merged**
