### PR TITLE
[FIX] Remove unique index from read receipt messageid 

### LINKED ISSUE #15484: Read receipts not working
### Description:

After updating to 2.1.0 the read receipts are not displayed anymore. No checkmark in browser, and only grey checkmarks in the app. No blue checkmarks after a message is read.

Also when showing message info, only the person who send the message is shown in the list.

### Steps to reproduce:

1. Direct chat or group chat
2. open message context menu, select info
3. only the person who wrote the message is shown, no one else, even if the message has been read

### Expected behavior:

* message read receipt shown in info
* blue checkmark in direct chat

### Actual behavior:

* In group chats: only the person who wrote the message is shown, no one else, even if the message has been read
* in direct chats no blue checkmark appears
 
### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.0
- Operating System: 4.19.72-gentoo, Ubuntu 18.04 LTE (tested on two systems)
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 4.2.0

### Additional context

* could be related to changes in #15316
* **could be a problem on our end because using MongoDB 4.2.0**

### Relevant logs:

Server log when accessing "info":

```
Meteor ➔ method getReadReceipts -> userId: RQySce2mbjTpGyxGt , arguments:  [ { messageId: '4cce12f2-60f4-443f-b253-46043a799eae' } ]
Meteor ➔ method canAccessRoom -> userId: RQySce2mbjTpGyxGt , arguments:  [ 'THG8ez3NKvCi9WoYv', 'RQySce2mbjTpGyxGt' ]
```

### PR DESCRIPTION
**Pull request by geekgonecrazy**
@rocketchat/backend we might have to create a migration some how to recreate this index or to remove unique from messageId?

This would fix #15484

### CODE REVIEW

**Comment by wreiske** [comment]
👀  😍

**Comment by geekgonecrazy** [comment]
@MarcosSpessatto should we dropIndex in migration and then ensure again?  Not sure best way to do this with the models

**Comment by rodrigok** [comment]
@geekgonecrazy I don't think this would solve the problem since the index added on the [PR merged](https://github.com/RocketChat/Rocket.Chat/pull/15316/files#diff-24c2f84b4f52df1d2d2c1b6c135ad6beR15) was not the one with the unique modifier.

We need to investigate this better since the compound index is correct there. Only one read per message per user is allowed.

**Comment by geekgonecrazy** [comment]
ah right.. thats a compound index.  mine is not valid then :grin:

**Pull request closed without merging**
