### PR TITLE
[enhancement] Sort by user roles

### PR DESCRIPTION
**Pull request by gsunit**
Beginning steps towards issue #13967. Currently displaying the role of the users under Members List. [This](https://github.com/RocketChat/Rocket.Chat/commit/4a9e1819d4281ba52a3e59958a174e1a1622807b), [this ](https://github.com/RocketChat/Rocket.Chat/pull/13976/commits/1d311922e8c2d8427e02aa5046e9c5ed33126bcb) and [this](https://github.com/RocketChat/Rocket.Chat/pull/13976/commits/a6d87eae0285def47908c27a086c9b89dd9e354b) commit contains the code. The rest is lint fixes. @engelgabriel please review the commits.

### CODE REVIEW

**Comment by gsunit** [comment]
Closes #13967. Finally implemented sort based on user roles. The hierarchy for sorting can be changed easily by changing the order of roles in the array ([refer this commit](https://github.com/RocketChat/Rocket.Chat/pull/13976/commits/a6d87eae0285def47908c27a086c9b89dd9e354b)).

**Comment by engelgabriel** [comment]
hi @gsunit sorry to the late review. I think you need to update your branch in order for us to be able to see your changes. 

The current DIFF of this PRs is showing a lot of changes that our revert work done by others.

**Comment by gsunit** [comment]
I have made the necessary changes, the feature is working just fine. Please let me know if anything else needs to be changed.

**Comment by engelgabriel** [comment]
HI @gsunit you need to sync your branch with develop. The PR still looks a bit messy, with conflicts and lots of file changes that would revert previews commit from other contributors.

**Comment by gsunit** [comment]
No problems! Shall I create a new PR? The thing is each time I solve the conflicts, as soon as there is new development in the develop branch the conflicts appear again. Unfortunately, I have semester exams this week, I will be able to create a new PR after resolving the conflicts by the end of this week. Hope that's not a problem.

**Comment by gsunit** [comment]
Closing this PR now. The new one works just fine! :)

**Pull request closed without merging**
