### PR TITLE
Livechat Transcript

### LINKED ISSUE #4079: Feature Request : Send completed LiveChat as e-mail
Hello guys,

we'd like to request a feature that is currently keeping us from implementing LiveChat: The ability to forward the content of completed/closed livechats automatically via e-mail. Ideally, this would be triggered when the livechat is closed, sending all messages with usernames and timestamps from this livechat to a single e-mail address the admin can configure. That way any ticket system can receive the communication and agents can book their time.

Thanks in advance

### PR DESCRIPTION
**Pull request by AlecTroemel**
@RocketChat/core 
Closes #4079 

This adds the option for livechat guest's to have a transcript of their chat emailed to them when a room is closed (either by a guest or agent). 

|  screen shot 2016-10-03 at 12 12 38 pm | screen shot 2016-10-03 at 12 50 28 pm  |
|---|---|

screen shot 2016-10-03 at 1 01 29 pm

Under the hood the livechat widget now tracks the 'state' of a chat, and when the state changes a corresponding function is invoked. Currently valid states are

- connecting: currently not connected to any agent, but room is created 
- connected: in chat with agent 
- closed: the chat has been closed  

but these can be expanded on easily. I set it up this way because of other features I plan to PR (replacing message prompt with "connecting to agent ..." when in connecting state, show discloser  message on connect, etc)

### CODE REVIEW

**Comment by sampaiodiego** [comment]
hey @AlecTroemel thanks once again for the awesome contribution =)

I have two comments about your PR:

- I think there is no need to create another flag to control the room state. we already know it's state using the existing fields.. something like this:

State | `open` | `waitingResponse` | Description
------- | ---------| ------ | ----
connecting | `true` | `true` | currently not connected to any agent, but room is created
connected | `true` | `undefined` | in chat with agent
closed | `undefined` | `undefined` | the chat has been closed

- Another thing we are trying **not** to do is using Meteor's publish/subscribe.. we are using _stream_ to accomplish the same result.

I can help you with both items if you want.. just please let me know :smiley:

**Comment by AlecTroemel** [comment]
Nice! No need to duplicate what's already available. After looking at stuff a little more, do you think  triggering the transcript prompt should done though a command message being sent when the room is closed, similarly to how the survey is initiated here?https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-livechat/app/client/lib/_visitor.coffee#L39

The other option I can think of would be to listen for changes to `open` and `waitingResponse` and prompting when the conditions change to close.

**Comment by sampaiodiego** [comment]
yeah, triggering it by a command message I think should be great.

**Comment by sampaiodiego** [comment]
Thanks again @AlecTroemel 

I did some fixes/improvements (80bb9d685f519541aa76d0e4f9bbe1db973e5a59, 725fa52ff1250fa5dd19f1bff6fc96fc44d31936, 5e65b5f99b8ebb5fe08bf37b360ae29a422c823c, d0afa3f037243ac587f945d2c03544114a763dc0, 6e72100ebb9bd812fec567a0a1969fe4e93adc33), hope you like it :smile:

**Comment by AlecTroemel** [comment]
Nice fixes, thanks!

**Comment by paulhibbitts** [comment]
This will be a great feature for educational uses of RocketChat! I've already had students requesting a Livechat transcript for their virtual office hours (http://paulhibbitts.net/cmpt-363-163/) sessions.

**Comment by CONFORM-IT** [comment]
Nice!
Does the popup window appear for the livechat guest or the livechat agent, or for both? Both would be ideal so the visitor has a protocol and the agent can forward this to a ticketing system. 
Is this feature already part of 0.43.0?

**Comment by AlecTroemel** [comment]
@CONFORM-IT currently it only appears for livechat guest's, but I don't think it would be too hard to extend it to agents as well. And yes I believe it is in the most current build of rocketchat

**Comment by CONFORM-IT** [comment]
@AlecTroemel having that option for agents/internal users too would be great.

**Pull request merged**
