### PR TITLE
[NEW] Add option on Channel Settings: Hide Notifications and Hide Unread Room Status (#2707, #2143)

### LINKED ISSUE #2143: Add feature to snooze/mute notifications
Because sometimes you've got to focus :)

I like the idea of snoozing **all** notifications for X amount of time as well as muting/limiting notifications from individual channels (with options to allow @username mentions and highlight words)

# Slack options:

### LINKED ISSUE #2707: Mute channel function
If there'll function "mute channel" like in slack it will be great. )

### PR DESCRIPTION
**Pull request by marceloschmidt**
@RocketChat/core 

Closes #2707
It doesn't cover snooze, but helps #2143.

### CODE REVIEW

**Comment by sampaiodiego** [comment]
prints pls 😊

**Comment by marceloschmidt** [comment]
image

image

image

**Comment by engelgabriel** [comment]
I am just a bit worried about the UX... I was expecting mute to be a boolean... we need to review the notifications UI as a whole.. the Unread Alert is also confusing.

**Comment by lucasvanhalst** [comment]
Mute should just turn off all kinds of notifications IMO

**Comment by graywolf336** [comment]
I think the term "mute" is a little bit odd here, from the screenshots. If you have "Everything" selected, then are you muting everything or are you allowing everything? Same goes for "Nothing" selected, would nothing be muted or would nothing be allowed?

**Comment by marceloschmidt** [comment]
Can we please pick a better wording for this and merge it? Let me know the best wording and I'll fix the conflicts.

**Comment by marceloschmidt** [comment]
Changed wording:

image
image

Please merge? :)

**Comment by marceloschmidt** [comment]
@sampaiodiego finished solving conflicts. could you and/or @rodrigok review this please? I would like to have it merged.

**Pull request merged**
