### PR TITLE
[IMPROVE] Add setting To not allow thread messages in Main Channel

### PR DESCRIPTION
**Pull request by shrinish123**
## Proposed changes (including videos or screenshots)

This feature was requested by a user @ksrx on PR #21553. This setting will stop the new users from sending the thread messages in the main channel if the admin wants too.

https://user-images.githubusercontent.com/56491104/116806092-6c6cd980-ab48-11eb-9034-276997f1dcc3.mp4

This will stop users from sending messages to the main channel if the admin doesn't allow it.

### CODE REVIEW

**Review by ksrx — APPROVED** [review]

**Comment by shrinish123** [comment]
@sampaiodiego Please Review

**Comment by dougfabris** [comment]
Hey @shrinish123 
We're going to deprecate `show message in main thread` because of that, there's no reason to add a new setting to not allow it. Thanks for your contribution!

**Comment by ulope** [comment]
@dougfabris Either I'm misunderstanding our you are 😅 

The PR you linked doesn't remove the `show message in main thread` functionality at all. It just removes the preference.

What is being asked here and is **very much** needed is an admin option to prevent users from changing this option themselves. 
In our org (and I can imagine many others as well) we never want the thread messages to "contaminate" the main thread.

**Comment by dougfabris** [comment]
@ulope Hmmm. I understood what you said here. IMO if the admin doesn't want the users to display the thread message in the main message, on the UI side we shouldn't even show the Also send to channel option. I will re-open this one and verify with our product team.

**Pull request closed without merging**
