### PR TITLE
[NEW] Option to mute group mentions (@all and @here)

### LINKED ISSUE #1654: Turn off notifications for @all type mentions
Please allow users to turn off notifications for @all  - every time my browser makes a noise I have to stop whatever I am doing, switch to the browser, hunt for the tab that made noise, find the channel that has a notification, and discover somebody just asked "how are you doing?". Right now I close the browser out of self-protection or I get nothing done at all, but I don't always remember to open the chat session again to find out how cow-orkers are doing and I miss stuff because of a feature that is initially supposed to help me  NOT miss things
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29105639-turn-off-certain-notifications?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Hudell**
Closes #1654 

This PR adds a new preference on the channel notification settings to mute `@all` and `@here` mention notifications.

### CODE REVIEW

**Comment by graywolf336** [comment]
Is this a user preference? I am just thinking that there can be some channels, like say announcements, which admins of a server don't want people to turn off this type of notification...any ideas?

**Comment by Hudell** [comment]
It's a user preference, per channel.

Allowing admins to disable this preference for certain channels would also be a nice feature to have, but I don't see it as a requirement.

**Comment by karlprieb** [comment]
Maybe we should merge this PR and create another issue to work on this "improvement", what you guys think?

**Comment by graywolf336** [comment]
Do we currently have an option for admins to disable notifications preferences for users?

**Comment by geekgonecrazy** [comment]
@Hudell what do you think about calling it group mentions instead of generic?  I think its a bit more meaningful. 

I think this would be a great thing to have.

**Pull request merged**
