### PR TITLE
[FIX] Image attachment re-renders on message update

### LINKED ISSUE #5028: Editing reaction emoji to an image causes it to go back to 'click to load'.
Your Rocket.Chat version: [I am still not aware of any way for a non-admin user of Rocket.Chat to obtain this information. Please let me know how to do this if possible.]

When I 'click to load' an image, and then someone adds or removes a reaction emoji on the message, the image goes back to the 'click to load' state.

### PR DESCRIPTION
**Pull request by Kailash0311**
Closes #5028 and #14092 

**Issue and research**: On researching and playing around with codebase a bit I found out that message is re-created everytime someone updates the message, (e.g: Starring or adding a reaction as mentioned in the issues that this PR solves.)Since it is meteor's default reactivity system because of which it is happening, my resolution is a simple work-around.

**Resolution**:  Add a `onDestroy` function to the lazyloadtemplate(This template is responsible for showing the preview of the attachment.) This template gets destroyed and recreated whenever there is some update in the message (e.g: Starring or adding a reaction). Workaround is a simple `Template.onDestroy` call that stores the value of `loaded` state before being destroyed because of the update in the message. So whenever the template is recreated, now `this.loaded` has the same state as what was before updating a message(or being destroyed).

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@RocketChat/core if this solves... this would be amazing to include.  An extremely annoying issue

**Comment by geekgonecrazy** [comment]
Does this work for others?  Like say youtube embed?

**Comment by Kailash0311** [comment]
> Does this work for others? Like say youtube embed?

No, it doesn't because youtube embed doesn't depend upon lazyloadImage package. But I guess the strategy would be the same there too.

**Comment by rodrigok** [comment]
@Kailash0311 Ok, but with your solution ALL images will share the same control variable right? Doesn't that defeats the purpose?

**Comment by rodrigok** [comment]
A possible solution may be creating a `Set` to act as a cache where you store the `src` and every time you create the template instance you define the loaded initial state as true if the src already exists in Set.

**Comment by rodrigok** [comment]
To be clear, this will not stop the re render @geekgonecrazy , will just prevent the render of the preview/base64 image and then the original image, so it may blink less, but videos would back to the initial state due to the re render. To solve that we need to remove NRR or move to another template language,

**Comment by geekgonecrazy** [comment]
Ah!  So this is only preventing the blury base64 to regular.  Since the other image is already downloaded it re-renders fast enough you don't notice it.

Drats.. I was hoping solving it really was this simple as its an extremely annoying issue.

Avoiding the blurry to clear flicker still would be a welcome change though

**Comment by Kailash0311** [comment]
> @Kailash0311 Ok, but with your solution ALL images will share the same control variable right? Doesn't that defeats the purpose?

Oh, yes. How could I not see that! That is why new images were never loading the preview image.
Thanks!

**Comment by Kailash0311** [comment]
> A possible solution may be creating a `Set` to act as a cache where you store the `src` and every time you create the template instance you define the loaded initial state as true if the src already exists in Set.

Do you mean using set method in Session package that meteor provides?

**Comment by Kailash0311** [comment]
> To be clear, this will not stop the re render @geekgonecrazy , will just prevent the render of the preview/base64 image and then the original image, so it may blink less, but videos would back to the initial state due to the re render. To solve that we need to remove NRR or move to another template language,

Yes, this will not stop re-render as the message itself is being rendered altogether. This will just skip the loading of the preview image and directly load the main image.

**Comment by rodrigok** [comment]
@Kailash0311 I mean the Set class https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by Kailash0311** [comment]
> With this changes ALL images will share the same control variable.

Yes, I understood it.

**Comment by Kailash0311** [comment]
In the recent changes, the PREVIEW image will not be re-loaded when the message is re-rendered.

**Pull request merged**
