### PR TITLE
Fix RocketChat/Rocket.Chat#329. Check for duplicate name before creating Channel and Private Group.  Also, check Private Group for illegal name. 

### PR DESCRIPTION
**Pull request by rwakida**
channel or private group

Queried ChatRoom for Room with same name and returned a descriptive
error if one was found when creating a Channel or Private Group.

### CODE REVIEW

**Comment by sampaiodiego** [comment]
hey @rwakida , thanks for PR

the throwed messages are displayed to user? if so, can you change it for translations? like [this](https://github.com/RocketChat/Rocket.Chat/blob/master/client%2Fviews%2Fapp%2FsideNav%2FprivateGroups.coffee#L3)

**Comment by rwakida** [comment]
Hi @sampaiodiego, sorry, I forgot about internationalizing it.  =)

I'll add it to the en.il8n.json, but what about the other languages?  Do I add it in English so it's not forgotten?

**Comment by sampaiodiego** [comment]
Exactly. Do it only for english, other languages will be translated later
on lingohub, it alerts about new words to be translated :)

Em qui, 23 de jul de 2015 16:26, Reid Wakida <notifications@github.com>
escreveu:

> Hi @sampaiodiego <https://github.com/sampaiodiego>, sorry, I forgot about
> internationalizing it. =)
>
> I'll add it to the en.il8n.json, but what about the other languages? Do I
> add it in English so it's not forgotten?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/pull/330#issuecomment-124217750>
> .
>
-- 
.Diego Sampaio

**Comment by rwakida** [comment]
HI @sampaiodiego.  I updated the code to use il8n.  Also, I realized that private groups didn't check for illegal names like channel does so I added the validation to createPrivateGroup.coffee.

**Comment by sampaiodiego** [comment]
well done @rwakida .. thank you again =)

**Pull request merged**
