### PR TITLE
[NEW] Show user's status description by the usernames in messages list

### PR DESCRIPTION
**Pull request by wreiske**
This is a work in progress.... I can't seem to get them to be reactive! Maybe @Hudell knows?

status_bubbles_messages

image

The status bubble only shows if the user has a status message. The status text displays when you hover over the status bubble.

### CODE REVIEW

**Comment by tassoevan** [comment]
@wreiske This is super tricky. Due to performance issues, the `message` template is non-reactive, only re-rendering when the message object is updated that its collection.

BTW, should this feature not be added only after setting an emoji for a custom status? I believe this was removed from the feature, right?

**Comment by wreiske** [comment]
> @wreiske This is super tricky. Due to performance issues, the `message` template is non-reactive, only re-rendering when the message object is updated that its collection.
> 
> BTW, should this feature not be added only after setting an emoji for a custom status? I believe this was removed from the feature, right?

I was thinking to do this one in steps... adding emojis to a status text, and assigning an emoji to a message is two different things. 

image

image
image

If there is no emoji set for the status, it shows the bubble.

image

**Comment by wreiske** [comment]
Now that NRR is pulled, I'm wondering if this will just work? 🤔 @ggazzo

**Comment by wreiske** [comment]
🥳

**Pull request merged**
