### PR TITLE
[FIX] Wrong message count statistics in Admin info page

### LINKED ISSUE #10233: Message count in statistics is strange
### Description:

In the admin info panel Rocket.chat displays usage statistics. However, it seems that the message count is not correct.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.1

### Actual behavior:

usage-count

=> as you see, the sum of all message is not correct if 

`Total Messages = Total Messages in Channels + Total Messages in Private Groups + Total Messages in Direct Messages + Total Messages in Livechats`

### LINKED ISSUE #12610: Not displayed the number of users and messages in private and public channels on the page /admin/rooms
### Description:
On the page
https://xxxxxx/admin/rooms
The current number of members of the channel or private group is not displayed, but the number of users in personal correspondence is displayed.
Also included recycling on this channel in the admin displays 1084 messages, and in fact there are only 10.

### Actual behavior:
image
image
image

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.1
- Operating System: Debina 9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enable
- NodeJS Version: 8.11.3
- MongoDB Version: 4.0.4

### PR DESCRIPTION
**Pull request by subham103**
Closes #10233
Closes #12610

Previously, the message count for every Room is increased upon message addition but is not updated upon the deletion of a message #12610. So, upon the removal of messages, the message count of rooms shows the wrong message count.

Now the message count of each room is updated upon message deletion, which makes the message count of each room error-free.
So it will be better if we sum up the four values(4 different types of rooms: PrivateGroupMessages, ChannelMessages, DirectMessages, LivechatMessages) to get the exact total message count.

### CODE REVIEW

**Comment by gabriellsh** [comment]
Closes #12610

**Comment by ashwaniYDV** [comment]
@subham103 You can rename the function as `decMsgCountById` to keep it consistent with `incMsgCountById` as @gabriellsh suggested :)

**Comment by subham103** [comment]
@ashwaniYDV, actually he already renamed it in one of his commits :p

**Comment by subham103** [comment]
@gabriellsh @ggazzo could you please merge this pr?

**Pull request merged**
