### PR TITLE
Avoid sending of images whose links are in markdown messages

### PR DESCRIPTION
**Pull request by sumedh123**
@RocketChat/core 

Closes https://github.com/RocketChat/Rocket.Chat/issues/9942

screen shot 2018-03-01 at 12 11 06 am

### CODE REVIEW

**Comment by sumedh123** [comment]
@karlprieb @rafaelks Please review.

**Comment by karlprieb** [comment]
@sumedh123 I tested your branch and now we are not getting url previews in all type of messages. I think we shouldn't get previews only on `code` message, right?

**Comment by sumedh123** [comment]
@karlprieb I will check it once again and let you know asap.

**Comment by gdelavald** [comment]
@sumedh123 are you planning on fixing the issues here or should we take over? Thanks!

**Comment by sumedh123** [comment]
@gdelavald Sorry, this issue was kinda left behind. If you want to take over, please feel free to.

**Comment by karlprieb** [comment]
So @sumedh123 can I close this PR?

**Comment by sumedh123** [comment]
@karlprieb Yes, you can close the pr. I will still keep a track of this issue. If no one picks this issue up, I will try once again.

**Pull request closed without merging**
