### PR TITLE
[FIX] Stream not connecting connect when using subdir and multi-instance

### LINKED ISSUE #13200: Clustering not working when using a ROOT_URL with a subpath
### Description:

When configuring a ROOT_URL for Rocket.Chat on a subpath (ex: https://awsome.tld/rocketchat1), the clustering feature does not seem to work properly. The instances are discovered, but the broadcast status as displayed in the admin's information page ("Current Status > Connected") is always empty and the "Current Status > Status" is either set to "waiting" or "connecting" but never "connected". I tried activating the debug & info logs in the server settings and saw this:
```
StreamBroadcast ➔ Auth.info prevent self connect 10.42.11.126:3000
StreamBroadcast ➔ Connection.info connecting in 10.42.12.64:3000
```

If I change the ROOT_URL to  https://awsome.tld, I start to see these logs:
```
StreamBroadcast ➔ Connection.info connecting in 10.42.12.64:3000
StreamBroadcast ➔ Auth.info Authorizing with 10.42.12.64:3000
StreamBroadcast ➔ Auth.info broadcastAuth with 10.42.12.64:3000 true
```
and the instances seem to be communicating correctly again in the Admin's Information page.

--

### Steps to reproduce:

1. Set a ROOT_URL with a subpath
2. Create a Cluster with several instances of Rocket.Chat

### Expected behavior:

The broadcast cluster should work event with a subpath.

### Actual behavior:

The Rocket.Chat instances see each other but do no communicate an broadcast notifications to each other.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.1
- Operating System: PhotonOS 2.0
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.3
- MongoDB Version: 4.0.5

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Fixes #13200

### CODE REVIEW

**Comment by sampaiodiego** [comment]
this is tricky since the websocket path handled by meteor is always on the root.. because of that, this PR doesn't work.. but if the `INSTANCE_IP` is set to go through the reverse proxy, it *needs* to have the subdir part.

**Comment by geekgonecrazy** [comment]
That's not the case though.  direct IP to IP in a cluster setup it doesn't work.  :(

I even tried on my local dev machine and it wouldn't connect.  No proxy involved. 

If ROOT_URL is set to: http://localhost:3000/rocketchat the instance refuses to respond to anything on / it will only respond on /rocketchat/

With this change locally anyways this worked with 3 instances where as with out this change they all sat there saying connecting.

What can we do different to make this work?

**Comment by sampaiodiego** [comment]
On my local setup it was the opposite. I'll have to give it another try.

Em sex, 3 de mai de 2019 18:24, Aaron Ogle <notifications@github.com>
escreveu:

**Comment by geekgonecrazy** [comment]
Let me know.  :grin: I gave the docker image to someone that used subfolder and had a multi-instance in a k8s cluster and this fix seemed to do the trick.  Maybe we need to add more conditionals to make it work in other scenarios?

Oh btw when testing locally I had issues apparently meteor registers on a different random port and then proxies 3000 through or something?  I had to hop into .meteor/local/build and execute `node main.js` with PORT=3004 and another terminal with PORT=3005 to truly test it.

**Comment by geekgonecrazy** [comment]
Good!  🤗

**Pull request merged**
