### PR TITLE
[BREAK] remove old livechat client

### LINKED ISSUE #13156: Send buttons is not shown on IE11
### Description:

Send Icon is not shown on smaller screen less than 500px

- Version of Rocket.Chat Server: 0.72.3 
- Operating System: windows 10

I was Manage to solve it by adding custom CSS

/* IE11 bug send button is not shown */
@media only screen and (max-width: 500px) {
  .rc-message-box__send {
    flex-basis: 45px
  }
}

Extra: cursor is not defined for send button
.rc-message-box__send {
  cursor: pointer
}

### LINKED ISSUE #14004: Livechat widget issue : no toolbar with IE11 & running away from mouse cursor.
### Description:

1. When I open a test page with livechat installation script provided from Rocket.Chat management console in Internet Explorer 11, the livechat widget has problems.
- when minimized, it shows maximize, alarm, and popup icon on the right side of the title bar.
- when maximized, those icons are now shown, precisely, they are located at much lower posion from the original position and seems invisible because of their white color. Style applied to the .title class has line-height property which should be inherited to .title .toolbar class but not applied.

2. Sometimes when I try to click toolbar icons whit chrome or edge, and sometimes when I move mouse cursor to the widget with IE, then the widget moves to the left and escapes from the monitor scrren as if it hates and tries to escape from the mouse cursor invation.

### Steps to reproduce:

1. Make a test html page with the javascript presented to you on livechat - installation page of the admin console
2. Open that page with a browser such as Internet explorer and chrome
3. Enjoy...

### Expected behavior:

Toolbar icons is shown when maximizing the widget when I open the test page in IE11

### Actual behavior:
Toolbar icons is not shown when maximizing the widget when I open the test page in IE11
Livechat widget goes left and leaves the monitor screen when I click the widget(Chrome) or move mouse cursor to the widget(IE11)

### Server Setup Information:

- Version of Rocket.Chat Server:  0.73.4
- Operating System: CentOS 7
- Deployment Method: Manual Installation
- Number of Running Instances: 1
- DB Replicaset Oplog: No
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6

### PR DESCRIPTION
**Pull request by ggazzo**
closes #14004
closes #13156

### CODE REVIEW

**Comment by reetp** [comment]
Surely you can't be pushing this out until you have given an option to disable the showing of user Avatars and Personal names???

I don't want my staff avatars or their full names showing outside of work thanks. GDPR & all that.

This needs fixing first. 
https://github.com/RocketChat/Rocket.Chat/issues/12908

Tagging it to this:
https://github.com/RocketChat/feature-requests/issues/135

**Comment by engelgabriel** [comment]
Thanks for the heads up @reetp we will prioritize this feature.

**Comment by engelgabriel** [comment]
@reetp just to be clear, is there ANY functionality on the OLD widget that is not present on the NEW one? From what I've read, the issue you mentioned is a problem on both, right?

**Comment by reetp** [comment]
> @reetp just to be clear, is there ANY functionality on the OLD widget that is not present on the NEW one? From what I've read, the issue you mentioned is a problem on both, right?

Yup..... looks like it. I hadn't checked/tested the old one for some long while....  my bad.

I can see that the Full Name, Avatar and Email address are all visible... I thought that was only on the new one. That is shocking. Not sure where I missed that.

Yes, I can see the Email address can be turned off in admin/Livechat.

But the Avatar and Full Name can't. Sometimes my users upload joke avatars - say birthdays or whatever etc - I don't want clients seeing that.

Nor do I want their full names on display.

So now I have realised, this is a complete disaster. I'll have to disable chat from my site.

**Comment by engelgabriel** [comment]
We will add a toggle to turn of avatars and full names before we release 2.0.0

**Pull request merged**
