### PR TITLE
[FIX] Fix small images being scaled up

### LINKED ISSUE #11513: Small images receive height of 200 pixels
### Description:

When pasting small images into chat that are less than 200 pixels high, they are resized in chat to have a height of 200 pixels, i.e. they are scaled up and much bigger than they should be.

### Steps to reproduce:

Take a screenshot of an image that is less than 200 pixels high, e.g. just 100 pixels high.
Paste the image into a chat.
Note that the image is resized in the chat to be 200 pixels high.

### Expected behavior:

Images that pasted should have a maximum height of 200 pixels but if they are smaller, they should not be scaled up.

### Actual behavior:

Example of an image that is 50 pixels high pasted into chat:

screenshot_20180720_081116

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.2
- Operating System: Ubuntu Linux (x64)
- Deployment Method: snap
- NodeJS Version: v8.11.3
- MongoDB Version: 

### Additional Information:

The height is set directly on the element style, i.e. not through a class.

### Temporary Workaround:

In the Layout > Custom CSS, have made the following addition:

```
img.gallery-item { height: auto }
```
Images that are larger than 200px high are managed by the `max-height` setting in the `gallery-item` class.

### PR DESCRIPTION
**Pull request by ledlamp**
Closes #11513; the height attribute is not necessary as the CSS already specifies a max-height of 200, but this attribute causes images with a height less than 200px to be scaled up.

Before:
https://n546.qonq.gq
After:
https://e0oi.qonq.gq

As you can see the CSS already specifies max-width: https://9o8w.qonq.gq

Removing the height attribute fixes it:
https://roee.qonq.gq
While large images are still limited to 200px height.

### CODE REVIEW

**Comment by ledlamp** [comment]
(Regarding the above commit) I just encountered this issue again with attached images. They also have a `height` html attribute but it's based on the image height in the attachment JSON. I had a bot sending attached images without the height attribute, and in that case the getImageHeight() function defaults to 200px and the issue appears. Again, the height attribute is completely unnecessary and stupid; CSS already takes care of it.

**Comment by ledlamp** [comment]
TODO probably want to remove `height="200"` from [app/oembed/client/oembedUrlWidget.html](app/oembed/client/oembedUrlWidget.html) too but not sure if CSS sets max-height: 200px on those, and well I can't even find any site that activates the large one.

**Comment by rodrigok** [comment]
@ledlamp the fixed height value is necessary to prevent the messages list to keep jumping while loading the images since the height can not be guessed before the image load.

**Comment by rodrigok** [comment]
@ledlamp would love to hear from you a better solution for this, otherwise, we will need to keep the **necessary** and **not stupid** solution.

**Comment by rodrigok** [comment]
We apologize for not getting a review on this sooner. 

It's not a problem anymore
image

I'll close this PR for now, let us know if the issue persists in some way.

**Comment by ledlamp** [comment]
> We apologize for not getting a review on this sooner.
> 
> It's not a problem anymore
> image
> 
> I'll close this PR for now, let us know if the issue persists in some way.

I should have clarified this issue didn't occur with attachments (except attachments with unspecified height, like if you send it with a bot), but with images embedded from urls.

I just tested it on open.rocket.chat and it seems nothing has changed.

**Comment by ledlamp** [comment]
> @ledlamp the fixed height value is necessary to prevent the messages list to keep jumping while loading the images since the height can not be guessed before the image load.

I've never noticed or had a problem with this issue after implementing my modifications, but the image issue was a terrible issue for me as I always use my own image host.



> @ledlamp would love to hear from you a better solution for this, otherwise, we will need to keep the **necessary** and **not stupid** solution.

Sorry but I ended up not using rocket chat anymore so I can't bother; but the height attributes to fix that other issue seems like a hack fix, and that other issue should be fixed properly without creating new and worse issues.

**Pull request closed without merging**
