### PR TITLE
Pin/Unpin functionality

### PR DESCRIPTION
**Pull request by geekgonecrazy**
I'm a bit of a meteor noob.. Ok total noob.  But here is my attempt to add pin/unpin functionality.

This would add the fields `pts` and `pinned` to the messages.

`pts` being pinned time stamp.  This is needed to allow grabbing subsets of pinned as well as displaying when message was pinned.

Related to #310 

I don't have all i18n files updated either.

### CODE REVIEW

**Comment by rodrigok** [comment]
Looks really awesome, you are not so crazy after all :smile_cat:

**Comment by geekgonecrazy** [comment]
Lol!  This is debatable!

**Comment by rodrigok** [comment]
Just waiting for the interface implementation.

**Comment by geekgonecrazy** [comment]
Soon as the tab system is figured out and the UI respect of edit/delete/pin that should be pretty easy

**Comment by marceloschmidt** [comment]
Tab system is ready. @geekgonecrazy are you working on this implementation, os shall I pick up from where you left?

**Comment by geekgonecrazy** [comment]
@marceloschmidt if you want to pick up on that feel free.  Heh i've got so many different pieces up in the air.

**Comment by marceloschmidt** [comment]
I'll do it ;) thanks

**Comment by marceloschmidt** [comment]
@geekgonecrazy As per your implementation, one should only be able to pin their own messages? I'm not sure that is really useful... I think there are two alternative implementations for this:

1. Users can pin anyone's message and the pinned messages will appear for that user only.
2. Admins can pin anyone's message and those messages are displayed for everybody in the channel.

@RocketChat/owners what do you think?

**Comment by sampaiodiego** [comment]
this is the expected behavior to me @marceloschmidt .

but, admins should be able to pin messages only to him.

**Comment by geekgonecrazy** [comment]
That's pretty much how I was thinking.  Admins / future moderators / channel creator can pin channel wide.

I was kinda thinking it might be broken up pins for this behavior and staring being at the individual level

**Comment by sampaiodiego** [comment]
I think pinned messages should be global.. only admins can do it..

if you (normal user) wants to "save" a message, you should **star** it! or some another term for that.. but it should be two different commands to not confuse people.

**Comment by graywolf336** [comment]
I think anyone in the channel should be able to pin messages - for small teams there isn't a need to add complexity. So, maybe this needs to be configurable instead of just one set way.

**Comment by geekgonecrazy** [comment]
Yeah I agree small teams I can see this being useful for pinning links etc during research phase and want others to be able to access it

**Comment by sampaiodiego** [comment]
yeah.. it should be configurable..

but I think that you should pin everyone's messages and it will be always visible pinned to everyone. like @marceloschmidt said on second option.

**Pull request merged**
