### PR TITLE
[NEW] LDAP Group Sync

### LINKED ISSUE #2759: Room/Channel/Group Membership based on LDAP group membership
Your Rocket.Chat version: 0.24.0

Hi

I would like the ability to assign membership to a Room/Channel/Group via a group in a LDAP directory. This way we can set the membership once and not update it every time someone new comes on board.

I think this would be particularly useful for Private Groups, where we have people come and go within the organization. 

Thanks

### PR DESCRIPTION
**Pull request by dlang9159**
Closes #2759 #11710 #5252 #5086

This PR is my first draft for synchronisation of LDAP Group membership and RocketChat Private Group or Channel membership.

Currently the sync is part of the user sync. When a user is synced, it also looks up all the LDAP groups the user is in and adds the user to the room, or creates a new room for the corresponding LDAP group. After that, it checks if the user was removed of any group on the LDAP side and duplicates the removal in RocketChat.

Because I only have a limited testcase (LDAP server with only specific settings) I am not able to test all possible configurations and therefore I am glad to here feedback.

### CODE REVIEW

**Comment by SonikV** [comment]
Good afternoon, tell me how to set up synchronization and creating channels depending on the membership of a particular group AD

how too enable this package packages/rocketchat-ldap/ ?

**Comment by dlang9159** [comment]
I guess, this is ready for a review. Or did I miss something? If yes, I'm glad to hear and fix it soon.

**Comment by romuloslv** [comment]
any prediction of when it will be available?

**Comment by dlang9159** [comment]
> any prediction of when it will be available?

Sorry to disappoint you, but I can not make any predictions. Because of some changes in the Rocket.Chat code I have to rework my initial code changes. Also I wait for feedback for my code.

**Comment by dlang9159** [comment]
Closed in favor of #14278

**Pull request closed without merging**
