### PR TITLE
Rocket.Cat Shouldn't be Admin

### LINKED ISSUE #1632: Admin user role undefined on initial account
I deployed a fresh clone from github tonight, launched via "meteor" and registered the initial user, expecting the admin user role to be automatically assigned. It wasn't. The admin user had no admin access. 

Console output in relevant part:

```
I20151210-20:11:35.450(-7)? [publish] admin-settings
I20151210-20:11:35.451(-7)? [methods] hasPermission ->  arguments: { '0': 'QKKXCYBxZZjjtKDoP', '1': 'view-privileged-setting' }
I20151210-20:11:35.451(-7)? [methods] getRolesForUser ->  arguments: { '0': 'QKKXCYBxZZjjtKDoP', '1': undefined }
```

Manually setting the role (  https://github.com/RocketChat/Rocket.Chat/wiki/Creating-the-First-Admin ) worked as expected.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29034124-admin-user-role-undefined-on-initial-account?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by graywolf336**
The recent addition of the user `Rocket.Cat` for integration and it being created as a first user has caused the "real" first users to no longer be made admin. This fixes #1632 and #1646

### CODE REVIEW

**Comment by graywolf336** [comment]
@RocketChat/core Would like someone to test this before this is merged in, to double check my work. Appears to be a high priority for new installations which opt to use the develop builds since they have to make manual changes to get their first user to be admin.

**Comment by Sing-Li** [comment]
Oh ... I have just started implementation on `@rocket.cat: makeme admin`   :disappointed_relieved:

**Comment by sampaiodiego** [comment]
lgtm

**Comment by graywolf336** [comment]
Going to merge the pull request then, thanks @Sing-Li @sampaiodiego :+1:

**Comment by geekgonecrazy** [comment]
:+1:

**Comment by rodrigok** [comment]
@graywolf336 makes sense, sorry and thanks :smile:

**Pull request merged**
