### PR TITLE
[FIX] Include toPhone Number to custom fields

### LINKED ISSUE #24570: Omnichannel: Add toPhone Number to custom fields from twilio sms integration
When an SMS comes in from Twilio, it grabs the city, state, and country and updates the room information. It would be nice if it included the toPhone as well.

We have multiple branches around the country. Each branch has a phone number. Customers can text into those numbers and they all get passed into rocket.chat omnichannel. If we could see the phone number that they are texting, we would know which branch they are trying to speak to. This should be a couple of lines added to this section:

https://github.com/RocketChat/Rocket.Chat/blob/96c555544ec5027aede0d8f5562c66781d2abea6/app/livechat/imports/server/rest/sms.js#L178-L191

### PR DESCRIPTION
**Pull request by aakash-gitdev**
included toPhone in sms.js

## Issue(s)
Closes #24570

## Further comments
toPhone added in a new if branch

### CODE REVIEW

**Comment by aakash-gitdev** [comment]
This is my first PR in Rocket Chat. Kindly let me know how can I improve my changes,

**Comment by KevLehman** [comment]
Hey! Thanks for your contribution. I see there's a conflict, I'll try to fix it in your branch since this PR has been for a while 😬

**Comment by KevLehman** [comment]
Hey @aakash-gitdev , sadly I cannot push into your fork, because of permissions. Would you mind updating your branch with the latest of develop?

Otherwise, what I can do is replicate your change and put you as co-author 🤗

**Comment by dougfabris** [comment]
> Hey @aakash-gitdev , sadly I cannot push into your fork, because of permissions. Would you mind updating your branch with the latest of develop?
> 
> Otherwise, what I can do is replicate your change and put you as co-author 🤗

@KevLehman since we don't receive news from the contributor, what do you think to move forward with the second option?

**Comment by KevLehman** [comment]
@dougfabris Yup, that's what I'm gonna do 😬

**Comment by KevLehman** [comment]
Closing in favor of #27656 
Thanks Aakash! 🥳

**Pull request closed without merging**
