### PR TITLE
Make Side Nav More Compact

### LINKED ISSUE #6227: Simple UI improvement to the left bar - save 5% space on the left bar
I have to keep scrolling to use the left bar.

If we can make the left bar more compact that would be helpful.

Here are a couple of suggestions to use the space in the leftbar more efficiently,

image

### PR DESCRIPTION
**Pull request by MartinSchoeler**
@RocketChat/core 

Closes #6227

Reduced the top margin in the h3 of the side nav

### CODE REVIEW

**Comment by engelgabriel** [comment]
I don't think we should hide the channels when they turn off. The user may want to stop receiving new chats, but is still going to have to deal with the current ones.

**Comment by jszaszvari** [comment]
@engelgabriel  Turning it off should hide them as it's already pretty cluttered. 

If the user is "Away" or "Busy" then this should just stop receiving chats but continue to show them so they can finish up/read them 

?

**Comment by MartinSchoeler** [comment]
@engelgabriel maybe make it a preference?

**Comment by MartinSchoeler** [comment]
@engelgabriel could you review again, i removed the livechat hide

**Comment by engelgabriel** [comment]
We still need to fix the problem on the referred issue. Maybe we could have a more generic fix, like a "colapse" button on the right of all grounding titles on the nav bar.

image

**Pull request closed without merging**
