### PR TITLE
[FIX] OEmbedURLWidget - Show Full Embedded Text Description

### LINKED ISSUE #20556: 3.11.0 Attachments and embed are cut off / limited in length
### Description:

The new embeds for messages have broken a lot of functionality we previously relied on. The new format is much larger and doesn't show the full message body.

### Steps to reproduce:

1. See below

### Expected behavior:

- [ ] Favicons shouldn't show if they don't exist or if they fail to load
- [ ] Messages shouldn't cut off with elipsis. 

#### Broken embed favicons shouldn't show if they don't exist

image

#### Embeds have a ton of padding between words and don't show the full message body (cut off with ...)

image

Another example of a message getting cut off.
image

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0

### LINKED ISSUE #20628: [BUG] URL OEmbeds are cut off
### Description:

The `og:description` in the URL embeds are cutoff and not fully shown.

### Steps to reproduce:

1. Send a link to any channel (or direct message)
Make sure the *description of the link is long*. Try `https://95nyn.csb.app/` or `https://github.com`.
2. You will find that the text is being wrapped and not fully shown

### Expected behavior:

The full text is shown.

### Actual behavior:

The text is being cutoff with ellipsis.

earlier

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.8 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome/Firefox
- Operating System: Ubuntu

### Additional context

This is not related to issue #20556 because it is related to `DefaultAttachments` and not `OEmbeds`.

### PR DESCRIPTION
**Pull request by aditya-mitra**
## Proposed changes (including videos or screenshots)

Embeds were cutoff when either _urls had a long description_.
This was handled by removing `overflow:hidden;text-overflow:ellipsis;` from the inline styles in [`oembedUrlWidget.html`](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/oembed/client/oembedUrlWidget.html#L28).

### Earlier

earlier

### Now

now

## Issue(s)

Closes #20628

## Steps to test or reproduce

- Send a link to any channel (or direct message)
Make sure the *description of the link is long*. Try `https://95nyn.csb.app/` or `https://github.com`.
- You will find that the text

## Further comments

**This is not related to [Issue #20556](https://github.com/RocketChat/Rocket.Chat/issues/20556#issuecomment-774411671)**

### CODE REVIEW

**Comment by aditya-mitra** [comment]
This resolves the problem for both (URL embeds and bot message embeds) because [all bot message text embeds are by default url embeds](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/oembed/client/baseWidget.js#L13-L25). It can be found here in this file - [/app/oembed/client/baseWidget.js](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/oembed/client/baseWidget.js)

This pull request is open for review.
Thank you.

**Comment by wreiske** [comment]
Please note that this doesn't fully fix everything outlined in #20556. The large padding on embeds is also an issue.

**Comment by aditya-mitra** [comment]
@wreiske Did you mean the block quotes?
I was unable to notice them. Could help me by pointing them out?
I will come up with a fix as soon as possible.
Thank you.

**Comment by wreiske** [comment]
> @wreiske Did you mean the block quotes?
> I was unable to notice them. Could help me by pointing them out?
> I will come up with a fix as soon as possible.
> Thank you.

Sorry, I meant the field objects on the embeds. 
image

See all of the extra padding?

**Comment by aditya-mitra** [comment]
Markdown texts can now be displayed in **oembeds** as mentioned in #20560 

parse markdown

**Comment by aditya-mitra** [comment]
@ggazzo This Pull Request is open for review.

**Review by ggazzo — APPROVED** [review]

**Pull request merged**
