### PR TITLE
Regression: return home after close chat

### PR DESCRIPTION
**Pull request by MartinSchoeler**
## Further comments

OC-259

### CODE REVIEW

**Review by aleksandernsilva — APPROVED** [review]

**Review by ggazzo — CHANGES_REQUESTED** [review]
Could you explain to me why sending it home is something useful?  there is no information that helps the agent there.  if he's in current chats it's even worse.  I would very kindly ask you to reconsider

I actually did it on purpose and found it much better.  I know it changes behavior, no that doesn't mean it got worse

Feel free to dismiss my review but I would like to see you considering my suggestion

**Review by cauefcr — APPROVED** [review]
Reviewed and tested, it works perfectly here.

**Review by aleksandernsilva — APPROVED** [review]

**Review by ggazzo — CHANGES_REQUESTED** [review]
what happens if the room is closed by other client or other user tab?
since we're so focused on consistency and behavior, I suppose it's critical if someone else (or yourself in another tab) closes and doesn't get an update

**Comment by MartinSchoeler** [comment]
Closing this, giving preference to https://github.com/RocketChat/Rocket.Chat/pull/26988

**Pull request closed without merging**
