### PR TITLE
Allow Livechat visitors to switch the department

### LINKED ISSUE #5998: Allow visitors to switch departments (livechat)
Right now, a visitor is not able to switch to a different department, once he has registered.

This has severe limitations in situations where people might ask different questions over time, e.g. developers asking about fronted and backend questions.

I'd like to allow the visitor to easily switch to a different department.
Any open chats would need to be closed, as I don't think visitors should be allowed to forward open requests on their own.

### PR DESCRIPTION
**Pull request by drallgood**
@RocketChat/core 

Closes #5998 

This PR for the live chat feature allows visitors to switch their department after the initial registration.
As we're using this feature as our support chat for developers, people tend to have questions for different departments and might want to switch between them every time they have a question.
So, this PR allows them to do just that by going to the options menu and just selecting a new department
screen shot 2017-02-14 at 12 16 57 am

This is my first PR for this project, so please let me know if there is something missing and I will make sure to update it accordingly

### CODE REVIEW

**Comment by yethrib** [comment]
I am looking forward to this update, would it be possible to filter / split the available departments using the javascript on the frontend using a group id?

**Comment by drallgood** [comment]
@yethrib The list can be filtered in the live chat settings. It only shows the departments that are enabled to be shown during the registration.

**Comment by drallgood** [comment]
@sampaiodiego Did you have time to look at this PR?

**Comment by yethrib** [comment]
Must say first, I am really impressed by Rocket.Chat, fantastic.

I can see huge potential in this PR with some further modifications.

I propose that the departments should be grouped so that the frontend can call it using an encrypted token id (group id).

This should feature in the administration screen before an agent commences a live chat to see where the chat has come from i.e. which group and department.

To include a grouping of departments may require a database update without affecting much of the existing functions.

**Comment by sampaiodiego** [comment]
@drallgood yes, I did =)

I think it should be better to have a link on the options menu like: "Change department", and then when you click it, show (somehow) the departments for you to chose.

also, I think it should be a setting for admins to chose whether allow visitors to change the department or not.

**Comment by drallgood** [comment]
@sampaiodiego Alright. That makes sense. I will update the PR accordingly.

**Comment by drallgood** [comment]
@sampaiodiego I finished the implementation. Not sure this is the most elegant solution (a single dropdown in the entire chat window) but I didn't see any other way of doing this.
The sweetalert library RocketChat is using sadly doesn't allow select boxes in dialogs, or I would have used that to allow the user to switch.

**Comment by yethrib** [comment]
I agree with @sampaiodiego restricting the option to change departments would be a good feature. Could this be implemented in such a way by grouping departments?

**Comment by drallgood** [comment]
@yethrib I don't think that's necessary.
You're already able to select departments that should be presented to the user upon registration and I would use the same list for this feature. There is in my opinion no point of having a different set of departments here.

The flag for the admin is already implemented. It's a boolean that allows the admin to decide whether visitors should be allowed to switch or not.

**Comment by yethrib** [comment]
@drallgood the point i'm trying to make is, if I have one rocket chat server running and livechat on many sites, before any live chat starts, how will I know which site / group it has come from?

**Comment by drallgood** [comment]
@yethrib That's a separate issue that will not be tackled by this PR.
I think you should open an issue for that so that we can properly discuss it. It will impact several other areas (e.g. you probably need to configure the livechat script somehow when you embed it in different places)

**Comment by yethrib** [comment]
I have created https://github.com/RocketChat/Rocket.Chat/issues/6230

**Comment by drallgood** [comment]
New screenshots:
screen shot 2017-03-07 at 7 59 02 pm
screen shot 2017-03-07 at 7 59 12 pm
screen shot 2017-03-07 at 7 59 21 pm
screen shot 2017-03-07 at 7 59 46 pm

**Comment by drallgood** [comment]
@sampaiodiego Awesome. I wasn't really happy with the way I solved it. Your solution looks way better! (And next time I know how to do it).

Thanks!

**Comment by Nasr2013** [comment]
Ending chat option does't end the chat, I mean when click yes to close the chat it just froze . vistore has to type /close then yes button will work.

Any help much appreciatted. 
Thank you

**Comment by drallgood** [comment]
Hope this makes it into the next release 😄 
We're patiently waiting for this feature

**Pull request merged**
