### PR TITLE
[FIX]Added success message on saving notification preference.

### LINKED ISSUE #20219: [BUG] No success message after saving Notification Preferences in room.
### Description:
After saving notification preferences from contexual bar no success message is displayed.

### Steps to reproduce:

1. Select any room
2. From contexual bar select notification preferences.
3. Toggle any option.

### Expected behavior:
Success message should be displayed on screen.

### Actual behavior:

No success message is displayed on screen.

https://user-images.githubusercontent.com/55157259/104770527-b5b23c80-5796-11eb-8636-0134f6963211.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

### Additional context
I am working on it.

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)

Added success message after saving notification preferences.

https://user-images.githubusercontent.com/55157259/104774617-03ca3e80-579d-11eb-8fa4-990b108dd8d9.mp4

## Issue(s)

Fixes #20219

### CODE REVIEW

**Comment by dougfabris** [comment]
@Darshilp326 We should have a way to check if everything works well with `rooms.saveNotification` and dispatch a message for a possible error, as well. Do you like to improve it in this PR?

**Comment by Darshilp326** [comment]
@dougfabris Error messages are already dispatching.
Screenshot from 2021-01-18 22-17-00

**Comment by dougfabris** [comment]
@Darshilp326 Nice! I'm going to accept the PR and it probably will be merged ASAP. Thanks for the help mate!

**Review by dougfabris — APPROVED** [review]

**Comment by Darshilp326** [comment]
@dougfabris Looking forward to more such prs:)

**Review by ggazzo — APPROVED** [review]

**Pull request merged**
