### PR TITLE
Custom processing script for integration webhooks

### LINKED ISSUE #2426: Custom processing script for integration webhooks
Allow users to add custom scripts that for the following steps of the webhooks:

- Prepare Outgoing Requests
- Process Outgoing Requests Responses
- Process Incoming Payloads

### PR DESCRIPTION
**Pull request by rodrigok**
Closes #2426

- [x] Field to insert **Process_Incoming_Request** script
- [x] Field to insert **Prepare_Outgoing_Request** script
- [x] Field to insert **Process_Outgoing_Response** script
- [x] Execute scripts in sandbox
- [x] Allow **Prepare_Outgoing_Request** to prevent request and return a new message
- [x] Use Logger

### CODE REVIEW

**Comment by rodrigok** [comment]
LGTM

**Comment by engelgabriel** [comment]
LGTM

**Comment by pavankumarkatakam** [comment]
Hey, how to use this filed to transform incoming data.

**Comment by bott0r** [comment]
I am trying to figure that out as well :D

**Comment by javaning** [comment]
I am not familiar with the vm module, for incoming web-hook, maybe write something like this ?:
  here **content** is one key in sandbox.

    var res = {"content":
    {   "text": " ",
        "username":" ",
        "attachments": [
            {
                "title": "",
                "title_link": "",
                "text": "",
                "image_url": "",
                "color": ""
            }
        ]
    }
    }
    if (headers.event=='xxxx') 
    {
        res.content.text= content.xxx; //this is a message;
        res.attachments.title='1111'; //...
    }

    return res;

**Comment by pavankumarkatakam** [comment]
Im actually using the Gitlab to integrate with, but gitlab will send event names as request header with the name `X-Gitlab-Event` , with these type of header name i cant write `headers.X-Gitlab-Event` and i also tried like this `headers['X-Gitlab-Event']` but not working.

**Comment by bott0r** [comment]
Thank you for your kind reply, i am quite litterally on the struggle bus when it comes to read out the incoming array which looks like this   
```
@bodyParams { update_id: 1337, 
                message: {  message_id: 1337, 
                                                from: { id: 123456789, first_name: 'bott0r' }, 
                                                 chat: { id: 123456789, first_name: 'bott0r', type: 'private' }, 
                                                 date: 1456911431, 
                                                  text: 'Hi how are you' 
                                 } 
            }
```
and transform it :(

**Comment by javaning** [comment]
@pavankumarkatakam  try headers["X-Gitlab-Event"] ?

**Comment by javaning** [comment]
@bott0r  thie line 
    `res.content.username=content.message.from.first_name;` //right?

**Comment by bott0r** [comment]
I have no idea what i should be doing and the line you quoted is of course completely wrong :D

**Comment by rodrigok** [comment]
Hey folks, I created a tutorial to use scripting to integrate with GitHub https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting---GitHub

If you create new integrations can you share with us?

**Comment by bott0r** [comment]
with my limited background (physicist) i doubt i can share anything anytime soon :(

**Pull request merged**
