### PR TITLE
[FIX] Add retries to docker-compose.yml, to wait for MongoDB to be ready

### PR DESCRIPTION
**Pull request by tiangolo**
The current `docker-compose.yml` file requires manual steps to deploy a Rocket Chat stack, it cannot be done in a single deterministic command or integration with CI systems.

The current instructions require to wait for MongoDB to be ready, and then starting the `mongodb-init-replica` service manually, and then the `rocketchat` service manually too.

That means that, if starting from scratch, with a fresh MongoDB container, at the firsts `docker-compose up -d`, those two services will fail to start and stay down.

The proposed change makes those two services wait for MongoDB to be ready, by retrying 30 times, waiting 5 seconds before each retry. That way, when the service `mongo` is ready, `mongo-init-replica` will run, initialize the replica set and exit normally (with exit code 0). And then `rocketchat` will be able to start with the initialized MongoDB.

---

This would make the instructions for Docker Compose here: https://rocket.chat/docs/installation/docker-containers/docker-compose/

Be almost only `docker-compose up -d`.

And after a bit, everything will be ready.

The docs PR is here: https://github.com/RocketChat/docs/pull/1050

### CODE REVIEW

**Comment by tiangolo** [comment]
I'm not sure what to do about the test errors as I didn't modify anything related to them.

**Comment by tiangolo** [comment]
The companion docs PR is here: https://github.com/RocketChat/docs/pull/1050

**Comment by tiangolo** [comment]
I'm not sure about the process, I have signed the CLA about 3 times, and then the CLA Bot comments saying that I signed it.

And a couple days later it edits the comment and I appear again as if I hadn't signed it. Am I doing something wrong?

**Comment by geekgonecrazy** [comment]
Looks like all is good from CLA standpoint.  :+1:

**Comment by tiangolo** [comment]
I see that the Circle CI build is always "Pending — Your job is on hold on CircleCI!", is there anything that I have to do on my side to "un-pause" it?

**Comment by rodrigok** [comment]
@tiangolo that's expected, it's a job we added to be able to trigger the docker image build manually when we need to test the PR, you can see it's not marked as required here.

**Comment by tiangolo** [comment]
Get it. Thanks!

**Comment by Sing-Li** [comment]
@tiangolo have you tested this with any particular version of mongo?    On some mongo version, issuing the `rs.initiate()` EARLY will make the DB totally irresponsive 😞

**Comment by tiangolo** [comment]
I'm using it on a CI/CD environment/application with `mongo:3.2`, which is what was used when I created the PR. But I haven't updated it to Mongo 4.0.

**Pull request merged**
