### PR TITLE
Disconnect on Cordova Pause and Reconnect on Cordova Resume

### PR DESCRIPTION
**Pull request by graywolf336**
@RocketChat/core 

Closes: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/112

This basically listens for Cordova's `pause` event and disconnects from the server thus saving background battery usage. Then when Cordova fires `resume` event we reconnect to the server. This will cause a little bit of delay, but I feel that delay is worth the extra battery life saved.

### CODE REVIEW

**Comment by marceloschmidt** [comment]
Does push notification still work after that?

**Comment by TheReal1604** [comment]
@marceloschmidt After disabling the mobile background data usage for the rocket.chat app on Android the mobile push notifications work like before. (Because the push notifications come from a system service..)

**Comment by sampaiodiego** [comment]
My only concern is about [this](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui/lib/cordova/user-state.coffee).

I think we should call `disconnect()` and `reconnect()` on the [existing callbacks](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui/lib/cordova/user-state.coffee) to avoid a race condition causing the user not being set away.

**Comment by rodrigok** [comment]
@graywolf336 did you test this? Solved the battery problem?

**Comment by graywolf336** [comment]
@sampaiodiego I agree, I didn't see that last night when I looked for existing ones. I will move it to there.

@rodrigok Not yet, I created this pull request so I could make usage of the heroku deployment.

**Comment by sampaiodiego** [comment]
@graywolf336 you forgot to change the `package.js` file and change the filename :wink:

**Comment by graywolf336** [comment]
That's what I get for trying to do it fast before I left for work. 👎

**Comment by engelgabriel** [comment]
We should seta timer, for 5 minutes. If the user is just going to another app to get some info, he can come back quickly. The 5 minutes can be a user's config.

**Comment by rodrigok** [comment]
@engelgabriel maybe 1 minute?

**Comment by graywolf336** [comment]
@engelgabriel I agree with @rodrigok, one minute is probably good enough by default to increase the battery saving this hopefully will enable.

**Comment by engelgabriel** [comment]
Agreed, 1 minute should be fine. Can you do that @graywolf336?

**Comment by graywolf336** [comment]
Yes I will take a look at adding that this week.

**Comment by graywolf336** [comment]
@RocketChat/core Thoughts on this now?

**Comment by engelgabriel** [comment]
Should we add a issue to turn the time into a setting @graywolf336 ?

**Comment by TheReal1604** [comment]
Nice! Thanks for your amazing work. @graywolf336 @engelgabriel

**Comment by graywolf336** [comment]
@engelgabriel Yeah we could, probably should be a personally setting though.

**Comment by Sing-Li** [comment]
Thanks for keeping the world _green_ ,  @graywolf336  !

**Comment by kevincolten** [comment]
I like @graywolf336 's idea, this should be an admin setting.

**Pull request merged**
