### PR TITLE
[NEW] Add close button to flex tabs

### LINKED ISSUE #7435: Add an "X" to easily close menu windows
image

Should be added to every menu screen since clicking the menu icon to close is not intuitive at all.

### PR DESCRIPTION
**Pull request by sampaiodiego**
@RocketChat/core 

Closes #7435

What I did in most files was just removing the `<div class="content">` because I added it to the container template:

image

image

### CODE REVIEW

**Comment by RichardFoxworthy** [comment]
This is a good addition, but the close button scrolls off the flextab panel along with content. I'd expect the close button to remain anchored to the top corner of the flex tab panel, not move with any scrollable content content

**Comment by sampaiodiego** [comment]
@RichardFoxworthy thanks for the feedback.. which browser and OS are you using? on google chrome I can say the button stays at the top even if you scroll the content.

**Comment by RichardFoxworthy** [comment]
@sampaiodiego I am using Chrome. The button scrolls with content in every tab except for 'Members' - see this example for Room Info tab. All the others do the same, except Members

**Comment by sampaiodiego** [comment]
you're right @RichardFoxworthy .. I think I was looking at members list only.. can you please open a issue for that? thank you

**Pull request merged**
