### PR TITLE
[NEW] Remove all closed Livechat chats

### LINKED ISSUE #12279: [Livechat] Remove all chats
I would like to be able to close and remove all the chats at once.
So we should add a button in the current chats list to do so.

### PR DESCRIPTION
**Pull request by knrt10**
Closes #12279 

@renatobecker would you please review. Closing chats and also showing delete all button according to filter set in room.

### CODE REVIEW

**Comment by renatobecker** [comment]
Hi @knrt10!
Can you please fix the conflicts here?

Thanks.

**Comment by knrt10** [comment]
@renatobecker fixed. Please review

**Comment by renatobecker** [comment]
Hi @knrt10 I'have made several improvements in this PR.
As you can see below, I replaced that big red button with a popover, I think it's a better UX/UI approach:

Screen Shot 2019-10-11 at 18 40 58

Another important thing, now the process of removing rooms is implemented on server side, so we just need to call the server method once.
Your opinion about theses changes would be very appreciated, thanks for your help with this implementation.
Since I worked in this PR I'm requesting the review from @sampaiodiego and/or @rodrigok, Ok?

**Comment by knrt10** [comment]
LGTM!

**Pull request merged**
