### PR TITLE
Faster desktop notifications

### PR DESCRIPTION
**Pull request by mccambridge**
@RocketChat/core 

Adds setting under General -> Notifications to set the number of seconds a desktop notification should appear in the browser (defaults to 5 sec). Currently, Chrome defaults to 20 seconds, and this is somewhat annoying.

Implemented Notification.close() in notifications.coffee in a setTimeout with the duration of the timeout equal to the settings value provided (x1000ms).

### CODE REVIEW

**Comment by rodrigok** [comment]
@mccambridge Are you using OS X? I think that this remove the notification from the notification central.

**Comment by mccambridge** [comment]
Yes, I'm on OS X. I don't think these notifications add anything to notification central. These are just pop-up desktop notifications as far as I can tell. The timeout just closes it. https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by mccambridge** [comment]
If you'd like to see a fake notification using the same timeout, you can run:

`const n = new Notification('lala', { body: 'yada', silent: true}); setTimeout(() => n.close(), 5000)`

in a web console.

**Comment by rodrigok** [comment]
@mccambridge Yes, the notifications goes to OS X notification center, see https://github.com/RocketChat/Rocket.Chat/issues/1866 and https://github.com/RocketChat/Rocket.Chat/pull/1890

As you can see here https://github.com/RocketChat/Rocket.Chat/pull/1890/files, we removed the close timeout to keep notifications in notification center.

**Comment by mccambridge** [comment]
Okay, got it. Personally, I don't use notification center and would rather not see the notification linger for so long. But that's just my opinion.

What do you think about a setting where the administrator could choose whether or not to set the timeout?

**Comment by rodrigok** [comment]
@mccambridge an option of notification timeout is a good idea, 0 could be disabled

**Comment by mccambridge** [comment]
@rodrigok okay, updated to include `0` as an option, by which the timeout would not be set. `0` is the default value.

**Comment by geekgonecrazy** [comment]
@mccambridge So just to confirm when 0 they will behave as they do currently?

**Comment by mccambridge** [comment]
Exactly. And default is `0`, so default is they behave as they do currently.

**Comment by rodrigok** [comment]
LGTM

**Comment by rodrigok** [comment]
@RocketChat/core Someone can review to give the second lgtm?

**Comment by sampaiodiego** [comment]
LGTM

**Comment by mccambridge** [comment]
Thanks, y'all!

**Pull request merged**
