### PR TITLE
[FIX] File uploads for unknown file types but nothing is blocked

### PR DESCRIPTION
**Pull request by 20051231**
## Proposed changes

I When the block list is empty, all file types should be allowed. But if the browser does not recognize the mime of a file type, the file is still rejected.
## Issue(s)

#16836
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by stleitner** [comment]
This only works if the block list is empty. If another media type is blocked, files with unrecognized mime type still fail.

**Comment by scebryan** [comment]
> This only works if the block list is empty. If another media type is blocked, files with unrecognized mime type still fail.

Hello, Do you think this can be solved? If another media type is blocked, files with unrecognized mime type still fail.

Thanks!!

**Comment by 20051231** [comment]
> > This only works if the block list is empty. If another media type is blocked, files with unrecognized mime type still fail.
> 
> Hello, Do you think this can be solved? If another media type is blocked, files with unrecognized mime type still fail.
> 
> Thanks!!

If a blocked mime is not recognized by the browser, the file still need to be blocked so I did not change the logic in this case.

I think we might lookup the mime from the file extension in case of unrecognized mime. Or accept both mime and extension in the list?

**Comment by scebryan** [comment]
It is an option, if the browser does not recognize the mime, search if the file extension is in the whitelist.

**Comment by juancroldan** [comment]
We are also having this problem. The issue is not solved, should it be still open?

**Comment by sampaiodiego** [comment]
just to make sure, do you guys have both blacklist and whitelist settings blank and can still not upload files? if so, please open a new issue

**Pull request merged**
