### PR TITLE
[FIX] Message view mode setting was missing at user's preferences 

### LINKED ISSUE #10326: personal "view mode" (chat window) setting gone in 0.63.0
Hello Devs.

After upgrading to 0.63.0 the personal setting "view mode" is gone. Usually you can choose between normal, cozy and compact. I can find the "view mode" settings under accounts as adminstrator but it's rather useless if i cannot change that setting as regular user. Any ideas on that? Bug or feature?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.0
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: yes
* Node Version: 8.9.4
* mongoDB Version: 3.4

thanks and cheers
t.

### PR DESCRIPTION
**Pull request by kaiiiiiiiii**
Closes #10326 (@himbeere)

This PR brings back the view mode for messages, which has accidentally been removed by @karlprieb in PR #10016.

I’ve done the following in addition:

1. The values passed to ‘selected’ in the view mode dropdown where passed as strings. This prevented the result from ever becoming true. Values are passed as integer now.
2. Renamed viewMode to messageViewMode to avoid any confusion with the new sidebar view mode.
3. Moved all notification related stuff in an own section. This shortens the 'messages' section and builds a better visual connection between the view mode and it’s heading.

I’m not quite sure if the migration’s gonna work like that. In my tests it does not remove the fields when migrating from an older version than 0.63.0.

**Screenshot of Notifications section:**
2018-04-10 17_37_54- 1 rocket chat

**Screenshot of Messages section:**
2018-04-10 17_38_29- 1 rocket chat

Regards,
Kai

### CODE REVIEW

**Comment by karlprieb** [comment]
Idk, I don't think we should use auto translators.

@RocketChat/core What you guys think?

**Comment by graywolf336** [comment]
> Idk, I don't think we should use auto translators.

I agree. Let's let our community translators handle them, since we never know what the results actually are..

**Comment by karlprieb** [comment]
So @kaiiiiiiiii can you remove the auto translations?

**Comment by kaiiiiiiiii** [comment]
I'll do that, no worries :)

**Pull request merged**
