### PR TITLE
[WIP] Adding functionality for End-to-End encrypted conversations

### PR DESCRIPTION
**Pull request by mrinaldhar**
@RocketChat/core 

Creating new package "RocketChat-e2e", that enables end-to-end encrypted chat conversations in Rocket.Chat, as part of Google Summer of Code 2017. 

Project will add functionality for encrypted direct messaging, encrypted group conversations and encrypted file uploads.

---

Objectives completed at end of GSoC programme: 
- E2E Encryption support for Direct messaging
- E2E Encryption support for Private groups
- E2E Encryption support for uploaded files 
- Offline encrypted chats

### CODE REVIEW

**Comment by jfchevrette** [comment]
@mrinaldhar This is awesome! May I ask is this only 1-on-1 private chats or is this also going to encrypt conversations in rooms?

**Comment by mrinaldhar** [comment]
I'll first be adding support for 1-on-1 conversations, but plans include supporting encrypted group chats as well.

**Comment by cyclops24** [comment]
@mrinaldhar It's very awesome feature. Is it complete or still needs more work?

**Comment by geekgonecrazy** [comment]
Fixes: #7507

**Comment by geekgonecrazy** [comment]
Note for any that come across.  This is merged into a branch, not to develop.  Still WIP

**Pull request merged**
