### PR TITLE
Improved user search (name and username)

### PR DESCRIPTION
**Pull request by BirknerAlex**
Hello guys,

we are using Rocket.Chat as company and our LDAP usernames are very difficult. So most employees knowing only the real names of the employees and not their LDAP username.

That's the reason why we needed to change the user search to username or name (real name) instead of only username.

I really hope I did not forget anything in this change.

Have a nice weekend!

Regards,
Alexander Birkner

### CODE REVIEW

**Comment by marceloschmidt** [comment]
I think that if we add the option to search by name as well, we should show the name **and** username:
image

**Comment by BirknerAlex** [comment]
Hey @marceloschmidt,

the userSearch template has been changed. It shows now name and username in the results.

Regards,
Alexander

**Comment by hvma** [comment]
status?

**Comment by BirknerAlex** [comment]
FYI: I've merged the upstream develop branch into my develop branch.

**Comment by BirknerAlex** [comment]
@engelgabriel: Is there anything what I need to change or can this pull request be merged?

**Comment by graywolf336** [comment]
@BirknerAlex Mind showing a screenshot of the new search result?

**Comment by BirknerAlex** [comment]
Sure, here you go! :)

**Comment by marceloschmidt** [comment]
LGTM

**Comment by sampaiodiego** [comment]
LGTM

**Comment by marceloschmidt** [comment]
@BirknerAlex Sorry for taking this long. We have just merged it :) Thanks for you efforts!

**Pull request merged**
