### PR TITLE
[NEW] Allow setting user for "groups.list" API endpoint

### LINKED ISSUE #12943: Add userId argument to "groups.list" REST API call
The [`groups.list` API call](https://rocket.chat/docs/developer-guides/rest-api/groups/list/) lists all private groups of the current user.

It would be very useful to retrieve the list of private groups for a given user, similar to the [`groups.counters` API call](https://rocket.chat/docs/developer-guides/rest-api/groups/counters/). This could be achieved similarly by adding a `userId` argument.

### PR DESCRIPTION
**Pull request by mbrodala**
Closes #12943

Needs an update in https://rocket.chat/docs/developer-guides/rest-api/groups/list/

### CODE REVIEW

**Comment by mbrodala** [comment]
Yes, I've noticed the rather strict policy in RC that not even admins can look into private groups they are not part of.

In our case we are building a integration where one requirement is to list all private groups of a user on our site for direct linking into RC.

> so if you give an admin the power to list all private rooms of any user is participating, what is the purpose of private rooms on the end

Not sure I get what you mean here since `groups.listAll` already exists which bypasses most policies.

**Comment by geekgonecrazy** [comment]
is this still needed?  It seems like the endpoints  both show all now

**Comment by mbrodala** [comment]
@geekgonecrazy Can you elaborate on that? There was no change in the `groups.list` API AFAIS.

**Comment by rodrigok** [comment]
We apologize for not getting a review on this sooner.

The `groups.listAll` API lists all the private groups for admins only but id doesn't associate any group to any user.

I'll close this since we, as mentioned before, we have a strict policy of who can see/edit/delete private groups or his members.

Thanks

**Pull request closed without merging**
