### PR TITLE
Allow invalid ssl certs.  IE self signed on oembed fetch

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Reference issue: #727

I think also an issue being had where uploads aren't showing previews when behind nginx with ssl.

### CODE REVIEW

**Comment by graywolf336** [comment]
Wondering if this should be an option in the admin panel? Since this could potentially be a security risk?

**Comment by jclabaugh** [comment]
I agree it should be an option, not a default in Admin Settings

[    ] allow invalid/self-signed SSL cert's for link validation/previews

**Comment by geekgonecrazy** [comment]
Yeah it probably should be. :)

**Comment by engelgabriel** [comment]
Agreed!

**Pull request merged**
