### PR TITLE
Fixing problem with file name in utf-8 format

### PR DESCRIPTION
**Pull request by pkonetskiy**
It is fix problem with file name in utf-8 format when download file through proxy.

### CODE REVIEW

**Comment by pkonetskiy** [comment]
I made two screenshots which demonstrate about mistake.
These are screenshots of url that are sent to the server with and without a proxy.
Снимок экрана 2021-06-17 в 19 13 59
Снимок экрана 2021-06-17 в 19 27 59
The name of file in url isn't needed but it cann't be empty.

**Comment by johncrisp** [comment]
Thanks for adding this.

I'll see if we can get some attention.

**Comment by sampaiodiego** [comment]
thanks @pkonetskiy for your contribution.. 

I'm not sure I got the current issue. Is it not working for you? I have tested here and it worked for me, I mean, I got no issue uploading, previewing and downloading the file with the original name.

**Comment by pkonetskiy** [comment]
Thank you for answer @sampaiodiego 
Yes I have the problem and not only me. Look at the post - https://forums.rocket.chat/t/hello-i-need-help/9247
I am using Apache/2.4.47 (Unix) as a proxy for rocketchat. If I don't use proxy everything works correctly.

**Comment by johncrisp** [comment]
I'm hoping that this will get reviewed.

Due to the way the sprints work it may not get looked at immediately but rest assure we aren't ignoring you.

**Comment by sampaiodiego** [comment]
closing as the issue seems to be with the proxy configuration and not with rocket.chat itself.

**Comment by LucasDachman** [comment]
> closing as the issue seems to be with the proxy configuration and not with rocket.chat itself.

What is the solution for the proxy configuration?

**Pull request closed without merging**
