### PR TITLE
[NEW] Add missing remove add leader channel

### PR DESCRIPTION
**Pull request by Montel**
Closes https://github.com/RocketChat/Rocket.Chat/pull/13315

### CODE REVIEW

**Comment by MarcosSpessatto** [comment]
@Montel can you please add these endpoint to the `groups.` as well? It is interesting to have these possibilities in groups too. What do you think?

**Comment by Montel** [comment]
it's already implemented :)

**Comment by Montel** [comment]
groups.addLeader and groups.removeLeader is already implemented.
It was just missed for channels.

**Comment by MarcosSpessatto** [comment]
Oh, you're right. I'll implement some tests for these endpoints, or you can take care of this?

**Comment by Montel** [comment]
Please do it :) You know better it as me :)
I will work on other missing RESTAPI that I found :)

Thanks

**Comment by Montel** [comment]
(Another request https://github.com/RocketChat/Rocket.Chat/pull/13334 it's about typo in command name, I don't know how to add requester). Regards

**Comment by Montel** [comment]
I created this one https://github.com/RocketChat/Rocket.Chat/pull/13445 (I hope that it's ok now :) )

**Pull request merged**
