### PR TITLE
Append read receipt feature for #3411

### LINKED ISSUE #3411: read receipts?
Your Rocket.Chat version: (make sure you are running the latest) 31

Is there any way to tell if a Rocket.Chat message has actually been read by the recipient?

### PR DESCRIPTION
**Pull request by ggrish**
@RocketChat/core 

Closes #3411

Append read receipt info to message entry.

### CODE REVIEW

**Comment by tgxn** [comment]
Hey, this is great, but it looks like it depends on the code in your other PR #4048? (for the setMessageReader function)

**Comment by rodrigok** [comment]
Hi @alexdorn87, first of all, thanks by this contribution.

I have some questions/suggestions about this PR

1. Can you merge your 2 PRs in one since they are dependents?
2. I like the idea, but this should be optional, can you create a setting for that and disabled by default?
3. You can improve your code by removing your loop on messages and changing the update to affect all desired messages in one single query, I can help you with this if you want.
4. Will you change the interface to show this list of users?
5. Maybe we should add a setting to enable this feature to only channels with a certain number of users, we have bad experiences with large arrays, think in rooms with thousands of users.

@RocketChat/core what do you think?

**Comment by geekgonecrazy** [comment]
This would be a great addition!  

I agree large rooms this could be very bad for experience.  Maybe a setting to only enable for rooms with users <= x ?  And let users define it.  Then default it to like 10-15 ?

**Comment by danielpedersen87** [comment]
hi #rodrigok

Thanks for your detailed message.
1)
Could you help to me to know how to do it, please?

2) 
I will make it, but now I am some busy.
If you don't mind, please make it, too.
Or not, I will make it myself
3)
Now I don't know what you mean.
If you can do it, please help me.
thanks
4)
I changed already on my server.
But I don't commit it, because I don't know the design will be accept by your team.
5)
Yes, That's good idea.
I hope to interact with you more and make more completed chat server.
I am appreciate for your open source chat server.
I hope to get more touch with you.

thanks, guys.

**Comment by alexdorn87** [comment]
hi #rodrigok

Thanks for your detailed message.
1)
Could you help to me to know how to do it, please?

2) 
I will make it, but now I am some busy.
If you don't mind, please make it, too.
Or not, I will make it myself
3)
Now I don't know what you mean.
If you can do it, please help me.
thanks
4)
I changed already on my server.
But I don't commit it, because I don't know the design will be accept by your team.
5)
Yes, That's good idea.
I hope to interact with you more and make more completed chat server.
I am appreciate for your open source chat server.
I hope to get more touch with you.

thanks, guys.

**Comment by engelgabriel** [comment]
@alexdorn87 can you update all the indentation to TABs?

**Comment by xavierzwirtz** [comment]
If I stepped in and cleaned this pull request up would the RocketChat team be willing to pull it in? This feature is vital for the way my team uses chat, but I don't want to be running a custom version.

**Comment by engelgabriel** [comment]
Yes @xavierzwirtz we'd like to add this feature, if you can make the changes, we'd love to merge it.

**Comment by xavierzwirtz** [comment]
Awesome.

@alexdorn87, could you post the UI modifications you made somewhere?

**Comment by alexdorn87** [comment]
Hi @xavierzwirtz

which UI modification do you need?
Could you give me more details, please?

**Comment by xavierzwirtz** [comment]
The UI for displaying which users have seen a message. I've got the changes you have pushed cleaned up and rebased on tip. Just need the UI changes.

**Comment by RichardFoxworthy** [comment]
any progress on this one @alexdorn87 and @xavierzwirtz ? Will be a great new piece of functionality!

**Comment by xavierzwirtz** [comment]
I was able to rebase the changes to the server, and I can see the data getting sent back to the server whenever a message is read. However, I am not familiar with the UI framework that is being used within rocket chat, and have not had time to get familiar with it. I was hoping that @alexdorn87 could post up the UI changes that he made here so that I can get them integrated as well.

**Comment by alexdorn87** [comment]
I posted all files.
if you need more, please tell me more details

**Comment by xavierzwirtz** [comment]
@alexdorn87, you said that
> I changed (the UI) already on my server.
> But I don't commit it, because I don't know the design will be accept by your team.

Could you post the changes that you made for that? I can get them into a PR and have the RocketChat review them.

**Comment by RichardFoxworthy** [comment]
Hi again @alexdorn87 and @xavierzwirtz - is there an easy way forward to complete this PR? Would be a great feature addition to Rocket.chat!

**Comment by ArchimedesFM** [comment]
This would be a great feature addition to Rocket.chat!

**Comment by HammyHavoc** [comment]
Would love to see this in RC, and completely agree about keeping it disabled by default, and defaulting to only on rooms with a handful of users.

**Comment by engelgabriel** [comment]
@sampaiodiego can you link this on the PR you are about to create for this feature?

**Comment by engelgabriel** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/9717

**Pull request closed without merging**
