### PR TITLE
Protect uploads

### LINKED ISSUE #724: Protect Uploads - download should not be possible without logging in
Right now uploads to a Rocket.Chat instance are not protected, meaning anyone can download them without being authenticated. I feel this should be an admin option, to protect or not protect uploads and require an account to download them.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26494518-protect-uploads-download-should-not-be-possible-without-logging-in?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gmsecrieru**
Should close #724 

- [x] Create admin setting for protected files
- [x] Block unauthorized downloads
- [x] By-pass restriction during oEmbed (server-side) lookup.

### CODE REVIEW

**Comment by flashguy22** [comment]
@gmsecrieru as you have been working on this any chance to get it finished any time soon?

**Comment by gmsecrieru** [comment]
Hi @flashguy22 , I'm still working on a solution for [Item no. 3](https://github.com/RocketChat/Rocket.Chat/pull/1266#issue-113709933), but I don't have an ETA at this point. If you think you could leave with this limitation for a little longer (i.e. not showing uploaded images embedded on messages -- example bellow) you could sync with current code from this PR as the main functionality is already implemented.

screen shot 2015-11-03 at 11 33 07

**Comment by flashguy22** [comment]
Thanks for your feedback @gmsecrieru. I will wait until you have found a solution for the inline preview.
Keep up the great work!

**Comment by marceloschmidt** [comment]
@gmsecrieru isn't item 3 related to https://github.com/RocketChat/Rocket.Chat/issues/1334 ?

**Comment by gmsecrieru** [comment]
No. Item no. 3 refers to an unauthorized HTTP client (in this case our oEmbed server-side request to the resource) requesting restricted content.

**Comment by graywolf336** [comment]
@gmsecrieru have you done anything else on getting this to be completed? Sounds like we almost need to implement an api token or system like that which will allow integrations to be configured to be allowed to do items such as requesting downloading items.

**Comment by Megatronic79** [comment]
Is this ready for testing now guys?

**Comment by gmsecrieru** [comment]
@graywolf336 Not really, I have been travelling for the last 3 weeks or so. I think I might have left something-about-to-be-ready-to-commit before that, I will look as soon as I'm able.

**Comment by flashguy22** [comment]
any update on this?

**Comment by marceloschmidt** [comment]
lgtm

**Comment by marceloschmidt** [comment]
LGTM

**Comment by sampaiodiego** [comment]
lgtm

**Comment by marceloschmidt** [comment]
lgtm

**Comment by sampaiodiego** [comment]
lgtm

**Comment by flashguy22** [comment]
Sweet! I've been desperately waiting for this one.

**Comment by Megatronic79** [comment]
Hi guys, when this feature is on uploads dont seem to work on the Browser and get the following error int he logs: (However using ghe desktop app the upload shows correctly)

Error: Not Allowed [403]
    at [object Object].Meteor.fileStore.UploadFS.store.GridFS.onRead (lib/fileUpload.coffee:81:17)
    at Object.path [as handle] (packages/jalik_ufs/ufs-server.js:157:1)
    at next (/var/www/rocket.chat/bundle/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at Object.Package [as handle] (packages/cfs_http-methods/packages/cfs_http-methods.js:422:1)
    at next (/var/www/rocket.chat/bundle/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at middleware (packages/oauth/oauth_server.js:157:1)
    at packages/oauth/oauth_server.js:146:1
with it on using FireFox:

turnedon

With it off with Firefox:

turnedoff

Anyone able to reproduce this?

I tested the protected files from a remote location so that part is working for non-authenticated users.

**Comment by geekgonecrazy** [comment]
@Megatronic79 do you have this on master?  Looks like this may should have undergone more testing before being merged.

**Comment by engelgabriel** [comment]
@rodrigok know about a but on the mobile app, but I didn't know about the browser too.

**Comment by sampaiodiego** [comment]
I've fixed in 1a3796fd06197d98cc5a060314b934733bb12690

**Comment by Megatronic79** [comment]
Thanks guys, confirmed this hotfix is working fine.

**Pull request merged**
