### PR TITLE
[FIX] Admin panel custom sounds, multiple sound playback fix and added single play/pause button

### LINKED ISSUE #16213: [Improvement] Single button for play/pause instead of two
### Description:
In the custom sound admin section, there are three buttons (play, pause and reset). These three buttons are shown seperately. It would be more convinient to show play/pause as a single button like a general media player.

### Steps to reproduce:

1. Go to admin pane-> custom sounds
2. Notice the three media buttons

### Expected behavior:
There should be single play/pause button

### Actual behavior:
There is both play and pause button.
Screenshot from 2020-01-11 23-56-44

### Additional context
I am working on it.

### PR DESCRIPTION
**Pull request by ashwaniYDV**
Closes #16213 #16208 

### Before changes
(1) All sounds can be played simultaneously which overlaps with the other ones.
(2) There are seperate buttons for play and pause.

### After changes:
(1) One sound can be played at a time.
(2) There is a single button for play and pause which looks consistent with most of the media players and is more handy for admins than having seperate buttons for play and pause.

a1

### CODE REVIEW

**Comment by ashwaniYDV** [comment]
@sampaiodiego Kindly please review :)

**Comment by gabriellsh** [comment]
Hey! Really cool what you did, works better in my opinion. Just make it so when the sound finishes playing it on its own resets to the play button.

**Comment by ashwaniYDV** [comment]
> Hey! Really cool what you did, works better in my opinion. Just make it so when the sound finishes playing it on its own resets to the play button.

@gabriellsh I have done the requested changes. But doing so I encountered some more corner case issues. I have solved them too.
Please review.

**Comment by ashwaniYDV** [comment]
@gabriellsh Thank you very much. This reduced lots of code and also I dont have to worry about end cases which I faced using the settimeout. :+1:

**Pull request merged**
