### PR TITLE
Slash command handler

### PR DESCRIPTION
**Pull request by warcode**
Handles all /commands by allowing registered callbacks for commands
First to register takes that command
Any entry starting with / will be intercepted and a message will not be delivered
Format is /command this goes as one big parameter

Updated /me as example

### CODE REVIEW

**Comment by engelgabriel** [comment]
I really REALLY liked it!

**Comment by engelgabriel** [comment]
@warcode I think on the add method, we should allow to pass on a "help" message.. so we can create a /help that will list all /commands

**Comment by warcode** [comment]
@engelgabriel Yes. That is a great idea.

I considered a /help but there either has to be a way to show a message only to the person who typed the command, or have a bot send a direct message which might be confusing to new users.

**Comment by engelgabriel** [comment]
Agrees, i think we could even be just a "autocomplete" box... like the mentions.

**Pull request merged**
