### PR TITLE
[FIX] Thread view expand command in wide screens

### PR DESCRIPTION
**Pull request by edward-raven**
## Proposed changes (including videos or screenshots)
Allows users with wide screens stretch thread sidebar.

## Issue(s)
#22548

## Steps to test or reproduce
- Maximize window to 1920px width
- Open any thread sidebar

Expected: there is expand button
Actual: there is no expand button

### CODE REVIEW

**Comment by ggazzo** [comment]
makes no sense letting the thread be expanded on >1920px  screens, because after that resolution the thread size is a percentage from the screen, and that value is actually bigger than the "expanded"  thread

**Comment by ggazzo** [comment]
but thans

**Comment by ggazzo** [comment]
on even larger screens the effect is the opposite the expanded gets smaller than the normal version :x

**Comment by edward-raven** [comment]
Hi @ggazzo 
Thanks for reply.

You're right, on pretty wide screens (starts from ~2800px) the effect of the `Expand` button is opposite. 
However:
> makes no sense letting the thread be expanded on >1920px screens

it's no quite correct. The suggested fix allows the thread be expanded on greater **or equal** 1920px screens. Here are screenshot on 1920px screen.
Without fix:

With fix:



So, it looks as expected.

BTW: About 24% PC users have 1920x1080 screen resolution, while only ~2% have really wide screens (based on https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide)

**Review by ggazzo — APPROVED** [review]

**Comment by edward-raven** [comment]
@ggazzo Thanks for approval

**Pull request merged**
