### PR TITLE
[IMPROVE] Add decoding for commonName (cn) and displayName attributes for SAML

### PR DESCRIPTION
**Pull request by pkolmann**
I want to create users via SAML. Currently the SAML IDP sends the Attributes urn:oid-encoded. This patch adds the decoding for commonName (cn) and displayName attributes.

Secondly it adds the displayName as a possibility for the name of the new user.

### CODE REVIEW

**Comment by pkolmann** [comment]
@MarcosSpessatto could you please review my changes and help me get them merged. Thanks

**Comment by rodrigok** [comment]
@pkolmann can you fix the conflicts?

**Comment by pkolmann** [comment]
@rodrigok I fear I f*ed up my branch again... :(

I have an updated patch that applies cleanly to 0.73.1. Can you use this as well?

`diff --git a/packages/meteor-accounts-saml/server/saml_server.js b/packages/meteor-accounts-saml/server/saml_server.js
index 4794b9d62..9e87fdca7 100644
--- a/packages/meteor-accounts-saml/server/saml_server.js
+++ b/packages/meteor-accounts-saml/server/saml_server.js
@@ -116,7 +116,7 @@ Accounts.registerLoginHandler(function(loginRequest) {
 
 		if (!user) {
 			const newUser = {
-				name: loginResult.profile.cn || loginResult.profile.username,
+				name: loginResult.profile.displayName || loginResult.profile.cn || loginResult.profile.username,
 				active: true,
 				globalRoles: ['user'],
 				emails: emailList.map((email) => ({
diff --git a/packages/meteor-accounts-saml/server/saml_utils.js b/packages/meteor-accounts-saml/server/saml_utils.js
index 1331abd69..8f156d56f 100644
--- a/packages/meteor-accounts-saml/server/saml_utils.js
+++ b/packages/meteor-accounts-saml/server/saml_utils.js
@@ -361,6 +361,15 @@ SAML.prototype.mapAttributes = function(attributeStatement, profile) {
 	if (!profile.email && profile.mail) {
 		profile.email = profile.mail;
 	}
+
+	if (!profile.displayName && profile['urn:oid:2.16.840.1.113730.3.1.241']) {
+		profile.displayName = profile['urn:oid:2.16.840.1.113730.3.1.241'];
+	}
+
+	if (!profile.cn && profile['urn:oid:2.5.4.3']) {
+		profile.cn = profile['urn:oid:2.5.4.3'];
+	}
+
 };
 
 SAML.prototype.validateResponse = function(samlResponse, relayState, callback) {
`

Maybe someone can tell me, where I did the update of my branch wrong:

`  git clone git@github.com:pkolmann/Rocket.Chat.git rocketChatGit
  cd rocketChatGit/
  git remote add upstream git@github.com:RocketChat/Rocket.Chat.git
  git merge upstream/master
  git push
`

**Comment by pkolmann** [comment]
@Hudell thanks for the hint. I managed now to get everything uptodate. Now you should be able to pull.

**Comment by pkolmann** [comment]
@rodrigok the branch is now in sync and can be merged. Thanks

**Comment by engelgabriel** [comment]
@sampaiodiego can you review and merge this?

**Pull request merged**
