### PR TITLE
Automate statistics generation and send statistics to Rocket.Chat, unless opt-out.

### PR DESCRIPTION
**Pull request by marceloschmidt**

### CODE REVIEW

**Comment by graywolf336** [comment]
Is it going to be enabled by default?

**Comment by marceloschmidt** [comment]
Yes, we would like to receive anonymous stats about deployed rocket.chat instances. If you don't want to send them, you can opt-out.

**Comment by graywolf336** [comment]
Okay good, was going to suggest it be enabled by default. :+1:

**Comment by geekgonecrazy** [comment]
awesome!

**Pull request merged**
