### PR TITLE
Give SlackBridge the option to use a (formatted) alias for imported messages

### PR DESCRIPTION
**Pull request by TobiasKappe**
@RocketChat/core 

I added the option to make the SlackBridge module import messages tagged with a formatted alias. This way, you can tell which messages were imported from Slack and which were sent directly to RocketChat.

### CODE REVIEW

**Comment by rodrigok** [comment]
@marceloschmidt can you review this?

**Comment by rodrigok** [comment]
Hei @TobiasKappe, can you solve the conflicts? I will merge your PR after that

**Comment by TobiasKappe** [comment]
@rodrigok Thanks for getting back to me; I resolved the conflicts.

**Comment by rodrigok** [comment]
Awesome @TobiasKappe, thanks

**Pull request merged**
