### PR TITLE
Release 0.70.2

### PR DESCRIPTION
**Pull request by sampaiodiego**
`2018-10-08  ·  1 🐛  ·  1 👩‍💻👨‍💻`

### Engine versions
- Node: `8.11.3`
- NPM: `5.6.0`

### 🐛 Bug fixes

- E2E alert shows up when encryption is disabled ([#12272](https://github.com/RocketChat/Rocket.Chat/pull/12272))

### 👩‍💻👨‍💻 Core Team 🤓

- [@Hudell](https://github.com/Hudell)

### CODE REVIEW

**Comment by MatthiasHertel** [comment]
hi

where can i see if the docker images is on **0.70.2** ? 

i pulled the latest image (` image: rocketchat/rocket.chat:latest`) and rebuild it ... but i still hang on **0.70.1**

-matthias

**Comment by MatthiasHertel** [comment]
https://hub.docker.com/r/rocketchat/rocket.chat/builds/

is 4month old ? is strange ..

**Comment by a1268512** [comment]
> hi
> 
> where can i see if the docker images is on **0.70.2** ?
> 
> i pulled the latest image (`image: rocketchat/rocket.chat:latest`) and rebuild it ... but i still hang on **0.70.1**
> 
> -matthias

same here

**Comment by reetp** [comment]
Definitely something not right. 'latest' is still on 0.70.1

Removed all images. Changed my compose file to:

image: rocketchat/rocket.chat:0.70.2

➔ System ➔ startup
➔ +-----------------------------------------------------+
➔ |                    SERVER RUNNING                   |
➔ +-----------------------------------------------------+
➔ |                                                     |
➔ |  Rocket.Chat Version: 0.70.1                        |

https://hub.docker.com/r/rocketchat/rocket.chat/tags/

Shows 0.70.2 and 'latest' so presuming there was a mistake in the build setup somewhere.

**Comment by sampaiodiego** [comment]
I'm sorry guys.. I tagged a wrong commit as `0.70.2`.. I'll release `0.70.3` ASAP

**Pull request merged**
