### PR TITLE
Notifying user if an already existing user is added

### LINKED ISSUE #13837: Added user can be added again in channel
### Description:
When we try adding a user to channel, we just can simply add his name in search bar and add to him in the channel, 
Now if we again search his name in add user we can add him again.

### Steps to reproduce:
1. Go to add user in channel
2. Add a user to channel
3. Again search his name in the list.

### Expected behavior:
If user is already in channel he/she should not be in list to get added

### Actual behavior:
We can add the user again !

Screenshot from 2019-03-22 01-03-28

You can see doodle1 is already in channel and yet we can add him again.

### PR DESCRIPTION
**Pull request by gsunit**
Currently, a success `toastr` is displayed even if an already existing user is added to a channel. With this we can issue an elegant little notification, which is only visible to the user, that says `$username is already in here.`
Closes #13837

### CODE REVIEW

**Comment by bhardwajaditya** [comment]
@gsunit I think it would be better if along with the toastr message we can add that users already in the channel are not displayed in the autocomplete popup list.

**Comment by gsunit** [comment]
Thanks, @bharadwajaditya! Can be easily done. But then there will be no notifications.  Let's wait for the reviewers and see what they have to say.

**Comment by bhardwajaditya** [comment]
@gsunit yeah sure. This was just my idea for this issue. Since you are working on it so it will be easy for you to implement it.

**Comment by sudipt1999** [comment]
@gsunit  I was also working on this issue ! my bad I didn't saw the issue referenced.

**Comment by gsunit** [comment]
Closing this PR due to conflicts. Opening a new PR for the same feature, please have a look.

**Comment by sudipt1999** [comment]
Did it creates conflict with https://github.com/RocketChat/Rocket.Chat/pull/13962 @gsunit  ! Please have a look! Mine is for not adding added user to pop up list !

**Pull request closed without merging**
