### PR TITLE
[FIX] Long room announcement cut off

### LINKED ISSUE #8888: [Bug] Long room announcement cut off
### Description:

When creating a long or multi-line announcement, it's not being displayed completely.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3

### Steps to Reproduce:

1. Create a very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very long text for the announcement
2. See it cut
announcement cut off

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #8888

image

### CODE REVIEW

**Comment by karlprieb** [comment]
@sampaiodiego thanks for your review :) I fixed, take a look:

image

**Comment by soundstorm** [comment]
But this won't work on mobile, right?
I don't know any mobile browser showing the title tag.

**Comment by karlprieb** [comment]
@soundstorm No, do you have a suggestion on how this should work on mobile?
You can always open the Room Info tab to see the complete announcement :)

**Comment by soundstorm** [comment]
@karlprieb could be an ontouch event with a popup, so title will show up on desktop and popup on mobile (and touch enabled desktops).

**Comment by rodrigok** [comment]
@soundstorm Thanks by the suggestion, I'll merge this PR and we can improve it for mobile before the final release, is that ok @karlprieb ?

**Comment by karlprieb** [comment]
Sure 👍

**Pull request merged**
