### PR TITLE
[NEW][Omnichannel] Livechat widget support for rich messages via UiKit

### PR DESCRIPTION
**Pull request by ggazzo**
## Proposed changes

This pull request updates the livechat widget, making it possible to render rich messages via UiKit
## Screenshots
Clipboard - August 21, 2020 9_57 PM
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Elintondm** [comment]
Anyne knows how to enable this feature? Please!!!!

**Comment by OnthegOinOz** [comment]
Hi @ggazzo Nice to see what you've been working on be released. If I understand correctly? Rich messages via UiKit is available in the support bot channel for the support person to receive rich messages with actions (like buttons?) and we can create them via API?

If that is correct, is there or will there be a way for using the UIKit to post message via API in a specified channel and also directly to a person. Like we use RC to post all our external system notifications.

Cheers
Cam

**Comment by ggazzo** [comment]
hey @cam-cross @Elintondm @AhmedNageh08 , sorry for the late response...the UiKit, was designed to work with rocketchat apps, because with action needs an appID and actionID to work. I can see two ways to develop what you want @cam-cross. 

first way: developing a rocketchat.app , create an endpoint, and send messages by this custom endpoint/api  instead of the original endpoint..

second way: developing a rocketchat.app that intercepts the message creation and inserts their rich message

**Comment by cam-cross** [comment]
Thanks @ggazzo ... I think this is a similar suggestion from @Sing-Li . Though @rodrigok suggested keeping it easy and using markups (which is limited). I'll have to get our engineer to research what it would take him to build rocketchat.app from either suggestion.

**Comment by ggazzo** [comment]
Markups would insert some security issues, anybody could reproduce the payload and don't know what could happen, since you will develop an app anyway, I would create a new endpoint (protected)

**Comment by ggazzo** [comment]
Btw did you mean markdown? Sorry maybe I got it wrong 😬

**Comment by cam-cross** [comment]
ha ha @ggazzo again I suffer from not being an engineer and using the incorrect terms... yes Rodrigo's suggestion was to use Markdowns

**Pull request merged**
