### PR TITLE
[BREAK] Remove internal hubot package

### PR DESCRIPTION
**Pull request by MarcosSpessatto**

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Updated title.  We **for sure** must label this one as a breaking change

**Comment by thaiphv** [comment]
How is it going to affect existing installations of Rocket.Chat when we upgrade them to this release?

**Comment by geekgonecrazy** [comment]
You would have to move to external hubot.  The scripts should work identically

**Comment by thaiphv** [comment]
Thanks for the clarification @geekgonecrazy

**Comment by tholu** [comment]
@geekgonecrazy So using https://github.com/RocketChat/hubot-rocketchat in a docker deployment is just fine, right?

**Comment by geekgonecrazy** [comment]
> @geekgonecrazy So using https://github.com/RocketChat/hubot-rocketchat in a docker deployment is just fine, right?

correct!

**Comment by whande1992** [comment]
Com o Hubut interno, o bot funcionava em todos as salas e canais, agora funciona somente em canais e no privado somente com o usuário rocket.chat. Qual a forma de habilitar em todas as salas de conversas?

**Pull request merged**
