### PR TITLE
Connecting to agent message option

### PR DESCRIPTION
**Pull request by AlecTroemel**
@RocketChat/core 

Option to replace text input with "connecting to agent" message when a guest is waiting to connect to an agent (Guest Pool routing method only)
screen shot 2016-10-07 at 11 43 25 am

### CODE REVIEW

**Comment by rodrigok** [comment]
@AlecTroemel this PR was approved, can you fix the conflicts?

**Comment by AlecTroemel** [comment]
@rodrigok sorry just saw this, I can begin the fixes today

**Comment by rodrigok** [comment]
@AlecTroemel Awesome, thanks

**Comment by AlecTroemel** [comment]
Note that It will spin "connecting to agent" endlessly if a livechat is closed, and the guest types a new message in an attempt to start a new chat. PR #4740 fixes this.

**Pull request merged**
