### PR TITLE
Search for private groups

### LINKED ISSUE #3785: Search for private groups
We use rocket chat as internal chat and discuss many issues in private channels.
Our problem is the search function of rocket.
By using STRG+P you`re able to search for users or channels. Unfortunately you`re not able to search for private groups.
Can you please extend the search function also on private groups.

### PR DESCRIPTION
**Pull request by LNarita**
@RocketChat/core 

Closes #3785 

Expands search to private groups for time and `ctrl+f` saving.
BTW, I'm also cleaning the last typed value after hiding the spotlight input since the search command is bind to `ctrl+p` and not `ctrl+p ctrl+a` 'haha. :smile:

### CODE REVIEW

**Comment by rodrigok** [comment]
Thanks @LNarita but we already changed the spotlight implementation in another branch, I did a new PR to bring this implementation to develop as you can see here https://github.com/RocketChat/Rocket.Chat/pull/4269

**Comment by LNarita** [comment]
No problem!
:smile:

**Comment by rodrigok** [comment]
@LNarita Please test the new implementation and tell me what do you think

**Comment by LNarita** [comment]
@rodrigok I've just tested it and it feels great! Thanks a lot!

**Pull request closed without merging**
