### PR TITLE
test: Copy new EE test license from CI to unit tests

### PR DESCRIPTION
**Pull request by d-gubert**
## Proposed changes (including videos or screenshots)

Copy the new EE test license from CI to the licnese package unit tests

### CODE REVIEW

**Comment by ggazzo** [comment]
What about using the env var and the hardcoded one as fallback?

**Comment by d-gubert** [comment]
> What about using the env var and the hardcoded one as fallback?

did

**Review by rodrigok — DISMISSED** [review]

**Review by tassoevan — APPROVED** [review]

**Pull request merged**
