### PR TITLE
[FIX] Database indexes not being created

### PR DESCRIPTION
**Pull request by sampaiodiego**
## Proposed changes (including videos or screenshots)

Indexes from raw models using the property `indexes` were not being created due to an issue on OOP works in JS.

### CODE REVIEW

**Review by ggazzo — CHANGES_REQUESTED** [review]
check the warnings `Missing return type on function`

**Comment by sampaiodiego** [comment]
I saw the warnings.. TS can correctly infer the missing returning type based on the parent class, that's why I didn't added them..

also, if we care about that warning specifically we should turn them into errors don't you think?

**Comment by ggazzo** [comment]
Yep , but the infer can lead you to add undesirable results, thats why we force you to explicit define the return
> TS can correctly infer the missing returning type based on the parent class, that's why I didn't added them..

**Comment by sampaiodiego** [comment]
> Yep , but the infer can lead you to add undesirable results, 

I don't understand why it lead to undesirable results, can you please explain that?

> thats why we force you to explicit define the return

this is not accurate, there is nothing forcing anything, they're just warnings.. and this also relates to my previous question that you probably didn't see: 

> also, if we care about that warning specifically we should turn it into errors don't you think? I mean, if you have to check the linting logs to ask for changes if a warning show up, IMO our linting rules are bad and should be improved, so we can focus on what matters.

**Comment by ggazzo** [comment]
> > Yep , but the infer can lead you to add undesirable results,
> 
> I don't understand why it lead to undesirable results, can you please explain that?

imagine that we have a colleague, who is working in the following code:..
```
const fn = () => { 

	if(a){
		return false
	}

	return true;
}
``

somehow he decides to do something like 


```
const fn = () => { 

	if(a){
		return false
	}

	if(b) {
		return 'yes';
	}

	return true;
}

The ts will infer the result  as `boolean | string` and everything will "look good", until in same place we realise having a string instead a boolean is a problem;

that why we suggest always starting by the result definition


I agreed it should be an error, if we deal with warnings the same way we handle erros

**Review by ggazzo — APPROVED** [review]
Warnings are a parallel discussion ;)

**Pull request merged**
