### PR TITLE
[NEW] Sort channel directory listing by latest message

### LINKED ISSUE #11951: Sort channel directory listing by newest message
In the "Directory" for a Rocket.chat instance the channels can be sorted by "Name", "Users", and "Created At". Often I'd like to sort by "Last Message" but it's not enabled for that column. Ideally the ability to sort on that column could be added to the directory.

_Edit:_ This would also be useful for folks who are viewing channels in "preview" mode but not actually joining channels.

### PR DESCRIPTION
**Pull request by subham103**
closed #11951 

Currently, In the "Directory" for a Rocket.chat instance the channels can be sorted by "Name", "Users", and "Created At". Now by clicking on the Last Message field, we can sort the channels in ascending/descending order. 
Rocket Chat(3)
Rocket Chat(4)

@sampaiodiego, please review:)

### CODE REVIEW

**Comment by subham103** [comment]
@sampaiodiego, please review this!

**Comment by subham103** [comment]
@gabriellsh Does this pr is in a state to merge? Should I rebase to the current state so that this pr will be merged?

**Comment by subham103** [comment]
@ggazzo @gabriellsh please comment^

**Comment by Kayoku** [comment]
Hi, thank you for this PR ! Do you think it's possible to make this also for the "topic" column ?
I think that it's almost the same file to edit..
Thank you again !

**Pull request merged**
