### PR TITLE
[IMPROVE] Message Box icons have hover effect

### LINKED ISSUE #21068: [UI] Message Box icons don't have hover effect.
### Description:

If the user hovers over icons like Emoji picker or microphone or '+' icon, the cursor changes to pointer but the icon color remains the same.

### Steps to reproduce:

1. Open any room, and Try hovering over any of the mentioned icons.

### Expected behavior:

We can add a hover effect for changing the colour of the icon.

### Actual behavior:

Only cursor changes to pointer.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0-develop
- Operating System:  linux
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome 88.0
- Operating System: Windows 10

### Additional context

https://user-images.githubusercontent.com/53378650/110704844-8b6f7f00-821b-11eb-828a-753fe9d81027.mp4

### PR DESCRIPTION
**Pull request by apurv-1**
- [x] I have read the Contributing Guide.
  - [x] I have signed the CLA.
  - [ ] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  - [ ] Any dependent changes have been merged and published in downstream modules
  - [ ] I have added necessary documentation (if applicable)

## Proposed changes (including videos or screenshots)

Added hover effect for changing the colour of the icon on MessageBox.

https://user-images.githubusercontent.com/53378650/110706291-a6db8980-821d-11eb-8fbf-4258c068d453.mp4

## Issue(s)

fixes #21068

### CODE REVIEW

**Comment by apurv-1** [comment]
@dougfabris Please have a look! Thanks.

**Comment by aditya-mitra** [comment]
@apurv-1 Can add a **_closes_** under the Issues of this pr?
Something like this : `Closes #21068`.

This would not only **close the issue on this pull request being merged** but also be helpful while seeing the issues page **indicating that this issue already has a pull request.**

If you want to know more about such keywords, please check it out [here](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). :smiley:

**Comment by apurv-1** [comment]
Yeah, Sure! Thanks for the suggestion. 😃

**Comment by dougfabris** [comment]
@apurv-1 Recently we refactor our Message Composer and it already fixes it! #27566
Because of that, I'm closing this one, thank you so much for your help!

**Pull request closed without merging**
