### PR TITLE
[FIX] Dropdown elements were using old styles

### PR DESCRIPTION
**Pull request by kaiiiiiiiii**
Closes [my promise](https://github.com/RocketChat/Rocket.Chat/pull/9883#issuecomment-368663288) to @karlprieb.

This PR changes all dropdown element types from rc-input__element to rc-select__element.

Two more things:
1. The dropdown has still a cut off at the bottom (like any other dropdown in RC). May someone can give me a hand with that? :)
2. Is it possible to remove the margin ("0.5rem 0") from the rc-select element? Looks a lot better without it.

**Before (User UI):**
screen shot 2018-04-17 at 22 17 28

**After (User UI):**
screen shot 2018-04-17 at 22 17 21

**Before (Admin UI):**
screen shot 2018-04-17 at 22 17 53

**After (Admin UI):**
screen shot 2018-04-17 at 22 13 43

### CODE REVIEW

**Comment by karlprieb** [comment]
@kaiiiiiiiii can you add [this arrow icon](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-apps/client/admin/appManage.html#L234) like we did on the RocketChat Apps admin panel?

Thank you! 👍

**Comment by kaiiiiiiiii** [comment]
@karlprieb Done :)

**Comment by karlprieb** [comment]
Thank you @kaiiiiiiiii :)

Can you add a screenshot about the cut off at the bottom that all select elements have?

**Comment by kaiiiiiiiii** [comment]
Will do that as soon as I'm home from work @karlprieb  :)

**Comment by kaiiiiiiiii** [comment]
**100% zoom**
screen shot 2018-04-18 at 21 27 34

**400% zoom**
screen shot 2018-04-18 at 21 28 14

The UI gets a bit messy with zoom, but it's really hard to see the cut off without it.

**Comment by karlprieb** [comment]
@kaiiiiiiiii you can put `line-height: 1rem !important;` on `.rc-select__element` class for now and we will find a better way to fix that in the future.

**Comment by kaiiiiiiiii** [comment]
Done that as well, mate :)

**Pull request merged**
