### PR TITLE
chore(deps): Update exif-be-gone, enable eslint no-var-requires

### PR DESCRIPTION
**Pull request by joshbuddy**
This updates the version of exif-be-gone being used and removes the eslint carve out for `no-var`. The updates to exif-be-gone are merely linting changes and packages changes.

### CODE REVIEW

**Review by ggazzo — APPROVED** [review]

**Comment by joshbuddy** [comment]
@ggazzo seems like issues with tokens in the workflow actions

**Comment by joshbuddy** [comment]
Hey @sampaiodiego I noticed you activity on this PR. I was curious if its possible to get a PR like this reviewed and merged and if so, what should I do? Also fine dropping it, just wondering.

**Comment by sampaiodiego** [comment]
@KevLehman do you recall why the `require` was needed?

**Comment by KevLehman** [comment]
IIRC, this was to prevent TS typings from getting weird by importing the TS files inside exif-be-gone package, related to this: `https://github.com/microsoft/TypeScript/issues/41883`

If the application builds and typecheck works, maybe it's good to remove, otherwise, we have to keep it.

**Comment by joshbuddy** [comment]
@KevLehman Oh, I thought it was releated to https://github.com/joshbuddy/exif-be-gone/commit/cfe4bdb2d3ff1f51c7889dbde11d7deb8d01b544

Anyways, if its really still needed, so be it. Thanks for looking at it.

**Comment by sampaiodiego** [comment]
idk where the button to allow CI to run is 🙈

**Review by sampaiodiego — APPROVED** [review]

**Pull request merged**
