### PR TITLE
Fixing potential security issue ( #6196 ) by removing from field.

### PR DESCRIPTION
**Pull request by pkgodara**
Solving security issue shown in #6196 by removing user defined "from" field and using "From_Email" setting set by administrator in SMTP settings.

### CODE REVIEW

**Comment by marceloschmidt** [comment]
I am not sure this is what the @RocketChat/core team wants... https://github.com/RocketChat/Rocket.Chat/issues/6196#issuecomment-288096955

**Comment by rodrigok** [comment]
@engelgabriel @graywolf336 @geekgonecrazy @sampaiodiego what do you think?

**Comment by sampaiodiego** [comment]
I agree with @marceloschmidt , it is not a security issue, since only administrators could use this.

BUT, I liked @pkgodara idea in using the `From` value set on admin. I also can see some email providers rejecting emails if don't provide a valid `From` value. 

So, I'm good with this PR.

**Comment by engelgabriel** [comment]
I understand the intent, but I don't agree with this PR. This features was created specifically for the use case you are trying to block. We used it to send email alerts or announcements for the registered users as from different parts of the organisation, so they would get the replies.

So I think this can be a setting or a permission if some admins want to block it?

**Comment by engelgabriel** [comment]
Maybe we should just pre-fill the input with the `From_Email` value. On the end of the day, the admin can change the value of `From_Email` to what ever he wants before using the email tool, and change it back if he really wants to... unless in some hosting providers this setting is block via environment variable... in witch case the HOSTING admin, should be able to block the CHAT admin from doing so... ideas?

**Pull request closed without merging**
