### PR TITLE
[oembed] correct url when supply from providers

### PR DESCRIPTION
**Pull request by nishimaki10**
`URL.format` is not using the `urlObj.path`.

### CODE REVIEW

**Comment by rodrigok** [comment]
Yes, it's not using the `path`, that's why we get the `pathname` to pass inside the `parsedUrl`.

Can you give an example when this is not working?

**Comment by nishimaki10** [comment]
@rodrigok My example

```diff
     parsedUrl = _.pick urlObj, ['host', 'hash', 'pathname', 'protocol', 'port', 'query', 'search']
  
+    console.log urlObj
     RocketChat.callbacks.run 'oembed:beforeGetUrlContent',
     	urlObj: urlObj
     	parsedUrl: parsedUrl
+    console.log urlObj
  
     url = URL.format urlObj
+    console.log url
     opts =
     	url: url
```

`urlObj` is modified to provider's url in `oembed:beforeGetUrlContent`.
In my understanding, `parsedUrl` is the original url.

```coffee
			data.urlObj.port = consumerUrl.port
			data.urlObj.hostname = consumerUrl.hostname
			data.urlObj.path = consumerUrl.path
```

Get 3 logs.

```
{ protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'www.youtube.com',
  port: null,
  hostname: 'www.youtube.com',
  hash: null,
  search: '?v=NGcT3yPlXUY',
  query: 'v=NGcT3yPlXUY',
  pathname: '/watch',
  path: '/watch?v=NGcT3yPlXUY',
  href: 'https://www.youtube.com/watch?v=NGcT3yPlXUY' }
```
```
{ protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'www.youtube.com',
  port: null,
  hostname: 'www.youtube.com',
  hash: null,
  search: '?v=NGcT3yPlXUY',
  query: 'v=NGcT3yPlXUY',
  pathname: '/watch',
  path: '/oembed?maxheight=200&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DNGcT3yPlXUY',
  href: 'https://www.youtube.com/watch?v=NGcT3yPlXUY' }
```

`urlObj.path` is changed. But `URL.format urlObj` returns following result.

```
https://www.youtube.com/watch?v=NGcT3yPlXUY
```

expect:
```
https://www.youtube.com/oembed?maxheight=200&url=https%3A%2F2Fwww.youtube.com%2Fwatch%3Fv%3DNGcT3yPlXUY
```

And get error.

```
Exception in defer callback: SyntaxError: Unexpected token <
	at Object.parse (native)
	at __coffeescriptShare (packages/rocketchat_oembed/server/providers.coffee:70:19)
	at packages/rocketchat_lib/lib/callbacks.coffee:73:21
        ...
```

**Comment by nishimaki10** [comment]
We can consider that better implementation. But this PR is a shortcut to fix this bug for now.

**Comment by rodrigok** [comment]
So, the problem is not related with this part, but with the provider changing the path and not the pathname + query.

Should change the file `providers.coffee`:
```diff
RocketChat.callbacks.add 'oembed:beforeGetUrlContent', (data) ->
	if data.parsedUrl?
		url = URL.format data.parsedUrl
		provider = providers.getProviderForUrl url
		if provider?
			consumerUrl = Providers.getConsumerUrl provider, url
			consumerUrl = URL.parse consumerUrl, true
			_.extend data.parsedUrl, consumerUrl
			data.urlObj.port = consumerUrl.port
			data.urlObj.hostname = consumerUrl.hostname
-			data.urlObj.path = consumerUrl.path
+			data.urlObj.pathname = consumerUrl.pathname
+			data.urlObj.query = consumerUrl.query
```

Do you agree?

**Comment by nishimaki10** [comment]
@rodrigok Oh, I see! Certainly it better of your way is smart.

**Comment by nishimaki10** [comment]
@rodrigok Fixed it. How does that look?

**Comment by rodrigok** [comment]
LGTM

**Comment by engelgabriel** [comment]
Is this related to https://github.com/RocketChat/Rocket.Chat/issues/2684 ?

**Comment by nishimaki10** [comment]
Thank you for advise!

**Pull request merged**
