### PR TITLE
[FIX] cannot add multiple lines in attached file description 

### PR DESCRIPTION
**Pull request by Kunalvrm555**
- [x] have read the Contributing Guide - https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
  - [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
  - [x] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  - [ ] I have added necessary documentation (if applicable)
  - [x] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)
BEFORE:

https://user-images.githubusercontent.com/67605729/159765148-cb44f565-c7cc-4c63-9a49-d2bcab40816f.mp4

AFTER:

https://user-images.githubusercontent.com/67605729/159765173-fbc93b43-3cb8-4d86-b29e-fdf8d4628831.mp4

## Issue(s)

#24776 
## Steps to test or reproduce

#24776

### CODE REVIEW

**Comment by ankar84** [comment]
Looks good! 
Users ask for that feature when they want to add large message to picture (pretty often in fact)

**Comment by Kunalvrm555** [comment]
hey @debdutdeb 
Can you have a look at this one ?
Please suggest any changes, if any, that need to be accomodated to proceed.

**Comment by debdutdeb** [comment]
According to our PM, the description field not being multiline is by design. I'll double check with him

**Comment by debdutdeb** [comment]
Yes, just confirmed. Unfortunately we won't be able to move forward with this one. Thank you for your effort though. I'm sure you learnt something from the experience too ;)

**Comment by ankar84** [comment]
> According to our PM, the description field not being multiline is by design

What a pitty...

**Comment by debdutdeb** [comment]
@dudanogueira - please add this to the list as well, let's see if we can still make this happen or not :)

**Comment by ankar84** [comment]
@debdutdeb @dudanogueira hey!
https://github.com/RocketChat/Rocket.Chat/issues/22732
Mobile client have that ability, and I 100% sure, that it is right. Because Telegram (messaging golden standard nova days) have that ability too.
What PM say about the reasons of such decision?

**Comment by lcharette** [comment]
> Mobile client have that ability

Then mobile should at least be consistent with web...

**Pull request closed without merging**
