### PR TITLE
Revert "fix: Inconsistent Markdown Formatting in Custom Status Field"

### PR DESCRIPTION
**Pull request by csuadev**
Reverts RocketChat/Rocket.Chat#32574 from community since there are some scenarios where it is making channels to break where the MarkdownComponent is used.

Task: [SUP-537](https://rocketchat.atlassian.net/browse/SUP-537) [CORE-651](https://rocketchat.atlassian.net/browse/CORE-651)

[SUP-537]: https://rocketchat.atlassian.net/browse/SUP-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-651]: https://rocketchat.atlassian.net/browse/CORE-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by yash-rajpal — APPROVED** [review]

**Comment by KevLehman** [comment]
Can you describe the scenarios or link a task related with this revert? Also, the original PR was closign a support issue + 2 github issues, should we re-open them?

**Review by KevLehman — CHANGES_REQUESTED** [review]
the above comment

**Comment by scuciatto** [comment]
> Can you describe the scenarios or link a task related with this revert? Also, the original PR was closign a support issue + 2 github issues, should we re-open them?

I reopened the tasks and GH issues

**Review by KevLehman — APPROVED** [review]

**Comment by KevLehman** [comment]
Thanks @scuciatto !

**Pull request merged**
