### PR TITLE
[Markdown] Add schemes settings for link

### LINKED ISSUE #2656: Markdown Headers do not work
Your Rocket.Chat version: 0.23.0

I set Markdown Headers to `True`. However, do not work with the user does not have a `view-privileged-setting` permission.

 I pended the #2652, because I have found this issue.

### PR DESCRIPTION
**Pull request by nishimaki10**
@RocketChat/core 

Closes #2656
Add `public: true` for settings.

Add schemes settings. (Default: http,https)

Markdown settings

### CODE REVIEW

**Comment by rodrigok** [comment]
Hi @nishimaki10, I fixed the setting problem and the missing style in this PR https://github.com/RocketChat/Rocket.Chat/pull/2797

Can you move your translates into files at `rocketchat-lib/i18n/`? We removed all i18n files of our packages to centralize the translations.

**Comment by nishimaki10** [comment]
@rodrigok I move translates, and merge latest develop branch. Thanks.

**Comment by rodrigok** [comment]
@nishimaki10 Awesome :smile:

**Comment by rodrigok** [comment]
LGTM

**Comment by engelgabriel** [comment]
LGTM

**Pull request merged**
