### PR TITLE
[FIX] Remove all agent subscriptions when an Omnichannel chat is closed

### PR DESCRIPTION
**Pull request by renatobecker**
When an Omnichannel chat is closed the subscription of the agent who is serving the chat is removed, but other agents may join the conversation and, in that case, the subscriptions of other agents are not removed, hence, the chat gets stuck on their queues and prevent them from taking new chats in the queue.

Now, all room subscriptions will be removed as soon as the chat is closed.

### CODE REVIEW

**Review by sampaiodiego — COMMENTED** [review]
@renatobecker two questions:

- any special reason to target this to a patch release? from what I understood it is been like this for a long time, seems like a regular fix to be on the next minor release;
- for those agents that stuck on the queue because their subscriptions were not removed, are you not planning to add a migration to clean their queues?

**Comment by renatobecker** [comment]
> @renatobecker two questions:
> 
> * any special reason to target this to a patch release? from what I understood it is been like this for a long time, seems like a regular fix to be on the next minor release;
> * for those agents that stuck on the queue because their subscriptions were not removed, are you not planning to add a migration to clean their queues?

@sampaiodiego you're right, we can wait for the next minor release.
Regarding migration, yes, it requires a migration which I'll add here too. I'll set this PR as a draft in order to prevent any incomplete merge.

**Comment by sampaiodiego** [comment]
Great, thanks @renatobecker .. the current code looks good, waiting the migration for the final review :)

**Comment by renatobecker** [comment]
> Great, thanks @renatobecker .. the current code looks good, waiting the migration for the final review :)

@sampaiodiego I just submitted the migration file, this PR is no longer in draft mode.
Thanks!

**Review by murtaza98 — DISMISSED** [review]

**Review by sampaiodiego — APPROVED** [review]

**Pull request merged**
