### PR TITLE
Limit message box height

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

# Before
captura de tela 2016-09-15 as 16 03 33

# After
captura de tela 2016-09-15 as 16 03 51

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
With this would it make sense to add scrollbar? So if they want to use mouse to scroll instead of arrow keys?

**Comment by rodrigok** [comment]
@RocketChat/core Can someone test in windows to see if there are ugly scroll bars inside the textarea?

**Comment by rodrigok** [comment]
@geekgonecrazy I did 😄

**Comment by geekgonecrazy** [comment]
@rodrigok ah!  I just realized that, just couldn't see them in the screenshot 👍

**Comment by rodrigok** [comment]
@engelgabriel Please do not merge!

**Comment by rodrigok** [comment]
@geekgonecrazy I did some changes, it's better in macOS with `show scroll bars` enabled

**Comment by geekgonecrazy** [comment]
Windows 10 edge:
No text / Single line of text:
image

Long text:

image

**Comment by geekgonecrazy** [comment]
@rodrigok `-ms-overflow-style: -ms-autohiding-scrollbar;` seems to help

**Comment by sampaiodiego** [comment]
this is how it looks on Firefox (Ubuntu):
image

**Comment by rodrigok** [comment]
@sampaiodiego can you try again? I did some improvements

**Comment by sampaiodiego** [comment]
@rodrigok tried! much better =)

**Pull request merged**
