### PR TITLE
logo and sounds fix for apache subfolder proxy 

### PR DESCRIPTION
**Pull request by xklonx**
when apache proxifies url like http://domain.com/chat/
path must be relative to base (root) url like http://domain.com/chat/assets/logo
and not http://domain.com/assets/logo

@RocketChat/core

### CODE REVIEW

**Comment by engelgabriel** [comment]
@xklonx why did you close this? Was the fix not working?

**Comment by xklonx** [comment]
I did commit with wrong email address and have not found how to fix it. Later, I'll recreate a fork and reopen the request.
I'm not familiar with the project structure, prompt, whether will create a need for the migration of these changes? I do not think I can do it.

**Comment by engelgabriel** [comment]
@marceloschmidt can you review if he needs to create the migration for these changes?

**Comment by marceloschmidt** [comment]
No need for migration, as any custom sound would already have the correct path. This PR is good! Thanks @xklonx

**Comment by xklonx** [comment]
I recreated [https://github.com/RocketChat/Rocket.Chat/pull/6202](https://github.com/RocketChat/Rocket.Chat/pull/6202)

**Pull request closed without merging**
