### PR TITLE
[NEW] Added chat.getDeletedMessages since specific date

### PR DESCRIPTION
**Pull request by MarcosSpessatto**
Closes: https://github.com/RocketChat/Rocket.Chat/issues/12155

### CODE REVIEW

**Comment by vynmera** [comment]
Can we have a permission for this, or some kind of server option to disable this? It's a very bad idea to just expose all deleted and pruned messages to all users... and even if not visible to all users, this may still raise questions with some GDPR practices.

**Comment by cardoso** [comment]
@vynmera The "msg" field (the actual content of the message) is emptied when the message is deleted. You can se an example in the WIP docs: https://github.com/RocketChat/docs/pull/1028/files

@MarcosSpessatto can you confirm this endpoint never returns the "msg" field?

**Comment by rafaelks** [comment]
@MarcosSpessatto Yes, thanks for looking into it @cardoso, only the `_id` is enough here.

**Comment by vynmera** [comment]
Yeah, just IDs is fine!

**Comment by engelgabriel** [comment]
please https://github.com/RocketChat/docs/pull/1028 too

**Pull request merged**
