### PR TITLE
[NEW] Contextual Bar Redesign

### LINKED ISSUE #8965: Owner cannot set self as leader or moderator
In a recent discussion in our Chat community, it came to our attention that owners of channels cannot set themselves as moderators or leaders of a channel. The discussion was initiated by a question about the difference between the three roles, and the mention that a leader's avatar, status and "chat now" option can be displayed at the top of a room, which many people find a desirable capability (that's how it was discovered that owners of a channel cannot change their own roles). 
Also in the discussion, it came up that even though an owner is not supposed to be able to leave a channel or group without designating someone else as an owner, it actually happened to one user, so now there is an ownerless group that he can't join unless he is invited.
Since the presumption is an owner cannot change his or her role so there will be no accidental abandonment of channels, that actually has happened, and in the meantime, owners of channels who would like to take advantage of the leader function cannot.
Unless we are missing something obvious! 
Thank you!

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. 
2. 
3.

### PR DESCRIPTION
**Pull request by ggazzo**
@RocketChat/core 

closes #8965

### CODE REVIEW

**Comment by ggazzo** [comment]
@karlprieb 
image

**Comment by ggazzo** [comment]
@karlprieb I found problems on RTL :/

**Comment by karlprieb** [comment]
Thanks @ggazzo for your report, I will review my changes and fix.

**Comment by geekgonecrazy** [comment]
Once you click in on member list it seems to have no way to go back to member list.  Even when hitting the x and clicking member list again.  Just fyi.

Looks fantastic though 😁

**Comment by geekgonecrazy** [comment]
@ggazzo this error from ci:
image

**Comment by geekgonecrazy** [comment]
Fields in room info need some attention:

image

**Comment by graywolf336** [comment]
Any idea when this will be completed and merged?

**Comment by cyclops24** [comment]
Guys, if you want and deploy somewhere then I can reviewed new design in RTL mode and report bugs here to fix before PR merge. 😉 

**/CC:** @karlprieb @ggazzo @engelgabriel

**Comment by geekgonecrazy** [comment]
@cyclops24 designpreview.rocket.chat 😏

**Pull request merged**
