### PR TITLE
[FIX] User's Custom Status to be displayed in Direct Chat

### LINKED ISSUE #20197: User's Custom Statuses no longer displayed in Direct Chat
### Description:

Custom User statuses don't appears in the windows at the top by Username on Direct Message Windows.   If you click the User Info button it appears in there, but that is not helpful.   It was helpful to see Custom Status Messages next to a user's name when direct messaging.    It use to appear much like how Topics appears in Rooms.
Request to reinstate the ability for Custom Status messages to be displayed in a direct message windows.

### Steps to reproduce:

1. Have any user set a custom status
2. Start a direct message with them

### Expected behavior:

Custom Status should appear by user's name in a direct message window

### Actual behavior:

No custom status appears, it is listed under user info only

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System:  3.10.0-1160.6.1.el7.x86_64
- Deployment Method: tar
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v12.20.1
- MongoDB Version:3.6.21

### Client Setup Information

- Desktop App or Browser Version:  Both the latest desktop client and Chrome/Brave Browsers were used
- Operating System: Win 10 1909

### PR DESCRIPTION
**Pull request by aditya-mitra**
## Proposed changes (including videos or screenshots)

In a **2-person direct message**, the status of the *other* user could not be seen in the Header.
It has been fixed by fetching the user's status-text in a 2-person direct message room.

status can be seen

## Issue(s)

Closes #20197 

## Steps to test or reproduce

Same as mentioned in #20197 

## Further comments

The status-text of the user (who you are chatting with in direct message) can be shown as the room topic.
Room Topics are unaffected by this change.

Displaying the status text in the header is more convenient than click on the user to find his/her status.

### CODE REVIEW

**Comment by aditya-mitra** [comment]
@ggazzo Can you please review :D

**Comment by wreiske** [comment]
Is this reactive? E.g. if someone updates their status, does it update automatically or do you have to refresh the room?

**Comment by aditya-mitra** [comment]
@wreiske 
No, it's not reactive.
If the user updates his **custom status**, we have to manually refresh.

But, the his **online/offline status is reactive**.

I could not find an implementation of *reactive user custom status text* in the client folder.

**Comment by wreiske** [comment]
My original implementation before the switch to react was reactive. I would say anywhere a status message shows (top of room, inside user popup, sidebar, etc.) It should be reactive and update when the user updates their status.

**Comment by aditya-mitra** [comment]
@wreiske Can you please point out (or share) your implementation?
I would try to add that in `react`.

**Comment by wreiske** [comment]
The original PRs:

https://github.com/RocketChat/Rocket.Chat/pull/13933
https://github.com/RocketChat/Rocket.Chat/pull/14853

Specifically the room headers: https://github.com/RocketChat/Rocket.Chat/pull/14853/files#diff-b200b9e23149e92470df6e0b1601a6b817f472d95764df95301388ed6c992df4

Thanks for your help @aditya-mitra !

**Comment by aditya-mitra** [comment]
@wreiske I made the *user status text **reactive***!.

I used another hook `function` to get the *live user status text*.

I have also made a short video to demonstrate it working.

https://user-images.githubusercontent.com/55396651/106020028-508d0e00-60e9-11eb-9384-62a801b0b6b3.mp4

**Comment by aditya-mitra** [comment]
@ggazzo Can you please review :D

**Comment by aditya-mitra** [comment]
@ggazzo Are some more changes required?
I will do those as soon as possible.

**Comment by aditya-mitra** [comment]
Closing this in favour of #20593 .

**Pull request closed without merging**
