### PR TITLE
[FIX] Error message for making discussion channel favorite

### LINKED ISSUE #21041: Making Discussion Channel to favourite
### Description:

If user try  to add discussion channel to favourite It don't show any pop-up/message if user is not the part of that Discussion channel

### Steps to reproduce:

1. Try to add any Discussion channel to your favourite (that you are not part of it)

### Expected behavior:

At-least we can show any can of pop-up/message

### Actual behavior:

it's like kind of error why i can not mark it favourite

https://user-images.githubusercontent.com/51324264/110456821-02a7f480-80f0-11eb-8e23-4f2fc9cd9eec.mp4

### Server Setup Information:

- Version of Rocket.Chat Server:  3.13.0-develop
- Operating System: linux
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chorme
- Operating System:Window 10

### PR DESCRIPTION
**Pull request by shrinish123**
Added an error toast message if one tries to make a discussion channel favorite which he is not a part of.

## Proposed changes (including videos or screenshots)

Initially, it used to show nothing as can be seen on issue #21041 
Right now it catches the error and shows in the toast message as shown 
Screenshot (9)

## Issue(s)

Fixes #21041 

## Steps to test or reproduce
Try to add a discussion as your favorite without being a member of the discussion

## Further comments

The message shown in the toast message comes from the server and I only catch the error coming from the serer and display it through the toast message

### CODE REVIEW

**Comment by shrinish123** [comment]
Please Review @dougfabris

**Comment by dougfabris** [comment]
> Please Review @dougfabris

@shrinish123 Unfortunately the problem here is deeper. We have two things to work on:

1. If we're not part of a channel and we open a discussion, the breadcrumbs do not show the proper parent room. 

image

2. The favorite button should display only if we already joined the conversation. 

If you could help us with that, let me know. Thanks =)

**Comment by ABHAYJAIN2601** [comment]
> > Please Review @dougfabris
> 
> @shrinish123 Unfortunately the problem here is deeper. We have two things to work on:
> 
>     1. If we're not part of a channel and we open a discussion, the breadcrumbs do not show the proper parent room.
> 
> 
> image
> 
>     1. The favorite button should display only if we already joined the conversation.
> 
> 
> If you could help us with that, let me know. Thanks =)

I think Discussion must private to channel members Like if they discussion important things so it needs to be within them right?

**Comment by shrinish123** [comment]
@ABHAYJAIN2601 no but we can only view a discussion without being a member only if it is started in a public channel , and private discussions shouldnt be created in public channels

**Comment by ABHAYJAIN2601** [comment]
@dougfabris This mean we need some way to connect discussion room to parent room by storing parent room id.
may be if we can add one field parent room-id and in normal case room -id and parent room-id will be equal in rest case we can store parent room id ? or i can try to find another way if this will not work

**Comment by shrinish123** [comment]
@dougfabris I have now added the commit so that the favorite button will only be displayed if we have joined the conversation. 
Please Review. This solves issue #21041. I will try to also fix your 1st point
A screenshot of how does it look like now : 

review2

**Comment by ABHAYJAIN2601** [comment]
@dougfabris what we need to do if user is not part of parent channel can we show message saying to join it first or show parent room even if user is not part?

**Comment by ABHAYJAIN2601** [comment]
Now user will see correct name of parent channel and favorite icon will be display after user join channel in both Public and Private channel .Do we need anything more to solve this issue otherwise i can  generate PR for this one.
https://user-images.githubusercontent.com/51324264/111476395-20123980-8754-11eb-8381-f8129fc13797.mp4

**Pull request closed without merging**
