### PR TITLE
Updated version of qnub:emojione

### PR DESCRIPTION
**Pull request by cygery**
New version supports more representations of emojis containing an apostrophe and tooltips for emoji images using the title attribute which contains the text representation of the emoji (either shortcode or ASCII string).

### CODE REVIEW

**Comment by mathdroid** [comment]
Well played :+1:

**Comment by cygery** [comment]
Thanks :)

**Comment by gmsecrieru** [comment]
:+1:  LGTM
emoji

Thanks!

**Comment by shtefcs** [comment]
Bravo :+1:

**Comment by shtefcs** [comment]
This is not working anymore on my chat. Aslo don't see it's working on rocket.chat demo.

Can anyone confirm this ?

**Comment by cygery** [comment]
Confirmed. Now the [official emojione package](https://atmospherejs.com/emojione/emojione) is used which apparently lacks my commits.

**Comment by shtefcs** [comment]
Ok, tnx.

What now :D ?

**Comment by cygery** [comment]
I'll try to merge them and send another PR to the new/official repo.

**Comment by cygery** [comment]
PR sent. Once it gets merged, tagged, and released we need to update the version of emojione here again.

**Comment by shtefcs** [comment]
oki, waiting for that.

**Pull request merged**
