### PR TITLE
slash command for open

### PR DESCRIPTION
**Pull request by Deepakkothandan**
@RocketChat/core 

Add Slash command open to go to an existing channel

### CODE REVIEW

**Comment by Deepakkothandan** [comment]
@RocketChat/core 
The PR is not working yet, when I try to execute the slash command, nothing happens and I dont get any error messages too.

I tried placing the FlowRouter.go inside the if(subscription != null ) block, but received Can't set timers inside simulations, on googling I understood the problem so implemented it, as in the current way.

Any suggestions on how to proceed further?

**Comment by Deepakkothandan** [comment]
@geekgonecrazy Could you please help me on this

**Comment by marceloschmidt** [comment]
@Deepakkothandan what are you trying to accomplish? Is this supposed to be the same as clicking on a room name? or are you trying to create a channel if it doesn't exist as well?

**Comment by Deepakkothandan** [comment]
@marceloschmidt Yes you are right. As an alternative, I tried placing the code `FlowRouter.go(RocketChat.roomTypes.getRouteLink(subscription.t, subscription));` in the final if block,  the url changes in client side, but I get an empty page and the error in console is Error: Can't set timers inside simulations

But, when I execute the same line independently in the console it works.

**Comment by marceloschmidt** [comment]
Thanks @Deepakkothandan for the PR! I'm looking into it now and will merge it as soon as I make the required changes ;)

**Comment by Deepakkothandan** [comment]
@marceloschmidt Thank you, also please notify me when you do the changes, so I can have a look into what did I miss :smile:

**Comment by marceloschmidt** [comment]
The problem was much deeper, @Deepakkothandan.
Up until now, we didn't have a slashcommand that would run solely on client side. All our slashcommands are server-side. I had to make a few changes to how slashcommands are run, checking if they are client-only. 
Commiting in a few minutes, then you can check the PR commits ;)

**Comment by marceloschmidt** [comment]
@Deepakkothandan check this commit https://github.com/RocketChat/Rocket.Chat/commit/299163ee95ee6604399df8810b91500d11947910 if you want to see what changes I've made.

**Comment by Deepakkothandan** [comment]
@marceloschmidt Thank you very much for making the necessary changes, I am going through it and beginning to understand it, Thanks again :smile:

**Pull request merged**
