### PR TITLE
Inline-video responsive patch

### PR DESCRIPTION
**Pull request by DevBrent**
On mobile, webm/mp4 videos expand beyond the frame.

This corrects inline-video to be responsive with a max width and height of 512x288 which is below the previous 300 height and 16:9.

In a separate patch I will address iframe embeds if they are found to be of trouble on mobile.

### CODE REVIEW

**Comment by DevBrent** [comment]
It's possible 480x270 could be a better maximum size because it is one quarter each dimension of a 1080p resolution.

533x300 would be the best if the height was set to 300 for a specific reason.

**Comment by engelgabriel** [comment]
@rodrigok should we change it to 480x270 ?

**Comment by rodrigok** [comment]
@DevBrent @engelgabriel sure we can, there is no reason for this 300px that I can remember.

**Comment by engelgabriel** [comment]
@DevBrent please update as you said?

**Comment by DevBrent** [comment]
Done

**Comment by engelgabriel** [comment]
LGTM

**Pull request merged**
