### PR TITLE
[FIX] Elements in User Info require some padding

### LINKED ISSUE #13638: [UI/UX] Elements in User Info require some padding
### Steps to reproduce:

1. Click on user icon
2. Username and Status need some padding at the top

### Expected behavior:

before_padding

### Actual behavior:

after_padding

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 1.0.0-develop
- Deployment Method: Local Server
- Number of Running Instances: 1
- DB Replicaset Oplog: Enables
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6

### Additional context

I will be working on this issue

### PR DESCRIPTION
**Pull request by mushroomgenie**
Closes #13638 

### Before

before_padding

### After

after_padding

### CODE REVIEW

**Comment by fliptrail** [comment]
@mushroomgenie I guess package-lock.json should remain unchanged. @knrt10  What's your call?

**Comment by knrt10** [comment]
yes @fliptrail you are right. @mushroomgenie when you run `npm i` stash those package-lock.json changes and then commit

**Comment by mushroomgenie** [comment]
@fliptrail and @knrt10 Sorry I must have missed that step while committing.I'll revert the commits and then push to the PR.

**Comment by ggazzo** [comment]
@mushroomgenie please fix the conflicts (:

**Comment by mushroomgenie** [comment]
@ggazzo Can you review the changes ?

**Pull request merged**
