### PR TITLE
[FIX] room data is not erased after deleting rooms by app

### PR DESCRIPTION
**Pull request by cuonghuunguyen**
## Proposed changes (including videos or screenshots)

Currently only the room is removed when we delete the room by Apps.
After this PR, we will remove all of the related data of the room when removing it by Apps Engine

### CODE REVIEW

**Review by debdutdeb — APPROVED** [review]
lgtm! thanks :)!

**Review by thassiov — DISMISSED** [review]
LGTM

**Review by AlenDavid — APPROVED** [review]
LGTM

**Comment by cuonghuunguyen** [comment]
Done

**Comment by ggazzo** [comment]
could you please synchronize with develop again? it should not fail more
btw there is any reason you blocked changes on your fork? if not I could update by myself

**Comment by cuonghuunguyen** [comment]
Could u do me a favor?

Vào 2:45 SA, Th 4, 8 thg 3, 2023 Guilherme Gazzo ***@***.***>
đã viết:

**Review by debdutdeb — APPROVED** [review]

**Pull request merged**
