### PR TITLE
adding extraData to loadHistory method

### PR DESCRIPTION
**Pull request by S3baso**
@RocketChat/core

### CODE REVIEW

**Comment by sampaiodiego** [comment]
hi @S3baso .. thanks for the contribution

can you please describe an user case for this? thanks

**Comment by S3baso** [comment]
hi @sampaiodiego i just want to add a external package to filtering chat messages by users

**Comment by sampaiodiego** [comment]
ok.. but it's not a good idea creating an `extraData` param into a method..

the way you implemented it, you can call something like this:
`Meteor.call('loadHistory', 'any', false, 20, false, { rid: { $ne: 'any' } })`

and get the last 20 message of all rooms.. because you're `_.extend()` the `extraData` over the original query.

also, the model functions have to be as dumb as possible..

**Comment by S3baso** [comment]
Oh, my fault... You're right, i will change this

**Pull request closed without merging**
