### PR TITLE
fix: Overriding Retention Policy not working

### LINKED ISSUE #19730: Retention Policy settings not working correctly in channels
### Description:

It seems like the retention policy configuration which you can overwrite in channels is a bit buggy. Sometimes the maximum message age doesn't work, then sometimes there is a maximum age of "30" even though nothing is configured.

I post example images to show what I mean.

**Our Retention Policy settings in Admin:**
image
image

### Steps to reproduce:

1.  Create new private room
2. Open Room-Info -> **1st error: wrong Information:**
image
I didn't set any retention policy settings yet so I don't expect a warning that something gets deleted here.

3. Click Edit -> Prune
4. Tick "Automatically prune old messages" and "Override global retention policy"
5. Set "Maximum message age in days (default: 30)" to 1
6. Click "Save"
7. Reload RocketChat and open Room Info again

### Expected behavior:

See retention policy info box with maximum age 1

### Actual behavior:

**2nd error:** Sometimes saw "30" again, sometimes saw "NaN".
If I repeat the steps above sometime it starts working again, cannot reproduce exactly though.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.0
- Deployment Method: docker

### LINKED ISSUE #20186: [Bug] Impossible to override globale retention policy in a room with a bigger value.
### Description:

It seems impossible to specify a bigger room retention policy in the web interface.
The new value is written in the mongo database, but in the preferences of the room the the policy is set to the globale value.

### Steps to reproduce:

1. You must set a global retention policies ex: 30 days.
2. Go on a channel and try to set a value bigger than the global one You can do the same with the APi or directly in BDD (it's the same result)
3. The value is correctly written in the database
4. You can check that the value is always the general value not yours.
5. If you set a value lower than the global value it works and the new value is yours.

### Expected behavior:

We expect that if a value is specified on a room, this value override the globale retention value and that in all cases.
We don't want the application takes only the smaller value.

### Actual behavior:

Screenshots can be done, but I think the description is enough to reproduce the bug.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1 to 3.10.3
- CENTOS (on docker): 
- Deployment Method: docker (swarm)
- Number of Running Instances: 12
- DB Replicaset Oplog: Enabled
- NodeJS Version:  12.18.4
- MongoDB Version: 4.2.11

### Client Setup Information

- Desktop App or Browser Version: insignificant
- Operating System: insignificant

### LINKED ISSUE #20348: [BUG] Max age for retention policy in room edit resets after realod
### Description:
In room edit settings, when we try to set max Age more than global default, it shows settings saved but after we reload instead of new value of days field, it shows default value.

### Steps to reproduce:

1. Go to any room
2. open edit room settings panel
3. change maximum age under override message retention policy settings.

### Expected behavior:
Correct value should be displayed always

### Actual behavior:
After reload default value is shown if new value is more than default value
maxAge-retention-before

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.11-develop
- Operating System: Ubuntu 20.10
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome version 87
- Operating System: Ubuntu 20.10

### Additional context
Working on it.

### LINKED ISSUE #30810: Room does not have retention policy [error-action-not-allowed]
### Description:
Today i've installed free Rocket.Chat with Snap. I want different retention policy's per channel.
All i got is the message "Room does not have retention policy [error-action-not-allowed]", can't find anything about that

### Steps to reproduce:

Install free R.C with snap on Ubuntu 22.04, set it up and configure.
Create channels and try to override global policy

### Expected behavior:

A link where i can set permission or that it just works

### Actual behavior:

I only get a message "Room does not have retention policy [error-action-not-allowed]" and nobody seems to know about

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.4 
- Operating System: Ubuntu 22.04.3 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: don't know
- NodeJS Version: 14.21.2 - x64
- MongoDB Version: 5.0.15 

### Client Setup Information

- Desktop App or Browser Version: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0 
- Operating System: Manjaro Linux 23.0.2

### Relevant logs:
I don't see relevant logs - on server side just mongodb  :-/
Bildschirmfoto_2023-10-31_00-51-04

Clientt side:

Request:
POST /api/v1/rooms.saveRoomSettings HTTP/1.1
Host: 10.0.0.79:3000
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0
Accept: application/json
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://10.0.0.79:3000/channel/just4fun/channel-settings
X-User-Id: AX9jWdJCQwEKsHrn2
X-Auth-Token: cJri8qbrvvs0_wkXEkTFsCrxp0mv_pIlNqtWOcoj--U
Content-Type: application/json
Content-Length: 86
Origin: http://10.0.0.79:3000
DNT: 1
Connection: keep-alive
Cookie: rc_uid=AX9jWdJCQwEKsHrn2; rc_token=cJri8qbrvvs0_wkXEkTFsCrxp0mv_pIlNqtWOcoj--U
Pragma: no-cache
Cache-Control: no-cache

Reply:

{"success":false,"error":"Room does not have retention policy [error-action-not-allowed]","errorType":"error-action-not-allowed","details":{"method":"saveRoomSettings","action":"Editing_room"}}

### LINKED ISSUE #31667: Channel Retention Override Shows NaN on first character set
### Description: 
When trying to set a channel retention override on channels, entering any digit (or clicking the spinner) causes the text to disappear and the description to be set to NaN.

### Steps to reproduce:
(Steps written with the assumption that a global retention policy is set).

1. Open Channel information by clicking the "I" button on the toolbar.
2. Select to edit the channel clicking on the "Edit" button.
3. Scroll down to the bottom of the tab that opens, and open the "Prune" section.
4. Select to automatically prune old messages.
5. Select to override the global retention policy.
6. Click on the spinner or try entering a digit.

### Expected behavior:

The selected number retention policy override can be entered and saved.

### Actual behavior:

The description of the selected maximum message age in days is changed to default: NaN and the text box goes empty. No digits or text can be then be entered.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.3
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.3
- MongoDB Version: 6.0.12 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Firefox 122.0
- Operating System: Ubuntu

### PR DESCRIPTION
**Pull request by dougfabris**
## Issue(s)

Closes #30810
Closes #31667
Closes #19730
Closes #20348
Closes #20186

## Further comments

[SUP-563](https://rocketchat.atlassian.net/browse/SUP-563)

[SUP-563]: https://rocketchat.atlassian.net/browse/SUP-563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ggazzo — APPROVED** [review]

**Comment by Gummikavalier** [comment]
@dougfabris I had a go with retention time fix with 6.9.0 rc1. When setting the test scenario up I noticed this issue:

Screenshot from 2024-05-31 11-31-31

This happens when changing the channel type from private to public with channel owner privileges.

The two days retention in the picture is a global default for all channels.

The user owning this channel does not have pruning rights aka Clean Channel History privilege (the default). I did not touch anything else on this newly created channel, only tried to switch it from private to public directly after the channel was created with the same account. I also cleaned cached while testing for this new issue.

**Comment by dougfabris** [comment]
@Gummikavalier Nice catch, an issue indeed!
It's related to the `edit-room-retention-policy` permission. Room owners don't have it by default so they can't change retention policy. We should hide the retention based on this permission on the UI, I will raise the proper fix.

Thank you so much for helping us 🚀

**Comment by dougfabris** [comment]
@Gummikavalier JFYI, the [fix](https://github.com/RocketChat/Rocket.Chat/pull/32531) for it will be on `6.9.0`.

**Comment by dougfabris** [comment]
@Gummikavalier Indeed, I tested only the input render and I missed checking the permission when initiating the form values, so when users without the `edit-room-retention-policy` permission tries to edit the room for the first time, they ended up on the error again. I will raise a fix and I'll try to add to a possible path release for `6.9.x`. 

Thanks again for the huge support on this!

**Comment by Gummikavalier** [comment]
Apart from that issue with permission during making changes as regular owner, the actual pruning tests seemed to work ok.

I had different channels with 3 and 1 days retention, 2 days as global policy for others, running for several days. Messages remained and disappeared accordingly.

One channel was set to never prune and the messages have stayed intact there as they should.

Looks good to me. :+1:

**Pull request merged**
