### PR TITLE
test: fix API test flakiness 

### PR DESCRIPTION
**Pull request by sampaiodiego**

### CODE REVIEW

**Review by KevLehman — APPROVED** [review]

**Comment by blacktoby** [comment]
@KevLehman @sampaiodiego 
When is this commit going into the next bugfix release? We are waiting for it, since it fixes the message export in rooms.

**Comment by sampaiodiego** [comment]
hey @blacktoby , is it really broken? I thought it was not affecting production environments

**Comment by blacktoby** [comment]
Yes it is. The error explained in this [PR 29903](https://github.com/RocketChat/Rocket.Chat/pull/29903) is still happening in 6.4.4.
You commented, that the problem is fixed with this PR. So I hoped it will soon go live.

**Comment by blacktoby** [comment]
@sampaiodiego thanks for putting the pr into the 6.4.5 release. This helped us tremendously! Now the message export for rooms works as expected.

**Comment by sampaiodiego** [comment]
that's good to hear @blacktoby .. thx for the heads up! otherwise the fix would have to wait for 6.5.0

**Pull request merged**
