### PR TITLE
[NEW] Adds ability for Rocket.Chat Apps to create discussions

### PR DESCRIPTION
**Pull request by marceloschmidt**
Depends on https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/229
Converts new apps-engine properties to rocket.chat models

### CODE REVIEW

**Comment by lolimay** [comment]
Hi @marceloschmidt ! Have you created an app to test if it works? Would you mind sharing the app here? Thanks!

**Comment by marceloschmidt** [comment]
The app is not ready yet, but you can easily test it with the following code:
```
const discussion = await modify.getCreator().startDiscussion()
  .setParentRoom(await read.getRoomReader().getById('your_room_id'))
  .setReply(`This is the first message sent in the discussion`)
  .setDisplayName(`Discussion name`)
  .setSlugifiedName(`a_random_id`)
  .setCreator(await read.getUserReader().getById('your_user_id'));
const rid = await modify.getCreator().finish(discussion);
console.log(rid);
```

**Comment by marceloschmidt** [comment]
And you can add a `.setParentMessage(await read.getMessageReader().getById('a_message_id') as IMessage)` to make it reply to a specific message.

**Comment by sampaiodiego** [comment]
just making sure nothing has changed in the past two weeks.. can we go ahead and merge this?

**Pull request merged**
