### PR TITLE
[FIX] Added afterUserCreated trigger after first CAS login

### PR DESCRIPTION
**Pull request by AmShaegar13**
@RocketChat/core 

The afterUserCreated callback is not called when creating a user on first CAS login. This causes inconsistent behaviour with the 'User created' integration when using CAS.

This PR adds the missing trigger after a user is created by CAS login.

### CODE REVIEW

**Comment by rodrigok** [comment]
@AmShaegar13 Awesome, thanks. Can you do some changes?

The best place to put that code is [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/lib/accounts.js#L125) inside the `Accounts.insertUserDoc`, you should check if the user has username and then call that callback, then we will solve that problem for every place we call the Accounts.insertUserDoc passing username and not call the callback.

The reason for the `if` is that callback is called only by the method `setUsername`, meaning you have finished your registration.

What do you think?

**Comment by AmShaegar13** [comment]
@rodrigok no problem. Although I did not do it in the first place to avoid the callback being triggered for every user joining a live chat. Wouldn't that be the case?

Is that, what you want?

**Comment by rodrigok** [comment]
@AmShaegar13 Good point, that is not desired at all, we are working to remove livechat from user's collection anyways.

You can check if the user has username and `type !== 'visitor'`, that solves the problem and keep the code in a central place. We could remove that on the next release when we finish the livechat users separation.

**Comment by rodrigok** [comment]
@AmShaegar13 Can we talk at https://open.rocket.chat/direct/rodrigo.nascimento ?

**Comment by AmShaegar13** [comment]
@rodrigok How about this?

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:53388)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1eNK72-002oy3-3W
	for greg@biomassiv.es; Fri, 08 Dec 2017 08:58:52 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=chm27a2ciaCNXx9dpz3fVcqguj4=; b=fA+hxmLMChh5YMnI
	WmMNKgNYo9B689Bn8552CaAsLRBGUPH2k4N8YJeJUqezqLZs0/toi+1xi0+X10Fm
	7BlYZWplZO5OX/7mAQWvBlYU8RtZRw9KBrL60nhpq7Zyz0lueoDsfRLztJDxodaK
	jtYmgKeXs+D5XRYo+8rjVqv0RZU=
Received: by filter0159p1iad2.sendgrid.net with SMTP id filter0159p1iad2-6538-5A2AA885-2C
        2017-12-08 14:58:13.624146975 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0008p1iad1.sendgrid.net (SG) with ESMTP id M9oNmopcSy2qIbi-8xRp6A
	for <greg@biomassiv.es>; Fri, 08 Dec 2017 14:58:13.508 +0000 (UTC)
Date: Fri, 08 Dec 2017 14:58:13 +0000 (UTC)

**Pull request merged**
