### PR TITLE
Regression: Fixed update room avatar issue.

### LINKED ISSUE #20432: [BUG] Room avatar cannot be updated.
### Description:
Trying to update room avatar gives TypeError.

### Steps to reproduce:

1. Select ant channel
2. Room Info
3. Edit

### Expected behavior:
Room avatar should be updated without any error

### Actual behavior:
On updating room avatar TypeError is displayed.

https://user-images.githubusercontent.com/55157259/105950991-61ac2f80-6095-11eb-9aaa-59475b6d8dee.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

### Additional context

Working!

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)

Users can now update their room avatar without any error.

https://user-images.githubusercontent.com/55157259/105951602-560d3880-6096-11eb-97a5-b5eb9a28b58d.mp4

## Issue(s)

Closes #20432

### CODE REVIEW

**Comment by Darshilp326** [comment]
@dougfabris  @lolimay Please review:)

**Comment by dougfabris** [comment]
@Darshilp326 I think we have a bug after change the room avatar, the room doesn't change the image properly in roomInfo, in the thumbnail of the room and in the sidebar. Would be amazing to fix that. Can you check for us?

**Comment by yash-rajpal** [comment]
@dougfabris I looked into it. If any room uses default room avatar, then there is no avatarEtag in its room object. This property makes up the avatar url so that it can be displayed.
When we edit the room avatar, avatar etag property is attached to room object. I think this prop is being attached after some time because in my testing after sometime this prop came in object automatically after 20 mins, or something is happening due to which this property is not added immediately. 
So everytime we need to show the room avatar, we can fetch room details using room id and then show avatar.
I have made a PR regarding this #20479. Please take a look at it.

**Comment by Darshilp326** [comment]
@dougfabris Sure, I will be working on that issue.

**Review by d-gubert — APPROVED** [review]

**Comment by aditya-mitra** [comment]
>  I looked into it. If any room uses default room avatar, then there is no avatarEtag in its room object. This property makes up the avatar url so that it can be displayed.
> When we edit the room avatar, avatar etag property is attached to room object. I think this prop is being attached after some time because in my testing after sometime this prop came in object automatically after 20 mins, or something is happening due to which this property is not added immediately.
> So everytime we need to show the room avatar, we can fetch room details using room id and then show avatar.
> I have made a PR regarding this #20479. Please take a look at it.

@yash-rajpal Are you still working on this issue? If you don't mind, I have a fix which might resolve the problem pointed out in the comment in #20479

**Comment by yash-rajpal** [comment]
@aditya-mitra I am still working on it.

**Pull request merged**
