### PR TITLE
[WIP] Send all messages directly through msgStream

### PR DESCRIPTION
**Pull request by sampaiodiego**
@RocketChat/core 

Today, sending a message has this flow:

1. [client] call `sendMessage` method
2. [server] runs method `sendMessage` - insert message on DB
3. [server] receive the message from DB on an `observe` issued on server startup
4. [server] send the message received thourgh `msgStream`
5. [client] receives the new message (with extra details)

This idea is sending the message to clients without waiting for DB (removing step 3).

I'm expecting a faster startup process, lower memory usage (both because I'll remove the forever-`observe` on startup), faster data sync on all connected clients.

### CODE REVIEW

**Comment by marceloschmidt** [comment]
Good idea!

**Comment by geekgonecrazy** [comment]
Can we ensure with this that a message is still going to be saved?  What if the server gets shut down before it saves, but its already been delivered to the client?

**Comment by sampaiodiego** [comment]
yes we can @geekgonecrazy .. and it is already done this way: 
the message is saved [here](https://github.com/RocketChat/Rocket.Chat/blob/b28f736fb90bb63396f20400ffae18be35ffb3fe/packages/rocketchat-lib/server/functions/sendMessage.coffee#L24) and sent to clients [here](https://github.com/RocketChat/Rocket.Chat/blob/b28f736fb90bb63396f20400ffae18be35ffb3fe/packages/rocketchat-lib/server/functions/sendMessage.coffee#L37).

but after I found [so many places to change](https://github.com/RocketChat/Rocket.Chat/pull/3341/commits/b28f736fb90bb63396f20400ffae18be35ffb3fe), I put this on background.. Need to think in a better and standard way to save and then send the message via stream..

**Comment by engelgabriel** [comment]
this is being implemented in another branch.

**Pull request closed without merging**
