### PR TITLE
[BREAK] Update the default port of the Prometheus exporter

### LINKED ISSUE #11329: We should reserve a port for the Prometheus exporter
**Is your feature request related to a problem? Please describe.**
We haven't reserved a port for the Prometheus exporter and currently use a default port that is reserved for the node_exporter. We should update https://github.com/prometheus/prometheus/wiki/Default-port-allocations and reserve the next available port for the Rocket.Chat Prometheus exporter.

**Describe the solution you'd like**
I will update https://github.com/prometheus/prometheus/wiki/Default-port-allocations and reserve the next available port, which is `9458`, for the Rocket.Chat Prometheus exporter. And then submit a pull request that sets the default port to this value. This will be a broken change but I believe if someone actually use Prometheus for monitoring, they have to set the port to some other value than `9100`. This setting is available in `0.66.0`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by thaiphv**
Closes #11329 
This is a breaking change as it changes the default port from `9100` to `9458`. I've already updated the [Default Prometheus Port Allocation](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) and reserved the port `9458` for the Rocket.Chat exporter.
This commit also returns a 200 response when someone hits the `/` endpoint. The response also includes a simple static HTML. This change is useful when we want to run a health check on the endpoint because all we need is a 200 response status.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@rodrigok this should be ok with prior versions right?  Because the setting value would stay the same?  If so this LGTM

**Comment by geekgonecrazy** [comment]
Thanks @thaiphv for adding this is good and much more permanent

image

**Comment by thaiphv** [comment]
Can we consider merging this before the wrong default port number becomes a permanent setting?

**Comment by geekgonecrazy** [comment]
For sure I should have assigned it to a milestone so we made sure to get it merged

**Pull request merged**
