### PR TITLE
[IMPROVE]  Thread join without send a message

### PR DESCRIPTION
**Pull request by bhardwajaditya**
#13644 

**Users can join a thread without sending a message.**

thread-join

### CODE REVIEW

**Comment by bhardwajaditya** [comment]
@knrt10 yeah it will work the same way you mentioned.
thread

**Comment by bhardwajaditya** [comment]
@ggazzo @sampaiodiego please review this.

**Comment by knrt10** [comment]
@bhardwajaditya I don't think you understand what I am saying. Input message box where we type our message is already there even before joining the thread. It should appear only when we join that thread. Please refer to the gif I uploaded above. Hope this helps 👍

**Comment by bhardwajaditya** [comment]
@knrt10 that's the feature of threads which separates it from regular channels. It's a conversation so as soon as user sends a message he is a part of conversation. I guess they asked to implement it in such a manner that one can be a part of the conversation without sending a message.

**Comment by ggazzo** [comment]
@bhardwajaditya could you use a link style instead of a button? thanks

**Comment by bhardwajaditya** [comment]
@ggazzo will this work?

join-message

**Comment by ggazzo** [comment]
I asked @thiagosanchz to check

**Comment by bhardwajaditya** [comment]
@ggazzo I will post a new one . This one had merge conflicts because of change in repository structure. Will tag him in the new one.

**Comment by thiagosanchz** [comment]
Hey @bhardwajaditya thanks for this solution. In the current threads, when I send a message in a thread I automatically join, so I change our text area to permit these two interactions:

**Join in a thread with button join**
Threads - Join

**Join in a thread with text message**


What do you thank? 
@engelgabriel take a look

**Comment by bhardwajaditya** [comment]
@thiagosanchz this looks much better than the one I used. I will close the pull request I just created.

**Comment by ggazzo** [comment]
@bhardwajaditya please apply that behavior to non joined channels and threads (not only for threads) :) thanks

**Comment by thiagosanchz** [comment]
@ggazzo Perfect!

**Pull request closed without merging**
