### PR TITLE
[FIX] Improve desktop notification formatting

### PR DESCRIPTION
**Pull request by Sameesunkaria**
Improved desktop notification notification formatting to match the push notifications.

Currently the desktop notification for a channel is as follows:

- Title: **@username @ #channel**
- Body: *message*

This PR changes it to 

- Title: **#channel**
- Body: username: *message*

**Current Notification**
Current desktop notification

**Proposed Changes**
Proposed

**Current push notification on iOS**
Push notification on iOS

This is a non breaking change. 

**This change also applies to in-app notifications on iOS, introduced in  RocketChat/Rocket.Chat.iOS#1504**

### CODE REVIEW

**Comment by cardoso** [comment]
@rafaelks @sampaiodiego what do you guys think?

**Comment by graywolf336** [comment]
Do you mind showing a screenshot of it working? :thinking:

**Comment by Sameesunkaria** [comment]
@graywolf336 Added some screenshots.

**Comment by kaiiiiiiiii** [comment]
The notification looks a lot cleaner with your changes. I like that 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sampaiodiego** [comment]
@cardoso check it out https://rocket-chat-pr-10445.herokuapp.com/

**Comment by Sameesunkaria** [comment]
@cardoso Try logging in with the App Store release version of the app. It should also work with the chime sound!

**Comment by sampaiodiego** [comment]
heroku messed it up 🤦‍♂️

**Pull request merged**
