### PR TITLE
Regression: Filter of canned responses in contextual-bar

### PR DESCRIPTION
**Pull request by tiagoevanp**

### CODE REVIEW

**Comment by tiagoevanp** [comment]
closes https://github.com/RocketChat/Rocket.Chat/pull/22761

**Review by MartinSchoeler — CHANGES_REQUESTED** [review]
Screen Shot 2021-07-26 at 3 05 40 PM
I'm getting this error on the admin table

**Comment by MartinSchoeler** [comment]
> Screen Shot 2021-07-26 at 3 05 40 PM
> I'm getting this error on the admin table

The same happens when I use the "all" option on the sidebar

Screen Shot 2021-07-26 at 3 09 16 PM

**Comment by KevLehman** [comment]
That could be my mistake, can you share the request made by the client, so i can take a look at it @MartinSchoeler ?

**Comment by MartinSchoeler** [comment]
> That could be my mistake, can you share the request made by the client, so i can take a look at it @MartinSchoeler ?

`offset=0&count=25 ` on the sidebar

`text=&sort={%22shortcut%22:1}&count=25` on the admin table

**Review by MartinSchoeler — APPROVED** [review]

**Pull request merged**
