### PR TITLE
[FIX] Creating roles with same name

### LINKED ISSUE #21272: WE can create many roles with the same name
### Description:

We can make create roles  in the admin panel with the same name .

### Steps to reproduce:

1. Go to the Admin Panel -> Permissions -> + button in the right corner
2. Try to create a new role with name which is already existing . And it creates a new role with the same name
3. 

### Expected behavior:

There should be only one role with one name

### Actual behavior:

Screenshot (13)

As we can see here we can create many roles with admin name

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13
- Operating System: Windows
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.x
- MongoDB Version:4.x

### Client Setup Information

- Desktop App or Browser Version:Beowser
- Operating System:Windows

### PR DESCRIPTION
**Pull request by shrinish123**
## Proposed changes (including videos or screenshots)

Now whenever the user tries to create roles with the same name it prompts the user about it and stops from making the new Role

## Issue(s)

Closes #21272

## Steps to test or reproduce

Go to admin panel-> permissions->add a button to create a role with the same existing name

## Further comments

This pull request was made to incorporate the changes requested in #21274

### CODE REVIEW

**Comment by shrinish123** [comment]
@KevLehman I have made the requested changes for #21274  in this pull request as the repo got deleted

**Comment by KevLehman** [comment]
Nice! I'm closing this one

**Comment by KevLehman** [comment]
Oh sorry, closed the wrong one 🙈

**Review by KevLehman — APPROVED** [review]

**Comment by shrinish123** [comment]
@sampaiodiego  Please Review 😄

**Comment by shrinish123** [comment]
@ggazzo Please check this one

**Pull request merged**
