### PR TITLE
Prevent password including whitespaces

### PR DESCRIPTION
**Pull request by Gyubin**
@RocketChat/core 

So far, users have been able to change passwords with whitespaces. I changed it. Only characters not whitespaces can be password.

### CODE REVIEW

**Comment by graywolf336** [comment]
So, are what spaces not allowed anywhere in the password or where are you restricting that?

**Comment by engelgabriel** [comment]
We cannot simply impose this rules to all Rocket.Chat users.

What we can do, is to create some settings that would generate some Regex to validate passwords.

**Comment by engelgabriel** [comment]
Thanks for your contribution @Gyubin, can we help you build the feature in a way that works for the whole community?

**Comment by Gyubin** [comment]
Sure. Let me know what feature i can contribute. Thanks 😄

**Comment by engelgabriel** [comment]
@sampaiodiego can you give some guidance here on how this password validation feature should be built?

**Comment by jwilkins** [comment]
If you are dictating the characters that can be used in a password, you are doing it wrong.  

http://security.stackexchange.com/questions/77359/does-it-indicate-a-bad-password-system-to-disallow-certain-characters-in-passwor

**Comment by engelgabriel** [comment]
@jwilkins I agree, but my idea is to actually allow admins to impose any rules they want, minimum number of special characters, etc. But I understand that people may use the feature to sync the password rules with other system that have characters limitations. So it would not be a Rocket.Chat limitation, but just way for admin to integrate with legacy system, but something that we would not encourage anyway.

**Pull request closed without merging**
