### PR TITLE
Add option to sort rooms by activity

### PR DESCRIPTION
**Pull request by billtt**
@RocketChat/core 

By default, rooms (including channels, private groups and direct messages) are sorted by name. But it will be useful to have them sorted by recent message activities.

This PR adds buttons above the room list to switch between the two sort types.

**Sort by Name**
image

**Sort by Activity**
image

### CODE REVIEW

**Comment by rodrigok** [comment]
I like the idea, but what about the perfomance impact?

In our demo server we have more than 100k users on room general, if we use your code we will update more de 100k records for each message sent on general, right?

**Comment by billtt** [comment]
@rodrigok Yes that's a problem for large deployments. I can think of another approach for this feature: to store the `la` field in room instead of subscription. But it will require more client time for room sort (as it will require querying both room and subscription collections). What do you think?

**Comment by rodrigok** [comment]
@billtt as far as I know we are getting all subscriptions and all rooms (which you are in) from server to client. So probably we can do that in the room's object.

**Comment by billtt** [comment]
@rodrigok Yes, and every message users send will trigger a room update already (because of the msg count field), so there should be no extra performance impact.

**Comment by rodrigok** [comment]
@billtt Yes, if you use the room object the performance will be the same.

**Comment by billtt** [comment]
Hi @rodrigok I've made the changes to use room.lm instead of adding a field in subscription. However, after I changed the client logic, I can't get the tests to pass. They always stuck at waiting for the .leave-room button to be visible.
I think the only thing I did that might caused this problem is using Array instead of Cursor object in the "rooms" helper. But I can't see why this should be a problem. I've run tests locally, but I can see the "leave room" button when it stuck. And the functions work properly when I visit my local build in browser.
Do you have any clue what might be the problem? Thanks!

**Comment by graywolf336** [comment]
@rodrigok any chance of you helping out with the requested items?

**Comment by graywolf336** [comment]
Closing as this will be resolved via: https://github.com/RocketChat/Rocket.Chat/issues/9541

**Pull request closed without merging**
