### PR TITLE
[NEW] Allow multiple subcommands in MIGRATION_VERSION env variable

### PR DESCRIPTION
**Pull request by arch119**
This is minor patch to allow multiple subcommands in the env var named "MIGRATION_VERSION" that is read by the DB Migration script. I have also replaced the occurrence of what I believe is now obsolete "MIGRATE" env var in some comments.
 
Background:
 Currently, MIGRATION_VERSION supports a single command like "rerun", "exit" . There are cases, when we want to rerun a specific DB migration script and exit right away. This requires a combination of both "rerun" and "exit" to be passed in. This could be better than creating another subcommand that does the combination of both. The change should also be backwards compatible.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@sampaiodiego this looks like a pretty useful addition to the code you added.  What do you think?

**Comment by sampaiodiego** [comment]
oh.. yes it is. awesome.

**Comment by sampaiodiego** [comment]
@arch119 since there is a commit from Shambhu Shrestha, he needs to sign the CLA. do you know him?

**Comment by sampaiodiego** [comment]
@arch119 do you know Shambhu Shrestha? we need him to sign the CLA.. otherwise you can do a commit with the changes yourself 😃

**Pull request merged**
