### PR TITLE
[FIX] Email verification

### LINKED ISSUE #8007: E-Mail verification settings do not work
### Description:

Rocket.Chat is able to sent an email to a new user in order to verify the email address. The admin can switch this option on and off via the setting "Accounts_EmailVerification".

### Expected behavior:

When setting "Accounts_EmailVerification" to false in the admin panel, no email verification is in place (meaning: sending no email to an user, asking for a click on the provided link). 

### Actual behavior:

If "Accounts_EmailVerification" is false, an verification email is sent anyway.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): AWS
* Number of Running Instances: 2
* Node Version: v4.5.0

### Steps to Reproduce:

0. Configure SMTP
1. Set  "Accounts_EmailVerification" = false 
2. Register a new user with a valid email adress
3. The user will receive a verification link

You can set in (1) the value "true", try it, and make another iteration with "Accounts_EmailVerification" = false. Every time, an email will be sent.

### PR DESCRIPTION
**Pull request by MartinSchoeler**
@RocketChat/core 

Closes #8007

### CODE REVIEW

**Comment by rodrigok** [comment]
@MartinSchoeler We use the email verified property to send emails when user is offline. If we stop sending the verification email the user never will be able to receive offline emails. The mais purpose of this setting is to disable the login when user has no verified email, that doesn't means we should stop trying to verify the email for other reasons.

We could improve the setting label and description to make it clear. What do you think?

**Comment by NANDAWEN** [comment]
my strongest side, unfortunately. That's fixed now.

**Comment by soundstorm** [comment]
@rodrigok something like "only allow verified users to login"?

**Comment by rodrigok** [comment]
@soundstorm Yes, looks good.

@MartinSchoeler Can you change the label?

**Comment by luixxiul** [comment]
Will this be included in `3.2.1` or `3.1.3`?

**Comment by soundstorm** [comment]
Just took 2.5 years to add my suggested changes 😂

**Comment by engelgabriel** [comment]
Thanks @soundstorm  :)

**Pull request closed without merging**
