### PR TITLE
RocketChat.TabBar

### PR DESCRIPTION
**Pull request by marceloschmidt**

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Looks good!  :+1:

**Comment by Sing-Li** [comment]
On android mobile, large screen phone (samsung note) ... tab bars are difficult to use.  It also forces the  room messages to become narrow - requiring more scrolling to see messages (smooth scrolling is hardware dependent).

The 'feel' of the app has completely changed. (In my opinion not positive).  And at least for now,  the mobile user gets no new feature with this, and just penalty.  

Can we detect mobile and bring back the old ui for mobile only?

**Comment by engelgabriel** [comment]
We will.. not exactly the old... but something more along those lines.

**Comment by Morgul** [comment]
What about doing something like this:

That tab bar is hidden behind a `...`:

screen shot 2015-09-12 at 12 46 55 pm

Once you hit that, the tabs expand across the top, sliding the channel name and burger out of the way:

screen shot 2015-09-12 at 12 55 31 pm

(Imagine a nice animation sliding everything out of the way.)

Then, the tab buttons work exactly like the current tab bar, except from the top.

**Comment by geekgonecrazy** [comment]
ah!  I think @lee.faus actually proposed something just like this.  

What about the cases where there are more then can across the top?

**Comment by Morgul** [comment]
@geekgonecrazy You can scroll the top bar left/right. I've seen several apps do that.

**Comment by engelgabriel** [comment]
@Morgul that's aligned with what I have imagined.

**Comment by geekgonecrazy** [comment]
Would it have tabs when wide and that when small?  Or is that too inconsistent?

**Comment by Morgul** [comment]
@geekgonecrazy That's what I'm imagining. Nice responsive UI. :)

**Comment by Sing-Li** [comment]
@Morgul  :+1:  swipe left and right to change tabs with underscore selected tab indicator ... certainly a trending Ui concept

**Comment by Morgul** [comment]
Yeah, that sounds great. Let's do that. ;)

**Pull request merged**
