### PR TITLE
[FIX] New screen sharing Chrome extension checking method

### PR DESCRIPTION
**Pull request by sampaiodiego**
Try to communicate with Chrome extension to see it is installed instead of checking for a cookie (the Chrome extension will not set a cookie anymore).

Chrome extension version 0.3+ accepts this method.

@RocketChat/core

### CODE REVIEW

**Comment by rodrigok** [comment]
Is this working on electron?

**Comment by engelgabriel** [comment]
@sampaiodiego did you test on Electron?

**Comment by geekgonecrazy** [comment]
@rodrigok unless i'm missing something I don't think screensharing has ever worked in electron.  The extension isnt baked in unless this is a recent change that I missed?

**Comment by sampaiodiego** [comment]
@rodrigok @engelgabriel [as you can see on the previous code](https://github.com/RocketChat/Rocket.Chat/pull/7044/files?diff=split#diff-5e169dd03e7f398b134954909d9e856dL429), it skips the extension checks if you're on electron..

**Comment by rodrigok** [comment]
True 😄

**Pull request merged**
