### PR TITLE
[IMPROVE] Add "Jump to message" button for quoted messages

### LINKED ISSUE #16298: [IMPROVE] Make the quote clickable and redirect to the message that was quoted
### Description:

Currently the quote isn't clickable but the date and time right next to it redirects to the message, It would be great if clicking anywhere on the quote redirects to the message

### Steps to reproduce:

1. Quote a message
2. Try to click on the markdown box that appears

### Expected behavior:

The quoted message should be clickable

### Actual behavior:

out

### PR DESCRIPTION
**Pull request by aKn1ghtOut**
## Checklist

- [x] I have read the Contributing Guide
- [x]  I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes

Added a "Jump to Message" button for quoted message attachments, as discussed in an issue mentioned below, by @engelgabriel .
Also, fixed the timestamp not being clickable to reach the message.

## Issue(s)

Closes #16298 

## Steps to test or reproduce

1. Quote a message
2. No way to be sent to the original message from the quotation.

## Further comments

Debating whether to keep the action as it is or to make it more like an actual button aesthetically.

### CODE REVIEW

**Review by ggazzo — CHANGES_REQUESTED** [review]
I'm afraid this code is outdated could you check if its possible to implement using react? thanks

**Comment by aKn1ghtOut** [comment]
On it!

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Closing this PR because it's stale now and it was already fixed in another one.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Comment by mrmmg** [comment]
@dougfabris 
Hi
You said, "Closing this PR because it's stale now and it was already fixed in another one."
Can you send the link to that PR?
In version 8.0.1, there is no option for this feature!

**Comment by dougfabris** [comment]
@mrmmg sorry, I forgot to mention #41091

**Pull request closed without merging**
