### PR TITLE
Remove Sandstorm support

### PR DESCRIPTION
**Pull request by sampaiodiego**

### CODE REVIEW

**Comment by fbender** [comment]
Why has this change been made? I was hoping for an updated version in the Sandstorm app market but instead support has been removed … how easy would it be to provide a recent version in the app market that predates this change?

**Comment by sampaiodiego** [comment]
creating a package for sandstorm was becoming even a more challenging task as we were adding more and more features. there was a lot of specific code for sandstorm that was becoming hard to maintain with no valuable return.

you can try following this doc to create your own sandstorm package: https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial-meteor/

**Comment by zeigerpuppy** [comment]
there has been quite a lot of new activity on Sandstorm lately.  This should lead to improvements in the underlying capabilities (links between grains and access to web services).  It's worth checking in every now, we'd love to have Rocket Chat back with an update (and then as I am sure I can speak for all Sandstorm users on that point).
It's true that there is quite a bit of extra work in packaging for Sandstorm, which is why that part needs to get better to get great apps like Rocket Chat back into the ecosystem.

**Comment by engelgabriel** [comment]
Yes, I totally agree with @geekgonecrazy

**Pull request merged**
