### PR TITLE
Changed edit to editedAt and editedBy

### PR DESCRIPTION
**Pull request by marceloschmidt**

### CODE REVIEW

**Comment by blaskovicz** [comment]
Thanks for this! I'll pull our sweet edited by code when I get back!

**Comment by marceloschmidt** [comment]
We had `edit: { at: ..., by: ... }` as an object. The reason why we made two properties `editedAt` and `editedBy` is to be easier in the future, if we want to port the code to another db, postgresql for example.

**Comment by blaskovicz** [comment]
Sounds good

**Comment by blaskovicz** [comment]
As a side note, I have a lot of postgres experience if you guys need help with that

**Comment by marceloschmidt** [comment]
That's awesome! We'll probably need that, but for now we need the Meteor guys to do their part too ;) https://github.com/meteor/postgres-packages

**Pull request merged**
