### PR TITLE
ensure that user is logged-in before listening for `onUser 'message'` notifications

### LINKED ISSUE #3011: rocketchat-ui: RoomManager fails to properly listen for `onUser` notifications
Your Rocket.Chat version: `develop` branch

Greetings. Thanks again for this awesome software!

We are running Rocket.Chat in production on Heroku. Most things work well, but we've run into an _intermittent_ bug where sometimes [these lines of code in `RoomManager.coffee`](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui/lib/RoomManager.coffee#L41-L46) aren't working.

For example, if I type `/invite NONEXISTENTUSERNAME`, the phony `rocketbot` user never replies. Sometimes a `Shift+Reload` helps. Other times it doesn't.

In addition, I inserted a `console.log` statement before line 42 (`msg.u =`) (in our deployed versino) and the messages don't appear in the browser. Furthermore, when I type the code below into the JavaScript developer console (in Chrome), I _do_ see the messages. This validates my assumption that the notifications are, in fact, being _sent_; they just aren't being _received_ by the `RoomManager`:

### The JS Console Code

```javascript
RocketChat.Notifications.onUser('message', function(msg) { console.log('got onUser notification:', msg) })
```

### The Result in the Console

```
got onUser notification: Object {_id: "baLMnqpfZW3yBJmw9", rid: "GENERAL", ts: Fri Apr 22 2016 16:29:01 GMT-0700 (PDT), msg: "No user exists by the name of `@jkdfaajdfls`.", u: Object…}
```

I tried moving those lines inside of the `Meteor.startup ->` callback, but it didn't help. I'm happy to submit a PR if someone has ideas on how to fix this.

Any ideas?

### PR DESCRIPTION
**Pull request by jeffreywescott**
@RocketChat/core 

Closes #3011

This addresses an issue where `RoomManager.coffee` was making an assumption that the user would be fully logged in before it asked for `onUser 'message'` notifications (which is not always true in the case of custom authentication solutions).

Please let me know if I've got something wrong here, or if there's a better solution. I'm happy to resubmit.

### CODE REVIEW

**Comment by sampaiodiego** [comment]
hi @jeffreywescott thanks for the PR :smiley: 

in the case you mentioned, what kind of trouble this "assumption" is causing?

also, since you included a computation depending on `Meteor.userId()`, if the users log off and log in, he will start receiving double notifications, because computation was invalidated.

**Comment by jeffreywescott** [comment]
Hi, @sampaiodiego ... thanks for the quick response!

As I mentioned in the bug, the assumption is problematic because, if the code runs _before_ the user is logged in, then the notifications never turn into messages for the user. For example, if a user types `/invite NONEXISTENTUSERNAME`, s/he won't see a response saying "no such user".

Should I update the PR to, in the case of no `Meteor.userId()`, call `RocketChat.Notifications.unUser` to remove the callback?

Or is there a better solution all together?

**Comment by sampaiodiego** [comment]
Ok, got it.

Calling `RocketChat.Notifications.unUser` looks a good idea.
If it doesn't work, we can think in how to re-evaluate the subscription after the user log in.

**Comment by jeffreywescott** [comment]
Okay, @sampaiodiego, hopefully this PR is acceptable now. It definitely works for our use case, and signing-out and back in doesn't seem to double-post notifications.

Let me know if there's any way I can make it better.

**Comment by engelgabriel** [comment]
@sampaiodiego and @rodrigok can you please review this?

**Comment by rodrigok** [comment]
LGTM

**Comment by sampaiodiego** [comment]
I was trying to test this, but after log off and log in I was unable to use the system.

the chrome tab got stuck and consuming 100% CPU

**Comment by jeffreywescott** [comment]
Ah, okay. That sounded like weird behavior for this relatively simple PR.

**Comment by jeffreywescott** [comment]
Hey, folks. Any progress on this? Is there a better way to solve my issue?

**Comment by sampaiodiego** [comment]
Hey, I'm sorry, I was too busy doing other stuff. I'll take a look on this tomorow ok?

In the meantime you can test the following, log in with user A, then log in with user B on an incógnito window, sendo a direct messages from user B to A. The user A should get a desktop notification.
Then log off the user A, and then log in with user A again.
Send another messages from usar B to user A.

In my previous test, the A get two desktop notifications after log off and log in.

**Comment by jeffreywescott** [comment]
Hi, @sampaiodiego. No need to apologize, or to promise a particular response timeframe; I really appreciate all of your help. :-)

I just ran the test that you asked, including my PR, and I only get a single notification for User A, both before and after the subsequent login.

Let me know if there's some other way I can help move this along. And thanks again!

**Comment by sampaiodiego** [comment]
hey @jeffreywescott 
after a good testing we realized the problem was with [meteor-streamer](https://github.com/RocketChat/meteor-streamer/).

it is registering a new callback each time we listen to an event.. this is not a problem to the event your PR are listen to (`RocketChat.Notifications.onUser 'message'`) because it does a `upsert` on messages, so even if it runs multiple times, it will update the message and not insert a new one.

**but** this is a problem on others streams we listen to (like [this one](https://github.com/RocketChat/Rocket.Chat/blob/develop/client/notifications/notification.coffee#L11)).

so ... can you please revert your code to like it was on [this commit](https://github.com/RocketChat/Rocket.Chat/pull/3017/commits/e9a9a4fc2891cb46bb40fb015d73a628a36d7a7b)? it was good enough (there is no need to unsubscribe :wink: )

I'll release a new version of [meteor-streamer](https://github.com/RocketChat/meteor-streamer/) with the fix, so everything will be fine =)

thank you again..

**Comment by jeffreywescott** [comment]
@sampaiodiego new PR in #3118.

**Pull request closed without merging**
