### PR TITLE
[NEW] Add support to external livechat queue service provider

### LINKED ISSUE #8940: Create an integration to get next livechat agent from external queue
### Description
Create an integration to get next livechat agent from external queue.

### PR DESCRIPTION
**Pull request by sampaiodiego**
@RocketChat/core 

Closes #8940

I'm also creating a new section `Routing` which groups all options related to queue:
image

Later on I'll add a new doc page describing payloads and all details about it.

### CODE REVIEW

**Comment by ingmartinfarias** [comment]
Hi, how to use external queue??

**Comment by reetp** [comment]
@ingmartinfarias please don't hijack issues.
Kindly use the forums https://forums.rocket.chat/ or chat https://open.rocket.chat #support to ask support questions.

**Comment by sampaiodiego** [comment]
well, we're indeed missing a documentation for this.. @renatobecker I've created this issue https://github.com/RocketChat/docs/issues/955, can you please add to your todo list? thx

**Comment by renatobecker** [comment]
@sampaiodiego, sure!
I'll do that.

**Pull request merged**
