### PR TITLE
[NEW] Multiple slackbridges

### LINKED ISSUE #9339: Multiple SlackBridge configurations
A feature request to support multiple SlackBridge configurations. I hoped it was possible to connect different Slack instances with my centralized Rocket.Chat. I have multiple Slack instances because of some customers with their own Slack instance and so a general overview in Rocket.Chat would be perfect.

### PR DESCRIPTION
**Pull request by Hudell**
Closes #9339

This PR adds support for multiple slack bridges on the same RC server.

### CODE REVIEW

**Comment by smellems** [comment]
Thanks @Hudell! This is related to #10915 as well.

Question: how will this work where channels in multiple Slackbridges have the same name?  ex.: #general 

Right now, channels names have to match in Rocket.Chat and Slack for the bridge to work.

**Comment by Hudell** [comment]
Channel names still need to match. If there are two slackbridges with a channel with the same name, both will work together in the same RC channel. However, Rocket.Chat will not send messages received from one Slackbridge to the others.

**Comment by creaux** [comment]
What left on this PR?

**Comment by Hudell** [comment]
The only thing missing is an area on the administration center to configure multiple slack servers.

**Comment by TimHarrison** [comment]
Any update on the build out of the admin setting page to complete this effort? It's been over a month since any visible progress was made on this feature. By the sounds of it, this feature is highly desirable by many people and organizations, including me. I'm sure the completion of this feature would make a lot of people happy!

**Comment by Hudell** [comment]
I changed the API Token setting to accept multiple lines, so you can add as many API tokens as you need and RC will connect to each of them individually. With this, there's no need to change any code to test the multiple slack bridges.

**Comment by Ismaw34** [comment]
Maybe this PR #11213 could be added to this?

**Pull request merged**
