### PR TITLE
[NEW] Add sweet alert to video call tab

### LINKED ISSUE #7860: Add "Start Videochat" button-click step before actually starting a videochat and inviting channel users to it
image

Right now the process to start a video chat within a channel is to open the Video Chat sidebar tab, and the chat automatically starts and invites room participants to join.

It would be great if when you open the tab, rather than immediately starting and inviting, instead there was a button that you had to click which would cause those things to happen.

### PR DESCRIPTION
**Pull request by MartinSchoeler**
@RocketChat/core 

Closes #7860 

Adds a Sweet alert prompt before starting a video conference using the flex-tab button, hopefully this will reduce the amount of times that people start a video call by mistake
screenshot from 2017-09-12 14-36-46

### CODE REVIEW

**Comment by mnlbox** [comment]
It's really needed @MartinSchoeler.
Thanks brow :wink:

**Comment by jszaszvari** [comment]
Good stuff @MartinSchoeler  
Love it!

**Comment by graywolf336** [comment]
@RocketChat/core Why can't this be added to this upcoming release?

**Comment by gdelavald** [comment]
@graywolf336 since this is a new feature, we avoid adding those to RCs so we don't create any more bugs

**Comment by graywolf336** [comment]
My opinion this is more a fix than a new addition, since it's too easy to randomly start new video calls and not mean it. But that's just my two cents..

**Pull request merged**
