### PR TITLE
[NEW] Room counter sidebar preference

### LINKED ISSUE #8836: 0.59++ Room counter UX not intuitive
### Description:

As of the new UI, counters for each room type are added to the navigation bar. 
Those counters show the total number of rooms per type subscribed to. 
* Version of Rocket.Chat Server: 0.59.3
counter intuitive

### Expected behavior:

User feedback was that this was not intuitive: The total number of rooms is not relevant to the user at all, but the unread count matters (at least more). It's counter-intuitive (scnr).

### Proposal: 
Provide an option to configure the counter. As per our feedback, this was not even necessary to be configured per user, but per server was fine.

### LINKED ISSUE #8859: Make room type counter optional and fix alignment
image

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #8859 
Closes #8836

Now the user have the option to show/hide the room counter on sidebar

image

image

image

### CODE REVIEW

**Comment by ggazzo** [comment]
congrats RTL is working to <3 image

**Comment by mrsimpson** [comment]
@karlprieb you named the setting hide “message counter”. If it was a message counter (# unread subscriptions) I believe this was fine for most people, but as far as I recall, it was a room.count() - and that was unexpected

**Comment by rodrigok** [comment]
@mrsimpson You are right

**Comment by karlprieb** [comment]
You're right @mrsimpson 
I made a PR #9013 to fix that.

Thank you!

**Pull request merged**
