### PR TITLE
[NEW] Custom user status

### LINKED ISSUE #2422: Additional user statuses
Possible solutions: 
- let user define the status with a brief text
- have admins define some additional global user statuses
- or (least preferred) add few more options to rocket.chat  
  (such as _"In a meeting", "Extended Busy", "Be Right Back", "Do Not Disturb", "With a client", "Working From Home"_ etc... )

### LINKED ISSUE #11403: Job title next to status
image

I would like to request extra field next to status with Job title which will be getting from LDAP attribute "tittle".

Something like this:

image

### PR DESCRIPTION
**Pull request by Hudell**
Closes #2422
Closes #11403

@RocketChat/core 

This PR adds a "Custom User Status" option to the admin page, where an admin can register any number of custom User Statuses, choosing a name and type (online, away, busy or offline).

The type will be the actual status of the user, but the custom status name will be displayed next to the user's name as well.

Users will also be able to write their own custom status text.

### CODE REVIEW

**Comment by erlend-sh** [comment]
Any news on this?

User status is incredibly important for out remotely distributed team.

**Comment by Hudell** [comment]
Screenshot

**Comment by Hudell** [comment]
The PR actually includes a page like that, but on the admin settings. That way admins can register new custom status for everybody to use.

I hadn't thought of doing the same on the user level, but it could be interesting.

**Comment by Hudell** [comment]
Closed in favor of #13933

**Pull request closed without merging**
