### PR TITLE
IRC prototype.

### PR DESCRIPTION
**Pull request by haosdent**
Just a prototype, still need a lot of things to do. Please don't accept it.

### CODE REVIEW

**Comment by haosdent** [comment]
... Let me open a issue to track it. I need do more improvements on my plugin.

**Comment by engelgabriel** [comment]
I've accepted it but disabled the package by default. So anyone can check it out if they want... they just need to uncomment the package.

**Comment by haosdent** [comment]
Thank you very much! @engelgabriel  I would upload more patches to it at this weekend.

**Comment by bott0r** [comment]
@haosdent ! I hope this wont go to waste! I'd certainly would install it!

**Comment by haosdent** [comment]
hi, @bott0r Thank you for your email. I feel very sorry to don't continue to improve this plugin recently. I am busy with other projects and my company issues in path months. I promise that I would restart this at next month (May).
Actually I would like to support more irc commands and make it more simple to setup. Thank you for your understanding. I feel very sorry about my current status and apologize for this again.

**Comment by bott0r** [comment]
Don't apologize! Life can be a busy place!  Looking for future updates, Good Luck!

**Comment by engelgabriel** [comment]
I'd love to see the package being developed further! Let us know if we can help.. Maybe making it installed by default will motivate other to join the effort?

**Comment by haosdent** [comment]
@engelgabriel  Thanks your comment. I think it could not be installed by default until I make it stable enough.

**Comment by bott0r** [comment]
Any news on this? Thanks in advance!

**Comment by haosdent** [comment]
Would restart at this Sunday. T_T Stuck by more things recently...

**Pull request merged**
