### PR TITLE
Saml

### PR DESCRIPTION
**Pull request by rodrigok**

### CODE REVIEW

**Comment by Sing-Li** [comment]
SAML is big!  Used by large enterprises all over the world.

This will be one well used piece of code for sure. Once again @rodrigok's amazing ninjaworks prevail.

**Comment by synotna** [comment]
Hey,

The current SAML implementation does not assign new users a RocketChat role, so users are left in a funny state - sidebar with only history, no access to channels etc

Is it enough to mention it here, or shall I create a new issue?

**Comment by rodrigok** [comment]
@synotna, please open a new issue, this isn't a issue, we can't reopen this PR.

Thanks.

**Comment by synotna** [comment]
Done https://github.com/RocketChat/Rocket.Chat/issues/1640 :)

**Pull request merged**
