### PR TITLE
[FIX] Threads and Discussions fixes

### LINKED ISSUE #14158: Bug: reacting a message inside a thread from thread panel looses the message
### Steps to reproduce:

1. Open any thread
2. React to a message
3. Message will be removed from the UI

### LINKED ISSUE #14344: Add ability to unsubscribe from threads
It doesn't seem to be clear how to remove ourselves from threads. If not possible, it should be. 

I propose we have a group in the sidebar for threads like we do discussions.

### PR DESCRIPTION
**Pull request by ggazzo**
readded threads follow and unfollow Closes #14344
Allow change discussions properties #14027
fix edited messages for nrr disabled
should close #14158

### CODE REVIEW

**Comment by rodrigok** [comment]
@ggazzo can you split this in multiple PRs?

**Comment by ggazzo** [comment]
do you really think we need create 4 prs for 10~20 lines, they are small fixes? I'm used to reviewing 40~80 files and usually its not a big deal...if you really think it worth, sure I can I'm perfectly able to do :x

**Comment by rodrigok** [comment]
@ggazzo it's not due to the code changes, but the description of the changes, you are adding 4 fixes in a single change line in change log that means almost nothing. Would be much better if we have each of them listed in change logs and well described don't you think?

**Comment by ggazzo** [comment]
I really dont think it worth in that specific case or I would create separated prs on the beginning. but as you wish:
https://github.com/RocketChat/Rocket.Chat/pull/14387
https://github.com/RocketChat/Rocket.Chat/pull/14389
https://github.com/RocketChat/Rocket.Chat/pull/14390
https://github.com/RocketChat/Rocket.Chat/pull/14391
https://github.com/RocketChat/Rocket.Chat/pull/14394
https://github.com/RocketChat/Rocket.Chat/pull/14393

**Pull request closed without merging**
