### PR TITLE
Improve: Switch storage in docker-compose

### PR DESCRIPTION
**Pull request by geekgonecrazy**
## Proposed changes (including videos or screenshots)

Removed the option to force --storageEngine=mmapv1  as we need to get people using wiredtiger

### CODE REVIEW

**Review by sampaiodiego — COMMENTED** [review]
idk how this file is being used and if changing this could cause trouble to people using it.

I was thinking change the purpose of this file so people can use it as a development environment. wdyt?

**Comment by fdellwing** [comment]
This will break setups that somehow autoupdate the docker-compose.yml. Updating to wiredTiger is easy but has to be done right and is different for single instances (more work) and clusters (pretty straighforward).

**Comment by KevLehman** [comment]
I agree that we may want to have a `docker-compose.development.yml` file instead of modifying the only one. That would be a more "backwards compatible" approach. 

Additionally, maybe we can mention in the docs that you can override the `command` directive by specifying a command to `docker-compose run` https://docs.docker.com/compose/reference/run/?

**Comment by geekgonecrazy** [comment]
Interesting.. do you think people really keep updating their docker-compose from here for production?  This seems kinda odd and against any best practice a sys admin should follow.  🙈

We do have an upgrade doc for people using docker-compose.  https://docs.rocket.chat/installation/docker-containers/mongodb-mmap-to-wiredtiger-migration

Making to a development oriented one makes sense to me.  Could be cleaned up to remove traefik and hubot.  Should we delete this and have people use another one?  Or keep this?  At some point we will be forced to change this.  How do we handle that?  Thoughts?

**Comment by KevLehman** [comment]
Not really sure haha. I think that it should be ok to modify the compose in exceptional cases 🙈 not sure if this is one of those.

About the transition, I think I'm not the best person to answer that haha. I'd say that maybe adding that change (in the compose) as a breaking change in one of the releases and put a comment somewhere there to advice devops to be careful when updating.  I don't know how impactful is the storage engine change (but this article says it's a bit complicated with 0 downtime https://www.percona.com/blog/2017/03/07/how-to-change-mongodb-storage-engines-without-downtime/)

**Comment by geekgonecrazy** [comment]
Exactly a change is not so cut and dry.  Basically existing node and existing files on disk can't work with wiredtiger. Has to go through replication to a new node which then stores it in the wiredtiger format.

**Comment by debdutdeb** [comment]
@fdellwing I do agree with @geekgonecrazy, automatically updating the compose files, extremely odd practice :/

That being said, can we do something like this -

- create a prod top level directory and put the new compose file there with comments mentioning the change from mmap to wiredtiger
- deprecate the existing top level compose file (rename to docker-compose-deprecated.yml basically)
- use a development specific compose file as @sampaiodiego suggested.

As for backwards compatibility, the new one could be designed in a way that a simple `docker-compose up` wouldn't do anything (essentially no entrypoint in the container image and also no `command` value). All such (weird) automation pipelines will be rendered useless since the existing containers are still going to be running, just as orphan ones (from dc's perspective), and no new containers will start up unexpectedly. Forcing the admins to take manual action.

For the dev environment - something like `docker-compose run rcbuild sh -c 'meteor npm i && meteor npm start'`. 

Any thoughts? I've already discussed with @sampaiodiego about the docker-dev-env-setup task, moving what I use personally to here. Also with @geekgonecrazy about simplifying the existing "production" compose file. This way maybe we can get around that automatic compose file update practice and kill two birds with one stone.

**Comment by debdutdeb** [comment]
**If** agreed, this will need some thorough documentation, I'm aware of that. But IMO, this is a very important change.

**Comment by debdutdeb** [comment]
Another approach, which I would prefer more, is to create a prod directory, have the new production compose file there, deprecating the existing one, and for development purpose, have a docker-compose-development.yml file. Basically a 404 for the top docker-compose.yml file. The result would be similar with a better visibility of pipeline failure for those who're handling these automatically (again, why? How? so many questions).

**Comment by geekgonecrazy** [comment]
@debdutdeb I'm going to close this as things are now all moved around and you have several PR's related to docker-compose

**Pull request closed without merging**
