### PR TITLE
fix emoji search icon and remove label

### LINKED ISSUE #5216: Search Emoji text missing on Lingohub
This text appears to be missing on Lingohub, can't translate it.

image

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #5216

Remove label and change icon to search icon.
image

### CODE REVIEW

**Comment by graywolf336** [comment]
I am curious, why was the label removed?

**Comment by karlprieb** [comment]
@graywolf336 I think the icon made the search field obvious.
@engelgabriel asked me to remove search label when possible.

**Comment by graywolf336** [comment]
@karlprieb Ah okay. Funny thing is Google just updated their Android Keyboard with a search for emoji and the search includes a label "Search emoji" 😆

**Comment by karlprieb** [comment]
@graywolf336 I saw that! :D Maybe we can change that, but idk... I think we can remove labels when the icon has good indications.

**Comment by graywolf336** [comment]
@karlprieb Yeah I'm not sure either, I was just curious 🤔

**Pull request merged**
