### PR TITLE
[WIP][NEW] Preview message before sending

### PR DESCRIPTION
**Pull request by fliptrail**
Steps to #13875 

**This is work in progress**

This is a feature to preview a message before it is actually sent.

### Current Progress
imported

### CODE REVIEW

**Comment by fliptrail** [comment]
Current Progress:
Peek 2019-03-24 04-04
The message is exactly copied.
Next steps: render it without triggering any events.

**Comment by fliptrail** [comment]
Current progress:

Peek 2019-03-25 00-26

**Comment by fliptrail** [comment]
@engelgabriel What do you think of this feature?

**Comment by geekgonecrazy** [comment]
Neat idea.. but this is going to clash with the pop up for suggestions. So I don’t think it could pop up.  Need some sort of UI/UX change

**Comment by fliptrail** [comment]
@geekgonecrazy Thank you! It is actually not clashing with suggestions. The suggestions are coming up above it neatly. Moreover, it would only be visible on clicking a button

**Comment by geekgonecrazy** [comment]
Cool.  But this still is kind of ugly to have both popping up. 

Like I said super neat thing.  But, I think it would have to be a slightly more cleverly implemented.  A way that would look better and fit more in the flow

@rocketchat/core

**Comment by MIKI785** [comment]
Could this be optional? I mean you don't really need to see a preview of majority of messages sent.

**Comment by thiagosanchz** [comment]
@fliptrail I can see a big problem with this idea, what's happening if write a big text? And the application always will show the user text repeated during the typing. I see these two problems being bigger than solving the issue you brought.
Thanks ;)

**Comment by fliptrail** [comment]
@thiagosanchz there would be a button to check the preview, this would be really helpful in katex

**Comment by tassoevan** [comment]
Some toggle button + a keyboard shortcut to alternate between the input field and the preview pane may be neat.

**Comment by fliptrail** [comment]
Carried forward by @ashwaniYDV in #16268

**Pull request closed without merging**
