### PR TITLE
Update emojione sprite and emoji picker

### LINKED ISSUE #3735: Emoji One upgrade to v2.2.5
Emoji One has received an update.
https://github.com/Ranks/emojione/releases

Features new 'Unicode 9' set which might be useful to colorify what one has to say.

Please add support for the new ones.

Your Rocket.Chat version: 0.35.0

### PR DESCRIPTION
**Pull request by sampaiodiego**
@RocketChat/core 

Closes #3735

I have also created a README file with instructions for a further update.

image

### CODE REVIEW

**Comment by marceloschmidt** [comment]
LGTM !

**Comment by xasx** [comment]
@marceloschmidt the lgtm thingy is still waiting. Does it work properly?

**Comment by marceloschmidt** [comment]
@xasx usually it requires two lgtm, but since you also typed it in your message and the check hasn't gone away, I'd say it isn't anymore. I'm not sure if it has something to do with the latest github update, which I thought was UI only.

**Comment by xasx** [comment]
@marceloschmidt Thanks for the info. Probably the keyword is required to be on the beginning of a comment? Anyway, @engelgabriel took the helm :smile:

**Pull request merged**
