### PR TITLE
Add type message to quoted messages

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Adds `type: 'message'` for quoted messages

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
I think adding to old messages would be extremely costly.  We would have to select all messages with attachments and then check each one to see if it was a permalink and if the permalink was valid and then finally update it. 

I think adding as a property for only going forward is probably ok.  Primarily added to aid @RocketChat/android  team:

**Comment by engelgabriel** [comment]
If anyone can think about a migration that could be fast... @sampaiodiego can you think about a query to do it faster using regex?

**Comment by sampaiodiego** [comment]
using server's URL as part of the regex _could_ be faster than doing all checks @geekgonecrazy mentioned.

but running a regex query on a server with millions of messages is always terrifying 😱

**Comment by geekgonecrazy** [comment]
Per discussion internally this isn't desired.

**Pull request closed without merging**
