### PR TITLE
[FIX] Add ability to click link and icon to trigger download in electron app

### PR DESCRIPTION
**Pull request by ph1p**
You cannot click the link in the electron app to download a file.
This PR will fix it.

bug

### CODE REVIEW

**Comment by adipose** [comment]
Correct me if I'm wrong, but doesn't this simply end up duplicating the behavior of the "download" icon rather than adding the additional feature of opening the file?  In some browsers (Fx), clicking on the link currently will prompt you for what to do (open/save).  By adding the HTML5 "download" attribute, it will now always save.  This seems like a regression.

On the client, the link will now at least do something, but it's not any new functionality.  It simply does what the icon does.

**Comment by ph1p** [comment]
This is correct. It's not a new feature. I've opened this request, because we use rocket.chat at our company and many people report, that they can't download files. Their not clicking on the download icon. I've copied the code, because this was the easiest solution for me with no sideeffects. If there is no special dependence on other functionallities, we can add `download=""`and the download problem is solved.

**Comment by adipose** [comment]
@ph1p OK, we are in the same boat.  I added the "download" attribute so the link does something.  However, the behavior in the Fx browser continues to be superior.  In Chrome, you can specify that certain file types are to be opened after download, but this interface is not available from Electron.  I suspect that this issue properly belongs on the Rocketchat.Electron side.

**Comment by tassoevan** [comment]
I'm closing this PR due to the considerations made by @adipose.

Although it helps desktop client users to have a better experience, this change also degrades a little how web client users interact with attachments. Ideally, both desktop and web clients should download the file to a temporary folder and open it in a desktop application.

Recent changes in Rocket.Chat desktop client use the same approach as a workaround, without interfering in the web client. This feature will be ship in the release `2.13.0` of desktop application and revisited after the `2.15.0` one.

**Pull request closed without merging**
