### PR TITLE
Many fixes for RTL

### PR DESCRIPTION
**Pull request by fduraibi**
- A lot of fixes for RTL 
- Reformatting and alignment of the whole file.

* The RTL interface seems perfect now and every thing I tested works.

### CODE REVIEW

**Comment by engelgabriel** [comment]
@fduraibi Thanks a lot for the help!!! I really appreciate it!

Can you preserve the original text formatting? Otherwise we can't see what has been changed. :(

**Comment by fduraibi** [comment]
@engelgabriel the original text was not formatted properly, so I fixed the indentations to match the `base.less` file by using only tabs and no spaces.

**Comment by engelgabriel** [comment]
Ok.. let me fix the indentation first.. and commit your changes after.. so we can see.

**Comment by engelgabriel** [comment]
@fduraibi can you pull again and merge the files?

**Comment by fduraibi** [comment]
ok

**Comment by fduraibi** [comment]
@engelgabriel I created a new request https://github.com/RocketChat/Rocket.Chat/pull/1560

**Pull request closed without merging**
