### PR TITLE
Remove emoji dependence on cdn

### PR DESCRIPTION
**Pull request by steedos**
save local copy of pngs to /public/images/emojione/png/
and set the emojione param:
emojione.imagePathPNG = '/images/emojione/png/'

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
This closes #1046 also.

@RocketChat/owners should we have the option to enable CDN to enable / disable things like this? For performance as mentioned in #1046

**Comment by steedos** [comment]
I think in mobile app, the local copy is more important.

**Comment by engelgabriel** [comment]
I am in talks with the guys form Emoji to create a official meteor package, so this would be solved by that.

Lets leave this open until I get that sorted.

**Comment by engelgabriel** [comment]
All looks good!!! :) We are using the official package now.

Maybe have a flag to use the Sprites inside the package?
https://github.com/Ranks/emojione/tree/master/assets/sprites

So it would be automatically update as a package asset, and not need to care about feature releases.

**Comment by engelgabriel** [comment]
I'll close this as we will use sprites as per https://github.com/RocketChat/Rocket.Chat/issues/1046

**Comment by Schniz** [comment]
Is there a way to use local files in an internal, isolated network? environment variables or something?

**Comment by sampaiodiego** [comment]
@Schniz we'll use internal sprites for emojis soon

**Comment by Schniz** [comment]
:shipit: :dancer: 

It will be awesome! thank you guys :smile:

**Pull request closed without merging**
