### PR TITLE
fix: Invalid username occupying email address during registration

### LINKED ISSUE #30601: When creating a new account, an invalid username occupy an email address
### Description:

When creating a new account, if the user types in an invalid username(in my case I have a space in between), the email(which is prompted before username) will be reserved hence it can not be used even after the user modifies the username.

I confirmed this bug by using this unit test in testing mode(follow the steps in https://developer.rocket.chat/contribute-to-rocket.chat/modes-of-contribution/assist-with-testing-rocket.chat)
```
it('should send email to user (return success), when is a valid email', (done) => {
			request
				.post(api('users.sendConfirmationEmail'))
				.set(credentials)
				.send({
					email: adminEmail,
				})
				.expect('Content-Type', 'application/json')
				.expect(200)
				.expect((res) => {
					expect(res.body).to.have.property('success', true);
				})
				.end(done);
		});
```

I first replaced the `adminEmail` with an email that is not valid(not existed) and this test failed. Then I tried to create an account using an invalid username(with space in between) with the same email. I clicked the "Join your team" button once and there was no response. I clicked the button once again and it prompted that the email is already existed. I ran the unit test above again and it passed which means the email is written to the database. 

In the actual server, the same behavior holds.

Testing Server:
https://github.com/RocketChat/Rocket.Chat/assets/62249815/75b0d5b4-7864-4910-a975-8647dd1f3056

Actual Server:

https://github.com/RocketChat/Rocket.Chat/assets/62249815/90a3cd35-b873-4219-8214-3bc3510054b8

### Steps to reproduce:

1.  Follow my procedures above.
2. 
3. 

### Expected behavior:

 

Should not reserve the email and prompt the username is invalid.

### Actual behavior:

The email is reserved and not telling the username is invalid.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.0-develop
- Operating System: macOS 13.4.1 (22F82)
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.4 - x64 
- MongoDB Version: 6.0.3

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### PR DESCRIPTION
**Pull request by Rahulr2101**
## Proposed changes (including videos or screenshots)

[Screencast from 30-10-23 02:38:31 PM IST.webm](https://github.com/RocketChat/Rocket.Chat/assets/117565630/61d8bfde-50d3-4c67-aa25-b3ae390f7b4b)

 This pull request aim to fix issue (#30601) by preventing users from adding an invalid username, specifically usernames with spaces in between. 

## Issue(s)

Closes #30601

## Steps to test or reproduce

    1. Visit the Registration/Create an account page.
    2. Enter an email address in the designated field.
    3. Enter a username that contains spaces.
    4. Attempt to proceed with the registration process.
    5. Now register with username without spaces.
    6. An error will be displayed: "Email already exists."

### CODE REVIEW

**Review by dougfabris — CHANGES_REQUESTED** [review]
Hi there, thanks for the contribution! 🚀 💯 

Let's try to use a better validation as we have on `apps/meteor/client/views/account/profile/AccountProfileForm.tsx` ?

**Comment by Rahulr2101** [comment]
@dougfabris Sorry for the late response, as I was busy with my college exams. I have made the required changes to the PR.

**Comment by dougfabris** [comment]
@Rahulr2101 I think we could include the same validation, even the `checkUsernameAvailability`

**Comment by Rahulr2101** [comment]
When I use `useEndpoint('GET', '/v1/users.checkUsernameAvailability');` to check if the username exists or not, it shows an error indicating that I should be logged in to use this endpoint.
image

**Comment by debosmita-S** [comment]
Hi @dougfabris 👋  
I’d like to work on this issue and re-implement the fix based on your previous review comments  
(reusing existing username validation logic and avoiding authenticated endpoints during registration).  
Please let me know if that sounds good. Thanks!

**Pull request closed without merging**
