### PR TITLE
[FIX] User Mention Problems (#16622)

### LINKED ISSUE #16622: User mentions after a right angle-bracket don't work
### Description:

If you try to mention a user, and there is a `>` character directly before or with a space in between, the mention does not work. If two spaces are placed between the `>` and the `@`, the mention works correctly.

### Steps to reproduce: 

(replace person with the name of an actual person in the channel)
1. Enter the message  `<test> @person `
2. Now, enter the message  `<test>  @person ` (extra space between > and @)

### Expected behavior:

Mentions for both 1 and 2 work correctly, the user is notified and the mention is highlighted.

### Actual behavior:

The mention for 2 works as expected, but for message 1 the mention is not highlighted and the user is not notified

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.1

### Additional context

From a brief look at the code in `/app/mentions/lib/MentionsParser.js`, it looks like the regex is working correctly, but the match is including the angle bracket (and optional space) when searching for the user.
(e.g. instead of searching for a user named `reffu42` it searches for one named `> @reffu42`). 
I'm not sure how to fix the regex, but potentially replacing a leading `> ` on the matched mention could fix it.

### PR DESCRIPTION
**Pull request by Pranav2612000**
Closes #16622 

Changed the regular expression so that it can now identify mentions like these: 
<test> @user_name(with a single space between the words) and 
<test>     @user_name(with multiple spaces) as well.

### CODE REVIEW

**Comment by ashwaniYDV** [comment]
@Pranav2612000 you have pushed package.json and packagelock.json too

**Comment by Pranav2612000** [comment]
I needed those dependencies to get RocketChat to run. I forgot about these later.

**Comment by gabriellsh** [comment]
Please, undo unnecessary changes (packe-lock, additional dependencies, etc). Thanks!

**Comment by Pranav2612000** [comment]
> Please, undo unnecessary changes (packe-lock, additional dependencies, etc). Thanks!

On it.

**Pull request closed without merging**
