### PR TITLE
Share Functions under single button in MessageBox

### PR DESCRIPTION
**Pull request by tgxn**
@RocketChat/core 
@rodrigok 

Closes: 
#4038 - Incorrect conditional when rendering the send button.

Took some time to think about how this would best work, and I think this comes close to a implementation that I'm happy with.

Based on PR #4006, I moved the buttons around and added an expanding section for the "Share" buttons.

Still requires browser testing, as I only tested in Chrome and Mobile Chrome/Rocket.Chat App (Android).

LTR
= Hidden
image
= Expanded
image

RTL
= Hidden
image
= Expanded
image

### CODE REVIEW

**Comment by dytec** [comment]
Tested on Chrome and Safari
Chrome: working
Safari: only the attachment button shows up

image

**Comment by tgxn** [comment]
@dytec Thanks for giving it a go - I'm not able to try it out for myself as it seems that Apple decided to stop producing Safari for Windows. :/

My housemate has a Macbook, so I'll be able to trial it once I get home today.
If you have any suggestions or a fix @dytec please let me know or possibly submit a pull against my branch?

**Comment by dytec** [comment]
@tgxn I´ve digged a little bit and it seems that this behavior is not related to your PR.

The following screenshots are from a fresh pull of the develop branch without your PR:

Chrome:
image

Safari:
image

I´ve to dig deeper...

**Comment by dytec** [comment]
BTW it seems that in Safari the Geolocation API is available ONLY when connected to WIFI...

**Comment by tgxn** [comment]
Hmm, I think it might be due to the css allowing too much space for the buttons (when they are hidden, which happens when certain API's aren't available).

**Comment by dytec** [comment]
I´m not sure if it´s a CSS issue because the missing buttons are not available in the DOM:

image

**Comment by engelgabriel** [comment]
@dytec we had a bug with Safari, did you test the latest version from `develop`?

Thanks for the PR @tgxn, and we agree the we should have the *option* to  group all _attachments_ into a single button, but we still need to keep the emoji on the oposite side, so we don't lose the alignment with the text on top.

image

**Comment by dytec** [comment]
@engelgabriel Yeah fresh download from develop a few minutes ago...

**Comment by engelgabriel** [comment]
This is how Slack looks like today

image

**Comment by tgxn** [comment]
@engelgabriel 
I moved the emoij picker back to the left hand side. I agree it looks better this way with the text aligned.
image

**Comment by tgxn** [comment]
Updated screenshots:

New Settings Section
image

Grouped-Open
image

Grouped-Closed
image

Ungrouped
image

Now I also tested out some different combination of enabled/disabled options, here's some examples.
image
image

**Comment by geekgonecrazy** [comment]
@tgxn you rock!  Thanks for the contribution! The more attachment types we add the worse this has gotten.  This is a fantastic addition! 👍 

Will take a look at mentioned issue.

**Pull request closed without merging**
