### PR TITLE
[FIX] Render reply preview with message as a common message

### PR DESCRIPTION
**Pull request by tassoevan**
### Before

before

### After
after

### CODE REVIEW

**Comment by Vacak7** [comment]
Dear All, 
Can we render the new replies under the original messages? Is there a way to modify the DOM to render it there?

**Comment by tassoevan** [comment]
@Vacak7 I guess you're talking about [threads](https://github.com/RocketChat/Rocket.Chat/issues/1112).

**Comment by Vacak7** [comment]
@tassoevan I was talking about that: https://forums.rocket.chat/t/change-reply-place-in-conversation/1193

**Comment by Vacak7** [comment]
@engelgabriel  @tassoevan 
Can you tell me; why the message reply was designed like this? 

image

Why is that the reverse? Is there any way to change it?

**Pull request merged**
