### PR TITLE
Setup for application tests and package testing

### LINKED ISSUE #1044: Suggestion for package testing approach
Now that we are starting to add tests, we need to make sure that we can:

1. Test packages as standalone, single units.
2. Test the application as a whole.

Package-specific tests should be placed within `packages/package-name/tests` and should follow [velocity+jasmine conventions](https://velocity.readme.io/v1.0/docs/jasmine-testing-modes).

_Example of package testing_ (Velocity's Continuous Integration mode)
`VELOCITY_TEST_PACKAGES=1 meteor test-packages rocketchat:lib --driver-package velocity:console-reporter --velocity`
screen shot 2015-10-08 at 12 34 41

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27263854-suggestion-for-package-testing-approach?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gmsecrieru**
Should close #1044

### CODE REVIEW

**Comment by gmsecrieru** [comment]
@Sing-Li @geekgonecrazy Let me know what you folks think of this approach. I have worked a bit on migrating current RocketChat.Markdown tests to this format but had a few issues with Underscore/_.trim.

I've seen so far that we need to explicitly declare each package dependency, but that didn't solve the problem at this point:
screen shot 2015-10-08 at 12 42 14



If you would like to jump in it would be great!

**Comment by geekgonecrazy** [comment]
oh got it working!  You sir rock!

Is the jasmine piece of the folder structure needed?  If maybe we could take it out?  If we can make this as simple as possible.

**Comment by gmsecrieru** [comment]
I don't think it is _needed_, but should we add another testing framework to our stack it would be good to have those test cases organized IMHO.

**Comment by gmsecrieru** [comment]
I have current package-specific tests set up, but still could not run application tests.

*rocketchat:lib and rocketchat:markdown*
screen shot 2015-10-08 at 16 57 50

**Comment by gmsecrieru** [comment]
Application tests execution up and running!

Chrome:
`VELOCITY_DEBUG=1 JASMINE_DEBUG=1 velocity test-app --ci`
screen shot 2015-10-09 at 14 13 14

PhantomJS
`PHANTOMJS_BIN=**/usr/local/bin/phantomjs** JASMINE_BROWSER=PhantomJS velocity test-app --ci`
screen shot 2015-10-09 at 14 21 17

**Comment by gmsecrieru** [comment]
@RocketChat/owners 

Added Travis CI scripts and removing testing dependencies. This should be ready to merge and will help us setting up #1074

**Comment by gmsecrieru** [comment]
For some reason we are experiencing a timeout during `travis-ci/pr` build:
screen shot 2015-10-14 at 16 08 35

**Comment by engelgabriel** [comment]
@samhatoum can you give us a hint on what are we doing wrong here?

**Comment by Sing-Li** [comment]
Please do not modify travis.yml at this point.  There are many moving parts that can break with the CI/CD merge down.   Please hold the travis mod for a follow-up PR.  Thanks.

**Comment by gmsecrieru** [comment]
I will try to get this karma-related issue addressed in the meantime!

**Comment by samhatoum** [comment]
@engelgabriel is there still an issue to look at? I just got back fro London

**Comment by gmsecrieru** [comment]
Hi @samhatoum , I had put this off for a while but if you are willing to help us out I can get back. We have package-level tests running, and our mainly issue is to run the application tests with Travis. 

I have tried a few different things but the end result is mostly the same:
- https://travis-ci.org/RocketChat/Rocket.Chat/builds/85384331
- https://travis-ci.org/RocketChat/Rocket.Chat/builds/85390388
- https://travis-ci.org/RocketChat/Rocket.Chat/builds/85395784
- https://travis-ci.org/RocketChat/Rocket.Chat/builds/85398113

```
W20151014-19:48:30.280(0)? (STDERR) [sanjo:karma]: start request failed { [Error: connect ECONNREFUSED]
W20151014-19:48:30.280(0)? (STDERR)   code: 'ECONNREFUSED',
W20151014-19:48:30.281(0)? (STDERR)   errno: 'ECONNREFUSED',
W20151014-19:48:30.283(0)? (STDERR)   syscall: 'connect' }
```

Any help appreciated. Thanks for your time!

**Comment by samhatoum** [comment]
I think you guys are missing the latest chrome, so Karma can't start. Try this adding this to your travis yml:

```
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
```

**Comment by Sing-Li** [comment]
@samhatoum  Thank you!  The tests-after-build proceeded much more smoothly.   

One question - the set-up time per packaged test is extremely long right now (for unit test where we might have thousands to run per build ... and if we have 10s of packages) - total build time can become quite a problem ... any ideas on how best to deal with this/structure our tests? 

@gmsecrieru  - please examine the logs - as there are multiple errors (one being web socket ECONNERR) in the logs but the final return code is 0

**Comment by samhatoum** [comment]
@Sing-Li no problem

regarding packages, there's a couple of things you can do. 

1) cache the files downloaded by the package so that startup time becomes less
2) run the package tests in parallel on different travis nodes
3) combination of both!

**Comment by samhatoum** [comment]
you should consider using the `velocity-cli` npm package. See here: https://velocity.readme.io/docs/continuous-integration-ci

**Comment by Sing-Li** [comment]
@samhatoum Thanks again for the great suggestions!
@gmsecrieru @geekgonecrazy Are we ready to move on with this?

**Comment by leefaus** [comment]
thanks @samhatoum.  so many things we can learn from him!

**Comment by samhatoum** [comment]
@leefaus no worries, happy to help

**Comment by Sing-Li** [comment]
@samhatoum   -   to avoid doing an extra build (takes up to 8 minutes - and we needed to do it twice already) just for testing, we included the following packages into our demo-server production build:

 `meteor add sanjo:jasmine velocity:console-reporter`

Are they placebo when not activated?   Will there be any side-effects?   TIA

**Comment by samhatoum** [comment]
you should add 
```
export VELOCITY=0
```
then they will be placebo, otherwise Jasmine will start mirrors

**Comment by Sing-Li** [comment]
@samhatoum   We just merged a Cordova build to main, and it has a local copy of autoupdate 1.2.4. 

The build breaks now when running velocity due to ISOBUILD constraints violation.   Have you seen this before?

TIA

```
163.30s$ meteor add rocketchat:livechat rocketchat:hubot sanjo:jasmine velocity:console-reporter
rocketchat:hubot: updating npm dependencies -- coffee-script, hubot,
hubot-calculator, hubot-google-hangouts, hubot-google-images,
hubot-google-translate, hubot-maps, hubot-help, hubot-scripts, hubot-youtube...
builLivechat: updating npm dependencies -- shelljs...
WARNING: The output directory is under your source tree.
                                              
Changes to your project's package version selections:
                                              
package-version-parser            added, version 3.0.4
practicalmeteor:chai              added, version 2.1.0_1
practicalmeteor:loglevel          added, version 1.2.0_2
rocketchat:hubot                  added, version 0.0.1
rocketchat:livechat               added, version 0.0.1
sanjo:jasmine                     added, version 0.20.2
sanjo:karma                       added, version 3.0.2
sanjo:long-running-child-process  added, version 1.1.3
sanjo:meteor-files-helpers        added, version 1.2.0_1
sanjo:meteor-version              added, version 1.0.0
velocity:chokidar                 added, version 1.2.0_1
velocity:console-reporter         added, version 0.1.4
velocity:core                     added, version 0.10.8
velocity:meteor-internals         added, version 1.1.0_7
velocity:meteor-stubs             added, version 1.1.1
velocity:shim                     added, version 0.1.0
velocity:source-map-support       added, version 0.3.2_1
                                              
rocketchat:livechat: Livechat plugin for Rocket.Chat
rocketchat:hubot: Package hubot for Meteor server
sanjo:jasmine: Velocity integration of the Jasmine testing framework
velocity:console-reporter: A console reporter for Velocity
The command "meteor add rocketchat:livechat rocketchat:hubot sanjo:jasmine velocity:console-reporter" exited with 0.
$ ./node_modules/velocity-cli/bin/velocity test-packages --ci
[[[[[ Tests ]]]]]
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:
   
   While selecting package versions:
   error: No version of autoupdate satisfies all constraints: @=1.2.4, @=1.2.3
   Constraints on package "autoupdate":
   * autoupdate@=1.2.4 <- top level
   * autoupdate@=1.2.3 <- top level
   
=> Your application has errors. Waiting for file change.
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by samhatoum** [comment]
Does it work locally? Try zapping the versions file maybe?

**Comment by Sing-Li** [comment]
@samhatoum - same behavior locally.  zapping the versions file made no difference.   it added back autoupdate 1.2.4  -- seems like something in velocity start is insisting on 1.2.3 of autoupdate.

**Pull request merged**
