### PR TITLE
[NEW] Marketplace integration with Rocket.Chat Cloud

### PR DESCRIPTION
**Pull request by graywolf336**
Work in progress of the integration with marketplace and cloud, allowing purchasing apps. :)

### CODE REVIEW

**Comment by rodrigok** [comment]
@graywolf336 can you sync with develop moving the changes from package to folder app?

**Comment by rodrigok** [comment]
When click to by and cancel the spinner keeps running

**Comment by graywolf336** [comment]
Notice there's a `todo` comment in the code? ;) it does need to be fixed and the code says so lol

**Comment by rodrigok** [comment]
The install inside app's details does not open the iframe to confirm

**Comment by rodrigok** [comment]
@graywolf336 I didn't review the code, I'm reviewing the functionality.
If it's not complete please add `[WIP]` at the beginning of the PR's title and list the pending items because if Gabriel or the UX team will review the PR they will not read the code!

**Comment by rodrigok** [comment]
When bying an app the button `get for free` doesn't works generating the error:
image

**Comment by graywolf336** [comment]
It's a draft pull request, which is used to indicate that it is a draft and not fully ready. There is absolutely still a lot of work to do, a large portion of which I have knocked out and have already addressed.

**Comment by graywolf336** [comment]
This pull request was not intended to be review ready but was simply to show the current flow, of which the reason it was created in a draft status is because it is not working functionality wise.

**Comment by rodrigok** [comment]
Continue the development on https://github.com/RocketChat/Rocket.Chat/pull/13809

**Pull request closed without merging**
