### PR TITLE
[FIX] wont close modal when clicked outside

### PR DESCRIPTION
**Pull request by tharzeez**
[FIX] Modal won't close now when clicked outside during Channel, Direct message, Discussion creation, and file upload modal

## Issue(s)

closes issue number #17562 
Issue: The modal closes when clicked outside of the modal.

## How to test or reproduce

Mentioned in the issue linked above.

## The Screens that are changed.
Four modals namely Channel, Direct message, Discussion Creation, and File uploader won't close now when clicked outside of the modal.
So that changes are not lost.

## Screenshots
rocket_chat

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ankar84** [comment]
@ggazzo @tassoevan please review that PR

**Comment by tharzeez** [comment]
Hey, @ggazzo @tassoevan let me know if I need to change anything in this PR.

**Comment by ankar84** [comment]
> Hey, @ggazzo @tassoevan let me know if I need to change anything in this PR.

Yeah, @ggazzo @tassoevan please take a look at that fix for a very annoying bug.

**Comment by ankar84** [comment]
Why it is still not merged?

**Comment by dougfabris** [comment]
@tharzeez thank you so much for your contribution! Recently we've changed these Modals to our Fuselage's Modal and we also added the click outside (intentionally) to close Modal capability, as you can check here #24275
Because of these changes, I'm going to close this one. Hope to see you contributing more 😃

**Pull request closed without merging**
