### PR TITLE
regression: Move WorkspaceCredentials models to CE

### PR DESCRIPTION
**Pull request by yash-rajpal**
## Proposed changes (including videos or screenshots)

Migration 316 breaks community edition, the migration tries to use some models which are only present in EE, which crashes the server.

image

Fixing it by moving the required models to CE

### CODE REVIEW

**Comment by ggazzo** [comment]
I don't see much problem with a model being public, what we should be concerned about are the controllers/logic

**Comment by yash-rajpal** [comment]
> What happens if I don't have the license but then I install it?

Good Question, I have no idea, maybe @Gustrb can help us.

**Comment by KevLehman** [comment]
2nd vote for making the model CE. Nothing on the model needs to be EE as long as whatever is calling it is on EE.

**Comment by yash-rajpal** [comment]
3rd vote on moving the model to CE.

I'll take care of this.

**Comment by Gustrb** [comment]
Yea I think the best approach would be to make the models public and avoid having to do weird things such as migrating on license change

**Comment by yash-rajpal** [comment]
@ggazzo Moved the models to CE

**Comment by KevLehman** [comment]
Can you update the PR title as well? We're not skipping migration anymore

**Review by KevLehman — APPROVED** [review]

**Pull request merged**
