### PR TITLE
[NEW][API] Endpoint `settings.addCustomOAuth` to create Custom OAuth services

### PR DESCRIPTION
**Pull request by g-rauhoeft**
This pull request adds a new path to the app/api/server/v1/settings.js file, called "settings.addCustomOAuth", which allows users to create a new custom OAuth Service definition via the REST interface, as discussed under https://forums.rocket.chat/t/add-custom-oauth-via-rest-api/3967.

### CODE REVIEW

**Comment by reetp** [comment]
Just a thought, but is it worth looking at this as well while you are at it?

https://github.com/RocketChat/feature-requests/issues/142

**Comment by geekgonecrazy** [comment]
@reetp I think if addressing that feature request would need to open a PR as wouldn't fit in the scope of this PR

**Comment by codakin** [comment]
@geekgonecrazy I think the current implementation is correct.  This mimics the behavior in the application.  First you provide a name and the custom Oauth is created.  Then you make edits and provide additional values.  These values would be set via the REST API using the [Settings update call](https://rocket.chat/docs/developer-guides/rest-api/settings/update/).  This would prevent having to update the REST API call proposed, in the future if some settings should change.

Also, in the code you shared for [addOauthService](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/server/methods/addOAuthService.js#L24), it only accepts one parameter of name so the proposed solution is also consistent for this reason.  It then continues on the create all the parameters you'll need so that you can call the settings update REST API for each one you need to change.

Let me know if I'm missing something.  Would love to see this feature in the next release.

**Comment by geekgonecrazy** [comment]
Ah good point!  Not sure how I missed that.  It is definitely too bad that that doesn’t return the settings created to make it easier for the following call.  But I can’t think of a clean way to do that.

**Comment by g-rauhoeft** [comment]
Thanks for the comments, everyone! 

@reetp I'm sorry, but that does seem a bit far out of scope for this pull request, especially because it concerns very different parts of the application.

@codakin Thank you, that does fit my reasoning perfectly. Basically my implementation just provides an API route for what the admin UI "Add OAuth Service" button does. I set the options for the created OAuth Service via the options (settings?) API.

@geekgonecrazy Thank you for the change request. codakin explained the reason behind the lack of further parameters to the route. If the explanation is sufficient, could you please close the request? I believe returning a list of options would break consistency with the API of Rocket.Chat in general and the paths to update the properties of an arbitrary OAuth Service are quite easy to generate. I can supply examples for the documentation if you want.

**Comment by col-panic** [comment]
Related https://github.com/RocketChat/Rocket.Chat/issues/10420

**Comment by col-panic** [comment]
Is there any plan on including this in one of the next releases? Would parts of this code probably solve #10420 , if yes, could they be probably provided as separate PR? Thanks

**Comment by Ubitso** [comment]
@geekgonecrazy @g-rauhoeft Can you merge this PR? Any updates?

**Comment by g-rauhoeft** [comment]
> @geekgonecrazy @g-rauhoeft Can you merge this PR? Any updates?

Sorry mate, nothing I can do because I'm not a member of the Rocket.Chat team and haven't got write access.

**Pull request merged**
