### PR TITLE
livechat office hours

### LINKED ISSUE #3863: Feature request: Opening hours on LiveChat
Your Rocket.Chat version: 0.35

Staff tends to forget to logout of the livechat when they go home. We would very much like to be able to set opening hours for the livechat so that it is less relevat for people to logout..

### PR DESCRIPTION
**Pull request by AlecTroemel**
@RocketChat/core 
Closes #3863

Open and closing office hours feature for livechat. If enabled, when the current time hits the start time all livechat agents are switched to "available". Likewise when closing time is reached all agents are switched to "not-available". Users may still make themselves available or not available at anytime.

screen shot 2016-08-16 at 3 57 05 pm

### CODE REVIEW

**Comment by AlecTroemel** [comment]
the Travis CI build is giving errors for lines 3 and 142 of packages/rocketchat-livechat/client/views/app/livechatOfficeHours.js .LivechatOfficeHour is defined and is a collection

**Comment by sampaiodiego** [comment]
thanks @AlecTroemel again for your contribution =D

to solve the lint issue, please add this to the header of the file `packages/rocketchat-livechat/client/views/app/livechatOfficeHours.js`:
```
/* globals LivechatOfficeHour */
```

**Comment by sampaiodiego** [comment]
Hey @AlecTroemel you can run lint locally, just do:

```
npm install
npm run lint
```

**Comment by AlecTroemel** [comment]
I did not know that, thank you!

**Comment by AlecTroemel** [comment]
hmmm..lint passes but the Travis build fails because it cannot find `server/models/livechatOfficeHour.js`. Runs locally fine and the file is in this PR..Am I missing something simple?

**Comment by sampaiodiego** [comment]
it looks like you are running meteor on a case insensitive file system (like windows')

the correct file name is `LivechatOfficeHour.js` (as you can see [here](https://github.com/AlecTroemel/Rocket.Chat/blob/b1804ec50f1e366bcce1956d3f565edd8086e4d5/packages/rocketchat-livechat/server/models/LivechatOfficeHour.js))..

but you are adding it to package as `livechatOfficeHour.js` (as you can see [here](https://github.com/AlecTroemel/Rocket.Chat/blob/b1804ec50f1e366bcce1956d3f565edd8086e4d5/packages/rocketchat-livechat/package.js#L168))

**Comment by AlecTroemel** [comment]
sigh.. it was something simple, thanks again.

**Comment by engelgabriel** [comment]
@RocketChat/core what do you think of this cool feature?

**Comment by sampaiodiego** [comment]
LGTM

**Pull request merged**
