### PR TITLE
Chore: Disable Sessions Aggregates tests locally

### PR DESCRIPTION
**Pull request by KevLehman**
## Proposed changes (including videos or screenshots)

Disable Session aggregates tests in local environments
For context, refer to: #20161 

## Issue(s)

Locally, `sessions` tests where failing due to an external problem with MongoDB. They are working as expected on CI. The goal of this MR is to disable the test when running locally but allowing it to run on CI.

## Steps to test or reproduce

1. Run `npm run testunit` on local environment (linux or WSL)
2. Session aggregates test should fail

### CODE REVIEW

**Review by pierre-lehnen-rc — DISMISSED** [review]

**Comment by KevLehman** [comment]
@pierre-lehnen-rc @sampaiodiego I had a wrong email in my git config, causing the CLA to fail every time. Updated it to the correct one, there should be no more problems from it 🎉 

(Also, would you mind reviewing again @pierre-lehnen-rc? There were no changes, the new commit just dismissed the review)

**Review by sampaiodiego — APPROVED** [review]

**Review by sampaiodiego — CHANGES_REQUESTED** [review]
I have approved initially but then I thought would still be good to run those tests locally, the main problem was having them running on `husky` pre-push hook and failing.. what  do you think?

the hook currently runs `meteor npm run lint && meteor npm run testunit` , not sure what the best approach to remove only the `Sessions Aggregates` from `testunit` though :thinking:

**Comment by KevLehman** [comment]
@sampaiodiego I'm creating a second npm script that excludes the `sessions` test locally. This will require us to have a separate `./mocharc-local.js` apart from our current one (which will be used by all other scripts and pipelines.

I'll submit the changes in a while.

**Comment by KevLehman** [comment]
@sampaiodiego changed.

**Comment by sampaiodiego** [comment]
thanks @KevLehman .. while reading Mocha's documentation to understand how to use multiple `.mocharc` files I ended up here: https://mochajs.org/#merging and since arguments specified on command-line have the greatest priority I was wondering if we could then just use `--exclude` on the `pre-push` hook.. I tried here and it worked, what do you think? I guess it is a simpler solution..

this is how my husky config looked like:
```
	"husky": {
		"hooks": {
			"pre-push": "meteor npm run lint && meteor npm run testunit -- --exclude app/models/server/models/Sessions.tests.js"
		}
	}
```

**Comment by KevLehman** [comment]
I can swear I tried that and didn't worked 😂 

Yep, that's a nicer solution, let me do the change 👀

**Review by sampaiodiego — APPROVED** [review]

**Pull request merged**
