### PR TITLE
[FIX] Typos/missing elements in the French translation

### LINKED ISSUE #21524: Typos/missing elements in the French translation
### Description:
There are typos/missing elements in the French translation

### Steps to reproduce:

1. Go to Account & Preferences

### Actual behavior:
image
image
image
image
and many more

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0-develop
- Operating System: Linux
- NodeJS Version: 12.21.0 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Linux

### PR DESCRIPTION
**Pull request by Jeanstaquet**
## Proposed changes (including videos or screenshots)

- I have corrected some typos in the translation
- I added a translation for missing words
- I took the opportunity to correct a mistranslated word
- Test_Desktop_Notifications was missing in the EN and FR file
image

## Issue(s)

Fixes #21524

### CODE REVIEW

**Comment by Karting06** [comment]
Sorry for the typos, I will correct them on LingoHub too.

**Comment by Karting06** [comment]
@Jeanstaquet I find `Télécharger` for uploading confusing.
`Télécharger` is for downloading something in my opinion.

**Comment by Jeanstaquet** [comment]
Hello @Karting06 indeed I understand what you want, it can be confusing, but it is the dictionary definition, I had checked in several translators and they put download every time. 
How about 'uploader' instead?

**Comment by Karting06** [comment]
Hi @Jeanstaquet 
Yeah, it's better. I made your changes on LingoHub.
I noticed that some strings were already using `uploader`.
Others are using `envoyer`. 
For example: 
- `Upload_file_question` : 
   - English: `Upload file?`
   - French: `Envoyer le fichier ?`
- `Uploading_file`:
   - English: `Uploading file...`
   - French: `Envoi du fichier en cours...`

It's sometimes tricky to choose... ;)

**Comment by Jeanstaquet** [comment]
Perfect, the final choice, we keep sending then, to be in line with the rest of the translations? 

Indeed, I just discovered while doing the PR how tricky the translation can be :p

**Comment by Karting06** [comment]
Hi @Jeanstaquet, I thought that I saw that you wanted `envoyer` but I can't find that comment on Github anymore. 
Did I read it wrong?

**Comment by Jeanstaquet** [comment]
Hello, 
Okay I'm sorry, I thought you had replied that uploading was better, and I had deleted my comment as I thought I had misunderstood.

But to get back to the discussion then, do we upload or send? In my opinion uploading is better, but I'll leave it to you to decide, which is the definitive choice?

**Comment by Karting06** [comment]
Yeah, I would keep uploading.
Thanks for your input!

**Review by ggazzo — APPROVED** [review]

**Pull request merged**
