### PR TITLE
Updated Traefik cli commands to v2 & Upgraded Mongo from 4.0 to 5.0

### PR DESCRIPTION
**Pull request by IbrahimS2**
Traefik using a v1 configuration that is not compatible with the latest version, now after updating it to v2, it is all working well.

### CODE REVIEW

**Comment by johncrisp** [comment]
Can you please keep this PR up to date with develop please?


Thanks

**Comment by IbrahimS2** [comment]
@johncrisp In what aspect, sorry?

**Comment by IbrahimS2** [comment]
@johncrisp Please check now.

**Comment by IbrahimS2** [comment]
@johncrisp Is this PR gonna be considered at all?

**Pull request closed without merging**
