### PR TITLE
Modified find for autocomplete to show usernames that begin your input

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Currently the situation is something like this:

image

That first user should not be even displayed. If i'm typing @ something.  I would expect it to only match beginning with what i've typed.  Otherwise its more of a search then a completion.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Also should name even checked?  I would think it'd only check username.  Because you can't do @ Aaron Ogle you have to do @geekgonecrazy

**Comment by dbussert** [comment]
My 2 cents, a team working together in-real-life will remember people by their real name, not their username.  Slack nails this one with auto-completion via username or real name.

**Comment by geekgonecrazy** [comment]
@dbussert doesn't it always show their username as the sender of messages though?

**Comment by dbussert** [comment]
@geekgonecrazy, if you're replying directly to a message, you will inherently see their username, and its very easy to do a @username.  But if you're typing a new message to get their attention, you very likely may want to use a real name, since you don't have their username already in front of you.  Having real name support is also very good for newbies who might not know all the usernames by heart, but do know the person they are trying to address.

**Comment by rodrigok** [comment]
@geekgonecrazy I agree with @dbussert and Slack matches last name too

**Comment by geekgonecrazy** [comment]
@dbussert @rodrigok ok that's fine by me.  I'm good with it as long as the autocomplete is actually useful instead of a nuisance.  So as long as its pushing what is most likely a match to the top i'll be happy.

**Pull request merged**
