### PR TITLE
Chore: Add mongo 4.2 to array of mongo versions supported

### PR DESCRIPTION
**Pull request by KevLehman**
## Proposed changes (including videos or screenshots)

- MongoDB 4.2 is now supported

### CODE REVIEW

**Comment by sampaiodiego** [comment]
I was not sure to what happened before https://github.com/RocketChat/Rocket.Chat/pull/21550/checks?check_run_id=2338185382#step:7:9

so I have updated with base branch so the CI runs again

**Comment by KevLehman** [comment]
It appears the same happened again 🤔 weird, but seems like the Mongo container won't start on 4.2

**Comment by sampaiodiego** [comment]
maybe MongoDB 4.2 doesn't accept the other params we're using 🤔 like `--noprealloc --smallfiles --replSet=rs0`

I was also looking into other Actions:

- like this that have specific params for replica set (which can simplify our CI file) https://github.com/marketplace/actions/mongodb-in-github-actions
- this one already starts mongodb with password, which would be a good addition to our pipeline: https://github.com/marketplace/actions/setup-mongodb-with-password

but for this particular issue, my bet are on those additional params.

**Comment by KevLehman** [comment]
Yeah, it looks like those options are tied to the `nmap` engine, so probably the 4.2 doesn't know what to do with them.

**Comment by KevLehman** [comment]
As expected, removing the mmap flags worked 😬 since the flags were mostly "informative", what do you think about removing those flags at all?

**Review by sampaiodiego — APPROVED** [review]
I think that's fine =)

**Pull request merged**
