### PR TITLE
[IMPROVE] German translations

### PR DESCRIPTION
**Pull request by mrsimpson**
as [requested by @sampaiodiego](https://github.com/RocketChat/Rocket.Chat/pull/12461#issuecomment-433894066), I checked the german translations.
While it seems as if there was nothing missing, I saw that some of the new translations were not living up to the best standards. I at least improved them ;)

Also, I added a npm script which I used to determine missing keys in language files.

### CODE REVIEW

**Comment by sampaiodiego** [comment]
wow. thanks @mrsimpson .. I was reviewing this https://github.com/RocketChat/Rocket.Chat/pull/12470/ from LingoHub.. not sure what to do now :joy:

**Comment by mrsimpson** [comment]
@sampaiodiego ahh - I did not get that as #12470 is already closed.
I manually verified the German translations in #12470. They also look complete, but not perfect. 
I merged this into this PR.

=> You can merge the Lingohub-stuff if you're confident about the other translations.
You should merge this PR afterwards in order to improve them.

**Comment by sampaiodiego** [comment]
@mrsimpson I've merged the lingohub.. can you please fix the new conflicts here? thx :hugs:

**Comment by mrsimpson** [comment]
Done. in pain. Why can't all tools agree on a common sorting? Should be good to merge now

**Comment by sampaiodiego** [comment]
sry @mrsimpson I think that's my fault.. I ran a script to remove duplicated fields and it sorted different than lingohub :( I'll try to create a script to validate duplicate fields and the sorting on CI, that'd help. thanks again

**Pull request merged**
