### PR TITLE
fix: add option to mount media on snap

### LINKED ISSUE #13391: [snap] add option to mount media
Allow media plug so snaps can write to /media
Should be as easy as adding the removable-media plug: https://github.com/nextcloud/nextcloud-snap/blob/master/snap/snapcraft.yaml#L81 to our rocketchat-server part.

Then need to add something like this to the docs to tell people how to do it: https://github.com/nextcloud/nextcloud-snap/blob/master/README.md#removable-media

### PR DESCRIPTION
**Pull request by knrt10**
Closes #13391.

cc @geekgonecrazy does this solves the issue?

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Absolutely!  I would recommend them making a PR on the docs repo to updat the snap FAQ to explain how to mount removable media to snap.  As does require a special command

**Comment by knrt10** [comment]
Will do so too

**Comment by knrt10** [comment]
@geekgonecrazy is `sudo snap connect rocketchat-server:removable-media` the right command as far as I think?

**Comment by geekgonecrazy** [comment]
It looks like that’s it: https://askubuntu.com/a/882696

**Comment by knrt10** [comment]
Docs are updated 👍 cc @geekgonecrazy

**Pull request merged**
