### PR TITLE
Added crowd integration

### LINKED ISSUE #3594: Atlassian Crowd Integration
Your Rocket.Chat version: 0.33

I have been looking at Rocket.Chat as a solution in my corporate setting and we require Atlassian Crowd integration for our user management. I see that it doesn't currently support it out of the box so I've been working on implementing it myself using [this](https://github.com/wehkamp/atlassian-crowd-client/) npm module

I've had a few ideas about how to implement it but was wondering if I could get some feedback from people/devs on whether or not I should
1. Just authenticate users and create them in the user table when they first authenticate
2. Sync users by copying all users from a crowd group into Rocket.Chat's user table and allowing them to authenticate after their user exists in the table? (periodically then syncing the users to a set interval, a bit like other Atlassian products I believe)

Thanks

### PR DESCRIPTION
**Pull request by Intox123**
@RocketChat/core 

Closes #3594

- Users can login using their Atlassian Crowd credentials after initial setup. 
- Includes syncing of the users at an interval.
 - It will only sync those users who have logged into Rocket.Chat at least once.

- [x] Add a "test connection"  button
- [x] Fix issue with trailing / needing to be present

crowd

### CODE REVIEW

**Comment by rodrigok** [comment]
Hi @Intox123, do you want some help with this PR?

**Comment by Intox123** [comment]
Hi @rodrigok, sorry been busy. Hopefully will get this finished soon. Just need to make some more small changes.

**Comment by rodrigok** [comment]
@Intox123 Awesome, let me know when we can review/merge your PR 😄

**Comment by Intox123** [comment]
@rodrigok I think it's ready now :)

**Comment by Joykiller** [comment]
Got a question, @rufushonour @rodrigok 

So this integration for crowd is mainly the Agents backend for Jira right? Will this also sync up with the Customer user accounts for like ServiceDesk?

**Comment by antoniodfr** [comment]
Hi everybody. Do you know if this integration works with a Jira User Server instead of a full Crowd? 
Thank you in advance.

**Comment by rufushonour** [comment]
@antoniodfr It may have changed since I wrote it but when this PR was merged it only supported full crowd instead of the user subsystem inside JIRA

**Comment by JSzaszvari** [comment]
No. JIRA's built in user server can only be used by other Atlassian apps that integrate with JIRA (like Confluence)

**Pull request merged**
