### PR TITLE
add option to toggle sidenav

### LINKED ISSUE #4441: Collapsible “navbar” (on the left)
Your Rocket.Chat version: 0.40.1

Could the left-hand bar/pane, the so-called “navbar” (I believe), be made collapsible, too?  Like the one on the right-hand side.  

Thanks in advance.

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #4441
- Added option to close/open left sidebar
- Added RocketChat.ScreenSize to verify screen size information from the browser (if is desktop, tablet, mobile and portrait or landscape)

### CODE REVIEW

**Comment by marceloschmidt** [comment]
Other than that, I think your solution is looking great :)

**Comment by karlprieb** [comment]
Fixed :) Thanks!

**Comment by engelgabriel** [comment]
@RocketChat/core I am not sure I even like this feature, wha to you guys think?

@karlprieb this issue was still labeled: discussion so please wait until we have decided before investing time to implement it.

**Comment by graywolf336** [comment]
In all honesty, I think we just need to make this button visible at all times so people can toggle it whenever they want and we already have it:

image

**Comment by marceloschmidt** [comment]
I actually liked the implementation, so I'd keep it... It doesn't affect the current UX, so I don't think there's a con.

**Comment by geekgonecrazy** [comment]
Being able to collapse it using that is kind of nice.  But expanding having to find the very edge of the collapsed nav, is not convenient.

Maybe have this in conjunction with this icon.  Both able to trigger collapse / expand.
image

Could be a bit clunky though

**Comment by lucasvanhalst** [comment]
I would be down to having the hamburger menu always show when collapsed. And when it's not collapsed an arrow instead, so like how it is on mobile. That way the edge isn't needed.

**Comment by engelgabriel** [comment]
@karlprieb lets create a user preference to have the burger always ON.

**Comment by lucasvanhalst** [comment]
Is this closed in favor of a new PR? Since I was kinda looking forward to this.
@karlprieb

**Comment by engelgabriel** [comment]
@lucasvanhalst we will create a user preference to have the burger always ON.

**Comment by michnovka** [comment]
is this finished? I cannot seem to be able to collapse sidebar with linux app or web UI with 0.59

**Comment by ustm** [comment]
Any update?

**Comment by geekgonecrazy** [comment]
UI has been revamped.  I'd say no plans to continue PR.

**Comment by nunoguerreiro** [comment]
not reall working

**Pull request closed without merging**
