### PR TITLE
[NEW] Livechat notifications on new incoming inquiries for guest-pool

### LINKED ISSUE #7292: Live Chat: No desktop notification when someone joins live chat queue
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: activated
Node Version: v 4.8.2.

Hi there,

I'm using the live chat feature and activated the live chat queue. It would be great if there was a desktop notification on the agents desktop each time someone has joined the queue. At the moment only a sound is played. If sound is deactivated on a agents desktop, he does not get notified if someone joins the live chat queue. So eventually the agents will miss chat requests.

Greetings,
Stefan

### PR DESCRIPTION
**Pull request by mrsimpson**
Closes #7292

This fixes desktop notifications not being created if a live chat visitor created a room by sending the first message.

## Remarks

- Notifications other than livechat and guest pool are based upon the user's subscriptions. Only for the live chat inquiries (the "requests for an agent to join"), there's a need for an alternative mechanism.
- Once an agent is joined, he's the only one to notify which matches the default: He'll have a valid subscription once joined.
- All code added is non-destructive (new functions, arrays concatenated, ...) - it will most likely not make things worse, even if it doesn't meet all the aspects
- From an architectural perspective, it would be better to have the code for creating the livechat-notifications in a separate hook defined in the livechat-package. The way it's been implemented creates a dependency from the notifications-api to the livechat-models - which is not good. On the other hand, the dependency is de-facto already there (`room.t !== 'l'`) and implementing it there has a high re-use.

### CODE REVIEW

**Comment by renatobecker** [comment]
@mrsimpson, can you fix the conflicts in this PR, please?
Thx.

**Comment by mrsimpson** [comment]
@renatobecker of course. Before I do, please let me know if it’s ok to have livechat specific code in these files

**Comment by renatobecker** [comment]
@mrsimpson, You will see that there have been many changes in the `packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js` file since your implementation.
I suggest you to move your code to `rocketchat-livechat` package because it's a specific approach to that feature.

Thanks.

**Comment by mrsimpson** [comment]
@renatobecker 
> You will see that there have been many changes in the packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js file since your implementation.

I had already fixed this, however I'm not too happy with the implementation (as said [four days ago](https://github.com/RocketChat/Rocket.Chat/issues/11137#issuecomment-400113566))

Still, I just updated this PR now to match the current development state. Because of the way notifications in RC are implemented, it's quite tricky to move the code to the livechat-package without duplicating a lot of code.

Please have a look at it whether it matches your architectural needs or if it really has to move. In the later case, I'd appreciate if someone from the core-team did the refactoring of the notifications-stuff into a library).

**Comment by renatobecker** [comment]
@mrsimpson, looking deeply your implementation, I can see that you are using an approach where the notifications will be triggered for every new messages that the guest/visitor sends, not just the first message when the inquiry is created, am I right?
If I'm not wrong, this behaviour is not same as requested on the issue #11137, because there the user is asking for notifications just when the inquiry is created, what, IMO, would be best for a standard implementation.

If I'm wrong about your use case, please let me know.

In addition: The migration of the code to `rockechat-livechat` package could be easy if the purpose of this approach is to notify agents for new incoming Livechats.

I'll be waiting for your feedback.
Thanks.

**Comment by mrsimpson** [comment]
@renatobecker like this? Now, a new notification is being create only for the first message which creates the queue entry

**Pull request merged**
