### PR TITLE
[NEW] Engagement Dashboard

### PR DESCRIPTION
**Pull request by tassoevan**
It adds the Engagement Dashboard for the Enterprise Edition.

### CODE REVIEW

**Comment by rodrigok** [comment]
Need to move the models to the `ee` folder

**Comment by robbyoconnor** [comment]
Ugh this would be useful for the those of us who don't use the EE version...

**Comment by robbyoconnor** [comment]
Just to clarify, this is not available in the FOSS version?

**Comment by rodrigok** [comment]
@robbyoconnor exactly, this is an enterprise feature, stay stunned on our blog post, we will explain about the merge of the enterprise repository here In the community soon.

**Comment by robbyoconnor** [comment]
I really wish you didn't go this route 😢

**Comment by robbyoconnor** [comment]
This is valuable to those of us using it in FOSS communities

**Comment by rodrigok** [comment]
@robbyoconnor everything we put on the enterprise (EE) will be valuable for people using the community (CE) version. The difference is that now we made the enterprise open source as well and everyone will be able to follow what we have and propose to EE version.

I believe you all understand that Rocket.Chat is a company and needs to have revenue to continue increasing the features of the CE version, you will notice that our releases will have much more changes and improvements on CE version than EE, but the EE needs to have some important differentials to be saleable otherwise everyone will use the CE and the core development here will stop.

We will have a blog post explaining all this soon.

Thanks

**Comment by robbyoconnor** [comment]
I'll move this discussion to the community server.

**Pull request merged**
