### PR TITLE
Announce ubuntu and freebsd support

### PR DESCRIPTION
**Pull request by Sing-Li**

### CODE REVIEW

**Comment by k0nsl** [comment]
:+1:

I've been wondering about FreeBSD support, and now I don't have to wonder any longer. In fact, I tried to get it work to work on 10.2 but it was too much hassle at the time so I simply gave up..

**Comment by soonahn** [comment]
@Sing-Li I've had experience building debians and managing an aptitude repository before.  Let me know if there's something I could help out on in this.

**Comment by Sing-Li** [comment]
@sooahn !   Indeed there is.  If you can get a server bundle distribution .deb created,  we can work with you to host the aptitude repository (on our iron) or submit it to some public aggregators out there.

Basically, in a nutshell:
* start mongo db
* expand the rocketbinaries.tgz
* set a few environment variables
* `node  app.js`

Dependencies
* mongo db
* node.js

This will be AWESOME!

**Comment by Sing-Li** [comment]
@k0nsl  - thanks!  We are more than excited (and honored)  to be collaborating with the respected team at FreeBSD to make this a reality.   

Really looking forward to see thousands of deployments,  running smoothly and worry-free  for hundreds of thousands of users, around the world :smiley:

**Pull request merged**
