### PR TITLE
[IMPROVE] Play selected notification sounds as preview while changing sound settings 

### PR DESCRIPTION
**Pull request by try-catch-stack**
## Proposed changes (including videos or screenshots)

Currently no sound plays while changing the notification sound settings or adjusting the volume which does not seem to be a good user experience as the user cannot preview the changes.
This PR enables the user to listen the selected sound at the selected volume . 

Check out this video for the proposed changes (Turn on the volume)

https://user-images.githubusercontent.com/77742477/149933395-b863bf2b-9f2b-448a-bfdc-3935db1b13fe.mp4

### CODE REVIEW

**Comment by try-catch-stack** [comment]
@dougfabris @sampaiodiego Can you please take a look ?

**Review by NakulRaghav — APPROVED** [review]

**Comment by nishant23122000** [comment]
Amazing work.🔥

**Comment by try-catch-stack** [comment]
@debdutdeb Can you please take a look at this again as it is open for a while now and haven't got any updates on it?

**Comment by adrianbarbe** [comment]
Is this PR still actual for the community?
I need this feature... And want to know what to expect

**Review by ggazzo — APPROVED** [review]

**Pull request merged**
