### PR TITLE
[FIX] Only authorised users will be shown the 3 dot option in channel list of teams.

### LINKED ISSUE #21595: Irrelevant display of 3 dots options in channel item of teams
### Description:
Any non-admin/moderator/team owner user should not be shown the 3 dot option as in the backend the API call gives an error.

### Steps to reproduce:

1. Any team
2. Channels
3. Click on 3 dots

### Expected behavior:
The 3 dot option should only be shown to authorized users.

### Actual behavior:
All users can see the 3 dot option.

https://user-images.githubusercontent.com/55157259/114944241-d7d65c00-9e64-11eb-8a93-6e5a79d9a45d.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.21.1
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Ubuntu
- Operating System:Chrome/Firefox

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)

Only authorized channels will be shown the 3 dot option.

https://user-images.githubusercontent.com/55157259/114944461-44e9f180-9e65-11eb-8a44-aaa25aee130f.mp4

## Issue(s)

Closes #21595

### CODE REVIEW

**Comment by Darshilp326** [comment]
@dougfabris @ggazzo Please review :smile:

**Comment by Darshilp326** [comment]
@dougfabris Please review!

**Comment by dougfabris** [comment]
@Darshilp326 I'm closing this one because the issue is bigger and we'll use this approach: #21946. Thanks for the PR,

**Comment by Darshilp326** [comment]
@dougfabris Okay! No problem.

**Pull request closed without merging**
