### PR TITLE
[FIX] Corrected the user ability to view admin permissions

### LINKED ISSUE #20400: user can see admin permissions page
### Description:

A typical user can visit permissions page by call admin/permissions url directly although users do not have permission to view Permissions

### Steps to reproduce:

1. user login
2. user type https://XXX/admin/permissions url directly
3. user can see this page!

### Expected behavior:

Users restrict from seeing permission page in admin section when they do not have permission to view Permissions

### Actual behavior:

user can ses permissions page (can not edit)

### Server Setup Information:

I use rocket.chat demo cloud 

- Version of Rocket.Chat Server: 3.9.4
- Operating System: linux
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: firefox and chromium
- Operating System:  fedora 33

### PR DESCRIPTION
**Pull request by sushant52**
- [x] I have read the Contributing Guide -https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
  - [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
  - [x] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  - [ ] I have added necessary documentation (if applicable)
  - [ ] Any dependent changes have been merged and published in downstream modules
 
## Proposed changes (including videos or screenshots)
Added a check using the 'access-setting-permissions' to prevent non-authorized users to access the permissions page. This should not be done using 'access-permissions' because it changes one's ability to **modify the permissions** instead of just **accessing the permissions page**. The labels for the settings are swapped.

## Issue(s)

Closes #20400 

## Further comments

The labels for both the settings are actually swapped. This should be changed.
Screenshot from 2021-01-26 22-01-35

If one hovers over the setting, the actual function performed by that setting can be viewed.
Screenshot from 2021-01-26 22-04-35
This says "Access permissions screen", but it actually toggles the ability to **modify the permissions**, as shown in the tooltip.

Screenshot from 2021-01-26 22-06-05
This says "Modify settings-based permissions", but it actually toggles the ability to **access permissions page**, as shown in the tooltip.

I have verified this. With the settings below and the changes I made, random user can access the permissions page but not change it.
Screenshot from 2021-01-26 22-01-47

The labels should be swapped.

### CODE REVIEW

**Comment by sushant52** [comment]
@gabriellsh Please have a look :D

**Review by gabriellsh — CHANGES_REQUESTED** [review]
Please read https://github.com/RocketChat/Rocket.Chat/issues/20400#issuecomment-769422985

**Comment by sushant52** [comment]
@gabriellsh I think this is good now.

**Comment by yash-rajpal** [comment]
@sushant52 PR #20403 was made earlier than this PR, please let that pr handle this issue.
Thanks :)

**Comment by gabriellsh** [comment]
Closing in favor of https://github.com/RocketChat/Rocket.Chat/pull/20403, which is a more complete fix. Thanks for your effort anyway.

**Pull request closed without merging**
