### PR TITLE
Allow to send a temp message to one user to one room

### PR DESCRIPTION
**Pull request by rodrigok**
Allow send a message to one user via the notification system, this message is temporary and go away when user lost the data on minimongo.

From **server** to **client**
```javascript
RocketChat.Notifications.notifyUser('UserID', 'message', messageObject);
```

Example:
```javascript
RocketChat.Notifications.notifyUser('MZiFvWAfF4RF4AD5u', 'message', {
	_id: Random.id(),
	rid: 'GENERAL',
	ts: new Date,
	msg: 'user/client only message'
});
```

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
So this comes as if it were from rocketbot?

**Comment by rodrigok** [comment]
@geekgonecrazy yes, at least for now until a better idea :)

**Comment by graywolf336** [comment]
@rodrigok Maybe make it configurable in the admin panel? That way if someone has a different name for their bot they can use that instead?

**Comment by Morgul** [comment]
What if, instead, there was just a special style for system messages, and this didn't look like it came from a user at all? Like, right aligned, grey text, or something?

**Comment by rodrigok** [comment]
@graywolf336 yes, can be configurable, i will open an issue for that

@Morgul I like the ideia of the bot replying, just my opinion

**Comment by sampaiodiego** [comment]
I think if a command could be answered by the server, the command itself should listed on message area too..

something like this:

image

**Comment by geekgonecrazy** [comment]
Yeah i'm a fan of it coming from a bot.  For sure want it configurable. :)

A lot of IRC channels have a custom named service like a bot that does stuff like this.

**Comment by rodrigok** [comment]
@sampaiodiego I don't see this necessity

**Comment by Morgul** [comment]
@sampaiodiego While I agree with you that would be be more consistent, might that confuse the user into thinking that everyone can see what channels they're joining?

**Comment by graywolf336** [comment]
I think a message near the time needs to be displayed "This message is only visible to you."

**Comment by sampaiodiego** [comment]
sure @Morgul .. but this can be solved exactly how @graywolf336 said while I'm answering :stuck_out_tongue: 

maybe an icon indicating it's "private"..

**Comment by graywolf336** [comment]
Yeah, a small lock icon would be probably be good.

**Comment by Morgul** [comment]
I'd prefer something like a small grey label that says 'Private'.

**Comment by sampaiodiego** [comment]
btw, in my opinion even the answer of `bot help` should be visible only for who asked.

**Comment by sampaiodiego** [comment]
another idea:

image

**Comment by graywolf336** [comment]
I agree on the `bot help` visibility only being to those who used it.

I like that icon and then when they hover over it the `title` attribute says "This is only visible to you."

**Comment by geekgonecrazy** [comment]
`bot help` will require us be able to pass visibility in the message from the bot its self.

**Comment by rodrigok** [comment]
I like the Slack behaviour

captura de tela 2015-09-14 as 17 46 09

**Comment by geekgonecrazy** [comment]
Yeah that does make it 100% obvious.  No room for question really

**Comment by rodrigok** [comment]
ok, 5min, i will implement this

**Comment by graywolf336** [comment]
@rodrigok Timer started ;)

**Comment by Morgul** [comment]
Yeah, :+1: for being super explicit.

**Comment by rodrigok** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/808

**Pull request merged**
