### PR TITLE
Search improvements

### LINKED ISSUE #3549: [feature] time range search, search by time
Your Rocket.Chat version: 0.31.0

I was proposing to push more conversations to rocket chat instead of the mailing list but someone had a complain:
The problem of long discussions is that you can only search by words, regex, etc. But in mailing list archives you can also search information by time: day, week, month, year. I think this could be a valuable feature for rocket chat.

### PR DESCRIPTION
**Pull request by lucasvanhalst**
@RocketChat/core 

Closes #3549

Improves the search so you can filter on more things.

- You can now enter `from:me` to search for messages only created by the current user.
- `has:star` returns messages that are starred by the current user
- `is:pinned` or `has:pin` returns messages that are pinned in the current channel
- `has:url` or `has:link` returns messages that contain a link
- `has:location` or `has:map` returns messages that have a location attached
- `before:dd/MM/YYYY`, `after:dd/MM/YYYY` and `on:dd/MM/YYYY` return message that were created before, after or on the provided date respectively. You can also use dashes `-` or dots `.` instead of slashes.
- `order:asc` sorts messages by ascending timestamp. You can also use `order:ascend` or `order:ascending`
- `order:desc` sorts messages by ascending timestamp. You can also use `order:descend` or `order:descending`.

There is no indication in the UI that is this possible though.

I've also converted the coffeescript to js since I know you guys are doing this step by step.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@lucasvanhalst this is really cool!  So with all of this we kind of need a cheatsheet quick help thing there in the search.

**Comment by sampaiodiego** [comment]
that is indeed really cool!

**Comment by lucasvanhalst** [comment]
I think something like this would be better @geekgonecrazy

**Comment by geekgonecrazy** [comment]
@lucasvanhalst ah yes!  Agreed, that looks nice

**Comment by alfredbez** [comment]
> There is no indication in the UI that is this possible though.

I'd like to see 2 things here:
1. add instructions, maybe [here](https://github.com/RocketChat/Rocket.Chat/blob/a8dbc98412f4d3bb6c3cfd58149925122ec287dc/packages/rocketchat-ui-flextab/flex-tab/tabs/messageSearch.html#L6)
2. highlight filters ins searchbox (like in slack)

image

Date-filter seems buggy: 
image

I create two new seperate issues

**Comment by geekgonecrazy** [comment]
@alfredbez we'd welcome another PR to add that.  :smile:

**Comment by lucasvanhalst** [comment]
It's true that the date filters don't won't properly.  They did on my test environment of course..   God I hate time zones :D

**Comment by graywolf336** [comment]
To follow up, the dates still work but it's not in the Amreican format. It is dayday/monthmonth/year, so for Feburary 11th, 2017 the search would be: `on:11/02/2017`.

**Pull request merged**
