### PR TITLE
[IMPROVE] Omnichannel contact updates after addition or edit of any contact

### LINKED ISSUE #24197: Omnichannel contact doesn't update itself when a contact is added or edited
### Description:

I think it will be a small but great improvement to give instant feedback to the user when we add or edit contacts in the Omnichannel.

### Steps to reproduce:

1. Go to Omnichannel Contact Center.
2. Click on Add or if you already have a contact edit it.
3. Notice the UI doesn't reflect changes immediately. (You can refresh and see the changes though)

### Expected behavior:
Should immediately notice the changes made.

### Actual behavior:
Just a toast action to notify that changes have been made with no real visual effect in UI.

https://user-images.githubusercontent.com/73601258/149798524-f256b3f7-bd36-4f63-91d3-9d4d7f2a64ce.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0-develop
- Operating System: Ubuntu 20.04
- NodeJS Version: 14.18.2-x64
- MongoDB Version:4.4.4

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by sidmohanty11**
The contacts list were not updating after editing a contact or adding a new contact, so I used the reload function to get contact list updated after addition or edit of any contact.

## Proposed changes (including videos or screenshots)

Before,

https://user-images.githubusercontent.com/73601258/148402862-501e265b-d0e8-4201-b197-8aea48aa25f5.mp4

After,

https://user-images.githubusercontent.com/73601258/148402908-23a6b72a-de75-497d-b5d7-70167e7f4053.mp4

## Issue(s)

closes #24197
## Steps to test or reproduce

Mentioned in the issue.

### CODE REVIEW

**Comment by dudanogueira** [comment]
That's a nice catch!!

Those small improvements has a huge impact on user experience.

THanks!!!

**Comment by sidmohanty11** [comment]
Thank you so much @dudanogueira 😄

**Comment by renatobecker** [comment]
Hi @sidmohanty11 thank you for your contribution, we really appreciate that!
There are a few conflicting files though, would you be able to fix them, please? In that case, we can proceed with code review and merge processes.

Thanks!

**Comment by KevLehman** [comment]
Hey! Thanks for your contribution 🤗 

This time, we'll go with the approach taken by #29238 as both solve the same issue, with different code :) thanks again, and we'll see you in your next PR

**Pull request closed without merging**
