### PR TITLE
[FIX] Introduce AppLivechatBridge.isOnlineAsync method

### PR DESCRIPTION
**Pull request by renatobecker**
To properly run the `AppLivechatBridge.isOnline` method, it needs to become an asynchronous method.
Otherwise, we will get an error as shown below when executing it through the Apps-Engine:

```
W20200204-17:15:09.944(-3)? (STDERR) Exception on find Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
W20200204-17:15:09.945(-3)? (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor.js:1186:11)
W20200204-17:15:09.945(-3)? (STDERR)     at Meteor.EnvironmentVariable.EVp.get (packages/meteor.js:1199:10)
W20200204-17:15:09.946(-3)? (STDERR)     at Object.collection.<computed> [as find] (packages/matb33_collection-hooks.js:136:37)
W20200204-17:15:09.946(-3)? (STDERR)     at Collection.find (packages/mongo/collection.js:334:29)
W20200204-17:15:09.946(-3)? (STDERR)     at BaseDb.find (app/models/server/models/_BaseDb.js:130:21)
W20200204-17:15:09.946(-3)? (STDERR)     at Users.find (app/models/server/models/_Base.js:116:29)
W20200204-17:15:09.946(-3)? (STDERR)     at Users.findBotAgents (app/models/server/models/Users.js:112:15)
W20200204-17:15:09.946(-3)? (STDERR)     at Object.getBotAgents (app/livechat/server/lib/Livechat.js:96:16)
W20200204-17:15:09.946(-3)? (STDERR)     at Object.online (app/livechat/server/lib/Livechat.js:60:31)
W20200204-17:15:09.947(-3)? (STDERR)     at AppLivechatBridge.isOnline (app/apps/server/bridges/livechat.js:16:19)
W20200204-17:15:09.947(-3)? (STDERR)     at LivechatRead.isOnline (/Volumes/Workspace/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/accessors/LivechatRead.js:9:36)
W20200204-17:15:09.947(-3)? (STDERR)     at WhatsAppMessageEndpoint.post (evalmachine.<anonymous>:31:56)
W20200204-17:15:09.947(-3)? (STDERR)     at processTicksAndRejections (internal/process/task_queues.js:93:5) { roles: { '$all': [ 'bot', 'livechat-agent' ] } }
``

### CODE REVIEW

**Comment by d-gubert** [comment]
this is a breaking change to the Apps-Engine definition, which blocks us from changing it until the next major version.

@lolimay this is the same problem we've discussed [here](https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/213), can you work with @renatobecker to introduce a new method and deprecate this one?

@rodrigok do you think there is a better way to handle this situation?

**Comment by renatobecker** [comment]
> this is a breaking change to the Apps-Engine definition, which blocks us from changing it until the next major version.
> 
> @lolimay this is the same problem we've discussed [here](https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/213), can you work with @renatobecker to introduce a new method and deprecate this one?
> 
> @rodrigok do you think there is a better way to handle this situation?

Thanks @d-gubert for your comment, we just need to have a quick definition about this matter because Caixa is waiting this implementation to be able to use their App property.

**Comment by rodrigok** [comment]
@d-gubert since it was introduced 2 days ago and the release is under release candidate still I don't see any problems incorporating this beaking change.

**Comment by rodrigok** [comment]
We can release a new version and deprecate the old one where the feature was introduced

**Comment by d-gubert** [comment]
@rodrigok this functionality has actually been introduced 2 months ago [by this PR](https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/189/files#diff-4cf13b98634faac0a8c981c3dc9ac9ecR6) and has been part of the API since then

**Comment by rodrigok** [comment]
@d-gubert I see, so, yes, need to create a new method

**Review by d-gubert — APPROVED** [review]

**Pull request merged**
