### PR TITLE
[NEW] Internal hubot support for Direct Messages and Private Groups

### LINKED ISSUE #7550: Add internal hubot to private chats by default
What's the easiest way to do this guys and gals? Ideally it would be a default admin setting to toggle on or off (if on the hubot could repond to requests in every private chat until it's been removed from the chat.)

### PR DESCRIPTION
**Pull request by ramrami**
@RocketChat/core 

### Before 
Internal hubot only responded to public rooms (room.t = 'c')

### After
Internal hubot respond to the enabled room types ( 'c' or 'd' or 'p')

**Edit**
The bot respond in private groups only if it's added to that group.

Closes #7550 (maybe 5191 also)

### CODE REVIEW

**Comment by reetp** [comment]
Nice if this could make it in to 60 :-)

**Comment by slyk** [comment]
I would like people to DM to my hubot.
Internal is working ok on channels, but that creates scrapyard of messages, that needed only for person who talks to hubot.

Was trying to edit snap files to fast get this feature, but can't do this because of protection :(

---

hubot-rocketchat adapter could use DM, but I wanted to use internal.

How could we add this to release?

**Comment by reetp** [comment]
@ramrami is there any chance you could look at this ?
It would be really good to have it fixed.

**Comment by ramrami** [comment]
@reetp It's ready to be merged. All we need is a review from core team members.

**Comment by reetp** [comment]
@rodrigok can one of the devs look at this?

A fix and PR has been languishing here for some while for a bug that has been open for ages. I don't understand why it has been ignored so long.

Thanks.

**Comment by geekgonecrazy** [comment]
Sorry guys some how this slipped by.

**Comment by reetp** [comment]
Thanks Aaron :-)

**Comment by reetp** [comment]
As far as I can see it fixes:
https://github.com/RocketChat/Rocket.Chat/issues/3132
https://github.com/RocketChat/Rocket.Chat/issues/5191
https://github.com/RocketChat/Rocket.Chat/issues/7550

**Comment by reetp** [comment]
@ramrami is there anything that needs to be done so we can see this in the 0.62 release ?

**Comment by ramrami** [comment]
@reetp It's already approved by @geekgonecrazy, and it has been added to the [0.62.0](https://github.com/RocketChat/Rocket.Chat/milestone/100) milestone.

**Comment by geekgonecrazy** [comment]
We'll began merging PR's for 0.62.0 I believe this next week. No worries, I don't see any reason this won't land

**Comment by vaggeliskls** [comment]
Iam using 0.62.2 version of rocketchat. 
I have update the Enable for Public Channels, Enable for Direct Messages and Enable for Private Channels to true. Iam trying to do an bot help command but no response on private channels. On direct and public channels work perfectly. 
image

**Comment by ramrami** [comment]
Did you invite the bot to the private channel ?

**Comment by vaggeliskls** [comment]
I am running @rocket.chat help. Is there any specific way that i can invite the bot ? Thank you

**Pull request merged**
