### PR TITLE
Saml logout fix

### PR DESCRIPTION
**Pull request by danielbush**
@RocketChat/core 

Hi Guys,
This PR definitely needs some work - hoping someone might want to help me with this.
It extends #4649 with a logout that works for a single browser.  So, it's only the **last 3 commits** that would apply if #4649 is ok:

* FIX: handle saml urls with query strings.
* FEATURE: SAML sp-initiated logout.
* CHANGELOG: Saml.

The things I'm not sure about are listed in `CHANGELOG.md`.
* Using a Meteor `Session` key
* overriding `Meteor.logout`

Regards,
Daniel

### CODE REVIEW

**Comment by danielbush** [comment]
I think it works best if we either do `Meteor.logout` or `Meteor.logoutWithSaml` - so I've made that change.  But we're still rewriting `Meteor.logout` to do this.

**Comment by rodrigok** [comment]
Hi @danielbush, can you explain why we should call the logout for SAML and not just call the default logout?

**Comment by danielbush** [comment]
Hi @rodrigok If I don't use the saml logout and the user logs out after logging in with saml, then if they try to login to rocketchat in the same window using saml a second time, the idp automatically logs the user in, and the user will find themselves logged into rocketchat automatically.  Didn't seem like a good thing.

I need to fix an issue with this.  If the `idpSLORedirectURL` field is blank, this saml plugin looks like it uses the standard endpoint to the idp to send the logout request which will cause the simplesaml idp I'm testing with to give an error response.  So, I think I need to only do `logoutWithSaml` if `idpSLORedirectURL` is set for the current provider that has been used.  I'll push a fix for this.  That way this logout with saml is only triggered by `idpSLORedirectURL`.   You might be happier with this?

**Comment by danielbush** [comment]
@rodrigok how can I check if `idpSLORedirectURL` has been set for the current saml provider in `saml_client.js`?  Trying Session, pub/sub,... not having much luck.

**Comment by danielbush** [comment]
ok @rodrigok I've made `logoutWithSaml` only apply if `idpSLORedirectURL` is set.
We get an error (testing with simplesamlphp) if we do `logoutWithSaml` when `idpSLORedirectURL` is blank - the saml code will try to request logout using the normal endpoint.
I do think however there is an issue with using the standard logout - because it doesn't appear to log us out of the idp and a user can log back in again from the same window without having to supply credentials.

I've put some notes in the `CHANGELOG.md`.

**Comment by danielbush** [comment]
@rodrigok any updates?
Note: this p/r contains #4649 + idp "single logout" . So, it might be better just to review it all here?
The single logout is only triggered if we set the `idpSLORedirectURL` setting.

**Comment by geekgonecrazy** [comment]
@rodrigok can we make it accept the certificate instead of a file path.  Because if a file path docker will require extra config, and so will snaps (actually will require a lot more work to inject that certificate inside the snap)

**Comment by geekgonecrazy** [comment]
Ok changed from loading from file to storing the cert. 

Also added validateNewUser check.  I'm concerned though... because we have two methods defined with the same name for validateNewUser

**Pull request merged**
