### PR TITLE
Issue #616 - Fixed multiline code block overflow

### PR DESCRIPTION
**Pull request by rodrigogs**

### CODE REVIEW

**Comment by rodrigok** [comment]
Why not just override hljs class adding 1 rule instead creating a new class copying all rules?
```css
.hljs {
	overflow-y: hidden;
}
```

**Comment by rodrigogs** [comment]
Because overflow hidden behaviour is different from no overflow. In this case overflow hidden also solves the problem, but I think that to have no overflow at all is a better option to prevent another possible problems.

**Comment by rodrigok** [comment]
@rodrigogs according to http://www.w3schools.com/cssref/pr_pos_overflow.asp the default value of overflow is visible, so if you want to remove the overflow you can override with the value **visible** right?

**Comment by rodrigogs** [comment]
You are right. I were trusting in what I've heard from another developers, as I never aimed for front styling. Strange to hear the same wrong thing from a bunch of people that works just with this.

**Comment by rodrigok** [comment]
Nice :D

**Pull request merged**
