### PR TITLE
[FIX] Display Avatars switch: unable to disable showing avatars in messages

### LINKED ISSUE #26741: Display Avatars switch:  unable to disable showing avatars in messages
User Preference:
Display Avatars: Hides avatars on the channels, showing only the users' usernames.

This setting since version 5 does not disable the viewing of user's avatars in messages.

### PR DESCRIPTION
**Pull request by roy9495**
rocket_chat

## Proposed changes (including videos or screenshots)
Closes #26741

### CODE REVIEW

**Comment by roy9495** [comment]
> QQ: What do I do if I want avatars in my workspace? :P

I apologise, sir, I have not considered that.
I will redo this.

**Comment by roy9495** [comment]
> QQ: What do I do if I want avatars in my workspace? :P

Sir, do you suggest using a toggle button?

**Comment by gabriellsh** [comment]
> > QQ: What do I do if I want avatars in my workspace? :P
> 
> Sir, do you suggest using a toggle button?

There is already a user preference for this :)

**Comment by surendra0988** [comment]
Hello, I am Surendra.
I would like to work on this issue as my first open source contribution.
Could you please assign this to me?

**Comment by dougfabris** [comment]
No @surendra0988 the issue is closed for a reason

**Pull request closed without merging**
