### PR TITLE
[FIX] bug in syncing existing users

### LINKED ISSUE #13069: LDAP Existing user data not updated on Background Sync
### Description:
We use LDAP exclusively for user data and authentication. When an existing user logs in, any changes on the LDAP side (avatars and data we map to custom fields), get updated. When we perform a background sync -- manually from Administration or from the cron job -- new users are added. However, users that already exist do not have their data updated.

### Steps to reproduce:
1. Identify an existing user in your RocketChat install.
2. Change their avatar in Active Directory/LDAP.
3. Go to Administration>LDAP>Sync/Import
4. Click Execute Synchronization Now.

### Expected behavior:

I expect the user in step 1 above to have a new avatar, matching the one in LDAP. With tracing turned on, I expect to see a log line indicating an avatar was updated.

### Actual behavior:

No update to the user takes place. No errors are logged.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.1
- Operating System: Linux Ubuntu 16.04.5 LTS
- Deployment Method: tar, manual deployment
- Number of Running Instances: 4
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.6

### LDAP settings

LDAP Enable: true
Login Fallback: false
Find user after login: true
Merge Existing users: true
Logging: trace
Sync user data: true
Sync user avatar: true
Background sync: true
Background Sync import new users: true
Background sync update existing users: true

### Relevant logs:
Here is the log from the code that doesn't work. 
`[34mI20190103-16:39:39.300(-6) LDAP ➔ Connection.info Init setup 
[34mI20190103-16:39:39.304(-6) LDAP ➔ Connection.info Connecting ldap://corp.perfect-10.tv:389 
[34mI20190103-16:39:39.310(-6) LDAP ➔ Connection.info LDAP connected 
[34mI20190103-16:39:39.311(-6) LDAP ➔ Bind.info Binding UserDN MIS_Wiki@corp.perfect-10.tv 
[34mI20190103-16:39:39.316(-6) LDAP ➔ Search.info Searching user * 
[34mI20190103-16:39:40.874(-6) LDAP ➔ Search.info Page 
[34mI20190103-16:39:40.874(-6) LDAP ➔ Search.info Page 
[34mI20190103-16:39:41.289(-6) LDAPSync ➔ info Import running. Users imported until now: 100 
[34mI20190103-16:39:41.405(-6) LDAPSync ➔ info Import running. Users imported until now: 200 
[34mI20190103-16:39:42.168(-6) LDAP ➔ Search.info Final Page 
[34mI20190103-16:39:42.170(-6) LDAP ➔ Search.info Final Page 
[34mI20190103-16:39:42.204(-6) LDAPSync ➔ info Import running. Users imported until now: 300 
[34mI20190103-16:39:42.273(-6) LDAPSync ➔ info Import running. Users imported until now: 400 
[34mI20190103-16:39:42.344(-6) LDAPSync ➔ info Import running. Users imported until now: 500 
[34mI20190103-16:39:42.407(-6) LDAPSync ➔ info Import running. Users imported until now: 600 
[34mI20190103-16:39:42.455(-6) LDAPSync ➔ info Import finished. Users imported: 662 
[34mI20190103-16:39:42.456(-6) LDAPSync ➔ info Import finished. Users imported: 662 
[34mI20190103-16:39:43.456(-6) LDAP ➔ Search.info Idle 
[34mI20190103-16:39:43.458(-6) LDAP ➔ Connection.info Disconecting 
[34mI20190103-16:39:43.460(-6) LDAP ➔ Search.info Closed `

### PR DESCRIPTION
**Pull request by ohmonster**
Closes #13069

There was an if condition that seemed as if it were meant to gatekeep whether existing users were updated on background sync, based on the LDAP configuration. However it was constructed in such a way it would never be true.

https://github.com/RocketChat/Rocket.Chat/blob/7bd82ef94361af1d0344404af7e3847aab1328f7/packages/rocketchat-ldap/server/sync.js#L304-L305

I removed the bang.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@ohmonster thanks for the detailed report and then subsequent PR!

@rodrigok @Hudell can you guys take a look at this and corresponding issue?  Seems like this was an oversight that some how has just gone un-noticed.

**Comment by ohmonster** [comment]
Tweaking the condition fixed sync issues in my dev environment. But that’s just one server configuration, and I was tightly focused on a couple of things. 

The sync user code involves a lot of  installation specific settings, and I was concerned I  missed something in terms of side effects. 

But we’re hoping that it’s really that simple. 

Thanks!

**Comment by rodrigok** [comment]
This PR changes the code to import new users, it doesn't solve the problem related to updates.

I'll close this until we have a better solution.

Discussion here #13069

**Comment by geekgonecrazy** [comment]
is this not still a valid bug fix?  Does this condition ever actually evaluate to true?  From my understanding after this bug fix the syncing issue experienced was actually solved

**Comment by rodrigok** [comment]
@geekgonecrazy it's not valid, if the user turns off the "import new users" setting it will continue with the bug since what code is doing is changing the "import new users" feature to "reimport all users"

**Comment by ohmonster** [comment]
@rodrigok thanks for having a look.

**Pull request closed without merging**
