### PR TITLE
[NEW] Reply preview

### LINKED ISSUE #9912: Preview the message that the user is replying to
### Description:
When replying to the message we only see the URL of the message, not the actual message itself. The actual message can only be seen after the reply is sent. The message that the user is replying to should float just above the input field as in WhatsApp.

### PR DESCRIPTION
**Pull request by ubarsaiyan**
@RocketChat/core 

Closes #9912 
This adds a Whatsapp like preview feature to replies, ie. the user can see the mssg he/she is replying to. I tried to do this in the minimal amount of code, hence I reused the messageAttachment Template which is used for displaying replies or attachments to a message. When replying to a reply, the preview only shows the outermost mssg (only one level of reply) as it would take a lot of space to display all the levels. The preview can also show formatted mssgs. Deleting the whole message removes the reply preview. Sending the mssg also removes the reply preview. Many many optimisations and new features can be incorporated further such as:

- ~adding a 'x' button to hide the preview~ Done
- ~removing the url of the message being replied to from the input box~ Done
- ~beautifying the reply preview~ Done

screenshot from 2018-03-11 03-06-30
screenshot from 2018-03-11 03-06-30

image

### CODE REVIEW

**Comment by ubarsaiyan** [comment]
@MartinSchoeler I'm sorry to have included the unnecessary files. I have removed them now and also combined the commits into one.

**Comment by rodrigok** [comment]
That is really amazing @ubarsaiyan thank you.

I have a suggestion, what if you remove the Markdown that includes the mention (that link to the message) from the input field and add before send the message? That way we hide that ugly part.

Other good addition would be a X button to close/remove the mention, if you implement my suggestion above that would be the only way users could do that.

**Comment by ubarsaiyan** [comment]
@rodrigok Yes, I will implement that too :) and improve the ui too.

**Comment by ubarsaiyan** [comment]
@rodrigok @MartinSchoeler I have made the necessary changes: Implemented the ui of @ mention popup, adding a cancel reply button, removing the URL of the mssg being replied to from the input box. I have taken care that the code is bug-free and does the work minimal amount of code. The message in the input box is retained upon closing the reply and replying after writing the mssg.

**Pull request merged**
