### PR TITLE
[NEW] Screen Lock settings - mobile client

### PR DESCRIPTION
**Pull request by djorkaeffalexandre**
Screen Shot 2020-05-04 at 14 02 26

### CODE REVIEW

**Comment by sampaiodiego** [comment]
I don't know what is happening to GitHub CI 🤔 

anyways, I think we should mention this is more than a "Screen lock", it also requests a PIN code when locked.. I've seen an app calling this as "app protection", wdyt?

**Comment by diegolmello** [comment]
> I don't know what is happening to GitHub CI 🤔
> 
> anyways, I think we should mention this is more than a "Screen lock", it also requests a PIN code when locked.. I've seen an app calling this as "app protection", wdyt?

It's "Screen Lock" on WhatsApp and "Passcode Lock" on Telegram.
"App Protection" feels too generic IMO.

**Comment by sampaiodiego** [comment]
As much generic as "Screen Lock" :)

The point is, we need to describe a little bit more what it does, regardless the name we chose.

**Comment by djorkaeffalexandre** [comment]
> As much generic as "Screen Lock" :)
> 
> The point is, we need to describe a little bit more what it does, regardless the name we chose.

@sampaiodiego WDYT?

Screen Shot 2020-05-05 at 17 09 44

**Comment by sampaiodiego** [comment]
> > As much generic as "Screen Lock" :)
> > The point is, we need to describe a little bit more what it does, regardless the name we chose.
> 
> @sampaiodiego WDYT?
> 
> Screen Shot 2020-05-05 at 17 09 44

looks good :D

**Comment by xmxax** [comment]
Hey there! 

Is there any way for an admin to reset someone's PIN? 

I have someone claiming the system never asked them to set one up so now they are locked out

**Comment by diegolmello** [comment]
@xmxax not really.
PIN is saved locally on the device.
Only way is by uninstalling the app and installing it again.

**Pull request merged**
