### PR TITLE
[FIX] Thread message gets cut when emoji is followed by mention

### LINKED ISSUE #20794: Thread message gets cut when emoji is followed by mention
### Description:
When a person is mentioned just after an emoji, the content of the message after the emoji gets cut in the thread message in the channel.

### Steps to reproduce:
See screenshot

### Expected behavior:
The message should be completely shown.

### Actual behavior:
Screenshot from 2021-02-17 18-34-24

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### PR DESCRIPTION
**Pull request by im-adithya**
## Proposed changes (including videos or screenshots)

The regex includes searching for `> ` before mentions so '>' in '> @mention' 
was also being selected which cuts the emoji's end tag (...</span'**>**' @mention....)
disturbing the message's content and hence the issue.

## Issue(s)

This PR closes #20794
## Now

Screenshot from 2021-02-17 18-44-28

### CODE REVIEW

**Comment by im-adithya** [comment]
@dougfabris Can you please review this? :)

**Review by ggazzo — CHANGES_REQUESTED** [review]
please provide some tests for this case, thanks

**Comment by dougfabris** [comment]
@im-adithya are you planning to continue your work on this one?

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Pull request closed without merging**
