### PR TITLE
fix: random emoji suggested in popup when user typed ':D'

### LINKED ISSUE #28844: Rocket.Chat turns :D into :england:
### Description:

When typing `:D`, a list of emojis will be suggested. Hitting enter will then select the first of these suggestions instead of submitting the message. In my case, the first emoji in the list is `:england:`.

### Steps to reproduce:

1. Type `:D`.
2. Hit enter.

### Expected behavior:

Instead of suggesting `:england:` and then selecting it, I would expect the message to be submitted.

In Rocket.Chat 5.4.3 (the most recent version before Rocket.Chat 6.0.0 was released), this was actually the case:

https://user-images.githubusercontent.com/404840/230746959-4aab09f9-d256-4407-89ab-77412d241b19.mp4

### Actual behavior:

`:D` gets replaced by `:england:`, something I never intended:

https://user-images.githubusercontent.com/404840/230746966-7432085e-6a8d-4b22-9daa-23feeffa9cb3.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.5

### Client Setup Information

- Browser Version:
  - Chromium Version 112.0.5615.49 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 111.0.1 (64-bit)
- Operating System: Arch Linux

### PR DESCRIPTION
**Pull request by jayesh-jain252**
## Proposed changes (including videos or screenshots)

When a user typed `:D` the Emoji Popup suggested random emojis

This modification prevents emoji suggestions from appearing when only `:` or a single character after `:` is typed, for example, `:D`. It ensures that emojis are suggested only when at least two characters are entered after `:`, aligning with user expectations and reduces distractions during emoji selection.

After:

Emojis are suggested only when the user types at least 2 characters after `:`.

[suggest_emoji_when_two_characters.webm](https://github.com/RocketChat/Rocket.Chat/assets/79307894/9d55ad47-1b7d-4556-a797-498797ae3214)

## Issue(s)

Closes #28844

### CODE REVIEW

**Comment by debdutdeb** [comment]
can we even avoid the preview that shows up after `:` ?

**Comment by debdutdeb** [comment]
@yash-rajpal we could merge and rebase right?

**Comment by debdutdeb** [comment]
We can merge it to your work branch, you can then make the necessary changes. That way we preserve the contribution in history instead of closing altogether.

**Comment by debdutdeb** [comment]
I changed the base 🙏🏼  please let me know if you have any concerns.

**Comment by yash-rajpal** [comment]
> @yash-rajpal we could merge and rebase right?

I don't see why we should do that, this is not the correct solution.

**Comment by debdutdeb** [comment]
This is a common practice in open source, sometimes a community patch might not be in line with ours, in such a case we should pick the commits at least to preserve the contribution as long as it is not too incorrect. Or would require too much work to modify to our standards.

**Comment by jayesh-jain252** [comment]
@debdutdeb The solution mentioned by @yash-rajpal is better than mine, as it is more as per the user's expectations as it considers that popup is not shown when a user types only `:` or `:D` whereas mine shows `No results found`.

But @yash-rajpal In the mentioned PR https://github.com/RocketChat/Rocket.Chat/pull/29282 (I am not sure if it's WIP) When I type `:D` and hit Enter it converts it to `:england:`

[random_emoji_when_hitting_enter.webm](https://github.com/RocketChat/Rocket.Chat/assets/79307894/711d162f-7dd6-4f52-9c29-894b4324a2eb)

Adding code from this pr will solve that

[send_on_enter_emoji.webm](https://github.com/RocketChat/Rocket.Chat/assets/79307894/8f84a047-04a4-44b3-9c9e-00461b5e8aa2)

**Pull request closed without merging**
