### PR TITLE
[BREAK] Remove support to MongoDB 3.2 and deprecate MongoDB 3.4

### PR DESCRIPTION
**Pull request by sampaiodiego**
Also add env var flags to bypass validations:

- `BYPASS_OPLOG_VALIDATION`
- `BYPASS_NODEJS_VALIDATION`
- `BYPASS_MONGO_VALIDATION`

Where do you guys think we can add those to our docs?

### CODE REVIEW

**Comment by reetp** [comment]
Damn :-(

**Comment by rodrigok** [comment]
@sampaiodiego shouldn't we title this as `Remove support to MongoDB 3.2 and deprecate 3.4`?

**Comment by sampaiodiego** [comment]
Agreed @rodrigok

**Comment by reetp** [comment]
Ahhh. Relief :-) A bit more time.

This may want a bit of thought as there is no simple leap from 3.4 -> 4.x

**Comment by sampaiodiego** [comment]
right @reetp .. you have to upgrade "step-by-step", that means from 3.2 to 3.4 and then 3.4 to 3.6 and so on

**Pull request merged**
