### PR TITLE
mobile notification fix

### LINKED ISSUE #4270: Mobile Push Channel Notification
My Rocket.Chat version: 0.39.0

Hi, I have some issue with the Mobile Push configuration and I think there is a bug.
In the Notification panel of a channel, when I choose other than "Mentions (Default)" for Desktop Notification, then the settings in "Mobile push" are not taken into account (the default one is used "Mentions (Default)" ).

I look really quickly at the code (I don't know javascript) but I think it makes sense with the code in packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js (second else-if should be an if ?)

``` javascript
	RocketChat.models.Subscriptions.findNotificationPreferencesByRoom(room._id).forEach(function(subscription) {
		if (subscription.desktopNotifications === 'all') {
			settings.alwaysNotifyDesktopUsers.push(subscription.u._id);
		} else if (subscription.desktopNotifications === 'nothing') {
			settings.dontNotifyDesktopUsers.push(subscription.u._id);
		} else if (subscription.mobilePushNotifications === 'all') {
			settings.alwaysNotifyMobileUsers.push(subscription.u._id);
		} else if (subscription.mobilePushNotifications === 'nothing') {
			settings.dontNotifyMobileUsers.push(subscription.u._id);
		}
		settings.desktopNotificationDurations[subscription.u._id] = subscription.desktopNotificationDuration;
	});
```

If you can take a look and see if there is really an error.

Thank you for your time,
Axel

### PR DESCRIPTION
**Pull request by MartinSchoeler**
@RocketChat/core 

Closes #4270

fixes the mobile notification preference not working

### CODE REVIEW

**Comment by rodrigok** [comment]
LGTM

**Comment by mmeinert** [comment]
I was hoping to have the fix included on 0.40.0 . I can't find sendNotificationsOnMessage.js on my system, how can I apply the correction myself ?

**Comment by geekgonecrazy** [comment]
@mmeinert this is definetely in 0.40.0 - https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js#L82

**Comment by mmeinert** [comment]
@geekgonecrazy you are perfectly right, my fault... Thank you for your explanation.

And it works ! Just need fine tuning of those push related to status (#1602) and it'll be perfect

**Pull request merged**
