### PR TITLE
[New] Add ConferenceCall api

### PR DESCRIPTION
**Pull request by geekgonecrazy**
@RocketChat/core 

Adds `RocketChat.conferenceCallProviders` api to allow add new conferenceCall providers
Changes jitsi meet integration to make use of this api

In its current state it would be pretty much a drop in replacement with no userfacing changes being made except for settings organization.

Todo:
- [ ] Change livechat that used Jitsi_Enabled to determine if could use video call

I'd like to leverage the room types and create a conference room type and instead of using the sidebar.  Basically the idea being that you can be in a conference call and move back and forth between channels.

The idea would be that you'd be able to do the following:
1. Start conference call from a channel.  Choose to "invite" everyone in the room or just post a link in a room for them to join.
2. New conference call shows up.
3. Clicking on it brings it up full screen in main area.
4. Clicking another channel reduces it up in an out of the way spot.

Maybe something like this:
image
or
image

### CODE REVIEW

**Comment by sampaiodiego** [comment]
Awesome!
Liked the small view at bottom, but maybe above instance logo.

**Comment by graywolf336** [comment]
The video in the top left kind of reminds me of Microsoft Teams :see_no_evil: but I like this idea!

**Comment by HammyHavoc** [comment]
Love the idea of moving it to the sidebar; makes sense having it at the top where the user info is for avatar, status etc; good UX. Having it at the bottom isn't so intuitive.

**Comment by geekgonecrazy** [comment]
Going to close this PR.  Too much has changed, I still would like to see a conference provider at some point though :)

**Pull request closed without merging**
