### PR TITLE
[FIX] Don't use global search by default

### LINKED ISSUE #20595: [BUG] Global search not turned off by default
### Description:

When global search is turned on the default behaviour **is** of global search which should **not** be the case as addressed [here](https://github.com/RocketChat/Rocket.Chat/pull/19777)

### Steps to reproduce:

1. Enable Global Search from Administration.
2. Click on search icon in a channel.
3. Search for any string without checking the global search checkbox.

### Expected behavior:

The search shouldn't be global since the global search checkbox is checked off initially.

### Actual behavior:

The search is a global search.

https://user-images.githubusercontent.com/28918901/106859375-f2fc5100-66e8-11eb-9889-d1041c007dc2.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-develop
- Operating System: Ubuntu 18.04 LTS
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chromium
- Operating System: Ubuntu 18.04 LTS

### PR DESCRIPTION
**Pull request by RonLek**
## Proposed changes (including videos or screenshots)

Disabling just the checkbox as done [here](https://github.com/RocketChat/Rocket.Chat/pull/19777) isn't the complete solution since even if the checkbox is disabled the `searchAll` property is set to `true` when the global search is enabled from the administration panel. 

An additional change to not use global search by default is to **not** set the `searchAll` property by default.

### After Fix

https://user-images.githubusercontent.com/28918901/106861508-dca3c480-66eb-11eb-81eb-cff739d4027c.mp4

## Issue(s)

Fixes #20595 

## Steps to test or reproduce

1. Enable Global Search from Administration.
2. Click on search icon in a channel.
3. Search for any string without checking the global search checkbox.

### CODE REVIEW

**Comment by RonLek** [comment]
@sampaiodiego could you please take a look. I believe this was due to an uncovered case in [this](https://github.com/RocketChat/Rocket.Chat/pull/19777)

**Comment by RonLek** [comment]
@sampaiodiego what do you think? Looks good?

**Comment by zenjabba** [comment]
Any chance this gets pushed as it's an annoying quirk.

**Comment by ankar84** [comment]
Waiting this PR to be merged almost a year now...

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Closing this PR because it's stale now and it was already fixed here: #25568

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Pull request closed without merging**
