### PR TITLE
[IMPROVE] Adding some search modifiers on the UI

### LINKED ISSUE #7859: Expose search term filters
In #4320 some amazing search filters were added, but users do not know they exist. As proposed then, something like this should be added to show users what the possible search features are:

image

### PR DESCRIPTION
**Pull request by madguy02**
Closes #7859 #4406

### CODE REVIEW

**Comment by madguy02** [comment]
@tassoevan any suggestions on the improvements on the PR

**Comment by tassoevan** [comment]
Besides the linter issues, UI need some work to match Rocket.Chat styling, based on the suggestions in #4406 and #7859:

captura de tela 2018-08-17 as 11 39 51

Also, maybe `mouseenter` is not the best event to trigger it, since we must consider mobile access and people how heavily use keyboard navigation over mouse.

**Comment by madguy02** [comment]
@tassoevan @ggazzo i have few changes regarding the styles and the returned data format, Please let me know if upto the standands of Rocket.Chat styling, also the changes that are required

**Comment by rodrigok** [comment]
We apologize for not getting a review on this sooner. At this point the PR is too out of sync to be able to accept.

I'll close this PR for now since we gonna rewrite this view in React soon

**Pull request closed without merging**
