### PR TITLE
[FIX] Change password doesn't work as expected 

### LINKED ISSUE #21857: Change password doesn't work as expected
### Description:

When a user tries to change its password in the preferences section, the password change happens even if the user doesn't confirm his new password which renders the second input for password confirmation useless.

### Steps to reproduce:

1. Go to **My Account**
2. Go to profile
3. Change your password without confirming it. 

### Expected behavior:

Password shouldn't change unless the user confirms it .

### Actual behavior:

Password changes rendering the confirm password input useless.

https://user-images.githubusercontent.com/69837339/116538519-460b2c00-a905-11eb-9c74-ddf7e176f03c.mov

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### PR DESCRIPTION
**Pull request by PriyaBihani**
- [x] I have read the Contributing Guide
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- I have added necessary documentation (if applicable)
- Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

Earlier user could change its password without confirming it, this PR resolves this issue.

Previously
Password could be changed without confirmation

Now

Password change can not happen without confirming the new password

## Issue(s)
Closes #21857

### CODE REVIEW

**Comment by PriyaBihani** [comment]
@KevLehman can you review :)

**Review by gabriellsh — CHANGES_REQUESTED** [review]
This works, but gives the user no visual feedback and can create confusion. You might want to take a look at the checks at `client/views/account/AccountProfileForm.js:93`. I think that's the real problem.

**Comment by PriyaBihani** [comment]
> This works, but gives the user no visual feedback and can create confusion. You might want to take a look at the checks at `client/views/account/AccountProfileForm.js:93`. I think that's the real problem.

Hey Gabriel, i've added some checks that gives a visual of what's happening, can you take a look :)

**Comment by PriyaBihani** [comment]
@gabriellsh can you review ?

**Pull request closed without merging**
