### PR TITLE
[NEW] Add setting to change User Agent of OEmbed calls

### PR DESCRIPTION
**Pull request by AhmetS**
In doing so, If we want to share a single page application, we can include requests from `rocketchatbot` in our server rules to redirect to something like prerender.io version of the page or our own pre-rendering server.

Example prerender.io config:

```
    <IfModule mod_proxy_http.c>
        RewriteCond %{HTTP_USER_AGENT} rocketchatbot|baiduspider|facebookexternalhit|twitterbot|rogerbot|linkedinbot|embedly|quora\ link\ preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator [NC,OR]
        RewriteCond %{QUERY_STRING} _escaped_fragment_
        
        # Only proxy the request to Prerender if it's a request for HTML
        RewriteRule ^(?!.*?(\.js|\.css|\.xml|\.less|\.png|\.jpg|\.jpeg|\.gif|\.pdf|\.doc|\.txt|\.ico|\.rss|\.zip|\.mp3|\.rar|\.exe|\.wmv|\.doc|\.avi|\.ppt|\.mpg|\.mpeg|\.tif|\.wav|\.mov|\.psd|\.ai|\.xls|\.mp4|\.m4a|\.swf|\.dat|\.dmg|\.iso|\.flv|\.m4v|\.torrent|\.ttf|\.woff))(.*) http://service.prerender.io/http://example.com/$2 [P,L]
    </IfModule>
```

@RocketChat/core 

Closes #ISSUE_NUMBER

### CODE REVIEW

**Comment by engelgabriel** [comment]
@AhmetS Can we turn this into a setting? Save this string into a setting that can be changed in the admin panel. What to you think @rodrigok

**Comment by AhmetS** [comment]
@engelgabriel @rodrigok - I dont see the benefit of turning this into a setting.

We could always append `rocketchatbot` to the existing user agent?

```
'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36 rocketchatbot'
```

**Comment by rodrigok** [comment]
IMO, a setting is always better.

**Comment by geekgonecrazy** [comment]
Agreed.  I think would be best to leave the server admin in control of that instead of forcing rocketchatbot on it.  Could effect the results some websites return, and in general cause issues with oembed functionality.  

@AhmetS would you be able to make this change to a setting?

**Pull request merged**
