### PR TITLE
[IMPROVE] Galician onboarding translation

### PR DESCRIPTION
**Pull request by Thiagof99**
## Proposed changes (including videos or screenshots)

I've translated the entire onboarding page and forms to galician language. Here's an example of how the forms look now:
image

### CODE REVIEW

**Comment by Thiagof99** [comment]
@rodrigok please review

**Comment by Thiagof99** [comment]
@sampaiodiego please review

**Comment by Thiagof99** [comment]
@engelgabriel please review

**Comment by Thiagof99** [comment]
@ggazzo please review

**Comment by Thiagof99** [comment]
@hugocostadev please review

**Comment by Thiagof99** [comment]
@dudanogueira please review

**Comment by hugocostadev** [comment]
I'll address internally!  Thanks a lot for your contribution

**Review by hugocostadev — APPROVED** [review]

**Pull request merged**
