### PR TITLE
[FIX] Change "Idle Time Limit" from milliseconds to seconds

### LINKED ISSUE #9674: Idle Timeout doesn't have any units
https://github.com/RocketChat/Rocket.Chat/blob/2c65f2b0342300298073d0b831fdff6870d7dc9d/client/startup/startup.js#L94

Here it's just a number, without any indication of units. Same for the user interface, where the placeholder mentions a default of 300000. My guess is that it's in milliseconds, but that's just a guess. If so, maybe it would be better to change the units in the UI to seconds or minutes? Having an idle timeout down to the millisecond precision has IMO little practical value.

### PR DESCRIPTION
**Pull request by kaiiiiiiiii**
@RocketChat/core 

Closes #9674

This PR changes the Idle Time Limit from milliseconds to seconds. Let me know if I missed something!

screen shot 2018-02-11 at 03 55 11

### CODE REVIEW

**Comment by 0x0000007** [comment]
@RocketChat/core

I think we need something to convert saved user settings to minutes. My Idea would be something like this:

We set a maximum of 1440 minutes (24 hours) and check if the currently saved value is bigger than that. If so, we devide it by 60000 and round it up to next bigger value?

**Comment by geekgonecrazy** [comment]
Could you please explain why you want to make this higher?

Typically people actually want to decrease this and not increase.

If you set to 24 hours you could be away from your computer a whole day before your status goes to away.  This seems like defeats purpose

**Comment by 0x0000007** [comment]
I don’t want to set 1440 as a default, but the problem I see is the following: When we change the idle time limit from milliseconds to minutes (which definitely makes sense) some users might still have saved user preferences with the millisecond value (default 300000). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jszaszvari** [comment]
@geekgonecrazy I think the outcome needed here is maybe a migration/ conversion of the current millisecond value that would be set on most instances Into minutes ?

**Comment by 0x0000007** [comment]
That’s what I’m tried to say with my first comment ^^’

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by geekgonecrazy** [comment]
you'd have to pretty much run a migration on to convert from milliseconds to minutes.

But what happens if I actually prefer idle time to be 30 seconds?

If its in minutes it makes it more complicated.

**Comment by jszaszvari** [comment]
Maybe do it in seconds. Or I suppose 30 seconds would be specified as 0.5 mins

**Comment by jszaszvari** [comment]
Seconds would probably be the better option though

**Comment by kaiiiiiiiii** [comment]
Ok, I’m gonna change that later.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kaiiiiiiiii** [comment]
@geekgonecrazy Can you may take a look at my last commit and tell me if it's the right way to do a DB migration?

**Comment by geekgonecrazy** [comment]
I think everything looks right.

@sampaiodiego could you give a look and make sure looks good?  I think you are more familiar with the idle code.

**Comment by kaiiiiiiiii** [comment]
@sampaiodiego Any chance to get this in to the next release? Most of my users are really confused with the millisecond value.

**Comment by sampaiodiego** [comment]
I'm sorry @kaiiiiiiiii we'll need to target version `0.63.0` since the feature set for `0.62.0` is already closed

**Comment by kaiiiiiiiii** [comment]
Done :)

**Comment by kaiiiiiiiii** [comment]
Closed in favor of #9824 .

**Pull request closed without merging**
