### PR TITLE
[FIX] Create Custom OAuth services from environment variables

### LINKED ISSUE #10420: Custom OAuth config not created even if all env vars are set
### Description:
Installing Rocket Chat with a Helm chart, I'm specifying all the required variables to configure a custom OAuth provider as environment variables. E.g. I create env vars called:
```
  Accounts_OAuth_Custom-Keycloak: true
  Accounts_OAuth_Custom-Keycloak-url: https://example.com/auth
  ...
```
When I log into the Rocket Chat, no custom OAuth provider called `Keycloak` has been created. But if I create one called `Keycloak`, it populates all the fields from the env vars I supplied. This is preventing me automating the deployment of Rocket Chat with Helm.

### Server Setup Information:

* Version of Rocket.Chat Server: rocket.chat:0.62.2 (docker hub image)
* Operating System: N/A (kubernetes)
* Deployment Method(snap/docker/tar/etc): helm
* Number of Running Instances: 1
* DB Replicaset Oplog: n/a
* Node Version: unknown
* mongoDB Version: mongodb:0.4.15 (docker hub image)

### Steps to Reproduce:

1. Clone https://github.com/kubernetes/charts/tree/master/stable/rocketchat, and add the following to values.yaml:
```
config:
  Accounts_OAuth_Custom-Keycloak: true
  Accounts_OAuth_Custom-Keycloak-url: https://example.com/my-auth
  Accounts_OAuth_Custom-Keycloak-token_sent_via: Header
```
2. Install with helm
3. Log in as an admin. Go to Administration -> oauth. No custom provider called `Keycloak` will exist. 
4. Create a custom provider and call it `Keycloak`. The values will be populated from the above config values.

### Expected behavior:
Rocket chat should notice that env vars for the custom provider exist and should create the custom provider automatically.

### Actual behavior:
The custom provider needs to be created manually, but then it loads values supplied as env vars.

### PR DESCRIPTION
**Pull request by mrtndwrd**
Closes #10420 

This PR adds a function `customOAuthServicesInit()` that checks if there are environment variables set for custom OAuth services. If they are set, they get added to the settings.

Without this function, these environment variables are only parsed and added to settings *after* the custom OAuth service is created through the administration interface.

I currently call this function in the `oAuthServicesUpdate.js` file. I'm not sure if this is the best way to call a start-up function. All suggestions for improvement are more than welcome!

### CODE REVIEW

**Comment by mrtndwrd** [comment]
It seems the build-image-pr test failed due to something I didn't change. Is there anything I can do to fix this, or maybe retrigger the build?

**Comment by varac** [comment]
Dear Rocket.Chat devs, can anybody please review ? This is a very needed and useful feature.

**Comment by mrtndwrd** [comment]
@engelgabriel I have the feeling this PR might have slipped through the cracks. I would really like to have it reviewed and merged, because now I'm maintaining a fork of Rocket.Chat. As can be seen in #10420 I'm also not the only one that runs into the problem that this PR solves.

Is there anything I can do to help you start or speed up the review process? Thank you!

**Comment by varac** [comment]
Ping

**Comment by mrtndwrd** [comment]
@sampaiodiego you seemed to have an interest in #10420 (you put it on the todo list). Is there anything I can do to help speed up the review process a bit?

**Comment by sampaiodiego** [comment]
thanks @mrtndwrd .. I'll ask @pierre-lehnen-rc to review it for next release 👍

**Review by pierre-lehnen-rc — APPROVED** [review]

**Comment by mrtndwrd** [comment]
Thank you for merging!

**Comment by geekgonecrazy** [comment]
@mrtndwrd did you manage to actually use this? I'm fighting with every shell I try with rejecting environment variables with a `-` in them.

**Comment by mrtndwrd** [comment]
You're right, I can't think of a shell that will allow dashes in the environment variable name.

I can tell you that this *does* work if you install rocket.chat with the [helm chart](https://github.com/helm/charts/tree/master/stable/rocketchat). You need to set the `extraEnv` variable to set the variables used here. I can imagine you can do something similar with Docker or Docker-compose, but I haven't tried.

The way I use it is a bit complicated, but it boils down to that this is the helm values file we use: https://open.greenhost.net/openappstack/openappstack/-/blob/master/ansible/roles/apps/templates/settings/rocketchat.yaml (templated by ansible, don't ask me why :sweat_smile:)

**Pull request merged**
