### PR TITLE
[NEW] Feature/livechat hide email

### LINKED ISSUE #6612: [Feature Request] Posibility to hide email in LiveChat
Rocket.Chat Version: 0.52.0

Often times you do not want customers to write directly to people, but rather to the support mail. Later versions of Rocket.Chat shows your email in LiveChat to Guests. We need an option to hide the email.

### PR DESCRIPTION
**Pull request by icosamuel**
@RocketChat/core 
@RocketChat/livechat
Closes #6612 

New `Livechat_show_agent_email` config in the livechat tab of the web administration page as well as the Livechat management page, translated in en and fr.

The emails are not loaded from the database when we query for agent data, so they are never sent to the client.

### CODE REVIEW

**Comment by icosamuel** [comment]
I've got a small problem with labels not being replaced by i18n content

The strange thing is it worked inconsistently in between builds, but I believe I did not make any change to those lines that would break the desired behavior. Am i missing something obvious? 

I'm starting to believe the i18n package isn't properly rebuilt on my machine

**Comment by RichGriese** [comment]
I just set up a Beta Rocket & am playing with LiveChat. In testing the operator email is showing. Is it too new to see this fix/mod in the beta, or is there some other issue? Cheers!

**Comment by icosamuel** [comment]
Hey @RichGriese! glad to see youre interested in this feature as well!

Unfortunately, I don't think we will see this in the next few releases, since it's going into the 0.60 feature bag, and the rocketchat pipeline is still making release candidates for 0.59

What I personally do to cherry pick the features that are not out yet, is to keep my own version of the project. If you have the resources, you can build the project after integrating this branch, or just build the project on [my develop branch](https://github.com/icosamuel/Rocket.Chat) ;) 

Hope this helps, I cant wait to get this feature out in the open!

**Comment by icosamuel** [comment]
@sampaiodiego I realize that this is a minor feature, and that you might have a lot of different priorities.
With that said, may I request a review? I consider my work done and would like to close this PR.
Thanks for your time and help :)

**Comment by sampaiodiego** [comment]
hi @icosamuel .. thank you very much for another contribution.

indeed it was a minor feature I was able to test between other tasks. =)

so far it looks good, but I noticed it is still sending agent's email over the wire (but correctly not showing it depending on the setting). what you think on preventing the email field to be sent to the client instead of just not showing it? TIA

**Comment by alexweissman** [comment]
It would be ideal avoid sending the agent's email over the wire, but simply hiding it for now would be acceptable for the sake of getting this patched into the next release.  It's a fairly significant privacy issue, especially for those of us with agents who didn't know that their email address would become public information in the context of livechat.

**Comment by icosamuel** [comment]
sure, now that I'm more comfortable with the project, I can more easily change it's behavior to be on the server side. 

It'll take some time though, as the requirements are kind of met on our side, so my time mostly goes on other tasks :/

**Comment by alexweissman** [comment]
@icosamuel the great tragedy of open source 😛

**Comment by icosamuel** [comment]
Finally, I've found some time to sort this issue out! As of now, the emails do not even get out of the database if the setting is active.

This approach leaves us with much simpler changes and an elegant solution which does not even involve the Livechat client!

**Pull request merged**
