### PR TITLE
[FIX] Update "Deploy with docker compose" link

### PR DESCRIPTION
**Pull request by arnydo**
Received a 404. Noticed documentation was moved.
Updated link to reflect.

@RocketChat/core 

2017-10-20 09_52_52-page not found github pages - nightly

### CODE REVIEW

**Comment by cyclops24** [comment]
@arnydo so many link also have same problem. Can you extend your PR to fix all of that?

**Comment by gabsprates** [comment]
well... i fix that on #8532

**Comment by arnydo** [comment]
@cyclops24 Sure thing. I will go through all of the links and correct what I find.
Thanks for the update @gabsprates. Looks like you beat me to it then.

**Comment by geekgonecrazy** [comment]
Ah looks like another PR got merged with this fix.  Thanks for contributing though!

**Pull request closed without merging**
