### PR TITLE
[FIX] Default Attachments - Show Full Attachment.Text with Markdown

### LINKED ISSUE #20560: Jira notifications via WebHook - Layout broken
### Description:
After updating from Rocket.Chat 3.10.4 -> 3.11.0 the layout of incoming messages sent via JIRA Webhooks is broken / not useful.

### Steps to reproduce:
1. Create Incoming Webhook ( see https://docs.rocket.chat/guides/administrator-guides/integrations/jira )
2. Create / Update JIRA Task
3. Read Rocketchat message

### Expected behavior:
Get a functional designed message with text and clickable links to the JIRA ticket.

### Actual behavior:
Get a message only containing the `*ACTION*[TICKET-ID](URL...`
To note here the URL is ending with "..." therefore not refered to as clickable URL in the chatwindow

jira_webhook

### Server Setup Information:
- Version of Rocket.Chat Server: 3.11.0
- Operating System: Debian 9.13
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled
- NodeJS Version: 3.6.21
- MongoDB Version: v12.20.1

### Client Setup Information
- Desktop App or Browser Version: all
- Operating System: all

### Additional context
The [jira-rocketchat-hook.js](https://github.com/malko/rocketchat-jira-hook/blob/master/jira-rocketchat-hook.js) worked fine for years.

### Relevant logs:
-

### PR DESCRIPTION
**Pull request by aditya-mitra**
## Proposed changes (including videos or screenshots)

Removed truncating of text in `Attachment.Text`. 
Added `Attachment.Text` to be parsed to markdown by default.

### Earlier
earlier

### Now

now

## Issue(s)

Closes #20560 

## Steps to test or reproduce

[#20560 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/20560#issuecomment-773190476) shows the bug which can be reproduced by using the `cURL` command if you already have a bot with the correct credentials.

Otherwise you can use this way to reproduce the message, (I have used a bot for that):
1. On the terminal, do `git clone https://github.com/aditya-mitra/rocketchatbot.git  && cd rocketchatbot && git checkout reproducing-issue-md && npm install` (this will clone the repo and install dependencies)
2. Add [this bot with these username and password](https://github.com/aditya-mitra/rocketchatbot/blob/reproducing-issue-md/src/index.ts) to the **list of users**. (For reference, you can see this - https://www.freecodecamp.org/news/how-to-build-a-rocketchat-bot-with-typescript/#how-to-set-up-a-bot-account-in-rocket-chat)
3. Now in the terminal *where you cloned the repo for the bot*, do `npm start`.
4. You will get a message in the **general channel** of your running instance.

### CODE REVIEW

**Comment by fdellwing** [comment]
Unrelated to the PR, you do not need to setup an own bot. RC comes with the `rocket.cat` bot on board.

**Comment by aditya-mitra** [comment]
Thanks for pointing that out :D
I guess that will be easier setup.

**Comment by fdellwing** [comment]
I'll try to test this tomorrow. It's a bit complicated in our 3 instances docker-compose setup, but should work.

**Comment by yash-rajpal** [comment]
LGTM.

**Comment by fdellwing** [comment]
Seems to fix the issue 👍

**Comment by danielpotthast** [comment]
Why isn't this fix already merged in 3.11.1?

**Review by ggazzo — APPROVED** [review]

**Comment by Exordian** [comment]
Emojis and linebreaks are still broken. Yet, Markdown and full size work fine again

**Pull request merged**
