### PR TITLE
[IMPROVEMENT]  Take attachment comments into account when message searching

### LINKED ISSUE #11584: [IMPROVEMENT] Take attachment comments into account when message searching
Currently, when you upload a file you can't find it by searching messages.

### PR DESCRIPTION
**Pull request by madguy02**
Closes #11584 

This PR tackles the issue to be able to search by file comments using desc:<file comment name>. This PR also includes a fix to the label:<file title>

### CODE REVIEW

**Comment by madguy02** [comment]
@Hudell let me know if changes are required.

**Comment by madguy02** [comment]
@Hudell  Reverted the commits( for the Search modifier UI) will open a new PR

**Comment by madguy02** [comment]
@rodrigok i have added the requested changes, please review it once

**Comment by rodrigok** [comment]
We apologize for not getting a review on this sooner. 

Closed by https://github.com/RocketChat/Rocket.Chat/pull/16858

**Pull request closed without merging**
