### PR TITLE
[FIX] Client breaks when trying to deactivate a user who's the last owner of one or more room[s]

### PR DESCRIPTION
**Pull request by debdutdeb**
## Issue(s)

#25155

### CODE REVIEW

**Comment by debdutdeb** [comment]
Ftr I don't know if it's deja vu or not, but i could swear I saw a similar patch a while ago. Or maybe it was in a different section altogether.

**Comment by ankar84** [comment]
> Ftr I don't know if it's deja vu or not, but i could swear I saw a similar patch a while ago. Or maybe it was in a different section altogether.

Actually I have the same filling!

**Comment by ankar84** [comment]
@debdutdeb what do you think that fix could be included in some patch version like 4.6.2?

**Comment by sidmohanty11** [comment]
@debdutdeb I think you saw it here #24933 :)

**Comment by debdutdeb** [comment]
Ahhhh yes! Thanks @sidmohanty11 ! I'm closing this one in favor of that.

**Pull request closed without merging**
