### PR TITLE
Fixes[UI] added users were added to popup list 

### PR DESCRIPTION
**Pull request by sudipt1999**
Earlier if user is present in room also then also he was shown in pop list of add users in channel!

Screenshot from 2019-04-01 00-48-24

this small change fixed it !

### CODE REVIEW

**Comment by sudipt1999** [comment]
issue

This was the issue user was able to be added because it was shown in popup list of invite user

**Comment by sudipt1999** [comment]
@tassoevan kindly please have a look at this, opened from a long time.

**Comment by ggazzo** [comment]
hi @sudipt1999 thanks for your PR, I have to say that your code its perfect, but we have a problem with `getUsersOfRoom` method, so I will put your pr as waiting until we fix it ;)

**Comment by rodrigok** [comment]
This fix does not fix the issue #2194

**Comment by engelgabriel** [comment]
The implementation is not correct. If we want to filter out existing members, we need to do this on the server API level, and not on the client level.

**Pull request closed without merging**
