### PR TITLE
[FIX] Add missing custom fields to apps' users converter

### PR DESCRIPTION
**Pull request by cuonghuunguyen**
## Proposed changes (including videos or screenshots)
Add missing `customFields` mapping for the app users converter.

### CODE REVIEW

**Comment by JargeZ** [comment]
These fields have been lacking for a long time 🥺

**Review by JargeZ — APPROVED** [review]
I tested this as a local patch. Works properly.
Any thought about accepting this PR?

**Comment by kierenevans** [comment]
Hi!

This appears to fix the issue I've been encountering and also what the forum members at https://forums.rocket.chat/t/accessing-senders-custom-fields-inside-islashcommands-executor/9715/5 encountered.

Is there any progress to getting this merged?

Thanks

**Comment by cuonghuunguyen** [comment]
@d-gubert hi, could u help me to merge this?

**Review by d-gubert — APPROVED** [review]

**Pull request merged**
