### PR TITLE
[NEW] Threads V 1.0

### PR DESCRIPTION
**Pull request by ggazzo**
Based on https://github.com/RocketChat/Rocket.Chat/pull/13394

Closes https://github.com/RocketChat/Rocket.Chat/issues/6888
Closes https://github.com/RocketChat/Rocket.Chat/issues/13843
Closes https://github.com/RocketChat/Rocket.Chat/issues/1112

Coauthored with @khaledalyawad and @mrsimpson 

compressed reply message

### CODE REVIEW

**Comment by zdumitru** [comment]
Thanks for enormous work. @ggazzo Is there a way to have it added to milestone (release) `1.0.0`?

**Comment by sampaiodiego** [comment]
we're working hard for that @zdumitru  :sweat_smile: I'll add the milestone to reflect that

**Comment by mrsimpson** [comment]
@ggazzo Just tested the branch. Once I understood it being "only" an optional grouping of related messages in the parent channel in a side panel, I actually liked it. 
At first, I was irritated by all messages of the threads also appearing in the parent channel. However, this makes notifications compatible with the current mechanism - and the replies are not much better organized. Well done. :+1:

The mechanism relies on users always utilizing the "reply" action. Since it's hidden in the context menu, I doubt this will always be used. Also, there's only one message input and even when reading a thread and typing a reply, it's by default a message in the parent channel => I believe UX has to be improved here. Suggestions for making usage of "reply" more convenient:

- At least once a thread has been started, provide an always one-click-reachable button at each message of the thread. Maybe next to the emoticon-icon. I'm not the UX-guy, you probably come up with something better...
- If a thread panel has been opened (you're reading the thread) => Writing a message in this state probably replies to the thread opened. => the default when entering the message input should be that a reply to the last message of the thread is being created. If you use the standard reply-message-preview, the user can still decide not to reply to the thread. 
- At the end of the thread preview in the side panel should be an explicit, "huge" reply-button which then sets the focus to the message input 

Moreover, I noticed the "discussion" button also exists for replies.
As long as this does not trigger a conversion (see #14016), I'd hide this from the menu. It only creates confusion if the same stuff is discussed in two places. 

Once remark: I really like the way it works. However, I was relunctant to call it "threads". I'd prefer "smart replies" or something similar. With the word **"thread" I associate the threaded messages not to appear in the parent channel**. 
So unless you plan to somewhat "compress" the tread display in the parent channel, you may think about a different marketing to set user expectations more towards what the implementation delivers.

**Comment by engelgabriel** [comment]
@mrsimpson 

You are too fast!! heheheh

Yes, we will give it a try to "compress" the tread display in the parent channel, turning it into a single line, with the small avatar version, like when you use RC in compress mode.

We were already working on the message box for the thread area, it is now live.

I am also uneasy with the work THREAD being the main word, I think we should use the wording in a way that REPLY is the main word, and even the ICON should be the REPLY icon all the time, and remove this THREAD icon altogether.

Please join us at https://threads-qa.rocket.chat to test the latest version of threads

**Comment by khaledalyawad** [comment]
this is awesome!, testing now!

**Comment by engelgabriel** [comment]
Screenshot 2019-04-07 at 03 31 03

**Comment by engelgabriel** [comment]
compressed reply message

**Comment by rodrigok** [comment]
@ggazzo we need to test this with one App installed and see if the app engine will not remove the new properties

**Comment by Korben3** [comment]
Hi, where is the toggle to turn of threaded replies? It's a nice feature but tastes differ, so is it possible to turn it off?

**Comment by mrsimpson** [comment]
>Hi, where is the toggle to turn of threaded replies? It's a nice feature but tastes differ, so is it possible to turn it off?

@Korben3 as far as I recall it’s in the admin settings, section „threads“

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Korben3** [comment]
Thanks, seems like the docs on rocket.chat/docs hasn't been updated yet.

**Comment by Korben3** [comment]
@mrsimpson do you have an image of where to find this? It's for someone else that has rocket chat installed.

**Comment by yaxu** [comment]
Is there somewhere to discuss the threading UI? We've tried it for a while and the consensus is that it makes channels more difficult to read. For example:

image

The font is too small and the interleaving of threads makes it difficult to follow any of the discussion.

**Comment by khaledalyawad** [comment]
I think if we avoid/minimize posting notifications on the main thread this will make it cleaner. We can have a dedicated view to let users notified on what is new on the threads/discussions they are following

**Comment by zdumitru** [comment]
Not forcing thread replies being sent to the main channel will make things look cleaner. [There is a feature request for that](https://github.com/RocketChat/feature-requests/issues/117). You can upvote it.

**Pull request merged**
