### PR TITLE
[FIX] Fix and improve Atlassian Crowd User Sync

### PR DESCRIPTION
**Pull request by kos4live**
Before the sync was running into a exception of "Cannot read property 'crowdClient' of undefined" and was running on all instances redundant.
Now the described issue was fixed and used SyncedCron with configurable sync interval.

### CODE REVIEW

**Comment by piotrkochan** [comment]
could you get rid of this plain password saved in user document?

**Comment by steerben** [comment]
Nice to see, that it progresses @engelgabriel

**Comment by Hudell** [comment]
It seems like a good part of this pull request is already implemented on our `develop` branch now. @kos4live I'm sorry it took us so long to check this, but do you mind comparing your changes to the ones that were merged and check if there's anything missing?

**Comment by rodrigok** [comment]
@Hudell can you check what is different from our new changes and see if it makes sense?

**Comment by rodrigok** [comment]
@Hudell ping, can you check this?

**Comment by Hudell** [comment]
I compared the PR with the existing implementation and with the only exception of a try catch being handled in a different place, it's pretty much the same code.

I'll be closing this one now.

**Pull request closed without merging**
