### PR TITLE
[FIX] Double output of message actions

### PR DESCRIPTION
**Pull request by timkinnane**
Actions markup is output twice, in immediate succession: 
https://github.com/RocketChat/Rocket.Chat/blob/135c6f8e1bb204cd7b07682dec8e189144fe3871/packages/rocketchat-message-attachments/client/messageAttachment.html#L152-L162

@ubarsaiyan and @ggazzo - Please review and get this merged asap. Did no one even look at this feature before it got merged?

### CODE REVIEW

**Comment by ubarsaiyan** [comment]
@timkinanne I noticed it when it was deployed and sent a PR asap but got no response. https://github.com/RocketChat/Rocket.Chat/pull/11853

**Comment by timkinnane** [comment]
Right. Thanks @ubarsaiyan I searched issues for "actions" but not buttons. Better to be specific, there's a lot of buttons in Rocket.Chat.

**Comment by ubarsaiyan** [comment]
@timkinnane Sorry, I thought this would be merged quickly so didn't give much thought in the title. I will keep this is in mind from now onwards. :)

**Comment by timkinnane** [comment]
@ubarsaiyan was your PR merged? Can I close this?

**Pull request merged**
