### PR TITLE
[FIX] Adds css styling to the cmsPage.html

### LINKED ISSUE #13577: Default styles for Terms of Service and Privacy Policy are hideous
### Description:

The default styles for Terms of Service and Privacy Policy are hideous.

### Steps to reproduce:

1. Add a few `<p>` and `<h1>` tags to the Privacy Policy or Terms of Service (Layouts->Content).
2. Open the Privacy Policy or Terms of Service links form the login page.

### Expected behavior:

Should look at least decent.

### Actual behavior:

Looks terrible (see screenshot below).

rocket_chat_pp

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.2
- Operating System: Ubuntu 18.04 (4.4.0-141-generic)
- Deployment Method: snap
- Number of Running Instances: 1 
- DB Replicaset Oplog: Enabled?
- NodeJS Version: v8.11.3
- MongoDB Version: 3.2.7?

### PR DESCRIPTION
**Pull request by fliptrail**
Makes the Terms of Condition page and the Privacy Policy page more attractive to the user.

Closes #13577 

Initial State:
imported

Final State: 

Updated the CSS styling like this so that headings and text are clearly visible. Also added margins and padding to the whole container.
screenshot from 2019-03-07 20-58-06

### CODE REVIEW

**Comment by codekhal** [comment]
It Looks decent but you could add more space between the last 2 lines and improve a bit of styling so issue hopefully would be closed. Though, it's just my opinion.
Cheers :)

**Comment by fliptrail** [comment]
Problem with that is that the text coming from server is not marked up properly. There's a brute force method. Will try to use it.

**Comment by fliptrail** [comment]
Added more commits and improved the final status

**Comment by fliptrail** [comment]
Please review this PR

**Comment by fliptrail** [comment]
@tassoevan @wreiske Please review this.

**Comment by ggazzo** [comment]
@fliptrail sorry but you deleted your branch I cant push any fix, and I dont think its good enough... sorry...

**Comment by fliptrail** [comment]
I will try again better next time. Actually this was one of my first PR's on this repo and I was actually trying to understand the repo structure.

**Pull request closed without merging**
