### PR TITLE
/leave /part added

### PR DESCRIPTION
**Pull request by geekgonecrazy**
/leave and /part

### CODE REVIEW

**Comment by rodrigok** [comment]
@geekgonecrazy take a look at my fixes of /invite and my PR https://github.com/RocketChat/Rocket.Chat/pull/654 that add more things to slashCommand

**Comment by rodrigok** [comment]
Hei @geekgonecrazy, do you need some help with this PR? :smile:

**Comment by geekgonecrazy** [comment]
I started on the kick using runAs then having them gracefully leave the
room.  But then started down the path of actually making a kick method.

If you want to apply your ninja skills I won't complain lol

**Comment by rodrigok** [comment]
Np, just curious. You will add this method to this PR?

**Comment by geekgonecrazy** [comment]
I think i'll quickly pull kick out in the morning and do it in a completely separate pull request.  That way the code will be easier to review.  Plus gives me a bit more time to do the kick method.

**Pull request closed without merging**
