### PR TITLE
fix: Automate text direction based on the language in messages

### LINKED ISSUE #29365: Text Direction Issue: Message Boxes Do Not Handle Mixed RTL and LTR Text Correctly
### Description:

There is an issue with the text direction in message boxes. Currently, all messages are treated as LTR, even when they contain mixed RTL and LTR text. This affects the readability and formatting of text, especially for languages that require RTL orientation. 

In addition to that, the `dir="rtl"` attribute is not added to any `div` with `data-qa-type="message-body"`.

### Steps to reproduce:

1. Log into Rocket.Chat and navigate to a chat room.
2. Send a message with mixed RTL and LTR text.
3. Observe the text orientation of the message in the chatbox.

### Expected behavior:

The message box should adapt the text direction (`dir="auto"`) based on the content of the message. The `dir="rtl"` attribute should be added to any `div` with `data-qa-type="message-body"`.

### Actual behavior:

The message box treats all text as LTR, regardless of the actual content. The `dir="rtl"` attribute is not present in `div` elements with `data-qa-type="message-body"`.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

This issue affects the readability and comprehension of the chat messages, especially in languages that require RTL orientation. This is a significant concern for the inclusivity and usability of Rocket.Chat.

### Relevant logs:

```markdown
<!-- Sample code to illustrate the problem block -->
<div class="message-box" data-qa-type="message-body">
    Mixed RTL and LTR text content goes here...
</div>
```

### PR DESCRIPTION
**Pull request by anefzaoui**
## Proposed changes (including videos or screenshots)

This pull request resolves the issue [#29365](https://github.com/RocketChat/Rocket.Chat/issues/29365). It ensures that the `dir` attribute for message boxes is set to "auto", and `dir="auto"` attribute is added to any `div` with `data-qa-type="message-body"`. This ensures proper handling of text direction for languages that require RTL orientation.

## Issue(s)

Fixes #29365

## Steps to test or reproduce

Please follow the steps outlined in the issue to test the changes.

## Further comments

This change ensures that the Rocket.Chat application correctly handles the text direction for languages that require RTL orientation, improving overall accessibility and usability. I'm not so sure about the correct tests to cover this?

### CODE REVIEW

**Comment by anefzaoui** [comment]
Can someone please look at this? This is fairly simple although I'm not sure how to get this to RocketChat's attention? Cc @juliajforesti :)

**Comment by anefzaoui** [comment]
Can someone please look at this? We really need it
@rodrigok @sampaiodiego @engelgabriel @ggazzo @marceloschmidt @MartinSchoeler
Thank you!

**Comment by dougfabris** [comment]
@anefzaoui Thanks for the contribution, I'm going to take a look asap!

**Comment by anefzaoui** [comment]
Hi @dougfabris 

The dir="auto" attribute is essential for handling mixed language content. It's not about *UI design* or *text alignment* per se, instead, it ensures that words in a sentence with both Left-to-Right (LTR like English, French) and Right-to-Left (RTL like Arabic and Hebrew) languages are displayed in their correct order. This attribute lets the browser automatically decide the text direction based on the content, maintaining readability regardless of the overall UI language.

### Pain points when using a forced or inherited `dir`

1. **Mixed Language Sentence (Forced LTR)**
   - Scenario: A sentence that combines English (LTR) and Arabic (RTL) words, but the container is forced to LTR.
   - Example: `<div dir="ltr">This is a test مرحبا بكم</div>`
   - Issue: The Arabic phrase "مرحبا بكم" (meaning "Welcome") will be displayed in a left-to-right order, disrupting the natural reading flow. The words get jumbled, making the sentence confusing and difficult to read.

2. **Inherited Directionality**
   - Scenario: A nested element containing Arabic text inherits the LTR direction from its parent.
   - Example: 
     ```html
     <div dir="ltr">
       Welcome to our site
       <span>مرحبا بكم</span>
     </div>
     ```
   - Issue: The Arabic phrase, being in an LTR context due to inheritance, will not display correctly. The phrase will be rendered in reverse, leading to a nonsensical and hard-to-read text.

### Correct behavior when using `dir="auto"`

- **Mixed Language Content**
  - Scenario: A sentence that mixes English and Arabic words.
  - Example: `<div dir="auto">This is a test مرحبا بكم</div>`
  - Benefit: With `dir="auto"`, the browser automatically detects and applies the correct direction for each part of the sentence. English is displayed LTR, and Arabic is displayed RTL. This ensures that both parts of the sentence are easy to read and appear in their natural order, regardless of the surrounding text or UI direction.

Using `dir="auto"` addresses these pain points by allowing each language segment to be displayed in its natural reading direction, significantly improving the user experience in multilingual environments.

I hope this answered your question with as much details as possible. I was the developer responsible for implementing proper RTL UIs in the now-deprecated "Mozilla's Firefox OS" project, if you need to schedule a call or a proper discussion board to explain this further just let me know.

Thanks!

**Comment by dougfabris** [comment]
@anefzaoui Thank you so much for your explanation, I will share the content you bring to us with the design team and will think about how we can add some tests in the PR and guarantee the issue doesn't happen in future changes

**Comment by dougfabris** [comment]
@anefzaoui In a discussion with the team we thought we should add this rule for our message composer and our text inputs as well, what do you think? There are other places we should have this rule in your opinion besides the messages?

**Comment by anefzaoui** [comment]
> @anefzaoui Thank you so much for your explanation, I will share the content you bring to us with the design team and will think about how we can add some tests in the PR and guarantee the issue doesn't happen in future changes

Thanks!

> @anefzaoui In a discussion with the team we thought we should add this rule for our message composer and our text inputs as well, what do you think? There are other places we should have this rule in your opinion besides the messages?

Basically this is needed in any place where a user needs to type something & anywhere where users are expected to input text, since the user can type and combination of words.

**Review by dougfabris — APPROVED** [review]
Alright, as your PR is targeted to messages, let's merge it. Feel free to help us fix the missing places, but I will share this need with the team as well. Thanks a lot!

**Comment by anefzaoui** [comment]
@dougfabris thanks!! Will do, however is there like a chat server for volunteers or a proper way to notify and recommend such features? if such is available then discussions can be much more detailed and clear than in the comments.

**Comment by dougfabris** [comment]
@anefzaoui You can join us on the [Open Server](https://open.rocket.chat/), in the #support channel you can raise a question if needed, also we do have a [Community Forum](https://forums.rocket.chat/) where you can search/create a post. For feature request we do have a [repository](https://github.com/RocketChat/feature-requests) for it.

**Pull request merged**
