### PR TITLE
[FIX] Formal pronouns and some small mistakes in German texts

### PR DESCRIPTION
**Pull request by AmShaegar13**
@RocketChat/core 

I fixed mostly formal German pronouns. See http://germanforenglishspeakers.com/pronouns/personal-possessive-pronouns/

### CODE REVIEW

**Comment by rodrigok** [comment]
@AmShaegar13 could you fix he conflicts?

**Comment by AmShaegar13** [comment]
@rodrigok fixed. Didn't know this one was still open.

**Comment by AmShaegar13** [comment]
@rodrigok could you please merge? I just rebased again but I would like to not fix merge conflicts again.

**Comment by soundstorm** [comment]
@rodrigok I liked the informal german - but adding a second language file for german would mess things up due to higher maintenance, right?

**Pull request merged**
