### PR TITLE
Katex plugin (for TeX math rendering)

### LINKED ISSUE #1922: writing math
First, Rocketchat is great! I'm slowly convincing my research group to use it.
It would be very useful to be able to write latex style math. Mathjax seems to be a stable solution (although I'm no expert). 
http://mathjax.readthedocs.org/en/latest/misc/mathjax-in-use.html

### PR DESCRIPTION
**Pull request by pitamar**
Closes #1922

### CODE REVIEW

**Comment by codyaray** [comment]
For anyone looking for how to use this, try passing in your katex expression between \[ and \]

\[ f(x) = \int_{-\infty}^\infty \hat f(\xi)\,e^{2 \pi i \xi x} \,d\xi \]

**Comment by laserroger** [comment]
But it seems not work

**Comment by codyaray** [comment]
Make sure its enabled in the administration section

**Comment by laserroger** [comment]
Thanks for that. Is the demo's general channel enable this?

**Comment by codyaray** [comment]
Not sure. I'm just a user. :)

**Pull request merged**
