### PR TITLE
[IMPROVE] Removes hardcoded prune message limit of 2000

### LINKED ISSUE #21305: Deleting Messages deletes max 2000 messages
### Description:

Deleting Messages deletes max 2000 messages

### Steps to reproduce:

1. click on the channel in question
2. click on the triple dot in the upper right corner
3. click delete messages
4. select older-than
5. choose 2021-01-01
6. click the big fat red DELETE button

### Expected behavior:

Messages before 2021-01-01 are deleted

### Actual behavior:

2000 Messages are deleted.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: I dont know what this is
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: desktop 3.0.3 
- Operating System: MacOS

### Additional context

none that I am aware of.

### Relevant logs:

no relevant logs found.

### PR DESCRIPTION
**Pull request by sammyzord**
- [x] I have read the Contributing Guide - https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat
- [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
- [x] Lint and unit tests pass locally with my changes
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- I have added necessary documentation (if applicable)
- Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

Added a new setting in the `General` section of the administrator panel. This setting allows the user to select how many messages the `Prune Messages` action will delete in bulk, this enables the user to dynamically set a limit compatible with their server's capability.

image

## Issue(s)

Closes #21305
## Steps to test or reproduce

1. Click the user Menu
2. Go to the admin panel
3. Go to the `General` section
4. Scroll down until you see the `Prune Messages Limit` input
5. Set the limit of your choice
6. Go to a channel
7. Click the channel menu
8. Select `Prune Messages`
9. Prune all channel messages

Now you should see a success message saying how many messages were deleted
image

### CODE REVIEW

**Comment by mc** [comment]
it seems the code was refactored and the limit moved to:

https://github.com/RocketChat/Rocket.Chat/blob/develop/client/views/room/contextualBar/PruneMessages/PruneMessagesWithData.js#L92

:-/

**Comment by sammyzord** [comment]
> it seems the code was refactored and the limit moved to:
> 
> https://github.com/RocketChat/Rocket.Chat/blob/develop/client/views/room/contextualBar/PruneMessages/PruneMessagesWithData.js#L92
> 
> :-/

Oh! Thanks for the heads-up, I will adjust it accordingly ASAP

**Comment by KevLehman** [comment]
@sampaiodiego do you know if the limit was set to 2000 for a reason? 😬

**Comment by sampaiodiego** [comment]
> @sampaiodiego do you know if the limit was set to 2000 for a reason? 😬

I think the only reason was to not overload the server.. 🤔

**Comment by sampaiodiego** [comment]
maybe @ggazzo remembers better than me

**Comment by ggazzo** [comment]
Kinda, the process can take much more time than we expect, without official partial results we would never  be sure if the hang up or still running. Maybe an meta data informing about the tasks wold be nice

**Pull request closed without merging**
