### PR TITLE
[WIP]Custom group notifs

### PR DESCRIPTION
**Pull request by Kailash0311**
Implementing #2192

### CODE REVIEW

**Comment by Kailash0311** [comment]
Till now I have only added the option of a role admin to add roles by creating an option under channel settings.

**Comment by slyk** [comment]
Will your design work with permission roles and notification groups as the same thing? I guess it adds many limitations, separate notification groups would be more flexible and dont add any dependencies.

**Comment by Kailash0311** [comment]
@slyk what do you mean by permission roles? I don't know about it.  :sweat_smile: .

**Comment by zdumitru** [comment]
@Kailash0311 Can you fix the failing test, please?

**Comment by slyk** [comment]
@Kailash0311 I mean the "roles" in RocketChat, their main function is to set permissions for users. Those roles not used to group people by their job type.
https://rocket.chat/docs/administrator-guides/permissions/
`A Role is a set of permissions that can be given to users.`

> Till now I have only added **the option** of a role admin **to add roles** by creating an option under channel settings.
After that line I thought you added ability to add more standard RocketChat "roles" that controll users permission.

Anyway, ANY type of solving this problem now will be good news. So thank you!!

**Comment by Kailash0311** [comment]
So here I meant roles as in custom Group Notification groups. 
It doesn't interact with role permissions which are already there.
I may have to rename the attribute from 'roles' to something more intuitive(e.g notifGroupNames)

**Comment by slyk** [comment]
Hello friend! Any news about the feature?

**Comment by Kailash0311** [comment]
Hey, sorry, I didn't proceed after that. I'll keep this PR updated in future in case of advancements.

**Comment by J0kerFace** [comment]
Is there any update about this feature?

**Comment by rodrigok** [comment]
We apologize for not getting a review on this sooner.

Since this PR didn't evolve and doesn't solve the issue mentioned I'll close this in favor of https://github.com/RocketChat/Rocket.Chat/pull/16311

**Pull request closed without merging**
