### PR TITLE
Fixed padding in reply thread button

### LINKED ISSUE #16029: [BUG] Reply in Thread button hovers the text
### Description:

Reply in Thread button in the threads panel could hover the text.

### Steps to reproduce:

1. Go to the thread replies panel
2. Find a thread reply that is one line long.
3. Hover a mouse over that line

### Expected behavior:

Reply in thread button should not hover the text (same way like emoji and three dots menu buttons don't).

### Actual behavior:

image

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.1
- Operating System: linux
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v8.16.2
- MongoDB Version: 

### Client Setup Information

- Desktop App or Browser Version: web version
- Operating System: -

### Additional context

Related to #15685

### PR DESCRIPTION
**Pull request by abhishuraina**
Fixed #16029

### CODE REVIEW

**Comment by gabriellsh** [comment]
Hey, the actual problem is that the thread button shouldn't be displayed at all. The padding is right.

**Comment by gabriellsh** [comment]
I don't know if that would be the best fix either, it looks a bit weird in Mobile view IMO.

You have to remove package-lock.json from your committed files also.

Thanks for the help!

**Comment by abhishuraina** [comment]
@gabriellsh considering the changes you mentioned for the replies section and i'll adjust the padding so that the changes in the mobile view are not noticeable. 
I think if we change the design of reply and emoji buttons that would be bit weird, as this is the issue of text overlapping (padding) the design is although very good. 
Any suggestions?

**Comment by engelgabriel** [comment]
I think we need to do what I suggested in https://github.com/RocketChat/Rocket.Chat/issues/16029#issuecomment-626386392

**Comment by gabriellsh** [comment]
I agree with @engelgabriel

**Comment by rodrigok** [comment]
@abhishuraina thanks for your contribution.

I'll close this PR for now, if you want to contribute a new one based on what Gabriel suggested here (https://github.com/RocketChat/Rocket.Chat/issues/16029#issuecomment-626386392) we will be happy to review and merge.

Thanks

**Pull request closed without merging**
