### PR TITLE
[NEW] [WIP] A better search experience

### PR DESCRIPTION
**Pull request by mrsimpson**
## Purpose

There are multiple places in Rocket.Chat to search for ... something. Searching in RC leaves users frustrated since there are many different places *with different semantics, icons and result sets*. Let me elaborate on this a bit:

### The side panel

image

- Effectively searches subscriptions and users. It kind-of mixes things you've already seen (subscriptions) and people you have not been talking to. 
- Does not occupy any other space than the sidepanel.
- Is always visible

### The global search

image

- Searches everything. With different possible providers, its capabilities may vary, but in general it does not restrict anything.
- With Chatpal enabled, it even supports NLP features and entity facets.
- It's only reachable once a channel has been opened => the "global" semantic is thus not intuitive.

### The directory

image

- Provides overviews of channels and users - independent of whether they have been seen / contacted earlier on.
- The search capabilities are very limited (e. g. not even the description of a channel is being searched) => it's more a filterable list
- Is always reachable

## How to resolve this

There should be ONE global search with the capability to find everything and (optionally) ONE search for finding content within a channel.

This PR goes a first step and adds a global search to the directory, giving it the capability to act as *THE* central place to find something in Rocket.Chat.

##  How it looks like

With global search enabled in settings
image

This is how it currently looks if Chatpal's activated
image

@RocketChat/core this is - of course - only a very first draft in order to kick-off discussions and get your input. Do you already have mockups / thoughts in this area?

### CODE REVIEW

**Comment by mnlbox** [comment]
Guys any chance to see this in 0.70.0?

**Comment by engelgabriel** [comment]
I had a conversation with @mrsimpson yesterday in person and I agree with this points.

Meybe we should make clear that the left panel search is really just a filter on the local list? So could chnage the icon for a filter... I am not sure I like that idea myself.

Or we can make the side bar larger on wide screens... and do like Telegram and WhatsApp, and have a more powerfull search there.

image

image

**Comment by mrsimpson** [comment]
@engelgabriel I really think that only searching in the left-hand-side effectively wastes a lot of space and capabilities of the desktop.

After longer discussions with @ruKurz we found out that there are two different usecases for searching: 

1. I want to switch to a new context and need to find it. This is what the icons in the sidepanel header do: They either open a list of subscriptions or allow browsing (searching in a graphical way).
2. I want to produce a message based on things I read / wrote earlier on. This does not only have to be a message, it may also be a user I want to mention. =>this is the purpose of the search in the tabbar (once a room's been opened).

Let's focus on the really global ones for the first step.
I can see two ways of dealing with the different searches:

## Combine them

The ease-of-use `cmd+k` must not be jeopardized. At the same time, if browsing is requested, the complete space of the screen should be used. => A dynamic expansion of the left-hand-side panel to include the directory (which is basically a facetted search) might be a solution. But this surely is something wort a real designer and/or UX-expert

## make the semantic more clear 

@engelgabriel once said in the context of threads that the channel list could be imagined as inbox. Then, why not expose `cmd+k` with this semantic? This would allow the directory to use the magnifier symbol and include all types of global facets / searches / dashboards there.

**Comment by mrsimpson** [comment]
@engelgabriel I do think that a better (global) search experience is elementary feature missing in RC.
Howver, I'm not going to pursue this anymore, so closing this PR in order to clean up the backlog.

**Pull request closed without merging**
