### PR TITLE
Additional md support

### PR DESCRIPTION
**Pull request by geekgonecrazy**
This adds support for:

```
![alt text](image)
```
as well as
```
[text](link)
```

both accept http or https only.

```
* test
* test
```

No longer produces:

**test**
test

or 
```
~ test
~ test
```
Producing
~~test~~
~~test~~

See `bot help`

Its pure regex... But it gets the job done.  I tried looking into showdown.  Problem with it is you need to add a xss filter.  The one they have appears to be using outdated methods.  So the browser pops up a bunch of alerts.

Thoughts @RocketChat/owners ?

### CODE REVIEW

**Comment by rodrigok** [comment]
I don't know if we should support headers (h1, h2, etc)

**Comment by engelgabriel** [comment]
Can we make some support configurable? Like the headers.
I can see it being very useful, like on a tab with a room description... but some people wanting to disable it in other areas...

**Comment by geekgonecrazy** [comment]
@engelgabriel absolutely.  We don't have an easy way to do per channel config, so I guess I could disable this for now?

**Comment by marceloschmidt** [comment]
We need that per channel settings ASAP :)

**Comment by graywolf336** [comment]
What about a special environmental variable to enable support for it temporarily?

**Comment by rodrigok** [comment]
@engelgabriel for tabs ok, but for messages... i don't like the ideia

**Comment by graywolf336** [comment]
Until posts are added, with full markdown support, I feel there should be the option to turn on/off headers support..

**Comment by geekgonecrazy** [comment]
Yes posts would be the big thing where we'd want to allow headers

**Comment by geekgonecrazy** [comment]
@RocketChat/owners Added a flag to enable this in messages.  Disabled by default

**Comment by geekgonecrazy** [comment]
Hold on this!  I'm going to add tests to this package.

**Comment by Sing-Li** [comment]
Ready for more tests now, please see #1028

**Comment by kakawait** [comment]
It could be cool to improve some built-in md like `` ` `` operator.

Actually if you want to escape `` ` `` see http://daringfireball.net/projects/markdown/syntax#code you should use ``` `` ```  operator in order to have something like ``see my ` ``, but it is not static indeed if you want to escape ``` `` ``` you should use ```` ``` ```` (3 * `` ` ``) operator

I hope you understand me :) (actually github support it if you want a try)

**Comment by geekgonecrazy** [comment]
@kakawait i'm not sure I understand.  Could you write an example then screen shot it?  So I can see what it looks like before you submit it?

**Comment by kakawait** [comment]
@geekgonecrazy Ok it's a bit tricky but if you want to write a **backtick quote** inside md inline literal you will try to write something like **\`test \` test\`**. But as you can see that will not work because md parser will can't understand that your literal backtick is not the end of literal syntax.

See screenshot

screen shot 2015-10-08 at 10 18 14

screen shot 2015-10-08 at 10 18 20

So in order to have backtick quote inside inline literal md spec suggest to double backtick as delimiter for inline so you should write **\`\`test \` test\`\`** in order to work (test on github) but on RocketChat it does not work:

screen shot 2015-10-08 at 10 18 35

screen shot 2015-10-08 at 10 18 43

*ATTENTION* the spec is recursive! So if you want to write 2 backticks inside inline literal you should use 3 backticks as delimiter **\`\`\`test \`\` test\`\`\`**, and etc.

And last tricky thing if you want to write just a backtick (or more) inside literal without text you should use spaces between your backtick and delimiter like **\`\` \` \`\`**

But I don't know if it easy to implement, even more with regex way! May be restricted limitations for the moment or use dedicated libraries!

**Comment by geekgonecrazy** [comment]
@kakawait wow... lol that seems super complicated.  I'll let someone with better regex chops do that one.  :)

**Comment by rodrigok** [comment]
@kakawait I think you could open a new issue for this problem, seems to be complicated.

For me, we can merge this PR.

**Comment by geekgonecrazy** [comment]
@rodrigok that'd be ok with me.  I'll add my tests in a separate PR since we are still trying to figure all that out.

**Pull request merged**
