### PR TITLE
[FIX] API Error preventing adding an email to users without one (like bot/app users)

### PR DESCRIPTION
**Pull request by debdutdeb**
Signed-off-by: Debdut Chakraborty <debdut.chakraborty@rocket.chat>

### CODE REVIEW

**Review by sampaiodiego — COMMENTED** [review]
I need to ask for a test case 😬

**Comment by debdutdeb** [comment]
Hm but the api doesn't allow no-email user creation. Not sure how can I add an e2e for this.

**Comment by sampaiodiego** [comment]
> Hm but the api doesn't allow no-email user creation. Not sure how can I add an e2e for this.

true.. I thought about that after I send the comment.. 😞

**Comment by sampaiodiego** [comment]
ohh. you can create a test case adding an email to `rocket.cat` user.

**Review by sampaiodiego — APPROVED** [review]

**Comment by dudanogueira** [comment]
This seems to also be affecting slack imports:
https://forums.rocket.chat/t/cannot-read-property-0-of-undefined-when-editing-user/13604

**Pull request merged**
