### PR TITLE
Check i18n file for missing variables

### PR DESCRIPTION
**Pull request by sampaiodiego**
## Proposed changes

The ideia is to have a check on CI to validate if a translation key is missing a variable to be replaced.

Missing a replacement variable in a translation can be critical to the end user, as the variable can be used for import information.. For example, the translation key `New_visitor_navigation` uses the variable `__history__` to show all the information regarding the page history on a livechat session. But [in](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-i18n/i18n/lv.i18n.json#L1856) [many](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-i18n/i18n/ca.i18n.json#L2024) [languages](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-i18n/i18n/pt.i18n.json#L2142), the `__history__` variable is missing, causing an incomplete message in chat history (actually, a message without the most important information, which are the page details).

The script is currently finding **295 missing variables**, what do you think we should do with them? We can either fixed them all (which can be very tricky for some languages) or remove all of them and since this check will be up for now on, no translation with a missing variable will be re-added.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

I had this script sitting around for so long, so I decided to open a pull request for us to discuss about it.

Please also give feedback to the script output, I made it to be useful enough to help fixing the issues, but there are lot of room for improvement.

### CODE REVIEW

**Comment by rodrigok** [comment]
@sampaiodiego that's a great addition, thanks.

Let's fix the `pt` and `pt-BR` ones and remove all the others, I agree it's the best way to let the translators make the translation again, try to fix them can lead to a wrong translation.

**Comment by Karting06** [comment]
Hello,
I can help with the translation of French & Dutch if needed.

**Comment by sampaiodiego** [comment]
thanks @Karting06 🤗 

you can check the current issues on the links below:

- french https://github.com/RocketChat/Rocket.Chat/pull/18762/checks?check_run_id=1057361649#step:15:229
- dutch https://github.com/RocketChat/Rocket.Chat/pull/18762/checks?check_run_id=1057361649#step:15:633

you can fix them opening another PR.. once it's merged I just need to rebase this PR and we're good to go :D

**Comment by Karting06** [comment]
OK, I will do that. 
@sampaiodiego I know that there are more translations missing than reported, do I add them in the same PR or another one?

**Comment by sampaiodiego** [comment]
@Karting06 I'd say another one.. if you want to contribute to missing translations please refer to https://docs.rocket.chat/contributors/contributing/translating .. we can invite you to our lingohub project, where things are much easier

**Comment by Karting06** [comment]
@sampaiodiego I have sent an email and will do it on Lingohub then.

**Comment by sampaiodiego** [comment]
I've removed the missing keys from all languages.. The CI should now pass, we can merge this.

**Review by rodrigok — APPROVED** [review]

**Pull request merged**
