### PR TITLE
[FIX] Fixes bug in latex-parsing

### LINKED ISSUE #9683: Random string of characters when sending `\([]\)`
### Description:

This is not a very complicated issue, I just have a simple question. When I send \`\\([]\\)\` to anyone, on any channel. I get this weird string of characters (`=!=tzLPMZngtWTMZNuXb=!=`). Can someone explain this to me.

### PR DESCRIPTION
**Pull request by c0dzilla**
@RocketChat/core 

Closes #9683 
Latex rendering function was returning incorrect value leading to resulting message being of the form '=!=<Random.id()>=!='. This pr fixes this.

### CODE REVIEW

**Comment by engelgabriel** [comment]
Testing the PR I had the following result:

image

But I don't think that latex should be parsed at all inside code formatted boxes or inline code, what do you guys think?

@RocketChat/core ?

**Comment by c0dzilla** [comment]
@engelgabriel presently latex parsing and markdown parsing callbacks on a message occur independently with latex parsing at higher priority. Latex parsing can be disabled in case inline/block code match occurs. Thoughts?

**Comment by nusje2000** [comment]
@c0dzilla I think the question should be, what would a user use more often. I think, based on my use case, people use codeblocks more often than latex parsing. Altho latex parsing could be usefull in some cases, I dont think it should be at a higher priority than inline/block code. But that is my opinion

**Comment by c0dzilla** [comment]
@engelgabriel what is the status on this? Is there anything needed to be done?

**Comment by tassoevan** [comment]
Thank you for the contribution. However, I'm closing this PR because it collides with other related issues we've worked on, as you can see in #11698 and #11746.

**Pull request closed without merging**
