### PR TITLE
Custom oAuth fix

### PR DESCRIPTION
**Pull request by OmarQunsulExpertiger**
Has the custom oAuth been tested?
Because with me first it was not working properly, until I have done the modifications in this pull-request.

### CODE REVIEW

**Comment by rodrigok** [comment]
@OmarQunsulExpertiger yes, is working, seems that your server doesn't reply requests with correct content type so **HTTP.get** can't return the parsed **data** and only returns the **raw content**.

Can you confirm this?

**Comment by engelgabriel** [comment]
@rodrigok can we deal with both cases? Like we did on the integrations?
I've read the HTTP spec, and the Content Type is not mandatory, altho highly recommended.

**Comment by rodrigok** [comment]
@engelgabriel yes.

@OmarQunsulExpertiger the best solution should be test if there is no **response.data** end then try to parse **response.content** as JSON, this way we keep the default parsers like url encoded.

This parser should be inside the method **getIdentity**

**Comment by OmarQunsulExpertiger** [comment]
@rodrigok it turned out that when I introduced this change, my app was not responding with content_type 'json', even though I thought it was.

So what I did now, that I changed the code as you suggested, and it's working in both scenarios, if the app returns **json** or **plain** responses.

Let me know if I need to check anything else.

**Comment by engelgabriel** [comment]
LGTM

**Comment by rodrigok** [comment]
LGTM

**Pull request merged**
