### PR TITLE
Admin redesign

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

I made a redesign in some of Administration pages.
This redesign was based on Material Design principles.
I added a `page-admin` class to change form elements design only in those pages, so the team can test and see if like. If it's ok I can make a PR to change this globally.

Making this redesign I saw some flaws in CSS redesign that decrease performance and painting of pages. The `css` files aren't well organized, etc.
If you consider that I can make a proposal for a CSS refactor :)

Here is some screenshots of the changes.

Info
info

Import
image

Rooms

Users
image

Permissions

Custom Emoji
image

Integrations
image

Mailer
image

### CODE REVIEW

**Comment by engelgabriel** [comment]
We need to merge this https://github.com/RocketChat/Rocket.Chat/pull/4348 before start changing any CSS. I have been trying to test the PR, but maybe you an help me @karlprieb ?

**Comment by karlprieb** [comment]
Sure, I will test tomorrow and add my comment there.
After the merge I will need to change some CSS for this PR work so I will put a WIP tag in the title, ok?

**Comment by engelgabriel** [comment]
@karlprieb one of the things I really don't like about material design, is the animation on INPUT fields, and the minimalistic design that turn them into a sing bottom line.  Let's give them a the full outline.

**Comment by timkinnane** [comment]
Looks like great work @karlprieb! I'm also a bit unsure how to apply material design. I tend to think the biggest problem with UX in Rocket.Chat right now is too many different approaches applied inconsistently.

Instead of redesigning components in isolation, I'd like to work with anyone who's interested on a baseline style guide, and then begin the long process of applying it across the app to each component in turn - while providing a clear vision and documentation to help other contributors follow the right path.

**Comment by timkinnane** [comment]
@karlprieb fyi, on my last comment, I've contributed some docs on use of color here:
https://rocket.chat/docs/developer-guides/ui-and-theming/colors/

The last example relates to admin settings components, though maybe it's not expressed very well, my rough scheme was:

- **transparent-dark** for the "page" background
- **content-background-color** for the settings panels
- **transparent-darker** for disabled labels and input backgrounds
- **component-color** is the default border color, will be inherited if not overruled
- **secondary-background-color** for table backgrounds headers
- **transparent-light** and **transparent-lighter** for alternate table row coloring

I'm not saying your work has to be implemented that way, but it would be good if you could utilise the color variables, so that site owners can have consistent UI theming in the admin sections.

I added some notes about the possibility of site owners have dark themed UIs, where uses fixed colors and color effects (like lighten or darker) for input states will cause contrast issues if the theme doesn't allow for it - here's a demo of the proposed approach using contrast calculated colors: https://codepen.io/owlandfox/pen/EyJROO

Though maybe the simpler approach is to have a fixed seperate color scheme for admin pages that doesn't inherit theme colors, then accessibility can't be broken. What do you think?

**Comment by karlprieb** [comment]
Hey @timkinnane sorry for the delay. Im with little time for Rocket.Chat lately :(
Thanks for your great work on #4348  :)

I talked to @engelgabriel about material design before and we think that is good to use for reference only, but now the Rocket.Chat doesn’t has any style guide for reference yet, so the big problem still is the UI discrepancy.

Will be good with we ( @engelgabriel , you and me) start a discussion about a baseline style guide, what you think?

I saw you new documentation. Its good :) I will follow that to reimplement my work and keep the pattern.

We need to talk with @engelgabriel about themes and discuss how can we do that, maybe based in your codepen example.

If we will keep admin colors separated from app theme we need to change the that colors to something more generic that will not look weird compared to the app theme. Do you agree?

**Comment by timkinnane** [comment]
Agree agree agree! 👍  I like the idea of using material as a guide only where we need it, not to make it too heavy. It might actually be better to start with an isolated admin theme and not worry about the app theme because its too big a job for now.

I really like just the simple design concepts of material, without going to the complexity of motion and layers... e.g. https://material.google.com/layout/metrics-keylines.html#
Just bringing consistent spacing to RC containers and typography would be an excellent start.

We could start by agreeing some rules for basic component (type, buttons, inputs, tables). Maybe share some mockups / sketch files? Maybe @engelgabriel can set up a private room in demo.rocket.chat for us to discuss further?

**Comment by ToeiRei** [comment]
Any chance to get some more info at the Users page? Something like last login?

**Pull request closed without merging**
