### PR TITLE
[IMPROVE] Change default upload settings to only block SVG files

### PR DESCRIPTION
**Pull request by sampaiodiego**
## Proposed changes

Change default upload settings to only block SVG files and allow everything else.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by georgmu** [comment]
@sampaiodiego Could you please explain why svg is on the blocklist?

I ran into a problem uploading a python script (test.py) and wondered why it didn't work. Searching for a reason (together with #18263) I wonder why svg is blocked here. What makes it so special? There are no comments anywhere (commit message, code) which explain this blocking.

**Comment by sampaiodiego** [comment]
SVG files cannot be rendered directly into the chat history as they support scripts. so until we properly handle that, we decided to disable them by default.

**Comment by palmeida** [comment]
I came across this today, trying to upload Jupyter notebooks, and I thought there might be some reason to block SVG files that I shouldn't mess with. I don't know what you mean by "rendered directly into the chat history", so I don't understand what may be the consequences. I now have an empty Blocked Media Types field and everything seems to work fine (I can upload Jupyter notebooks and an SVG upload also worked, and was rendered in the chat window).

**Comment by georgmu** [comment]
>  don't know what you mean by "rendered directly into the chat history", so I don't understand what may be the consequences.

The problem seems to be an SVG with malicious embedded javascript code inside. If there is a preview image of the upload, then this code might be executed.

**Pull request merged**
