### PR TITLE
Fix Improvement PR #5646 

### PR DESCRIPTION
**Pull request by hussamEddinAlhendi**
@RocketChat/core 

 
After Improving my pull request customField it was not work

### CODE REVIEW

**Comment by engelgabriel** [comment]
@rodrigok already did it on https://github.com/RocketChat/Rocket.Chat/commit/b4c5da1594ffc6d407aa91980de0a6febd82561f

**Comment by hussamEddinAlhendi** [comment]
@engelgabriel but it was not work I only fixed the error in passing createRoom parameters

**Comment by hussamEddinAlhendi** [comment]
@engelgabriel but there is readOnly messing in passing createRoom params so createRoom take customFields as readOnly

**Comment by hussamEddinAlhendi** [comment]
and customFields will be added as null to group object even if the body don't have customFields

**Pull request closed without merging**
