### PR TITLE
[FIX] Wordpress oAuth authentication wasn't behaving correctly

### LINKED ISSUE #10492: [BUG] WordPress authentication not working
Server to reproduce this bug: https://cardoso.rocket.chat
Version: 0.63.0

When pressing the OAuth button, I'm being redirected to this URL:
https://public-api.wordpress.com/oauth/authorize?client_id=57848&redirect_uri=https://cardoso.rocket.chat/_oauth/wordpress?close&response_type=code&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJPUXZPRm9yWDJSajNQXzNIQnpRTU1nTXM3VVlwRFY4ajUyQ2pBNkJDX1Q1IiwiaXNDb3Jkb3ZhIjpmYWxzZX0=&scope=openid

It should be this URL:
https://public-api.wordpress.com/oauth2/authorize?client_id=57848&redirect_uri=https://cardoso.rocket.chat/_oauth/wordpress?close&response_type=code&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJPUXZPRm9yWDJSajNQXzNIQnpRTU1nTXM3VVlwRFY4ajUyQ2pBNkJDX1Q1IiwiaXNDb3Jkb3ZhIjpmYWxzZX0=&scope=openid

Notice the oauth -> oauth2 change

When manually overriding this, I can go further into the OAuth flow, but the server throws these errors:

Server logs:

```
[34mW20180418-12:40:39.984(0) (oauth.js:424) [35mError in OAuth Server: Failed to complete OAuth handshake with wordpress at https://public-api.wordpress.com/oauth/token. failed [404] { "error": "not_found", "message": "The specified path was not found. Please visit https://developer.wordpress.com/docs/ for valid paths." }
[34mI20180418-12:40:40.496(0) Exception while invoking method 'login' Error: Failed to complete OAuth handshake with wordpress at https://public-api.wordpress.com/oauth/token. failed [404] { "error": "not_found", "message": "The specified path was not found. Please visit https://developer.wordpress.com/docs/ for valid paths." }     at CustomOAuth.getAccessToken (/app/bundle/programs/server/packages/rocketchat_custom-oauth.js:150:21)     at Object.OAuth.registerService.query [as handleOauthRequest] (/app/bundle/programs/server/packages/rocketchat_custom-oauth.js:211:32)     at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)     at middleware (packages/oauth.js:194:5)     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 
```

The logs show this URL
https://public-api.wordpress.com/oauth/token

It should be accessing this URL:
https://public-api.wordpress.com/oauth2/token

Notice again the oauth -> oauth2 change.

### PR DESCRIPTION
**Pull request by kaiiiiiiiii**
Closes #10492

wordpress_oauth

### CODE REVIEW

**Comment by kaiiiiiiiii** [comment]
Done that. Let me know if there's anything else I can do :)

screen shot 2018-04-23 at 20 46 46

**Comment by graywolf336** [comment]
@RocketChat/core any reason we can't add this to the v64 release? Because it is a login issue and delaying it to the next release feels wrong to me.

**Comment by geekgonecrazy** [comment]
@kaiiiiiiiii which oauth plugin are you using?

https://wordpress.org/plugins/oauth2-provider/ this plugin seems to not have /oauth2 but /oauth as the path.

Also then when changing it to /oauth manually in the url, then this: `An+unsupported+scope+was+requested` error is returned

**Comment by cardoso** [comment]
@geekgonecrazy I think it's not a plugin, but the built-in (first-party) Wordpress Application OAuth 🤔 

At least I didn't have to use any plugins to set it up.

https://developer.wordpress.com/docs/oauth2/

**Comment by geekgonecrazy** [comment]
We are on-premises so most software also is on-premises for our users.  At least we try to be friendly to that.  So maybe we need a drop down in the wordpress option to select between wordpress.com and plugin based?

Or... we need to make it clear that this is now for wordpress.com.  As previously was not. 

Most that I know of using it are using a plugin with wordpress hosted by a Cpanel type shared hosting setup.  Not many that I know of use wordpress.com

**Comment by cardoso** [comment]
I think it needs to be a separate option with the name of the plugin, instead of just "Wordpress" @geekgonecrazy 

But we shouldn't be committing to maintaining an integration of a third-party plugin of a third-party service in our main codebase IMO. (Which also implies we need to maintain it in both Android and iOS)

Maybe this can be a Rocket.Chat App in the future? 🤔

**Comment by kaiiiiiiiii** [comment]
Thanks for pointing that out @geekgonecrazy and sorry for any inconvenience.

I’ll work on a more flexible version the next couple of days :)

**Pull request merged**
