### PR TITLE
[FIX] Verification email body

### LINKED ISSUE #16911: [BUG] Confusing verification email
### Description:

I changed a user email and received an email asking to verify my account, but the writing is confusing.
It says "You have successfully created an account..." although I didn't create a new account.

### Steps to reproduce:

1. Enable "Verify email" on server
2. Change a user email

### Expected behavior:

Maybe verification emails shouldn't assume it's a new user.

### Actual behavior:
image

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0-develop on open server

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
Closes #16911

### CODE REVIEW

**Comment by GOVINDDIXIT** [comment]
@kaiiiiiiiii Any changes you want to suggest?

**Comment by kaiiiiiiiii** [comment]
Yes, for sure, why not. I thought it’s obvious enough.

Imagine my sites name is “Google”.

“Welcome to Google, the best open source chat solution available today!”.

But my site isn’t the “best open source chat solution”, RocketChat is. My site is just based on that product.

I hope that clarifies my downvote.

**Comment by rodrigok** [comment]
I agree with @kaiiiiiiiii

**Comment by GOVINDDIXIT** [comment]
So should I hardcode the site name to Rocket.Chat?

**Comment by GOVINDDIXIT** [comment]
@rodrigok I have updated the PR. Pls review

**Comment by danger89** [comment]
ps. there is something fundamentally wrong with the `Build and Test / build-image-pr` testcase. I saw the same issue within my own PR. Does somebody from the rocketchat devs fix this or?

**Comment by rodrigok** [comment]
@danger89 it's normal, the CI doesn't provide the secrets when building PRs from forks, so the image build doesn't works for them since it requires a secret to upload the image.

**Pull request merged**
