### PR TITLE
[NEW] Run CircleCI with and without Apps Framework enabled

### PR DESCRIPTION
**Pull request by Hudell**
Changes CircleCI configuration to run the tests with and without the Apps Framework

### CODE REVIEW

**Comment by Hudell** [comment]
@graywolf336 I think we can merge it anyway, there's no problem in changing it later and it may be able to detect a few problems like the one we had this week.

**Comment by graywolf336** [comment]
Can you fill me in? I wasn't aware of an issue related to Apps.

**Comment by Hudell** [comment]
#10671  #10705 

Took us a while to figure out it was caused by the App Framework, as it didn't happen on our localhosts.

**Comment by geekgonecrazy** [comment]
Do we still want this?  Or should we close this out?

**Comment by sampaiodiego** [comment]
idk.. we had an issue at some point that happened only with apps enabled.. but I'm not sure how buggy it's right now that we would still need this.

**Comment by sampaiodiego** [comment]
@rodrigok wdyt?

**Comment by rodrigok** [comment]
@sampaiodiego It's important.
@Hudell can you change the env var to the setting override?

**Pull request closed without merging**
