### PR TITLE
fix: Exporting rooms messages as file throws error on server side

### PR DESCRIPTION
**Pull request by matheusbsilva137**
## Proposed changes (including videos or screenshots)

 - Create read stream based on file path (and not file descriptor) when uploading zip export file.

## Steps to test or reproduce

Enter a room and access the "Export Messages" option in the menu. Choose the "Export as file" method and pick a date period, then click on the "Export" button.
Currently, an error is thrown (not consistently, it doesn't happen in every attempt):

<details>
<summary><b>Error logs</b></summary>

```
W20231011-13:54:43.044(-3)? (STDERR) (node:140025) Warning: Closing file descriptor 47 on garbage collection
W20231011-13:54:43.045(-3)? (STDERR) (node:140025) [DEP0137] DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. Please close FileHandle objects explicitly using FileHandle.prototype.close(). In the future, an error will be thrown if a file descriptor is closed during garbage collection.
W20231011-13:54:43.056(-3)? (STDERR) [Error: EBADF: bad file descriptor, read] {
W20231011-13:54:43.056(-3)? (STDERR)   errno: -9,
W20231011-13:54:43.056(-3)? (STDERR)   code: 'EBADF',
W20231011-13:54:43.056(-3)? (STDERR)   syscall: 'read'
W20231011-13:54:43.057(-3)? (STDERR) }
W20231011-13:54:43.059(-3)? (STDERR) === UnHandledPromiseRejection ===
W20231011-13:54:43.060(-3)? (STDERR) Error: EBADF: bad file descriptor, read
W20231011-13:54:43.060(-3)? (STDERR)  => awaited here:
W20231011-13:54:43.060(-3)? (STDERR)     at Function.Promise.await (/home/matheus/.meteor/packages/promise/.0.12.2.bqfx3w.89spp++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20231011-13:54:43.060(-3)? (STDERR)     at app/file-upload/server/lib/FileUpload.ts:730:14
W20231011-13:54:43.060(-3)? (STDERR)     at /home/matheus/.meteor/packages/promise/.0.12.2.bqfx3w.89spp++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20231011-13:54:43.060(-3)? (STDERR)  => awaited here:
W20231011-13:54:43.060(-3)? (STDERR)     at Function.Promise.await (/home/matheus/.meteor/packages/promise/.0.12.2.bqfx3w.89spp++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20231011-13:54:43.060(-3)? (STDERR)     at server/lib/dataExport/uploadZipFile.ts:37:12
W20231011-13:54:43.060(-3)? (STDERR)     at /home/matheus/.meteor/packages/promise/.0.12.2.bqfx3w.89spp++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20231011-13:54:43.060(-3)? (STDERR)  => awaited here:
W20231011-13:54:43.061(-3)? (STDERR)     at Function.Promise.await (/home/matheus/.meteor/packages/promise/.0.12.2.bqfx3w.89spp++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20231011-13:54:43.061(-3)? (STDERR)     at server/lib/dataExport/sendFile.ts:76:12
W20231011-13:54:43.061(-3)? (STDERR)     at /home/matheus/.meteor/packages/promise/.0.12.2.bqfx3w.89spp++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 {
W20231011-13:54:43.061(-3)? (STDERR)   errno: -9,
W20231011-13:54:43.061(-3)? (STDERR)   code: 'EBADF',
W20231011-13:54:43.061(-3)? (STDERR)   syscall: 'read'
W20231011-13:54:43.061(-3)? (STDERR) }
```

</details>

This error shouldn't be thrown anymore with the changhes in this PR.

## Further comments

This error is not consistent to reproduce, but it happens after garbage collection runs (see the warning in the first line of the error logs). What may be going on is that the file descriptor was being closed (since it was unused) before we created the read stream. By using the file path instead we can avoid such errors and skip the `open` step that doesn't look useful.
TC-851

### CODE REVIEW

**Review by KevLehman — APPROVED** [review]
I don't know the context of this so take it as a symbolic approve, but I've been finding this every now and then lol

**Review by debdutdeb — CHANGES_REQUESTED** [review]
without autoclose the fd won't be closed even on an error, please close it manually there too.

i also don't know anything about this, so just a pure technical review

**Comment by KevLehman** [comment]
As a side note, if it's kinda "consitent" to reproduce, you may start to put some logs or debug statements to see what's going on with the descriptor.

Generally you don't need to change the autoClose form for readStreams, which could mean after the stream is being piped is still trying to be used somewhere else, maybe a place without an await or smth.

**Comment by matheusbsilva137** [comment]
Hey @KevLehman and @debdutdeb guess I've found the real root cause of this issue now
We were getting the file descriptor of the exported zip file and then using it to create a read stream. Apparently, turns out this fd could be closed (by the garbage collector) before we created the actual read stream, which caused that error. This happened frequently on our test envs, but after these changes we couldn't manage to reproduce it anymore.

**Comment by sampaiodiego** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/30657

unfortunately I was not actually aware of this PR and fixed the same thing in the above PR.. 😬

**Pull request closed without merging**
