### PR TITLE
[FIX] Fix email on mention

### LINKED ISSUE #8027: "Mentions" email setting send emails even when not mentioned
Reproduced in 0.58.2 and 0.59.0-rc.3

Steps to reproduce:
1. Open Room
2. Set email notifications to "All Messages"
3. Get emails for new messages
4. Change setting to "Mentions"
5. You will still get emails for "All Messages" with the subject as "You have been mentioned by..." even though you were not mentioned.

Note: This may simply be a bug with the "Mentions" setting. Things seems to work fine when "Use account preference" is selected.

### PR DESCRIPTION
**Pull request by MartinSchoeler**
@RocketChat/core 
closes #8027

This fixes a issue when you would receive email notifications for all messages even when only the `mentions` setting was selected

### CODE REVIEW

**Comment by sampaiodiego** [comment]
Actually it was this way on purpose to prevent too much emails from being sent, so `@all` mention was used only for push and desktop notifications. @RocketChat/core thoughts?

**Comment by pkgodara** [comment]
After #7639 ,
I think settings under preferences and channel settings are clashing. My preferences setting is `All Mentions/DMs` & channel setting to `Mention`, but still I get email notification for every message.

And further, I'm getting notified for messages that I've posted myself.

**Comment by rodrigok** [comment]
IMO, we should send email on `@all` mentions, cuz it's mention in anyway. We limite the use o `@all` to rooms with more than a certain number of members

**Comment by engelgabriel** [comment]
I agree with @rodrigok

**Comment by MartinSchoeler** [comment]
I will make some changes to be sure that the mention all limit is verified before sending a email

**Pull request merged**
