### PR TITLE
[NEW] Version update check

### LINKED ISSUE #9542: [FEATURE] Alert of new version available
### Description:

Feature to alert administrators (could be configurable) when there is a new version of the Rocket.Chat server available and show if that update includes a security fix.

- Show an alert on top of the screen that could be dismissed (@arthurgiustina I need your work here)
- Send a message via Rocket.Cat to all administrators alerting about the update, so that could alert them via email or push notifications
- Send an email too alerting in case they changed the setting to not receive messages via email

The service will run in a cron job every day and will check against one of our services, for that the instance will need to inform their version, nodejs version, OS distribution and version and maybe some more data, always anonymously, of course this check could be disabled.

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

screen shot 2018-02-20 at 11 54 33 pm

Closes #9542

- [x] Show banner to admins
- [x] Send message via Rocket.Cat to admins
- [ ] Send email to admins
- [x] Allow dismiss the banner
- [x] Do not alert multiple times
- [x] Alert security updates

### CODE REVIEW

**Comment by gdelavald** [comment]
Can we display the 'update your instance' only for admins? Seems more reasonable than showing to every user on the server.

**Comment by geekgonecrazy** [comment]
Agreed!  Maybe a role filter on the alerts so can restrict to just admin?

**Comment by sampaiodiego** [comment]
it [IS](https://github.com/RocketChat/Rocket.Chat/pull/9793/files#diff-c0c4b8e61a6c0bdf6bc6087fa5371095R36) already filtering only admins

**Comment by rodrigok** [comment]
@geekgonecrazy if you click to see more information the banner will not close, but if you close it will be removed from database and will not be showed again until we release a new version.

**Pull request merged**
