### PR TITLE
Add drawingCanvas

### PR DESCRIPTION
**Pull request by garg**
@RocketChat/core 

This is related to #5718

This is a work in progress collaborative paint addon. There are some UI issues as explained in #5718. In RocketChat v0.33 this would open the paint tab automatically. It would also work fine when changing channels. With v0.46, Switching channels breaks it because I am unable to destroy and recreate the canvas because I haven't figured out how to getTemplate.

### CODE REVIEW

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (115/100 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 5493 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:49585 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWmiT-0032cA-DW
	for greg@biomassiv.es; Thu, 26 Jan 2017 10:16:05 -0600
Date: Wed, 25 Jan 2017 19:17:04 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485400624;
	bh=rUPn+MTqtl3KuXAa2MFkN0Hr2O/h0b4WT2b4JWmYT7A=;
	h=From:Reply-To:To:Cc:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=UN9Ow+zkxnQqNhWkbPP7HFEijAQDZKOt+iF3JnGZJFuR+iBa8Swrt2SLeHrjBsMfz
	 IHbX75IV+LZJjTH3qV1mu9XT5fk/3tfSjLpsGU7KcOGvGqzPLJBn6i9ZMCJAMc8jea
	 BOPNypu5n3o3BZUOZel0A4aTc8DQVIxmCafOCHNo=

**Comment by engelgabriel** [comment]
@garg why dont you do a PR adding the code of https://github.com/garg/drawingCanvas into a `/packages/rocketchat-drawing` folder?

**Comment by garg** [comment]
Ok. I'll do that right now. I had added it as a submodule but I'll make this change and push it again.

**Comment by marceloschmidt** [comment]
@RocketChat/core there is room for improvement, but @garg did an amazing job!! This is an awesome addition to Rocket.Chat. Can we merge this and working on improving it later on?

**Comment by sampaiodiego** [comment]
@marceloschmidt I haven't tested it, but as @garg said there is a bug when leaving and entering channels.. and also a lot of lint issues..

**Comment by marceloschmidt** [comment]
Ah :( I didn't realize the bug when leaving and entering rooms (that slipped through my read).
And the lint problems are all related to this file: `rocketchat-paint/client/compatibility/glbrush/g010_util2d.js` which I believe should not be fixed, for being part of an external lib

**Comment by mnlbox** [comment]
It's very interesting feature ❤️

**Comment by marceloschmidt** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/issues/255

**Comment by graywolf336** [comment]
Closing this due to the comment from Gabriel Engel on this issue: https://github.com/RocketChat/Rocket.Chat/issues/255#issuecomment-378953344

**Pull request closed without merging**
