### PR TITLE
Capensisma bad word filter

### PR DESCRIPTION
**Pull request by geekgonecrazy**
@RocketChat/core 

Replaces #2940

Fixed formatting issues with eslint

### CODE REVIEW

**Comment by capensisma** [comment]
Thanks

**Comment by sampaiodiego** [comment]
LGTM

**Comment by marceloschmidt** [comment]
LGTM

**Comment by rodrigok** [comment]
LGTM thanks @geekgonecrazy

**Comment by capensisma** [comment]
LGTM?? thanks :D yeah my first PR is live :P

**Comment by capensisma** [comment]
What's next ? You decide! Epic PR Battle of All time :D

**Comment by engelgabriel** [comment]
Please install http://eslint.org/ in your editor, so you next PR will pass the code formatting and quality test, ok?

**Pull request merged**
