### PR TITLE
Russian translate add

### PR DESCRIPTION
**Pull request by denegny**
Add Russian translate.
Something was left without translation, but the main part is translated

### CODE REVIEW

**Comment by fonsich** [comment]
Where can i send you my german translation?

**Comment by marceloschmidt** [comment]
First you have to fork our project.
Then you can create a german i18n.json file under i18n subdirectory with all your translations.
Last step would be to commit your changes to your fork and make a Pull Request so we can merge your changes into the main project.

**Comment by fonsich** [comment]
I hope i did it right... ;-)
Didn't use Github until now...
Like the project!

**Comment by marceloschmidt** [comment]
Perfect! Thanks for your support.

**Comment by marceloschmidt** [comment]
@denegny, you'd you like to help us keep up with translations? we've moved our files from transifex to lingohub. If you don't mind being our russian translator, please drop us an email at support@rocket.chat. Thanks!

**Pull request merged**
