### PR TITLE
Livechat client app new message notification

### LINKED ISSUE #3012: Notification sound at LiveChat customer panel
It would be great to have a notification sound to notify the customers when the chat agent replies on their LiveChat. I really like this feature when I use online chat support on different systems, because many times chat agents take some time to check the issue and than get back, so the customer does not have to check time by time if they got a reply but they will hear the notification sound.

### PR DESCRIPTION
**Pull request by AlecTroemel**
@RocketChat/core

Closes #3012

Gives clients using the livechat app the ability to turn an incoming messages notification sound on and off.

### CODE REVIEW

**Comment by palidanx** [comment]
I just deployed a copy of rocket.chat via an ubuntu snap, and the client browser doesn't seem to be getting any sound notifications.  Is this currently working?

**Comment by AlecTroemel** [comment]
should be! Audio isn't blocked by the browser is it?

**Comment by palidanx** [comment]
I tried it on firefox and chrome on windows 10 and both don't seem to be working.  Do I have to configure anything on the admin sound to specifically allow sound chiming?

**Comment by crowdstar5566** [comment]
Can we please get the file added or get the reference to notify.mp3 changed to chime.mp3?

**Pull request merged**
