### PR TITLE
[FIX] OTR issue

### LINKED ISSUE #20074: Off-the-Record Conversation always results in a timeout
### Description:

Off-the-Record conversation always results in a timeout

### Steps to reproduce:

When I start an Off-the-Record conversation, I've got a Timeout error.

### Expected behavior:

Starting OTR conversation

### Actual behavior:

image

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0
- Operating System: Linux
- Deployment Method: Docker image
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.4

### Client Setup Information

- Desktop App : 3.0.7 or 3.1.1
- Operating System: Windows

### Relevant logs:

While using Chrome browser there're no errors in the console.

Thanks,

Rémy

### PR DESCRIPTION
**Pull request by ggazzo**
closes #20074

## Proposed changes (including videos or screenshots)

Since the users are not being stored at the user collection anymore (thats a good thing actually), there is no such record to to fetch and show the username.

### CODE REVIEW

**Review by dougfabris — APPROVED** [review]

**Comment by Bengrunt** [comment]
Hi, will this fix be released in 3.11.x as well ? Thanks a lot ! 👍

**Comment by qchn** [comment]
This bug is still a thing with the latest version (3.11.1)

**Comment by joseluisq** [comment]
The bug is not fixed on 3.11.0.

**Comment by Bengrunt** [comment]
Seems like it's present in 3.12.0-rc0: https://github.com/RocketChat/Rocket.Chat/releases/tag/3.12.0-rc.0

Thanks! :)

**Comment by TBG-FR** [comment]
Looks like it's still not working in 3.12.0 ... We've updated, but the OTR still always end up in time out :/
Do others experience this ?

**Pull request merged**
