### PR TITLE
[FIX] Improper grammar when converting channel member to owner

### LINKED ISSUE #25727: Grammatical error in User__username__is_now_a_owner_of__room_name_
### Description:

Grammatical error in the Toaster confirming a user has been upgraded to an Owner in a channel. `User__username__is_now_a_owner_of__room_name_` should say "an owner" instead: `User__username__is_now_an_owner_of__room_name_`

This should be updated in all 52 lines of code where this phrase exists:
https://github.com/RocketChat/Rocket.Chat/search?q=User__username__is_now_a_owner_of__room_name_ 

### Steps to reproduce:

1. Go to a channel
2.  Promote a user to an Owner
3.  Confirmation Toaster has grammatical error

### Expected behavior:

Toasters are free from grammatical errors

### Actual behavior:

A Owner_RC_Toaster

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  v14.17.6
- MongoDB Version: 4.2.5 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 101.0.4951.64 (Official Build) (x86_64)
- Operating System: MacOS Monterey

### PR DESCRIPTION
**Pull request by JoshMcCullough**
## Proposed changes (including videos or screenshots)

This is just a simple grammar adjustment for the English language when a user is upgraded to an owner within a channel.

## Issue(s)

Closes #25727

## Steps to test or reproduce

 Upgrade a user from a member to an owner of a channel and observe the grammatical error when your locale language is English.

### CODE REVIEW

**Review by debdutdeb — DISMISSED** [review]

**Review by ggazzo — DISMISSED** [review]

**Comment by ggazzo** [comment]
@JoshMcCullough  can I ask you to sync your branch with `develop` ?

**Comment by JoshMcCullough** [comment]
> can I ask you to sync your branch with `develop` ?

Done -- rebased and pushed.

**Comment by dougfabris** [comment]
@JoshMcCullough please, can you sync the PR again? We fixed the issue with the CI Auto Label! It should work now, so we can merge it! Thanks

**Comment by JoshMcCullough** [comment]
> please, can you sync the PR again?

Done. But I had to replace this PR with [this one](https://github.com/RocketChat/Rocket.Chat/pull/27265) because the fork on this PR no longer exists.

**Pull request closed without merging**
