### PR TITLE
Only require a password if change email or password in user profile

### PR DESCRIPTION
**Pull request by nishimaki10**
@RocketChat/core

In my use case, allow only changing name.
I think unnecessary that re-enter password in this case.

### CODE REVIEW

**Comment by rodrigok** [comment]
@RocketChat/core what do you think?

**Comment by geekgonecrazy** [comment]
It seems like really only thing that should require a password is email change and password change, because those are the only two things that could be used for an account take over.

**Comment by marceloschmidt** [comment]
I agree with @geekgonecrazy on requiring it only for e-mail and password. I'm on the edge about a setting to completely disable it though...

**Comment by nishimaki10** [comment]
Thank you for advice! I did re-implementation.

**Comment by marceloschmidt** [comment]
Awesome @nishimaki10 !!

LGTM.

**Comment by rodrigok** [comment]
LGTM

**Pull request merged**
