### PR TITLE
[FIX] Scrollbar not using new style

### LINKED ISSUE #8049: [FIX] Make scrollbar more visible using JS
image

### PR DESCRIPTION
**Pull request by ggazzo**
applied on sidenav and room

@RocketChat/core 

Closes #8049

### CODE REVIEW

**Comment by karlprieb** [comment]
@ggazzo Can you use NPM module instead Meteor packages?

**Comment by ggazzo** [comment]
no

**Comment by ggazzo** [comment]
@MartinSchoeler could you see the error plz? :)

**Comment by ggazzo** [comment]
thanks @rodrigok

**Comment by cyclops24** [comment]
@ggazzo , @karlprieb , @rodrigok Please visit above issue. ( #8223 )

**Comment by rodrigok** [comment]
@cyclops24 It was my fault, the PR was in progress and with test erros, so I fixed the tests and thought was the reason to be in progress, so I merged it.

I created a new PR (https://github.com/RocketChat/Rocket.Chat/pull/8244) disabling the scrollbar implementation and @ggazzo will finish the implementation in another PR.

Thanks by your review 😄

**Pull request merged**
