### PR TITLE
[FIX] Fix Unread Bar Disappearing

### LINKED ISSUE #5989: Unread Message bar disappears after few seconds
I Just upgraded my instant to 51.0, so i dont' have any unread messages, but i noticed in demo.rocket.chat  as of Feb 11, 2017 the unread message bar on top of the room disappears after few seconds, without clicking read.

### LINKED ISSUE #6967: Brief flash of unread messages.
Rocket.Chat Version: 
Running Instances: 
Web, desktop (rocketchat-desktop-2.7.0.rpm) , android client
DB Replicaset OpLog:
Node Version:

When I click on a channel there is a brief flash on the a bar to jump to the latest unread message but before I get to it, it goes away. This happens maybe 1 in 4 times I'm guessing. I see this on the web, desktop client, and on the Android client on my phone.

### PR DESCRIPTION
**Pull request by MartinSchoeler**
@RocketChat/core 

Closes #6967
Closes #5989

This bar was disappearing shortly after opening a room
screen shot 2017-07-04 at 3 52 46 pm

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
My hero!  This has been annoying me.  😁

**Comment by MartinSchoeler** [comment]
@karlprieb could you review again this? This created a bug that when you join a channel it would create a unread number that could not be removed
screen shot 2017-07-04 at 4 44 17 pm

**Comment by cr22rc** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/6967  I have this issue open maybe the same thing.
I'd really like to get a fix for this !

**Comment by MartinSchoeler** [comment]
@cr22rc Yes this Pull Request will solve this issue

**Comment by cr22rc** [comment]
Hi any ETA when this fix can be included in the client -- honestly it's driving me crazy ... I'm not sure why others are not screaming more about this.  It seems to affect mye almost every other time I click on a channel @geekgonecrazy

**Comment by geekgonecrazy** [comment]
@cr22rc looks like we're targetting it for 0.57.2 release. :)

**Pull request merged**
