### PR TITLE
[FIX] Add missing is/are translation for user actions

### PR DESCRIPTION
**Pull request by Karting06**
## Proposed changes (including videos or screenshots)

Add missing `is` & `are` translation key in order to better translate the `$USER1 is typing`. 

## Issue(s)

It doesn't fully fixed it but it fixes it for some languages: #23593
## Steps to test or reproduce

See: #23593

### CODE REVIEW

**Comment by chotaire** [comment]
Not all languages feature present progressive I believe. This will likely require "is" and "are" to be left empty in affected language translations, however translators will just fill them because the strings exist. 

This entire PR that changed typing indicators complicates things to an extreme and I would rather see that reverted. There should not be a case where message typing indicators demand present progressive, and then the strings are even split. This really isn't good at all!

As an example, there is a present progressive in German, however in the case of "is writing" or "are writing" it would actually not be used because it just wouldn't sound right.

**Comment by chotaire** [comment]
Oh, despite my concerns, @Karting06 the translations you added also need to be referenced within the code. For now this shouldn't do anything.

**Comment by Karting06** [comment]
@chotaire It does work (tested in French). 
It's used [here](https://github.com/RocketChat/Rocket.Chat/commit/a0249005961091c06b820d807d42e36f75be4996#diff-c825f97d19958626d81c98c83366f003657fe9631c93609ec62add90d5bf4a29)

**Comment by Karting06** [comment]
But, I completely agree with you. 
The core code should be rewritten instead of simplifying to `is + action`.

**Comment by dougfabris** [comment]
> But, I completely agree with you. The core code should be rewritten instead of simplifying to `is + action`.

@Karting06 Would you like to help us with that? 😄

**Comment by Karting06** [comment]
@dougfabris, okay. But that will be in a few weeks ;)

**Comment by ankar84** [comment]
Any news guys?

**Comment by TBG-FR** [comment]
I think you got it right, it should be reworked to create `[is] action` strings for each `action`
- That will handle languages using `is action` and languages using only `action`
- That will give more context to people doing translations, hence getting them right (for exemple `recording` is mistranslated in French because of that)

I'd be willing to do these modifications, if anyone has already some ideas or guidelines, feel free to give them 😄 

While I'm here, how do you apply to be able to help translating RocketChat in LingoHub ? I sent a mail years ago and never been added 😅

**Comment by ankar84** [comment]
> While I'm here, how do you apply to be able to help translating RocketChat in LingoHub ? I sent a mail years ago and never been added

Ask @sampaiodiego at open to send invite link. He invited me to LingoHub.

**Comment by TBG-FR** [comment]
@sampaiodiego If you can send me an invitation, I'd be happy to contribute !
You can also give my your thoughts about #27004 😉

**Comment by TBG-FR** [comment]
@Mugros @ankar84 I'd be happy to have your review 😄

**Comment by TBG-FR** [comment]
@dougfabris Thank you for your reactivity ! I didn't receive any invitation, but my account wasn't created with my Github public email and wasn't linked to Github, I fixed it, can you invite me again ? Thanks a lot !

**Comment by dougfabris** [comment]
@TBG-FR Already sent to your GitHub public email 😃 
Thanks for helping us!

**Comment by Karting06** [comment]
Hi @TBG-FR, thanks for taking the time to fix it.
Didn't have the time in the last weeks.

Nice to see that it will be solved.
Thanks @dougfabris

**Comment by TBG-FR** [comment]
Hello @dougfabris , sorry to bother you but I can now access the RocketChat project on LingoHub, but I can't do anything
- Dashboard displays "0 targeted language"
- When I try to translate an (not yet translated) element, it's greyed out

Can you check the perms ? The new RocketChat version introduced new strings, and they need translations 😅 

Many thanks in advance ! 🙏

**Comment by dougfabris** [comment]
@TBG-FR I changed your permissions on the projects, can you check it again?
Thanks for helping us, mate!

**Pull request closed without merging**
