### PR TITLE
regression: Thread file upload

### PR DESCRIPTION
**Pull request by yash-rajpal**
## Proposed changes (including videos or screenshots)

When the user uploads an image to a thread, it gets sent to the channel instead.
## Issue(s)

Introduced here: #32324

## Steps to test or reproduce

1. Open a channel
2. Send a message
3. Hover the message → Start a thread
4. Send a message inside the thread
5. Inside the thread, send an image

## Further comments

[CORE-421](https://rocketchat.atlassian.net/browse/CORE-421)

[CORE-421]: https://rocketchat.atlassian.net/browse/CORE-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by debdutdeb — APPROVED** [review]

**Review by debdutdeb — COMMENTED** [review]
possible we get tests written for this?

**Comment by sampaiodiego** [comment]
do you know what caused this regression? just so we can take a look for other possible regressions as well

**Comment by yash-rajpal** [comment]
@sampaiodiego This regression was caused by #32324 - when we reverted the encryption of file description. We missed reverting this one line. 

I don't think their are anymore regressions related to this.

**Comment by sampaiodiego** [comment]
thx @yash-rajpal .. I'm bit confused though.. because this code used to add the whole `msgData` not just the `tmid` field, like:

```
const msg = await executeSendMessage(userId, {
   // ...
   ...(msgData as Partial<IMessage>),
   // ...
});
```

why not make it like it was before?

**Comment by sampaiodiego** [comment]
> We missed reverting this one line.

do you mean you didn't use `git revert` to revert the other PR? that's scary 🙈

**Comment by yash-rajpal** [comment]
I used `git revert` but there was a conflict in this file and missed that part 😞

**Comment by moimran123** [comment]
I want to work on this issue .please assign me this issue.

**Comment by debdutdeb** [comment]
@moimran123 this is a pr. It already fixes an issue. There is nothing to assign here.

**Review by dougfabris — APPROVED** [review]
LGTM!

**Pull request merged**
