### PR TITLE
[FIX] RTL

### PR DESCRIPTION
**Pull request by ggazzo**
@RocketChat/core 

Closes #ISSUE_NUMBER

### CODE REVIEW

**Comment by cyclops24** [comment]
Thanks @ggazzo it seems that many of issues fixed. Just some small things need fixing.

**Comment by ggazzo** [comment]
@cyclops24 could you test again?

**Comment by rodrigok** [comment]
@ggazzo can you fix the conflicts?

**Comment by cyclops24** [comment]
Thanks @ggazzo :wink:

**Pull request merged**
