### PR TITLE
[FIX] teams.removeMembers client usage

### PR DESCRIPTION
**Pull request by dougfabris**

### CODE REVIEW

**Review by ggazzo — APPROVED** [review]

**Review by ggazzo — CHANGES_REQUESTED** [review]
Please create a api test for this case ;)

**Review by ggazzo — APPROVED** [review]

**Comment by sampaiodiego** [comment]
just a ping here, since the new test is failing

**Comment by dougfabris** [comment]
@sampaiodiego ready to go!

**Review by casalsgh — APPROVED** [review]
based on previous review and not additional code changes I'm approving this PR.

**Pull request merged**
