### PR TITLE
Added /invite slash command

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Allow invite via: `/invite username`

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
This would close #592

**Comment by rodrigok** [comment]
So nice :smile_cat: 

Can I invite user with @, like `/invite @rodrigo.rocket.team`?

Could make sense cause we can use auto complete of mention popup.

**Comment by geekgonecrazy** [comment]
heh no I didn't think of that.  Shouldn't be too hard to add though.  I'll try and add that real quick.  :)

**Comment by geekgonecrazy** [comment]
Actually.. not sure what's going on.  Even checking for and removing the '@' right before.  It doesn't seem to work.  Weird..

**Comment by rodrigok** [comment]
If you comment the package to prevent automatically installation I can accept your PR and help you :)

**Comment by geekgonecrazy** [comment]
Alright there we go.  Commented out.

**Comment by rodrigok** [comment]
@geekgonecrazy done :)

**Pull request merged**
