### PR TITLE
[FIX] Apostrophe is parsed correctly in display text of markdown URL

### LINKED ISSUE #10322: [BUG] Apostrophe misparsed in display text of markdown url
### Description:

If display text in [text] (url) or <url|text> contains an apostrophe, it is not properly displayed.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.0
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.4

### Steps to Reproduce:

Enter a message like [it's good] (https://www.google.com) // without space between text and url

### Expected behavior:
image

### Actual behavior:
image

### PR DESCRIPTION
**Pull request by fliptrail**
Closes #10322 
The link text is now un-escaped while displayed on the UI.

**Initial State**
imported

**Final State**
Screenshot from 2019-03-18 22-42-04

### CODE REVIEW

**Comment by knrt10** [comment]
@fliptrail why do you have commits for different branches? You should rebase and checkout before committing

**Comment by fliptrail** [comment]
@knrt10 I will take care of that from next time.

**Comment by knrt10** [comment]
@fliptrail you can still fix this. rebase your branch with develop branch and force push the changes

**Comment by fliptrail** [comment]
> @fliptrail you can still fix this. rebase your branch with develop branch and force push the changes
Actually, I forgot and I already have a PR on develop branch open.

**Comment by engelgabriel** [comment]
@sampaiodiego is there any security risk involved in not scaping the title?

**Comment by rodrigok** [comment]
We apologize for not getting a review on this sooner.

Unfortunately `unescapeHTML` isn't the correct solution, if you try `[it<span style="color:red;">s good](https://www.google.com)` you see that you can inject HTML code what leads to XSS security injection.

I'll close this PR by know, please open a new one if you find a better solution.

Thanks

**Pull request closed without merging**
