### PR TITLE
Command room archive unarchive

### PR DESCRIPTION
**Pull request by Deepakkothandan**
@RocketChat/core 

Slash Command for Room Archive and Room Unarchive

### CODE REVIEW

**Comment by marceloschmidt** [comment]
LGTM

**Comment by rodrigok** [comment]
LGTM

**Comment by graywolf336** [comment]
What about instead of notifying the current user the room was archived, the entire channel gets messaged saying the channel is now archived?
> @username has archived this channel.
and
> @username has unarchived this channel.

**Comment by rodrigok** [comment]
Great point @graywolf336, I totally agree with you

**Comment by marceloschmidt** [comment]
I'm making those changes and then I'll accept this PR

**Comment by Deepakkothandan** [comment]
@marceloschmidt Thank you for making the changes, I was trying with the function notifyall and notifyroom and could not get it to work. I never thot of this way of doing it. Maybe next time I will ask for your suggestions :smile:

**Pull request merged**
