### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by Sopheaks60**
I was translate Rocket Chat competed into Khmer(Cambodian) Language, How can I commit it.

### CODE REVIEW

**Comment by rodrigok** [comment]
Hey @Sopheaks60, seems that you made changes in branch **semantic-ui** that doesn't is merged with our master branch, it's a test with semantic-ui installed. So this PR has 260 changed files hehe.

You need to copy the files you have translated and update them in branch master and then create a PR from your master to our master, then only your changes will be show as **Files changed** here.

Ok?

**Comment by Sopheaks60** [comment]
Could you tell me how can I update it?
While I try to run git pull it is no permission.
Could you provide me some step?

**Comment by rodrigok** [comment]
* Fork this repo (You already did)
* Clone your fork to your machine
* Do your changes in files
* Commit your changes and push to your repo
* Open GitHub and create a new PR from your master to our master

You can work in branch master or you can create a new branch in your fork. You will create the PR from the branch that you've changed to our master, but never use another branchs for our repo because they have changes that don't could be merged to our master.

**Comment by engelgabriel** [comment]
@Sopheaks60 can you send us the file via email?

**Comment by Sopheaks60** [comment]
I sent it to you ready where email.

**Pull request closed without merging**
