### PR TITLE
[NEW] Remove exif metadata from uploaded files

### PR DESCRIPTION
**Pull request by KevLehman**
## Issue(s)

https://app.clickup.com/t/vb7dwv
## Further comments

- The library was one of the only ones with no external dependencies (a lot rely on `exiftool` for doing the removal)
- Library was almost the only one with stream support
- It didn't work only for JPEGs, although it's the most common format that includes exif data
- Metadata from other file types (pdf, video files) is not removed. The good part is that videos/files containing metadata are far less common than images.
- If we want to add support for all image/video types, we would need a combination of `exiftool` + `ffmpeg`

### CODE REVIEW

**Comment by KevLehman** [comment]
Huh, interesting, I didn't know we typechecked the packages too 🤔

**Comment by sampaiodiego** [comment]
wut.. I didn't know as well :thinking: weird

**Comment by KevLehman** [comment]
@sampaiodiego I can copy the code from the library into RC, however 🤔 it bugs me on why it's trying to typecheck the module.

**Comment by sampaiodiego** [comment]
@KevLehman can you maybe take a look if that is the intended behavior of `tsc`? or if there is a flag we can provide to not do that? or maybe something on our `tsconfig.json`

**Comment by KevLehman** [comment]
@sampaiodiego it's weird, indeed. It looks like it's related to the `import` statement. Basically, when you `import` something, `tsc` will see it and try to compile it (ref https://github.com/microsoft/TypeScript/issues/41883#issuecomment-831235280)

Changing the `import` for a require fixes the issue, but it doesn't look like a clean solution 😬 what do you think?

**Review by sampaiodiego — APPROVED** [review]

**Pull request merged**
