### PR TITLE
Add filter to allow/deny @all

### PR DESCRIPTION
**Pull request by thomasspiesser**
@RocketChat/core 

With this PR, an administrator has the option the deny the use of the `@all` tag.
bildschirmfoto 2016-07-06 um 09 48 49
Administrators, room moderators and owners are not affected and can still use the `@all` tag.

When a regular user tries to use it and it is has been denied by the admin, the message is not send and the user is informed about it.
bildschirmfoto 2016-07-06 um 09 49 26

Info: "Alle Benutzer in diesem Raum benachrichtigen ist nicht erlaubt" is the german t9n for "Notify all in this room is not allowed".

### CODE REVIEW

**Comment by rodrigok** [comment]
Awesome, can you add a description for this setting to warn that admins, moderators and owners can still use?

**Comment by thomasspiesser** [comment]
Sure! Where would you like to show this warning?

**Comment by danielwegener** [comment]
I'd rather like this feature as a `mention-all` permission.

**Comment by thomasspiesser** [comment]
All for it! What would I need to change for that?

**Comment by rodrigok** [comment]
@thomasspiesser you should use `RocketChat.authz.hasPermission(Meteor.userId(), 'mention-all')` instead of the setting check and add that permission here https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-authorization/server/startup.coffee

**Comment by thomasspiesser** [comment]
@rodrigok thanks, let me know if i got it right.

**Comment by rodrigok** [comment]
@thomasspiesser awesome, did you test? I think you should add user by default to the list of roles of that permission.

**Comment by thomasspiesser** [comment]
@rodrigok OK, I added `user` to the permission default. I did test it and it seems to work like a charm.

**Comment by rodrigok** [comment]
Awesome, thanks

**Pull request merged**
