### PR TITLE
[FIX] Correcting the case there are no result in admin users list 

### LINKED ISSUE #21548: Search by email in admin users list causes error
### Description:

Searching users by email causes an error

### Steps to reproduce:

1. Go to the administration section
2. Click on Users
3. Type an email of a user you'd like to search

### Expected behavior:

I expect to have the user show up or be told no user is found

### Actual behavior:
image

### Server Setup Information:

- Version of Rocket.Chat Server: **3.13.1**
- Operating System: **Ubuntu 16.04.7 LTS** 
- Deployment Method: **Docker**
- Number of Running Instances: **1** 
- DB Replicaset Oplog: **yes**
- NodeJS Version: **12.2**
- MongoDB Version: **4.0**

### Client Setup Information

- Desktop App or Browser Version: **3.1.1**
- Operating System: Linux Mint

### Additional context

N/a

### Relevant logs:

```I20210413-20:49:34.072(0) server.js:204 API ➔ debug get users.list threw an error: TypeError: Cannot read property 'total' of undefined  at Object.get (app/api/server/v1/users.js:273:48)   at app/api/server/api.js:394:82 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 ```

### PR DESCRIPTION
**Pull request by Jeanstaquet**
## Proposed changes (including videos or screenshots)

I added a default case to the total when there are no result to the user's query 

https://user-images.githubusercontent.com/45966964/114737105-fba38000-9d46-11eb-972e-4d92de531c95.mp4

## Issue(s)

Fixes #21548

### CODE REVIEW

**Comment by robbyoconnor** [comment]
This is cleaner than https://github.com/RocketChat/Rocket.Chat/pull/21558

**Comment by robbyoconnor** [comment]
There is a need to rebase.

**Comment by Jeanstaquet** [comment]
Hello @robbyoconnor what do you mean ?

**Comment by robbyoconnor** [comment]
> Hello @robbyoconnor what do you mean ?

I meant yours is a cleaner fix.

**Review by ggazzo — APPROVED** [review]

**Comment by robbyoconnor** [comment]
w00t thanks @ggazzo and @Jeanstaquet

**Comment by robbyoconnor** [comment]
Not sure if this fixed the issue or if it was included in the 3.13.3 but I still have this issue.

cc: @johncrisp @ggazzo

**Comment by Jeanstaquet** [comment]
@Jeanstaquet I will also look at it

**Comment by robbyoconnor** [comment]
@Jeanstaquet not sure though, they could have just cherry-picked the security fix onto the release branch, so it's very likely that it may be slated for the next release.

**Comment by Jeanstaquet** [comment]
@robbyoconnor On my side everything works propely, this is exaclty the sale bug on your side ?

**Comment by robbyoconnor** [comment]
Yeah, search for an email that doesn't exist and it errors out for me.

**Comment by robbyoconnor** [comment]
@Jeanstaquet it will be in the next release that's currently in the rc phase.

**Comment by Jeanstaquet** [comment]
Ok perfect, thanks for the follow up @robbyoconnor

**Pull request merged**
