### PR TITLE
Add room leader to chat

### PR DESCRIPTION
**Pull request by danischreiber**
[NEW] Show room leader at top of chat when user scrolls now. Set and unset leader as admin.

### CODE REVIEW

**Comment by danischreiber** [comment]
Hi Diego, Ill put those methods back.

I agree about the DOM changes, but I couldn't figure out how to get the
fname into that collection, so I went this way. If you can help me figure
it out, I'm happy to use the old implementation.

**Comment by danischreiber** [comment]
It looks like the reason those methods aren't in the pull request is
because they were already committed by Nascimento:
[image: Inline image 1]
Was the original version of the leader code added to the master develop
branch already?

**Comment by sampaiodiego** [comment]
> Was the original version of the leader code added to the master develop
branch already?

there were not. looks like email image attachments does not work, I cannot see the image you sent.

**Comment by danischreiber** [comment]
Closing because I opened a new PR from a branch rebased from develop

**Pull request closed without merging**
