### PR TITLE
Regression: Fix call direction

### PR DESCRIPTION
**Pull request by murtaza98**
## Issue(s)

Right now all calls are being marked as inbound, even the outbound ones

### CODE REVIEW

**Review by aleksandernsilva — APPROVED** [review]

**Review by cauefcr — APPROVED** [review]
LGTM!

**Comment by KevLehman** [comment]
Can you check if this won't conflict with the changes I did on Tiago's PR? Thanks!

**Comment by murtaza98** [comment]
> Can you check if this won't conflict with the changes I did on Tiago's PR? Thanks!

@KevLehman nice catch. I've updated this PR to match the changes there so conflicts won't happen

**Review by KevLehman — APPROVED** [review]

**Comment by KevLehman** [comment]
Build's failing, but it don't wanna say why :trollface: can you take a look?

**Comment by murtaza98** [comment]
> Build's failing, but it don't wanna say why :trollface: can you take a look?

All green now :smile:

**Review by KevLehman — DISMISSED** [review]

**Review by MartinSchoeler — APPROVED** [review]

**Review by KevLehman — APPROVED** [review]

**Pull request merged**
