### PR TITLE
[NEW] Migration document for Sandstorm version to standalone

### PR DESCRIPTION
**Pull request by peterlee0127**
[NEW] Migration document for Sandstorm version to standalone version

Due to sandstorm version is difficult to maintain. There are many issues (powerbox,sandbox) can't fix easily. This document can let user to migrate their sandstorm version Rocket.Chat to standalone version. (to the latest version :) 👍 )

### CODE REVIEW

**Comment by engelgabriel** [comment]
Could you also add this content to https://github.com/RocketChat/docs/blob/master/installation/paas-deployments/sandstorm-io/README.md 

And maybe just put a reference to https://rocket.chat/docs/installation/paas-deployments/sandstorm-io/ in this README.md ?

**Comment by peterlee0127** [comment]
Sure.

**Comment by peterlee0127** [comment]
It's seems develop branch of .sandstorm is removed. So, where should I put this document ?
thanks

**Comment by engelgabriel** [comment]
@rodrigogs should we keep the .sandstorm folder for reference?

**Pull request closed without merging**
