### PR TITLE
Prevents listing inactive users on member list (#792)

### LINKED ISSUE #792: Deactivated Users Show Up on Member List
Maybe I don't understand the purpose of deactivating a user, but I would think that a user who is deactivated wouldn't show up anywhere in the member lists except on the administration pieces.

### PR DESCRIPTION
**Pull request by gmsecrieru**
Should close #792

### CODE REVIEW

**Comment by graywolf336** [comment]
:+1:

**Comment by rodrigok** [comment]
@gmsecrieru you've tested your solution? I think this will not work.

The field **active** of user's record is not sent from server to client.

**Comment by marceloschmidt** [comment]
@gmsecrieru a possible solution for this would be to edit `publications/activeUsers.coffee` and add `active: true` to the `Meteor.users.find` query. This way the publication would not even send the inactive users to the client and there would be no need to check that on client side. Another option, though *not* recommended, would be to pass the `active` field in the fields list of this publication, but that would only be useful if you were doing anything with the inactive users, that would require them to be present on client side, which I do not believe we need right now.

**Comment by gmsecrieru** [comment]
Thanks for your input and forgive me if my findings stated below are not correct as I am still learning/researching into our code base, but answering your comments:

@rodrigok Yes, I've tested and it does work here:

*Searching for inactive user*
screen shot 2015-09-14 at 14 23 22

*Searching for active user*
screen shot 2015-09-14 at 14 23 36

@marceloschmidt I think we do use inactive users at the moment. Check out the Admin's  "Users" panel:
screen shot 2015-09-14 at 14 23 56

**Comment by marceloschmidt** [comment]
@gmsecrieru When you are in the admin panel, once you select a user, it uses the `fullUserData` publication, which is only available for admins and that's why there you have the `active` flag. Try the following test: without being at the admin panel (or without having selected the testdummy), go to the same search and do your test again. You'll find that testdummy won't show either when activated or not activated. In fact, no user will return, unless you have selected it on admin panel.

**Comment by gmsecrieru** [comment]
@marceloschmidt I have created a third user (which is not admin) and performed the following tests:

*Search for an active user*
screen shot 2015-09-14 at 14 42 04

*Search for an inactive user*
screen shot 2015-09-14 at 14 42 15

Not sure if I am missing something or if we (even accidentally) already have this data on client somehow. I think I will be able to log into the Demo server in about an hour, maybe we can talk this through better! 

Thanks again!

**Comment by marceloschmidt** [comment]
@gmsecrieru I see the problem. In fact, when you used `active: true` on `createChannelFlex` and `directMessagesFlex`, you are actually using that on server subscription, where it is totally fine to use that flag. The problem I believe is with membersList. Have you successfully displayed more than yourself in members list? Try logging in with two users and check the members list, see if you can see both users online. I know I should have downloaded your code before trying to provide a solution for what I *think* doesn't work ;)

**Comment by gmsecrieru** [comment]
@marceloschmidt Yes, it's there! For what it's worth, "george" is and Admin user, thus I don't know if that would reflect by any means in the result of "third.user" member list

screen shot 2015-09-14 at 15 12 01

**Comment by marceloschmidt** [comment]
Ok! I'll give it a proper testing later on :) sorry for not doing it before.


--
Marcelo Schmidt

**Comment by gmsecrieru** [comment]
Take your time and thanks!

**Comment by marceloschmidt** [comment]
My bad (and @rodrigok's), you were right! Since all your conditions belong to autocomplete filter settings, they are all run on server side, so they are right! This PR is ready for merge @engelgabriel.

**Pull request merged**
