### PR TITLE
fix: oauth login by redirect failing on firefox

### LINKED ISSUE #23043: Firefox OAuth login fails (comes back to login page) for some RC instances
### Description:

OAuth login fails since some time for the combination of Firefox and certain RC instances. Chrome OAuth login works just fine, so does the OAuth login with same FF browser and RC version on other instances.

Only thing I can see in FF when it fails is the following (maybe unrelated) error in the JS console:
The Notification permission may only be requested from inside a short running user-generated event handler.

I just retested with latest RC 3.18.0-rc.0 and can provide two demo instances for testing:
a) https://bb-compat.egroupware.de/rocketchat/ fails with FF :(
b) https://bb-trunk.egroupware.de/rocketchat/ works apart from bug described in #23024, which happens independent of used browser

To test you need to click on [EGroupware users click here] button to initiate the OAuth login. For credentials please ping @ralfbecker @ open.rocket.chat. (The RC instance might take 1-2 minutes to start up, if not already started!)

### Steps to reproduce:

1. Open above URL a) with Firefox to see failure for FF
2. Click on [EGroupware users click here] button to initiate the OAuth login
3. Log in with provided credentials (see above)

### Expected behavior:

After redirector from authorization server you should be logged in RC (as it works with Chrome or URL b).

### Actual behavior:

You're back on the RC login page

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.0-rc.0 down to at least 3.15.x maybe longer
- Operating System: Linux
- Deployment Method: docker with official rocketchat/rocket.chat container
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: depending on RC version
- MongoDB Version: 4.2.13

### Client Setup Information

- Desktop App or Browser Version: latest Firefox 91.0.2
- Operating System: Windows or MacOS tested

### Relevant logs:

RC docker logs show no error.

### LINKED ISSUE #30545: OAuth with Login Style "Redirect" does not work anymore in Firefox (Chrome works fine)
### Description:

After updating to Rocket.Chat 6.4.0 we see the following issue:

Our custom OAuth does not work anymore in Firefox when Login Style "Redirect" is selected. After clicking the login button and entering the credentials on our login page the user is redirected back to the RC login page. Clicking the login button again loops back to the login page. The problem does **not** occur in Chrome or in the apps. Also, the login work properly when the Login Style is changed to "Popup" (this is our current workaround).

### Steps to reproduce:

1. Open RC login page in Firefox.
2. Click on OAuth login button of a custom OAuth-provider with Login Style set to "Redirect".
3. Enter credentials on OAuth provider page.

### Expected behavior:

Login to RC (show homepage / default channel).

### Actual behavior:

The user is always redirected back to the RC login page after successful OAuth login.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.0
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.21 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Firefox 102.14.0esr (64-Bit) / 118.1.0 (Android app)
- Operating System: Linux / Android

### Additional context

Our issue looks exactly like https://github.com/RocketChat/Rocket.Chat/issues/20374, which has been fixed in https://github.com/RocketChat/Rocket.Chat/pull/20722. Could this be a regression, i.e. that the workaround https://github.com/RocketChat/Rocket.Chat/blob/6.4.0/apps/meteor/app/custom-oauth/client/swapSessionStorage.js does not work anymore?

Also, https://github.com/RocketChat/Rocket.Chat/issues/23043#issuecomment-1641596320 could be the same issue.

### Relevant logs:

There are no relevant entries in the server log.
In the Firefox console we see the following error (stack trace shortened for readability):

`Object { stack: "r@https://chat.example.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:1:4644\nn@https://chat.example.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:92:18922\n_livedata_nosub@https://chat.example.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:92:18994
[...]@https://chat.example.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:246:381731\n", isClientSafe: true, error: "not-allowed", reason: undefined, details: undefined, message: "[not-allowed]", errorType: "Meteor.Error" }
SDKClient.ts:86:13`

### LINKED ISSUE #30688: [6.4.2/3/4] Custom OAuth (Keycloak) - OpenID Connect - issue with Firefox - working with Chromium
### Description:

Custom OAuth login (Keycloak) not working working with Firefox normal and privacy mode. Same on different OS (Linux and Windows 10). This was not the case with Rocket.Chat 6.3.10
Working with Chromium, Edge.

### Steps to reproduce:

1. Setup OAuth Provided with Keycloak and use Firefox 118.0.2 to login.
2. Entering credential into Keycloak
3. Redirect to Rocket.Chat reaches login page

### Expected behavior:

Getting logged into Rocket.Chat

### Actual behavior:

Staying on the login page

### Server Setup Information:

- Version of Rocket.Chat Server:  6.4.2 / 6.4.3 / 6.4.4
- Operating System:  Rocky Linux 8.8.
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  yes
- NodeJS Version:  14.21.3
- MongoDB Version: 5.0.21

### Client Setup Information

- Browser Version: Firefox 118
- Operating System: Windows 10 and Fedora 39

### Additional context

Issue happened on my test system after upgrading to Rocket.Chat 6.4.2 from 6.3.10

### Relevant logs:

No error is present in the logs.

### PR DESCRIPTION
**Pull request by pierre-lehnen-rc**
## Issue(s)

Closes #30545 
Closes #23043 
Closes #30688

### CODE REVIEW

**Comment by TimmiORG** [comment]
@pierre-lehnen-rc what will be the ETA for this fix?

**Comment by andreaswolf** [comment]
Can confirm that this works in our setup, in Firefox in regular and private mode. IIRC the login used to also work in private mode, but not in regular mode with the latest 6.4 release.

**Review by MarcosSpessatto — APPROVED** [review]

**Comment by andreaswolf** [comment]
Is there anything I can do to support a quick merge + release of this fix? The 20th is approaching rapidly and this bug is blocking us from rolling out RocketChat 6.4 to our users.

**Comment by TimmiORG** [comment]
Hi @casalsgh 
any chance to get this fix earlier than 6.6.0?

**Comment by casalsgh** [comment]
> Hi @casalsgh any chance to get this fix earlier than 6.6.0?

Checking into it and possibly having a patch release. Might be a few days before I get back, but is on my list.

**Comment by jessicaschelly** [comment]
Validated that the fix is working on Firefox, Chrome, Edge, and Safari. Other types of login such as "Popup" continue to work as well.

**Comment by Gummikavalier** [comment]
Confirmed working for us with RC 6.4.6 and Firefox. :thumbsup:

**Comment by BigSnicker** [comment]
Great stuff. Working perfectly for us. Thanks for all the work.

**Pull request merged**
