### PR TITLE
[FIX] adjustments for tooltips to show room name instead of id

### LINKED ISSUE #14083: [BUG] tooltips show room id in discussions
### Description:

when setting a member as leader, owner or moderator the tooltip that appears on the top right of the page shows the room id instead of the name

### Steps to reproduce:

1. Go to any discussion you created
2. Click on members list
3. Open the options list for any user
4. Click on set as moderator, owner or leader
### Expected behavior:

it should show room name

### Actual behavior:
image

### Additional info

i'm working on the issue

### PR DESCRIPTION
**Pull request by mohamedar97**
Closes #14083

### CODE REVIEW

**Comment by knrt10** [comment]
@mohamedar97 I saw that you are creating different PRs for same type of issue. What you could have done is create a one PR will all the changes. It would be helpful for others to manage when merging. Now don't change it, from next time remember it because it would be helpful for you too to manage one PR than many with same kind of solution. Hope this helps, thanks

**Comment by mohamedar97** [comment]
i'm thought this how things work here so i created different PRs. if i delete two of the 3 PRs and commit all of the changes to the initial PR would that be better?

**Comment by knrt10** [comment]
It’s ok, don’t worry now. It’s for future reference. 🙂

**Comment by mohamedar97** [comment]
absolutely not. i really appreciate how tolerant you are with me since i started contributing to RC

**Comment by knrt10** [comment]
That’s what Open source community is for. You learn and help others learn 🤟🏼

**Pull request merged**
