### PR TITLE
[NEW] Fix Issue #5453 - Convert (Y) to thumbs up emoji

### LINKED ISSUE #5453: Convert (Y) to thumbs up emoji like :) is
Your Rocket.Chat version: 0.48.2

As (Y) is quite popular for a thumbs up 👍 , it would be good to get it to automatically in the same way that :) and :( works

### PR DESCRIPTION
**Pull request by vaibhav4595**
@RocketChat/core 

Closes #5453 
screen shot 2018-03-09 at 1 10 00 am

Adding code that converts `(y)` and `(Y)` to the 👍 emoji. Works standalone and within-text.

### CODE REVIEW

**Comment by rodrigok** [comment]
Hi @vaibhav4595 thanks by your contribution.

Can you fix the lint errors?

**Comment by vaibhav4595** [comment]
@rodrigok I have tried fixing the lint errors.

**Comment by geekgonecrazy** [comment]
also implemented in: #5490

This implementation is a bit better.. but wonder if still should be something like @sampaiodiego comment here: https://github.com/RocketChat/Rocket.Chat/pull/5490#issuecomment-271880567

**Comment by sampaiodiego** [comment]
I still find the hacky solution better 😛

**Comment by graywolf336** [comment]
I agree here :)

**Comment by pierre-lehnen-rc** [comment]
Closing in favor of #16559

**Pull request closed without merging**
