### PR TITLE
[IMPROVE] UI of Permissions page

### LINKED ISSUE #13700: The current UI of Permissions page is unsatisfactory
### Description:

The current UI of admin/permissions page is unsatisfactory and looks very poor. 
Especially where Text in permissions is embedded in HTML twice, both name and _id.
Also, the livechat permissions expand out of view. 

### Steps to reproduce:

1. Be the Admin of a server
2. Click on triple dots in sidebar --> Administration
3. Go to Permissions tab

### Expected behavior:

It should look nice to user.

### Actual behavior:

Screenshot from 2019-03-14 04-21-23

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0 - develop
- Operating System: Ubuntu 18.0.10
- Deployment Method: Local
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.4 x86
- MongoDB Version: 

### Additional context

I am working to improve it majorly.

### PR DESCRIPTION
**Pull request by fliptrail**
Closes #13700 

This improves the UI of Permissions page. Now, **all the roles are properly visible** with horizontal scroll support for small screen devices. The text alignment and size of check boxes have been changed as well as size of edit icon. Also, now, the names of permissions are visible and the ID of permissions is hidden, (which earlier was redundant).

**Initial State**
Screenshot from 2019-03-14 04-21-23

**Final State**
Screenshot from 2019-03-15 20-38-39

### CODE REVIEW

**Comment by ggazzo** [comment]
hey man before commit try run `./node_modules/stylelint/bin/stylelint.js --fix "app/**/*.css"`

**Comment by engelgabriel** [comment]
The ID only looks redundant in English, but they are very helpful in other languages.

**Comment by fliptrail** [comment]
@engelgabriel For a user in another language, he would be able to see Permission in his native language as well as the Permission in ID (english). I personally, think that it would be redundant. However if you suggest, I can push a commit to display the ID in a smaller font and a greyed out color. That would be more appealing to the user. The rest of my commits focus on displaying of all roles and horizontal scrolling on small devices.

**Comment by engelgabriel** [comment]
Ok, let's try the following:

- Alight the first column to the left and remove IDs, but remove keep it a single line, so it is easy to read.
- Rotate the role names 90deg with `transform: rotate(-90deg);`
- Add IDs back on a new LAST column

The result should be something similar to the "Browser compatibility" table at https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation#Browser_compatibility

image

**Comment by engelgabriel** [comment]
The Permission ID in a smaller font and a greyed out color in monospace font underneath could look good too.

**Comment by fliptrail** [comment]
Working on it.

**Comment by fliptrail** [comment]
Screenshot from 2019-03-17 06-03-14
@engelgabriel Please review, did as suggested.

**Comment by engelgabriel** [comment]
Thank you so much @fliptrail it is almost perfect. I have some suggestions to make it a bit better, but they are not required for us to merge this PR.

1. The checkboxes should be in the vertical center of the line.
2. Something is making the columns have different widths, they should all have the same width.
3. Remove the black lines, as we don't use them anywhere on the project.
4. Keep the role names also in a single line and remove the unnecessary edit icon.

**Comment by fliptrail** [comment]
Edit icon is I guess necessary to show that roles can be edited.
I guess without black borders the table would look odd
Please give your reviews.

**Comment by fliptrail** [comment]
I will try to put custom checkboxes.

**Comment by engelgabriel** [comment]
> I will try to put custom checkboxes.

I don't have a problem with the native checkboxes, keep them. Just fix the vertical alignment.

**Comment by engelgabriel** [comment]
Thank you so much @fliptrail 
@ggazzo please merge this and let's do any minor improvements later.

**Pull request merged**
