### PR TITLE
[IMPROVE] Unread threads on top.

### LINKED ISSUE #21088: Unread threads not displayed on top.
### Description:
In a channel with many users, we need to scroll to find all our unread threads.

### Steps to reproduce:

1.  Make a thread
2. Reply on a previous thread from a new account.
3. Make a new thread 

### Expected behavior:
Unread threads should be displayed on top

### Actual behavior:
Unread threads are not displayed on top.

https://user-images.githubusercontent.com/55157259/110916013-5871dc00-833e-11eb-8102-d8d9e5a4b72a.mp4

### Server Setup Information:

- Version of Rocket.Chat Server:3.13.0-develop 
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu

### Additional context
Working

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)

Unread threads would be displayed on top.

https://user-images.githubusercontent.com/55157259/110916357-b999af80-833e-11eb-8a72-024f752e3659.mp4

## Issue(s)

Closes #21088

### CODE REVIEW

**Comment by Darshilp326** [comment]
@dougfabris Please review! :smile:

**Comment by Darshilp326** [comment]
@dougfabris Please review! :smile:

**Comment by engelgabriel** [comment]
Thanks for your contribution, but I am not sure I agree with the change. We have a filter to display only the unread threads. The view "all" threads mode, show all thread by activity. If we decide to change it, we need to make sure the query on the DB also is using the same logic.

**Comment by Darshilp326** [comment]
> Thanks for your contribution, but I am not sure I agree with the change. We have a filter to display only the unread threads. The view "all" threads mode, show all thread by activity. If we decide to change it, we need to make sure the query on the DB also is using the same logic.

Hello! Which filter are you talking about?

**Comment by yash-rajpal** [comment]
I think this is the one @Darshilp326 
image
If a user wants to see unread threads, user can select the `unread` from the following.

**Comment by Darshilp326** [comment]
> I think this is the one @Darshilp326
> image
> If a user wants to see unread threads, user can select the `unread` from the following.

Ohh my bad! Completely missed that filter. Closing this PR.

**Pull request closed without merging**
