### PR TITLE
[FIX] "Enter usernames" placeholder is cutting in "create channel" view

### PR DESCRIPTION
**Pull request by TheReal1604**
@RocketChat/core 

Closes https://github.com/RocketChat/Rocket.Chat/issues/8785

before:
bildschirmfoto 2017-12-19 um 23 14 52

after:
bildschirmfoto 2017-12-20 um 00 07 18

### CODE REVIEW

**Comment by rodrigok** [comment]
Idk if it's the best solution for it. It will break the input to the second line as soon we add a new tag/user.

@karlprieb thoughts?

**Comment by TheReal1604** [comment]
@rodrigok with 70% it breaks at the second username and it is displayed correctly..

**Comment by ggazzo** [comment]
@TheReal1604 `flex:1` doesn't solve your problem?

**Comment by TheReal1604** [comment]
@ggazzo flex:1 seems to fix it at the first view.. BUT.. you get this after entering usernames (also cutted at the end):

bildschirmfoto 2017-12-20 um 20 55 21

**Comment by rodrigok** [comment]
@TheReal1604 but it's better than create a new line after first tag or cut the placeholder at the beginning don't you think?

**Comment by TheReal1604** [comment]
@rodrigok For me as a user it looks really unpolished and broken if something gets cutted. :/

I think a better way is to hide the description of the field if a username is selected. This should look consistent. What you think?

**Comment by rodrigok** [comment]
@karlprieb what do you think 🔝

**Comment by karlprieb** [comment]
@TheReal1604 @rodrigok I agree, we can use `flex: 1` to fix the "placeholder" width and when the first user is added we can hide/remove the placeholder.

**Comment by TheReal1604** [comment]
That sounds awesome! @karlprieb I have unfortunately no idea how to do the hiding thing. I correct the pull request to `flex:1`. Can you take a look?

**Comment by karlprieb** [comment]
@TheReal1604 Yep, I'll take a look! :)

**Comment by rodrigok** [comment]
@ggazzo meanwhile I'll merge this PR cuz it improves the current behavior.

**Pull request merged**
