### PR TITLE
Fix confusing text labels on audio/video chat buttons.

### PR DESCRIPTION
**Pull request by ndarilek**

### CODE REVIEW

**Comment by ndarilek** [comment]
Any plans for this? I'd like to use rocket.chat as an audio/video chat solution, but as a blind user I find the existing labels a bit confusing. This should fix those.

Thanks.

**Comment by marceloschmidt** [comment]
Hello @ndarilek . I think your change is very important, but I'm concerned about the layout changes. Would it work to add descriptive labels as title attributes to the button tags, somehting like `<button class="start-audio-call button" title="Join audio call"><i class="icon-phone"></i></button>`? Thanks.

**Comment by ndarilek** [comment]
Title attributes are bad for accessibility because they aren't 
consistently presented.

What we can do is move the text into an aria-label attribute, meaning it 
won't be visible to anything other than screen readers. But if you're 
going to have visual text at all, having it just be the word "Start" 
followed by a visual symbol of what is starting is very confusing for me 
as a screen reader user.

Do you need all of the text to be an aria-label? If so I can make that 
change and push it.

**Comment by marceloschmidt** [comment]
Yes, please make that change, if you can. Thanks!

**Pull request closed without merging**
