### PR TITLE
Added 'Reset' button to return to default Theme

### PR DESCRIPTION
**Pull request by sarahabrahamson**
Added a 'Reset' button in admin.html and admin.coffee to change the 21 different color options back to the default values, which I found in "rocketchat-theme/server/variables.coffee". Problem brought up in issue #1244

### CODE REVIEW

**Comment by engelgabriel** [comment]
@RocketChat/core and @sarahabrahamson 
What do you think about creating a more generic feature, to reset ANY setting?
I started to update the Settings API here https://github.com/RocketChat/Rocket.Chat/pull/1449 so we could have a RESET method by ID or GROUP since we now know what the original value was.

**Comment by sampaiodiego** [comment]
I don't know if a generic button to reset any setting will work to themes (didn't check the code).. but I agree, a generic reset button to any setting could be great, as so this to themes :)

**Comment by engelgabriel** [comment]
Since #1449 has ben merged and now we have the metadata on the settings object 
```
valueSource
packageValue
processEnvValue
meteorSettingsValue
```
can we implement the generic reset button?

**Comment by geekgonecrazy** [comment]
@sarahabrahamson I'd still really love to see this. I've found my self wanting this several times recently

**Comment by engelgabriel** [comment]
Lets create an issue for that

**Comment by engelgabriel** [comment]
Lets do that with https://github.com/RocketChat/Rocket.Chat/issues/1244

**Pull request closed without merging**
