### PR TITLE
[FIX] Remove e2e from users endpoint responses

### LINKED ISSUE #12317: e2e private_key in REST /api/v1/users.list
### Description:

I am running a dev snapshot and I was testing out the REST API.

When calling /api/v1/users.list on my server, I get the e2e data for every user for my bot-user, including the private Keys. Is this an expected behavoir? Should maybe only be the public key be exported?

The Private key of only the user who is asking for the data?

### Steps to reproduce:

1. have a rest user with role bot
2. authenticate via curl https://server/api/v1/login -d "username=rest1&password=SECRET
3. query users via curl -H "X-Auth-Token: xxx" -H "X-User-Id: yyy" https://server/api/v1/users.list

### Expected behavior:

Userlist without security sensible data.

### Actual behavior:

Userdata with sensitive user data:

```
      {
         "active" : true,
         "utcOffset" : 2,
         "language" : "en",
         "username" : "user1",
         "e2e" : {
            "public_key" : "{\"alg\":\"RSA-OAEP-256\",\"e\":\"AQAB\",\"ext\":true,\"key_ops\":[\"encrypt\"],\"kty\":\"RSA\",\"n\":\"XXX\"}",
            "private_key" : "{\"$binary\":\"YYY==\"}"
         },
         "_id" : "XXX",
         "type" : "user",
         "name" : "My Admin",
         "status" : "online"
      }
```

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.0-develop
- Operating System: Debian stable 4.9.0-8-amd64
- Deployment Method: git clone and local build
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.12.0
- MongoDB Version: 3.2.11-2+deb9u1

### PR DESCRIPTION
**Pull request by MarcosSpessatto**
Closes #12317

### CODE REVIEW

**Comment by sampaiodiego** [comment]
@graywolf336 I think as far as we don't know how mobile will implement it, it is safer to exclude it at all

**Comment by graywolf336** [comment]
@rafaelks thoughts on the above?

**Comment by rafaelks** [comment]
@graywolf336 @sampaiodiego Is the public key being returned somewhere else so we can get it later?

**Comment by sampaiodiego** [comment]
@rafaelks yes, there is a set of new endpoints.. one of them is `e2e.fetchMyKeys` 😉

**Pull request merged**
