### PR TITLE
[FIX]  Thread header disappearing when header edited

### LINKED ISSUE #16230: Editing top message of a thread changes how the top message is displayed
### Description:

If you edit the first/top message of a thread this edited message will be no longer shown as a "main" message in the channel. Additionally switching to the the thread view will show the message twice.

### Steps to reproduce:

1. Create message and reply to it in thread:
grafik

2. Edit original message:
grafik

3. Results with errors highlighted by red arrows:
grafik

### Expected behavior:

- [ ] show the message in the main thread still as a big channel message
- [ ] do not show the message twice in the thread

### Actual behavior:

See screenshots in steps to reproduce

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 

### Client Setup Information

- Desktop App or Browser Version: 2.4.0 desktop app

### PR DESCRIPTION
**Pull request by ritwizsinha**
Closes #16230 
out

### CODE REVIEW

**Comment by ritwizsinha** [comment]
@ggazzo please review

**Comment by ritwizsinha** [comment]
@sampaiodiego please review

**Comment by ritwizsinha** [comment]
@gabriellsh please review

**Comment by ritwizsinha** [comment]
@gabriellsh please review

**Comment by rodrigok** [comment]
@ggazzo should we close this one in favor of the new threads implementation?

**Comment by rodrigok** [comment]
The new threads implementation will close this PR

**Pull request closed without merging**
