### PR TITLE
Accessibility fixes

### PR DESCRIPTION
**Pull request by ndarilek**

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Thanks for the contribution.  :+1: 

One thing real quick:

"Members List" isn't using i18n.

**Comment by ndarilek** [comment]
Good catch, does this fix it?

**Comment by geekgonecrazy** [comment]
It does.  Thanks!  :+1:

**Comment by ndarilek** [comment]
Excellent!

Any chance this fix might land in the Sandstorm package soon? Would love 
to see it there.

Thanks.

**Comment by geekgonecrazy** [comment]
@ndarilek absolutely.  I think a new release will be done very soon.  @Sing-Li might be able to give a better idea.

We're working on automating a lot of the different releases.  :)

**Pull request merged**
