### PR TITLE
[FIX] Reactions list showing users in reactions option of message action.

### LINKED ISSUE #20752: Reactions list in message actions renders blank.
### Description:
User reactions list on messages renders blank. 

### Steps to reproduce:

1. Message
2. React with any emoji
3. Select reactions from message action

### Expected behavior:
All users who have reacted with that emoji should be displayed.

### Actual behavior:
The list is blank.

https://user-images.githubusercontent.com/55157259/107857525-d41e5d00-6e54-11eb-9d6e-ab7b74d1d30b.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

### Additional context
Working!

### LINKED ISSUE #21002: The Reactions option doesnt show who have reacted what emoji on the message
### Description:

If we try to see the reactions on a particular message to check which users reacted what emoji, it just shows an empty modal

### Steps to reproduce:

1. Hover over any message
2. Click on the 3 dots option and then go to last option 'Reactions'
3. Click on Reactions 

### Expected behavior:

The modal should actually show who have reacted

### Actual behavior:

issue 3

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0
- Operating System: Windows (WSL)
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.x
- MongoDB Version: 4.x

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)

Reactions list shows emojis with respected users who have reacted with that emoji.

https://user-images.githubusercontent.com/55157259/107857609-5870e000-6e55-11eb-8137-494a9f71b171.mp4

## Issue(s)

Closes #20752 
Closes #21002

### CODE REVIEW

**Comment by Darshilp326** [comment]
Screenshot from 2021-02-14 02-07-28

Does it look better than the one in that PR video?
As users need to scroll less. :slightly_smiling_face:

**Comment by Darshilp326** [comment]
@ggazzo @dougfabris Please review :smile:

**Comment by dougfabris** [comment]
> @ggazzo @dougfabris Please review 😄

@Darshilp326 The reactions list is coming empty. Could you check what's happening? Btw nice improvement!

**Comment by dougfabris** [comment]
> @ggazzo @dougfabris Please review 😄

I made some fix changing the approach. Thanks!

**Review by dougfabris — APPROVED** [review]

**Pull request merged**
