### PR TITLE
[NEW] Add generic tag field to user

### PR DESCRIPTION
**Pull request by goiaba**
@RocketChat/core 

Beside the current username and real user name, this change introduces a generic field that can be mapped to any LDAP attribute. This new field, named tag, is invisible to the final user but is used in the users search functionality. For instance, suppose the LDAP attribute 'color' is mapped to 'tag'. After that, one could find all users whose 'color' LDAP attribute is blue by typing 'blue' in the searh field.

TODO: Update documentation (if accepted)

### CODE REVIEW

**Comment by graywolf336** [comment]
Why not use the `customFields` property of users that we already support?

**Comment by goiaba** [comment]
@graywolf336, Are they taken into account in the users' search? If so, then you are right and customFields is enough.

**Comment by graywolf336** [comment]
@goiaba Doesn't appear so, but maybe using that and adding that feature would be good since we do have quite a few users who use the `customFields`...but to what extent the `customFields` is actually used throughout Rocket.Chat itself, I don't personally know.

**Comment by goiaba** [comment]
@graywolf336 Good idea. I'll work on it.

**Pull request closed without merging**
