### PR TITLE
[Fix] Links containing ":"  will not be rendered as emoji

### LINKED ISSUE #12321: Links containing ":" (e.g. LinkedIn links) will render emojis
### Description:

Pasting links containing the colon character will render an emoji instead of the proper link text. This is problematic for all LinkedIn post links that contains segments with `urn:li:`:

### Steps to reproduce:

1. Paste a LinkedIn post link in any chat in Rocket.chat.
2. Link segments is converted to emoji.

### Expected behavior:

No emojis replaced inside links.

### Actual behavior:

image

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.5
- Deployment Method: Docker
- Number of Running Instances: 1

### Additional context

Possibly related to #6770

### PR DESCRIPTION
**Pull request by knrt10**
Closes #12321 & #6770

Steps to solve:-

To avoid this, HTML messages were split into an array. The array was looped and matched with URL RegEx. Only those were changed which did not match URL RegEx. 

Screenshot

screenshot 2019-03-03 at 4 21 51 pm

@tassoevan would you please review

### CODE REVIEW

**Comment by knrt10** [comment]
@rodrigok would you please review this

**Comment by knrt10** [comment]
@tassoevan @ggazzo any updates on this?

**Comment by knrt10** [comment]
@tassoevan can you please check this

**Comment by ggazzo** [comment]
hey @knrt10 thanks for your time, but I believe that code (#15516) are the best way to avoid emojis inside urls

**Pull request closed without merging**
