### PR TITLE
[NEW] Informal German translations

### PR DESCRIPTION
**Pull request by mrsimpson**
- Address users in an informal way
Liebe Deutsche :de: Anwender, wir kennen euch nun besser. Ab sofort wollen wir "Du" zu einander sagen
- Harmonize texts for "private Kanäle" / "Private Gruppen" => Always translate to "Kanäle"

### CODE REVIEW

**Comment by kaiiiiiiiii** [comment]
Please add a second language option for that

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mrsimpson** [comment]
@marceloschmidt we discussed this quite some time ago. Just seen the PR is still open.
I understand @kaiiiiiiiii 's concern about informalizing. However, I recall you wanted to have the informal one. I could also move the contents of these files to another language file, but you should decide what the default is: formal or informal?

**Comment by marceloschmidt** [comment]
When I think about formal vs informal in Portuguese, formal Portuguese sounds very inadequate for a software, while informal Portuguese may sound as poorly built, so we use a mix between the two, whatever "sounds" best. I say use your best judgement. Does formal sound too weird in that context? If so, try less formal... in Portuguese, we use a lot of English words, because translating them would be very weird, such as "Online" and "Logout" for example.

**Comment by kaiiiiiiiii** [comment]
@mrsimpson It’s may a pain in the arse to have two german translations, but we use RC in an enterprise environment and we definitely don’t want to use informal german on our installation :)

**Comment by mrsimpson** [comment]
@kaiiiiiiiii Finally, I managed to provide a second language option for informal german in Rocket.Chat (with TAPi18n as translation framework) 🎉
TAPi18n refers to the [IETF language tag specification](https://en.wikipedia.org/wiki/IETF_language_tag). In there, the following is stated:
> Optional variant subtags, separated by hyphens, each composed of five to eight letters, or of four characters starting with a digit; (Variant subtags are registered with IANA and not associated with any external standard.)

However, at least on my local build, the language variant is not accepted in TAPi18n! I could use some help from the TAPi18n-warriors around here (looking at you, @sampaiodiego ;) )

**Comment by mrsimpson** [comment]
Yup, also thought about Lingohub. But even if it didn’t: there are other (direct) ways of contributing to the informal translations. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mrsimpson** [comment]
@sampaiodiego I fought some more fights with TAPi18n - and kind of lost: I could not get it accept the IETF compliant language name `de-DE-informal`. 
The I played it dirty and invented a non-existent, but syntactically accepted language code `de-IN`. This way, TAPi18n and the above layers finally accept the language files. 🎉 
I don't really like this, but neither the end user should ever notice nor should other libs and tools like Lingohub trouble it.
If you accept: would you be so kind to merge it?

**Comment by sampaiodiego** [comment]
all my fights against TAPi18n ended as lost 😢 

I'll give it a try and merge it 😉

**Pull request merged**
