### PR TITLE
[FIX] Fixing the Channel List UI

### PR DESCRIPTION
**Pull request by shrinish123**
## Proposed changes (including videos or screenshots)

The last channel from the channel list was hidden by the logo, but now the last channel is properly visible as shown.

Before : 
initial

After : 
after

## Steps to test or reproduce
Just open the channel list, make many channels and check the last channel

### CODE REVIEW

**Comment by shrinish123** [comment]
@dougfabris Please Review :)

**Review by apurv-1 — APPROVED** [review]
Looks good to me.

**Comment by shrinish123** [comment]
@apurv-1 can we merge the pull request then ? Thanks for approving it

**Comment by dougfabris** [comment]
> @dougfabris Please Review

Unfortunately, we cannot move forward with your PR. This is not the correct approach to solve that. Thank you for helping us!

**Pull request closed without merging**
