### PR TITLE
Meteor update to 1.4.4

### PR DESCRIPTION
**Pull request by engelgabriel**
@RocketChat/core 

Closes #ISSUE_NUMBER

### CODE REVIEW

**Comment by karlprieb** [comment]
@engelgabriel Can we wait until tomorrow to merge this PR? I need to check what changed in some libraries.

**Comment by engelgabriel** [comment]
OK

**Comment by karlprieb** [comment]
I checked for jQuery, Moment and Spacebars changes and it's fine :) Thanks for waiting!

**Comment by engelgabriel** [comment]
This PR depends on:
https://github.com/meteor/meteor/issues/8515
https://github.com/meteor/meteor/pull/8516
https://github.com/abernix/meteor/commit/2140bf436ea557931932d813aecfc492379eb159

**Comment by fifou17** [comment]
😊

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Karl Prieb<mailto:notifications@github.com>
Envoyé le :vendredi 24 mars 2017 06:17
À : RocketChat/Rocket.Chat<mailto:Rocket.Chat@noreply.github.com>
Cc : Subscribed<mailto:subscribed@noreply.github.com>
Objet :Re: [RocketChat/Rocket.Chat] Meteor update to 1.4.3.2 (#6455)


I checked for jQuery, Moment and Spacebars changes and it's fine :) Thanks for waiting!

**Pull request closed without merging**
