### PR TITLE
[FIX] Trigger afterCreateUser even after registration

### PR DESCRIPTION
**Pull request by mrsimpson**
## Motivation

As an admin, I want to be informed about new users registering themselves, as I need to activate them individually. For this, I want to create an outgoing integration which triggers on "user created".

## Issue

The callback is not fired, though a user has been created: No username has been specified at this point in time, thus the callback is skipped - imho unnecessarily.

## Compatibility

This change is kind-of incompatible: Now, an `undefined` username might be passed to an integration. However, due to the very isolated nature of the webhooks, this should have no major impact on stability. A note in the release notes might help though.

### CODE REVIEW

**Comment by Hudell** [comment]
The problem is that the `afterCreateUser` event is also called when the username is set for the first time. Your change would make this event be called twice for the same user.

**Comment by rodrigok** [comment]
@mrsimpson is this ok to land on version 4 next month? Since it's a breaking change it's not possible to land on 3.1 but I agree with the change.

**Comment by mrsimpson** [comment]
@rodrigok sure it is. No need to hurry here.

**Comment by rodrigok** [comment]
Needs to create a new event for when the username is set so users can keep the behavior just switching the this new event if necessary.

**Pull request closed without merging**
