### PR TITLE
[WIP][FIX] Removes thread button for deleted messages

### LINKED ISSUE #16320: Deleting messages that have replies continues to show replies button
### Description:
When a message that has replies is deleted, the message is lost but the number of replies continues to be visible. However clicking on this button, the thread channel reproduces no replies. The thread is lost.

### Steps to reproduce:
1. Write a message, and reply to the said message (even a single reply will do).
2. Now delete the message you just replied to.
3. Click on the button that will show number of replies to said removed message.

### Expected behavior:
If the message is deleted, all the replies to it lose context so either they should also be removed or the **number of replies** button should not be visible anymore for the deleted message.

### Actual behavior:

On clicking the **replies** button, the main channel shows nothing.
ezgif-1-83e2bf2d0f6b

### Client Setup Information
- Desktop App or Browser Version: Google Chrome 79.0.3945.130 (Official Build) (64-bit)
- Operating System: Windows 10

### PR DESCRIPTION
**Pull request by lisa761**
Closes #16320 

This pull request checks whether the message body has length greater than zero to check if message exists and only when it exists does it show the replies button. This way, when a message that had replies is deleted by a user, the removed message will show no replies (unlike what we had previously) whereas the replies to the said removed message will become normal messages (like what was happening before).

### What happened before:
Screenshot from 2020-02-25 00-00-26
Screenshot from 2020-02-25 00-00-48
Screenshot from 2020-02-25 00-00-57

### What happens now:
Screenshot from 2020-02-25 00-08-12
Screenshot from 2020-02-25 00-08-24

### CODE REVIEW

**Comment by zdumitru** [comment]
> This way, when a message that had replies is deleted by a user, the removed message will show no replies (unlike what we had previously) whereas the replies to the said removed message will become normal messages (like what was happening before).

I don't think this is the right approach. Imagine there were other messages written in a channel in the meantime. And all of a sudden some new messages will appear in between them. I think that thread replies should remain thread replies even after main message has been deleted.

**Comment by lisa761** [comment]
@zdumitru Right, I have been thinking about it, I can't figure out how this should work, because if the main message gets deleted, the replies do not have a context anymore, which would still be the case even if they become normal texts. Would it be okay to delete those replies? or should we let it be, and just try to link the replies to deleted messages so that they still show the button and on opening the thread, the replies are still there. Would it be okay for deleted messages to still keep in store, the replies?

**Comment by zdumitru** [comment]
@lisa761 Replies should still be grouped and shown under a message that says "deleted". Each thread reply has a `tmid` and `rid` parameters that is linked to `parentMessage._id`. So this has to be used to keep the grouping.

**Comment by lisa761** [comment]
@zdumitru Alright, that would mean that we cannot completely delete the parent message so that it still retains its id, right? So would that mean just erasing the body of the message when a message with replies is deleted? and what should we do for when the show deleted messages setting is off?

**Comment by zdumitru** [comment]
> So would that mean just erasing the body of the message when a message with replies is deleted? and what should we do for when the show deleted messages setting is off?

Yes, keeping a body with a note "deleted message" would help. And then all thread replies still grouped under the blue button.

**Comment by ggazzo** [comment]
hey @lisa761 please check here `app/threads/server/hooks/afterdeletemessage.js`
```javascript
Meteor.startup(function() {
	const fn = function(message) {
		// is a reply from a thread
		if (message.tmid) {
			undoReply(message);
		}

		// is a thread
	HERE->>>	if (message.tcount) {
			Messages.removeThreadRefByThreadId(message._id);
		}

		return message;
	};

	settings.get('Threads_enabled', function(key, value) {
		if (!value) {
			callbacks.remove('afterDeleteMessage', 'threads-after-delete-message');
			return;
		}
		callbacks.add('afterDeleteMessage', fn, callbacks.priority.LOW, 'threads-after-delete-message');
	});
});
```

**Comment by lisa761** [comment]
Thanks @ggazzo and @zdumitru, I am on it

**Pull request closed without merging**
