### PR TITLE
Allow owner to delete the room

### LINKED ISSUE #1578: Allow room creator to delete that room
Currently only admins can delete rooms, but it will be nice if the person who created the room becomes like a room admin and can delete that room from the "Room Settings" tab.

In the case of the rocket chat demo server, we see many many rooms that users created mostly for testing but never used again. They cannot delete it, and it is hard for the admins to delete since they don't know if will be used in the future or not.

In production environment a group of people can start a room use it for sometime and be done with it, or they might leave it unused but they can still come back for the message history. So they are the ones who decides if the room is still needed or not. It can be added as an option in the admin settings, so the admin can allow such feature or not.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28870653-allow-room-creator-to-delete-that-room?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by peccu**
@RocketChat/core 

Closes #1578 
(already closed...)

I copied implementations from admin's' room info tab to general room's right tab can access non admin users.

This implementation allows deleting room to user who have `delete-*` permission.

can-delete
cant-delete

If you want to enable this user, you need to add these permissions to owner or user.

I think there are no owners in direct channel. We have to add `delete-d` to **user**.

permissions

### CODE REVIEW

**Comment by sampaiodiego** [comment]
I'm ok with this since there is an admin configuration allowing it.
I mean, admins should be able to enable or disable deleting rooms by owners, since them can already archive it.

**Comment by peccu** [comment]
sorry for my poor description...

I only added "DELETE" button to room info tab for non-admin user.

can-delete

I want to permit owner to delete room.

Permissions table is not relative to this PR.

**Comment by sampaiodiego** [comment]
Oh, and I'm sorry for not being that clear.
What I tried to say was: I like the feature, but we _need to create a setting_ to admins choose whether they allow owners to delete their rooms or not.

**Comment by rodrigok** [comment]
@sampaiodiego yes, so you can go the permissions page and disable that.

**Pull request merged**
