### PR TITLE
Sticky navbar in permission page

### LINKED ISSUE #7648: Do not scroll header when scrolling permissions is set
### Description:

When scrolling Permissions down it's hard to know which columns goes for which role.
Is it possible to "freeze" header line of this table for easily identify matching role?

### Server Setup Information:

* Version of Rocket.Chat Server: any
* Operating System: any
* Deployment Method(snap/docker/tar/etc): any
* Number of Running Instances: any
* DB Replicaset Oplog: n/a
* Node Version: n/a

### Steps to Reproduce:

1. Enter Administration menu
2. Enter Permissions
3. Scroll down

### Expected behavior:

Seeing header line all the time

### Actual behavior:

Header line is not visible

### PR DESCRIPTION
**Pull request by Pratyush1197**
This is to add a sticky navbar for heading in permissions page.
As in this page there are many permissions and it becomes quite confusing while we scroll down So this feature will keep the heading intact and it becomes quite easier for the user to select one of the permission.
screenshot_2019-01-26 1 rocket chat
As in the screenshot the heading bar will be present while scrolling

closes #7648

### CODE REVIEW

**Comment by ggazzo** [comment]
hey @Pratyush1197 I couldn't see any difference running your pr, are you sure its working?

**Comment by rodrigok** [comment]
@ggazzo I know you were changing this screen, does this PR is still valid?

**Comment by ggazzo** [comment]
I think so, actually, I didn't change that page yet...

**Comment by Pratyush1197** [comment]
@ggazzo yes it is still working on my machine and according to file changed it is suppose to work

**Comment by ggazzo** [comment]
@Pratyush1197 thanks for your contribution, but we made some changes(https://github.com/RocketChat/Rocket.Chat/pull/14646) and our pr got 'useless', again thanks for your time.

**Pull request closed without merging**
