### PR TITLE
[NEW] Command /hide to hide channels

### LINKED ISSUE #8239: Annoying Hide/Leave Rooms buttons - please back to previous
### Description:

New Hide/Leave Rooms buttons require 2 clicks to select each option instead 1. This is very annoying because you waste your time clicking if you have many conversations with different people each day. Everyone in my team will hate this so I can't upgrade to 0.59 if this function will work like that.. Please make it like in 0.58.* versions. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.7
* Operating System: any
* Deployment Method(snap/docker/tar/etc): any
* Number of Running Instances: ~
* DB Replicaset Oplog: ~
* Node Version: ~

### Steps to Reproduce:

1. Click "3 dots" on left side
2. Select Hide/Leave

### Expected behavior:

1. Click Hide or Leave.

### LINKED ISSUE #10713: [FEATURE] Create slash command /hide to "close" direct messages
### Description:

The slash commands `/leave` and `/part` only work on channels
The idea is to add `/hide` command to do the same as we do with the UI:

hide

### PR DESCRIPTION
**Pull request by mikaelmello**
Closes #10713
Closes #8239

Simple feature requested in #10713, when an user executes the slash command `/hide`, they hide the channel and are redirected to the homepage.

image

I've decided to redirect the user to the homepage after hiding because that is the current behavior when you hide the current room you are in using the GUI.

### CODE REVIEW

**Comment by mikaelmello** [comment]
@karlprieb @ggazzo I've been recommended to ask one of you to review it, if possible

**Comment by mikaelmello** [comment]
@ggazzo and @graywolf336, all done.

**Comment by mikaelmello** [comment]
@ggazzo Much better. I had written Hide_given_room to match the join command, but if you prefer it that way alright. About Room_doesnt_exist, it was because of direct messages.

**Comment by ggazzo** [comment]
Actually, the sentence 'Hide_given_room' is better but, we have a lot of strings, and probably we will change in the future

**Pull request merged**
