### PR TITLE
Add keywords for outgoing integrations across all public/private/direct channels

### LINKED ISSUE #3506: Integrations option to enable for all private groups in addition to all public channels
Your Rocket.Chat version: (make sure you are running the latest)
0.33.0

I'd like to be able to configure an integration to respond to all private groups in addition to all public channels. Right now if I want to enable an integration in any private group, I have to manually specify all public channels in the comma-separated list.

### LINKED ISSUE #3674: Adding an intergration for all channels and direct messages.
Your Rocket.Chat version: 0.34.0

When adding a new Outgoing WebHook Integration I don' see any way to add the integration for all channels AND all direct messages.  Is this possible?

If not I would think it would probably be beneficial to add.

### PR DESCRIPTION
**Pull request by cpitman**
@RocketChat/core 

Closes #3506
Closes #3674

This pull request adds three special keywords when adding channels to an outgoing integration: `all_public_channels`, `all_private_groups`, and `all_direct_messages`. As their names imply, each one makes an outgoing integration apply to the entire class of channels. In order to use `all_private_groups` or `all_direct_messages` a user must have the `manage-integrations` permission.

This helps apply common integrations across the board. For example, I get requests for giphy support on private channels daily. I also get frequent requests for integration support in direct messages.

All existing behavior (like when the channels are blank) is preserved. While doing this, I also factored out common logic from add and update outgoing integration into a single validation method.

### CODE REVIEW

**Comment by heynemann** [comment]
It would be really beneficial to us if this moved forward. We'd love to allow users to use bots in private channels and/or direct messages.

Anything else required here to get this PR forward?

**Comment by cpitman** [comment]
I've merge in the latest develop branch and retested, this should be ready for a merge.

**Comment by sampaiodiego** [comment]
I have some privacy concerns about this.

I find myself not being that comfortable if the admin can "see" all my messages both on private groups and 1v1 chats.

I know how frustrading it is not being able to use some integrations (like giphy) on all private rooms, but I think we should solve this using a different approach.

or maybe letting room participants know their messages can be read by sys admins.

**Comment by cpitman** [comment]
Anyone with the "manage_integrations" permission can already add an integration to any private group or direct message, without actually having access to the underlying group. So in that sense there is no security impact, since the user still has to have the same permission to use these targets. Any sys admin can also just customize rocketchat to forward them all messages.

**Comment by cpitman** [comment]
Literally, I currently maintain the same thing for my users, except I have to add each channel name to a very long list. I'm not in these channels, but RC gives administrators these permissions. This just makes RocketChat easier to administer.

**Comment by engelgabriel** [comment]
@rodrigok can you please review this and merge into develop?

**Comment by andrehp** [comment]
Hi, sorry to bother you, but is there anything missing in this pull request? Having this feature would really help in convincing people to convert from Slack to RocketChat

**Comment by shirshendu** [comment]
I would love to see this feature as well; I just started on rocketchat, and while everything else is pretty great, I found it very odd to not be able to use bots in private conversations. Found out later that everyone needs to nag an admin for being allowed something so simple. I can imagine many users just assuming that bots don't work at all in private conversations (since I almost concluded so myself, but then decided to nag an admin).

**Comment by rodrigok** [comment]
@engelgabriel can we merge this?

**Pull request merged**
