### PR TITLE
Chore: VideoConference UX/UI Refactor 1st Interaction 

### PR DESCRIPTION
**Pull request by pierre-lehnen-rc**
Given some user feedback, some changes were made to the initial design before the official release.
This pull request provides the suggested tweaks.

### CODE REVIEW

**Review by d-gubert — APPROVED** [review]
Apps-Engine related changes are ok

**Review by ggazzo — APPROVED** [review]

**Review by d-gubert — DISMISSED** [review]
\o/

**Review by dougfabris — APPROVED** [review]

**Review by dougfabris — APPROVED** [review]

**Comment by ggazzo** [comment]
QA:

**Comment by janainaCoelhoRocketchat** [comment]
just ended qa =)

**Review by ggazzo — APPROVED** [review]

**Pull request merged**
