### PR TITLE
feat: access-marketplace permission

### PR DESCRIPTION
**Pull request by yash-rajpal**
## Proposed changes (including videos or screenshots)

access-marketplace permission for marketplace section

image

## Further comments

TC-626

### CODE REVIEW

**Review by gabriellsh — CHANGES_REQUESTED** [review]
If I access the marketplace without permission, I can see the sidebar. In this case we should show the page no found.

image

**Review by gabriellsh — DISMISSED** [review]

**Review by tiagoevanp — COMMENTED** [review]
I have a question, why we are fixing permissions for admin and users only? What kind of role shouldn't be able to visit marketplace view since we are trying to expose the apps? The code looks fine to me, but I want to have better explanation about the reason for this PR to accept it... 🤔

**Review by tiagoevanp — DISMISSED** [review]

**Comment by gabriellsh** [comment]
> I have a question, why we are fixing permissions for admin and users only? What kind of role shouldn't be able to visit marketplace view since we are trying to expose the apps? The code looks fine to me, but I want to have better explanation about the reason for this PR to accept it... 🤔

We added this new permission as default for regular users, it doesn't change behaviour, but now if an admin wants to remove this permission, they can do it.

**Review by gabriellsh — APPROVED** [review]

**Review by matheusbsilva137 — APPROVED** [review]
Back-end LGTM

**Pull request merged**
