### PR TITLE
Use SoundCloud Oembed API for SoundCloud integration

### PR DESCRIPTION
**Pull request by kakawait**
Use SoundCloud Oembed API https://developers.soundcloud.com/docs/api/reference#oembed in order to support more links than previous implementation

- for track

screen shot 2015-10-23 at 09 34 31

- for user

screen shot 2015-10-23 at 09 34 41

- for group

screen shot 2015-10-23 at 09 35 08

- for set

screen shot 2015-10-23 at 09 36 33

### CODE REVIEW

**Comment by kakawait** [comment]
Related to previous implementation #1161 and should close #1090

**Comment by graywolf336** [comment]
Awesome! I will have to try this out, very nice addition

**Comment by kakawait** [comment]
@rodrigok Thanks to your new callbacks! But it can be cool to handle oEmbed protocol as defined here http://oembed.com/ to support many other provider easily (SlideShare, Vimeo, Flickr, etc).

Even rewritting YouTube to use oEmbed because today we are fetching video url (like https://www.youtube.com/watch?v=iwGFalTRHDA) 

screen shot 2015-10-23 at 09 45 37

close to 40kb to fetch and using oEmbed API

http://www.youtube.com/oembed?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DiwGFalTRHDA&format=json

screen shot 2015-10-23 at 09 46 36

Moreover create a common oEmbed API support will help to close issue like #960 

```
URL scheme: http://*.rdio.com/artist/*
URL scheme: http://*.rdio.com/people/*
API endpoint: http://www.rdio.com/api/oembed/
Documentation: http://developer.rdio.com/docs/oEmbed
Example: http://www.rdio.com/api/oembed/?format=json&url=http%3A%2F%2Fwww.rdio.com%2Fartist%2FThe_Black_Keys%2Falbum%2FBrothers%2F
```

**Comment by kakawait** [comment]
@graywolf336 Attention package is disable (comment) by default!

**Comment by graywolf336** [comment]
I'm not a core developer, so I can't merge it but I will be testing it out tomorrow (in a few hours) locally and will comment here if they haven't merged it already. :smile:

**Comment by rodrigok** [comment]
@kakawait sure we will, https://github.com/RocketChat/Rocket.Chat/issues/1218, thanks for the suggestion.

**Comment by rodrigok** [comment]
This is working fine :)

**Pull request merged**
