### PR TITLE
Added toAll mentions for yall, everyone, channel, and here

### PR DESCRIPTION
**Pull request by calebmeyer**
Requested by my team on the second day we started using rocket chat. I couldn't find any other mentions of @all but please let me know if I missed anything.

### CODE REVIEW

**Comment by engelgabriel** [comment]
Thanks for the PR. My only concern about this, is that everyone, channel, and here should have different behaviors. 

@channel will send a notification to all team members in the channel where you post the message.

@everyone notifies every member of your team. This command can only be used in the team-wide channel (usually called #general).

Both notifications will be sent to all team members in the channel whether they are active, away or offline.

@here is best for sending announcements relevant only to team members that are _currently working or available_.

Maybe we could create an issue for that.

**Comment by sampaiodiego** [comment]
agreed @engelgabriel , I think we should have different behaviors for each of this _global mentions_ ..
but for now it should better have the keywords working (even with the same behavior) for a smooth transition from other chat services.

**Comment by engelgabriel** [comment]
Ok, so lets accept the PR and open an issue for this?

**Comment by sampaiodiego** [comment]
I think it's ok.
maybe we should add the new options to autocomplete too: [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages%2Frocketchat-ui-message%2Fmessage%2Fpopup%2FmessagePopupConfig.coffee#L20)

**Comment by graywolf336** [comment]
`@channel` and `@everyone` I think should notify everyone in the channel, whether they're online or not.

`@here` I think should notify only those online in the channel it is done at

**Comment by geekgonecrazy** [comment]
> @everyone notifies every member of your team. This command can only be used in the team-wide channel (usually called #general).

Do any other platforms do this?  I've never seen this behavior.

**Comment by engelgabriel** [comment]
https://get.slack.help/hc/en-us/articles/202009646-Making-announcements

**Comment by geekgonecrazy** [comment]
@engelgabriel ah!  So we'd have to either limit it to general for now.  Or wait until we have an option to specify a lobby channel or teams.

**Comment by engelgabriel** [comment]
I am happy to accept the PR for now, if we add the new options to autocomplete. We can implement the difference later.

**Comment by calebmeyer** [comment]
@engelgabriel please let me know if 7530fb6 was what you are looking for.

**Comment by sampaiodiego** [comment]
@calebmeyer , I'm sorry, is this actually working?
I tried using "keywords" and nothing happens =\

**Comment by calebmeyer** [comment]
@sampaiodiego I don't know. I've been having trouble getting meteor installed to test.

I'll see if I can't get docker set up locally on my mac.

**Comment by sampaiodiego** [comment]
oh, so, it's not working =)
today we have 2 aliases to `@all` command, what do you think if we add the same _aliases_ to the commands you requested?

**Comment by calebmeyer** [comment]
I don't think I understand what you mean by "alias" here. If you mean that typing these things acts the same as the `@all` command, then I would be perfectly okay with that. I just want to be able to type `@everyone` and have everyone (in the current channel) notified.

**Comment by sampaiodiego** [comment]
hmm.. the _alias_ only works for the auto-complete feature:
image

if you actually sends the message with `@channel` it does nothing.

so I think it not accomplish what you want, neither this PR

**Comment by rodrigok** [comment]
I don't like a lot of options, we should have only `@all` and `@here` and use alias to help autocomplete of the other options.

**Comment by pcarn** [comment]
I like having the additional options. If you can't remember which one works, it makes it easier on the user if any of those they type can be supported.

**Comment by fduraibi** [comment]
How about adding these words to the translation files. It would make more sense to use local words than only English ;)

**Comment by marceloschmidt** [comment]
I think we should make a decision on this, so we can get it cleared either by accepting or by closing it. I vote for closing it for two reasons:
- 1 - Like @sampaiodiego said before, when you type @channel it doesn't do anything. If you type @channel and select @all from the list, it will replace for @all.
- 2 - I don't even think we should have those options to begin with... I think @all is good enough, although I agree that a few people would see a benefit in changing it to something else (but not adding more options, just replacing it).

**Comment by rodrigok** [comment]
I don't like the option to mention everyone, because we need to add everyone to the channel, this can be a mess.

We should think about a new option to send notification to everyone, like a notification inbox and allow only admins to use this feature by default.

**Comment by rodrigok** [comment]
So, my vote is for merge this PR and allow users to use all of theses options to notify users inside the channel.

**Comment by marceloschmidt** [comment]
@rodrigok do you think this PR is good as it is now, or does it need code change? as it is now, it will not notify anyone if `@channel` is typed in the message.

**Comment by rodrigok** [comment]
@marceloschmidt sorry, I thought this PR was complete and only adding alias for `@all`.

Changing my vote to **close** this PR :smile:

**Comment by sampaiodiego** [comment]
closing this since it doesn't do what it was supposed do.

**Pull request closed without merging**
