### PR TITLE
Rocket models in webhooks

### LINKED ISSUE #6336: [Q] How to access to models from outgoing webhook integration?
```
class Script {
  prepare_outgoing_request({ request }) {
    console.log(Messages.findOneByid(msgId)); //Messages is not defined
    console.log(RocketChat.models); //RocketChat is not defined
}}
```

In this case I want to find message and author of this message from outgoing request, but I can't access to models.

### PR DESCRIPTION
**Pull request by graywolf336**
@RocketChat/core 

Closes #6336

### CODE REVIEW

**Comment by sampaiodiego** [comment]
I can see integrations being broke because the way change model's functions (without any kind of control or versioning)

**Comment by graywolf336** [comment]
I think we need to list those changes inside of the `HISTORY` now, @sampaiodiego

**Comment by rodrigok** [comment]
@graywolf336 can you fix the conflict?

**Comment by graywolf336** [comment]
@rodrigok Done

**Comment by mykiep** [comment]
Are there any examples on how to access the models with outgoing and incoming webhooks?  I'm trying to use this in liue of having to make rest calls to the APIs inside of web hooks. I've tried a couple ways with no luck.

**Comment by graywolf336** [comment]
@mykiep you can use any of the models and their methods found at (except for the ones starting with an underscore: https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/rocketchat-lib/server/models

Thus to find a user you could do `Users.findOneById(userId)` to get the user's record in the database or `Rooms.findOneById(roomId` to get a room's record in the database.

**Pull request merged**
