### PR TITLE
added new rest method to update room info

### PR DESCRIPTION
**Pull request by JamesHGreen**
@RocketChat/core 

Closes #ISSUE_NUMBER

 uproom= requests.post ('http://devbox:3000/api/v1/admin.updateRoom', headers=jg, data='{"name":"Herb","topic":"bad Stuff","newName":"maddy"}') 

uproom.content
'{"_id":"mmqX23pD64HiCYcJ5","name":"maddy","t":"p","usernames":["jgreen-1","jgreen"],"msgs":0,"u":{"_id":null,"username":null},"ts":"2016-09-12T21:13:02.998Z","ro":false,"sysMes":true,"_updatedAt":"2016-09-14T23:10:05.389Z","topic":"bad Stuff"}'

### CODE REVIEW

**Comment by JamesHGreen** [comment]
allow a rest-api method to update room info.
must have admin role.

**Comment by engelgabriel** [comment]
hi @JamesHGreen can you please resolve the conflicts?

**Comment by engelgabriel** [comment]
related to https://github.com/RocketChat/Rocket.Chat/pull/4307

**Comment by JamesHGreen** [comment]
closed this opened new one under  #4576

**Pull request closed without merging**
