### PR TITLE
[FIX] Attachment download from title fixed

### LINKED ISSUE #20583: Cannot open attachments with accents
### Description:

When I send an attachment, no one can download it if the file name has an accent.

### Steps to reproduce:

1. create a document called, for instance, ánimo.txt
2. attach it to any chat
3. click on the file name (not on the tiny download arrow besides it)

### Expected behavior:

It should be opened/downloaded

### Actual behavior:

A 404 error occurs, and chat with this person becomes empty. User needs to "Reload Server" or `Ctrl + R` to see them again.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: Debian
- Deployment Method: sources
- Number of Running Instances: 1
- NodeJS Version: 12.18.2
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: Any client, both desktop and web client
- Operating System: any client, tested on windows and linux

### Additional context

It seems when clicking on the file name, it doesn't parse the URL correctly, so 
https://chat.example.com/file-upload/v2kMN5WR4d2GSeFwC/Creaci%C3%B3n%20LISTA%20en%20AC.docx which it works
it parse the URL as
https://chat.example.com/file-upload/v2kMN5WR4d2GSeFwC/Creación%20LISTA%20en%20AC.docx which doesn't works

It's a bit odd, because when I right-click on the link, it does extract the proper URL, so I could copy it, open a new tab and paste it, and it would work, but left-clicking on it, it fails
image

Which is even more odd, is if I take then the failing URL, with the accent, and paste it on a new tab, then it works... :astonished: 
image

### PR DESCRIPTION
**Pull request by yash-rajpal**
- [x] I have read the Contributing Guide
  - [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
  - [x] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  - [ ] I have added necessary documentation (if applicable)
  - [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

Added target = '_self' to attachment link, this seems to fix the problem, without this attribute, error page is displayed.

## Issue(s)

fixes #20583 #20559 
## Steps to test or reproduce

given on issue
## Further comments

fix-attachment-download-after1

### CODE REVIEW

**Comment by yash-rajpal** [comment]
@ggazzo Please Review. :)

**Comment by yash-rajpal** [comment]
Changed target to self, seems to solve the issue.

**Review by ggazzo — DISMISSED** [review]

**Review by MartinSchoeler — CHANGES_REQUESTED** [review]
Hey, could you check this Pull Request on our Electron (Desktop) app? It seems to be opening a browser window when you click on the download icon. Thanks!

**Comment by ggazzo** [comment]
try change self to blank

**Comment by yash-rajpal** [comment]
Sir, I checked both download icon and title link work fine and open in electron app only. In earlier commits, I had target as _blank but I figured keeping it as blank would open new browser window and hence I changed it to self due to this reason.
Self doesn't opens a new window. I am also attaching a gif as proof. 
download-attachment-2
Thanks @MartinSchoeler , Please review. :)

**Comment by yash-rajpal** [comment]
Actually in my testing both work fine on desktop app, so I am changing target to _blank only. Below is a gif with target set to blank.
attachment-download-3

**Review by tiagoevanp — APPROVED** [review]

**Pull request merged**
