### PR TITLE
[FIX] Strange msg when setting room announcement, topic or description to be empty

### PR DESCRIPTION
**Pull request by vynmera**
People in my team were getting confused by this, so a very simple fix for now as, looking at the code, changing it to e.g. "Room announcement removed by user" will be quite difficult:

**Before**

**After**

It looks better than just keeping that empty string there, I suppose.

### CODE REVIEW

**Comment by kaiiiiiiiii** [comment]
Why don’t we change the hole message to something like “Room announcement was removed by ...”? :)

**Comment by vynmera** [comment]
@kaiiiiiiiii I looked into that, actually. The way these messages are set up right now, it'd either be very hacky to add, or require a relatively large change in how the messages are rendered. Unless I'm missing something important...

**Comment by kaiiiiiiiii** [comment]
Aaah, totally missed that part in your PR description ... sorry 'bout that ^^'

**Comment by vynmera** [comment]
@kaiiiiiiiii Don't worry about it :-) For insight, you can see it hardcoded here: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-channel-settings/client/startup/messageTypes.js#L29

I tried to add a `message_override`, which would trigger if the new content was empty, but I couldn't get it to work, sadly (I suppose I'm still too new to this codebase). If someone else manages to do it, do tell as that'd look a lot better than both options we have right now~

**Comment by kaiiiiiiiii** [comment]
I looked into it as well and your right, it's really tricky and there should be a complete revision of the hole process to create those messages..

An ugly, but probably working solution would be:

- New messageType 'room_announcement_removed'
- Extended function call in saveRoomAnnouncement.js

`		RocketChat.models.Messages.createRoomSettingsChangedWithTypeRoomIdMessageAndUser(escapedMessage ? 'room_changed_announcement' : 'room_announcement_removed', rid, escapedMessage, user);
`

But I don't really like that idea ^^'

**Pull request merged**
