### PR TITLE
[FIX] Message Parser version upgrade

### PR DESCRIPTION
**Pull request by hugocostadev**
## Proposed changes (including videos or screenshots)

This version includes some fixes to the message-parser package about the phone number and link highlighting 

## Issue(s)

 
fix https://github.com/RocketChat/Rocket.Chat/issues/27257
fix https://github.com/RocketChat/Rocket.Chat/issues/27141
fix https://github.com/RocketChat/Rocket.Chat/issues/27065

## Further comments

TC-255
TC-250

### CODE REVIEW

**Comment by cuonghuunguyen** [comment]
can we have the option to allow all link schema? We use a lot of schema on our side

**Comment by hugocostadev** [comment]
> can we have the option to allow all link schema? We use a lot of schema on our side

Hi @cuonghuunguyen could you elaborate, please?

Currently we accept all protocol and domain schemas,  now with this PR we are enabling file path schema with this pattern: `[Label](FILE_PATH)`

**Comment by cuonghuunguyen** [comment]
do you mean without the option Allowed schemes for link?

**Comment by hugocostadev** [comment]
> do you mean without the option Allowed schemes for link?

Yes, currently these options work only with the Legacy parser, is the next releases we will make this clear and soon we will remove those options together with the legacy parser

**Review by gabriellsh — APPROVED** [review]

**Pull request merged**
