### PR TITLE
Admin option to limit group members

### PR DESCRIPTION
**Pull request by billtt**
@RocketChat/core 

Gives the admin an option to limit the number of members in private groups. Sometimes the management of an organization don't want most of the conversations happen in private groups, hence the option.

image

### CODE REVIEW

**Comment by engelgabriel** [comment]
@billtt can you please resolve the conflicts?

**Comment by billtt** [comment]
OK. I thought only the maintainers had the permission to resolve conflicts.

**Comment by billtt** [comment]
@marceloschmidt Actually I did check the limit for group creation, I just forgot to count the creator in lol

**Comment by billtt** [comment]
@marceloschmidt fixed

**Comment by rodrigok** [comment]
@billtt Can you fix the conflicts?

**Comment by rodrigok** [comment]
@billtt Let me know if you can fix the conflicts, mean while I'm moving it to the next release.

**Comment by billtt** [comment]
@rodrigok Sorry for the delay, haven't got time on this yet. Will fix this as soon as I can.

**Comment by billtt** [comment]
@rodrigok I've fixed the conflicts.

**Comment by graywolf336** [comment]
@karlprieb how hard would this be to move over to the new ui? The logic behind it is valid and pretty much ready to go, we just need to update it to reflect our new ux/ui.

**Comment by billtt** [comment]
I've fixed the conflicts, and it's updated with the new UI now.

**Comment by graywolf336** [comment]
Thanks @billtt! It has been added to the next release's milestone, so after we release v0.64 we will look into getting it added. :)

**Comment by billtt** [comment]
Thanks @graywolf336 
I may not check the thread often, so if there is anything wrong (like conflicts), please let me know.

**Comment by billtt** [comment]
I think it looks better on the switch label (the second one).

**Comment by geekgonecrazy** [comment]
Upside to the first one is less to worry about with i18n.  But the second one looks a bit better :)

**Pull request closed without merging**
