### PR TITLE
[FIX]  Login error message not obvious if user not activated

### PR DESCRIPTION
**Pull request by crazy-max**
If user is not activated and try to login, the error message says `User not found or incorrect password`. We should tell the user that his account is not activated.

### CODE REVIEW

**Comment by crazy-max** [comment]
@ggazzo @engelgabriel 

Hey guys, can you give me some feedback on this ?
We need this fix in our company :)

Thanks a lot!

**Comment by crazy-max** [comment]
Hey @sampaiodiego it's me again :smile:

Can you give me some feedback on this ?
We need this fix in our company :)

Thanks a lot!

**Comment by sampaiodiego** [comment]
thanks @crazy-max I'll talk to front-end team.

**Comment by crazy-max** [comment]
Hi @sampaiodiego what the front-end team thinks about it ? Thanks

**Comment by crazy-max** [comment]
Hey @sampaiodiego, some feedback of the front-end team ? Thx

**Pull request merged**
