### PR TITLE
[NEW] Use enter separator rather than comma in highlight preferences + Auto refresh after change highlighted words

### LINKED ISSUE #8377: [UX] [i18n] Use enter separator rather than comma in highlight preferences
Hi guys,
I want talk about this part of app:
highlight

I think it's better to use `Enter` character as a separator rather than comma in highlight preferences because comma in any language is difference for example in Arabic comma is `،` but in English is `,` so it's so difficult to use highlight feature in other language with below steps:
1. Type a word in Arabic
1. Switch keyboard layout to English
1. Type a comma
1. Switch keyboard layout to Arabic
1. Type another word

If we use `Enter` as a separator this feature can be more useful for non-English users.
I find related code here:

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui-account/client/accountPreferences.js#L156

### LINKED ISSUE #8436: [Feature] [UX] Auto refresh after change highlighted words from account preferences
Hi guys,

Now when we change highlighted words we need to refresh page manually to see result in action. I think it's better to auto refresh page after change highlighted words from account preferences exactly something like when we change language setting.

What's your opinion?
Are you agree with this?
I can create PR for this.

**/CC:** @karlprieb , @ggazzo

### PR DESCRIPTION
**Pull request by cyclops24**
@RocketChat/core 

Closes #8377 
Closes #8436 

It's an improvement for non-English users as @mnlbox said in #8377. + New auto refresh feature after change highlighted words from account preferences

### CODE REVIEW

**Comment by rodrigok** [comment]
Can you create a migration to keep old values working?

**Comment by cyclops24** [comment]
@rodrigok We don't need migration here. Because we store highlights value in DB as an array not string. See below image:


**/CC:** @ggazzo , @karlprieb

**Comment by rodrigok** [comment]
@cyclops24 Can you fix the conflict?

**Comment by rodrigok** [comment]
Can you fix the lint error?
```
/home/circleci/repo/packages/rocketchat-ui-account/client/accountPreferences.js
  3:8  error  's' is defined but never used  no-unused-vars
```

**Pull request merged**
