### PR TITLE
[WIP] [NEW] Message Reports UI

### PR DESCRIPTION
**Pull request by wreiske**
# This is a WORK IN PROGRESS.

- [X] Fix Report Dialog Thank You
- [x] Add Admin Tab Page for viewing reported messages
- [ ] Add functionality to automatically email or DM an admin when a message is reported.
- [ ] Mark report as resolved + send DM or email to the person that reported that it has been resolved.
- [ ] Other things I haven't thought of yet.

### Before
thankyou-before

### After
thankyou-after

### CODE REVIEW

**Comment by Gandalf-the-Grey** [comment]
First of all, such half-baked feature shouldn't be in UI at all if it is still WIP.
All it does right now is confusing users and moderators.

That being said, feature (when completed) would be great to have

> - [ ] Add Admin Tab Page for viewing reported messages
Agree on that. Otherwise it's useless.
Except it should be accessible by channel moderators / global moderators, not only admin.

> - [ ] Add functionality to automatically email or DM an admin when a message is reported.

Not e-mail. E-mail is more expensive in matter of resources than DM. Also DM is a bit of overkill, well designed moderation panel and notifications there would be enough.

> - [ ] Mark report as resolved + send DM or email to the person that reported that it has been resolved.

As above, not e-mail.

> Other things I haven't thought of yet.

Easily manageable UI for moderators.

**Comment by wreiske** [comment]
The report feature is in the UI (I assume) do to requirements by third-party services (like Google Play and Apple Store) that require such features. Reports have been a part of Rocket.Chat for a long time, there just has never been a UI to see them. The goal of this pull-request is to make those reports visible.

I already have the tab page for viewing reports working and ready to commit, however, I've been busy with other work related things that take precedence.

**Comment by geekgonecrazy** [comment]
Definitely don’t feel the need to blow this into something huge.  I think just having a place to view the reports is huge.  

Also if you make send DM, if they have email options setup they would get an email.  

Maybe the option could be DM role?  By default being the admin role?  Hm... if permission to view reports could actually allow set to a global moderator role 🤔

**Comment by novacrazy** [comment]
What’s the status on this?

**Comment by wreiske** [comment]
> What’s the status on this?

Work in progress. I'll have time this week to polish it up.

**Comment by marianotribuj** [comment]
Hi! I'd like to know the status on this issue. Do you think it will be merged soon? If you need hands to either test or develop something, let me know. Thanks!!

**Comment by novacrazy** [comment]
Do you think this will be finished by 2020? Would be nice to have some moderation tools this decade.

**Comment by pr0f-cha0s** [comment]
You have the box next to "Add Admin Tab Page for viewing reported messages" checked off. Where in the Administration page, and under what tab can I currently view reports?

**Comment by novacrazy** [comment]
Nine month checkup. If it were a human, it would be born by now. 

Has there been any progress on this? Are there any other Rocket devs that can work on this?

I watch all uploaded files personally to ensure there is no illegal content on my server, but imagine the other communities out there that rely on message reporting to, you know, report bad behavior to the admins/moderators. Adding the "Report message" feature without any way of actually using it was ***incredibly*** irresponsible.

**Comment by geekgonecrazy** [comment]
I know this one isn't fully complete.  But if it even has report and view.. its already better then previously.  Might be worth merging and then iterating on?

**Comment by sampaiodiego** [comment]
thanks @wreiske for the initiative in bring this up.. we've recently decided to go a path way simpler that is showing reports in pre-configured private group.. we plan to implement that by the next quarter.. so  I'll close this PR.

**Pull request closed without merging**
