### PR TITLE
[FIX] Real Name mention not including @

### PR DESCRIPTION
**Pull request by nishimaki10**
@RocketChat/core 

Prepend `@` (Use Real Name: Enable)

before
screenshot-004

after
screenshot-005

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@RocketChat/core do we want to include this? Its a very simple change, but could be UX improvement ?

**Comment by graywolf336** [comment]
I honestly think so. Real names are turned on in one of the servers I am part of and when someone mentions me, it is confusing to just see my name and not an ampersand sign.

**Comment by karlprieb** [comment]
I agree with you @geekgonecrazy @graywolf336 guys, I'll wait the build and approve that!

**Comment by karlprieb** [comment]
Ok, so should we wait and discuss before accept this PR @engelgabriel ?

**Comment by sampaiodiego** [comment]
closing this as we decided to also remove `at` sign from "regular" mentions.

**Pull request closed without merging**
