### PR TITLE
[FIX] Message-parser link issues

### PR DESCRIPTION
**Pull request by hugocostadev**
## Proposed changes (including videos or screenshots)

The changes were made in the fuselage repository. This PR just update the message-parser package version
Check the changes in this PR: 
https://github.com/RocketChat/fuselage/pull/962

## Issue(s)

fix https://github.com/RocketChat/Rocket.Chat/issues/27376
fix https://github.com/RocketChat/Rocket.Chat/issues/27484
fix https://github.com/RocketChat/Rocket.Chat/issues/26476
fix https://github.com/RocketChat/Rocket.Chat/issues/27078
fix https://github.com/RocketChat/Rocket.Chat/issues/27890

## Further comments

TC-294

### CODE REVIEW

**Review by yash-rajpal — APPROVED** [review]

**Comment by rodrigok** [comment]
@hugocostadev not sure what is going on but it's not building at all

**Comment by hugocostadev** [comment]
> @hugocostadev not sure what is going on but it's not building at all

It's a flack test, I'll update with the develop to see how it goes

**Comment by rodrigok** [comment]
@hugocostadev can you solve the flack test? I never saw a flaky test on unit tests

**Comment by Matt-something** [comment]
Links where the toplevel domain doesn't include a full stop are still broken, see [27981](https://github.com/RocketChat/Rocket.Chat/issues/27981)

**Comment by MarlynxLinux** [comment]
Test Version 6.4.5
Links are displayed incorrectly:
[test1](http://rocket.chat?text=(some_argument))

Снимок экрана от 2023-11-08 10-33-37

**Pull request merged**
