### PR TITLE
[NEW] Custom avatar shape

### PR DESCRIPTION
**Pull request by vynmera**
This PR adds the option to user settings to change the shape avatars are displayed in. By default it uses the same as we've always had (rounded square).

**User setting**

**Rounded square** (the same as original)

**Circle**

**Square**

Enjoy!

## Before we merge...
...what should the default be? I set it to the original rounded square for now, but frankly I find the circles to be _very_ good-looking. So let's leave it up to discussion: **should we change the default to circles**?

### CODE REVIEW

**Comment by kaiiiiiiiii** [comment]
I’m up for keeping the current look as a default value 👍

Nice feature btw :)

**Comment by vynmera** [comment]
@kaiiiiiiiii That would allow the PR to be merged as-is :+1: - but we've still got a full month to discuss it :)

**Comment by karlprieb** [comment]
@engelgabriel what you think about that?

**Comment by tassoevan** [comment]
While I agree that circles are cool as default, old users shouldn't get this visual after upgrade. Is it possible to differentiate old and new setups on migration, @sampaiodiego?

**Comment by vynmera** [comment]
@tassoevan Do migrations run on first setup? Otherwise we could just have a migration that sets the default back to rounded squares.

**Comment by sampaiodiego** [comment]
migrations do not run on first setup, so that could work.

IMHO we shouldn't have an option for this.. this should be a product decision and not an user/admin decision.. @thiagosanchz your input might be needed as well.

**Comment by thiagosanchz** [comment]
Hey guys! We discuss a lot about that, but the point (for now) is how companies brands working on circle avatar. I agree that is a product decision (and not a feature), so... in the next versions of our design system, we will discuss again and I'll share with you the decision.

**Comment by sampaiodiego** [comment]
Thanks @vynmera for you many contributions.. But I'll be closing this as the code is too behind now and the plans are to keep avatar rounded still.

**Pull request closed without merging**
