### PR TITLE
[FIX] Parse inline code without space before initial backtick

### LINKED ISSUE #9553: Inline code `test`/`test` not parsed correctly
### Description:

This is a very minor issue, but I've noticed it several times now, and the Rocket.Chat behaviour seems to deviate from several other Markdown interpreters I've tested.

The problem is that Rocket.Chat won't display the following Markdown code correctly:

\`test\`/\`test\`

See Steps to reproduce below. I've tried several other Markdown interpreters I've found online, and they all display it correctly:

* https://dillinger.io/
* http://markdownlivepreview.com/
* https://stackedit.io/app
* https://markdown-it.github.io/

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3
* Operating System: Debian stretch
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.3

### Steps to Reproduce:

Post this string in Rocket.Chat:

\`test\`/\`test\`

### Expected behavior:

It should be displayed like this (GitHub does it correctly):

`test`/`test`

### Actual behavior:

But instead it is displayed like this:

`test`/\`test\`

### PR DESCRIPTION
**Pull request by c0dzilla**
@RocketChat/core 

Modified regex in matching function.
Closes #9553 

Earlier:
earlier_parse

Now:
fixed_parse

### CODE REVIEW

**Comment by c0dzilla** [comment]
The test that it is failing is checking exactly what #9553 complains about.

image

Is there some reason why the regex has been written like this that I'm unaware of? Or should the test be modified?

**Comment by c0dzilla** [comment]
@geekgonecrazy is there some reason why the test is checking that inline code without initial space is not parsed?

**Comment by geekgonecrazy** [comment]
I'm not sure.  Feel free to adjust the test to test the functionality if that's not enough to fully test

**Comment by c0dzilla** [comment]
@geekgonecrazy I've modified the test.

**Pull request merged**
