### PR TITLE
[IMPROVE] Remove differentiation between public x private channels in sidebar

### PR DESCRIPTION
**Pull request by dougfabris**
### before
image

### after
image

### CODE REVIEW

**Review by gabriellsh — APPROVED** [review]

**Comment by tmartincpp** [comment]
Hi, I have seen that this we be implement starting from 3.16.

Any chance to have the old behavior as a configuration parameter ?

I'm afraid that quite a lot of users might be triggered by this change.

**Comment by milton-rucks** [comment]
@ivans-netto

**Comment by ivans-netto** [comment]
Hey @tmartincpp I am glad to have your feedback and your concern, it is very welcome.

I am designer at Rocket.Chat and would like to share with you one of the reasons behind this change.

I know that for now, it looks like it is just a change between Private x Public Channels and its goal is very abstract, but behind the scenes much is happing in Rocket.Chat's design. 
This small change will allow us to evolve the sidebar structure, little by little the concepts will be organized in a better and clear way. Rooms types, things inside rooms, all this hierarchy between concepts are in our roadmap.
However, in order to move things forward, we need to avoid over complexing things.

Have a great day 🚀

**Comment by tmartincpp** [comment]
Thanks for your answer @ivans-netto.

**Comment by teak421** [comment]
A fundamental change has been made to how it looks to our end-users and there is no way to have a configuration switch to leave the current look and feel?  PLEASE consider adding a configuration setting to leave the original behavior.

**Comment by ivans-netto** [comment]
@teak421 Thanks for asking, just clarifying, we are considering that, however on the [release 3.16.0](https://github.com/RocketChat/Rocket.Chat/pull/22485) it will go with no configuration setting to leave the other behavior.

**Comment by teak421** [comment]
@ivans-netto What the designer said above really is a great idea...but, for us Enterprise customers,  you can't just do a massive change like this without the ability for us to leave the current behavior.  Basically, the vision is great...how about simply having the ability to revert to the current 3.15 view, and then when the design has been completed, THEN you release it on us...with the ability to CHOOSE which look / feel the end-users will see.

**Comment by Redleks** [comment]
It's terrible! 
How roll back this change?! Why do you do that without some settings to turn back past view?

**Comment by EnCz** [comment]
I'm very much looking forward to a nicer and more organized way of using the sidebar but I do agree that it's very presumptuous by the rocket.chat devs to just **cut** this feature without warning. We're in a very lucky place where we don't use public rooms anyway. But if we did the pure idea to explain to 700+ people (most of them non-techie) in our instance why their public and private rooms suddenly get mixed is creepy as hell.

**Comment by AlexVonB** [comment]
Hi, just FYI, there seems to be a setting in Accounts > Default User Preferences that should be removed, too: `Merge Private Groups with Channels`:

grafik

Using 3.16.1. Best!

**Comment by Redleks** [comment]
> Hi, just FYI, there seems to be a setting in Accounts > Default User Preferences that should be removed, too: `Merge Private Groups with Channels`:
> 
> grafik
> 
> Using 3.16.1. Best!

No such setting. Version 3.16.3

**Comment by fdellwing** [comment]
I stumpled across this today and we also really hope for a setting to restore the old behavior. It's a complete mess at the moment.

**Comment by johncrisp** [comment]
Please see my comment on the original issue.

https://github.com/RocketChat/Rocket.Chat/issues/22707#issuecomment-883531211

**Comment by Redleks** [comment]
3.17.0
Still nothing. Hating so much this change...

**Comment by teak421** [comment]
I think there will be nothing until the first of the year... at least I THINK I remember reading something like this.  This is a bummer, for sure...

**Pull request merged**
