### PR TITLE
[NEW] Add shield.svg api route to generate custom shields/badges

### PR DESCRIPTION
**Pull request by alexbrazier**
@RocketChat/core 

Related to #867

Add api route to generate svg shields/badges for channels, online users and generally to join chat.

## Example badges

`/api/v1/shield.svg`
shield 4

`/api/v1/shield.svg?type=online`
shield

`/api/v1/shield.svg?type=online&name=Rocket.Chat`
shield 1

`/api/v1/shield.svg?type=channel&channel=general`
shield 3

`/api/v1/shield.svg?type=channel&name=Rocket.Chat&channel=general`
shield 2

`api/v1/shield.svg?icon=false&name=Rocket.Chat`
shield 5

## Admin Option
image

### CODE REVIEW

**Comment by graywolf336** [comment]
Maybe add some settings to enable or disable this for the private servers who don't want this enabled. Otherwise looking good

**Comment by alexbrazier** [comment]
Yeah, I was thinking it might be an issue with the online users option. Do you think it should be a setting to disable all, or just the online users one?

**Comment by graywolf336** [comment]
Maybe a setting to disable them each individually? That way it's highly configurable?

**Comment by k0nsl** [comment]
Yes, I echo the same sentiments already emitted by @graywolf336 — especially about servers which are private, but other than that? I like it!

**Comment by geekgonecrazy** [comment]
This is awesome! :+1:

**Comment by rodrigok** [comment]
This is awesome.

Can we secure that against DDOS attack? Maybe cache the count of online users for 1min, idk if it will help :)

**Comment by alexbrazier** [comment]
@rodrigok I've changed it to cache online count for 1 minute as you suggested

**Comment by rodrigok** [comment]
@graywolf336 @geekgonecrazy @marceloschmidt @sampaiodiego what do you think guys? Is that good in the code point of view?

**Comment by geekgonecrazy** [comment]
I think for github specifically this won't be too bad in terms of DDoS.

**Comment by TheReal1604** [comment]
This is really awesome, thanks for this.

**Pull request merged**
