### PR TITLE
fix: application crashing when clicking on CAS settings

### LINKED ISSUE #29301: GUI crashes after opening CAS or email settings
### Description:

The application GUI just crashed, when opening CAS(Central Authentication Service) and Email  in the settings. 
### Steps to reproduce:

1. Go to workspace
2. Click on settings
3. open CAS & also Email

### Actual behavior:

Screenshot 2023-05-20 000135

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0-develop
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version:6.0.3 

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### PR DESCRIPTION
**Pull request by jayesh-jain252**
## Proposed changes (including videos or screenshots)

Application crashed when user clicked on CAS settings (/admin/settings/CAS)

After:

image

## Issue(s)

Closes #29301 

## Further comments

The application crashed because of 

image

This issue is occurring due to special characters such as `% . :` etc in the en.i18n.json.

### CODE REVIEW

**Comment by jayesh-jain252** [comment]
@debdutdeb I have addressed this problem by escaping `% . : /` characters in this pr. However, I'm concerned that there might be other similar settings causing the same problem. Let me know if there is an alternative or more effective approach to resolving this issue.

**Comment by anikdhabal** [comment]
> @debdutdeb I have addressed this problem by escaping `% . : /` characters in this pr. However, I'm concerned that there might be other similar settings causing the same problem. Let me know if there is an alternative or more effective approach to resolving this issue.

Hey @jayesh-jain252 If possible, please make a PR that solves both issues. Email also.

**Comment by jayesh-jain252** [comment]
> Hey @jayesh-jain252 If possible, please make a PR that solves both issues. Email also.
Hi @anikdhabal to resolve the email issue, I'll need some additional information. I have already provided some details in the issue itself. You could check that out.

**Comment by hugocostadev** [comment]
The mentioned PR https://github.com/RocketChat/Rocket.Chat/pull/29289/ is the proper fix

**Pull request closed without merging**
