### PR TITLE
Ui to set default channels

### PR DESCRIPTION
**Pull request by sampaiodiego**
Closes Issue #405 .

Improved `/admin/rooms` page:
image

Added editable `default` field:
image

image

### CODE REVIEW

**Comment by AdrianoCahete** [comment]
"Default" isn't simpler with checkbox than true/false? Checked if true, unchecked if false.

**Comment by sampaiodiego** [comment]
yes, simpler but not "compatible" with the rest of the form.
I kept the same behavior to all fields.

**Comment by Brettk80** [comment]
This does seem to work on 0.45.0

**Comment by chrbo** [comment]
Hey Guys, great work! Does anybody know in which version this feature will be released?

**Comment by Rohlik** [comment]
I can´t see this option in last version of RC 0.55.0
http://imgur.com/a/dTJLv

**Comment by k0nsl** [comment]
Ditto. I was actually going a bit crazy trying to find it but then I decided to check here and luckily it wasn't just me. What happened with this option?

**Comment by DanManB** [comment]
I opened an issue for it.

**Pull request merged**
