### PR TITLE
[IMPROVE] Folder structure

### PR DESCRIPTION
**Pull request by KevLehman**
## Proposed changes (including videos or screenshots)

This is the base branch for the modifications. So far, this PR includes:
1. Move models to `server/models`
2. Move settings to `server/settings`
3. Move `app/2fa` to `services/2fa`
4. Move `app/importer*` to `services/importer/*`
5. Move `app/api` to `server/api`
6. Move `slashcommands**` to `server/services/slashcommands*`

The rest of the moves will be done on following PRs targettiing this branch.

### CODE REVIEW

**Comment by sampaiodiego** [comment]
I noticed the models are under `/server/models/models` and `/server/models/raw` .. what about if we use `/server/models/meteor` for the first one? this would also remind us it is something we need to get rid of 🙈 

can we move the content of the files under `server/settings/settingfiles/*` to file `app/lib/server/startup/settings.js` ?

should we move all the files from `app/lib/server/startup/` to `server/startup/` already? :) 

in the PR description you said you moved slash commands to `server/services/commands` but instead you moved to `server/services/messages/slashcommands/*` .. what is wrong in this case, the description or the new location? 🙈 

there are some conflicts already, can you please fix them as well? 🤗

**Comment by KevLehman** [comment]
1. I think we can move them 🤔 to `models/meteor`. That would take some time due to the amount of files importing from `models/models` 
2. I kinda like having the files that create settings in one place, with the settings service. Additionally, I was thinking in creating a task to move the contents of app/lib to a proper place (a separate one, since those files are requested everywhere, and it's easy to break something with that 😬 )
3. I think it's the same as the previous one 🙈 I don't want to mix the changes to that folder with the rest of the application, since small thing there can cause issues
4. Description is wrong, i'll update 😬 thanks for noticing that
5. Yup, I'll fix the conflicts in a sec 🎉

**Comment by sampaiodiego** [comment]
1. that would be great :D 
2. ok, makes sense
3. ok too, makes sense =)
4. great!
5. :hourglass_flowing_sand:

**Comment by KevLehman** [comment]
@sampaiodiego , conflicts were resolved! In order to avoid more conflicts between this PR and the rest of the folder structure prs, I'll move the models from `models/models` to `models/meteor` in the last PR 😬 does that sounds good to you?

**Pull request closed without merging**
