### PR TITLE
Fixups to allow running out of subdirectory

### LINKED ISSUE #335: Use Meteor.absoluteUrl() to handle being deployed on a virtual-host.com/folder/
I'm kind of struggling trying to get it working on a server name like that http://my.domain/rocket.chat/ 
More precisely, these fonts/images are trying to load from / instead of ROOT_URL : 
 * /fonts/roboto-regular-webfont.woff2 
 * /fonts/roboto-regular-webfont.woff 
 * /images/logo/favicon-16x16.png?v=3
 * /fonts/roboto-regular-webfont.ttf

Which is not *critical* but the FlowRouter does not behave as well making it impossible to use the app : 

    There is no route for the path: /rocket.chat/

is the error I get, and the meteor-timesync client is trying to use `/_timesync` too (but I managed to redirect using nginx...).

My set-up is to use the docker container and a nginx reverse proxy. 
I'm not exactly sure what to do to fix the client side... 

Regards, 

Olivier.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/24876830-use-meteor-absoluteurl-to-handle-being-deployed-on-a-virtual-host-com-folder?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1696: Run Docker image in domain / subdir
Hi Guys,

i want to run the docker image in a subdirectory of my domain, for example:

https://domainxyz.com/rocket/

On Reverse Proxy site its all fine, but what parameters i have to change on the application site? The Rocket.Chat Logo and some other things are at the moment not displayed correctly in cause of malformed links..

I tryed the following:

 sudo docker run --name rocket.chat -p 3000:3000 --env ROOT_URL=http://domainxyz.com/rocket/ --link db -d rocket.chat

Anyone has an idea?

Thx!

-> Edit: It seems all after the / in the "root_url" is not recognized. In the settings general it displays only "http://domainxyz.com" not /rocket/

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29233772-run-docker-image-in-domain-subdir?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #2401: Failed to accept video conversation when ROOT_URL set as http://domain.name/chat/rocketchat
Your Rocket.Chat version: 0.20

for some reason, I should set my Rocket.Chat instance's ROOT_URL with a path,

export ROOT_URL=http://domain.name/chat/rocketchat

In a private group, I can start a video conversation,but when other group members accept this conversation, the page go white and the browse's URL become http://domain.name/chat/rocketchat/chat/rocketchat/group/private-group.  And they can hear my voice. If I go another group or channel and then back the this private group, every thing goes right. the video can be seen and the voice can be heard.

### PR DESCRIPTION
**Pull request by rodrigok**
Improvements from #2518 

Closes #1696
Closes #335 
Closes #2401

### CODE REVIEW

**Comment by lunitic** [comment]
Any ETA for this patch?

**Comment by rodrigok** [comment]
@lunitic Will be merged after our weekly release to give us more time to test in develop

**Comment by lunitic** [comment]
@rodrigok good then I will help test it later this week

**Comment by engelgabriel** [comment]
Will probably close https://github.com/RocketChat/Rocket.Chat/issues/2655

**Pull request merged**
