### PR TITLE
[FIX] Change spread operator to Array.from for Edge browser

### LINKED ISSUE #12809: Unable to change channels in Edge using the web client.
### Description:

Changing channels will always fail in almost all builds of Microsoft Edge. The culprit is this line when exiting a room:

https://github.com/RocketChat/Rocket.Chat/blob/5ca2b8f2744f4f2eed62ec609b8f0581d262806c/packages/rocketchat-lib/client/lib/roomExit.js#L26

In every browser but Edge this will work fine, however in Edge you can't use the spread operator with a `NodeList` in certain edge (hah) cases. You can try it for yourself, open rocket chat, open the console, and paste in:

```js
const e=document.querySelector(".main-content");
[...e.children]
```

In Edge you'll get a "function expected", in all other browsers it will work. Replace `[...e.children]` with `Array.from(e.children)` and it should work as expected in all browsers.

### Steps to reproduce:

1. Join an RC server.
2. Click on a channel
3. Click on a different channel

### PR DESCRIPTION
**Pull request by ohmonster**
Closes #12809

### CODE REVIEW

**Comment by tassoevan** [comment]
I've found the same issue in `packages/rocketchat-lazy-load/client/index.js` and `packages/rocketchat-ui/client/lib/sideNav.js`. Would you mind fix them too?

**Comment by ohmonster** [comment]
and... done.

**Comment by ohmonster** [comment]
> @ohmonster can you revert the package.lock changes? It doesn't make sense since the package.json was not changed.

It snuck in. I think I got it reverted -- my git skills aren't at reflex level. So let me know.

**Comment by rodrigok** [comment]
@ohmonster that's ok, thanks 😄

**Pull request merged**
