### PR TITLE
Enable using UI name (non-dotized) of room in title

### PR DESCRIPTION
**Pull request by danischreiber**
[NEW] Add setting for using UI Real Name for rooms

### CODE REVIEW

**Comment by graywolf336** [comment]
Why is the description field on a room considered the room's real name?

**Comment by danischreiber** [comment]
Its the non slugified name. Isn't it?

On Jul 17, 2017 9:20 AM, "Bradley Hilton" <notifications@github.com> wrote:

Why is the description field on a room considered the room's real name?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RocketChat/Rocket.Chat/pull/7506#issuecomment-315675547>,
or mute the thread

**Comment by graywolf336** [comment]
Not that I'm aware of, it's text input field that allows anything to be put into it.

**Comment by danischreiber** [comment]
@graywolf336 thanks for the comments. Removed that part from the request now.

**Comment by danischreiber** [comment]
Closed this PR and opened a separate one with just the requisite changes: https://github.com/RocketChat/Rocket.Chat/pull/7520/commits/fa203fdf987e094a29e75624d4383d12df840a77

**Pull request closed without merging**
