### PR TITLE
feat: proxy avatars for Accounts_AvatarExternalProviderUrl

### PR DESCRIPTION
**Pull request by anicoa**
This PR adds the ability to proxy external avatars. Solves Issue #32812 

Internal ticket:  https://rocketchat.atlassian.net/browse/CONN-298

### CODE REVIEW

**Review by tassoevan — APPROVED** [review]

**Review by KevLehman — APPROVED** [review]

**Comment by anicoa** [comment]
@tassoevan sorry if I get it wrong. But now - as the pr is merged now -  where can i activate the proxying of the external avatar url through the rocketchat server itself?  Can't find the feature I added the pr for in the admin section anymore ;)

**Comment by tassoevan** [comment]
@anicoa We discussed internally if a setting made more sense than just **always** proxying all the avatars requests. As we didn't find any strong reasons for maintaining the old behavior, the setting was ditched while the new behavior was kept.

**Comment by anicoa** [comment]
@tassoevan thanks for clarification and work. Found this right now in the code but could not reproduce the behaviour on a fresh updated 6.12  installation. Will try/investigate and report.

**Comment by anicoa** [comment]
@tassoevan checked the functionality with one 6.12.1 and one 6.12 installation.

1. Set Accounts_AvatarExternalProviderUrl to https://www.google.com/{username}
2. Login
3. Developer-Tools show request to https://www.google.com/foobar

Anything else I have to consider?

**Comment by anicoa** [comment]
@tassoevan we tested the functionality and it's working now. Thank you very much.

We have two suggestions we would/could also solve with a pr.

a) A backend option "Prefer local stored avatars" would be good for a smooth transition and also it opens the posibility to override a centraly stored avatar.

b) Error handling would be very good fetching the avatar from external URL. In case it returns HTTP 4xx or HTTP 5xx Rocket.Chat should generate avatar by first name/last name or by username.

Would an pr solving this two cases would be welcomed?

Thanks a lot
Nico

**Pull request merged**
