### PR TITLE
[FIX] Making clicking on quoted message body redirect to original message

### LINKED ISSUE #16298: [IMPROVE] Make the quote clickable and redirect to the message that was quoted
### Description:

Currently the quote isn't clickable but the date and time right next to it redirects to the message, It would be great if clicking anywhere on the quote redirects to the message

### Steps to reproduce:

1. Quote a message
2. Try to click on the markdown box that appears

### Expected behavior:

The quoted message should be clickable

### Actual behavior:

out

### PR DESCRIPTION
**Pull request by aKn1ghtOut**
Closes #16298 

Right now, when a message is being quoted, it is added as markdown/text and doesn't redirect to the original message unless the timestamp is specifically clicked. I only realised one could click the timestamp when looking at the code.
Right now

I changed the a tag from enclosing the timestamp to enclosing the whole quote and changed some styles. This, therefore, now allows clicking on the quote itself instead of on the timestamp.
Updated

### CODE REVIEW

**Comment by gabriellsh** [comment]
After your changes, clicking a quoted attachment message reloads the page. Also I think theres no need to make any changes to the stylesheets. Could you take a look into that? Thanks for your help!

**Comment by aKn1ghtOut** [comment]
Looking into this, @gabriellsh

**Comment by aKn1ghtOut** [comment]
@gabriellsh I changes how it was being handled, and now, instead of the page url changing, it just goes to the message while on the same page.

**Comment by engelgabriel** [comment]
please see https://github.com/RocketChat/Rocket.Chat/issues/16298#issuecomment-632261740

**Comment by aKn1ghtOut** [comment]
Closing this and opening a fresh PR

**Pull request closed without merging**
