### PR TITLE
[NEW] Show full name in mentions if use full name setting enabled

### PR DESCRIPTION
**Pull request by alexbrazier**
@RocketChat/core 

Show users full name in mentions instead of username if use real name setting enabled. It will also show username if you hover over name.

### CODE REVIEW

**Comment by sampaiodiego** [comment]
I think the ideal implementation of this is like [we did](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/stream/messages.js#L50-L53) for the other real name implementation (injecting the name just before sending the message to the client) instead of save saving the name on the message object

**Comment by alexbrazier** [comment]
@sampaiodiego I have updated it as per your suggestion

**Comment by alexbrazier** [comment]
@sampaiodiego Good spot. I have updated it so that mentions change instantly when a user changes their name.

I changed notifications to use full name in #3851 
It looks like this for me
image

Does it not work for you?

**Comment by sampaiodiego** [comment]
oh sorry, I meant the mentions on notifications :grimacing:

**Comment by alexbrazier** [comment]
I've made the change to the notification mentions to use real names.

**Comment by alexbrazier** [comment]
@sampaiodiego Do you want me to make any other changes?

**Comment by sampaiodiego** [comment]
@alexbrazier nope.. looks good =)

**Comment by rodrigok** [comment]
@alexbrazier I want to merge this PR, can you fix the conflicts?

**Comment by alexbrazier** [comment]
@rodrigok Conflicts have been resolved

**Pull request merged**
