### PR TITLE
Improved Settings for Messages, Login, SideNav.

### PR DESCRIPTION
**Pull request by tgxn**
@RocketChat/core 

This pull contains a bunch of improvements mainly within the "Administration" -> "Layout" area.
- Addition of settings area for login screen.
- Addition of settings area for SideNav.

New Settings
Login_Show_PoweredBy (I'm looking for feedback on this, I'm not sure if you want the ability to disable links back to RC in the master branch)
Login_Show_Logo
SideNav_Show_Count (Will show the counts that I added in a previous pull;)

New Permissions
view-more-c-rooms (provides the "Show more channels" link)
view-more-d-rooms (provides the "Show more DMs" link)

There was some discussion in this issue from @marceloschmidt regarding these permissions.
https://github.com/RocketChat/Rocket.Chat/issues/2857

The permissions I've added only control the UI display of the "More channels" button, however I'd be happy to add restrictions around viewing the related flex for each Channels and DMs.

### CODE REVIEW

**Comment by tgxn** [comment]
There's also some settings within Message and Layout that would probably make sense to be moved under these new areas, so I may look at refactoring more of the settings if this is something you would like to address. (Making the settings more logical and clean)

**Comment by rodrigok** [comment]
@tgxn Sorry by the delay, I liked this PR, can you solve the conflicts? 

@RocketChat/core what do you think?

**Comment by graywolf336** [comment]
`Login_Show_PoweredBy` I think should be removed, that way we still get linked back to and credit provided.

Otherwise, this looks good once the conflicts are resolved. 👍

**Comment by engelgabriel** [comment]
@tgxn can you please sign our Contributor License Agreement?

**Comment by Hudell** [comment]
Since the author never signed the *Contributor License Agreement* and the code is already incompatible, I'll be closing this PR. If the agreement gets signed we can think about updating the code.

**Comment by graywolf336** [comment]
@Hudell considering this was created before we implemented the CLA, then this **should** have been treated as an exception which we did earlier ones.

**Comment by Hudell** [comment]
Ah, I wasn't aware of that.

**Pull request closed without merging**
