### PR TITLE
Client folder rocketchat-ui

### LINKED ISSUE #6046: Client files that live outside `/client` folders.
Any client-only files that do not live within a client/ folder causes meteor server to reboot rather than a client refresh. 

@rodrigok 
Related: https://github.com/RocketChat/Rocket.Chat/pull/6016#issuecomment-279896521

Packages:

### Meteor (I'm not sure we should modify these)
- [ ] meteor-accounts-saml 
- [x] meteor-autocomplete
- [x] meteor-timesync

### Rocketchat
- [x] rocketchat-autolinker
- [x] rocketchat-cas
- [x] rocketchat-colors
- [x] rocketchat-custom-oauth
- [x] rocketchat-custom-sounds # admin 
- [x] rocketchat-emoji
- [x] rocketchat-emoji-emojione
- [x] rocketchat-favico
- [x] rocketchat-highlight-words
- [ ] rocketchat-iframe-login
- [x] rocketchat-logger # antispan.js, logger.coffee
- [ ] rocketchat-markdown
- [x] rocketchat-mentions
- [x] rocketchat-slackbridge # slashcommand
- [x] rocketchat-slashcommands-archiveroom
- [x] rocketchat-slashcommands-create
- [x] rocketchat-slashcommands-invite
- [x] rocketchat-slashcommands-inviteall
- [x] rocketchat-slashcommands-join
- [x] rocketchat-slashcommands-kick
- [ ] rocketchat-slashcommands-leave # Should be split into client/server
- [x] rocketchat-slashcommands-open
- [x] rocketchat-slashcommands-topic
- [x] rocketchat-slashcommands-unarchiveroom
- [x] rocketchat-tooltip
- [x] rocketchat-ui
- [x] rocketchat-ui-account
- [x] rocketchat-ui-admin
- [x] rocketchat-ui-flextab
- [x] rocketchat-ui-login
- [x] rocketchat-ui-master # master
- [x] rocketchat-ui-message
- [x] rocketchat-webrtc
- [x] rocketchat-wordpress

I would say go through the `rocketchat-ui-` first as they'll benefit the most.

### PR DESCRIPTION
**Pull request by Kiran-Rao**
@RocketChat/core 

#6046

### CODE REVIEW

**Comment by engelgabriel** [comment]
@Kiran-Rao why did you close this? Was it wrong?

**Comment by Kiran-Rao** [comment]
@engelgabriel Didn't pass CI, was going to reopen when I had time to fix it. 

Related: #6166

**Comment by engelgabriel** [comment]
@MartinSchoeler can you help solve the CI?

**Comment by Kiran-Rao** [comment]
@engelgabriel fixed.

**Pull request merged**
