### PR TITLE
  fix: Close button of Invite friends Diaglog in Game Center

### PR DESCRIPTION
**Pull request by anikdhabal**
## Proposed changes (including videos or screenshots)

 Close button of Invite friends Diaglog in Game Center is fixed and add a cancel button.

Before:-

https://user-images.githubusercontent.com/81948346/232785961-50baccab-2dd0-461a-8a13-eaa914129393.mp4

After:-

https://user-images.githubusercontent.com/81948346/232785996-ef5302e9-b2c9-4dd6-b71a-dcf2d57e1f94.mp4

## Issue(s)

#28865 
## Steps to test or reproduce

1. Click on Game Center
2. Add friend in any game
3. Click close button in Popup Diaglog

### CODE REVIEW

**Comment by anikdhabal** [comment]
@tassoevan can you review it sir?

**Comment by anikdhabal** [comment]
@tassoevan Sir Can you review it?

**Comment by debdutdeb** [comment]
@anikdhabal why did you close this one?

**Comment by anikdhabal** [comment]
@debdutdeb here it is https://github.com/RocketChat/Rocket.Chat/pull/28986

**Pull request closed without merging**
