### PR TITLE
[NEW] Accept GIFs and SVGs for Avatars converting them to PNG and keep transparency of PNGs

### LINKED ISSUE #3766: Don't automatically convert uploaded avatar to JPEG
A suggestion: don't automatically convert uploaded avatar to JPEG — this is particularly "annoying" for those who want an animated GIF as their avatar.

### LINKED ISSUE #11230: [Bug] Avatars with transparent background get background after upload
### Description:

Users can upload pngs with transparent backgrounds as avatars. In the past, the transparency was displayed correctly. Currently, a transparent background is converted in a black one after upload. 

### Steps to reproduce:

1. Upload any png with transparent background / elements as avatar

### Expected behavior:

transparent

### Actual behavior:

rocket_chat

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.0-rc.1 (open.rocket.chat)

Tested with Chrome.

### PR DESCRIPTION
**Pull request by tassoevan**
Closes #11230 
Closes #3766

avatars

### CODE REVIEW

**Comment by rodrigok** [comment]
@tassoevan what is the difference in size (kb) of the final images? (jpeg x png)

@rafaelks is that change (from jpeg to png) ok for mobiles?

**Comment by tassoevan** [comment]
@rodrigok Using `rocketcat.png` as reference, the cropped PNG version is twice the size of the JPEG version. Using a very noisy image, PNG avatar was around seven times greater than the JPEG one. Should I test PNG compression and apply adaptative filtering?

**Comment by rafaelks** [comment]
@rodrigok We're currently requesting the avatars in **jpeg** format via mobile... will that keep working?

> "\(baseURL)/avatar/\(encodedUsername)?format=jpeg"

**Comment by rodrigok** [comment]
@tassoevan @rafaelks I would say we should only change the default background color to white and not allow avatars with transparency

**Comment by tassoevan** [comment]
I guess this was discussed before (#3766), but I see no conclusion about it.

**Comment by engelgabriel** [comment]
@tassoevan can we verify the upload format and keep the same? So rather than forcing one or the other, we can allow people to decided? PNGs for photos is BAD, and JPG for logos is also really bad.

I know that the browser can guess the image type from the file itself, but I am not sure how it would work on mobile? Maybe we can send the filetype on the http headers?

What do you guys think?

**Comment by rafaelks** [comment]
JPEG & PNG both works in mobile with no problem at all, but we should respect the `format` parameter in the query always or deprecate it.

**Comment by tassoevan** [comment]
@rafaelks I just changed the format which the avatars are _stored_. The output still converts from that format to the one requested in `format` parameter.

**Comment by rafaelks** [comment]
@tassoevan Great! So nothing should change for the mobile apps since both applications are passing the format parameter. 😊

**Comment by rodrigok** [comment]
@gabrielsixel do we want to accept avatars with transparent backgrounds?

**Comment by gabrielsixel** [comment]
@rodrigok wrong Gabriel?

**Comment by rodrigok** [comment]
@gabrielsixel ops, sorry 😄 

@engelgabriel  do we want to accept avatars with transparent backgrounds?

**Comment by tassoevan** [comment]
Better link #11202 here since there are common decisions to be made.

**Comment by crazy-max** [comment]
Any news on this ?

**Comment by ChrissW-R1** [comment]
> Any news on this ?

Another PR which will never be merged?

**Comment by engelgabriel** [comment]
We will work to keep GIFs and PNGs as they are, convert SVGs to PNGs and everything else will be converted to JPG.

**Pull request merged**
