### PR TITLE
Timkinnane pr/color fixes

### PR DESCRIPTION
**Pull request by engelgabriel**
@RocketChat/core

### CODE REVIEW

**Comment by timkinnane** [comment]
Just to update related issues to the new PR ... #2347 #1944 #2184 #3625 #3605 #4004

**Comment by timkinnane** [comment]
@engelgabriel @karlprieb - I tried pulling in #4815 as well as version 0.45.0 updates to my branch, here: https://github.com/timkinnane/rocket.chat/tree/pr/color-fixes but it doesn't work. It builds without a theme CSS file and the following build error (that I have no idea what it's related to):

```
W20161102-16:35:47.201(11)? (STDERR) TypeError: Cannot read property 'length' of undefined
W20161102-16:35:47.202(11)? (STDERR)   at SendStream.pipe (/_MYUSER_/.meteor/packages/webapp/.1.3.12.esb3px++os+web.browser+web.cordova/npm/node_modules/send/index.js:498:48)
W20161102-16:35:47.202(11)? (STDERR)   at Object.WebAppInternals.staticFilesMiddleware (/_MYPATH_/.meteor/local/build/programs/server/packages/webapp.js:433:8)
W20161102-16:35:47.203(11)? (STDERR)   at /_MYPATH_/.meteor/local/build/programs/server/packages/webapp.js:634:23
```

I think I could probably resolve this if I could understand the arcane magic of `packages/rocketchat-theme/server/server.coffee`

@engelgabriel would it be possible for you to add some comments to that file so I know what's doing what and how it's compiling the css. I have a strong feeling it could be more efficient (possibly even unit-test-able), but I don't know where to start unraveling the spaghetti.

@karlprieb, thanks for your updates. Have you tried merging in recent versions to your fork? Do you get the same errors as me, or is it something with my configuration?

I have time in the next week to help get this merged into the next release if I can get some help, which would be really great to do before it collects more conflicts again.

**Comment by karlprieb** [comment]
@timkinnane Sorry, but I didn't got any of these errors :( The only error I got is from `help.coffee`

**Comment by timkinnane** [comment]
Finally finished (I think) tweaking colors and I created a docs page! PR for that submitted too.
https://github.com/timkinnane/Rocket.Chat.Docs/tree/master/6.%20Developer%20Guides/10.%20UI%20and%20Theming/Colors

Thanks @engelgabriel for your recent changes too. I've merged them in but there's still two problems regarding settings and migrations... 

1. I wrote the migrations to create the new settings with the old values, then remove the old ones. But old settings are still visible in the admin settings pages (even after server restart) - which is really ugly because it's a long list of settings that do nothing and we've removed the translations for some of them so its just raw settings names.

2. The logic for the setting `theme-option-extended-colors` is fairly untested (afaik) and I don't really understand the rocketchat-theme server build process enough to test it. The intention is that if `theme-option-extended-colors` is enabled, it will load minor color variables from settings, otherwise it will inherit them from major colors, as defined in the [variables](https://github.com/RocketChat/Rocket.Chat/blob/timkinnane-pr/color-fixes/packages/rocketchat-theme/server/variables.coffee) file. However, I think currently it will inherit the default major color values instead of the current settings.

Help!? 👋 🤓

**Comment by timkinnane** [comment]
@engelgabriel if the minor-colors / extended-colors issue is holding things up, I had an idea that would help get this pulled in quickly, but might be controversial.

What if for now we just remove the minor/extended admin settings and force the variables to inherit from major colors (as is currently the fallback)? The effect would be less logic and complicated settings structure and a more simple palette.

Don't know if that would annoy people looking for more granular controls, but they can always set custom css overrides. Besides, the current issues with hard-coded colors prevents granular control anyway, so at least we're fixing that.

I can submit another PR for that before next week if it's acceptable - but if you'd made progress already I'm happy to wait.

**Comment by rodrigok** [comment]
@timkinnane What do you think about this solution?
captura de tela 2016-11-11 as 19 02 14

Where users can select colors or use expressions like variables?

**Comment by rodrigok** [comment]
@timkinnane I did push these changes, can you test?

**Comment by timkinnane** [comment]
Wow, that's an elegant solution. I can test tomorrow.

**Comment by timkinnane** [comment]
@rodrigok I noticed one bug, where changing from "color" to "expression" and back doesn't restore the color picker, until you change another field.

I'm trying to test more, but I'm still getting the old color settings show up. I've tried `meteor reset`, dropped mongo and rebuilt the app, restarted the server, deleted the `.meteor` folder manually and just restored the files from the repo. Where are these settings cached, I can't find them anywhere in source?

screenshot 2016-11-13 17 42 23
screenshot 2016-11-13 17 42 34

**Comment by timkinnane** [comment]
I rebuilt this morning and can't reproduce that bug with selections.

I'm all good for this to be merged in now, assuming the cached settings issue is only a problem with my local environment?

There's some follow ups to improve the admin UI (hopefully with some help from @karlprieb) but I don't want to hold this PR any further. It's an overall improvement, so we can fix the smaller issues in further PRs.

**Comment by rodrigok** [comment]
@timkinnane can you send me a list of setting that you think are in cache?

**Comment by timkinnane** [comment]
As in the screenshots above. *All* the color settings that were removed in migrations still show up (e.g. `theme-color-quaternary-font-color` etc, even `theme-options-extended-colors`). They appear with the other color settings but since the translations were removed it shows the raw setting id instead of the proper label. If this is just happening to me I'm happy to move on.

Are we otherwise happy to merge? @engelgabriel @rodrigok

**Comment by rodrigok** [comment]
@timkinnane can you try to execute in your browser's console:
```
RocketChat.CachedCollectionManager.clearAllCache()
```

Then reload the page?

**Comment by timkinnane** [comment]
Yeah that worked. Thanks @rodrigok! Is there some way to trigger that to run in the client  if the current version is not equal to the cached build?

**Comment by rodrigok** [comment]
@timkinnane sure, you can increase the cache version here https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/client/lib/cachedCollection.js?ts=2#L101

**Comment by timkinnane** [comment]
@rodrigok So just changing that to `version = 3` for this PR would ensure any client loading this version of the app for the first time will clear cache? If so, that's definitely something we should do. Can you change the PR ? It would be a lot easier than me submitting a new one.

**Comment by rodrigok** [comment]
@timkinnane Done 😄

**Comment by timkinnane** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by justinr1234** [comment]
I'd like to contribute but don't know the current state of things. Is there a todo list?

**Comment by engelgabriel** [comment]
@justinr1234 please talk to @karlprieb at the demo server.

**Pull request merged**
