### PR TITLE
check mention-all permisson with message creator rather than current …

### LINKED ISSUE #4060: Webhook integration doesn't send @all messages.
Your Rocket.Chat version: 0.37.1  (problem appeared in 0.36.0).

When trying to send message with @all tag I'm getting '{"success":false}'. Single-user tags and common messages work as before.
Changes to 'mention-all' permission does not help. (#3703)

```
$ curl -X POST --data-urlencode 'payload={"text":"@all: test"}' $WEBHOOKURL
{"success":false}
$ curl -X POST --data-urlencode 'payload={"text":" test"}' $WEBHOOKURL                                            {"success":true}
```

### PR DESCRIPTION
**Pull request by pandada8**
@RocketChat/core 

Closes #4060

check 'mention-all' permission with message creator rather than current user

### CODE REVIEW

**Comment by graywolf336** [comment]
@pandada8 can you explain why this is needed? As this is only ran before the message is saved which usually is done by the message's creator.

**Comment by pandada8** [comment]
Sorry for the late response.
the fix is about #4060, when a incoming webhook is called, the `Meteor.userId()` is undefined and failed the check, even the bot has `mention-all` permission. and also failed the webhook finally.

**Comment by graywolf336** [comment]
@rodrigok check out this fix for #4060

**Comment by rodrigok** [comment]
LGTM

**Pull request merged**
